### ISSUE TITLE
Can't find ML_Model Builder in VS 2017 - 15.9.22

### ISSUE THREAD

**Issue by MattFinlay** [dotnet/machinelearning-modelbuilder#1003]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by zewditu** [comment]
Hi @MattFinly, Thanks for reporting the issue. 
 ML.Net Model builder  is only shipped with VS  2019 for version 16.6.1 and later. Hence for your version VS2017 - 15.9.22 you have need go to the [market place]( https://marketplace.visualstudio.com/items?itemName=MLNET.07) and install it as extension.

**Comment by zewditu** [comment]
Hi @MattFinly, Thanks for reporting the issue. 
 ML.Net Model builder  is only shipped with VS  2019 for version 16.6.1 and later. Hence for your version VS2017 - 15.9.22 you have need go to the [market place]( https://marketplace.visualstudio.com/items?itemName=MLNET.07) and install it as extension.
