### ISSUE TITLE
Trailing Spaces cause error on CLI 

### ISSUE THREAD

**Issue by bizbizzz** [dotnet/machinelearning-modelbuilder#1009]
**Describe the bug**
- On which step of the process did you run into an issue:
Created sh file to run in command line, had a trailing space at the end of each mlnet regression command.

- Clear description of the problem:
After trying to run sh file in terminal, received error 'nrecognized command or argument '

**To Reproduce**
1. Make a sh file with "mlnet regression etc etc etc " command with trailing space
2. Run in terminal
3. Get error

**Expected behavior**
That it runs and ignores trailing space

**Comment by beccamc** [comment]
@bizbizzz Thanks for reporting and good find! I tried this on our latest version (16.2.0) and I wasn't able to reproduce. I put in trailing spaces and spaces between. 

![image](https://user-images.githubusercontent.com/9122518/94709016-d8fdcc80-030a-11eb-8a4f-065e83998bfe.png)


I also tried with the regression scenario. What version are you on?

**Comment by bizbizzz** [comment]
Hi! 
Sorry forgot to mention this is on mac OS. Still not working.

**Comment by beccamc** [comment]
Thanks for the context! I'll try again with mac.

**Comment by vzhuqin** [comment]
Cannot repro this issue on:

- MLNET: 16.2.0
- SDK version: 3.1.409
- macOS Catalina version: 10.15.7 (19H524)

Steps:
1. Install the SDK and MLNET according to the macOS tutorial: https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
2. Go through to the Train your model steps
3. Run command with some spaces: mlnet classification     --dataset      "yelp_labelled.txt"     --has-header false     --label-col 1          --train-time 20     --name sampleclassisifcation0526
4. Training completed without any error as below screenshot
![Screen Shot 2021-05-26 at 9 40 47 AM](https://user-images.githubusercontent.com/81727020/119590299-10276d80-be07-11eb-8f17-c5e3e0f873b0.png)

**Comment by beccamc** [comment]
@bizbizzz We can't reproduce for 16.2.0.  Can you upgrade and let us know if it you still see a problem? Thanks!

**Comment by beccamc** [comment]
No repro for this issue. Please upgrade to 16.2.0. If you still see a problem, feel free to re-open or file a new issue. Thanks!
