### ISSUE TITLE
If user overrides parsing settings ... can we pass the new settings to prose to see if they work? or some how validate it

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#1013]
If user overrides parsing settings ... can we pass the new settings to prose to see if they work? or some how validate it

**Comment by beccamc** [comment]
There are two parts to the Prose analysis. Both of these run in the DataProcessingEngine.cs file. 
1. Learn the properties of the program (using ReadFlatFileLearner). This includes column delimiter, column names, hasHeader. 
2. Learn column types - purpose and data types (using RichDataTypeDetector). 

We can't redo `#1` the ReadFlatFileLearner. These are the settings customers select and it doesn't make sense for prose to re-predict these items if the user has manually changed them. For example, if the user changes the delimiter we simply re-parse the column names. There isn't anything for prose to really predict in this case. The user has told us explicitly how to read their data, and it becomes a read problem not a predict problem. 

Prose will still help us with `#2`. There is a method in DataProcessingEngine `GetRichDataTypes(string fileName, bool hasHeader, string[] delimiter, List<string> columnNames)`.  We can pass what a customer has selected into this method and get the new column type values out. 

Things that need to be done....
1. When a parsing setting changes we need to reparse the column names. There is an example close to what will be needed in our old pre-prose [code](https://github.com/dotnet/machinelearning-tools/blob/ef65575149e1d40fa6d311881d60f56774b14f63/src/Microsoft.ML.ModelBuilder/DataSources/FileDataSource.cs#L96). 
- If HasHeader becomes false update to col0, col1, etc.
- If HasHeader becomes true or delimiter changes, parse the new column names. 
2. After getting the new column names we will need to call `DataProcessingEngine.GetRichDataTypes` again. This is currently a private method and will need to be exposed via service hub method. 
3. Re-run FileDataSource.GetAllDataAsync with the new values. 

As far as validation, if we get failures in any of the manual steps above we need to let the user know this didn't work. For example, re-parsing column names doesn't yield at least two columns. Another is re-parsing data yields a different number of column headers and column data (i.e. two column header but three columns of data). These types of errors with the delimiter seem the most likely to me. 

@JakeRadMSFT and @zewditu does this provide the info needed?

**Comment by beccamc** [comment]
I've completed item 2 above because it was needed for SQL work

- [ ] When a parsing setting changes we need to reparse the column names. There is an example close to what will be needed in our old pre-prose code.
- [ ] After getting the new column names we will need to call DataProcessingEngine.GetRichDataTypes again. This is currently a private method and will need to be exposed via service hub method.
- [ ] Re-run FileDataSource.GetAllDataAsync with the new values.

**Comment by zewditu** [comment]
@beccamc yes , hence we to have a work item for this process , is that right?

**Comment by beccamc** [comment]
@zewditu I'm not sure I'm understanding the question. Are you asking if this is your responsibility to implement or if we'll create a work item for me to pick up later?

**Comment by zewditu** [comment]
@beccamc my question was almost the second one , I think jake created . is that right @JakeRadMSFT ?

**Comment by beccamc** [comment]
This implementation is done.
