### ISSUE TITLE
The type or namespace name 'SampleClassification' could not be found 

### ISSUE THREAD

**Issue by DARKDRAGON532** [dotnet/machinelearning-modelbuilder#1014]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

`Program.cs(2,7): error CS0246: The type or namespace name 'SampleClassification' could not be found (are you missing a using directive or an assembly reference?`

**Comment by beccamc** [comment]
@DARKDRAGON532 Sorry you ran into this problem and thanks for reporting! This was from your console app? Or from the generated example console app (<YourProject>.ConsoleApp)?

**Comment by DARKDRAGON532** [comment]
my console app

**Comment by beccamc** [comment]
@DARKDRAGON532 What version of Model Builder are you using? Can you attach a copy of your sample project here for me to look at? Thanks!

**Comment by beccamc** [comment]
@DARKDRAGON532 any progress on the above questions?
