### ISSUE TITLE
How to consume the ML.Model in project in an ASP.Net .Net Framework 4.8 project in the same solution.

### ISSUE THREAD

**Issue by Darren-Wood** [dotnet/machinelearning-modelbuilder#1015]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/generate-code
Operating System: windows

Using Windows 10, Visual Studio 2019 Version 16.6.1.

The Model Builder created a ConsoleApp and ML.Model in my ASP.net Solution, but I am unable to run the Predict function because in the PredictionEngine function on the line 
ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
 it says that it can not find Microsoft.ML.FastTree or 1 of its dependencies. I can confirm they are installed. 

I tried running the console app as the starting project and it works fine in consuming the Model. 

So I think it is incompatibility between .NetFramework 4.8 and the ML.MOdel project.

Do you have any suggestions how I can overcome this?

sincerely

Darren

**Comment by Darren-Wood** [comment]
I believe this is not possible and so we are going to create a .net core webservice to consume the Model which we can then call.

**Comment by beccamc** [comment]
@Darren-Wood Sorry you ran into this problem! We do have a bug with .Net Framework 4.8. Is your project in the SDK style? We do have a work around if you don't want to create a .Net core webservice. 

![image](https://user-images.githubusercontent.com/9122518/94851542-3454bb00-03ee-11eb-9a18-c04a15ac5140.png)

**Comment by Darren-Wood** [comment]
Thank you for your answer. We are going to consume it in the Core Web.Service.
Sorry for not getting back sooner
