### ISSUE TITLE
Linux: ML.NET CLI Could not load file or assembly

### ISSUE THREAD

**Issue by roy011270** [dotnet/machinelearning-modelbuilder#1017]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: linux

I am following the ML.NET tutorial for Linux at https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train and I follow the steps but when training I got an error as mention below.

_**Could not load file or assembly 'Microsoft.ML.ModelBuilder.AutoMLService, Version=16.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.

Check out log file for more information: /home/rbabaylan/.mlnet/log.txt
Exiting ...**_

Attaching logs.
[log.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5281191/log.txt)

Thanks.

**Comment by beccamc** [comment]
@roy011270 sorry you ran into this issue! What Linux are you running and what platform is your linux running on? MLNet. CLI can't train on a 32-bit system. Is that the problem?

**Comment by roy011270** [comment]
I am training my model on a Linux ARM32 and ARM64 using a Raspberry Pi 4B.

I also tried training my model using Fedora and then the generated code run it on Raspberry Pi but the error is different **Unable to load DLL 'tensorflow' or one of its dependencies.

**Comment by LittleLittleCloud** [comment]
Looks like a dup of #994

Hi @roy011270 

Some of the libraries mlnet cli uses doesn't support arm32/64, (like tensorflow/ lightGbm) so unfortunately currently there's no way for you to run mlnet cli on arm cpu.

**Comment by roy011270** [comment]
> Looks like a dup of #994
> 
> Hi @roy011270
> 
> Some of the libraries mlnet cli uses doesn't support arm32/64, (like tensorflow/ lightGbm) so unfortunately currently there's no way for you to run mlnet cli on arm cpu.

Is there a plan for mlnet.cli to support linux-arm 32/64 in the future?

**Comment by LittleLittleCloud** [comment]
Hi @roy011270 
Sorry that I don't have an answer for that question, It depends on whether ML.Net has a plan to support Linux-arm 32/64 or not. Maybe you can create a issue in their repo.

The link to ML.Net
https://github.com/dotnet/machinelearning

**Comment by LittleLittleCloud** [comment]
close due to no response, feel free to reopen it if you have any questions
