### ISSUE TITLE
Create a Console app for Machine Learning tutorial

### ISSUE THREAD

**Issue by amysy** [dotnet/machinelearning-modelbuilder#1018]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Windows 10 Pro. Used Blend instead of the VBS19 Studio home screen to create a project. 
Creating the project from VBS Home solved the issue.

**Comment by amysy** [comment]
The Issue is resolved by creating the project from VBS home and not BLEND. 
No further action is needed.

**Comment by beccamc** [comment]
Great! Glad you were able to resolve this.
