### ISSUE TITLE
Training Results

### ISSUE THREAD

**Issue by amysy** [dotnet/machinelearning-modelbuilder#1019]
![MLTst10](https://user-images.githubusercontent.com/13893456/94329877-68f6eb80-ff84-11ea-8d99-95179679f692.PNG)
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
executed Train model commands with the defaults as shown on screengrab. But failed.

**Comment by beccamc** [comment]
Sorry you ran into this problem @amysy! Can you try training again with more time? Try 60 seconds and see if works. Thanks!

**Comment by amysy** [comment]
Hi Becca,
I tried and ran with the same 10 secs and it ran fine.
I was not able to find my issue on github and hence couldn't reply.
Best,

A.Syeda

Que Cera Cera

**Comment by amysy** [comment]
The issue resolved by rerunning after a 10 minutes break.
