### ISSUE TITLE
Azure ML Enterprise Error When Setting Up Workspace

### ISSUE THREAD

**Issue by jwood803** [dotnet/machinelearning-modelbuilder#1020]
**System Information (please complete the following information):**
 - Model Builder Version - 16.2.0.2046002
 - Visual Studio Version - 16.8.0 Preview 3.1

**Describe the bug**
When setting up a workspace for the object detection scenario, I get an error message indicating that the workspace must be an enterprise version before continuing. The workspace was just created and there is no longer an option to make it an enterprise workspace. This is preventing me from continuing creating the scenario in Model Builder.

**To Reproduce**
1. Create a new Azure ML Workspace in the Azure Portal.
2. In Model Builder, select that workspace in the Object Detection scenario when setting up the workspace.

**Screenshots**
![image](https://user-images.githubusercontent.com/1578160/94335267-5abac680-ffa8-11ea-9131-9319d11ddfe9.png)

**Additional context**
[This doc](https://docs.microsoft.com/en-us/azure/machine-learning/concept-workspace#wheres-enterprise) mentions that enterprise version of Azure ML is going away.

**Comment by beccamc** [comment]
@jwood803 sorry you ran into this issue and thank you for reporting! This was a previous requirement for Azure object detection. Azure recently changed their SKU and this is no longer necessary. 

I'm removing this check from Model Builder and will send out an update. If all goes well I hope to release the fix on Wednesday.

**Comment by hamishkeith** [comment]
This same issue also appears if you try and create a workspace using the VS GUI (object detection)

**Comment by jwood803** [comment]
Thanks for looking at this and getting a quick fix @beccamc! Looking forward to the update. 

Y'all are doing an awesome job with Model Builder! 😄

**Comment by Ezeji** [comment]
Hi @beccamc , please how soon are we expecting an update on this issue.

My team really need to ship out a product within timeline.

Thanks for the great job so far with your team.

**Comment by beccamc** [comment]
@Ezeji @jwood803 @hamishkeith Thank you for your patience on this issue! We have just shipped the fix.

FYI, the Azure ML team has a bug in object detection right now. High resolution image will cause an out of memory exception. This will be fixed in the Azure ML release on Monday. 

Let me know if you have any questions!

**Comment by hamishkeith** [comment]
thanks @beccamc !

**Comment by Ezeji** [comment]
Thanks @beccamc ... Patiently awaiting the other fix as pointed out.

**Comment by beccamc** [comment]
This should be fixed. Is anyone still experiencing problems?

**Comment by jwood803** [comment]
@beccamc This is good for me. Thanks for getting this out!

**Comment by Ezeji** [comment]
Thanks @beccamc ... Well done to your team for the great works so far.
