### ISSUE TITLE
Data Preview isn't updated, when a selected CSV file has been changed in background and the file is reselected by the user

### ISSUE THREAD

**Issue by janniksam** [dotnet/machinelearning-modelbuilder#1028]
**System Information:**
 - Model Builder Version: N/A (newest?)
 - Visual Studio Version 2019 16.7.5

**Describe the bug**

The data preview on the "Data" tab page does is not refresh, when a csv-File is changed in background and then reselected.

**To Reproduce**

1. Go to 'Data' tab page
2. Select a csv-file
3. Change the file in background
4. Select another file and then the first one again
5. The preview still shows the old preview data

**Workaround:**

It seems to be cached by the file name somehow. The preview will be updated when the changed file is renamed and the renamed file is selected.

**Expected behavior**

The preview should show the new data and it's stats (the correct count of lines etc.)

**Comment by beccamc** [comment]
@janniksam Sorry you ran into this! You are correct, for perf reasons we had a cache behind the scenes. A few notes... 

1. We use the file path for training. Even if the data preview isn't updated whatever changes you've made to the file (like adding additional lines) will be passed to ML.NET for training
2. Closing and re-opening Model Builder will reset the cache. 

I agree this is confusing. We've removed this from our code base and in our next release you won't see this problem anymore. Thank you for reporting!!

**Comment by janniksam** [comment]
Hello Becca,

although I didn't test it, I was pretty sure, that you do only use the data for preview purposes and use the updated file for the "training". Thanks for the reassurance, that it is in fact like I have expected it to be.

I mean, you don't need to remove it completely, but could also make it use a secondary criteria (e. g. the filesize), but thats just an idea, that would work for my case. (I had added a few data lines)

**Comment by beccamc** [comment]
Makes sense. We've actually almost completely redone our data processing experience, with our October release you should see more improvements than just this!
