### ISSUE TITLE
Visual Studio 2019 AI option not availavle

### ISSUE THREAD

**Issue by seliyahilal** [dotnet/machinelearning-modelbuilder#1029]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

Right-click on the myMLApp project in Solution Explorer and select Add > Machine Learning.
Option not avaivalable.
![image](https://user-images.githubusercontent.com/72309749/94994591-310c2b80-05b6-11eb-8fde-e20c17d8740e.png)

**Comment by LittleLittleCloud** [comment]
Looks like a dup of #969

Can you check if model builder is correctly installed (

**Comment by LittleLittleCloud** [comment]
close due to no response, feel free to reopen it if you have any questions
