### ISSUE TITLE
For SQL, Allow stop training when data from SQL is being downloaded to csv

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#103]
https://github.com/dotnet/machinelearning-modelbuilder/issues/17 

---
We should indicate the downloading part in the Progress window - 
"Status : Retrieving data from SQL Server"

**Comment by JakeRadMSFT** [comment]
@rustd and @iampiyusharora how do we want to show users download progress and expose the ability to cancel the download?

**Comment by briacht** [comment]
I assume he meant in the Progress section in the UI... 

Right now for files we have this:
![image](https://user-images.githubusercontent.com/10437687/69441103-04418380-0d18-11ea-87c2-6cce9c76491f.png)

Can we just put "Status: Retrieving data from SQL Server"?

If we expect this time could be long and we're able to get an estimate, we could always show it in the Output window. And user can hit "Cancel training" to stop it.

@kawilkin What do you think?

**Comment by kawilkin** [comment]
@briacht I agree. I think "Status: Retrieving data from SQL Server" with the progress spinner should be fine

**Comment by beccamc** [comment]
We aren't downloaded SQL to file anymore. @JakeRadMSFT  I'm closing this.
