### ISSUE TITLE
Not able to run first classification example

### ISSUE THREAD

**Issue by RaviBeagle** [dotnet/machinelearning-modelbuilder#1030]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: linux

rreddy78@jetson:~/dotnet_code/consumeModelApp$ mlnet classification --dataset "wikipedia-detox-250-line-data.tsv" --label-col "Sentiment" --train-time 10
Could not load file or assembly 'Microsoft.ML.ModelBuilder.AutoMLService, Version=16.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.

Check out log file for more information: /home/rreddy78/.mlnet/log.txt
Exiting ...

I have downloaded the wikipedia-detox-250-line-data.tsv from the link provided. 

I am using Jetson Nano a ARM64 computer

**Comment by beccamc** [comment]
Looks similar to https://github.com/dotnet/machinelearning-modelbuilder/issues/1017

**Comment by LittleLittleCloud** [comment]
And a dup of #994
