### ISSUE TITLE
Image Azure training - object reference not set to an instance of an object

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1033]
1. Choose Image Classification and Azure training
2. Select Subscription that does not have any ML workspaces
3. Try to refresh the Compute
4. Get error

![image](https://user-images.githubusercontent.com/10437687/95373541-02ca6c80-0892-11eb-8218-86a8fff0b276.png)

The refresh button should be disabled if no workspace is selected

**Comment by vzhuqin** [comment]
This issue can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps：
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Select "Object detection";
4. Navigate to "Environment" page, click "Set up workspace";
5. Select one subscription without ML workspaces;
6. Refresh the compute or click refresh button after "Subscription" or "Machine Learning Workspace name" or "Compute name";
7. No error prompts.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/49037e39-9a09-46ae-b64d-7d5c827d1890)
