### ISSUE TITLE
Stuck in "Finalizing..." label after training is done

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1034]
![image](https://user-images.githubusercontent.com/10437687/95374379-1de9ac00-0893-11eb-8f63-1336db01e685.png)

Should say Complete or Done or whatever text we have

**Comment by LittleLittleCloud** [comment]
A known bug for new code gen version

**Comment by LittleLittleCloud** [comment]
Hit it on the Oct release bug bash, so it might not be caused by new code gen branch

**Comment by LittleLittleCloud** [comment]
LGTM now
