### ISSUE TITLE
not toxic sentences like  "you are great" are labeled toxic

### ISSUE THREAD

**Issue by pattomatic** [dotnet/machinelearning-modelbuilder#1042]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: .NET Core SDK (3.1.402)
 - Visual Studio Version : VS2019

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
- Clear description of the problem: not toxic sentences like  "you are great" are labeled toxic

**To Reproduce**

Run the tutorial , evaluate the sentence 'you are great' - on my computer it returns toxic

**Expected behavior**
it is labeled not toxic (0)

**Screenshots**

**Additional context**

**Comment by justinormont** [comment]
This is due to https://github.com/dotnet/machinelearning-modelbuilder/issues/323

**Comment by pattomatic** [comment]
thanks
