### ISSUE TITLE
Not able to train data, Getting Error with "GPU Service not found. Falling back to CPU AutoML Service" training cancelled

### ISSUE THREAD

**Issue by Shylupink2tol** [dotnet/machinelearning-modelbuilder#1043]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
-Getting error training cancelled while trying to train data

**To Reproduce**
1. Followed the same steps mentioned in the ML.net example and when clicked on train data, got the error

**Expected behavior**
As per the example, train data should work without any error

**Comment by zewditu** [comment]
Hello,

could you get to the latest version of ML.Net Model Builder ?
If you're still seeing the problem, please let us know

**Comment by rohitguptamrt** [comment]
After updating Visual Studio to the latest ML.Net builder Still, it is throwing the same exception.

**Comment by zewditu** [comment]
HI @rohitguptamrt, sorry for hitting this error gain. Could you tell us more details about your steps to preproduce the issue that will help us to dig into it more . Are all your GPU compatibility checks are cheeked for green in Environment tab?

**Comment by JakeRadMSFT** [comment]
@rohitguptamrt in our latest versions of Model Builder we're pretty sure that error message doesn't show anymore. Is there a new error message?

Which version of Model Builder is installed?

**Comment by rohitguptamrt** [comment]
It seems it is working with the latest patch. Thank Guys.
