### ISSUE TITLE
Cannot access compute error when training for object detection

### ISSUE THREAD

**Issue by jwood803** [dotnet/machinelearning-modelbuilder#1045]
**System Information (please complete the following information):**
 - Model Builder Version: 16.2.2047901
 - Visual Studio Version: 16.8.0 Preview 3.2

**Describe the bug**
Receive the error "Cannot access compute. If using a low priority compute it may not currently be available. Try again with a dedicated compute or try again later."

**To Reproduce**
Created a new compute for the Object Detection scenario, added the data set, and clicked to train.

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/1578160/95840402-12bed200-0d12-11eb-9e22-5b3dcc17421e.png)

Selected workspace:
![image](https://user-images.githubusercontent.com/1578160/95840769-924ca100-0d12-11eb-98dd-c1cb849a4734.png)

Workspace details:
![image](https://user-images.githubusercontent.com/1578160/95839994-a3e17900-0d11-11eb-9468-d60c96eb22e8.png)

**Additional context**
I believe it's similar to #991 but I still get the error when using a dedicated compute instance.

**Comment by zewditu** [comment]
Thanks for reporting! we will look into it.

**Comment by zewditu** [comment]
Hi @jwood803, can you provide the log file to see the issue in more detail?

**Comment by jwood803** [comment]
Sure, @zewditu! I uploaded it [here](https://1drv.ms/t/s!AmAbB3zyhy6RiYEr3evjwER4NIaioQ?e=ycL0z2).

**Comment by zewditu** [comment]
Thanks @jwood803 , we will look into it.

**Comment by JakeRadMSFT** [comment]
@jwood803 unfortunately the logs are missing the inner exception that we'd need to get more information. We'll fix that in a future release.

Does it look like the compute was successfully created in the portal? Are there enough compute cores available to start the compute?

**Comment by jwood803** [comment]
@JakeRadMSFT It was successfully created, but it does show 0 nodes and 0 node count. I'm not sure if it only takes nodes when it does a run or if it needs at least one node for it to work.

![image](https://user-images.githubusercontent.com/1578160/96702197-86d72680-135f-11eb-8688-c6f97e385e6d.png)

**Comment by kasthack** [comment]
@JakeRadMSFT I'm getting the same error.

Full log: 
[37aeb4a9-72d5-4cac-8622-1551e545b7c5.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5477809/37aeb4a9-72d5-4cac-8622-1551e545b7c5.txt)
