### ISSUE TITLE
Training time finished without any models trained

### ISSUE THREAD

**Issue by prenco** [dotnet/machinelearning-modelbuilder#1046]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by y7thangeru** [comment]
This happened when i try to train the model, according to this tutorial https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
![image](https://user-images.githubusercontent.com/6522032/95955685-6ff87780-0e27-11eb-8ed9-bfb24cc81b8f.png)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 147

**Comment by y7thangeru** [comment]
It maybe because i don't have a dedicated GPU on my laptop? I was using a Leonovo Laptop with AMD A12 cpu.
If i change Time To Train into bigger numbers, like 100 seconds, i was able to get a result.
![image](https://user-images.githubusercontent.com/6522032/95956540-a5ea2b80-0e28-11eb-80a1-c96f08656515.png)

**Comment by zewditu** [comment]
Sorry you're hitting this error. 

The issue similar to issue [638](https://app.zenhub.com/workspaces/mlnet-tools-5cde1c97e3106e39e8ae08fc/issues/dotnet/machinelearning-modelbuilder/638)

**Comment by beccamc** [comment]
@y7thangeru sometimes it just needs longer training time. Were you running something else on your machine at the same time? 

@prenco Does adding more training time fix the problem?

**Comment by beccamc** [comment]
@prenco Please try adding more time. If that doesn't fix the problem feel free to re-open this issue and ping me. Thanks!
