### ISSUE TITLE
Object detection in limited scenarios.

### ISSUE THREAD

**Issue by ErikParso** [dotnet/machinelearning-modelbuilder#1047]
Hello, by this article https://devblogs.microsoft.com/dotnet/ml-net-september-updates/#object-detection-in-model-builder in ml.net version 1.5.2 it should be possible to train own model for object detection. I update ml.net packages and visual studio to latest versions, but object detection is still placed in limited scenarios section and it refers to example using existing YOLOv2 model.

**Comment by zewditu** [comment]
HI @ErikParso,  Could you get the latest version of ML.NET Model Builder from [ VS market place](https://marketplace.visualstudio.com/items?itemName=MLNET.07)

**Comment by ErikParso** [comment]
Thanks @zewditu ! I had installed this extension using Visual Studio Installer and it seems to be outdated. The version downloaded from marketplace is correct.
