### ISSUE TITLE
Update ML.NET and AutoML dependencies for each release

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#105]
We should come up with the schedule on when we want partner teams to give us the final build. Start updating from Aug release onwards

**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JakeRadMSFT** [comment]
I'm not sure why this bug exists. Let's open a bug/issue when we have a new version to update to.
