### ISSUE TITLE
Suggest to show (warning) msg to a user when they pass only a training file for multi-class, multi-label and object detection via automl-vision

### ISSUE THREAD

**Issue by love2learn-7179** [dotnet/machinelearning-modelbuilder#1055]
It's not a bug, more like a suggestion from AutoML-vision team.
When a customer just passes only training file for any of the supported tasks, it would be better to throw (warning) message saying that we do internal random split (80% for training and 20% for validation) and report metrics on those 20% validation dataset.

**Comment by beccamc** [comment]
@briacht For visibility

**Comment by beccamc** [comment]
@JakeRadMSFT and @briacht Is this for the CLI? Otherwise we need a spec and this shouldn't be listed as committed.

**Comment by beccamc** [comment]
Closing as duplicate of https://github.com/dotnet/machinelearning-modelbuilder/issues/60

**Comment by beccamc** [comment]
Please follow issue 60 for updates on specifying a test dataset.
