### ISSUE TITLE
Training using both instance and Cluster computes created in Azure portal failed.

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1057]
**Model Builder Version**:16.2.0.2047901
**Visual Studion Version**: professional 2019

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. Go to Azure Portal and create both Instance and cluster computes.
2. Select Image classification scenario in ML.Net Model Builder.
3. Select Azure on the Environment page and go to Create new Experiment dialog.
4. Select the  compute you created in the Azure portal for the Compute Name 
5. Go to the Data tab and select data
6. Go to Train tab and click the start training button.

**Expected Experience**
The training should be completed successfully 

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/e9154e56-6138-48f0-96c7-f4b9a25ac6a7)
**Additional Context**
Computes created via ML.NEt Model Builder's  Create new Experiment dialog are ok.

It seems that it is similar to  https://github.com/dotnet/machinelearning-modelbuilder/issues/1050

**Comment by zewditu** [comment]
Even if the user have both commute instance and commute clusters  type but only compute clusters are filtered in Model Builder . is that that right? @beccamc

**Comment by beccamc** [comment]
Yes that is right. We are only allowing compute clusters for training in Azure at this moment.
