### ISSUE TITLE
On first click of advanced option columns Predict Column reappears

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1058]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
On click of column features the column to predict shows up again 

![columnAppears.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/9bd52553-56a7-4103-9cf5-d09dce90fe28)

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by LittleLittleCloud** [comment]
LGTM
