### ISSUE TITLE
Add space in between words

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1059]
![image](https://user-images.githubusercontent.com/10437687/97356396-71796500-1855-11eb-9d0b-4e46234a058e.png)

Should read:

Column to predict (Label):

**Comment by beccamc** [comment]
@zewditu to confirm if this is already fixed. If it is fixed please link other issue (or fixing PR) and close this issue.

**Comment by zewditu** [comment]
Closed duplicated issue [1052](https://app.zenhub.com/workspaces/mlnet-tools-5cde1c97e3106e39e8ae08fc/issues/dotnet/machinelearning-modelbuilder/1052)
