### ISSUE TITLE
Helper text should disappear when textbox is selected

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1060]
![bb1](https://user-images.githubusercontent.com/10437687/97356861-21e76900-1856-11eb-85f3-93c8df594a4a.gif)

@romalpani to confirm

**Comment by romalpani** [comment]
@briacht you are right about the interaction. The helper text should disappear on click/focus of the text box. @zewditu can you use the standard WPF control for it? An example would be the VS search on the top bar of VS.

**Comment by romalpani** [comment]
Actually, the more accurate example is the "search box in Solution explorer". The colors on focus and disappearance of text matches that search box.

**Comment by beccamc** [comment]
This is fixed. 
![search.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/e0ca1528-40f8-4fd6-a141-7c93c7445667)
