### ISSUE TITLE
Vertical scroll bar in advance option window should be grey in dark theme

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1061]
**System Information (please complete the following information):**
 - Model Builder Version: 16.2.1.2052701
 - Visual Studio Version: 16.7

**To Reproduce**
1. choose dark theme
2. open advance window
3. vertical scroll bar is white

**Screenshots**
![image](https://user-images.githubusercontent.com/16876986/97357630-514aa580-1857-11eb-8a54-c30eec024d4e.png)

**Additional context**

**Comment by beccamc** [comment]
I'm moving this one to November release per discussion in standup

**Comment by beccamc** [comment]
No customer has reported this. Closing as low priority
