### ISSUE TITLE
Spacing on Data formatting page

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1062]
It doesn't look like there is enough vertical space. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/717fd79b-8c42-45c0-9bd8-16046683a6b4)

**Comment by zewditu** [comment]
[789](https://github.com/dotnet/machinelearning-tools/pull/789)

**Comment by beccamc** [comment]
Looks good
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/cfb0b72f-1ffe-4449-887f-2c0686f4cef7)
