### ISSUE TITLE
Changing type/purpose of columns 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1063]
Bug found by Luis: Changing a numeric column -> text in the advanced data options causes an error. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/cfcbfd59-e9db-4a86-b2c7-d87001594519)

**Comment by beccamc** [comment]
The problem here is caused by the Advanced data options only changing column **purpose**. We inform Auto ML of two things, the column purpose (including categorical) and the column type. The column type is numeric/text and is used by the Auto ML text loader. The error is being thrown by a mismatch in types passed to Auto ML. 

Xiaoyun did investigation...

[3:51 PM] Xiaoyun Zhang    https://github.com/dotnet/machinelearning/blob/f87a3bbd8adb12934dae0a0060813ce9b7500664/src/Microsoft.ML.AutoML/Utils/UserInputValidationUtil.cs#L113
​[3:52 PM] Xiaoyun Zhang
    Not this line....
https://github.com/dotnet/machinelearning/blob/f87a3bbd8adb12934dae0a0060813ce9b7500664/src/Microsoft.ML.AutoML/Utils/UserInputValidationUtil.cs#L117
So AutoML does an extra layer of examination for us and throw an error when column purpose is text but column type is not string
But the training should still fail even we remove the check because of putting a numeric column to a featurizer which only accepts string

**Bug fix:** We need to make a change that if the user changes a column purpose to numeric, we update the type to numeric (and same for text, if purpose is changed to text then type is changed to text).

**Comment by beccamc** [comment]
Other considerations. There is the following P1 in the spec:

> P1: If a user selects “Numeric” as the column purpose, but the column contains characters that are not values/numbers, then they should get a warning. 
> 
> Can do this by going through the top X amount of data and then extrapolating (so don’t have to parse through every single row – infer columns). 

I've tested and Auto ML doesn't complain when we change something from number -> text. It also doesn't complain for text -> number. I changed the Name column in the Titanic dataset to numeric. It is clearly text. There was no error thrown and the model trained successfully.

**Comment by LittleLittleCloud** [comment]
LGTM on taxi-fare-train.txt
