### ISSUE TITLE
Validate and throw data type error on "Data" step

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#1064]
**Is your feature request related to a problem? Please describe.**

When training a model and the data type is not what's expected, an error is thrown in the "Train" step telling the user they've provided the incorrect data type. This is expected and works correctly, but maybe it might make sense to throw the error in the "Data" step.

![image](https://user-images.githubusercontent.com/46974588/97367198-165c6800-187f-11eb-95d0-06d2897587f7.png)

**Describe the solution you'd like**

Validate the incorrect data type and throw error in the "Data" step, instead of "Train" so the user is able to fail faster and correct the issue ahead of time. 

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by beccamc** [comment]
This is fixed! 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/72d49f64-f392-46d7-ad64-75e21532c148)

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/96c76d5b-ffcd-4e72-8d51-d23ff68f2501)

**Comment by beccamc** [comment]
Related to https://github.com/dotnet/machinelearning-modelbuilder/issues/1063

**Comment by JakeRadMSFT** [comment]
We can use 1063 to continue track this
