### ISSUE TITLE
Vertical scroll bar in Azure  Attach dialog box should be themed 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1065]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/7c540845-0011-4e4b-b728-f826bab5aa3d)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
This has been open for 6 months with no one picking it up. I'm closing this as low priority
