### ISSUE TITLE
UI Bugs

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1066]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
## Not Aligned 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/98e96050-96b7-4182-aff9-897ea8ded0b6)
@romalpani is  this normal experience?  This is happened because we have large column name that is more than the width of the combo box. 
## Not themed 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/c986c5dd-8b22-4662-a30a-fe4eb7a64b85)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by LittleLittleCloud** [comment]
LGTM
