### ISSUE TITLE
Support more file separator formats

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#107]
Customer reported on the forum.

Model Builder does not handle correctly datatypes from csv files if Windows decimal separator etc. settings are different than en-US. Need to fix and support more different column and decimal separators in order to working with different data files. Column separator for example ; and decimal separator , as well.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by greazer** [comment]
@rustd, Is this an ML.Net AutoML issue?

**Comment by rustd** [comment]
No. The framework supports it and the tool needs to support this.

**Comment by greazer** [comment]
mlnet auto-train does infer the column separator, so the only real problem we have here is that our data preview is not doing the same inference. Once we get that right, the call to the CLI should just work.

**Comment by rustd** [comment]
Thomas mentioned that you are already working on a change in the PR for txt files.

**Comment by LittleLittleCloud** [comment]
that's what CLI used, maybe we can follow that
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.automl.columninferenceresults?view=automl-dotnet

**Comment by LittleLittleCloud** [comment]
See this [PR](https://github.com/dotnet/machinelearning-tools/pull/224)

**Comment by LittleLittleCloud** [comment]
#138

**Comment by rustd** [comment]
@LittleLittleCloud  can you please specify which separators do we support?

**Comment by LittleLittleCloud** [comment]
Sure , currently we support space , comma, tab and semicolon

**Comment by rustd** [comment]
@LittleLittleCloud can you please demo this today at the standup.
