### ISSUE TITLE
Search Text box Filter column names broken  when column  predict not selected 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1074]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/d008b8c3-c3f4-4ba6-9014-ea76a24716c4)_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
![search.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/2c0a3591-5657-4056-b59e-888afa719529)
