### ISSUE TITLE
Predicted SQL train time is way too long

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1075]
The wikipedia dataset in SQL format is predicted to take 60 minutes to train. This is way too long compared to what we used to suggest. Need to do some investigation here into the correct time. Now that we are streaming the sql data this should take less time than before

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/cc742cd3-45ae-4ed0-a3ea-b5dbc25ea0fb)

**Comment by LittleLittleCloud** [comment]
![image](https://user-images.githubusercontent.com/16876986/98164534-4d430700-1e99-11eb-8714-559602c0fa53.png)
LGTM

**Comment by justinormont** [comment]
How many models does it train? Normally it plateaus at ~120-150 models.

Ideally, we'd add early stopping to the code, which checks for the metric not improving in the last N iterations.
