### ISSUE TITLE
Change text -> numeric and evaluate is broken

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1077]
In the Titanic dataset I've changed the name column to "Numeric" instead of "Text". This trains fine, but causes a problem in evaluate tab. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/a6a2ce83-b9c1-4611-b059-717687b603ef)

**Comment by zewditu** [comment]
@beccamc I wonder which one is the bug? train without error or evaluate page error?

**Comment by beccamc** [comment]
The error on the evaluate page appears to be wrong. Investigation could prove that the training is incorrect, but this looks like a problem with evaluate. The fact that it is able to generate the code correctly shows this is probably an evaluate problem.

**Comment by beccamc** [comment]
This looks good 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/83d68747-9fe1-43c0-a9e1-d38eac139675)
