### ISSUE TITLE
File still in use in SQL data source

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1082]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. select Text classification  scenario 
2.  Select SQL data sources 
3. select your data sources 
4. change scenario  and select the same SQL data sources 

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/f8e94e6a-532a-4cb1-9e10-5df2a87a672c)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by zewditu** [comment]
In my investigation it seems that Model builder uses and  releases SQl  resources  properly but the the  dialog box we used to select sql data sources seems creating the problem. Because the exception is happened after we just select  the data sources it does not call any model builder code .

![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/56068cdd-1b4a-4ff8-b93c-c0f8f693568d)

**Comment by JakeRadMSFT** [comment]
Check if maybe we're not disposing of something with dialog?
