### ISSUE TITLE
Model Builder Error - A delimiter cannot be Nothing or an empty String

### ISSUE THREAD

**Issue by pete-oconnell** [dotnet/machinelearning-modelbuilder#1083]
When trying to add data as part of the model builder, selecting SQL as my source - as soon as I select the table name I receive the error A delimiter cannot be Nothing or an empty String.

I'm using Visual Studio 2019 and I installed ML.net via the vsix installer on the website. I've also added Microsoft.ML from Nuget as previously I had problems when working through the samples and this was the fix.

**Comment by pete-oconnell** [comment]
In addition to my issue, when I actually click the drop down on the table name, all my tables are listed as a single item.

**Comment by pete-oconnell** [comment]
I believe this issue is related to the content of the SQL table text containing new lines, I will do further testing to confirm

**Comment by LittleLittleCloud** [comment]
Thanks for the reporting
@beccamc  Can you take a look at this?

**Comment by pete-oconnell** [comment]
@beccamc I can confirm this problem is due to new lines being within the content. I've just created a new table with the same structure and put in some basic data which worked without issue. I added a 2nd row of data but with a new line and this generates the same error.

**Comment by beccamc** [comment]
@pete-oconnell Thanks for the detailed repo! I will try on my end. We just released a new version of Model Builder yesterday that includes some changes in SQL processing. It may fix the problem, I will try to reproduce on the new code.

**Comment by pete-oconnell** [comment]
> @pete-oconnell Thanks for the detailed repo! I will try on my end. We just released a new version of Model Builder yesterday that includes some changes in SQL processing. It may fix the problem, I will try to reproduce on the new code.

just tested the latest build and it appears to be fixed! :)

**Comment by beccamc** [comment]
Awesome! So happy to hear that. Let me know if you run into any other problems.
