### ISSUE TITLE
Fixed width dataset doesn't work

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1086]
Very simple single.txt dataset loads forever (it's only 10 lines so it seems to be hitting a swallowed exception) [https://app.zenhub.com/files/186917455/7d1800d2-1f72-4641-a4c5-4dd6d3c94bfb/download](https://app.zenhub.com/files/186917455/7d1800d2-1f72-4641-a4c5-4dd6d3c94bfb/download)

**Comment by zewditu** [comment]
Validated
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/bc85cfd9-c0f3-4585-8258-7e9af4959eca)
