### ISSUE TITLE
Monitor current run in Azure portal is not working

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1087]
![image](https://user-images.githubusercontent.com/16876986/98166331-1fab8d00-1e9c-11eb-815f-52eeda95d5cb.png)

![image](https://user-images.githubusercontent.com/16876986/98166411-3651e400-1e9c-11eb-92d8-de94c5d36983.png)

**Comment by beccamc** [comment]
https://github.com/dotnet/machinelearning-tools/commit/bbdd09ea9ae3a65cb093d1c691ab12010c3e332f

**Comment by zewditu** [comment]
Validated
