### ISSUE TITLE
GPU compatibility - alignment bug

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#1088]
**System Information (please complete the following information):**
 - Model Builder Version: 16.2.12055401
 - Visual Studio Version

**Describe the bug**
The compatibility check messages (success, error, warning) should be left aligned with the "Check compatibility" button.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/48927690/98166397-318d3000-1e9c-11eb-9793-1c54688e9cb6.png)

**Additional context**

**Comment by beccamc** [comment]
Pushing to next release
