### ISSUE TITLE
Spinner shows on data preview when data fails to load

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1093]
**Steps to Reproduce**
1. Select Text Classification scenario
2.On data Tab select data of having Fixed with 
3.Model builder Error shown 

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/85f8985e-9629-4617-9c20-3baa3e554c48)

**Additional Context**
After the error window is closed spinner keep continue spin.

**Comment by LittleLittleCloud** [comment]
The bug seems to be still there

**Comment by vzhuqin** [comment]
This issue not occurs on main branch:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.5
- .Net: 5.0.202

Now if the data fails to load, no spinner shows on Data Preview area.
![no spinner after fail load.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9c77753a-bc10-4c16-8002-93597e8b8b2d)
