### ISSUE TITLE
Add CONTRIBUTE.md and update README.md

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1100]

**Comment by beccamc** [comment]
Can we just remove these issues until we actually get the green light to open source?

**Comment by beccamc** [comment]
Or move them to a checklist in the Epic (e.g. close all individual issues and just have a list of things todo).  I think it's value to have this information captured, but I don't know it needs to be in individual issues until we are executing.

**Comment by LittleLittleCloud** [comment]
@beccamc  I'm OK with both ways, feel free to close it if you think this issue is too early to be created.

**Comment by beccamc** [comment]
I'm doing it!! Thanks XiaoYun!
