### ISSUE TITLE
cannot get reference to Microsft.ml

### ISSUE THREAD

**Issue by torstenbrg** [dotnet/machinelearning-modelbuilder#1101]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 1.5.0 preview2
 - Visual Studio Version (if applicable): 16.8

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**
![not found Microsft ML](https://user-images.githubusercontent.com/39350663/98812020-0d909800-2422-11eb-8079-262691074a9a.jpg)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by torstenbrg** [comment]
I am a Visual Basic user, not accustomed to C# and therefore there may well be something I have missed, even if I followed the tutorial to the letter. The model seems to have been created and the code part worked as well. Where does Microsoft.ML reside on the computer? How can I update it to version 1.5.2?

**Comment by torstenbrg** [comment]
I downloaded the 'wikipedia-detox-250-line-data.tsv.txt' and used it as data for the training.

**Comment by pete-oconnell** [comment]
@torstenbrg how did you install ML.net?

This looks similar to an issue I encountered, examples show to use .net core whereas I used .net framework when creating the project. I fixed my issue why adding Microsoft.ML via nuget and set the application to be x64.

**Comment by torstenbrg** [comment]
Thanks pete-oconnel. 

I used Visual Studio installer as per tutorial and checked the box for ML.NET. I'll try .net framework instead of .net core.

> @torstenbrg how did you install ML.net?
> 
> This looks similar to an issue I encountered, examples show to use .net core whereas I used .net framework when creating the project. I fixed my issue why adding Microsoft.ML via nuget and set the application to be x64.

**Comment by torstenbrg** [comment]
Hello Pete-OConnell,

I installed ML as instructed in the tutorial (It installs ML version 
1.5.0 preview2):

I tried to create a new project in VS 16.8.0 using .NET Framework 
instead of Core.

I have downloaded microsoft.ml.1.5.2.nupkg but when trying to install it 
(Install-Package) I get a lot of errors for missing packages:

I am a Visual Basic user and not good at all with C# or F#.

Therefore, there are probably settings that I am unaware of.

Torsten

On 2020-11-11 15:26, Pete OConnell wrote:

> @torstenbrg [1] how did you install ML.net?
> 
> This looks similar to an issue I encountered, examples show to use .net 
> core whereas I used .net framework when creating the project. I fixed 
> my issue why adding Microsoft.ML via nuget and set the application to 
> be x64.
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].


Links:
------
[1] https://github.com/torstenbrg
[2] 
https://github.com/dotnet/machinelearning-modelbuilder/issues/1101#issuecomment-725452647
[3]

**Comment by torstenbrg** [comment]
Hello @pete-oconnell ,

I installed ML as instructed in the tutorial (It installs ML version 1.5.0 preview2):
![Install ML](https://user-images.githubusercontent.com/39350663/98917247-6ddc1400-24cc-11eb-8a73-82b98543d8e6.jpg)

I tried to create a new project in VS 16.8.0 using .NET Framework instead of Core. 
I have downloaded microsoft.ml.1.5.2.nupkg but when trying to install it (Install-Package) I get a lot of errors for missing packages:


![Install nupkg](https://user-images.githubusercontent.com/39350663/98917315-80564d80-24cc-11eb-83ad-59125437ba87.jpg)



I am a Visual Basic user and not good at all with C# or F#.
Therefore, there are probably settings that I am unaware of.

**Comment by torstenbrg** [comment]
![Install ML from nuget org](https://user-images.githubusercontent.com/39350663/98919109-bd234400-24ce-11eb-96f5-5c0bb29ed3fb.jpg)

**Comment by torstenbrg** [comment]
Trying with VS CLI:
C:\ML.NET\ML\FrameworkMLML.ConsoleApp>**dotnet add package Microsoft.ML --version 1.5.2**
  Determining projects to restore...
  Writing C:\Users\torst\AppData\Local\Temp\tmpC13A.tmp
info : Adding PackageReference for package 'Microsoft.ML' into project 'C:\ML.NET\ML\FrameworkMLML.ConsoleApp\FrameworkMLML.ConsoleApp.csproj'.
info : Restoring packages for C:\ML.NET\ML\FrameworkMLML.ConsoleApp\FrameworkMLML.ConsoleApp.csproj...
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.CpuMath'&semVerLevel=2.0.0
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.DataView'&semVerLevel=2.0.0
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='System.CodeDom'&semVerLevel=2.0.0
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='System.Threading.Channels'&semVerLevel=2.0.0
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='System.CodeDom'&semVerLevel=2.0.0 734ms
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0 737ms
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.CpuMath'&semVerLevel=2.0.0 864ms
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.DataView'&semVerLevel=2.0.0 743ms
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='System.Threading.Channels'&semVerLevel=2.0.0 696ms
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/packages/FindPackagesById()?id='System.Threading.Channels'&semVerLevel=2.0.0'.
log  : Response status code does not indicate success: 404 (Not Found).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/packages/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0'.
log  : Response status code does not indicate success: 404 (Not Found).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/packages/FindPackagesById()?id='System.CodeDom'&semVerLevel=2.0.0'.
log  : Response status code does not indicate success: 404 (Not Found).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.DataView'&semVerLevel=2.0.0'.
log  : Response status code does not indicate success: 404 (Not Found).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.CpuMath'&semVerLevel=2.0.0'.
log  : Response status code does not indicate success: 404 (Not Found).
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='System.CodeDom'&semVerLevel=2.0.0
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='System.Threading.Channels'&semVerLevel=2.0.0
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.DataView'&semVerLevel=2.0.0
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.CpuMath'&semVerLevel=2.0.0
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0 445ms
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='System.CodeDom'&semVerLevel=2.0.0 457ms
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/packages/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0'.
log  : Response status code does not indicate success: 404 (Not Found).
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.CpuMath'&semVerLevel=2.0.0 453ms
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='System.Threading.Channels'&semVerLevel=2.0.0 454ms
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/packages/FindPackagesById()?id='System.CodeDom'&semVerLevel=2.0.0'.
log  : Response status code does not indicate success: 404 (Not Found).
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.DataView'&semVerLevel=2.0.0 463ms
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.CpuMath'&semVerLevel=2.0.0'.
log  : Response status code does not indicate success: 404 (Not Found).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/packages/FindPackagesById()?id='System.Threading.Channels'&semVerLevel=2.0.0'.
log  : Response status code does not indicate success: 404 (Not Found).
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='System.CodeDom'&semVerLevel=2.0.0
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.DataView'&semVerLevel=2.0.0'.
log  : Response status code does not indicate success: 404 (Not Found).
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.CpuMath'&semVerLevel=2.0.0
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='System.Threading.Channels'&semVerLevel=2.0.0
info :   GET https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.DataView'&semVerLevel=2.0.0
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='System.CodeDom'&semVerLevel=2.0.0 151ms
error: Failed to retrieve information about 'System.CodeDom' from remote source 'https://www.nuget.org/packages/FindPackagesById()?id='System.CodeDom'&semVerLevel=2.0.0'.
error:   Response status code does not indicate success: 404 (Not Found).
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='System.Threading.Channels'&semVerLevel=2.0.0 215ms
info :   NotFound https://www.nuget.org/packages/FindPackagesById()?id='Microsoft.ML.CpuMath'&semVerLevel=2.0.0 217ms


Usage: NuGet.CommandLine.XPlat.dll package add [options]

**Comment by beccamc** [comment]
@torstenbrg Thanks for reporting this problem. 

1. In the first project you tried, what version of .Net Core were you using?
2. In the new project, what version of .Net Framework are you using? 

Thanks!

**Comment by torstenbrg** [comment]
Hello Becca,

In both projects I have used VS 16.8 with versions of components that 
came with that installation, as per below:

Microsoft Visual Studio Community 2019
Version 16.8.0
VisualStudio.16.Release/16.8.0+30709.132
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019 00435-60000-00000-AA370
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019 16.8.550.19892
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services 
16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019 16.8.550.19892
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0 16.8.550.19892
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools 16.8.550.19892
Azure Functions and Web Jobs Tools

C# Tools 3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa
C# components used in the IDE. Depending on your project type and 
settings, a different version of the compiler may be used.

Common Azure Tools 1.10
Provides common services for use by Azure Mobile Services and Microsoft 
Azure Tools.

IntelliCode Extension 1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools 2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio 0.4
Simplifying the configuration of Azure DevOps pipelines from within the 
Visual Studio IDE.

Microsoft JVM Debugger 1.0
Provides support for connecting the Visual Studio debugger to JDWP 
compatible Java Virtual Machines

Microsoft Library Manager 2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger 1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards 1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers 1.1
Develop, run, validate your ASP.NET Core applications in the target 
environment. F5 your application directly into a container with 
debugging, or CTRL + F5 to edit & refresh your app without having to 
rebuild the container.

Microsoft Visual Studio VC Package 1.0
Microsoft Visual Studio VC Package

NuGet Package Manager 5.8.0
NuGet Package Manager in Visual Studio. For more information about 
NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio 16.0.30502.00
Microsoft Office Developer Tools for Visual Studio

ProjectServicesPackage Extension 1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools 16.0.62010.06180
Microsoft SQL Server Data Tools

TypeScript Tools 16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools 
3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa
Visual Basic components used in the IDE. Depending on your project type 
and settings, a different version of the compiler may be used.

Visual F# Tools 
16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package 1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual 
Studio

Visual Studio Container Tools Extensions 1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers 1.0
Visual Studio Tools for Containers

Workflow Manager Tools 1.0 1.0
This package contains the necessary Visual Studio integration components 
for Workflow Manager.

Thank you for your interest.

Torsten

On 2020-11-24 19:16, Becca McHenry wrote:

> @torstenbrg [1] Thanks for reporting this problem.
> 
> * In the first project you tried, what version of .Net Core were you 
> using?
> * In the new project, what version of .Net Framework are you using?
> 
> Thanks!
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].


Links:
------
[1] https://github.com/torstenbrg
[2] 
https://github.com/dotnet/machinelearning-modelbuilder/issues/1101#issuecomment-733151369
[3]

**Comment by beccamc** [comment]
Thanks for the info @torstenbrg!

Can you check something else for me? Open the .csproj file for the projects you tried (double click from solution explorer or use Go To File). What is the TargetFramework for each project?
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/905b59d8-79cd-4592-95bd-735bcd39b5b5)

**Comment by torstenbrg** [comment]
Hello Becca,

Thanks for your engagement.

I am sorry you make you disappointed but I have scrapped both test 
projects and cannot give you what you ask for.

Torsten

On 2020-12-01 19:08, Becca McHenry wrote:

> Thanks for the info @torstenbrg [1]!
> 
> Can you check something else for me? Open the .csproj file for the 
> projects you tried (double click from solution explorer or use Go To 
> File). What is the TargetFramework for each project?
> [2]
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].


Links:
------
[1] https://github.com/torstenbrg
[2] 
https://camo.githubusercontent.com/f793ae06d1aaef56c410edc13a040f611ed4bd2c068fb2f11f8b5c1005e7c7e3/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564353563336436386661633834303030313331346561612f39303562353964382d373963642d343539322d393562642d373335626364333962356235
[3] 
https://github.com/dotnet/machinelearning-modelbuilder/issues/1101#issuecomment-736725573
[4]

**Comment by beccamc** [comment]
@torstenbrg Sorry for the long delay here. Were you able to get it working with another project? Are you running into any other problem?

**Comment by beccamc** [comment]
@torstenbrg If you need help getting started on a new project please re-open and @ mention me. Thanks for your engagement!
