### ISSUE TITLE
Enable the service hub services to know the language used in VS 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1103]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
String in resources files in the the service hub services are  not localized  because  the service hub services is not detected the language change in visual studio rather it is based on system language.  

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
@zewditu What is there to validate here? I thought this wasn't working.

**Comment by zewditu** [comment]
Related issue https://github.com/dotnet/machinelearning-modelbuilder/issues/1092

**Comment by beccamc** [comment]
Closing this as the validation comes with #1092
