### ISSUE TITLE
Download ML.NET model builder on Mac doesn't install the model builder on my machine

### ISSUE THREAD

**Issue by arkeetect** [dotnet/machinelearning-modelbuilder#1106]
**System Information (please complete the following information):**
 - MacBook Pro (Retina, 13-inch, Mid 2014)
 - macOS 10.14.5 (18F132) Mohave
 - Model Builder or CLI Version: ML.NET Model Builder (Preview)
 - Visual Studio Version (if applicable): Visual Studio 2019 for Mac version 8.8 (November 10, 2020 release)

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet/model-builder
- Clear description of the problem: 
On Macbook Pro, click on Download 
Takes you to download for Mac page.
Click on Download button.
Downloads a VSIX file.
Can't do anything with that file on Visual Studio 2019 for Mac version 8.8 (running on MacBook Pro). 

**To Reproduce**
1. Go to 'https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet/model-builder'
2. On Macbook Pro, click on Download 
3. Downloads a VSIX file.

**Expected behavior**
Should be able to Add Machine Learning from right click Add on a project in VS 2019 for Mac 8.8

**Screenshots**

**Additional context**

**Comment by JakeRadMSFT** [comment]
Thanks for reaching out. Model Builder is only available for Windows version of Visual Studio.

The ML.NET CLI is available for MacOS use and the tutorial can be found here:
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/intro

You may have to chose MacOS if it isn't automatically detected in the tutorial.

**Comment by beccamc** [comment]
If this is still a problem, please go to https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install and choose "macOS". Sorry for the confusion. 

cc: @briacht and @luisquintanilla FYI, confusing that the [main page](https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet/model-builder) download button goes the VS Marketplace page.

**Comment by lindsaydemarchi** [comment]
Checking again in 2022-- are there plans to make this available in Visual Studio for Mac?

**Comment by beccamc** [comment]
I don't think Visual Studio for Mac support is in our current roadmap. cc @luisquintanilla

**Comment by luisquintanilla** [comment]
Hi @lindsaydemarchi 

At this time there are no plans to bring Model Builder to VS for Mac. As an alternative though we encourage you to use the ML.NET CLI for non-Windows environments. 

https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-ml-net-cli?tabs=mac

**Comment by ramzzzay** [comment]
I'm here to say: "bring Model Builder to VS for Mac" are very welcome. Especially on Apple Silicon Mac. 👀
