### ISSUE TITLE
Remove limit for SQL server of 10,000 rows and add warning when downloading large SQL tables

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#111]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by greazer** [comment]
@zewditu, how is this issue different than #17? Please specify the details in the description of the bug.

**Comment by rustd** [comment]
If connecting to greater than SQL database (>1 GB) add a Yes/ No information prompt (similar to the training time prompt) with the following message. Add telemetry tracking how many users are clicking yes or no.

"Start training will download 2 GB of data from your SQL Server to this machine. Training will start once the data is downloaded. This might take some time. Would you like to continue anyway?"

**Comment by zewditu** [comment]
@greazer  issue #17 is just removing text from the UI
