### ISSUE TITLE
           This line of code is getting a build error. MLNetModel is showing a "cannot find file path" in build errors. I went to properties, build, build path and went to the model folder. Still it says "Cannot find file". ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var modelInputSchema);  

### ISSUE THREAD

**Issue by BrittanyPruneau** [dotnet/machinelearning-modelbuilder#1112]
**System Information (please complete the following information):**
 - Model Builder or CLI Version:  Model Builder
 - Visual Studio Version (if applicable):   2019

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):  Generate Code 
- Clear description of the problem:
I replace the code in program.cs with the code specified on the Consume Your Model page. When I ran it, first I needed to change the using statement because I named my folder something other than MyMLApp. The using statement is now correct. The build path is incorrect. MLNetModelPath is lost
           This line of code is getting a build error. MLNetModel is showing a "cannot find file path" in build errors. I went to properties, build, build path and went to the model folder. Still it says "Cannot find file". ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var modelInputSchema);  

![error](https://user-images.githubusercontent.com/69804752/99737733-1e768480-2a86-11eb-82e7-4a96127d9bc2.JPG)

**Comment by beccamc** [comment]
@BrittanyPruneau Sorry you ran into this problem and thanks for reporting! Can you tell me your project version? Are you using .Net Framework of .Net Core?

**Comment by BrittanyPruneau** [comment]
I actually ran it in both .netframework and .net core

________________________________

**Comment by beccamc** [comment]
@BrittanyPruneau So sorry for the long delay here. Are you still having a problem?

**Comment by beccamc** [comment]
If this is still a problem (or you need help getting started) please re-open and @ mention me. Thanks!
