### ISSUE TITLE
Creating New Azure Machine Learning Workspace

### ISSUE THREAD

**Issue by Aamirkhan10218** [dotnet/machinelearning-modelbuilder#1113]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
@Aamirkhan10218 sorry you ran into this problem! Can I get more details? Is your issue similar to this https://github.com/dotnet/machinelearning-modelbuilder/issues/1104?

**Comment by beccamc** [comment]
Not enough information to investigate. @Aamirkhan10218 please let me know if this is still an issue!
