### ISSUE TITLE
local classification

### ISSUE THREAD

**Issue by masgh021** [dotnet/machinelearning-modelbuilder#1121]
model builder in classification scenario start training But:
 stop at 30mbyte downloaded of this model  file:
resnet_v2_50_299.meta: Downloaded 302616931 bytes out of 202616931
image==>>   https://pasteboard.co/JCptMpL.png

and not going to forward .
and say this error :
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Error] resnet_v2_50_299.meta: Download timed out.

I try many times but training process stop in this step.
what should i do ???

**Comment by LittleLittleCloud** [comment]
Hi @masgh021 

Sorry for the late reply,,  if the download is keeping failing, you can manually download resnet pretrain model from this link
```
https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta
```

And put it under this path %temp%\MLNET\

Then you should be good to go

**Comment by masgh021** [comment]
@LittleLittleCloud 
thank you it works .

**Comment by f-quintero** [comment]
> @LittleLittleCloud
> thank you it works .

Hi, can you share the file? the link is broken.
