### ISSUE TITLE
Section 508 502.3.1: (devenv/edit '') The Name property of a focusable element must not be null.

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1122]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #Benchmark; #Visual Studio; #A11yAuto; #WCAG4.2.1;

### Environment Details:
Microsoft Visual Studio 2019 Preview Version 16.8.0 preview 6.0

### Repro Steps:

1.Open Visual Studio Enterprise 2019 Preview 
2. Create a new .Net Core Console App (C#) 
3. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
4. Tab till "Object Detection" scenario and select the scenario
5. Tab till "Set up work Space" button and press enter
6. Run Accessibility Insights for Windows and Verify whether Name is given for the combo boxes and buttons present in the window

### App: 
devenv

### Element path:
 edit ''

### Issue Details: 
The Name property of a focusable element must not be null. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

### How To Fix: 
Provide a UI Automation Name property that concisely identifies the element.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

![1122_ML  Net model builder_name property is null](https://user-images.githubusercontent.com/51435580/100615356-7f7f4180-333d-11eb-95aa-ff408cee49ac.png)

**Comment by zewditu** [comment]
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/234c075a-70e2-4d60-be1a-38bb5a075fe4)

**Comment by SaisreeDandamudi** [comment]
@zewditu @beccamc 
Verified the bug in the latest build and the issue still re-pros.
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 4.0
![Screenshot (74)](https://user-images.githubusercontent.com/51435580/108485732-41057d00-72c3-11eb-9423-1f3aeaa03233.png)

**Comment by beccamc** [comment]
Removing the ready to review tag until we have a build for all of these issues

**Comment by beccamc** [comment]
Build https://devdiv.visualstudio.com/_apis/resources/Containers/7343454/VSSetup?itemPath=VSSetup%2FMicrosoft.ML.ModelBuilder.vsix

**Comment by SaisreeDandamudi** [comment]
Verified the bug in latest build and the issue is fixed. Hence closing the bug
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.10.0 Preview 1.0
![1122_fixed](https://user-images.githubusercontent.com/51435580/111135614-df26f300-85a2-11eb-9f5c-f98ad159a123.png)

**Comment by poojapatil36** [comment]
Github tag: #Closed;
