### ISSUE TITLE
Section 508 502.3.1: (devenv/edit '') The Name property of a focusable element must not be null.

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1123]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #Benchmark; #Visual Studio; #A11yAuto; #WCAG4.2.1;

### Environment Details:
Microsoft Visual Studio 2019 Preview Version 16.8.0 preview 6.0

### Repro Steps:

1.Open Visual Studio Enterprise 2019 Preview 
2. Create a new .Net Core Console App (C#) 
3. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
4. Tab till "Object Detection" scenario and select the scenario
5. Tab till "Setup Work Space" button and press enter and create a new experiment and tab till "next" button and press enter
6. Run Accessibility Insights for Windows and Verify whether Name is given for the combo boxes and buttons present in the window

### App: 
devenv

### Element path: 
edit ''

### Issue Details: 
The Name property of a focusable element must not be null. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

### How To Fix:
 Provide a UI Automation Name property that concisely identifies the element.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.
![1123_ML  Net model builder_ name property is null](https://user-images.githubusercontent.com/51435580/100616512-303a1080-333f-11eb-972e-5b235266b485.png)

**Comment by SaisreeDandamudi** [comment]
Verified the bug in the latest build and the issue is fixed.
Hence closing the bug
Please find the attachment for reference
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 4.0 [30917.4.main]
![Screenshot (73)](https://user-images.githubusercontent.com/51435580/108352374-c1b57200-720c-11eb-8a39-b56b0cda6910.png)

**Comment by poojapatil36** [comment]
Github tag: #Closed;
