### ISSUE TITLE
Section 508 502.3.1: (devenv/button '') The Name property of a focusable element must not be null.

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1124]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #NonBenchmark; #Visual Studio; #A11yAuto; #WCAG4.2.1;

### Environment Details:
Microsoft Visual Studio 2019 Preview Version 16.8.0 preview 6.0

### Repro Steps:

1.Open Visual Studio Enterprise 2019 Preview 
2. Create a new .Net Core Console App (C#) 
3. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
4. Select "Recommendations" scenario and press enter
5. Tab till "Next" button and press enter
6. Select file as input data source and Select the file that has your data
7. Select the column you need to predict and then navigate to "Next Step" and press enter
8. Run Accessibility Insights for Windows and Verify whether Name is given for  buttons present in the window

### App:
 devenv

### Element path:
 button ''

### Issue Details: 
The Name property of a focusable element must not be null. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

### How To Fix: 
Provide a UI Automation Name property that concisely identifies the element.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.
![1124_ML  Net model builder_ name property is null](https://user-images.githubusercontent.com/51435580/100617609-c15db700-3340-11eb-9070-fadc886b9524.png)

**Comment by SaisreeDandamudi** [comment]
@zewditu @beccamc 
Verified the bug in the latest build and the issue still re-pros.
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 4.0
![Screenshot (75)](https://user-images.githubusercontent.com/51435580/108486998-c0478080-72c4-11eb-8e89-f0cb71e10f36.png)

**Comment by beccamc** [comment]
Removing the ready to review tag until we have a build for all of these issues

**Comment by beccamc** [comment]
Build https://devdiv.visualstudio.com/_apis/resources/Containers/7343454/VSSetup?itemPath=VSSetup%2FMicrosoft.ML.ModelBuilder.vsix

**Comment by SaisreeDandamudi** [comment]
Verified the bug in latest build and the issue is fixed. Hence closing the bug
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.10.0 Preview 1.0
![Screenshot (98)](https://user-images.githubusercontent.com/51435580/111136188-7724dc80-85a3-11eb-8218-b03dd3ce644a.png)

**Comment by poojapatil36** [comment]
Github tag : #Closed;
