### ISSUE TITLE
Section 508 502.3.1: (devenv/custom '') The ControlType and LocalizedControlType must not both be set to "custom."

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1126]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #NonBenchmark; #Visual Studio; #A11yAuto; #WCAG4.2.1;

### Environment Details:
Microsoft Visual Studio 2019 Preview Version 16.8.0 Preview 6.0

### Note:
Same issue is observed in every tab item (environment, Data, Train, Evaluate, Custom and Next steps) and in every scenario(Text classification, Image classification etc)

### Repro Steps:

1.Open Visual Studio Enterprise 2019 Preview 
2. Create a new .Net Core Console App (C#) 
3. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
4. Now run Accessibility Insights for windows

The following accessibility issue needs investigation.

### App: 
devenv

### Element path:
 custom ''

### Issue Details: 
The ControlType and LocalizedControlType must not both be set to "custom." [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

### How To Fix: 
Sufficient:
Provide a string for the LocalizedControlType property that concisely describes the control's function or purpose.

**Better:**
If possible, use a predefined (non-custom) control type and the default localized control type. The UIA framework will provide the correct localized control type automatically.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.
![1126_ML  NET model builder_control type and localized control type must not be same](https://user-images.githubusercontent.com/51435580/100704669-de8b9780-33cb-11eb-9027-0853c7e93fc9.png)

**Comment by SaisreeDandamudi** [comment]
Verified the bug in the given build and the issue is fixed. Hence closing the bug
Please find the below screen shots for reference
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 4.0 [30917.4.main]
![Screenshot (57)](https://user-images.githubusercontent.com/51435580/108033543-28def500-705a-11eb-9af0-4bb1c9cc77ee.png)

**Comment by poojapatil36** [comment]
Github tag: #Closed;
