### ISSUE TITLE
Section 508 502.3.1: (devenv/custom '') An element must not have the same Name and LocalizedControlType as its parent.

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1127]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #Benchmark; #Visual Studio; #A11yAuto; #WCAG4.2.1;

### Environment Details:
Microsoft Visual Studio 2019 preview Version 16.8.0 Preview 6.0

### Repro Steps:

1.Open Visual Studio Enterprise 2019 Preview 
2. Create a new .Net Core Console App (C#) 
3. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
4.Tab till "Text Classification" scenario and select it
5.tab till "next" button and press enter
6.Now run accessibility on the screen

The following accessibility issue needs investigation.

### App:
 devenv

### Element path: 
custom ''

### Issue Details: 
An element must not have the same Name and LocalizedControlType as its parent. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

### How To Fix: 
Provide unique names for controls that have a parent/child relationship and the same ControlType property.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.
![1127_ML  NET model Builder_name and control type are same as parent](https://user-images.githubusercontent.com/51435580/100705460-3b3b8200-33cd-11eb-9e5f-a4f6ae20f61a.png)

**Comment by zewditu** [comment]
Fixed by previous release

**Comment by SaisreeDandamudi** [comment]
Verified the bug in the latest build and the issue doesn't re-pro. 
Hence closing the bug
Please find the screenshot below for reference
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 4.0 [30917.4.main]
![Screenshot (58)](https://user-images.githubusercontent.com/51435580/108040832-cd196980-7063-11eb-8464-04a7305110ff.png)

**Comment by poojapatil36** [comment]
Github tag: #Closed;
