### ISSUE TITLE
Section 508 502.3.1: (devenv/custom '') The Name property of a focusable element must not be null.

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1128]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #Benchmark; #Visual Studio; #A11yAuto; #WCAG4.2.1;

### Environment Details:
Microsoft Visual Studio 2019preview Version 16.8.0 Preview 6.0

### Repro Steps:

1.Open Visual Studio Enterprise 2019 Preview 
2. Create a new .Net Core Console App (C#) 
3. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
4.Tab till "Text Classification" scenario and select it
5.tab till "next" button and press enter
6. Select the data source type and upload the data file
7. Now run Accessibility Insights for Windows on the screen

The following accessibility issue needs investigation.

### App: 
devenv

### Elements path:
custom ''
custom ''
datagrid
edit ''

### Issue Details: 
The Name property of a focusable element must not be null. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

### How To Fix: 
Provide a UI Automation Name property that concisely identifies the element.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.
![1128_ML  Net model builder_ name property is null](https://user-images.githubusercontent.com/51435580/100706712-75a61e80-33cf-11eb-887b-695d616762c9.png)

**Comment by SaisreeDandamudi** [comment]
Verified the bug in the latest build and the issue is fixed.
Hence closing the bug
Please find the attachment for reference
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 4.0 [30917.4.main]
![Screenshot (72)](https://user-images.githubusercontent.com/51435580/108351867-10aed780-720c-11eb-9328-8e0d29fdca67.png)

**Comment by poojapatil36** [comment]
Github tag: #Closed;
