### ISSUE TITLE
WCAG 4.1.2: (devenv/button 'Refresh') Focusable sibling elements must not have the same Name and LocalizedControlType.

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1134]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #Benchmark; #Visual Studio; #A11yAuto; WCAG4.1.2;

### Environment Details:
Microsoft Visual Studio 2019 Preview Version 16.8.0 Preview 6.0

### Repro Steps:

1.Open Visual Studio Enterprise 2019 Preview 
2. Create a new .Net Core Console App (C#) 
3. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
4. Tab till "Object Detection" scenario and select the scenario
5. Tab till "Set up work Space" button and press enter
6. Run Accessibility Insights for Windows 

The following accessibility issue needs investigation.

### App: 
devenv

### Element path:
 button 'Refresh'

### Issue Details:
 Focusable sibling elements must not have the same Name and LocalizedControlType. [WCAG 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

### How To Fix:
 Provide unique names for sibling controls that have the same ControlType property.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.
![1134_ML  NET model builder_Focusable sibling elements must not have the same Name and LocalizedControlType](https://user-images.githubusercontent.com/51435580/100853327-a5c3ef00-34ad-11eb-8890-81afbba26446.png)

**Comment by SaisreeDandamudi** [comment]
Verified the bug in the latest build and the issue is fixed.
Hence closing the bug
Please find the attachment for reference
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 4.0 [30917.4.main]
![Screenshot (71)](https://user-images.githubusercontent.com/51435580/108351376-7189e000-720b-11eb-9834-672cd79b2bef.png)

**Comment by poojapatil36** [comment]
Github tag: #Closed;
