### ISSUE TITLE
bug in CLI code gen

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1137]
SampleClassification.Model pulls MLModel.zip from wrong place.

In ConsumeModel.cs--

Replace this line:
public static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

with:
public static string MLNetModelPath = Path.Combine(System.AppContext.BaseDirectory, "MLModel.zip");

**Comment by Hrishikesh46779** [comment]
In xamarin this line "public static string MLNetModelPath = Path.Combine(System.AppContext.BaseDirectory, "MLModel.zip");" throws
System.ArgumentNullException: 'Value cannot be null.
Parameter name: path1'
