### ISSUE TITLE
How convert model.zip(exported with model builder ) to .onnx file for image classification scenario

### ISSUE THREAD

**Issue by masgh021** [dotnet/machinelearning-modelbuilder#1141]
how convert model.zip file to onnx ???
in model builder result

**Comment by LittleLittleCloud** [comment]
I'm not quite follow your question here, If you mean to convert an mlnet model to onnx format, unfortunately there's no way to do that currently, however, if you just want to get the onnx model, you can simply use Azure training in image classification, which will generate an onnx model afterwards

**Comment by masgh021** [comment]
hello @LittleLittleCloud 
i am using local classification with  model builder , after that i want convert model.zip to onnx file  locally .
but when i use
https://www.nuget.org/packages/Microsoft.ML.OnnxConverter/
i get error .
how can i solve it ????

**Comment by LittleLittleCloud** [comment]
Hi @masgh021 
For my best knowledge, once model is exported as mlnet, there's no way you can convert it to onnx anymore. But I believe you can export a model as onnx as long as all its estimators can be exported as onnx. But I don't think image classification trainer is one of them. So in short there's no way for you to convert model.zip to onnx for now, sorry my man.

**Comment by LittleLittleCloud** [comment]
Close due to no response. Feel free to reopen it if you have any questions.

**Comment by MasterNaz** [comment]
I would like to know if there have been any changes regarding this topic in the last 3-4 years?

Is it now possible to locally train an object detection Model wtih an gpu and save it in ONNX format in addition to the ML.NET model, similar how the Azure MI Training does it online?
