### ISSUE TITLE
Using PFI for multivariate analysis

### ISSUE THREAD

**Issue by ramonsf33** [dotnet/machinelearning-modelbuilder#1144]
**Is your feature request related to a problem? Please describe.**
There is no related to a problem, is related to my master degree work and I want to calculate the probability to calculate several features factors 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LittleLittleCloud** [comment]
hi @ramonsf33  Can you provide more info here.

**Comment by ramonsf33** [comment]
Sure

Hi, I want to calculate an index for each breast cancer risk factor using a multivariate analysis. I have a few risk factors and I want to know how much each factor affects the appearance of the disease and to do it numerically, that is, to assign a weight to each risk factor based on the multivariate analysis.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JakeRadMSFT** [comment]
Sounds like PFI is what you're looking for.

PFI Docs: 
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net

I'd take a look at our PFI docs and this issue for code sample:
https://github.com/dotnet/machinelearning-modelbuilder/issues/1031

**Comment by ramonsf33** [comment]
Hi I have been trying to develop a model using the BCSC database and I can’t be able to do it, could any body help me? I have been trying to load the data from a csv file. The PFI method is the perfect method to me but I need to make it work.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JakeRadMSFT** [comment]
Can you elaborate on what you've tried and what isn't working?

**Comment by ramonsf33** [comment]
Hi sure
I have been trying to load the data in on datasets
https://www.bcsc-research.org/download_file/view/191/344

and perform a PFI method to obtain the importance of each feature but when I try to load the data using IDataView I got an error saying the column age could not be found.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by LittleLittleCloud** [comment]
Hi @JakeRadMSFT, I'm not quite familiar about PFI API in MLNET. could you help take a look at the column not found error when applying PFI

**Comment by JakeRadMSFT** [comment]
@ramonsf33 could you share the project or a snippet of the code? I can try to help debug the column issue.

**Comment by JakeRadMSFT** [comment]
@ramonsf33 Closing the issue for now but I'm happy to help investigate. Feel free to re-open and include the code you've tried.
