### ISSUE TITLE
A11y_ML .NET Model Builder_ try your model_ Keyboard: Keyboard tab stop is provided for non interactive content

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1145]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #NonBenchmark; #Visual Studio; #Keyboard; #WCAG1.3.1;

### Environment Details:
Microsoft Visual Studio 2019 Preview Version 16.8.0 Preview 6.0

### Note:

- Same issue is observed in "Value prediction - try your model" , "Recommendation - try your model" scenarios
 

### Repro Steps:

1.Open Visual Studio Enterprise 2019 Preview 
2. Create a new .Net Core Console App (C#) 
3. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
4. Tab till "Text Classification" scenario and select the scenario
5. Tab till "Next Step" button and press enter
6. Select the data source type and tab till "browse" button and upload the file
7. tab till "next Step" button and press enter
8. Tab till "Train" button and press enter.
9. After the training is over tab till "Next step" button and press enter
10. In the "Evaluate" page navigate till "Try your model" using tab and verify whether keyboard tab stop is provided for non-interactive content

### Actual Result:
Keyboard tab stop is provided for non interactive content. Tab stop is provided for entire section in "Try your model" section

### Expected Result:
Keyboard tab stop should not be provided for non-actionable content

### User Impact:
keyboard only users will get confused if tab stop is provided for non-interactive content

### Attachment for Reference

[1145_ML .NET Model Builder_ Keyboard tab stop is provided for non interactive content.pptx](https://github.com/dotnet/machinelearning-modelbuilder/files/5656791/1145_ML.NET.Model.Builder_.Keyboard.tab.stop.is.provided.for.non.interactive.content.pptx)

**Comment by SaisreeDandamudi** [comment]
[1145_ML.NET.Model.Builder_fixedKeyboard.tab.stop.is.provided.for.non.interactive.content.pptx](https://github.com/dotnet/machinelearning-modelbuilder/files/6007824/1145_ML.NET.Model.Builder_fixedKeyboard.tab.stop.is.provided.for.non.interactive.content.pptx)
Verified the bug in the latest build and the issue is fixed. Hence closing the bug
Please find the attachment for reference

**Comment by poojapatil36** [comment]
Github tag: #Closed;
