### ISSUE TITLE
A11y_ML .NET Model Builder_ Image Classification-Data Preview_ Screen Reader: Narrator/NVDA are not reading name for the tab items present in "Data Preview" section instead reading some irrelevant content

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1148]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #Benchmark; #Visual Studio; #Screen Reader; #Narartor; #NVDA; #WCAG1.3.1;

### Environment Details:
Microsoft Visual Studio 2019 Preview Version 16.8.0 preview 6.0

### Screen Readers:
Narrator
NVDA

### Repro Steps:

1.Start Screen Reader
2.Open Visual Studio Enterprise 2019 Preview 
3. Create a new .Net Core Console App (C#) 
4. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
5. Tab till "Image Classification" scenario and select the scenario
6. Select any of the environment and tab till "next step" button and press enter
7. Upload the file and navigate till data preview section and tab till tab items in Data preview section and verify whether screen readers are reading the proper name for the tab items

### Actual Result:
Narrator/NVDA are not reading name for the tab items present in "Data Preview" section instead reading some irrelevant content

### Expected Result:
Narrator/NVDA should read the name for the tab items present in "Data Preview" section

### User Impact:
Screen Reader users will not get the information about the tab items if screen readers doesn't the correct name for the tab items

### Attachment for Reference

[1148_ML .NET_Narrator is not reading name for the tab items.pptx](https://github.com/dotnet/machinelearning-modelbuilder/files/5663209/1148_ML.NET_Narrator.is.not.reading.name.for.the.tab.items.pptx)
[1148_ML .NET__NVDA are not reading name for the tab items.pptx](https://github.com/dotnet/machinelearning-modelbuilder/files/5663215/1148_ML.NET__NVDA.are.not.reading.name.for.the.tab.items.pptx)

**Comment by SaisreeDandamudi** [comment]
[1148_ML.NET_Fixed_Narrator.is.not.reading.name.for.the.tab.items.pptx](https://github.com/dotnet/machinelearning-modelbuilder/files/6041703/1148_ML.NET_Fixed_Narrator.is.not.reading.name.for.the.tab.items.pptx)
Verified the bug in latest build and the issue is working as expected.
Hence closing the bug
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 4.0
![Screenshot (87)](https://user-images.githubusercontent.com/51435580/109128174-3f313300-7775-11eb-8f18-364a999a2b35.png)

**Comment by poojapatil36** [comment]
Github tag: #Closed;
