### ISSUE TITLE
Section 508 502.3.1: (devenv/tab item 'Microsoft.ML.ModelBuilder.ImageFolderModel') The Name property must not include its class name.

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1150]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #Benchmark; #Visual Studio; #A11yAuto; #WCAG4.2.1;

### Environment Details:
Microsoft Visual Studio 2019 Preview Version 16.8.0 Preview 6.0

### Repro Steps:

1.Open Visual Studio Enterprise 2019 Preview 
2. Create a new .Net Core Console App (C#) 
3. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
4. Tab till "Image Classification" scenario and select the scenario
5. Select any of the environment and tab till "Next Step" button and press enter
6.Tab till Browse button and press enter and upload the file
7. Run Accessibility Insights for the screen

The following accessibility issue needs investigation.

### App:
 devenv

### Element path:
 tab item 'Microsoft.ML.ModelBuilder.ImageFolderModel'

### Issue Details:
 The Name property must not include its class name. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

### How To Fix:
 Provide a UI Automation Name property for the element that:
 · Concisely identifies the element, AND
 · Does not include the element's class name (such as Microsoft.*.* or Windows.*.*).

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.
![1150_ML  NET_The Name property must not include its class name](https://user-images.githubusercontent.com/51435580/101439545-b99ea380-393a-11eb-93a4-7162882b10c2.png)

**Comment by SaisreeDandamudi** [comment]
Verified the bug in the latest build and the issue is fixed.
Hence closing the bug
Please find the attachment for reference
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 4.0 [30917.4.main]
![Screenshot (68)](https://user-images.githubusercontent.com/51435580/108349086-96c91f00-7208-11eb-86b8-b749dc5f7a46.png)

**Comment by poojapatil36** [comment]
Github tag: #Closed;
