### ISSUE TITLE
Azure - Image Classification new compute creation empty list

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#1153]
**System Information (please complete the following information):**
 - Model Builder Version: 16.3.0.2056001
 - Visual Studio Version: 16.8.2

**Describe the bug**

When trying to train an image classification model in Azure and I want to create a new compute, the list of compute to choose from is empty.

**To Reproduce**

Create a new Azure ML compute form Model Builder compute dialog creation dialog.

**Expected behavior**

A list of computes to choose from.

**Screenshots**

![image](https://user-images.githubusercontent.com/46974588/101566531-277bb700-399d-11eb-963a-01adf41a4fcf.png)

**Comment by luisquintanilla** [comment]
I think this issue was around quotas or the type of workspace I had. I see the error message at the top. When I created a new workspace, I was able to run my experiment.

**Comment by LittleLittleCloud** [comment]
Glad to see your problem is solved, I'm going to close the issue and feel free to re-open it if you have any other questions
