### ISSUE TITLE
A11y_ML .NET Model Builder_ Train_ Screen Reader: Narrator/NVDA are not reading the status messages which "Training", "Training Completed"... which appears when when user start to train the model

### ISSUE THREAD

**Issue by SaisreeDandamudi** [dotnet/machinelearning-modelbuilder#1155]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yWCAG2.1; #A11yTCS; #Win32; #DesktopApp; #Feature-ML.NETModelBuilder-Win32-Nov2020; #A11ySev2; #NonBenchmark; #Visual Studio; #Screen Reader; #Narrator; #NVDA; #WCAG4.1.3;

### Environment Details:
Microsoft Visual Studio 2019 Preview Version 16.8.0 preview 6.0

###Screen Readers:
Narrator
NVDA

### Note:
- Same issue is observed in all the scenarios when user trains a model
- Same issue is observed in **"Try Your model" page in every Scenario**. Screen Readers are not reading the "Results" when user predict

### Repro Steps:

1. Start Screen reader
2.Open Visual Studio Enterprise 2019 Preview 
3. Create a new .Net Core Console App (C#) 
4. Tab to "Solution Explorer" and right click on the project (Shift + F10) and then from the expanded list Select "Add" and then from the list items select "Machine learning"
5. Tab till "Text classification" scenario and select the scenario
6. Tab till "Next Step" button and press enter
7. tab till browse button and upload the file and tab till "Next Step" button and press enter
8. Tab till "Start Training" button and press enter and verify whether screen readers are reading the information that appears on the screen

### Actual Result:
Narrator/NVDA are not reading the status messages which "Training", "Training Completed"... which appears when when user start to train the model

### Expected Result:
Narrator/NVDA should read the status messages which appear on the screen

### User Impact:
Screen reader users will not get the information like "Training" or "Training completed" etc. if screen readers will not read it.

### Attachment for Reference
[1155_ML .NET_Narrator not reading the status messages.pptx](https://github.com/dotnet/machinelearning-modelbuilder/files/5678431/1155_ML.NET_Narrator.not.reading.the.status.messages.pptx)
[1155_ML .NET_NVDA not reading the status messages.pptx](https://github.com/dotnet/machinelearning-modelbuilder/files/5678441/1155_ML.NET_NVDA.not.reading.the.status.messages.pptx)

**Comment by beccamc** [comment]
Build https://devdiv.visualstudio.com/_apis/resources/Containers/7343454/VSSetup?itemPath=VSSetup%2FMicrosoft.ML.ModelBuilder.vsix

**Comment by beccamc** [comment]
Please use public build https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by SaisreeDandamudi** [comment]
Verified the issue in latest MS build and the issue is fixed. Hence closing the bug.

**Comment by poojapatil36** [comment]
Github tag: #Closed;
