### ISSUE TITLE
Regression Experiment + CUDA

### ISSUE THREAD

**Issue by jucchytil** [dotnet/machinelearning-modelbuilder#1158]
I can train a LightGBM model using the RegressionExperiment.Execute command and it works very well.

Is it possible to configure the command to use the 640 CUDA 5.0 cores on my Nvidia GeForce GTX 960M video card to increase my runs/minute training rate?

**Comment by JakeRadMSFT** [comment]
Unfortunately it's not possible at this time. 

Can you point me to the "RegressionExperiment.Execute" that you're referencing?

**Comment by jucchytil** [comment]
Is this what you are looking for?

```
        // create the experiment
        var experiment = context.Auto().CreateRegressionExperiment(settings);

        // run the experiment
        var columnName = "FutureSmallPrice";
        var experimentResult = experiment.Execute(trainData, labelColumnName: columnName, progressHandler: progress);

```

I've downloaded the LightGBM source and am using the LightGBMNet.Train NuGet package with the goal of not only use the GPU, but also be able to refit the data as it arrives.  Coding is in progress and is looking promising.  I am super curious to see how accurate and fast my code will be when I am done.  One additional benefit will be I don't need to pass everything in and out of LightGBM through the file system as the nuget package accesses its C++ methods directly using DLLImport. 

Very interesting stuff.

**Comment by JakeRadMSFT** [comment]
Thanks for sharing! Did you notice a significant performance improvement?

How large is your dataset (# Columns and #Rows)?

**Comment by jucchytil** [comment]
Not really. It actually seemed to spend a fair amount of time transferring data to the GPU.

Dataset = 80K rows x 57 features

I got all three feature selection methods working (weights, feature contribution and feature permutation) working but was surprised how there wasn't as much correlation between them as I was hoping for.
I probably need to continue playing with them a bit more.

Joe

**Comment by JakeRadMSFT** [comment]
Thanks for reporting back! If you end up finding it improves training performance please let us know!

We definitely noticed a significant improvements with image training but we hadn't done a lot of testing for the other scenarios. Anything you provide could help us prioritize it in the future!

**Comment by JakeRadMSFT** [comment]
Closing for now -  thanks for investigating! Please let us know if there ends up being a performance improvement in the future and we can look to adding GPU support in ML.NET for regression.
