### ISSUE TITLE
Not getting add "machine learning" option in .net app

### ISSUE THREAD

**Issue by Brijesh1410** [dotnet/machinelearning-modelbuilder#116]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by greazer** [comment]
@Brijesh1410, please check the following:
1) You need to shutdown Visual Studio and allow the extension to actually get installed. If it has been installed, then opening Extensions>Manage Extensions in VS should show a Disable and Uninstall button.
![image](https://user-images.githubusercontent.com/11685408/60059166-3afb6b00-96a0-11e9-994e-9f524864d324.png)
2) Be sure you are right-clicking on the project node in the VS Solution Explorer.

If neither of the above are the problem, please send us more details including the specific versions of Windows and VS you're using.

**Comment by pmg1963** [comment]
I have same problem. The ML.NET Model Builder shows in Extensions and Updates, but when I right click the project in Solution explorer there is no Add Machine Learning Option. see image 
![image](https://user-images.githubusercontent.com/16771510/60699206-3fdcdc00-9f36-11e9-9cff-36fb7c76feda.png)

I am using Visual Studio Community 2017, Windows 10, 64 bit, version OS build 17134.829

**Comment by JakeRadMSFT** [comment]
@pmg1963 what project type are you right clicking on?

**Comment by JakeRadMSFT** [comment]
Resolving issue because we haven't received a response. If you're still having this issue, please re-open and include which project type you're right clicking on.

Cheers,
Jake
