### ISSUE TITLE
Machine Learning not showing up on context menu

### ISSUE THREAD

**Issue by gotmike** [dotnet/machinelearning-modelbuilder#1164]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: not sure where to find
 - Visual Studio Version (if applicable): 2019 v16.8.3

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
- Clear description of the problem: "Machine Learning" is not on the "Add" menu

**To Reproduce**
1. Right-click on Project
2. Click Add
3. Don't see Machine Learning

**Expected behavior**
I expect to see "Machine Learning" on my "Add" context menu

**Screenshots**
N/A

**Additional context**
Happened while following the tutorial step-by-step, new project. I was able to work around by installing the Model Builder as an extension instead, although this is not the way the tutorial instructed. I think you should add this as an alternate way to get this working in the tutorial.

**Comment by Alearian** [comment]
Same for me, project context menu does not contain the Add-> Machine Learning menu item. Updated to VS 16.8; followed the steps to enable ML but no context menu item.

**Comment by LittleLittleCloud** [comment]
dup of #969

**Comment by LittleLittleCloud** [comment]
Close due to no response. Feel free to reopen it if you have any questions.
