### ISSUE TITLE
capitalization on the namespace

### ISSUE THREAD

**Issue by gotmike** [dotnet/machinelearning-modelbuilder#1165]
System Information (please complete the following information):

Model Builder or CLI Version: not sure where to find
Visual Studio Version (if applicable): 2019 v16.8.3

When the code is autogenerated, it comes in as `MyMLApp` instead of `myMLApp`

On which page of the tutorial did you run into an issue (URL):
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume

Clear description of the problem:
The namespace does not match the tutorial

To Reproduce
Click Add to Solution and examine namespaces of the added projects

Expected behavior
I expect the namespace to match the tutorial

Screenshots
N/A

Additional context
I think this causes an issue with the project references as well. I had to go in and manually add project references from `myMLApp` to the two new ML projects to get it to work.

**Comment by LittleLittleCloud** [comment]
The namespace should be capitalized, which is recommended in C# programming. Could you change tutorial instead (myMLApp -> MyMLApp)
