### ISSUE TITLE
response from this code is not `true` but instead is `1`

### ISSUE THREAD

**Issue by gotmike** [dotnet/machinelearning-modelbuilder#1166]
System Information (please complete the following information):

Model Builder or CLI Version: not sure where to find
Visual Studio Version (if applicable): 2019 v16.8.3

When I run the app, it says "1" instead of "True"

On which page of the tutorial did you run into an issue (URL):
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume

Clear description of the problem:
The output doesn't match the tutorial.

To Reproduce
Run the project

Expected behavior
I expect the output to match the tutorial

Screenshots
N/A

Additional context
N/A

**Comment by LittleLittleCloud** [comment]
This is because the label is in format 0/1 instead of True/False. And the code's behavior is expected. We will update our doucments.
