### ISSUE TITLE
Consume the Model->"Add to solution"->Cancel, then no way to add to solution any more

### ISSUE THREAD

**Issue by GuangSunshine** [dotnet/machinelearning-modelbuilder#1167]
**System Information (please complete the following information):**
 - Model Builder Version: 16.3
 - Visual Studio Version 16.8.3

**Describe the bug**
- On which step of the process did you run into an issue:
- Consume the model
- Clear description of the problem:
   "Add to solution"->"Do you want to overwrite the existing project?" -> "No"
   Expected: user can still click "Add to solution" and specify a new project name
   Actual: "Add to solution" is disabled, there is no way to add the trained model the solution. 

**To Reproduce**
1. Add->Machine Learning->Scenario: Image classification
2. Set up environment, set up training data
3. Train
4. Evaluate
5. Consume the model, click "Add to solution". Because I already have projects "ML.NETstudyML.ConsoleApp" and "ML.NETstudyML.Model", it asks me do I want to overwrite them, choose "No"
6. Now the "Add to solution" button is disabled, there is no way to add the trained model to the solution.

**Expected behavior**
user can still click "Add to solution" and specify a new project name

**Screenshots**

**Additional context**

**Comment by vahpetr** [comment]
Duplicate https://github.com/dotnet/machinelearning-modelbuilder/issues/1163

**Comment by beccamc** [comment]
Thanks for reporting @GuangSunshine! Unfortunately we don't have a work around for this. You'll have to rename "ML.NETstudyML.ConsoleApp", retrain and then "Add to Solution" again.

We'll look at fixing this for the next release
