### ISSUE TITLE
MULTICOLUMN - More than 3 columns 

### ISSUE THREAD

**Issue by JoseManuelMartinezDiaz** [dotnet/machinelearning-modelbuilder#1169]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LittleLittleCloud** [comment]
Hi @JoseManuelMartinezDiaz 
Could you provide more detail on this case? Like which dataset you are using or what specific error you are encoutering.

**Comment by LittleLittleCloud** [comment]
Close due to no response. Feel free to reopen it if you have any questions.
