### ISSUE TITLE
Adding a change log

### ISSUE THREAD

**Issue by jernejk** [dotnet/machinelearning-modelbuilder#1177]
I have noticed that sometimes we are getting updates to ML.NET Model Builder with no changelogs (or at least I haven't seen them). Since this project is (still?) not open source, it's impossible for us to figure out what changed.

Can we have one consistent place for changes and have a link to that from:
* https://marketplace.visualstudio.com/items?itemName=MLNET.07
* https://docs.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-model-builder

Alternatively, you can publish the extension as open-source and off-load the work to the community. 😉

**Comment by zewditu** [comment]
@jernejk, thanks for your recommendation to make ML.Net Model Builder open source ! 
@JakeRadMSFT, what is the plan around to make it open source?

**Comment by JakeRadMSFT** [comment]
Thanks @jernejk! We'll start adding change logs! That's a great idea!

No ETA on Open Sourcing yet but we have been preparing to do so!

**Comment by jernejk** [comment]
Thanks. :)

I'm frequently doing demos to clients and audiences on various events, and it's nice to know what changed. 😊
I have once done a live demo in December where the UI completely changes and half of my demo was "Oh, they fixed that too... Awesome, I can now talk more about X!". 😂 (some of them were scripted as some have already seen my demos)

Great job on Model Builder. 🤗

**Comment by beccamc** [comment]
We've started adding change logs! You can see them here - https://github.com/dotnet/machinelearning-modelbuilder/tree/main/docs/release-notes. The first one covered about 9 months of work, so it isn't as detailed as I'd like, but we will improve as our releases becomes more regular. 

Thank you for the suggestion @jernejk! Please let us know when you have other ideas or thoughts.
