### ISSUE TITLE
Cusotmer: "Could not load file or assembly 'System.Runtime, Version=4.2.1.0 "

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#118]
Facing Issue "Could not load file or assembly 'System.Runtime, Version=4.2.1.0 "when i am trying to consume model in Main project

Customer reported issue on VS gallery Q&A.

**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by greazer** [comment]
@rustd, we can't do anything with this issue. If there's details in the VS gallery please include them here. If not, there is just nothing to go on here.
