### ISSUE TITLE
desktop.Clr.x64$C94B8CFE-E3FD-4BAF-A941...

### ISSUE THREAD

**Issue by shaggygi** [dotnet/machinelearning-modelbuilder#1180]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.3.0.2056001
 - Visual Studio Version (if applicable): VS 2019 16.8 RTM

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
- Clear description of the problem: Get an error dialog.

![image](https://user-images.githubusercontent.com/2956825/104112411-77131280-52bc-11eb-928b-c238bbd1373a.png)

**To Reproduce**
1. Add .NET Core console app in new solution.
2. Right-click project > Add > Machine Learning > error dialog.

**Expected behavior**
Should be able to add ML functions to project similar to instructions.

**Comment by JakeRadMSFT** [comment]
@shaggygi are you using a 64bit machine? Model Builder only supports 64 bit machines at this time

**Comment by shaggygi** [comment]
@JakeRadMSFT yes, this is a 64bit machine.  I believe this was working in an earlier preview, but getting the error now for some reason.  Tried repairing the VS instance, but still fails.

**Comment by JakeRadMSFT** [comment]
@shaggygi Sorry about the delay - I've been having difficulties with github notifications. We're you able to resolve this?

I believe following these steps would resolve it: 
https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#dev-team-cannot-reproduce-no-constant-repro-on-other-machines

**Comment by beccamc** [comment]
@shaggygi I know this issue is older, have you been able to resolve it?

**Comment by shaggygi** [comment]
@beccamc yes, but not sure what resolved.  I believe it was a fluke install of VS or ML extension.  sorry on delay for not closing.  thx for checking in 😄
