### ISSUE TITLE
Unable to find method 'PredictRegressionAsync/3'

### ISSUE THREAD

**Issue by armbrat** [dotnet/machinelearning-modelbuilder#1181]
**System Information (please complete the following information):**
 - Model Builder Version: 1.5.0-preview2
 - Visual Studio Version: 2019 16.8.3

**Describe the bug**
- On which step of the process did you run into an issue: During evaluation of value prediction of taxi dataset as defined by the next steps in the tutorial: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices-with-model-builder
- Clear description of the problem: After clicking Predict in the Evaluation section of Model Builder, I get the following error: Unable to find method 'PredictRegressionAsync/3' on Microsoft.ML.ModelBuilder.AutoMLEngine for the following reasons: 

**To Reproduce**
1. Open ML.NET Model Builder
2. Choose the Value prediction scenario
3. Click Data
4. Load the taxi CSV file (https://raw.githubusercontent.com/dotnet/machinelearning/master/test/data/taxi-fare-train.csv) 
4. Select "fare_amount" as the column to predict 
5. Click Train
6. Click Start Training
7. After training is complete, Click on Evaluate
8. Click on Predict, using the pre-populated values
9. At this point the error occurs: Unable to find method 'PredictRegressionAsync/3' on Microsoft.ML.ModelBuilder.AutoMLEngine

**Expected behavior**
I expect the evaluation stage to produce a prediction

**Screenshots**
Screenshot Attached

**Additional context**
- The example of calculating Yelp sentiment works correctly.
- Log file attached

**Comment by armbrat** [comment]
<img width="1286" alt="MLError" src="https://user-images.githubusercontent.com/10500545/104131684-d7419d00-532c-11eb-9156-db05bd29e4a1.png">

**Comment by armbrat** [comment]
[mllog.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5793076/mllog.txt)

**Comment by JakeRadMSFT** [comment]
Hmm that's an interesting one - Can you check if there is a log under %Temp%\servicehub\logs with a filename that contains "AutoML"?

**Comment by armbrat** [comment]
Hi Jake - please find it attached

[A576C36D-CreateAutoMLServiceAsync-13224-mdpec1x5-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/5805751/A576C36D-CreateAutoMLServiceAsync-13224-mdpec1x5-1.log)

**Comment by CurtisHx** [comment]
I'm also running into the same issue following the ML.NET tutorial on this step:
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/evaluate

using the Sentiment Labelled Sentences datasets from here: https://archive.ics.uci.edu/ml/machine-learning-databases/00331/sentiment%20labelled%20sentences.zip

I do not have a log file under  %Temp%\servicehub\logs.  

I've attached the exception log and my Visual Studio information.
[VS Info.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5873888/VS.Info.txt)


[45ae5a32-b6d4-4c67-9336-0c310188095b.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5873871/45ae5a32-b6d4-4c67-9336-0c310188095b.txt)

**Comment by vzhuqin** [comment]
Not repro this issue on Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps:
1). Download the dataset from: https://raw.githubusercontent.com/dotnet/machinelearning/main/test/data/taxi-fare-train.csv
2). Create new C# console app with .Net 5.0;
3). Add model builder by right click on the project;
4). Click "Value prediction" on Scenario page to navigate to Environment page;
5). Select Local (CPU) on Environment page;
6). Select File and click "Browse..." to input the downloaded dataset, set "fare_amount" to "Column to predict (Label)" on Data page;
7). Click "Start training" with default 600s train time on Train page and wait Training complete;
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/527c8fa8-676f-41e0-aada-63bbce257f99)
8). Click "Predict" button to predict the Results, no error on the predict process.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/96e2fad6-f437-4c90-897d-4b541f82890e)

**Comment by lovettchris** [comment]
I'm getting this same error with this version of the ModelBuilder on VS 2019:
![image](https://user-images.githubusercontent.com/18707114/121086588-339fd000-c798-11eb-90ba-706e81522737.png)

Here's the log:
[3abfc5af-5301-4eeb-90d0-6708a60f21b6.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6611969/3abfc5af-5301-4eeb-90d0-6708a60f21b6.txt)
