### ISSUE TITLE
Telemetry from AutoMLService fails

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1187]
Failures from AutoMlService.cs from Engine_AutoMLTelemetryReceived and AutoMLTelemetry_AutoMLTelemetryEventHandler. Not sure why. See TODO: 1187 in code.

**Comment by LittleLittleCloud** [comment]
This issue should no longer exist after this [PR](https://github.com/dotnet/machinelearning-tools/pull/909) merged in
