### ISSUE TITLE
Issue with updating an existing version

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#119]
The new version is not updating in VS2017. i tried removing a old version and installing new one but again issue occurs it say there no version of VS to install this

This was opened in the VS gallery Q&A.

**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by greazer** [comment]
@rustd are you interacting with the customer on VS Gallery? If so, please do that there, unless you know for sure that they discovered a bug and that there's specific repro steps you can supply here. My guess here is that their build of VS 2017 might not be the latest.

**Comment by gouravbhatt** [comment]
Hi,
i tried updating VS2017 and its working.. Thanks :)
