### ISSUE TITLE
Add Loader/Spinner when  Adding Projects

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#1195]
Seems slower than it used to be. We should also double check there isn't a perf regression for some reason.

**Comment by beccamc** [comment]
Marking this as lower priority. Maybe it should be P1? Change if you disagree!

**Comment by beccamc** [comment]
@zewditu Are you able to pickup this work item, given your refactor of the code page?

**Comment by beccamc** [comment]
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/bbd2f648-d11b-4c60-8c35-4e085b2a79ec)

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/9376b9d6-f707-481e-856f-72c484919a0b)
