### ISSUE TITLE
Text doesn't show complete when font size for environment is larger than 9

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1197]
font setting

![image](https://user-images.githubusercontent.com/16876986/106071504-4bb16580-60bb-11eb-9bcb-5ff6afe5fa1e.png)

Some text is not show complete
![image](https://user-images.githubusercontent.com/16876986/106071029-659e7880-60ba-11eb-8c07-3488adc8f437.png)

**Comment by romalpani** [comment]
We should consider renaming the tags to simply "Local" and "Azure" for all cases. 
It would solve this current issue, but also help make the overall size of the tags smaller. 
@briacht thoughts?

**Comment by briacht** [comment]
Works for me!

**Comment by romalpani** [comment]
@zewditu does that solve this issue? 
We can keep the tooltips as is.

**Comment by zewditu** [comment]
@romalpani  to be more specific, each card has an image, title, description, and Tag(azure or local ),  when we say renaming tags "Local" and "Azure" do you mean remove the description?  could you make it clear?

**Comment by romalpani** [comment]
@zewditu Just update the tags from "Local ML" to "Local" and "Azure ML" to "Azure". 
Everything else remains the same. 

For bigger font size ---- 

1. Title will get truncated if needed. When that happens, the tooltip on hover should read the full title.
2. Description will get truncated if needed (as it does for normal font size if the description is too long). When that happens, the tooltip on hover should read the description (as it does today).
3. Tags once updated with suggested text should work even for high-font size (at least English). In the case of longer languages (e.g. German) + bigger font size, truncate the text inside the tag after it reaches a maximum width, and keep the on-hover tooltip as it is in the current implementation.
4. Tags (when both local and azure present), use max-width for truncation such that both tags can fit in the card in the same row.

Does this help?

**Comment by zewditu** [comment]
yes, Thanks @romalpani !!!

**Comment by vzhuqin** [comment]
Still have some text is truncated on : ML.Net Model Builder: 16.7.7.2150601 (Main Branch), could you please take a look?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/016d6983-e5cd-4808-aa48-19a3ddeb2049)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a6d3d846-ef59-45bc-b40e-88854415573a)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0b5c1baa-c169-4f8a-bc7e-156586c87115)

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.9.1.2156601
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/372e5214-496d-40d8-9131-191c0ee276b8)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/66a0784f-4492-4746-9947-cebe7e68e235)
