### ISSUE TITLE
Cancel to select data show error window 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1199]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. select any of text scenarios 
2.  On data page click browse button and cancel to select a file 

**Expected Experience**
Nothing to show 

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/066de127-0e72-4228-901d-ee1ea079c948)
**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
Duplicate. Fixed with https://github.com/dotnet/machinelearning-tools/pull/876
