### ISSUE TITLE
Updated Guidance on Training Time

### ISSUE THREAD

**Issue by PrintsCharming** [dotnet/machinelearning-modelbuilder#120]
**Model Builder Version**: 16.0.1906.701
**Visual Studio Version**: 16.1.3

**Bug description**
Training time guidance seems to be un-realistic with **real world** data.

**Steps to Reproduce**
1. Train a classification model with 1 million rows but file size 146mb

**Expected Experience**
Per guidance training time should go about 30 minutes:
100 - 500 Mb | Numeric and Text | 30 min

**Actual Experience**
No measurable results in time frame

**Additional Context**
Perhaps rowcount is a better metric than file size.

**Comment by greazer** [comment]
@PrintsCharming Thanks for the feedback. We'll take a look a this to see what might make sense to change or say.

**Comment by rustd** [comment]
Can we please update this in the doc for Model Builder?

**Comment by taffmak** [comment]
I'm getting a similar thing.
The data I have needs to be classified to a 3 level classification.  I'm generating 3 models with essentially the same data but each with a successive level of classification in an additional column.
I intend to pass the data through each in turn to get each of the 3 classification levels.
I have 11 columns of data (mixed text/numeric) and 2.29M rows.
The files are 514.7MB, 522.9MB and 531.0MB
The first two get decent results (although getting exceptions from some trainers).
They've all had an hour to run, the first 2 start getting results quite soon and get several model evaluated.  The last one finished the first trainer with 4 seconds to spare!

**Comment by natke** [comment]
@rustd Sure, no problem. What is the new guidance?

**Comment by briacht** [comment]
Did we do some sort of testing on datasets to get the original file size guidance / where did those estimates come from?

**Comment by justinormont** [comment]
Aim at 100-200 models produced. And going over is fine.

The time for this will depend on:
* User's machine (CPU speed, number of cores, amount of RAM, GPU for images, disk speed)
* Data types (numeric is fast, categorical is less fast, text is slower, image is much slower)
* Number of rows / columns
* Which models do well on the dataset (trees tend to be slower than linear models)

**Comment by beccamc** [comment]
Per an offline conversation with Bri, no change required for our next release. Removing P0 and moving below ship blocking items.

**Comment by beccamc** [comment]
Closing this as we're tracking is a separate item.
