### ISSUE TITLE
Unguided scenario isn't cleared when selecting guided scenario

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1200]
1. Select unguided scenario
2. Return to Scenario page. 
3. Select other scenario
4. Left nav is wrong

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/4531d61a-158f-4941-9d3f-1d6b407bbc05)

**Comment by zewditu** [comment]
validated
