### ISSUE TITLE
Data and training tab are not cleared when switching between scenarios

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1201]
To reproduce
- finishing an e2e classification training
- switch to another scenario
- the data and training tab is still available, and the old data is not cleaned.

![image](https://user-images.githubusercontent.com/16876986/106072202-9b446100-60bc-11eb-9ecd-c5368ef4f178.png)

![image](https://user-images.githubusercontent.com/16876986/106072235-aac3aa00-60bc-11eb-8a6e-c77973a81668.png)

**Comment by beccamc** [comment]
Fixed in https://github.com/dotnet/machinelearning-tools/pull/935
