### ISSUE TITLE
Advance data option searching bar doesn't work

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1202]
To reproduce
- select dataset and go to advanced data option, search columns
- the catagory drop down list doesn't work

![image](https://user-images.githubusercontent.com/16876986/106072373-e8c0ce00-60bc-11eb-8b4a-ea79c2f55802.png)

**Comment by beccamc** [comment]
This is fixed in main (probably around the fix I did on columns)

**Comment by LittleLittleCloud** [comment]
LGTM
![Uploading image.png…]()
