### ISSUE TITLE
ML.Net ARM : Could not assembly 'Microsoft.ML.ModelBuilder.AutoMLService'

### ISSUE THREAD

**Issue by crazyoutlook** [dotnet/machinelearning-modelbuilder#1208]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.2.0 ML.Net
 - System: NVIDIA Jetson Nano, Ubuntu 18.04.5 LTS, JetPack 4,.4.
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): 
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: 
Could not load file or assembly 'Microsoft.ML.ModelBuilder.AutoMLService, Version=16.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.

**To Reproduce**

mlnet classification --dataset "yelp_labelled.txt" --has-header false --label-col 1 --train-time 20

**Expected behavior**
Ml Model should get trained

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@LittleLittleCloud ,cloud have any idea why is this issue?

**Comment by LittleLittleCloud** [comment]
Hi @crazyoutlook 

MLNet currently doesn't support ARM device because some of its libraries can only run on x64/86 platform. But as I know, @michaelgsharp in MLNet team is working on replacing those libraries with arm-compatible ones. So maybe in the next release this error will gone.

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you have any other questions.
