### ISSUE TITLE
Training is failed without any model built

### ISSUE THREAD

**Issue by Akash01nov** [dotnet/machinelearning-modelbuilder#1210]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
Hello @Akash01nov,
Training failed without any model built happened most of the time  if your data is very small or the training time is not enough .

could you try it larger dataset  or increasing  training time ?

**Comment by zewditu** [comment]
No customer response for log time , if you hit the issues let us know we will reopen it . 

Thanks.
