### ISSUE TITLE
GPU Service not found

### ISSUE THREAD

**Issue by sey-sa** [dotnet/machinelearning-modelbuilder#1212]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
Hi @sey-sa

Could you tell us more detail info for the better investigation of the issue? like steps to reproduce.

thanks .

**Comment by zewditu** [comment]
If you still hit the issue let us know , we will reopen it.
