### ISSUE TITLE
Guided scenario  focus is not fully visible

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1213]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. Navigate to any guided scenario using tab by the keyboard.

**Expected Experience**
All side of the card should show the focus sign. 

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/4c4710f8-e7c4-4a6c-b768-a2c5cf5fb77b)

**Additional Context**
unguided scenarios shown correctly
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/5fb80240-fb31-47ff-af8f-d45d0e82183d)

**Comment by JakeRadMSFT** [comment]
It seems like this is broken with the new config behind stuff.

**Comment by vzhuqin** [comment]
This issue can't be repro on main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

All scenarios are fully visible using the tab key on the keyboard.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/51815c3b-38f6-45ae-8144-42cb5218826d)
