### ISSUE TITLE
Unable to see  Browse button  on data tab

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1215]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/900f214d-7053-4ce1-b134-f00f74a20c9c)

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/e151488d-a005-4b84-b41a-6eaa35b03e17)

**Additional Context**
This is due to horizontal scrollbar is  disabled

**Comment by beccamc** [comment]
Browse button should pop down a line on small screens 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/930a9847-7f27-4dce-b8d7-db60e52a20c2)

**Comment by vzhuqin** [comment]
This issue not occurs on main branch, the "Browse..." button will pop to the next line if the screen becomes smaller.
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.5
- .Net: 5.0.202

![Browse button.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/345487c2-e252-4960-80b9-735829605d5e)
