### ISSUE TITLE
Consume page UI update 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1216]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Additional Context**
Based on this UI design 
https://www.figma.com/file/r3eH1oUgHhqdAzz4A4FRDK/ML.NET-Model-Builder-Code-Next-Steps?node-id=39%3A1862

**Comment by JakeRadMSFT** [comment]
![image.png](https://images.zenhubusercontent.com/5cde1c65e3106e39e8ae08f2/a94ad467-824a-4401-bd88-648dc7f1f430)

**Comment by JakeRadMSFT** [comment]
![image.png](https://images.zenhubusercontent.com/5cde1c65e3106e39e8ae08f2/a80f866d-104d-451f-8fd6-ebe6b1e5a526)
