### ISSUE TITLE
Yes/No header update is broken

### ISSUE THREAD

**Issue by andrasfuchs** [dotnet/machinelearning-modelbuilder#1217]
**System Information (please complete the following information):**
 - Model Builder Version: v16.3.0.2056001
 - Visual Studio Version: Community 2019 v16.8.3

**Describe the bug**
- On which step of the process did you run into an issue: 
Data
- Clear description of the problem:
I have a few big datasets stored in CSV files containing EEG data, ranging from 2 to 800 MBs. 
I used a 9MB file with 2003 columns and 349 rows. The first 2000 columns are the EEG data, and last 3 are label values between 0 and 100, indicating sleep, meditation and wakefulness. I would like to have 3 models for the 3 states.
The loading of the file was about 192 seconds, to select the column to predict took 18 seconds and to select to ignore a few others took 87 seconds. During these step the UI was not too responsive.

**To Reproduce**
1. Go to 'Solution Explorer'
2. Right click on your project
3. Add / Machine Learning
4. Select 'Value prediction'
5. Click 'Next' on the Environment page
6. Select the data source type as file
7. Browser for a big CSV file 
8. Try to select the column to predict and/or go to the "Advanced data options..." to ignore some others

**Expected behavior**
I would expect to have a very quick, intuitive way to select the column to predict, and the few columns to ignore.

**Screenshots**
![image](https://user-images.githubusercontent.com/910321/107041135-6ae97a80-67c0-11eb-954e-23fb42282ea5.png)

**Additional context**
You can download my test dataset from here: 
https://drive.google.com/drive/folders/1Kev-3jBDqkrtJOH7cMN0_-6AfFFfhNm1?usp=sharing

**Comment by JakeRadMSFT** [comment]
Sorry for the delayed response and thanks for reporting and sharing the datasets!

We'll investigate a short term solution to improve speeds (like not loading all the columns in the data preview) and a long term solution for how to better allow users with a large number of columns to change the column type and purpose.

**Comment by andrasfuchs** [comment]
Thank you, that sounds great!

Would you consider adding support for CSVs that have column names/headers in their first line? It would be more intuitive to reference the label column by its name and not like "col2001".

**Comment by beccamc** [comment]
@andrasfuchs Model Builder should automatically detect when a CSV file has a header row and use it for the column names. If it isn't auto detecting you can go to Advanced data options -> Data Formatting -> "Does the data contain column headers?"

**Comment by andrasfuchs** [comment]
> @andrasfuchs Model Builder should automatically detect when a CSV file has a header row and use it for the column names. If it isn't auto detecting you can go to Advanced data options -> Data Formatting -> "Does the data contain column headers?"

It looks like that it doesn't detect the headers automatically for me:
![image](https://user-images.githubusercontent.com/910321/109347795-fb712300-7873-11eb-8fc2-b85bd23bb5d0.png)

You can reproduce my case with the `2021-02-03_0-45Hz_headers.csv` file from the folder I mentioned above.


If I change the "Does the data contain column headers?" setting to Yes, then the headers are read correctly, but there is no data displayed in the data preview.

![image](https://user-images.githubusercontent.com/910321/109348306-a255bf00-7874-11eb-980c-a69bdaa56b1f.png)

**Comment by beccamc** [comment]
CSV should be loading in a reasonable amount of time. 

Problem with header yes/no.

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/4cf2e022-d64a-49f7-be54-9a500af5fffb)[https://app.zenhub.com/files/186917455/63008e68-98a6-4244-857a-a28b79a7e5d6/download](https://app.zenhub.com/files/186917455/63008e68-98a6-4244-857a-a28b79a7e5d6/download)

**Comment by beccamc** [comment]
@andrasfuchs The problem with the data preview for your dataset is the `"."` character in the column header.  The decimal dot `"."` is used by the WPF binding expression as property path separator.  It is just a problem with our display and shouldn't affect the training itself. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/07ecb856-d8a4-446f-8f76-f74b6099eb72)

That being said, I wasn't able to get a trained model. Were you?

**Comment by beccamc** [comment]
Are you sure you were on 16.13.6? I just tested on that dataset and I got ~15 seconds to load the preview.

**Comment by beccamc** [comment]
You should now be able to open a large file. We are limiting what is show in the UI for better perf. Check if out and let me know what problems you find! Thanks for all the details on this one Andras!

**Comment by luisquintanilla** [comment]
Hi @andrasfuchs 

Thank you for trying out the new release and great to hear loading times are better! Sorry you're still running into the column header issues. 

I've opened an issue already to track the header issue so no need to create one. Thanks again for the feedback. You can track progress and provide additional feedback here: #2132

**Comment by andrasfuchs** [comment]
Thank you @luisquintanilla
