### ISSUE TITLE
AMD GPU support

### ISSUE THREAD

**Issue by andrasfuchs** [dotnet/machinelearning-modelbuilder#1218]
**Is your feature request related to a problem? Please describe.**
I have a PC with AMD GPU. It is not supported (I think) at the moment, but it would be nice to use it for model training.

**Describe the solution you'd like**
I would like to have a item of my GPU on the Environment page.
If the GPU is not supported then a message should be shown to make it clear that it is detected, but not (yet) supported.

**Describe alternatives you've considered**
I haven't looked around yet, there are probably ML frameworks for AMD GPU, I don't know to be honest.

**Additional context**
![image](https://user-images.githubusercontent.com/910321/107041938-65d8fb00-67c1-11eb-91d1-42ed5a677f26.png)

**Comment by beccamc** [comment]
@andrasfuchs Thanks for reporting this! I see what you mean. @briacht and @romalpani for visibility.

**Comment by beccamc** [comment]
Small change, add doc link for supported environments https://github.com/dotnet/machinelearning-tools/pull/915

**Comment by beccamc** [comment]
Noticed [another customer](https://github.com/dotnet/machinelearning-modelbuilder/issues/990#issuecomment-765831005) had a very similar issue

**Comment by beccamc** [comment]
This has been updated to show a message stating GPU isn't supported for this scenario yet. Thanks for the feedback - let me know if you need anything else
