### ISSUE TITLE
Get error when I press train button

### ISSUE THREAD

**Issue by vbuns2000** [dotnet/machinelearning-modelbuilder#1222]
**System Information (please complete the following information):**
 - Model Builder 
 - Visual Studio Version (if applicable): 16.8.4

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem:
Get error when I press train button

**To Reproduce**
1. Get error when I press train button
2. See error

**Expected behavior**
Training should complete

**Screenshots**
![image](https://user-images.githubusercontent.com/15710480/107154237-2271be80-6972-11eb-9629-b99a370a0d26.png)

**Comment by beccamc** [comment]
@vbuns2000 Sorry you ran into a problem! Are you still experiencing this problem?  Are you VS instance and OS both in English? If not what language is it? Thanks!

**Comment by beccamc** [comment]
@vbuns2000 Is this still a problem? Can I have language details for your VS and machine?

**Comment by beccamc** [comment]
Closing this. Please re-open and @ mention me if this is still a problem. Thanks!
