### ISSUE TITLE
Regression from horizontal scroll turned on 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1229]
Looks like we have a few pages regress by adding the horizontal scroll. 😊 

Scenarios are now in one row: 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/1cb2497b-dbd9-482e-b580-88001614e6cf)

Data page no longer renders data preview in small box with own scroll. 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/68f57029-16be-4983-a0a3-f287e7c807a4)

I didn't look at evaluate or code pages. I think those should be fine?

**Comment by zewditu** [comment]
I think this was the fix by you https://github.com/dotnet/machinelearning-tools/pull/319/files

**Comment by beccamc** [comment]
@zewditu Yes, it looks like that was the PR I couldn't remember when we chatted in your "Small UI Fix" [PR](https://github.com/dotnet/machinelearning-tools/pull/896/files#r573235962).

**Comment by beccamc** [comment]
@zewditu I'm not certain we understood each other here. Do we agree on the problems (scenario page and text data) I described above?

**Comment by zewditu** [comment]
@beccamc  yes
