### ISSUE TITLE
consumeModelApp Crash

### ISSUE THREAD

**Issue by christianzoll** [dotnet/machinelearning-modelbuilder#1230]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: .NET Core SDK (3.1.112)
 - Visual Studio Version (if applicable): 'MacOS Catalina 10.15.7 Terminal's vi text-editor'

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
- Clear description of the problem:

**To Reproduce**
1. Go to 'MacOS Catalina 10.15.7 terminal's vi text-editor'
2. Complete Steps through Step 4 on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume using
3. Proof read step 4 
4. run dotnet run

**Expected behavior**

<img width="450" alt="Screen Shot 2021-02-17 at 2 34 13 PM" src="https://user-images.githubusercontent.com/66753884/108264806-9871e480-712d-11eb-82b3-884f40a0cb30.png">

**Screenshots**

<img width="532" alt="Screen Shot 2021-02-17 at 2 38 27 PM" src="https://user-images.githubusercontent.com/66753884/108264990-ceaf6400-712d-11eb-83f1-410e5e3d7546.png">

<img width="498" alt="Screen Shot 2021-02-17 at 2 43 09 PM" src="https://user-images.githubusercontent.com/66753884/108265492-76c52d00-712e-11eb-9952-ba087752cba0.png">

<img width="557" alt="Screen Shot 2021-02-17 at 2 44 31 PM" src="https://user-images.githubusercontent.com/66753884/108265632-a70ccb80-712e-11eb-87f6-439618d1f32b.png">

<img width="585" alt="Screen Shot 2021-02-17 at 2 43 36 PM" src="https://user-images.githubusercontent.com/66753884/108265550-88a6d000-712e-11eb-96a8-05d8f6013d76.png">

<img width="388" alt="Screen Shot 2021-02-17 at 2 45 42 PM" src="https://user-images.githubusercontent.com/66753884/108265760-d15e8900-712e-11eb-86ec-1c2b181c5258.png">

<img width="714" alt="Screen Shot 2021-02-17 at 2 46 45 PM" src="https://user-images.githubusercontent.com/66753884/108265863-f81cbf80-712e-11eb-9cb5-22e036e1f989.png">

<img width="1037" alt="Screen Shot 2021-02-17 at 2 50 54 PM" src="https://user-images.githubusercontent.com/66753884/108266298-8b55f500-712f-11eb-8be7-191309e8159e.png">

<img width="372" alt="Screen Shot 2021-02-17 at 2 48 05 PM" src="https://user-images.githubusercontent.com/66753884/108265988-269a9a80-712f-11eb-91c6-3c2047041246.png">

<img width="994" alt="Screen Shot 2021-02-17 at 2 51 57 PM" src="https://user-images.githubusercontent.com/66753884/108266411-b0e2fe80-712f-11eb-81ab-62c15bba67ad.png">

**Additional context**

**Comment by LittleLittleCloud** [comment]
This bug has already been fixed in private release and it will be published soon. For a temporary work-around, simply hard code the model path in consum.cs

**Comment by LittleLittleCloud** [comment]
The code generator in mlnet cli is in a broken state because the old code gen only support AutoML.Net while we are randomly pick both AutoML to launch trial.

**Comment by vzhuqin** [comment]
This issue not occurs on MLNET: 16.2.0.
macOS Catalina version: 10.15.7 (19H524)
![7C50984B-7B1D-4BD3-A7E9-063CAE718A84.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/647aaf5d-5583-4fab-afdb-246c6b2b69c4)
