### ISSUE TITLE
Save Button Throws Error with Re-Entrancy

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#1235]
![image](https://user-images.githubusercontent.com/31937616/108439008-4ac8ab00-7205-11eb-97b1-ee560fc96b64.png)

**Comment by JakeRadMSFT** [comment]
#1301

**Comment by vzhuqin** [comment]
This issue can be repro on environment:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps to reproduce the behavior:
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Navigate to consume page after trained;
4, See error if "Ctrl+S" to save.

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/10035b30-e21f-4a09-b006-1e407bbff0c5)

**Comment by vzhuqin** [comment]
This issue can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps:
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Close and reopen the model builder after trained;
4. No error by using "Ctrl+S" (Ctrl+Shift+S) or clicking Save (Save All) button to save on "Scenario","Environment", "Data", "Train", "Evaluate", "Consume", "Next steps" pages.
