### ISSUE TITLE
Model Builder generated code should be free of warnings and other errors.

### ISSUE THREAD

**Issue by vaibhav8600** [dotnet/machinelearning-modelbuilder#124]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version 2017

**Describe the bug**
I am trying to consume model created by model builder into windows application project 
in .netFramework 4.6.1 

**To Reproduce**

**Expected behavior**

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/49299817/60175742-0ddec200-9832-11e9-85e3-3851435df53f.png)

If `[applicable, add screenshots to help explain your problem.]( @URL)`

**Additional  #context**

**Comment by LittleLittleCloud** [comment]
Should we fix this after we take over CLI, It should be Code Generator's problem.

**Comment by justinormont** [comment]
I'd go ahead and check in a PR to the AutoML feature branch -- https://github.com/dotnet/machinelearning/tree/features/automl

**Comment by LittleLittleCloud** [comment]
It can't be reproduced on my laptop and my workstation (before it crashed) for VS 2019, VS 2019 preview and VS 2017. Let's just close that and reopen it if need
