### ISSUE TITLE
Label shouldn't be selectable twice

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1245]
1. Label shouldn't be selectable twice 
2. ~Alignment is off in this control~

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c88d8e2a-ef8f-459d-a4d1-4b5f168c12ac)

**Comment by beccamc** [comment]
Alignment fixed in https://github.com/dotnet/machinelearning-tools/pull/913

**Comment by vzhuqin** [comment]
This issue can be repro on environment:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/276f526f-57ce-49bd-b7a3-1fbc61ae2931)

Dadaset: https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt

**Comment by vzhuqin** [comment]
This issue can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps：
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Navigate to Data page after selected scenario and environment;
4. Open Advanced data options dialog, the "Save" button remain disable if you select multi "Label" purpose.

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a5e25be7-101b-4d3a-95cb-cd2c397520e5)
