### ISSUE TITLE
Can you  Please Add Name Entity recognition  feature into ML.net Model Builder

### ISSUE THREAD

**Issue by vaibhav8600** [dotnet/machinelearning-modelbuilder#125]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rustd** [comment]
Thank you for this request.

**Comment by JakeRadMSFT** [comment]
@vaibhav8600 sorry this didn't go through our normal issue handling procedures and got lost. 

Can you describe in more detail what you're trying to do?

**Comment by JakeRadMSFT** [comment]
Resolving due to lack of activity. Please re-open with more details if you're still experiencing this issue.
