### ISSUE TITLE
Model Builder UI should open and be active

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1251]
Sometimes when I right > click and add a .mbconfig from New Item Dialog, Model Builder will open in a new tab but the currently selected tab will remain active -- so user has to manually go to the Model Builder tab and open it

**Comment by JakeRadMSFT** [comment]
Reproduces if there is another file open.

**Comment by vzhuqin** [comment]
This issue can be repro on Environment:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

Steps to reproduce the behavior:

1. Create new console app with .Net 5.0;
2. Add Model builder by right click on the project;
3. See error: in editor area, the last opened file (program.cs) remains active.

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/07111a3f-a594-4300-bbda-b92505e6fde4)

One similar issue: https://github.com/dotnet/machinelearning-modelbuilder/issues/1391

**Comment by vzhuqin** [comment]
not repro this issue on: 
- Windows 10 Enterprise, Version 20H2
- **ML.Net Model Builder (Preview): 16.5.21.2122301**
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps:
1. Create new C# console app with .Net 5.0;
2. Add Model builder by right click on the project;
3. Find: In editor area, the created model builder is active even if there is another file (program.cs) open.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/94319f65-6172-42be-beaf-ce915f6a2ea2)
