### ISSUE TITLE
Everything  after training is not reset for the new scenario and Data sources

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1252]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _Select any scenario and got over all steps until train complete
2.  select a new scenario and or data set  every thing keep enabled and is not rested 

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
Duplicate
