### ISSUE TITLE
Object detection JSON Formatting help

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1253]
1. Nit: Space between text and hyperlink
2. I think we agreed to completely remove this dialog? hyperlink should link directly to docs?

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/a159f68a-0751-4d17-802b-b34837fb631d)

**Comment by beccamc** [comment]
@briacht Could you send the blog post or whatever we are linking to for this? Thanks!

**Comment by beccamc** [comment]
Additional item here. Move the support image types via Rohan [comment](https://teams.microsoft.com/l/message/19:a7c73b4892b5400aa89ff9143b2d9095@thread.skype/1618357381047?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=cc06da83-8d83-4792-a492-5dba24adfa10&parentMessageId=1617825054869&teamName=ML.NET%20Model%20Builder&channelName=Design%20Feedback&createdTime=1618357381047)

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/e76bb557-a517-46e6-8418-8712f3ab03fa)

**Comment by beccamc** [comment]
It's difficult to combine three text styles on two lines like that. I modified to this 
https://user-images.githubusercontent.com/9122518/114938100-4fc06a00-9e04-11eb-87e3-4f348b0f9441.png

**Comment by vzhuqin** [comment]
This issue can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps：
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Select "Object detection" scanario;
4. Select Azure and set up workspace;
5. Navigate to "Data" page;
6. See: 
a. have space between text and hyperlink;
b. link to docs after clicking the hyperlink;

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e7d2dd28-1cd2-4e05-bbab-9982ded391a0)
