### ISSUE TITLE
Data preview not updated after advanced options saved

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1254]
1. Select your Label
![image](https://user-images.githubusercontent.com/10437687/108441011-17881b00-7209-11eb-9338-a95021f5f2f3.png)

2. Open Advanced data options... and change that Label to a Feature. Save.
![image](https://user-images.githubusercontent.com/10437687/108441054-2f5f9f00-7209-11eb-9b42-b8e8a888c992.png)

3. Data Preview does not update
![image](https://user-images.githubusercontent.com/10437687/108441208-81a0c000-7209-11eb-88fe-637e566de67a.png)

**Comment by beccamc** [comment]
Closing this because we have removed this behavior! https://github.com/dotnet/machinelearning-tools/pull/1035
