### ISSUE TITLE
Method not found: Error

### ISSUE THREAD

**Issue by Picaso2** [dotnet/machinelearning-modelbuilder#1259]
I keep getting the error in the attached image

![image](https://user-images.githubusercontent.com/78003984/108608693-a6766e00-7396-11eb-8ec3-f5f556fd3c18.png)

I am using visual studio 2019 ver 16.8.5

I have downgrade the model builder and still got the error. 
I have re-upgrade and still the same error.
[molder builder error.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6016502/molder.builder.error.txt)

I was trying to go through ML.net tutorial text classification.
thank you for your help

**Comment by LittleLittleCloud** [comment]
Hi @Picaso2 
Did you also try other datasets or other scenarios? Does that also cause the same error?

**Comment by Picaso2** [comment]
Hi
I get the same error doing another project.

**Comment by Picaso2** [comment]
Hi
Ii have tried another set and event another computer and I still get the error.

**Comment by agausachs** [comment]
Same here. I just selected image classification, select a path with a bunch of photos, and after pressing the "train" button I received this message.
![MLIssue](https://user-images.githubusercontent.com/7044534/112348836-7dfccf00-8cc8-11eb-8ece-225b04c2bf1f.png)

**Comment by LittleLittleCloud** [comment]
@agausachs @Picaso2 
we push a preview release which should fix this bug, can you try it if had any time?

preview release url:
https://aka.ms/mb-preview/atom.xml

**Comment by agausachs** [comment]
With the preview release it's working perfect now (CPU mode, I haven't tested GPU). Thank you!

**Comment by LiQIjie** [comment]
> @agausachs @Picaso2
> we push a preview release which should fix this bug, can you try it if had any time? Please be reminded that the preview release also contains some other new features (like re-entrancy) which hasn't been documented. We are also looking forward to the feedback for these new features as well!
> 
> preview release url:
> https://aka.ms/mb-preview/atom.xml

solve my problem ,Thank you

**Comment by JakeRadMSFT** [comment]
Fixed in preview
