### ISSUE TITLE
Training time finished without any models trained

### ISSUE THREAD

**Issue by AyushSri8188** [dotnet/machinelearning-modelbuilder#1261]
Training time finished without any models trained

**Comment by beccamc** [comment]
@AyushSri8188 Sorry you ran into this problem! How long did you train for? Would you mind training for longer (maybe 60 seconds), and seeing if that fixes the problem?

**Comment by beccamc** [comment]
@AyushSri8188 any luck training for longer?

**Comment by beccamc** [comment]
Closing this. Please re-open and @ mention me if this is still a problem. Thanks!
