### ISSUE TITLE
Advance option dark theme doesn't work

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1264]
![image](https://user-images.githubusercontent.com/16876986/108915118-48899680-75e1-11eb-9d35-76efa0f07755.png)

**Comment by vzhuqin** [comment]
This issue can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps：
1. Set to dark theme and create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Navigate to "Data" page and open "Advanced data options" dialog, the styling is normal as below screenshot.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/09905488-9b4a-4846-bc37-6a32dd10c475)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3781e604-a75b-4008-945d-c15ff600d708)
