### ISSUE TITLE
Artifact from previous training. is not correctly clear 

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1265]
# Step to reproduce
- complete a train
- exit
- re-enter, change some settings and exit
- re-enter, the train page is still enabled. and it's showing the previous training.

![image](https://user-images.githubusercontent.com/16876986/108915374-a9b16a00-75e1-11eb-938d-b1fddf80afee.png)

**Comment by beccamc** [comment]
Closing this as 1271 is a duplicate
