### ISSUE TITLE
Environment IsComplete state not updating

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1267]
1. Image Classification
2. Select Local CPU
3. Select data
4. Return to environment page. Change to Azure. Environment isn't set up but "Next steps" are enabled. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/e22fa275-94e6-40d3-83df-811b134fd37a)

**Comment by vzhuqin** [comment]
@beccamc I can repro this issue on main branch: 16.5.25.2130702
![Repro 1267.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/fbf63ecf-6914-4f37-8391-914d073046a6)

**Comment by beccamc** [comment]
Thanks Qin!
