### ISSUE TITLE
IsCatagorical value not corrected infered

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1273]
Dataset: titanic.
The 'Sex' Column should be classified as catagorical, which it isn't.

![image](https://user-images.githubusercontent.com/16876986/108919142-5b06ce80-75e7-11eb-93af-91dbe965b072.png)

**Comment by beccamc** [comment]
This seems to be a regression. Treating as P0 because I think customers will reasonably expect this to work.

**Comment by LittleLittleCloud** [comment]
![image](https://user-images.githubusercontent.com/16876986/110159764-f7776080-7d9f-11eb-975d-c10f3944bdb1.png)
