### ISSUE TITLE
Unintended Page Navigation

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1276]
didn't get a screenshot...

1. Train images
2. Click "Retrain"
3. We show an error message warning about losing progress. **It also jumps back to the Data page**

----

1. Re-Open MB and click Predict on Evaluate page - Jumps back to Scenario
2. Retrain button -  Jumps back to Data Page

**Comment by beccamc** [comment]
The consistent repro here is to: Reload MB -> Click Train Tab via left nav -> Click Evaluate via left Nav -> Click predict button. This triggers a set of the `SelectedNavigationTabIndex` _from the framework_.

Things I have tried....
- :x: Breakpoints on the click handler for the predict button to ensure the event doesn't bubble up. The predict button click handler executes after the SelectedNavigationTabIndex set.
- :x: Maybe IsEnabled is getting toggled so the focus jumps back? The GetCompletedTab update handler doesn't execute AND the ProgressToEnabled converter doesn't execute. 
- :grey_question: Some focus property isn't being removed from the Train tab when navigating via the left nav. Biggest data point here is if you click DATA tab -> Train tab -> then on predict click it jumps back to the DATA tab. Maybe some previous focus isn't being removed?

Edit: I have finally received confirmation of this! Using snoop I inspected the UI. Here you can see "Evaluate" is selected, while "IsFocused" is still on the Train tab! 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/5935eac1-5250-4326-a59e-3fb153693224)

**Comment by vzhuqin** [comment]
This issue can be repro on: 
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

Steps to reproduce the behavior:
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. After trained;
4. Closed and Reopen the model builder;
5. Navigate to Data page, **re-input the data**;
6. Navigate to Train page, click "Start training" button, jump to Data page;
7. Navigate to Evaluate page and click "Predict" button after trained, jump to Data page;

**Comment by vzhuqin** [comment]
This issue can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps:
- After trained
1. Click "Train again"  ->no jump back to other page;

- Close and reopen model builder after trained:
1. Click Predict on Evaluate page -> no jump back to other page; 
2. Then navigate to Train page, click "Train again"->no jump back to other page.

- Navigate to Data page after trained, re-input the data;
1. Navigate to Train page, click "Train again" button, -> no jump back to other page; 
2. Navigate to Evaluate page and click "Predict" button after trained,-> no jump back to other page.
