### ISSUE TITLE
Add to solution keep continues to say Generating.. for azure environment training

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1279]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/5be7e16b-ee8b-4bb8-9f37-9a88be7e3949)

**Additional Context**

**Comment by zewditu** [comment]
I think this one regressed by https://github.com/dotnet/machinelearning-modelbuilder/issues/1278

**Comment by vzhuqin** [comment]
Can repro this issue on Main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps:
1). Prepare the JSON file according to: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#create-a-new-vott-project
2). Create new C# console app with .Net 5.0;
3). Add model builder by right click on the project;
4). Click "Object detection" on Scenario page to navigate to Environment page;
5). Select Azure and set up workspace on Environment page;
6). Click "..." to input the JSON file;
7). Click "Start training" on Train page, and wait Training complete;
8). Navigate to Consume page, click "Add to solution" after Web API, the sample WebApi project can be added;
9). Click "Add to solution" after Console app, show "Adding.." message with Model Builder Error.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ee0c136d-cbb7-484b-8ad0-755f4537c69b)
10). Close the error dialog, keep showing the message " Adding.. ".
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/913c12a8-a3fc-40bc-b0bb-0928c2724599)

**Comment by vzhuqin** [comment]
This issue not repro on main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122903
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Can add the console app and web api projects successfully.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/81530a8d-0806-4956-a030-f01b19ebae71)
