### ISSUE TITLE
CLI Hand Off

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#128]
[Repo](https://github.com/dotnet/machinelearning/tree/features/automl) Here
[build pipeline](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=8739&_a=summary) Here

- [x] Migrate source  to machinelearning-tools repo and solution
- [x] Migrate build to MicroBuild
- [x] Pull out CodeGen into shared library
- [ ] Update ModelBuilder to use CodeGen Library
- [ ] Transfer issues from CLI repo to this repo

**Comment by LittleLittleCloud** [comment]
Going to work on "Migrate source to machinelearning-tools repo and solution" and "Migrate build to MicroBuild"

**Comment by LittleLittleCloud** [comment]
on task 3, maybe a better way is to create public interface to code generator and add reference to mlnet in model builder, due to the fact that code generator is so cohesive with cli.

any suggestion? @JakeRadMSFT @tbombach

**Comment by LittleLittleCloud** [comment]
Going to work on task 3 and 4 now

**Comment by JakeRadMSFT** [comment]
Please hold off until we discuss where CLI and ModelBuilder lives going forward.
