### ISSUE TITLE
Tab should reflect dirty state like other tabs/designers

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#1284]

**Comment by vzhuqin** [comment]
@JakeRadMSFT could you help to provide more details to validate this issue? on which Scenario? Environment? Data? or repro steps?

**Comment by JakeRadMSFT** [comment]
@vzhuqin before this was fixed the "Document" tab never showed that it was "dirty" - meaning that it had unsaved changed.

For testing, Can you verify that the document shows that it has unsaved changes at expected times? Essentially anytime that the .mbconfig file should change when saved.

**Comment by vzhuqin** [comment]
This issue cannot be repro on main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122903
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Un-saved:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4b993d56-9f69-4f77-83b1-afbbabc2f848)
Try to close if un-save status
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/24fe5060-f0a8-4927-957a-0359e8d5cdc3)
Saved:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/91ca8deb-a67e-4acd-a0eb-5b227527f5df)

mbconfig file has changed after saved.
