### ISSUE TITLE
Combo Boxes in Data page and Azure dialog window  `AutomationProperties.LabeledBy `  property should set for visible Label element  

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1285]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
This is regression due to WPF and accessibility bug in Combo box 
https://github.com/dotnet/machinelearning-modelbuilder/issues/1206

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by zewditu** [comment]
Temporary fixes are done by https://github.com/dotnet/machinelearning-tools/pull/932 and https://github.com/dotnet/machinelearning-tools/pull/878/files

**Comment by beccamc** [comment]
Closing this as I've removed the work around.
