### ISSUE TITLE
Image training reentrancy doesn't work

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1287]

**Comment by beccamc** [comment]
It is reloading the Azure information! Adding a basic loading experience.

**Comment by vzhuqin** [comment]
@beccamc @LittleLittle
1. Could you help to provide the image-classification test matrix to validate this issue? 
2. Which training environment should be selected on Environment page? Azure?

**Comment by beccamc** [comment]
1. Any Image set should work. Do you have an image folder for other testing? If not I can provide one
2. It should work for both local and Azure environments. 

Let me know if that doesn't help

**Comment by vzhuqin** [comment]
@beccamc I don't have any image folder for testing, could you help to provide the image test matrixes for both local and Azure Environment?

**Comment by vzhuqin** [comment]
**Met some issues for re-entrancy image classification model builder, could you please take a look?**

Main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Azure Steps:
1). Download dataset from: https://testpass.blob.core.windows.net/test-pass-data/weather.zip
2). Create new C# console app with .Net 5.0;
3). Add model builder by right click on the project;
4). Click "Image classification" on Scenario page;
5). Select Azure and set up workspace on Environment page;
6). Click "..." to select a folder on Data page;
7). Click "Start training" on Train page, and wait Training complete;
8). Saved and closed the model builder;
9). Reopen the model builder, see:
a. prompt model builder error;
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/8fbcdfe3-5711-4de0-833f-b6e164e5a988)
b. closed the error dialog, navigate to Environment page, see the workspace information lost;
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ac77d446-2e63-4c10-a018-cc48112f1b20)
c. Navigate to Consume page, the code snippet lost (dark theme);
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e84f167b-d4bf-4e1f-9e1a-d6cf6c8a43f1)


Local Steps:
1). Download dataset from: https://testpass.blob.core.windows.net/test-pass-data/weather.zip
2). Create new C# console app with .Net 5.0;
3). Add model builder by right click on the project;
4). Click "Image classification" on Scenario page;
5). Select Local (CPU) on Environment page;
6). Click "..." to select a folder on Data page;
7). Click "Start training" on Train page, and wait Training complete;
8). Saved and closed the model builder;
9). Reopen the model builder, see: the code snippet lost (dark theme) on consume page;
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/8e163743-0f1a-4cf7-bd96-7f38a151199d)

**Comment by vzhuqin** [comment]
Tracking "Model Builder Error" on: Model Builder error occurs on the process of model builder for Azure. #1406
Tracking "code snippet lost" on: The code snippet on Consume page should not lost after added to solution and re-opened. #1417

No other rentrancy issue on main branch: 
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.5
- .Net: 5.0.202

Local (CPU):
![ImageLocalReentrancy.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/bc961b04-b9ab-4fa1-b0d4-36a2da664da0)
Azure:
![ImageAzureReentrancy.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/8afb9e3c-66e1-49ec-a72b-c706dcf01718)
