### ISSUE TITLE
Fix train error message if incorrect data type selected

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1290]
If a user changes the data type of a column which does not make sense (e.g. setting data type to Single for a column that only has strings), then the error message on train should be more descriptive than:

![image](https://user-images.githubusercontent.com/10437687/109215483-122a5380-7768-11eb-8f29-b40df5a081bc.png)

More like:

Input column "payment_type" cannot be a Single. Try changing the Data Type in Advanced Data Options.

**Comment by beccamc** [comment]
@beccamc To look at current experience for next weeks' triage meeting.

**Comment by beccamc** [comment]
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/f29eb8f0-f8b0-4ce4-a80f-9aea33cec90f)

**Comment by beccamc** [comment]
This has regressed, it's supposed to look like this: 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/257ca0dc-207c-48ab-b989-153eefb35ec7)

Regressed from this [PR](https://github.com/dotnet/machinelearning-tools/pull/1050)
