### ISSUE TITLE
Consume code control styling

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1292]
The large amount of gray padding on the top of this looks wrong to me 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/48be49e8-566e-4560-b391-44c623add47a)

Additionally, what is the status of user set coloring and font?  If these items won't make it, can we at least change the font to the default  Consolas. This doesn't look like a code snippet to me right now.

**Comment by zewditu** [comment]
Regarding use of colorization and font thing under follow-up to leverage other teams work  , currently we could  not get the effort  we can leverage. However , other teams like  Thomas Bombach have the same issue. The next step will be  follow up to get something to work.

**Comment by vzhuqin** [comment]
**No the status of user set coloring and font, will validate this on Next Private Preview.**

Some issues can't be repro on Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps：
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. After trained;
4. Navigate to Consume page, see: 
a. no large amount of gray padding on the top;
b. added "Code snippet:", "Copy" text on the top;

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/417dbddc-f79a-4215-a8d8-2253618d8b10)

**Comment by beccamc** [comment]
I'm going to close this issue. We can validate the new coloring when Zewditu is able to implement the feature. Thanks Qin!
