### ISSUE TITLE
SQL doesn't work with SQL Server Auth

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#1293]
SQL doesn't work with SQL Server Auth. 

After setting up connection MB shows this error:

![image.png](https://images.zenhubusercontent.com/5cde1c65e3106e39e8ae08f2/bdb5bdf6-4c0b-4244-abee-e2ab18f234ab)

**Comment by JakeRadMSFT** [comment]
https://github.com/dotnet/machinelearning-tools/pull/875/files

**Comment by beccamc** [comment]
@JakeRadMSFT For this one, training from your azure sql db was still failing, but it wasn't because of the auth.
