### ISSUE TITLE
mlnet command not found 

### ISSUE THREAD

**Issue by youseeshadowman** [dotnet/machinelearning-modelbuilder#1295]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 5.0
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: am running a command to train my model but i get an error, bash: mlnet: command not found

**To Reproduce**

**Expected behavior**

**Screenshots**
/home/spider/Desktop/Link to Screenshot at 2021-02-26 14-42-34.png
![Screenshot at 2021-02-26 14-42-34](https://user-images.githubusercontent.com/76045795/109296683-cba92780-7841-11eb-8815-b52ff4eb2ce6.png)

**Additional context**

**Comment by LittleLittleCloud** [comment]
Which shell are you using, if you are using a zsh-based command, the dotnet tool path will not be auto-added.

Could you check your $Path Variable and make sure the path to dotnet tool is added? Usually it should be $(User).dotnet\tools

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you have any questions.
