### ISSUE TITLE
Change tooltip strings

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1298]
Data:

**-Column to Predict (Label):**

"This is the target column which is the output of the model, or what you want the model to predict."

 

**-Features (no longer has tooltip); if we add it back:**

"These are the input columns for the model which contribute to the final prediction. Choosing features which are most relevant to the problem will help build a better model."

 

**-Column to Predict (Rating):**

"This is the target column which is the output of the model, or what you want the model to predict. For the recommendation scenario, this is a numerical rating of an item."

 

**-User column:**

"This is the column which represents who is giving the rating to an item. For the recommendation scenario, the model will recommend items for users based on which items have the highest ratings."

 

**-Item column:**

"This is the column which contains the 'thing' that is rated by a user. For the recommendation scenario, the model will recommend items for users based on which items have the highest ratings."

 

Train:

**-Time to train (seconds)**

"Model Builder automatically chooses a train time based on your dataset size. Longer training periods allow Model Builder to explore more models with a wider range of settings which can result in a better model."

**Comment by beccamc** [comment]
https://teams.microsoft.com/l/message/19:a7c73b4892b5400aa89ff9143b2d9095@thread.skype/1611860993450?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=cc06da83-8d83-4792-a492-5dba24adfa10&parentMessageId=1611860993450&teamName=ML.NET%20Model%20Builder&channelName=Design%20Feedback&createdTime=1611860993450

-Column to Predict (Label):

"This is the target column that you want the model to predict."


 

-Features (no longer has tooltip); if we add it back:

"These are the input columns for the model which contribute to the final prediction. Choosing features which are most relevant to the problem will help build a better model."


 

-Column to Predict (Rating):

"This is the target column that you want the model to predict.”


>>>>> Can we be smart and for Recommendation scenario update the string to reflect something like this….

"This is the numerical rating of an item you want the model to predict.”


 

-User column:

"This is the column which represents who is giving the rating to an item. The model will recommend items for users based on which items have the highest ratings."

 
-Item column:

"This is the column which contains the 'thing' that is rated by a user. The model will recommend items for users based on which items have the highest ratings."


Train:

-Time to train (seconds)

"Model Builder automatically chooses a train time based on your dataset size. Longer training periods allow Model Builder to explore more models with a wider range of settings which can result in a better model."

**Comment by beccamc** [comment]
Changing all except "Features". Features doesn't exist as a drop down anymore. This would need to be added to the Advanced Data Options dialog. Can add later if we improve the dialog.

**Comment by vzhuqin** [comment]
**The period is missing at the end of the "User column:" tooltip.**
- User column:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0c5e44a8-b5ab-46d0-a4f9-57f40d922e87)

Other 4 tooltips strings have been changed on main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Screenshots:
- Column to Predict (Label):
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9d592da9-547a-4b44-adcc-0386bc5cfadc)
- Column to Predict (Rating):
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0b212631-60a0-418f-b036-bad6facaed4e)

- Item column:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/716f8977-cb35-4815-83ea-c6fe893831a1)

- Time to train (seconds):
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/c3449952-733f-4ccb-9602-277da3528fc7)

**Comment by beccamc** [comment]
Checked in a fix in this PR https://github.com/dotnet/machinelearning-tools/pull/1030. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/b92695d2-58e3-4d10-b0ff-0e8e365dd4b7)

I'm just going to close this, I don't think we need to waste resources re-verifying. Thanks for catching Qin!
