### ISSUE TITLE
text gets cut off in Evaluate

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1302]
I used this dataset for text classification: https://www.kaggle.com/teejmahal20/airline-passenger-satisfaction?select=train.csv

Here are the Labels:
![image](https://user-images.githubusercontent.com/10437687/109696421-e3cebe80-7b41-11eb-8846-82930e57ebdc.png)

Here is what it looks like in Try your model:
![image](https://user-images.githubusercontent.com/10437687/109696534-0660d780-7b42-11eb-89f3-96d173016960.png)

**Comment by vzhuqin** [comment]
Verify this issue on latest main build: 16.7.0.2137701
I’m not sure if there will be such a long title, but I did name a very long one to verify the problem, find that there is not enough space to show the long title on Evaluate page. Could you help to take a look again?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/25a347f2-b05b-472c-b2b9-829af375b339)

**Comment by beccamc** [comment]
@zewditu Can you take a look here, and if it's a quick fix add the tooltip?

**Comment by LittleLittleCloud** [comment]
@beccamc @zewditu 
Is there any update on this issue?

**Comment by vzhuqin** [comment]
@beccamc @zewditu any update?

**Comment by zewditu** [comment]
@vzhuqin I will look into it.

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.9.1.2156904

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/df2740ca-543f-4b32-b8cd-12dae113c8b9)
