### ISSUE TITLE
use drop-downs for Categorical features instead of free text

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1303]
In Try your model, use drop-downs for Categorical features instead of free text

For example:
![image](https://user-images.githubusercontent.com/10437687/109697490-20e78080-7b43-11eb-9c9b-c06ce7527d1b.png)

![image](https://user-images.githubusercontent.com/10437687/109698604-6eb0b880-7b44-11eb-86ac-f4acfcc508c3.png)

**Comment by beccamc** [comment]
One thing to note about this, how much of the file do we want to scan to find all the possibilities? Right now we read 200 rows, but this might not be enough to find all the options for a drop down.

**Comment by beccamc** [comment]
This feature is P2 and won't be done for a while. Adding it to the Evaluate tab bugs p1/p2
