### ISSUE TITLE
image classification eval/try model doesn't work

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1304]
I added a new item, trained local image classification with CPU with this dataset:
https://www.kaggle.com/jeffheaton/iris-computer-vision

After training, in Evaluate page, I tried to test several images, but keep getting this error:
![image](https://user-images.githubusercontent.com/10437687/109729417-b0edf000-7b6c-11eb-94e0-4f88c90fea6b.png)

**Comment by JakeRadMSFT** [comment]
Resolved
