### ISSUE TITLE
Allow Sql Server Connection Settings to be Saved

### ISSUE THREAD

**Issue by carterlist** [dotnet/machinelearning-modelbuilder#1307]
**Is your feature request related to a problem? Please describe.**
When trying to develop a model, I connect to the same database server and database several times. I find this repetitive and unproductive.

**Describe the solution you'd like**
 It would be great to auto-save  the last sql server connection or even allow users save a couple of connection strings.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a
![image](https://user-images.githubusercontent.com/20445410/110134817-d01e9480-7d9b-11eb-8d62-8cbeba16009a.png)

**Comment by beccamc** [comment]
@carterlist Thanks for the feedback! In our next release of Model Builder (shipping this month) everything will be based on a config file. Our SQL config file will save a connection string and a command string. I'll update this issue when we ship and you can give us feedback on how it works.

**Comment by beccamc** [comment]
@carterlist We have a new build ready. Please try it out and let use know what you think! https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by beccamc** [comment]
This has shipped, closing this issue. Please re-open or file a new issue if you have comments! Thank you!
