### ISSUE TITLE
Cannot use local gpu environment for old preview model builder image classification 

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#1308]
**System Information (please complete the following information):**
 - Model Builder Version: 16.3.0.2056001

Opening issue from @philipbawn based on docs issue dotnet/docs#23111

Original Description:

I have model builder 16.3.0.2056001 and ml.net model builder gpu support version 16.3.0.2056001, I installed cuda_10.0.130_411.31_win10.exe from nvidia and extracted cudnn64_7.dll from cudnn-10.0-windows10-x64-v7.6.4.38.zip from nvidia, placing it in C:\program files\nvidia gpu computing toolkit\cuda\v10.0\bin\ - yet my visual studio looks like this when I try to progress adding image classification to a project.
![image](https://user-images.githubusercontent.com/10352261/110003857-a9912880-7ccb-11eb-8896-53ad9c974b02.png)

The model builder would let me proceed with cpu only:
![image](https://user-images.githubusercontent.com/10352261/110003928-bca3f880-7ccb-11eb-8871-579f68c6a17e.png)

**Comment by beccamc** [comment]
@JakeRadMSFT and @LittleLittleCloud Is this solved now?

**Comment by JakeRadMSFT** [comment]
Yes and docs are updated thanks to @luisquintanilla :)

**Comment by philipbawn** [comment]
@JakeRadMSFT @LittleLittleCloud @luisquintanilla  Thank you so much, the preview I downloaded today detected my GPU and informed me which version of cuda I need to install. You rock.
