### ISSUE TITLE
Proper description based on project number

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1309]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/e221ada5-17ed-4a3a-860b-ca86d3bee212)_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by vzhuqin** [comment]
This issue can't be repro on main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Have two sample projects (Console app and Web API) on Consume page, "Sample project**s**" is expected.

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/c892cc1b-db36-4925-954a-78f980a7a852)
