### ISSUE TITLE
Visual Studio Closing automatically

### ISSUE THREAD

**Issue by AkhilSynmax** [dotnet/machinelearning-modelbuilder#131]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/train
Operating System: windows

![Error](https://user-images.githubusercontent.com/50869926/58090686-73151700-7be5-11e9-9421-93cd28a798ca.PNG)

**Comment by rustd** [comment]
Just check that if the user uploads a .zip file, we don't crash VS.

**Comment by greazer** [comment]
Model Builder: 16.0.1907.1101
Dataset: wikipedia-detox-250-line-data.txt
Tested trying to supply a zip file as a csv or tsv is blocked by the UI
Trying crazy thing to modify the extension of the zip to txt causes a legit error (can't split data into multiple columns)

Not sure what else to try to make this happen.


@AkhilSynmax , we cannot reproduce this problem. If you are still experiencing it with the latest version of model builder, please reopen.
