### ISSUE TITLE
Boolean data type columns didn't get the right  C# value in Consumption.cs

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1313]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/0cbb26b1-2fe6-4a1a-ba79-c5fc39a4637f)_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by zewditu** [comment]
This issue is caused by Convert.ToString(value) when the value is a boolean type. It returns "True" or "False" which is not the right C# boolean value,  https://docs.microsoft.com/en-us/dotnet/api/system.boolean.truestring?view=net-5.0

**Comment by vzhuqin** [comment]
This issue can be repro on environment:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.202

Steps to reproduce the behavior:
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Select "Text classification" scenario and Local (CPU);
4. Select file and browse the dataset, select "Sentiment" as Label;
5. Click "Start training" on Train page;
6. Click "Predict" button on Evaluate page;
7. Click "Add a solution" on Consume page;
8. Run the sample console app project;
9. See error: 
Build started...
1>------ Build started: Project: 1313MLModel1ConsoleApp, Configuration: Debug Any CPU ------
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(9,11,9,16): error CS1001: Identifier expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(6,11,6,16): error CS1001: Identifier expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(11,11,11,16): error CS1001: Identifier expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(9,16,9,33): error CS0116: A namespace cannot directly contain members such as fields or methods
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(9,11,9,16): error CS1514: { expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(10,1,10,2): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(11,26,11,31): error CS1001: Identifier expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(11,26,11,31): error CS1514: { expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(11,26,11,31): error CS1513: } expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(11,26,11,31): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(11,31,11,38): error CS0116: A namespace cannot directly contain members such as fields or methods
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(12,5,12,6): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(66,1,66,2): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(6,16,6,33): error CS0116: A namespace cannot directly contain members such as fields or methods
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(6,11,6,16): error CS1514: { expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(7,1,7,2): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(11,16,11,33): error CS0116: A namespace cannot directly contain members such as fields or methods
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(11,11,11,16): error CS1514: { expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(12,1,12,2): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(13,26,13,31): error CS1001: Identifier expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(13,26,13,31): error CS1514: { expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(13,26,13,31): error CS1513: } expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(13,26,13,31): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(13,31,13,38): error CS0116: A namespace cannot directly contain members such as fields or methods
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(14,5,14,6): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(42,1,42,2): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(13,14,13,21): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(13,50,13,55): error CS1526: A new expression requires an argument list or (), [], or {} after type
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(13,50,13,55): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(13,55,13,62): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(13,75,13,75): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(15,29,15,30): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(15,29,15,30): error CS1513: } expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(16,115,16,116): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(16,115,16,116): error CS1513: } expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(17,44,17,45): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(17,44,17,45): error CS1513: } expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(21,37,21,44): error CS1002: ; expected
1>Done building project "1313MLModel1ConsoleApp.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
Build started...
1>------ Build started: Project: 1313MLModel1ConsoleApp, Configuration: Debug Any CPU ------
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(9,11,9,16): error CS1001: Identifier expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(6,11,6,16): error CS1001: Identifier expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(11,11,11,16): error CS1001: Identifier expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(9,16,9,33): error CS0116: A namespace cannot directly contain members such as fields or methods
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(9,11,9,16): error CS1514: { expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(10,1,10,2): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(11,26,11,31): error CS1001: Identifier expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(11,26,11,31): error CS1514: { expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(11,26,11,31): error CS1513: } expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(11,26,11,31): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(11,31,11,38): error CS0116: A namespace cannot directly contain members such as fields or methods
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(12,5,12,6): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.consumption.cs(66,1,66,2): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(6,16,6,33): error CS0116: A namespace cannot directly contain members such as fields or methods
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(6,11,6,16): error CS1514: { expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(7,1,7,2): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(11,16,11,33): error CS0116: A namespace cannot directly contain members such as fields or methods
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(11,11,11,16): error CS1514: { expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(12,1,12,2): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(13,26,13,31): error CS1001: Identifier expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(13,26,13,31): error CS1514: { expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(13,26,13,31): error CS1513: } expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(13,26,13,31): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(13,31,13,38): error CS0116: A namespace cannot directly contain members such as fields or methods
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(14,5,14,6): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\1313MLModel1.training.cs(42,1,42,2): error CS1022: Type or namespace definition, or end-of-file expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(13,14,13,21): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(13,50,13,55): error CS1526: A new expression requires an argument list or (), [], or {} after type
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(13,50,13,55): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(13,55,13,62): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(13,75,13,75): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(15,29,15,30): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(15,29,15,30): error CS1513: } expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(16,115,16,116): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(16,115,16,116): error CS1513: } expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(17,44,17,45): error CS1002: ; expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(17,44,17,45): error CS1513: } expected
1>C:\Users\v-zhuqin\source\repos\Validation\1313MLModel1ConsoleApp\program.cs(21,37,21,44): error CS1002: ; expected
1>Done building project "1313MLModel1ConsoleApp.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3859c6db-72f3-4402-b571-50b21234a07b)

Dataset: 
https://raw.githubusercontent.com/dotnet/machinelearning/main/test/data/wikipedia-detox-250-line-data.tsv

**Comment by vzhuqin** [comment]
Can be repro on: ML.Net Model Builder (Preview): 16.5.21.2122301
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ee176865-c113-499f-89b0-cf9e779c84d9)

Dataset:
https://raw.githubusercontent.com/dotnet/machinelearning/main/test/data/wikipedia-detox-250-line-data.tsv

**Comment by vzhuqin** [comment]
This issue not repro on Main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122903
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/072d093c-734e-4fc1-b091-c4084578abd0)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/001c4346-ec87-4c07-a41e-a51b804a615a)

Dataset:
https://raw.githubusercontent.com/dotnet/machinelearning/main/test/data/wikipedia-detox-250-line-data.tsv
