### ISSUE TITLE
Consume page code not selectable

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1314]
1. I am able to hit the copy button, but I can't select in the box itself to highlight and copy the code

![image](https://user-images.githubusercontent.com/10437687/110364543-c3e34300-7ff8-11eb-9928-2b346b9d6d82.png)

2. Also, when I hit the copy button, there is no feedback at all that I have copied the code snippet. When I hover, there is a blue highlight which I don't think is supposed to be there? @romalpani 

![image](https://user-images.githubusercontent.com/10437687/110365485-f3df1600-7ff9-11eb-9801-d5a5e19f5769.png)

3. Also, can we add color to the code snippet? Is it possible to hardcode color values since we know exactly what we'll be generating? I think it takes away from the modern design-- there's something just off about it.

**Comment by JakeRadMSFT** [comment]
Please work with @briacht and @romalpani for updated design (or Tomas to use the .NET Editor Control thing from .NET Interactive Window)

**Comment by romalpani** [comment]
Please find updated designs on this Figma file. I've discussed the interactions of the "copy" button to mitigate the issues accounted for here. 
https://www.figma.com/file/bhdPADawiO4YQGdUNExiUc/?node-id=1%3A133

**Comment by vzhuqin** [comment]
This issue can be repro on environment:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b9937980-58eb-49e1-a61a-bdba56461cc2)

**Comment by vzhuqin** [comment]
The first two points can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps to reproduce the behavior:
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. After trained;
4. Navigate to consume page: 
a. can select in the box itself to highlight and copy the code;
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/379140b1-61bb-4087-a7af-87419e723999)
b. changed to "Copied" after click "Copy" icon.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e0661292-7405-4b92-b4c2-0d4ad914e6eb)


But for the 3 point, no add color to the code snippet.

**Comment by vzhuqin** [comment]
for the third point, no add color to the code snippet on main branch:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.5
- .Net: 5.0.202
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b88b9cc5-a27c-4016-bdea-58fdf29eb049)

**Comment by beccamc** [comment]
@zewditu Is there a different issue tracking the color of the code snippet?

**Comment by LittleLittleCloud** [comment]
copy works, feel free to move this issue to ready to ship.

**Comment by beccamc** [comment]
Closing this - issue for colorization has been opened. https://github.com/dotnet/machinelearning-modelbuilder/issues/1509
