### ISSUE TITLE
Theming  in advanced data options 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1315]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/18bbd153-a6a5-4a63-8c7b-5d8b5697bdaa)_

![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/101ba678-3f45-4c5f-8cc8-e6ac999cb15b)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by LittleLittleCloud** [comment]
dup of #1264

**Comment by beccamc** [comment]
Closed as dupe
