### ISSUE TITLE
ModelInput shouldn't include label value

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1319]
"Survived" shouldn't include
![image](https://user-images.githubusercontent.com/16876986/110545597-30863c80-80e2-11eb-91c3-08eecd658dba.png)

**Comment by vzhuqin** [comment]
This issue can't be repro on main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps：
1). Download data set from: https://raw.githubusercontent.com/dotnet/machinelearning/main/test/data/taxi-fare-train.csv
2). Create new C# console app with .Net 5.0;
3). Add model builder by right click on the project;
4). Click "Value prediction" on Scenario page to navigate to Environment page;
5). Select Local (CPU) on Environment page;
6). Select File and click "Browse..." to input the downloaded dataset, set "fare_amount" to "Column to predict (Label)" on Data page;
7). Click "Start training" with default 600s train time on Train page, and wait Training complete;
8). Click "Predict" button on Evaluate page;
9). Navigate to Consume page, find that the label column "fare_amount" doesn't list in the ModelInput.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9abd299c-b12c-432c-9c81-ca11dc0d5ea8)

Below is the copied code snippet:
//Load sample data
var sampleData = new 1323_MLModel1.ModelInput()
{
    Vendor_id = @"CMT",
    Rate_code = 1F,
    Passenger_count = 1F,
    Trip_time_in_secs = 1271F,
    Trip_distance = 3.8F,
    Payment_type = @"CRD",
};
 
 //Load model and predict output
 var result = 1323_MLModel1.Predict(sampleData);
