### ISSUE TITLE
No Machine learning in add drop down list

### ISSUE THREAD

**Issue by RodrickRK** [dotnet/machinelearning-modelbuilder#132]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/create
Operating System: windows
 There is no option to select machine learning in the add list. I have updated to the latest visual studio and I've installed the plugin in twice.

**Comment by rustd** [comment]
Please re-open with more details if the issue can be reproduced.
