### ISSUE TITLE
"Added to solution" button doesn't work with dark theme

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1320]
![image](https://user-images.githubusercontent.com/16876986/110545750-6b887000-80e2-11eb-98d3-d02c21aabffc.png)

**Comment by vzhuqin** [comment]
This issue can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps：
1. Change to dark theme;
2. Create new C# console app with .Net 5.0;
3. Add model builder by right click on the project;
4. Value prediction>Local (CPU)>Data (File: taxi-fare-train.csv);
5. Click "Add to solution" after Web API on consume page after trained;
6. The message has changed, final changed to "Add again" after added one project and can be clicked with dark theme.

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/54e73d9a-8ea9-4e1b-8430-b90d9200d494)
