### ISSUE TITLE
Train page: Output window still shows 'Code generated' section

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#1321]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5.0.2115801
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue: Train page
- Clear description of the problem: After training is complete, the output window shows "Code generated" section. This will not be needed anymore since the Consume page now has a code-snippet section for customers to use instead. 

**To Reproduce**
1. Go to 

**Expected behavior**
Code generated section not needed in the output window on Train page.

**Screenshots**

![image](https://user-images.githubusercontent.com/48927690/110546316-2b75bd00-80e3-11eb-8e53-efdab6a9a320.png)

**Additional context**

**Comment by vzhuqin** [comment]
Validate this issue on Main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

**After trained, find the Code generated section shows in Output window, but the messages have changed.**
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/1882625e-ebc2-405f-8d55-9302c14a41ac)
@zewditu , as I can't access the referenced issue https://app.zenhub.com/workspace/o/dotnet/machinelearning-tools/issues/972 to get more information, could you help to confirm whether the changed Code generated part is expected?

**Comment by romalpani** [comment]
The "code generated" section is not needed in the output window on the Train page, including the title 'code generated'.
@briacht could you please confirm this?

**Comment by vzhuqin** [comment]
Repro on Main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122903
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202


![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/d65e1acf-f012-4a03-b4be-8e0b3b7b0e68)

**Comment by LittleLittleCloud** [comment]
Still reproducable

@zewditu can you take a look?

**Comment by zewditu** [comment]
I think the original intention of adding "Code generated"  is to update the status of the generation of code-behind files. @romalpani   why we need to remove it, is that because of the redundancy of info(we already have it in the main window)?
Generate code-behind files.

![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/86bc21ad-ce42-46da-a3dd-309a03002180)

**Comment by romalpani** [comment]
If the sentences highlighted in the above screenshot are like bookends to what's happening between them, then yes, we can maintain it. My understanding before was that "Code generated" was for the "consume code", not code-behind files. 

Since we are at it, could we perhaps update the copy there to reflect exactly what's happening...
E.g.,

**Generating code-behind files**

-----
-------
------
-----------
--------
-----

**Code-behind files generated**


Thoughts @briacht ?

**Comment by vzhuqin** [comment]
The "Code generated" was removed on main branch:  16.6.1.2132901
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/95c689ea-edea-4f20-96f6-63e8343d0002)
