### ISSUE TITLE
Consume page: 'Add to solution' should behave like hyperlink

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#1322]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5.0.2115801
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue: Consume page
- Clear description of the problem: The 'Add to solution' hyperlinks on the sample project boxes should behave like any other hyperlink. Currently, it is showing a blue background box around it on-hover. 

**To Reproduce**

**Expected behavior**
"Add to solution" should have the same hyperlink properties as in other places in VS.

**Screenshots**
![image](https://user-images.githubusercontent.com/48927690/110546605-8f988100-80e3-11eb-95d7-dd7bd1c92578.png)

**Additional context**

**Comment by vzhuqin** [comment]
This issue can't be repro on main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps：
1). Download data set from: https://raw.githubusercontent.com/dotnet/machinelearning/main/test/data/taxi-fare-train.csv
2). Create new C# console app with .Net 5.0;
3). Add model builder by right click on the project;
4). Click "Value prediction" on Scenario page to navigate to Environment page;
5). Select Local (CPU) on Environment page;
6). Select File and click "Browse..." to input the downloaded dataset, set "fare_amount" to "Column to predict (Label)" on Data page;
7). Click "Start training" with default 600s train time on Train page, and wait Training complete;
8). Click "Predict" button on Evaluate page;
9). Navigate to Consume page, find that the two buttons of 'Add to solution' have behaved like hyperlink.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0777cd4a-16e6-43c3-8a7c-9891bdc344df)

**Comment by romalpani** [comment]
@zewditu 

Hyperlinks on hover should not have an underline. Please refer to VS UI Guidelines here.
https://devdivdesignguide.azurewebsites.net/windows/patterns/buttons-and-hyperlinks/#visual-style-2
