### ISSUE TITLE
Consume page: Spinner keeps spinning if you say "No" to overwrite

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#1323]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue: Consume page
- Clear description of the problem: After adding a sample project once, if I click on "Add to solution" again I get the "Overwrite warning dialog". On this dialog, if I say "No", the dialog goes away but the spinner on the sample project section stays. 

**To Reproduce**

**Expected behavior**
The spinner should disappear and the hyperlink should show up again once the "Overwrite" dialog goes away.

**Screenshots**
![image](https://user-images.githubusercontent.com/48927690/110550967-86121780-80e9-11eb-931b-24453f089409.png)

**Additional context**

**Comment by vzhuqin** [comment]
This issue can't be repro on main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps：
1). Download data set from: https://raw.githubusercontent.com/dotnet/machinelearning/main/test/data/taxi-fare-train.csv
2). Create new C# console app with .Net 5.0;
3). Add model builder by right click on the project;
4). Click "Value prediction" on Scenario page to navigate to Environment page;
5). Select Local (CPU) on Environment page;
6). Select File and click "Browse..." to input the downloaded dataset, set "fare_amount" to "Column to predict (Label)" on Data page;
7). Click "Start training" with default 600s train time on Train page, and wait Training complete;
8). Click "Predict" button on Evaluate page;
9). Navigate to Consume page, click "Add to solution" after Web API, then click "Add to solution" button on “Add sample WebApi” dialog;
9). Click "Add again" after Web API, and click "Cancel" button on “Add sample WebApi” dialog;
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2d8fd354-6600-41e1-aaf0-78c35af952ff)
10). The dialog goes away with no error.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/f06ad43c-a2a8-40a8-ac78-90caf98310cb)
