### ISSUE TITLE
Web API clean up

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1324]
1. I believe with minimal web API, Startup.cs is not needed. @luisquintanilla to confirm

2. Also program.cs should be Program.cs (with capital P)

![image](https://user-images.githubusercontent.com/10437687/110672124-23218e80-8184-11eb-8291-3589ceff82b7.png)

3. The Predict function in model.consumption is now not useful for user since it only implements with predictionengine (not pool). I thought that originally we were adding the predictionengine pool in consumption.cs? @JakeRadMSFT

**Comment by luisquintanilla** [comment]
@briacht correct. There's no longer a need for the Startup.cs file since all the configs are in the Program.cs.

**Comment by vzhuqin** [comment]
@briacht @zewditu could you help to confirm if need to validate this issue on next version of ML.Net Model Builder (Preview)? Now there is no Web API sample project on Consume page.
Environment: 
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.202
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/f4fa0021-4863-4076-90d1-11e92674675f)

**Comment by vzhuqin** [comment]
The first two issues have been fixed on:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps:
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. After trained;
4. Click "Add a solution" on Web API;
5. See: 
 a. no Startup.cs
 b. Program.cs (with capital P)

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/5496af46-a343-465b-b71e-03a4ffcb645e)

**Comment by zewditu** [comment]
@JakeRadMSFT  @briacht  , we agreed  to keep  Predict method.

**Comment by LittleLittleCloud** [comment]
Confirmed, program.cs is still there while startup.cs is removed.
