### ISSUE TITLE
Boolean type is converted to String type for Text Classification

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1325]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5 and greater

**Describe the bug**
Although the label column is designated as data type "Boolean" it has been converted to a string type in consumption code. 

**To Reproduce**
1. Choose "Text classification" as your scenario
2. Load data and select a label
3. Open "Advanced data options" -> Column settings -> set label column as data type "Boolean"
4. In consume code, label value is expected to be a string

**Expected behavior**
My value should be treated as a boolean in code

**Comment by beccamc** [comment]
This is a known issue by the product team. Text classification scenario uses a multiclassification algorithm, which requires a string or single for the predicted label. We automatically convert a boolean label to the acceptable string type. 

Suggested fix: If label column is boolean type, run boolean classification instead of multiclass.

**Comment by beccamc** [comment]
I think this can be closed. @LittleLittleCloud we now support boolean classification right? So the intermediate fix of converting a bool to string is out of the product?

**Comment by LittleLittleCloud** [comment]
@beccamc 
I think so, feel free to move it to validate or close

**Comment by beccamc** [comment]
This is no longer in the product. Closing!
