### ISSUE TITLE
Image classification mbconfig file format

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1327]
Current format for image classification: 

```
  "DataSource": {
    "DataSourceType": "Folder",
    "LocalFolderPath": "C:\\Users\\...\\Images",
    "LocalInputFile": "C:\\Users\\....59e421e3-ad76-4978-ac9f-e3fe8f99f9c7.tsv",
    "RemoteInputFile": "C:\\Users\\....Temp\\36d99600-6e13-47e0-bd1c-73b8c496e24e.tsv",
    "RemoteFilePath": "Images\\36d99600-6e13-47e0-bd1c-73b8c496e24e.tsv"
  }
```

This format seems heavy. It feels like we only need a FolderPath and InputFile (both either local or remote). 

```
  "DataSource": {
    "DataSourceType": "Folder",
    "FolderPath": "C:\\Users\\...\\Images",
    "InputFile": "C:\\Users\\....59e421e3-ad76-4978-ac9f-e3fe8f99f9c7.tsv",
  }
```

**Comment by beccamc** [comment]
Long term:
1. Can we refactor the RemoteInputFile and LocalInputFile to both be relative paths, and then only one is required? _I don't know if this will be needed for datasets, so perhaps we should leave as is for now?_
2. Local Folder path used to create the tsv file doesn't need to be stored. We actually use the tsv and this is the more useful file for checking in. This experience should perhaps move towards something similar to datasets? You can create the tsv from a local folder path, then the tsv is the artifact you checkin and we use to train. 


Short term: 
 For local training we shouldn't store RemoteInputFile or RemoteFilePath.

**Comment by vzhuqin** [comment]
The image classification mbconfig file format has been changed on ML.Net Model Builder (Preview): 16.5.25.2126901

Local Image Classification:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/751b347e-3998-48d9-bfea-7ebacb5dc8a6)
Azure Image Classification:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9d0fadbf-d32b-45ab-be6d-b770da170ec1)
