### ISSUE TITLE
re-entrancy doesn't work for object detection

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1329]
1. I trained an object detection model in Model Builder (Azure ML environment)
2. Then saved I project and closed out of VS
3. I re-opened VS and train state was not saved and Train page looks like:
![image](https://user-images.githubusercontent.com/10437687/110990553-53a22d80-8328-11eb-9d4d-eba60b692141.png)

4. BUT if I go to data (which also is not completely updated and only shows small image previews):

![image](https://user-images.githubusercontent.com/10437687/110990622-63ba0d00-8328-11eb-8cc7-56aab47a7bf8.png)

And click on one of the previews, it takes ~20 seconds to load:
![image](https://user-images.githubusercontent.com/10437687/110990728-8ea46100-8328-11eb-9593-40695f45d924.png)

AND it brings back the train state:
![image](https://user-images.githubusercontent.com/10437687/110990763-9d8b1380-8328-11eb-8955-db75f331867a.png)

**Comment by vzhuqin** [comment]
Re-entrancy works for object detection with error dialog, could you help to take a look?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9b708228-d154-444e-9308-98c32981a5e4)

Validate this issue on Main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps:
1). Prepare the JSON file according to: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#create-a-new-vott-project
2). Create new C# console app with .Net 5.0;
3). Add model builder by right click on the project;
4). Click "Object detection" on Scenario page to navigate to Environment page;
5). Select Azure and set up workspace on Environment page;
6). Click "..." to input the JSON file;
7). Click "Start training" on Train page, and wait Training complete;
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/728fddcc-5570-4e09-bb92-b75aaa2f04d5)
8). Save and close the model builder;
9). Reopen the model builder, see prompt the error;
10). Close the error dialog, and navigate to Train page and Data page, see: the status is the last saved.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/dcc8989d-2a99-438e-a492-c3efa39e53e6)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/69e357ae-018f-444b-b735-fd7981827167)

**Comment by vzhuqin** [comment]
Reentrancy still occur model builder error on Main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122903
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4eb6c640-7c2d-4432-af46-6b55740dac2c)

**Comment by vzhuqin** [comment]
Verify this issue on main branch:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.5
- .Net: 5.0.202

Re-opened model builder, closed the prompted error window, the train state was saved.
![RentrancyObjectDetection.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/43f00516-75d7-45f5-ad1d-07bb4f650347)

Tracking "Model Builder Error" issue on: Model Builder error occurs on the process of model builder for Azure. #1406
