### ISSUE TITLE
Consume page changes

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1330]
See figma design - 

Code snippet:
- After click, Copy button shows ":heavy_check_mark: Copied" string for 1.5 seconds 
- Users should be able to select Code Snippet text and copy it via right click
- Only the code is scrollable. "Code snippet:" and "Copy" should stay at the top

Sample Project:
- Updated description string to "These projects use the most recent model created on _date_ at _time_". Data and time are the time stamp on the Model.zip.
- Add Sample App name. It should be YourModel_SampleApp**X**. After clicking Add to solution, it should show "_Adding..._", "_Added_" (for 1.5 seconds) and then "_Add Again_".  If adding an additional sample we should increment the X
- Warning dialog for name collision should say "Microsoft Visual Studio."

**Comment by beccamc** [comment]
Discussion on the `"These projects use the most recent model created on date at time"` string. Different opinions on including the string, and including the date/time. **Decision: Ship with string with date and time. It should display the time stamp on the Model zip.**

**Comment by romalpani** [comment]
Thanks @beccamc  for the notes. 
Here's the link to the Figma page. Look for the section "Final design 03/15/21" 
https://www.figma.com/file/bhdPADawiO4YQGdUNExiUc/?node-id=1%3A133

A couple of more points to add to the notes:
**1. Copy button: Accessibility**
The screen reader should announce the text "copied" after the button has been clicked. So, it should be in a 'live region'. 
Users should be able to tab to the "Copy" button using the keyboard. 

**2. Sample project timestamp** 
Hypothesis: Showing a timestamp will help customers learn that the sample project will use a particular timestamped version of the model.
We will look for feedback (community channels or whenever we do a more holistic in-person user study) if showing the timestamp is validating the hypothesis or not. 
Implementation of the "timestamp" also depends on feasibility that @zewditu shall confirm once she has a chance to explore the options.

**Comment by zewditu** [comment]
**Confirm:** Regarding the time stamp we can show the last updated time of Model.zip file

**Comment by zewditu** [comment]
For the scenario of if the user canceled to add the project due to name collusion what should be the status message? "project Not Add" ?

**Comment by romalpani** [comment]
@zewditu 
For 'same-project-name-scenario' in reference to this dialog below :
![image](https://user-images.githubusercontent.com/48927690/111667871-60180180-87d2-11eb-99f8-3dc4a9ff6347.png)

If the customer hits cancel on this dialog, we don't do anything. Simply bring them back to the main page. No need to change anything on the sample project tiles.

Does that answer your question?

**Comment by HaileyStorm** [comment]
I didn't even see the copy button my first time through the wizard, and I looked for it (after trying to select the text and ctrl-c / right-click-copy). Personally I think it'd be better to have a separate copy button, distinct from the TextBox control. Definitely, the text in itself should be selectable / copyable.

**Comment by zewditu** [comment]
@HaileyStorm thanks for your feedback! 

Yes,  the text should be selectable/copyable is fixed in the PR https://github.com/dotnet/machinelearning-tools/pull/978, 
for the location of the copy button @romalpani  what is thought?

**Comment by beccamc** [comment]
This is fixed.

**Comment by vzhuqin** [comment]
@beccamc I see your said this issue is fixed, but I don't see the consume page changed, do I need to validate it on next version of ML.Net Model Builder (Preview).

Not see the consume page changes on:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9298827e-6b4c-48ea-a8d8-c409f5c96dd9)

**Comment by vzhuqin** [comment]
Sample Project: Warning dialog for name collision should say "Microsoft Visual Studio."-->**This change doesn't realized.**
Repro steps:
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Navigate to Consume page after trained;
4. Click "Add again" after added one sample app;
5. Set the project name as same as last one or increment the X, click "Add to solution";
6. Prompt below error screenshot:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ac79d0df-5ff2-45a6-9be7-14e38d5cba91)


Other issues can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps：
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Navigate to Consume page after trained;
4. See the changes:
1) Code snippet:
- After click, Copy button shows "✔️ Copied" string for 1.5 seconds
- Users should be able to select Code Snippet text and copy it via right click
- Only the code is scrollable. "Code snippet:" and "Copy" should stay at the top

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b631d398-fc9a-4c71-b833-e110eafa2504)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/c1b9d8e6-eefc-4abb-8887-74e5b05bc11b)

2) Sample Project:
- Updated description string to "These projects use the most recent model created on date at time". Data and time are the time stamp on the Model.zip.
- Add Sample App name. It should be YourModelSampleAppX. After clicking Add to solution, it should show "_Adding...", "Added" (for 1.5 seconds) and then "Add Again". If adding an additional sample we should increment the X



![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ab52df0d-9238-476f-95a5-7dd53cec7de0)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/de10f864-441b-439c-9c0d-03c28e3e699a)

**Comment by beccamc** [comment]
@zewditu See error above

**Comment by zewditu** [comment]
This is due to the usage of relative model path  in generated projects  https://github.com/dotnet/machinelearning-modelbuilder/issues/1335

**Comment by zewditu** [comment]
I think this is fixed by https://github.com/dotnet/machinelearning-tools/pull/1025

**Comment by vzhuqin** [comment]
The change has been realized on main branch: 
ML.Net Model Builder (Preview): 16.5.24.2125801
Sample Project: Warning dialog for name collision should say "Microsoft Visual Studio."--realized.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/853393bb-1cef-4c64-8b97-30f855ed948b)
