### ISSUE TITLE
Please add a (local) training estimated time to completion on the Visual Studio Machine Learning page.

### ISSUE THREAD

**Issue by djmquestorsoftware** [dotnet/machinelearning-modelbuilder#1331]
Reference: ML.NET Model Builder. The "Train" page. "The model builder automatically sets the training time . . ." but does not display the time.

**Comment by beccamc** [comment]
@djmquestorsoftware Thanks for the feedback! I assume this is for either Image Classification or Object Detection training?

**Comment by djmquestorsoftware** [comment]
Yes, It is for classification. The suggestion is low priority. I am new to ML.Net and am experimenting. I was able to use ML.Net to test my idea. It took awhile and the estimated time would have help my planning. The test worked very well. I am now fitting the ImageClassification Train and Predict code to my app so I can semi-automate the classification of several million images. This fun stuff. Thank you for your attention.

DJM Questor Software

     On Tuesday, March 16, 2021, 05:17:56 PM PDT, Becca McHenry ***@***.***> wrote:  
 
 


@djmquestorsoftware Thanks for the feedback! I assume this is for either Image Classification or Object Detection training?

**Comment by beccamc** [comment]
This work is being tracked here https://github.com/dotnet/machinelearning-modelbuilder/issues/672. Please refer to 672 for progress. Thanks for reporting!
