### ISSUE TITLE
Azure Machine Learning workspace creation fails for Object Detection scenario

### ISSUE THREAD

**Issue by Leone-510** [dotnet/machinelearning-modelbuilder#1334]
**Model Builder Version**: ML.NET Model Builder (Preview) 16.3.0.2056001
**Visual Studio Version**: Microsoft Visual Studio Enterprise 2019 (version 16.7.4)

**Bug description**
I tried to create new workspace for first time in order to use object detection scenario without success:
"_Model Builder Error: Long running operation failed with status 'Failed'. Additional Info: 'At least one resource deployment operation failed. Please list deployment operations for details...'_ "

**Steps to Reproduce**
1. Extensions >> Manage Extensions >> Install Model Builder
2. Right-Click on Project >> Add >> Machine Learning
3. Scenario >> Object Detection
4. Environment >> Azure Machine Learning Workspace >> Setup workspace
5. Create new workspace >> Model Builder Error...

**Expected Experience**
I expected for Azure Machine Learning workspace to be set-up, in order to continue to the next step (Data)

**Actual Experience**
I tried twice to setup Azure Machine Learning workspace for the Object Detection scenario, with 2 different accounts, but the procedure failed with the same error. 

**Additional Context**

![AzureML_Creation_FirstAttempt(1)](https://user-images.githubusercontent.com/28001935/111682362-ef520300-882c-11eb-9bda-641c581462e8.png)
![AzureML_Creation_FirstAttempt(2)](https://user-images.githubusercontent.com/28001935/111682365-efea9980-882c-11eb-8d72-cca8934e8af0.png)
![AzureML_Creation_SecondAttempt(1)](https://user-images.githubusercontent.com/28001935/111682366-f0833000-882c-11eb-894e-30c24f5056ab.png)
![AzureML_Creation_SecondAttempt_ERROR(2)](https://user-images.githubusercontent.com/28001935/111682368-f0833000-882c-11eb-9a7b-6a9e9d9119b4.png)
[bf76ec0d-ae66-4154-99c1-ab3ed63af30b.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6166621/bf76ec0d-ae66-4154-99c1-ab3ed63af30b.txt)

**Comment by LittleLittleCloud** [comment]
Hi @Leone-510 Can you try creating workspace through the portal directly? The cause for deploying failure can be various and from model builder's log, it's hard to detect which one it is.

**Comment by beccamc** [comment]
@Leone-510 as LittleLittleCloud said it would be great if you could create from the portal directly. 

Can you also check the portal for why the previous job failed? Let me know if you'd like instructions on how to do this. Is the error something similar to `An invalid value was provided for 'accessPolicies'`? This [issue](https://github.com/dotnet/machinelearning-modelbuilder/issues/1104) happens sometimes on the create of a first workspace in a subscription.

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you have any other questions.
