### ISSUE TITLE
MBConfig should use Relative Paths

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1335]
**Describe the bug**
ModelBuilder doesn't update MLNetModelPath way when selecting adding to project. The MLNetModelPath in the copied mbconfig file still points to the original model instead of copied one.

**To Reproduce**
- train a model, and add to project (it doesn't matter whether it's webapi or console app)
- check mbconfig file in newly added project, notice that the MLNetModelPath still points to the original one

**Comment by vzhuqin** [comment]
This issue can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps：
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. After trained;
4. Add to project for console app and Web API;
5. Check the model builder paths are correct.

Console App:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/f6669651-852d-4c28-8c15-30506a283e45)
Web API:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/59aa644b-47b9-4b39-ab4c-8f809143ec3a)
