### ISSUE TITLE
I face issue "(process 10440) exited with code 0"

### ISSUE THREAD

**Issue by yogeshpatel002** [dotnet/machinelearning-modelbuilder#1336]
C:\Users\Hp\source\repos\ConsoleApp2\bin\Debug\netcoreapp3.1\MlCode.exe (process 10440) exited with code 0.

**Comment by beccamc** [comment]
@yogeshpatel002 Sorry you ran into this problem. Can you help me with a few things...  

1. On what step of the tutorial did you find this problem? Did this happen while opening model builder (at "Add Machine Learning"), or later in the process?
2. Was there a stack trace shown? Can you send the stack trace?
3. Can you attach a screenshot of the problem?

Thanks!

**Comment by beccamc** [comment]
@yogeshpatel002 any update on the above questions?

**Comment by beccamc** [comment]
Unfortunately we don't have enough information to investigate this issue. If you're still seeing a problem, please re-open and provide additional information. Thanks!
