### ISSUE TITLE
GPU extensions check incorrectly fails

### ISSUE THREAD

**Issue by HaileyStorm** [dotnet/machinelearning-modelbuilder#1337]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5.0.2115505
 - Visual Studio Version: 16.10.0 Preview 1

**Describe the bug**
- On which step of the process did you run into an issue: Environment
- Clear description of the problem: Environment -> Local (GPU) -> Check compatibility shows GPU extension not installed but Extensions -> Manage Extensions -> Model Builder Private Preview shows ML.NET Model Builder GPU Support (Preview) installed w/ same version number as model builder itself. 

**To Reproduce**
See above

**Expected behavior**
Compatibility check should succeed.

**Screenshots**
![image](https://user-images.githubusercontent.com/55606304/112049692-94aef480-8b15-11eb-8a5c-68dfeb53c4e2.png)

**Additional context**
Note that there are two GPUs, an integrated/APU and a discrete.

**Comment by LittleLittleCloud** [comment]
Hi @HaileyStorm 

Thanks for filing that issue, we are working on a fix for that which should be released soon. I'll let you know when the fix is released.

Regards

**Comment by LittleLittleCloud** [comment]
Close due to duplication
