### ISSUE TITLE
Advanced Data Options graphics issue with dark theme

### ISSUE THREAD

**Issue by HaileyStorm** [dotnet/machinelearning-modelbuilder#1338]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5.0.2115505
 - Visual Studio Version: 16.10.0 Preview 1

**Describe the bug**
- On which step of the process did you run into an issue: Data
- Clear description of the problem: The Data -> Advanced Data Options window does not display correctly when the Visual Studio color theme is set to Dark.

**To Reproduce**
1. Set Visual Studio theme to Dark
2. Choose e.g. Value prediction scenario
3. Go to the Data step
4. Click on Advanced Data Options
5. See screenshot

**Expected behavior**
All elements of the window should be visible and distinguishable.

**Screenshots**
![image](https://user-images.githubusercontent.com/55606304/112051367-79dd7f80-8b17-11eb-9b9d-4a2cf176b0a7.png)

**Additional context**
N/A

**Comment by LittleLittleCloud** [comment]
Hi @HaileyStorm 
Thanks for filing this bug. We already fix that which should be released soon.

Regards

**Comment by LittleLittleCloud** [comment]
dup of #1264
