### ISSUE TITLE
Update holdout strategy based on dataset's size

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1341]
**Is your feature request related to a problem? Please describe.**
If automl type is NNI, automl layer will use hold-out even for very small dataset, which leads to a large variance to evaluation steps.

**Describe the solution you'd like**
Follow AutoML.Net, only use hold-out for large dataset

**Comment by JakeRadMSFT** [comment]
Dev Work Tracking Task - Nothing to validate.
