### ISSUE TITLE
Cache dataset to accelerate trials

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1342]
**Is your feature request related to a problem? Please describe.**
Currently, trial runner will reload dataset every time a new trial starts, that's quite inefficient for large dataset. ML.Net provides data cache to eliminate thus inefficiency.

**Describe the solution you'd like**
cache dataset to improve training speed.

**Describe alternatives you've considered**

**Additional context**

**Comment by JakeRadMSFT** [comment]
Dev Work Tracking Task - Nothing to validate.
