### ISSUE TITLE
Let user select metric to optimize in automl training

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1343]
**Is your feature request related to a problem? Please describe.**
Currently, model builder use fixed optimize metric for automl scenarios, Macro accuracy for classification, r-squared for regression and recommendation. However, fixed metric can't always performs well, especially if dataset is imbalanced. Therefore, we should leave the decision of which metric to use back to users.

**Comment by luisquintanilla** [comment]
Closing this issue since it's already being worked on as part of #2191
