### ISSUE TITLE
Advanced data options changing datatype does not enabled "Save" button 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1346]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _select Text classification scenario
2. _ use this dataset [https://app.zenhub.com/files/186917455/f2e71c14-5124-4503-92af-124258de9ccb/download](https://app.zenhub.com/files/186917455/f2e71c14-5124-4503-92af-124258de9ccb/download)
3. label column : col0
4. go to advanced options change the data type of col2 into String from Boolean 

**Expected Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/0adad970-a840-4548-9ec3-1ed7e6c2e61c)_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by zewditu** [comment]
check or uncheck of categorical  also not trigger Save button enabled

**Comment by vzhuqin** [comment]
Can't repro this issue on
This issue can be repro on environment:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

The "Save" button is enabled after changed the data type of col2 into String from Boolean or check or uncheck of categorical.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/15d3f841-0766-4a3b-a077-6a8ad4b512cb)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a7d78c96-b09d-4e44-9f65-10f50fe1f774)

**Comment by vzhuqin** [comment]
Also not repro on ML.Net Model Builder (Preview): 16.5.21.2122301
Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
