### ISSUE TITLE
Advanced data option  change does not  disabled after Data tabs

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1347]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. select text scenario  go through all steps to enable all tabs
2. Select the same scenario> reentrancy  enabled 
3.go to advanced options
4 Do any update in advanced data options 

**Expected Experience*
1 Disabled all tabs after data  just like uploading new data
2. show spinner in saving of advanced data options update  because it takes a while to save 

**Actual Experience**
1. Save button in advanced data option is blocking and no spinner 
2. Tabs after data are still keep enabled 
**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
Per discussion mentioned in 1436, I'm closing this. We are re-evaluating how we handle resetting data/state.
