### ISSUE TITLE
model builder error

### ISSUE THREAD

**Issue by SUDALV92** [dotnet/machinelearning-modelbuilder#1348]
**System Information:**
 - Model Builder or CLI Version: unknown (latest?)
 - Visual Studio Version: 16.8.6

Using this tutorial: [https://devblogs.microsoft.com/dotnet/train-image-classification-model-azure-mlnet-model-builder/](url)
It crashed during new workspace creation.
log: [25db3535-983c-4827-a2b4-4f4133ff5691.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6211210/25db3535-983c-4827-a2b4-4f4133ff5691.txt)

Next resources still successfully created:
- application insights
- container registry
- key vault
- storage account

**Comment by SUDALV92** [comment]
I'm trying to create a workspace from the azure portal and getting this error:

> {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"An invalid value was provided for 'accessPolicies'."}]}

**Comment by SUDALV92** [comment]
Recreated all required resources from scratch in azure portal, everything works fine.

**Comment by beccamc** [comment]
@SUDALV92 sorry about this error! This is a known [issue](https://github.com/dotnet/machinelearning-modelbuilder/issues/1104) when creating your first workspace. We are working to replace the problem library now. 

Thank you for reporting and apologies for the delay!
