### ISSUE TITLE
Exception during training Image classification

### ISSUE THREAD

**Issue by sandervandevelde** [dotnet/machinelearning-modelbuilder#1349]
**System Information (please complete the following information):**
 - Model Builder Version:  latest version
 - Visual Studio Version : 2019 (the ICAM 7000 runs Windows 10 LTSC 1904).

**Describe the bug**
Exception during train step of Image classification:
```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 150
```

**To Reproduce**
1. In VS2019 on an Advantech Icam 7000, make a model based on the images in https://github.com/sandervandevelde/eurovision 
2. Start the training
3. Wait and after a while an error occurs

**Expected behavior**

No crash :)

**Screenshots**

Processor:
![image](https://user-images.githubusercontent.com/694737/112678458-3cf0f000-8e6b-11eb-9e89-8466598cd4a8.png)

![image](https://user-images.githubusercontent.com/694737/112677957-a45a7000-8e6a-11eb-91bb-8ddd099fc781.png)

**Additional context**

Exception log:
[classification exception on advantech ICAM 7000 7bf92b49-abd0-453c-ad8b-92ed77c22e36.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6213721/classification.exception.on.advantech.ICAM.7000.7bf92b49-abd0-453c-ad8b-92ed77c22e36.txt)

Device information:
[ICAM-7000_DS(122220)20201222171440.pdf](https://github.com/dotnet/machinelearning-modelbuilder/files/6213747/ICAM-7000_DS.122220.20201222171440.pdf)

Note: In the Github repo I already have a project with a TensorFlow model in it (Build on a separate device, Surface pro 4 I5). That application fails too (if you want I can share that issue too). That's why I try to build a new model on the target device itself (the ICAM 7000 which runs Windows 10 LTSC 1904. This is industry-grade hardware).

So it not clear to me if the problem is just the creation of the model or running the TensorFlow model on this device...

I rebooted the machine and retried it. Same error.

I got some comments from a friend that the processor could be the show stopper. An Atom processor is not supported for Tenserflow 15 and up? If that is the case, I expect a warning or error on the page with the hardware selection. OR, I would like to downgrade to Tensorflow 14.

**Comment by luisquintanilla** [comment]
Adding this issue on TF repo for reference.

https://github.com/tensorflow/tensorflow/issues/17386

**Comment by beccamc** [comment]
@LittleLittleCloud Can you help here?

**Comment by luisquintanilla** [comment]
@beccamc @LittleLittleCloud I took a look at this issue with @sandervandevelde last week. It looks like it's not specific to Model Builder and might be more at the API level. I haven't transferred it over to the ML .NET repo just yet.

**Comment by beccamc** [comment]
Okay great! Just wanted to make sure Sander wasn't left hanging. Thanks Luis!

**Comment by luisquintanilla** [comment]
@sandervandevelde since we were able to get training working on your device, are you okay with us closing this isssue?

**Comment by sandervandevelde** [comment]
Yes, this can be closed now.
