### ISSUE TITLE
Best Model isn't Rank 1 of Top 5

### ISSUE THREAD

**Issue by jalin168** [dotnet/machinelearning-modelbuilder#135]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/evaluate#

Operating System: Windows 10

I have 2 confuse:
(1). Best Model isn't Rank 1 of Top 5
(2). Best Model Accuracy is 88.24%, but I don't see any the same value in Top 5 models.

thanks.

![Sentiment tutorial_15_look Evaluate_red](https://user-images.githubusercontent.com/14954221/57569988-a6121a80-742f-11e9-8de3-0b86521a3b08.png)

**Comment by rustd** [comment]
Please try the latest version of Model Builder from the gallery.
