### ISSUE TITLE
"Failed. See more in output pane. " but is empty

### ISSUE THREAD

**Issue by jatem** [dotnet/machinelearning-modelbuilder#1352]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
Hi@jatem, Sorry to hit this! could you tell us more about the issues in the steps to reproduce section ?

**Comment by zewditu** [comment]
Close due to no response, feel free to reopen it if you have any other questions.
