### ISSUE TITLE
Local training for object detection

### ISSUE THREAD

**Issue by MaximeTasset** [dotnet/machinelearning-modelbuilder#1353]
I don't want to use the Azure ML for my object detection, why is it not possible to use my local machine?

**Comment by zewditu** [comment]
we have several similar requests for local Object Detection training. https://github.com/dotnet/machinelearning-modelbuilder/issues/1091

**Comment by beccamc** [comment]
Closing this as duplicate. Please see issue 1091 for tracking and updates.
