### ISSUE TITLE
move to multi-model AutoML

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1355]
### single-model AutoML
![image](https://user-images.githubusercontent.com/16876986/113056905-3ca16f00-9161-11eb-9ee3-8fe485a11090.png)
where
- tuner: hyper-parameter selection, and create trial parameter and submit to dispatcher, which launches trial.
- pipeline: single-model pipeline
- search space: search space for that pipeline

### multi-model AutoML
![image](https://user-images.githubusercontent.com/16876986/113057120-85592800-9161-11eb-963b-ca0ab283127e.png)

where
- config-based proposers in AutoML layer
- proposers proposes trial parameters
- controller submit trial parameters to dispatcher, which launches trial.
- each proposer is only in charge of single part. For example, learner propser: select pipeline from pipelines pool, hyperparameter + sample size proposer: select hyper parameter and sample size for that pipeline....

**Comment by beccamc** [comment]
I think we can move this to ship... I think we've been validating this while using :)
