### ISSUE TITLE
implement CFO tuner and a naive pipeline

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1356]
- [x] integrate init version CFO
- [ ] pass lowCostValue in addition to initValue
- [ ] bonus: other arguments you may consider to add: prune_attr, min_resource, max_resource (for sample size); resources_per_trial, mem_size (for prevent OOM error); cat_hp_cost (not necessary if we don't have cost-related categorical hps)

**Comment by beccamc** [comment]
I don't think any of us can validate this based on the info above. I'm moving this to Release.
