### ISSUE TITLE
Visual Studio stops working when training starts

### ISSUE THREAD

**Issue by JustAnotherPaul** [dotnet/machinelearning-modelbuilder#136]
I've tried any test data from the dotnet/machinelearning-samples repository and also made a pretty simple one myself:

A,B,C,D,E
1,1,1,1,1
1,1,1,1,2
1,1,1,1,3
1,1,1,1,4
1,1,1,1,5

1. Add -> Machine Learning
2. Selecting any scenario (it doesn't matter, since all of them crash)
3. Selecting the test data from above
4. As column to predic I select "E"
5. Time to train: 10 seconds (it doesn't mater)
6. then I click "Start taining" and VS crashes immediately

I've attached the VS ActivityLog.xml, are there any other Log files or information I could provide?
[ActivityLog.txt](https://github.com/dotnet/machinelearning/files/3162174/ActivityLog.txt)

**Comment by rustd** [comment]
Thank you for filing this issue and glad it worked!
