### ISSUE TITLE
Machine Learning "Customer Text Review Sample"

### ISSUE THREAD

**Issue by chuck189** [dotnet/machinelearning-modelbuilder#1362]
//Run into an issue not sure whats it's trying to target, saying it cannot be referenced by Version 4.5.2

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project '..\CustomerReviewMLsML.Model\CustomerReviewMLsML.Model.csproj' targets 'netstandard2.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.5.2'.	CustomerReviewMLs

**Comment by zewditu** [comment]
You need to upgrade your project target.NetFramework version from version  4.5.2 -> 4.6.1 the compatible version of .net standard 2.0. https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by zewditu** [comment]
Closed: You probably fix the issue, if you still hit let us know and feel free to reopen it.
