### ISSUE TITLE
model builder version in telemetry

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1363]
Not sure if this is already being done, but want to make sure that each telemetry event sent from Model Builder includes the version of Model Builder in the Properties

**Comment by beccamc** [comment]
Our preview channel reports an AssemblyVersion, as does the main branch. This gets added in a common method called PostTelemetry, which every telemetry event uses. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/041ca5f0-6f0f-4de1-be1b-801fa227a876)

Can I get more info on the problem? Anyone still on our version shipped with VS is missing the code change to add version number in telemetry.

**Comment by briacht** [comment]
Just checked, looks like it's there! Thanks
