### ISSUE TITLE
Select Table List Order and Usability

### ISSUE THREAD

**Issue by chrishirsch-psllc** [dotnet/machinelearning-modelbuilder#1364]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5.0.2115505
 - Visual Studio Version 16.8.4

**Describe the bug**
- On which step of the process did you run into an issue: Model Builder Add Data
- Clear description of the problem: When using SQL Server as the input data source, the Table dropdown is not usable for databases containing many tables/views.  The tables/views are not ordered alphabetically and it is difficult to locate the table/view.  Using the keyboard to navigate the list causes the UI to freeze while it loads information about the object and therefore arrow keys can not be used for navigation.  There is no means to enter the table/view manually or to search the items.

**To Reproduce**
1. Go to "Select a scenario"
2. Click on "Value prediction"
3. Click "Next step"
4. Select the SQL Server Option
5. Click "Choose data source"
6. Select Microsoft SQL Server
7. Click Continue
8. Enter a Server name
9. Provide credentials
10. Provide a valid database in "Select or enter a database name:"
11. Click OK
12. Click the Table dropdown

**Expected behavior**
Provide an ordered list of tables/views in the dropdown and/or utilize a control that allows user entry and/or search.

**Screenshots**
![image](https://user-images.githubusercontent.com/80786094/113366627-c00cbd00-9327-11eb-82c5-b9fc734c3f08.png)

**Comment by zewditu** [comment]
Sorry for the issue you are hitting and we thank you for letting us know the issue.

**Comment by beccamc** [comment]
@chrishirsch-psllc How many tables do you have? We can easily order the list, but you'll still be in trouble if the table you want is at the bottom. I can take a look at why the perf is so bad if you can share the number of tables you're trying to load. Thanks!

**Comment by chrishirsch-psllc** [comment]
Thank you for taking the time to review this issue.  The database utilized includes over 800 tables and views which are displayed in the list, but the usability issue is a concern with databases with fewer objects.  Based on a brief review of the “Add Data” screen, when the Table dropdown selection changes a few queries are executed:
- Query of schema data, INFORMATION_SCHEMA.TABLES for the selected table/view
- Query of the top 200 records of the selected table/view.  

The data queried appears to be utilized, in part, for the “Data Preview” at the bottom of the screen. The queries occur for each down/up arrow keystroke resulting in a delay between each item selection.  Modifying the location/timing of the database query, so that it does not occur upon selection changed, but perhaps after focus changes may resolve the keyboard accessibility problem.  To ensure that long lists are navigable, the dropdown list could be replaced by a control that accepts keyboard input, ideally with autocomplete from the list items.  Thank you!

**Comment by beccamc** [comment]
I hadn't realized the keyboard navigation bit. We need to fix that. Thanks for the clarification!

**Comment by beccamc** [comment]
https://github.com/dotnet/machinelearning-modelbuilder/issues/1431

**Comment by beccamc** [comment]
Validate...
- Tables in alphabetical order
- Can use keyboard to navigate without each table trying to load

**Comment by beccamc** [comment]
We've added a delay so that you can use the up and down arrows to navigate through the tables.
