### ISSUE TITLE
Microsoft.ML currently supports 'x64' and 'x86' processor architectures. Please ensure your application is targeting 'x64' or 'x86'.	AI			

### ISSUE THREAD

**Issue by Sherlock-12138** [dotnet/machinelearning-modelbuilder#1366]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
@Sherlock-12138 Sorry you ran into this problem! Are you on x32 bit windows? Are you trying to use Model Builder or the CLI?

**Comment by beccamc** [comment]
Any update on the above questions?

**Comment by beccamc** [comment]
Unfortunately we don't have enough information to investigate this issue. If you're still seeing a problem please re-open and ping me. Thanks for reporting

**Comment by BesTuerzt** [comment]
I have added the required item to the publish file, but the project still isn't functioning as expected.
Item: (EnableMLUnsupportedPlatformTargetCheck>false</EnableMLUnsupportedPlatformTargetCheck)
Could you please suggest any alternative solutions if you have any?

Additionally, could this issue be related to a CPU warning that I noticed? Your input would be greatly appreciated.
Thank you for your assistance.
Best regards
