### ISSUE TITLE
Limited scenarios do not allow the tutorial to Detect stop signs in images with Model Builder

### ISSUE THREAD

**Issue by Loongle** [dotnet/machinelearning-modelbuilder#1367]
I used Visual Studio 2019 to follow the steps in the tutorial. I could not continue to select the training scheme, which was in the limited  list

https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/object-detection-model-builder

![image](https://user-images.githubusercontent.com/7290992/113592265-827d9c00-9667-11eb-9086-f662de60f82a.png)

**Comment by beccamc** [comment]
@Loongle It looks like you're on an older version. Can you please update via the marketplace https://marketplace.visualstudio.com/items?itemName=MLNET.07&ssr=false#overview. 

Sorry for the confusion!

**Comment by beccamc** [comment]
Did updating Model Builder fix the problem?

**Comment by Loongle** [comment]
@beccamc Hi. I updated the version six days ago. but a new problem came up and I couldn't use local ML for training. currently only Azure is available for training. 

version: 16.3.0.2056001

![image](https://user-images.githubusercontent.com/7290992/114799964-65fe0400-9dcb-11eb-8996-8b49aa730ff7.png)

**Comment by Loongle** [comment]
![image](https://user-images.githubusercontent.com/7290992/114800118-acebf980-9dcb-11eb-96ea-83ef75fda2c6.png)

**Comment by Loongle** [comment]
@beccamc Maybe I made a mistake. The teaching content has been consistent with the documentation. can turn off. 
Thanks

**Comment by beccamc** [comment]
Thanks @Loongle. I'll make a note that you're requesting local Object Detection training.

**Comment by Loongle** [comment]
@beccamc Thank you very much. 👍
