### ISSUE TITLE
Add support for .arff dataset

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1369]
`arff` is a dataset format, which is a superset of `csv` and includes attributions of column information in header comment.

wiki
https://www.cs.waikato.ac.nz/ml/weka/arff.html#:~:text=An%20ARFF%20%28Attribute-Relation%20File%20Format%29%20file%20is%20an,for%20use%20with%20the%20Weka%20machine%20learning%20software.

we can use [arfftools](https://github.com/chausner/ArffTools) to parse arff dataset, or simply write our own parser since the .arff structure is quite simple.

**Comment by JakeRadMSFT** [comment]
Closing for now - waiting for related customer feedback.
