### ISSUE TITLE
Extra code generation folders added to solution when project and solution in same directory

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#137]
**Describe the bug**
When you select "Place solution and project in same directory" in New Project Dialog when creating a new project:
![image](https://user-images.githubusercontent.com/10437687/60300496-fd871f80-98e3-11e9-81c1-e94343a36b0d.png)

The file structure from code generation (Add Projects) gets messed up:
![image](https://user-images.githubusercontent.com/10437687/60300908-e39a0c80-98e4-11e9-9623-a66c713f45c4.png)

**Expected behavior**
Expect file structure to look like:
![image](https://user-images.githubusercontent.com/10437687/60300752-830acf80-98e4-11e9-8984-137ff8568a34.png)

**Comment by rustd** [comment]
Fix: Put the generated projects in the parent folder of the initial app from where Model Builder was launched.

**Comment by LittleLittleCloud** [comment]
Same behavior when you pick the `project and solution in the same folder` when creating a solution and then add a project into that solution. So should it be supposed to be a bug of Model Builder and get fixed?

**Comment by LittleLittleCloud** [comment]
dup of #359
