### ISSUE TITLE
Trying Azure reload on first open

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1372]
Steps: 
1. Start new mbconfig
2. Select Object detection
3. Go to Environment page

Loading spinner is shown: (we're trying to reload their Azure info) 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/0983e783-ff0b-4df7-84de-0453af71ebd5)

Error is shown:
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/020c486e-b63e-48a1-b8e5-238fe480a80d)

As a note, we probably shouldn't try reload a "0000..." id subscription

**Comment by beccamc** [comment]
To validate, ensure no error is thrown when you start a new OD session

**Comment by vzhuqin** [comment]
This issue can be repro on environment:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps to reproduce the behavior:
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Select "Object detection" scenario,
4. Jump to Environment page with prompting the Model Builder error dialog;

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e7f6102e-7f58-4e01-a207-752f8674a6e6)

Related issue: https://github.com/dotnet/machinelearning-modelbuilder/issues/1406

**Comment by vzhuqin** [comment]
This issue can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps：
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Click "Object detection" scenario to go to Environment page;
4. The Environment is displayed normally without error.

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/fb8bebc6-09e4-4e17-9c94-a0ed70ade2b0)
