### ISSUE TITLE
mlnetresources.blob.core.windows.net cannot be resolved

### ISSUE THREAD

**Issue by kaizen365** [dotnet/machinelearning-modelbuilder#1375]
Image Classification does not work as unable to download resnet_v2_50_299.meta

Error downloading resource from 'https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta': The remote name could not be resolved: 'mlnetresources.blob.core.windows.net'\nThe remote name could not be resolved:

**Comment by fuomag9** [comment]
I have the same issue as well

**Comment by rahulgorai** [comment]
I guess everyone is facing the same issue, but why this issue is not getting attended by Microsoft.

**Comment by beccamc** [comment]
Hi all, we're starting to look into this. Thanks for your patience

**Comment by beccamc** [comment]
This should be fixed now. Please check and let me know!

**Comment by fuomag9** [comment]
> This should be fixed now. Please check and let me know!

Fixed for me, thanks!

**Comment by beccamc** [comment]
Have reports that this is fixed. Closing - thanks!
