### ISSUE TITLE
Spinner needed for GPU check compatibility 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1377]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1.Select Image classification
2. Select Local(GPU)
3. Click on Check compatibility button 

**Expected Experience**
After  `Check compatibility` button clicked  spinner should be displayed until the result displayed 
**Actual Experience**
 `Check compatibility` button clicked  there is a delay to show the result without the spinner 
![image](https://user-images.githubusercontent.com/36615490/114644798-0bf72480-9c8d-11eb-91ac-010a9e4d2407.png)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
Check why `RunningGPUCompatibilityCheck` isn't working. It should show one spinner while all the values are being checked/loaded.

**Comment by JakeRadMSFT** [comment]
@zewditu Can you please add images ... I don't understand what is the expected/actual experience?

**Comment by zewditu** [comment]
The GPU service throws an exception before the visibility of the spinner ON courses this. Set the visibility of the spinner visible outside of the try-catch block to fix this issue.
