### ISSUE TITLE
Git Re-Entrancy

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#1379]

**Comment by beccamc** [comment]
@vzhuqin Have you already run testing on the git story? I think you did, and the only bug was https://github.com/dotnet/machinelearning-modelbuilder/issues/1451. Please let me know if that isn't true. Thanks!

**Comment by vzhuqin** [comment]
@beccamc , have another git issue: https://github.com/dotnet/machinelearning-modelbuilder/issues/1456

**Comment by beccamc** [comment]
This has been tested and has other issues tracking the problems. Closing.
