### ISSUE TITLE
Error saying a prediction label column is string type when it is a decimal(10,2)

### ISSUE THREAD

**Issue by gpintoextra** [dotnet/machinelearning-modelbuilder#1382]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.02027
 - Visual Studio Version 16.9.4

**Describe the bug**
- On which step of the process did you run into an issue: Train
- Clear description of the problem:
- I am creating a new model
- I connect to my database
- I select a table
- I select a column prediction label which is of type decimal(10,2) and its name is **CalidadPonderada**
- The data shows ok on the screen
- When I train the model I get this error saying that the column is of type string but it is not, it is a decimal number.

```
**Provided label column 'CalidadPonderada' was of type String, but only type Single is allowed.**

   en Microsoft.ML.AutoML.UserInputValidationUtil.ValidateTrainDataColumn(IDataView trainData, String columnName, String columnPurpose, IEnumerable`1 allowedTypes)
   en Microsoft.ML.AutoML.UserInputValidationUtil.ValidateColumnInformation(IDataView trainData, ColumnInformation columnInformation, TaskKind task)
   en Microsoft.ML.AutoML.ExperimentBase`2.ExecuteCrossValSummary(IDataView[] trainDatasets, ColumnInformation columnInfo, IDataView[] validationDatasets, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   en Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   en Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<>c__DisplayClass21_0.<ExecuteAsync>b__5() en /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:línea 81
   en System.Threading.Tasks.Task`1.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext() en /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:línea 108
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() en /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:línea 147
```

**To Reproduce**

**Expected behavior**
The model  is created after training

**Screenshots**

![Captura1](https://user-images.githubusercontent.com/82551051/114797548-b48fac00-9d93-11eb-97ed-33b47b0fa0f4.PNG)
![Captura2](https://user-images.githubusercontent.com/82551051/114797578-c2ddc800-9d93-11eb-928b-3de13edd3567.PNG)

[logfile_2113e03f-7ac3-4a62-8af1-574e65d5b2ad.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6314448/logfile_2113e03f-7ac3-4a62-8af1-574e65d5b2ad.txt)

**Additional context**
Hint: My windows os is in Spanish whichs considers decimal numbers like for example 3,14 with a coma not a dot like in english  3.14 but I changed the OS setting for decimal numbers separated by dot and the problem is the same.

**Comment by beccamc** [comment]
@gpintoextra Thanks for reporting and sorry for the issue here. Can you try upgrading to 16.3 and reproducing the problem? Upgrade here: https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by beccamc** [comment]
Any luck updating the MB version?

**Comment by gpintoextra** [comment]
Yes, problem solved. Thank you very much.

**Comment by beccamc** [comment]
Awesome! Thanks for reaching out, and let me know if you run into any more problems!
