### ISSUE TITLE
The tutorials docs will need to be updated.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1383]
**System Information (please complete the following information):**
 - ML.Net Model Builder (Preview): 16.5.0.2115505
 - Microsoft Visual Studio Enterprise 2019: 16.9.3

**Describe the bug**
Most contents of the tutorials docs are outdated, will need to be updated.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices-with-model-builder'
2. Scroll down to 'Add the code to make predictions'
3. See the docs are outdated:
Example 1: Scroll down to 'Add the code to make predictions',  will not have "Two projects will be created as a result of the training process.", only one sample project is created on Consume page.
Example 2: Do not have "Sentiment Analysis" and " Issue Classification" scenarios in current model builder, they should be classified to "Text classification" scenario.

**Expected behavior**
All tutorials docs have been updated accordingly.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/114826055-978dc400-9df9-11eb-82ec-0b7a76b5bace.png)
![image](https://user-images.githubusercontent.com/81727020/114825832-4a115700-9df9-11eb-9362-e14528bb039e.png)
![image](https://user-images.githubusercontent.com/81727020/114825912-60b7ae00-9df9-11eb-96d4-17683ca21298.png)

**Additional context**
Tutorials docs need to be updated:
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices-with-model-builder
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis-model-builder
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/health-violation-classification-model-builder
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder

**Comment by beccamc** [comment]
Thank you for reporting @vzhuqin! This is a great point. @briacht and @luisquintanilla

**Comment by briacht** [comment]
@vzhuqin Thanks for the feedback and for going through the Docs!

Before our "public" release, we will makes sure we update Docs to reflect all the new features and changes

**Comment by briacht** [comment]
This has been updated in the main Model Builder Doc: https://docs.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-model-builder

And Jon is working on updating the rest of the Model Builder tutorials. It's being tracked in Docs repo, so I will close this issue here.
