### ISSUE TITLE
Target framework for the generated sample project is .NET Core 3.1.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1384]
**System Information (please complete the following information):**
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**Describe the bug**
Target framework for the generated sample project is .NET Core 3.1.

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add Model builder by right click on the project;
3. Go to Consume page after Scenario>Environment>Data>Train>Evaluate steps;
4. Click "Add a solution" of console app;
5. Right click the sample project and click "Properties";
6. See Target Framework is .NET Core 3.1.

**Expected behavior**
Target framework for the generated sample project is .NET 5.0.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/114828243-40d5b980-9dfc-11eb-9856-4c9262af249e.png)
![image](https://user-images.githubusercontent.com/81727020/114828332-5945d400-9dfc-11eb-8085-0dbe36c310d2.png)

**Additional context**
NA

**Comment by beccamc** [comment]
@LittleLittleCloud @zewditu and @briacht What is the expected behavior here?

**Comment by zewditu** [comment]
The target framework for the console sample project is hardcoded to .net core 3.1.  
@briacht  do we want it to match with the user project targetframe work?

**Comment by briacht** [comment]
Yes it makes sense to match the project's target fx

**Comment by LittleLittleCloud** [comment]
I don't think it's worthwhile to match generated fx with the selected project. When generating a library or an app, the target with minimum requirement (or largest compatibility) should be selected. For library, the target framework should be .netstandard2.0 (which is targeted by ML.Net). And for console app, it should be .netcoreapp2.1 (the minimum version that supports .netstandard 2.0).

**Comment by LittleLittleCloud** [comment]
And using selected framework target can causes massive amount of bugs. As the selected project can be either .net library or app. It can support or not support .net standard 2.0. And it can have multiple selected framework targets in .csproj as well. There's no guarantee that the target of selected framework can also be used by generated projects unless it's been thoroughly verified. But it's not worthwhile to do as the corner cases are endless and benefits are too small.

**Comment by romalpani** [comment]
From a customer's perspective, wouldn't it make sense to generate a project with a target framework that matches their current project?

**Comment by LittleLittleCloud** [comment]
So what will be the definition of "match" their current project? If the target of selected project is `netstandard2.1`, which target will match, .net5.0, .netcoreapp 3.1, or net472? They are both correct answers because they all implements `netstandard2.1`. But which one will be preferred is a personal taste.

**Comment by romalpani** [comment]
@LittleLittleCloud not sure I follow your example. When you say "selected project" are you referring to the base project in the customer's solution tree (that they right-clicked on to create the ML model)?

But generally speaking, I think I get your point that it is difficult to define "match" because there could be a one-to-many mapping, and selecting one of those "many" framework options might vary from customer to customer. 

If that's the case, we could have the behavior as you suggested in your previous posts and see if we get feedback from customers on target-framework differences. Could also somehow track telemetry? 

If a customer does want to update the target framework for a sample project they added, would they have to go to right-click-project > properties window?

**Comment by zewditu** [comment]
@romalpani  if they want to update yes , they can do manually,

**Comment by JakeRadMSFT** [comment]
.netcoreapp2.1 isn't going to be supported soon.

I'd go with 3.1 or 5

**Comment by briacht** [comment]
2 options:

Option 1: If the project is an app targeting .NET 3.1 or 5, then generated projects match this version. If app targets .NET Standard, then app will target 3.1

Option 2: When user is choosing name of generated projects in that same dialog they can choose which version to target @romalpani

**Comment by JakeRadMSFT** [comment]
Those sound good to me!

**Comment by romalpani** [comment]
@briacht 
I like the two options too. Depending on dev-effort, I'd suggest Option 2.

**Comment by JakeRadMSFT** [comment]
We decided on Option 1.

We will consider Option 2 again as we get customer feedback.

**Comment by vzhuqin** [comment]
Verify this issue on main branch:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.5
- .Net: 5.0.202
find the Console app project is still .NET Core 3.1, could you help to take a look?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a571e6e9-10a9-41bc-9388-83875eb4b994)

The Web API project has become .NET 5.0.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/403dfcb5-263b-4dcb-bbd6-27ad10acddce)

Steps：
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. After trained;
5. Added Console App and Web API projects.
6. Open the projects' properties to check the Target framework.

**Comment by vzhuqin** [comment]
The Target framework for the two projects have been .Net 5.0 on main branch: 16.5.25.2126902
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2c59a601-c6fc-45ed-a483-e93729358e6e)
