### ISSUE TITLE
Consume model / Add to solution: the NAMEs of Model and ConsoleApp projects : it would be useful if it could be SPECIFIED

### ISSUE THREAD

**Issue by petersesztak** [dotnet/machinelearning-modelbuilder#1385]
At the end of the ML.NET Model Builder process: Consume model / Add to solution:
it would be VERY useful if the NAMEs of Model and ConsoleApp projectst could be SPECIFIED.

Why?: if the developer needs two or more Models (Scenarios) in one solution (e.g. one forecasting for X, and another value prediction for Y), it's frustrating if the latest  Model Builder process wants to OVERWRITE the prev. projects.

Recommended solution:
in addition to the existing default solution (Model and ConsoleApp project names come from Solution name):
with one (BASE name and DERIVED Model and ConsoleApp project names) or two input textboxes (two independent  Model and ConsoleApp project names) the user can specify project names.

Péter

**Comment by beccamc** [comment]
@petersesztak This is great feedback! In our next public release we're moving to file based config for Model Builder. This means for your solution you would have two model builder files, forcasting.mbconfig and value.mbconfig for the project. We won't add two complete projects anymore, but specific code files for each solution (and they'd be named forcasting.x and value.x). 

You will still be able to add complete sample projects to your app, and if you do we allow you to specify a name: 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/cff9e36f-a9ae-4172-8480-c99c5f0c7134)

I think this will solve your problem. We're working on stabilizing this release now. It is available in a private preview build. If you're interested in trying it out I can send those details. Thanks!
