### ISSUE TITLE
Always open "Scenario" page when reopen the model builder from solution explorer.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1386]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**Describe the bug**
- Reopen the model builder, it always open "Scenario" page.

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add Model builder by right click on the project;
3. Go through "Re-Entrancy Test Pass"
4. See error: Reopen the model builder, it will not open the UI again to your last saved state.

**Expected behavior**
At any point when using Model Builder, if you close out of the UI, you can double click on the *.mbconfig in Solution Explorer, and it will open the UI again to your last saved state.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/114995368-53b9be00-9ed0-11eb-9afa-106781d72b69.png)
![image](https://user-images.githubusercontent.com/81727020/114995408-5ddbbc80-9ed0-11eb-8745-899273fa7dca.png)

**Additional context**
Reference: https://devblogs.microsoft.com/dotnet/ml-net-and-model-builder-march-updates/

**Comment by beccamc** [comment]
@JakeRadMSFT and @briacht We've discussed this previously. We can't save an MRU (most recently used) in the mbconfig file. We can open to the farthest valid tab. That is that expected behavior right?

**Comment by JakeRadMSFT** [comment]
@briacht @beccamc 

I think I would want it to open to Min(Evaluate Tab, Furthest Tab).

Essentially if Evaluate Tab is available ... open that one ... else open Furthest Tab.

**Comment by beccamc** [comment]
No traction on this issue in over a year. Closing as low priority
