### ISSUE TITLE
The data and trained results will be cleared if reopen model builder and click the same scenario. 

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1387]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add Model builder by right click on the project;
3. Go through "Re-Entrancy Test Pass";
4. After trained the model, closed and reopened the model builder;
5. Want to click the same scenario to go to next step, the data and trained results are cleared

**Expected behavior**
Reopen model builder, want to click the same scenario to see next step, but the data and trained results are cleared, this is not the expected, I do not want to train new model. Hope adding one prompt message to reminder user.

**Screenshots**

![image](https://user-images.githubusercontent.com/81727020/114998040-1f93cc80-9ed3-11eb-90b5-22c177af6aa3.png)

**Additional context**

**Comment by beccamc** [comment]
I believe the issue here is clicking on the Scenario card registers as starting a "new" scenario. All data is reset. Clicking on the same scenario card should be the same as using the left hand for navigation.

**Comment by vzhuqin** [comment]
Not repro this issue on latest main build: 16.7.2.2140901
![1387Fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2dd010c6-f5e9-4d11-bb0b-8a43f6092a8e)
