### ISSUE TITLE
 The advanced data options page will take a while to close if reopen model builder.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1390]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**Describe the bug**
- On which step of the process did you run into an issue: Advanced data option
- Clear description of the problem: Reopen the model builder>data>advanced data options, do some changes, click "Save" button, it will take a while to close the window.

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add Model builder by right click on the project;
3. After trained and close model builder;
4. Reopen and go to 'Data>Advanced data options' and do some changes;
5. Click "Save" button, it will take a while (5-15s) to close the window.

**Expected behavior**
The advanced data options page can close without waiting too long time.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/115003049-004b6e00-9ed8-11eb-8590-e4a37332167f.png)

**Comment by JakeRadMSFT** [comment]
Related #1389

@beccamc @zewditu are we re-calling into Prose on re-load?

**Comment by beccamc** [comment]
We shouldn't be. I will assign and take a look

**Comment by beccamc** [comment]
Just checked, we aren't calling PROSE on reload. Additionally, on the new build this was much faster. 

The save was pretty fast for me. I reopened an mbconfig file, and opened Advanced Data Options....
![fastSave](https://user-images.githubusercontent.com/9122518/116617671-bb75fd00-a903-11eb-9e4a-bba3870cea42.gif)

**Comment by vzhuqin** [comment]
this issue not repro on main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122901
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Reopen the Advanced data options dialog and click Save button with some changes, it can close quickly.
