### ISSUE TITLE
 The "model builder" need to delete twice from Solution Explorer.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1392]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
- Need to delete twice, the "Machine Learning" can be deleted from Solution Explorer. 

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add Model builder by right click on the project;
3. Click delete by right click the model builder;
4. Model builder appear again under the project;
5. Delete again, that can be deleted.

**Expected behavior**
no need to delete twice.

**Comment by beccamc** [comment]
@LittleLittleCloud Can you take a look here?

**Comment by LittleLittleCloud** [comment]
#1394

**Comment by LittleLittleCloud** [comment]
I've tried to reproduce it on latest main but failed... Maybe it's already been fixed by perf improvements PRs.

**Comment by vzhuqin** [comment]
This issue not occurs on main branch: 16.5.25.2127401
![1392.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/95b24676-3ab0-47d6-b91c-4191f200ad5b)
