### ISSUE TITLE
No update the packages to the latest version after trained.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1393]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add Model builder by right click on the project;
3. After trained the model,
4. See error: The packages do not be updated to the latest version.

**Expected behavior**
The packages have been updated to the latest version after trained.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/115007386-82d62c80-9edc-11eb-863a-b856eb9390f1.png)

**Additional context**

**Comment by beccamc** [comment]
@LittleLittleCloud Can you take a look here?

**Comment by LittleLittleCloud** [comment]
It's not a bug, the ML.Net version used by ModelBuilder is 1.5.4. So in order to keep the maximum compatibility, version 1.5.4 instead of 1.5.5 is installed to generated project.

**Comment by LittleLittleCloud** [comment]
@beccamc @vzhuqin 
Do we want to update test matrix to remove this item?

**Comment by vzhuqin** [comment]
Thanks @LittleLittleCloud explanation. @beccamc could you help to update this behavior to the related Test Passes?

**Comment by beccamc** [comment]
I've checked in the Test Pass docs so we all can modify them. @vzhuqin Where is this located in the test pass?

**Comment by vzhuqin** [comment]
@becca, this isn't mentioned on current test passes, I found it after trained. I'd like that can add this expected behavior to one related test pass, is that fine?

**Comment by beccamc** [comment]
Yes thats fine! You can modify the pass if you'd like.
