### ISSUE TITLE
Model builder error if click "Yes" for overwrite.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1394]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add model builder by right click on the project;
2. After trained and add a solution, delete the model builder;
3. Open the model builder from the added sample project;
4. Click "Add a solution" on consume page;
5. Click "Yes" for overwrite;
6. Prompt model builder error.

**Expected behavior**
Can overwrite the sample project even if delete the previous model builder.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/115007976-2b848c00-9edd-11eb-9aba-0171e75edef7.png)
![image](https://user-images.githubusercontent.com/81727020/115008524-cbdab080-9edd-11eb-99be-1389691f25cc.png)

**Additional context**

**Comment by beccamc** [comment]
@LittleLittleCloud Can you take a look here?

**Comment by LittleLittleCloud** [comment]
I can't reproduce it on the current main, moving it to validate.

**Comment by vzhuqin** [comment]
Yes, can't reproduce this issue on main build:  16.6.2.2135501
![1394.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9f50dd01-44bb-412d-93ba-31c30cf3b887)
