### ISSUE TITLE
ISSUE IN TUTORIAL BY MICROSOFT

### ISSUE THREAD

**Issue by JoyPikaX** [dotnet/machinelearning-modelbuilder#1395]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: CLR v4.0.30319
 - Visual Studio Version (if applicable): 16.9.4

**System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'MLAlgorithmML.Model.ConsumeModel' threw an exception.
  Source=MLAlgorithmML.Model
  StackTrace:
   at MLAlgorithmML.Model.ConsumeModel.Predict(ModelInput input) in Z:\WORK DRIVE\Studies\LAB SESSIONS\Practical\Sem 4\ASP.NET MINI PROJECT USING MYSQL\Source Code\MLAlgorithm\MLAlgorithmML.Model\ConsumeModel.cs:line 25
   at MLAlgorithm.Program.Main(String[] args) in Z:\WORK DRIVE\Studies\LAB SESSIONS\Practical\Sem 4\ASP.NET MINI PROJECT USING MYSQL\Source Code\MLAlgorithm\MLAlgorithm\Program.cs:line 21

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
- Clear description of the problem:

**To Reproduce**
Run myMLApp ( in my case MLAlgorithm app) (select Ctrl+F5 or Debug > Start Without Debugging). You should see the following output, predicting whether the input statement is positive or negative.

**Expected behavior**
![image](https://user-images.githubusercontent.com/18565218/115107176-de5cf480-9f86-11eb-8c69-cbfbea30efd4.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/18565218/115107194-fd5b8680-9f86-11eb-91b6-43dbf48737ae.png)

**Additional context**
A given tutorial by microsoft is not working for me guys please let me know if i missed a step thanks in advance

**Comment by beccamc** [comment]
@JoyPikaX Sorry you ran into this problem and thanks for reporting! Is your project a .NET Framework project? If so, we have troubleshooting instructions [here](https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#runtime-error-in-code-systemiofilenotfoundexception-could-not-load-file-or-assembly-microsoftmldata)

Let me know if that helps!

**Comment by beccamc** [comment]
Any luck with the above?

**Comment by Mukund-Iyer** [comment]
Similar issue had occurred when I was doing the Tutorial. Please add the ML.Net NuGet package to your project. I had to install the NuGet package for Microsoft.ML and all it's dependencies. It worked after selecting the Solution Platform (x86 or x64).

Please refer the now Closed Issue "System.TypeInitializationException #1411" raised by me, for more details.

**Comment by beccamc** [comment]
Unfortunately we don't have enough information on this issue. Please try the above suggestions. If you're still seeing a problem, please re-open and provide additional information. Thanks for reporting!
