### ISSUE TITLE
The Best model of Binary Classification shows Multiclass classification trainer.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1396]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add model builder by right click on the project;
3. After trained the model;
4. See error: The Best model of Binary Classification shows Multiclass classification trainers: LbfgsMaximumEntropyMulti

**Expected behavior**
The Best model of Binary Classification shows binary classification trainer.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/115187006-31fd4880-a115-11eb-9792-2026069f11a1.png)

**Additional context**
 Classification: https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**Comment by LittleLittleCloud** [comment]
It's expected because we don't have binary-classification for now, which means all classification is multi-classification. Do we want to update test metric for that?

**Comment by vzhuqin** [comment]
Thanks for @LittleLittleCloud explanation, I may have misunderstood as see the information from https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis-model-builder, then think this test matrix is for binary classification.
![image](https://user-images.githubusercontent.com/81727020/115646734-50ea1d80-a355-11eb-84da-6088156bb4db.png)
Do I need to close this issue since this is expected?
