### ISSUE TITLE
There is no update and loss of data information in Data Preview area after changed purpose.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1397]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Close the model builder after set the Data;
4. Reopen the model builder and go to Data page;
5. Click "Advanced data options...";
6. Change the "fare_amount" from "label" to "feature",  and change "trip_time_in_secs" from "ignore" to "feature";
6. Click Save button;
7. See error: on the data preview area, the "fare_amount" column still shows "Label", and the "Payment_type" column information is missing .

**Expected behavior**
In the data preview area, the data information is updated and not lost after changed purpose.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/115187933-bb614a80-a116-11eb-96b3-2bec6f42422c.png)

**Additional context**
Value: https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv

**Comment by beccamc** [comment]
Per discussion in design meeting on 4/29, we agreed to remove the behavior that modifies the data preview grid based on user changes. This has perf implications for large datasets. 

This is no longer a bug, because we're removing all data grid changes based on column updates.

**Comment by beccamc** [comment]
@vzhuqin For visibility on the above. I didn't see the Preview Data Grid updates included in the test plans. Let me know if there is some documentation I should update. Thanks!

**Comment by vzhuqin** [comment]
@beccamc Yes, because when the content of advanced data options is changed, most data of the Data Preview fields will change accordingly, so filed this issue. Could you help add this changed behavior to AdvancedDataTestPass when you are free?
