### ISSUE TITLE
I have Visual Studio Enterprise version 15.9.7 and the ML extension says could not find a suitable version of Visual Studio.

### ISSUE THREAD

**Issue by krravi55** [dotnet/machinelearning-modelbuilder#140]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rustd** [comment]
Model Builder required Visual Studio 2017 15.9.12 or later version. Please update to this version and try again.
