### ISSUE TITLE
The results of "Table" and "Column to predict (Label)" options lost for SQL.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1402]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Select "Value Prediction" scenario and Local CPU Environment;
4. Go to Data page, select "SQL Server" to load data;
5. Choose "taxi" for Table and "fare_amount" for Label fields;
6. Closed and reopened model builder;
4. See error: 
  a. The results of "Table" and "Column to predict (Label)" options lost. 
  b. If recommendation: The results of Table/Column to predict (Rating)/User column/Item column options lost.

**Expected behavior**
Reopen model builder, the data UI should be the last saved state.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/115200332-ae4c5780-a126-11eb-9d96-7a040c74ca39.png)
![image](https://user-images.githubusercontent.com/81727020/115200343-b1dfde80-a126-11eb-90fd-086a2b9cb319.png)
![image](https://user-images.githubusercontent.com/81727020/115200386-bf956400-a126-11eb-923e-f40b771b17d6.png)

**Additional context**
1. This error happen on all table of below test matrix:
    
![image](https://user-images.githubusercontent.com/81727020/115201291-c40e4c80-a127-11eb-9ef7-78b85ba0b080.png)

2. The data in advanced data options dialog isn't lost.
    
![image](https://user-images.githubusercontent.com/81727020/115201062-798cd000-a127-11eb-9cc7-1481ebcef207.png)

2. SQL Classification: https://testpass.blob.core.windows.net/test-pass-data/iris.mdf

**Comment by vzhuqin** [comment]
Verified this issue on main branch: 16.5.25.2127102 & 16.5.25.2127401
Reentrancy the SQL model builder, the "Column to Predict (Label)" still lost,  if training completed before reentrancy, the training result comes back after re-selected the column.
@beccamc , could you help to take a look this issue again?
![#1402.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/71dd60bd-3922-45f4-9795-edde69b08af2)

**Comment by vzhuqin** [comment]
Still occurs on main branch: 16.5.25.2127802

**Comment by beccamc** [comment]
So sorry for the issues on this Qin. It should now be fixed!

**Comment by vzhuqin** [comment]
Will verify it when the issue #1494 is fixed.

**Comment by vzhuqin** [comment]
This issue has been fixed on main branch: 16.5.25.2130702
Reentrancy before training:
![1402Fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/dffdf8cb-c18f-4dd6-ac73-90bdb87afd48)
Reentrancy after training complete:
![1402Fixed-2.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/c59e2626-a663-48b3-92fb-b451fb780b40)
