### ISSUE TITLE
The predicted label value should not list in the model input of the generated sample project.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1403]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Click "Add a solution" on consume page after trained ;
4. Open the program.cs file of the generated sample project;
5. See error: The predicted label column show in the file.

**Expected behavior**
Label information is a predict value, no need to list in the model input.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/115207526-43068380-a12e-11eb-9b0d-178454add20f.png)
![image](https://user-images.githubusercontent.com/81727020/115207655-5e718e80-a12e-11eb-964a-2757fdf6bc09.png)

**Comment by beccamc** [comment]
@LittleLittleCloud Is this fixed? It sounds familiar to me.

**Comment by LittleLittleCloud** [comment]
Related issue
- https://github.com/dotnet/machinelearning-modelbuilder/issues/1319

I take a look at the fix PR and it only remove label value for code behind files. Since this file is in generaeted console app so I'm afraid it's not fixed yet.

@zewditu Can you create another fix similar to this one
- https://github.com/dotnet/machinelearning-tools/pull/974/files

**Comment by zewditu** [comment]
@LittleLittleCloud , https://github.com/dotnet/machinelearning-tools/pull/974/files  can  remove label column from  Program.cs file too. 


![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/705ed0dd-4f71-4b49-b9cc-16fb7e5da40b)

# Program.cs
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/3f03e1ba-4095-4998-90c2-448a6e49bc3e)

@vzhuqin  Might not get the latest  build after this fix merged

**Comment by vzhuqin** [comment]
This issue cannot be repro on build: 16.5.21.2122801

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/71e79fe0-c567-4f78-8f2c-f75fd1234eaf)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/913390dd-4390-411b-97ce-52ae62f507a5)
