### ISSUE TITLE
The Azure environment need to set up again and the trained result is lost if reopen the model builder.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1407]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Select "Object detection" scenario and set up workspace;
4. Input the data and trained successfully;
5. Close and reopen the model builder;
6. See error: 
 a. On Environment page: the workspace information have been reset, need to set up again.
 b. On Train page: the trained result is lost, and the UI have changed.

**Expected behavior**
The Environment and Train page should be the last saved status.

**Screenshots**
Environment page (reopen):
![image](https://user-images.githubusercontent.com/81727020/115330184-261d8f00-a1c6-11eb-86f4-3638e48597db.png)

Environment page (Last saved):
![image](https://user-images.githubusercontent.com/81727020/115330231-39c8f580-a1c6-11eb-84bb-a88c2e63f1f4.png)

Train page (reopen):
![image](https://user-images.githubusercontent.com/81727020/115330536-d25f7580-a1c6-11eb-94a3-169fc3d799e0.png)
Train page (Last saved):
![image](https://user-images.githubusercontent.com/81727020/115330568-e4411880-a1c6-11eb-9f69-25c8df301ab2.png)

**Additional context**
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder

**Comment by beccamc** [comment]
This is fixed! 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c46460d0-9f60-46d4-8667-4bec6dbf49ca)

**Comment by vzhuqin** [comment]
Thanks @beccamc , could you help to confirm whether "the workspace information was reset after reopen model builder" is expected?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/43289e0c-2d92-49c6-ac3e-cd42bfac022a)

**Comment by vzhuqin** [comment]
This issue not occurs on main branch: 16.5.25.2126902
![1407.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2fcfbc50-7854-4034-8f9b-e409315446a5)
