### ISSUE TITLE
System.IO.IOException occurs when running Azure object detection project.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1408]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Select "Object detection" scenario and set up workspace;
4. Input the data and trained successfully;
5. Add a solution on consume page;
6. Run the sample console app project;
7. See error: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

**Expected behavior**
No error during running the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/115346693-1791a080-a1e3-11eb-94bc-6cb5f5a9423e.png)

**Additional context**
Data (labeled and exported by using VOTT) from this tutorials: :https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder

**Comment by beccamc** [comment]
I'm not seeing the problem anymore

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/2183dad4-00e7-4db9-9ea3-d9fb714099e2)

**Comment by vzhuqin** [comment]
Yes, also not occurs on latest main branch: 16.5.25.2127401
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/d66a2221-674e-4c48-9cf8-2fee3e113000)
