### ISSUE TITLE
Project structure should not be changed after renamed .mbconfig file in solution explorer. 

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1409]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Close the model builder after trained;
4. Rename the model builder from "xxxMLModel1.mbconfig" to "xxxMLModel2.mbconfig" in solution explorer;
5. See error: the structure of model builder changed.

**Expected behavior**
Project structure should not be changed after renamed .mbconfig file in solution explorer. 

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/115353365-02207480-a1eb-11eb-9419-a1e1c1a29cd4.png)

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud Is there a way to detect name changes and then make sure our project file is up to date?

**Comment by LittleLittleCloud** [comment]
@JakeRadMSFT 
There should be a way through VS project system, I can take a look when I have time.

**Comment by LittleLittleCloud** [comment]
Could be solved together with #1446

**Comment by v-Hailishi** [comment]
The bug is not repro on the latest main build 17.17.0.2345601.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/5f5ebbdb-9855-4a02-907a-c0316be87ffe)
