### ISSUE TITLE
Update version of mlnet tool

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-modelbuilder#141]
Tomorrow the AutoML team is expecting to release a new version of the mlnet CLI (and the AutoML API), as part of the normal ML.NET monthly release cadence.

No issues are expected for Model Builder as this release is mostly bug fixes and stability improvements. For example the release will include a bug fix which will help internationalization (https://github.com/dotnet/machinelearning-modelbuilder/issues/93).

Currently Model Builder is pinned to the mlnet/0.3.0 nuget. 

Task:
Model Builder should update to the new CLI nuget once available. 

/cc @daholste, @JakeRadMSFT

**Comment by justinormont** [comment]
The AutoML API and CLI has been updated to 0.14.0. 

Release notes: https://github.com/dotnet/machinelearning/releases/tag/v1.2.0
CLI NuGet: https://nuget.org/packages/mlnet/
AutoML NuGet: https://nuget.org/packages/Microsoft.ML.AutoML/

**Comment by LittleLittleCloud** [comment]
See this [PR](https://github.com/dotnet/machinelearning-tools/pull/245)
