### ISSUE TITLE
System.TypeInitializationException

### ISSUE THREAD

**Issue by Mukund-Iyer** [dotnet/machinelearning-modelbuilder#1411]
**System Information (please complete the following information):**
 - DotNet CLI Version: 5.0.202
 - Visual Studio Version 16.9.4

**Describe the bug**
- URL of the Tutorial Step on which I encountered the issue: https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
- Received this issue: 
 `Unhandled Exception: System.TypeInitializationException: The type initializer for 'MyMLAppML.Model.ConsumeModel' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at MyMLAppML.Model.ConsumeModel..cctor()
   --- End of inner exception stack trace ---
   at MyMLAppML.Model.ConsumeModel.Predict(ModelInput input)
   at myMLApp.Program.Main(String[] args) in C:\Users\mukun\source\repos\myMLApp\myMLApp\Program.cs:line 17

   Press any key to continue . . .
`

**To Reproduce**
1. Replace the code in Program.cs with the code mentioned in from Tutorial.
2. Click Ctrl+F5

**Expected behavior**
It should have shown a console window with the following output:
"Text: This restaurant was wonderful.
  Sentiment: Positive"

**Screenshots**
![image](https://user-images.githubusercontent.com/82875381/115379543-3f870100-a1ef-11eb-90d8-c8771236597d.png)

**Additional context**
None.

**Comment by LittleLittleCloud** [comment]
Did you add a package reference to `Microsoft.ML` in MyMLAppML project after you replace the code in Program.cs

**Comment by Mukund-Iyer** [comment]
I had to install the NuGet package for Microsoft.ML and all it's dependencies. It worked after selecting the Solution Platform (x86 or x64). Thanks for the support. Really appreciate it.
