### ISSUE TITLE
Provide confusion matrix after training

### ISSUE THREAD

**Issue by sarul84** [dotnet/machinelearning-modelbuilder#1415]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
In the evaluate phase, we are seeing only best fit models over all accuracy and model name but having confusion matrix of the best fit model here would help developers to understand the model in better way.

**Describe alternatives you've considered**
Tried to extract confusion matrix programmatically but it's not giving correct value.

**Additional context**

**Comment by LittleLittleCloud** [comment]
Loop in our PM @briacht

**Comment by briacht** [comment]
Thanks for the suggestion!

Adding @houghj16 who is currently working on Model Explainability in ML.NET and can investigate adding confusion matrix after training.

**Comment by briacht** [comment]
Could we add confusion matrix to generated notebook?

And if we move forward with "Explain" page in UI, this would be good to add here.
