### ISSUE TITLE
Update CodeGen comment - SampleData has been removed from CodeBehind.

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1416]
![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/2b7badaf-f496-4fb9-a77c-442dbb20029a)

**Comment by LittleLittleCloud** [comment]
@zewditu  can you take a look, it looks like a regression caused by this PR
- https://github.com/dotnet/machinelearning-tools/pull/1004

@briacht Just to confirm if it's our plan to remove `GetSampleData` from all codegen file, or just console app and web api project.

**Comment by JakeRadMSFT** [comment]
Yes that was the plan - 

We should update the comment in the code-gen though!
