### ISSUE TITLE
The code snippet on Consume page should not lost after added to solution and re-opened.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1417]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301 
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

**Main branch:** 
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

**To Reproduce**
1). Download data set from: https://raw.githubusercontent.com/dotnet/machinelearning/main/test/data/taxi-fare-train.csv
2). Create new C# console app with .Net 5.0;
3). Add model builder by right click on the project;
4). Click "Value prediction" on Scenario page to navigate to Environment page;
5). Select Local (CPU) on Environment page;
6). Select File and click "Browse..." to input the downloaded dataset, set "fare_amount" to "Column to predict (Label)" on Data page;
7). Click "Start training" with default 600s train time on Train page, and wait Training complete;
8). Click "Predict" button on Evaluate page;
9). Navigate to Consume page, added one Console app sample project, then saved the model builder and closed it;
10). Reopen the model builder and navigate to Consume page;
11). See error: the code snippet lost.

**Expected behavior**
The code snippet on Consume page should not lost after added to solution and re-opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/116059913-f41f9780-a6b3-11eb-90a7-4af54a318c3c.png)

**Comment by JakeRadMSFT** [comment]
I believe this is fixed on Main

**Comment by vzhuqin** [comment]
This issue was found on main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

- ML.Net Model Builder (Preview): 16.5.21.2122301

And can be repro on build: 16.5.21.2122801 from https://privategallery.blob.core.windows.net/gallery/refs/heads/u/jakerad/init-and-spinners/atom.xml, could you help to take a look?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/841430a9-9746-415c-8032-eb257c23b753)

**Comment by vzhuqin** [comment]
Verify this issue on main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- ML.Net Model Builder (Preview): 16.5.21.2122903

Step:
Reopen the model builder, navigate to consume page, find the code snippet will not be displayed until 1-2 seconds, could you help to take a look?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a3617664-6ec8-4c9c-b4c0-297c5a22c026)
after 1-2 seconds:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/5d6a56af-1d3f-4ee4-a7e9-d4fd2c451005)

**Comment by vzhuqin** [comment]
The code snippet needs to wait 2-3s to appear after reopen , could you help to take a look again?
Main branch: 
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202
![wait 2-3s.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/164d279d-ed42-40fd-a426-71edbc079d2f)

**Comment by vzhuqin** [comment]
@beccamc  @JakeRadMSFT  The code snippet needs to take about 5-10s to display again, could you help to take a look?
![5-10s.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/d343924f-6710-4f2b-b74f-1b366196a8d4)

**Environment:**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.5.25.2127801
- Microsoft Visual Studio Enterprise 2019: 16.10.0
- .Net: 5.0.300

**Comment by LittleLittleCloud** [comment]
The code snippet will take a while to present if it's the first `.mbconfig` to open in your VS instance. This is because the API to get that code snippet is from a service hub service and it takes some time to start from cold status. However, if you have multiple `.mbconfig` opened in VS, the code snippet should appear pretty fast.

**Comment by LittleLittleCloud** [comment]
The code snippet takes about 1~3 seconds to show in the first `.mbconfig` and it appears pretty fast on the second attempt. So the delay should be expected.
