### ISSUE TITLE
Update generated Predict() method to increase inference perf

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1419]
Update generated code so that:

- Creating a new MLContext
- Loading the model
- Creating the Prediction Engine

happen outside of the Predict() method. We don't want all these things to happen everytime Predict() method is called; they should only happen once.

**Comment by luronumen** [comment]
Suggested partial consumption class (e.g.: _TestCaseClassifier.consumption.cs_):

![TestCaseClassifier consumption](https://user-images.githubusercontent.com/8019466/116398608-5f758080-a7fe-11eb-976c-0ae5e7b8475b.png)

**Comment by zewditu** [comment]
@Brichat, do we have a specific template for the predict method?

**Comment by beccamc** [comment]
Zewditu is blocked on what behavior we want. Jake and Bri, let us know what behavior you want here.

**Comment by LittleLittleCloud** [comment]
Thanks @luronumen for your wonderful example, @zewditu can you update consumption.cs to the following code?

@briacht Do we want to make `PredictEngine` publicly available?

```csharp
        private static string MLNetModelPath = Path.GetFullPath("titanic-binary.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
```

Experiment shows a huge perf improvement on predicting 100 data after applying lazy loading
| | before | after |
| - | - | - |
| n = 1 | 952ms | 1420ms |
| n = 100 | 19575ms | 1350ms |
