### ISSUE TITLE
tensorflow.dll packaged with 16.3.0.2056001 is dependent upon cuda 10.0 not 10.1.

### ISSUE THREAD

**Issue by mikeydoo** [dotnet/machinelearning-modelbuilder#1421]
**Model Builder Version**: Microsoft.ML.ModelBuilder.GPU","version":"16.3.0.2056001
**Visual Studion Version**: Microsoft Visual Studio Community 2019 Version 16.9.4

**Bug description**
tensorflow.dll packaged with 16.3.0.2056001 is dependent upon cuda 10.0 not 10.1.

**Steps to Reproduce**
Install from scratch following guide.

**Expected Experience**
Should work with cuda 10.1

**Actual Experience**
![image](https://user-images.githubusercontent.com/1997877/116301546-10950000-a798-11eb-9ecc-7b0d13d13e9d.png)

**Additional Context**
installing 10.1 or 10.0 dosnt work you get errors 
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize

probably down to wrong versions of tensorflow.dll

**Comment by JakeRadMSFT** [comment]
We have an updated version of Model Builder coming out soon that works with 10.1. 

Would you be interested in trying the preview build?

**Comment by mikeydoo** [comment]
That would be really good thanks Jake

**Comment by JakeRadMSFT** [comment]
@mikeydoo  you can sign up for the preview here:

 https://aka.ms/mb-private-preview
