### ISSUE TITLE
Model builder error for "Recommendation" scenario and SQL training.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1424]
**System Information (please complete the following information):**

- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122801
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

**Branch:**
https://privategallery.blob.core.windows.net/gallery/refs/heads/u/jakerad/init-and-spinners/atom.xml

**Data Set:**
https://testpass.blob.core.windows.net/test-pass-data/iris.mdf

**To Reproduce**
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Select "Recommendation" on Scenario page;
4. Select Local (CPU) on Environment page;
5. Select SQL Server and in put the data set;
6. Select "recommendation-ratings-train" as "Table", "rating" as Column to predict (Rating), "userId" as "User column", "movieId" as "Item column";
7. Click "Start training" with default 60s on Train page;
8. Pop up Model Builder Error: 
![image](https://user-images.githubusercontent.com/81727020/116387196-257f9b00-a84d-11eb-9646-257835930056.png)

**Screenshots**

**Additional context**
I cannot change column type as "Advanced data options" is not available for Recommendation scenario.

**Comment by beccamc** [comment]
Note, for validating this the "rating" column needs to be changed to single type. This can be done in the advanced data options dialog (recently added the column options for recommendation into the dialog)
