### ISSUE TITLE
"Text classification" scenario should not be selected by default after reopened model builder.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1426]
**System Information (please complete the following information):**
 - Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122901
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

**Branch:** 
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

**To Reproduce**
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Save and close the model builder;
4. Reopen the model build, see the "Text classification" scenario be selected by default. 
![image](https://user-images.githubusercontent.com/81727020/116515613-19541600-a8ff-11eb-849e-b550969154de.png)

**Expected behavior**
No scenario is selected after reopen the model builder since nothing was done before closing.

**Comment by beccamc** [comment]
Maybe this should go to chopping block? I'm not sure many customers will run into this. @JakeRadMSFT You put this in September, do you think it should be fixed?

**Comment by beccamc** [comment]
Oh actually this is fixed! 
![image](https://user-images.githubusercontent.com/9122518/130296016-5ac6b780-4ec2-4afc-a9b8-b5e0097dcbd3.png)

**Comment by LittleLittleCloud** [comment]
Validate it on VS2022 using the following mbconfig

```
{
  "TrainingTime": 0,
  "Scenario": "Default",
  "Type": "TrainingConfig",
  "Version": 1
}
```

**Comment by beccamc** [comment]
I propose it goes to the chopping block! Any thoughts XioaYun?
