### ISSUE TITLE
Train page displays abnormally.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1427]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122901
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

**Branch:**
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

**Data Set:**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Click "Text classification" on Scenario page;
4. Click Local (CPU) on Environment page;
5. Select "File" and input the data set, set "Sentiment" as label;
6. Navigate to Train page, see Train page displays abnormally as below screenshot:
![image](https://user-images.githubusercontent.com/81727020/116521381-799a8600-a906-11eb-9b45-781c42eaa529.png)

**Expected behavior**
Train page should display normally.

**Additional context**

- If close the model builder, then reopen, the train page changes to normal, and can complete training for Local (CPU)+File data.

![image](https://user-images.githubusercontent.com/81727020/116522273-97b4b600-a907-11eb-98f5-99721cc699ab.png)

- If close the model builder, then reopen on Local (CPU)+SQL Server, the train page still displays abnormally.

- This issue not happen on Azure environment of image classification and object detection scenarios.

**Comment by beccamc** [comment]
I think this is a regression introduced by @JakeRadMSFT async work.

**Comment by JakeRadMSFT** [comment]
Way to call me out! Yes it is :)

**Comment by beccamc** [comment]
That's what I'm here for! 😁
