### ISSUE TITLE
Localhost page can't be found for WebApi project.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1428]
**System Information (please complete the following information):**

- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122901
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

**Branch:**
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

**To Reproduce**
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. After trained;
4. Add Console app and Web API to solution;
5. Run the WebApi project, see error: This localhost page can't be found.
![image](https://user-images.githubusercontent.com/81727020/116536685-d18db880-a917-11eb-8b5a-60e1d1b3cc40.png)

**Comment by briacht** [comment]
This is not a bug. There are different ways of testing web apis (e.g. with PowerShell). We will assume that web developers will know how to test this web api and wait for customer feedback if that's not the case (at which point we can offer additional guidance on how to test the web api)
