### ISSUE TITLE
Multiple cuda installed shouldn't block GPU training.

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1429]
We should not block GPU training as long as Cuda 10.1 is enabled as the default version to use even if multiple Cuda versions are founded. To check if Cuda 10.1 is default Cuda, we can validate through two ways:
- `nvcc --version` and check the output cuda version
![image](https://user-images.githubusercontent.com/16876986/116619866-e5282780-a8f5-11eb-9cbe-b4f64c1315ca.png)

- check the path to Cuda binary in $Path variable and make sure Cuda10.1 appears at the top.

**Comment by JakeRadMSFT** [comment]
Keeping the current checks to keep things simple

**Comment by beccamc** [comment]
Moving this to triage for Jake and Xiaoyun to discuss if we want to fix this :)

**Comment by LittleLittleCloud** [comment]
track in #1642
