### ISSUE TITLE
Project overwrite autorization should be done  before the project generated 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1430]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
For Console and WebApi projects the project name authorization window popup after a while.  because the project names are checked after the project generated by the code gen , but we need to check just after the user type project name and click on Add to solution.

**Steps to Reproduce**
1.Select any scenario.
2.  Pass all steps till consume page.
3. Click on Add to solution button of console app or Web ApI .
4 Give project name and click Add to solution button.
5.Click on Add again button 
6. Give the same project name as the previous one and click on Add to solution  button 

**Expected Experience**
If project name conflict happened  authorization window should popup immediately.

**Actual Experience**
Request to overwrite the project name window popup after a  spinner displayed for a while 
**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
@zewditu Can you add more details to this bug? Now that Qin is helping us out we need to make sure everything is well explained for testing.

**Comment by zewditu** [comment]
@beccamc Sure!

**Comment by vzhuqin** [comment]
Can repro this issue on main branch, could you help to take a look?
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.5
- .Net: 5.0.202

The spinner displayed for 2s, then the overwrite window popup and the spinner continue displaying for about 5s.
![overwrite window2.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/26024c18-4f2c-4cee-8c7d-beb997701ee6)

**Comment by beccamc** [comment]
Yes this is correct! The issue was a spinner on the page (next to the "Add" button). I will close, thanks!
