### ISSUE TITLE
Performant selection picker (Label column, SQL tables, etc.)

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1431]
Our combo box is not performant. Users can have +10,000 columns, and it is impossible to open an interact with the drop down. This is a problem for our Label/User/Item columns and for SQL Tables. 

@romalpani for design help.

**Comment by romalpani** [comment]
Here's a WIP of two options to consider. 
https://www.figma.com/file/txIDYwDkd7qM4LV71lPUar/?node-id=32%3A55383

**Comment by beccamc** [comment]
https://github.com/dotnet/machinelearning-modelbuilder/issues/2008

**Comment by beccamc** [comment]
@luisquintanilla and @JakeRadMSFT [here is the dashboard](https://dataexplorer.azure.com/dashboards/5b95430c-93c0-4ccd-9a6c-6237ce7acfce?_startTime=1hours&_endTime=now#d15abd4c-5a6a-44c2-affa-29bbc460e14a) that shows column count. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/546a5d73-e337-4816-8ca4-16f3f88e804b)

I know this is a bit hard to read. Left graph shows that the most common column counts are under 10 (blue bar) and over 500 (bright pink bar).  Right graph shows that the average column count is 75. 

It seems that large datasets are quite popular, with over 900 uses of large datasets in February.

**Comment by JakeRadMSFT** [comment]
Kinda related to https://github.com/dotnet/machinelearning-modelbuilder/issues/1986

**Comment by luisquintanilla** [comment]
Thanks @beccamc for looking into this. Let's see how we can improve this experience. One thing we might have to look into is whether there are limitations on the number of columns algorithms use.

**Comment by luisquintanilla** [comment]
Info on trainers can be found here: [Create page with info about trainers · Issue #5896 · dotnet/machinelearning · GitHub](https://github.com/dotnet/machinelearning/issues/5896)

**Comment by beccamc** [comment]
I've taken a closer look at the telemetry, and the large number of columns I reported earlier is incorrect. Due to a bug we were bucketing failed and folder data into the large number of columns bucket. 

![image](https://user-images.githubusercontent.com/9122518/186003949-ba5495fb-f083-488f-8b6b-133f2ca1e4b0.png)

The true numbers show that small (<10 columns) datasets are more common.
