### ISSUE TITLE
Unable to execute MLNet CLI on Apple Silicon machine

### ISSUE THREAD

**Issue by cigoic** [dotnet/machinelearning-modelbuilder#1432]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.2.0
 - Visual Studio Version (if applicable): 2019 for Mac 8.9.8 (build 7)

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: mlnet get killed by zsh immediately.

**To Reproduce**
1. Install mlnet: `dotnet tool install -g mlnet`
2. Unzip yelp_labelled.txt to current work folder.
3. Execute commend: `mlnet classification --dataset "yelp_labelled.txt" --has-header false --label-col 1 --train-time 20`
4. Error: `zsh: killed     ~/.dotnet/tools/mlnet classification --dataset "yelp_labelled.txt"  false 1 2`

**Expected behavior**
mlnet starts training process.

**Screenshots**
![Screen Shot 2021-05-04 at 1 52 23 PM](https://user-images.githubusercontent.com/2939228/116965292-06b35580-ace0-11eb-86ee-0bfb19e27b65.jpg)

**Additional context**

**Comment by JakeRadMSFT** [comment]
Thanks for reporting and for showing interested of mlnet running on apple silicon! 


Currently ML.NET framework isn't fully apple silicon compatible. We're working closely with that team and when it's available we'll release a new mlnet cli as well.

Thanks for your feedback!

**Comment by JakeRadMSFT** [comment]
Related: https://github.com/dotnet/machinelearning/pull/5628

**Comment by luisquintanilla** [comment]
Hi @cigoic 

We recently published some updates to the CLI and you should be able to use it with M1.

You can install it with the following command:

```dotnetcli
dotnet tool install -g mlnet-osx-arm64
```

For more details, see the [installation instructions](https://docs.microsoft.com/dotnet/machine-learning/how-to-guides/install-ml-net-cli?tabs=mac#arm-1).
