### ISSUE TITLE
Train all models before generated code

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1433]
I've trained one model, and have 8 minutes of training left. We've already generated the code files, and have added the .zip file. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/79274e4c-e0a0-49b4-9e33-eed2f8fdffa6)

**Expected Behavior: Code files should be generated once it's "Done" or when user click Stop Training and 1 or more models has been trained.**

**Comment by JakeRadMSFT** [comment]
It should happen once it's "Done" or when they click Stop Training and 1 or more models has been trained.

**Comment by beccamc** [comment]
Thanks! Will update the bug description to make clear it's a bug.

**Comment by beccamc** [comment]
The code files should generate after the **last** model finishes training (when training is done).

**Comment by zewditu** [comment]
@beccamc ,@JakeRadMSFT  @briacht   when we display the label for code behind ?

![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/9d13da26-77e7-45ce-88b8-03714a68c917)


currently, we displayed all training results at the same time.

**Comment by beccamc** [comment]
We should display after training is complete.

**Comment by zewditu** [comment]
when does the user see generated files added to their project?

**Comment by beccamc** [comment]
Generated files should be added to the project after training is done. 
1. Start training
2. Training finishes
3. "Generated code behind files" label shows & generated code behind files are added to project

**Comment by vzhuqin** [comment]
This issue not occurs on main branch: 16.5.25.2127401
![1433.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b99c5cda-5180-4e60-9e2a-79804be055aa)
