### ISSUE TITLE
Azure Training issue

### ISSUE THREAD

**Issue by GHoltmann** [dotnet/machinelearning-modelbuilder#1437]
Hi Guys, good job, you made a very clear guideline about object detection and machine learning. I went thorugh the steps you described, but I am stuck at the model training with a resource issue in Azure.  I get a very general error 'Resource {dataName} is in conflicting state.' at the azure execution. To work around the issue, I´ve done some resources recreation and several different tests. still getting the same error. Maybe you have encountered the same error before?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63a4f3b7-a2a6-760a-534b-22788ba77b5c
* Version Independent ID: 1bee7901-164f-d9a7-9e7b-fd0ba55ad42e
* Content: [Tutorial: Detect objects in images with Model Builder - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#feedback)
* Content Source: [docs/machine-learning/tutorials/object-detection-model-builder.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/object-detection-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @briacht
* Microsoft Alias: **brachtma**

**Comment by briacht** [comment]
Hi @Gholtmann, thanks for filing this issue!

I've transferred the issue to the Model Builder repo so the team can investigate.

**Comment by GHoltmann** [comment]
Thank you @briacht - should you need further info to reproduce the issue, please dont hesitate to let me know.
    El miércoles, 5 de mayo de 2021 13:08:30 ART, Bri Achtman ***@***.***> escribió:  
 
 


Hi @GHoltmann, thanks for filing this issue!

I've transferred the issue to the Model Builder repo so the team can investigate.

**Comment by beccamc** [comment]
@GHoltmann Sorry you're experiencing this problem, and thanks for reporting. 

It sounds like the error is happening after you start training? Can you click on the "Monitor current run in Azure portal" link? If you don't see a link you can navigate there manually by going to https://ml.azure.com/ and navigating to the ML Workspace you are using, and then the Experiments tab. 

There should be a more detailed error in the training run. If you don't see if in the status area, you may need to go into the child runs and see if the error is reported there. 

![image](https://user-images.githubusercontent.com/9122518/117357716-e5d33780-ae7a-11eb-96c3-4646e1efa01c.png)

Can you let me know the error details you see there? Let me know if you have questions. Thanks!

**Comment by GHoltmann** [comment]
Thank you  Becca, see below. It seems that child task did not even start. Its in spanish, second screen capture 'ejecuciones secundarias' means child tasks, and marked as 'no inicado' (not started)









    El jueves, 6 de mayo de 2021 16:57:23 ART, Becca McHenry ***@***.***> escribió:  
 
 


@GHoltmann Sorry you're experiencing this problem, and thanks for reporting.

It sounds like the error is happening after you start training? Can you click on the "Monitor current run in Azure portal" link? If you don't see a link you can navigate there manually by going to https://ml.azure.com/ and navigating to the ML Workspace you are using, and then the Experiments tab.

There should be a more detailed error in the training run. If you don't see if in the status area, you may need to go into the child runs and see if the error is reported there.



Can you let me know the error details you see there? Let me know if you have questions. Thanks!

**Comment by beccamc** [comment]
@GHoltmann I think you included a screenshot, but I am not able to see it.  Can you open the issue and upload directly?

**Comment by GHoltmann** [comment]
HI @beccamc I uploaded the two screen captures below are you able to see them now?

![image](https://user-images.githubusercontent.com/83649292/117737003-4510af00-b1cf-11eb-93fc-17e7611c2e31.png)

![image](https://user-images.githubusercontent.com/83649292/117737055-683b5e80-b1cf-11eb-9428-2fd922af3fd6.png)

**Comment by beccamc** [comment]
@GHoltmann Sorry for the delay. I've looked around and have no idea what is causing this. Would you mind taking a look at the resources this run is trying to use?

You can find the summary on the Environment page. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/827d152b-747f-4d88-8202-897c3502a63d)

Specifically, is there only one Compute with your chosen name? Does the compute seem to be created correctly? We might need to pull the Azure team in on this one.

**Comment by GHoltmann** [comment]
@beccamc thank you Becca, please see below the screen capture. It draws my attention that resource id has two hyphens instead of having a name. 

![image](https://user-images.githubusercontent.com/83649292/118828874-098f7800-b894-11eb-8f36-c40896e0575f.png)

**Comment by beccamc** [comment]
@GHoltmann - Sorry for the delay again. Feel free to ping me if I don't respond in a few days. 

Can you double check the data has uploaded properly? 

Check your expected Label file location in Experiments -> _ExperimentName_ -> _FailedRun_ -> See All Properties -> Raw Json
![image](https://user-images.githubusercontent.com/9122518/120563762-fc63a480-c3ce-11eb-855b-a0feb6c304b4.png)

Then go to Datastores-> workspaceBlobStore -> Browse (Preview)
![image](https://user-images.githubusercontent.com/9122518/120563907-4ea4c580-c3cf-11eb-8d44-eef011aa186c.png)

Can you see if the json file is there, and the images are there?

**Comment by beccamc** [comment]
Any update on this issue? Was the data uploaded to the expected spot?

**Comment by GHoltmann** [comment]
Hi Becca, sorry for the delay. I tested many times but got stucked always at the same step. Was unable to solve the Azure issue by myself. Its probably simple for the Azure team to solve. 


Enviado desde Yahoo Mail para iPhone


El viernes, julio 9, 2021, 1:53 p. m., Becca McHenry ***@***.***> escribió:




Any update on this issue? Was the data uploaded to the expected spot?

**Comment by beccamc** [comment]
Sorry to ask the same question, but was the data uploaded to the right spot, as described [here](https://github.com/dotnet/machinelearning-modelbuilder/issues/1437#issuecomment-853445025)?

**Comment by GHoltmann** [comment]
Hi Becca, 
I was unable to check specifically on your question once again since my azure trial account has expired. Any suggestions?


Enviado desde Yahoo Mail para iPhone


El jueves, julio 15, 2021, 12:10 p. m., Becca McHenry ***@***.***> escribió:




Sorry to ask the same question, but was the data uploaded to the right spot, as described here?

**Comment by beccamc** [comment]
Unfortunately I'm not sure what to do if that Azure trail has expired. Are you using a new Azure account?

**Comment by GHoltmann** [comment]
Hi Becca! thank you for your help. Yes its a new Azure account and I guess there is something wrong with the accounts permissions. At my company we do have corporate Azure services, but for testing new solutions and concepts like this its easier to test with trial accounts rather than going through all the corporate approvals required internally to use a coporate Azure user.So considering the above, can you confirm is a newly created account goes smoothly with this ML setup? 
    El lunes, 30 de agosto de 2021 16:12:04 ART, Becca McHenry ***@***.***> escribió:  
 
 


Unfortunately I'm not sure what to do if that Azure trail has expired. Are you using a new Azure account?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by beccamc** [comment]
I haven't seen this problem with a newly created account. We are releasing a new Model Builder version this week (or early next).  I would recommend we try with that.

**Comment by GHoltmann** [comment]
Oh thats great news. Could you lt me know when ot os released? I will try with the new version. 


Enviado desde Yahoo Mail para iPhone


El jueves, septiembre 2, 2021, 7:31 p. m., Becca McHenry ***@***.***> escribió:




I haven't seen this problem with a newly created account. We are releasing a new Model Builder version this week (or early next). I would recommend we try with that.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by beccamc** [comment]
We just uploaded the new bits for VS 2019! You can download and try from the marketplace https://marketplace.visualstudio.com/items?itemName=MLNET.07

I think for your scenario you only need the VS 2019 Model Builder extension. In case you need other scenarios covered... the Model Builder GPU extension and VS 2022 aren't out yet. GPU should be available later today. VS 2022 will be available sometime between September 6th and September 15th.

**Comment by beccamc** [comment]
Any luck with the new version?

**Comment by GHoltmann** [comment]
Hi Becca, we will be testing your new version in November, as our team is currently working on other projects. I will keep you updated!
    El viernes, 3 de septiembre de 2021 13:33:24 ART, Becca McHenry ***@***.***> escribió:  
 
 


We just uploaded the new bits for VS 2019! You can download and try from the marketplace https://marketplace.visualstudio.com/items?itemName=MLNET.07

I think for your scenario you only need the VS 2019 Model Builder extension. In case you need other scenarios covered... the Model Builder GPU extension and VS 2022 aren't out yet. GPU should be available later today. VS 2022 will be available sometime between September 6th and September 15th.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by beccamc** [comment]
Sounds good. I'll keep this open for tracking until you're able to test.

**Comment by beccamc** [comment]
Hi! Were you able to test in November?

**Comment by GHoltmann** [comment]
Hi Becca!, we were not able to test any of it. I would like to run the tests from sctratch with the new released version. For the simplicity of the tests, I used a personal azure test account. Do you recommend using our corporate account for the testings?
    El martes, 15 de febrero de 2022 16:14:13 ART, Becca McHenry ***@***.***> escribió:  
 
 


Hi! Were you able to test in November?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by beccamc** [comment]
Using a personal azure account should be fine

**Comment by beccamc** [comment]
Any update here?

**Comment by beccamc** [comment]
Hi! Thanks for reporting this problem and testing out our Azure solution. I'm closing this issue. If you still have this problem (or any new problems) feel free to open another issue! Thanks again!

**Comment by GHoltmann** [comment]
Hi Becca, I really was unable to test further but our company is very interested in testing and implementing machine learning for video recognition. Thank a lot for your help! 
    El miércoles, 8 de junio de 2022 18:33:50 ART, Becca McHenry ***@***.***> escribió:  
 
 


Hi! Thanks for reporting this problem and testing out our Azure solution. I'm closing this issue. If you still have this problem (or any new problems) feel free to open another issue! Thanks again!
