### ISSUE TITLE
Accuracy and model not visible in Evaluate page after training

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1438]
I trained a classification model with yelp dataset:

![image](https://user-images.githubusercontent.com/10437687/117184732-e7730180-ad8d-11eb-91b0-ff70b2bed060.png)

Also I'm curious why it took row 2 of the dataset and not row 1?

**Comment by zewditu** [comment]
does your data set in row 1 has incomplete values?

**Comment by beccamc** [comment]
I think the first row is 

> Wow... Loved this place.	1

The problem might be with a header/no header? We might assume it has a header, and this dataset doesn't.

**Comment by vzhuqin** [comment]
This issue not occurs on main branch: 16.5.25.2127401
Set col1 as Label column, others are default settings:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0770ceae-b49a-45bb-b378-9c3c127e8d4d)
