### ISSUE TITLE
Evaluation page: can't parse `?` into unknown when input column type is single

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1439]
All columns are single type.
It's hard to say whether it's a bug or should be expected, but it's definitely blocking try-it-out story

![image](https://user-images.githubusercontent.com/16876986/117188376-daf0a800-ad91-11eb-9d31-5b7a104f4bf4.png)

**Comment by zewditu** [comment]
I think this is not a bug,  but we should communicate  exactly what happened there

**Comment by JakeRadMSFT** [comment]
We'll revisit our error story.
