### ISSUE TITLE
UI cleaning 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#144]
1.Number of previewed data should be described explicitly as top 10 rows are previewed
2. use Button for page navigation instead of links 
3. Bring rows & columns summary at the bottom of previewed table

![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/8bb641a6-b556-47aa-b94d-8d5c12e8b5da)

**Comment by rustd** [comment]
Waiting on customer feedback.
