### ISSUE TITLE
CodeGen error: sample data in Consoleapp.Program.cs can't handle `NaN` value.

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1440]
The correct code for `float.NaN` should be `float.NaN` instead of `NaNF`.
![image](https://user-images.githubusercontent.com/16876986/117188885-679b6600-ad92-11eb-9974-8e0f147a2249.png)

**Comment by LittleLittleCloud** [comment]
![image](https://user-images.githubusercontent.com/16876986/121081923-339cd180-c792-11eb-9e44-01d226347edb.png)

**Comment by LittleLittleCloud** [comment]
Not fixed

**Comment by LittleLittleCloud** [comment]
@zewditu Could you take a look

**Comment by vzhuqin** [comment]
Not repro this issue on main build: 16.7.0.2137701
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/587b0e18-ed47-41cb-ab01-a3adb722da9e)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/fb3ba463-cca7-41d3-8186-0805a3548960)
