### ISSUE TITLE
when using .mbconfig with git, train time gets reset

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1441]
1. I trained a regression model locally on my machine for 60 seconds and then saved and pushed changes to git
2. @luisquintanilla pulled the changes and opened the mbconfig - in the Train screen, the state of the last training run was saved and all there, but the train time in the textbox was set to 600 - we opened the .mbconfig json and saw the train time was still set to 60
3. Luis added a Web API from Consume step and saved everything
4. Luis used the ML.NET CLI to train the same .mbconfig and the train time was 600 seconds in the CLI - we opened the .mbconfig json again, and now the train time said 600 seconds

**Comment by beccamc** [comment]
I suspect that we're use the calculated value instead of the value from the training config. We should use the training config value. When the training time value is 0 (like on first initialize) then we should run the calculation.

**Comment by LittleLittleCloud** [comment]
LGTM
