### ISSUE TITLE
Regression model , issue with column with null value.

### ISSUE THREAD

**Issue by apacifico** [dotnet/machinelearning-modelbuilder#1443]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5.0.2115505
 - Visual Studio Version : 16.9.4

**Describe the bug**
We try to train a regression model and the system can't parse a column

Trial 0 encounter error with message: columns cannot be null or empty
Parameter name: columns
Trial 1 encounter error with message: columns cannot be null or empty
Parameter name: columns

**To Reproduce**
Use this file :  https://github.com/mdfarragher/DSC/blob/master/Regression/BikeDemandPrediction/bikedemand.csv

We try to predict the cnt column

**Expected behavior**
Able to manage situation where the dataset contains null values. Do we expect the file must be clean to be used by the model builder, means data wrangling must be done before using modelbuilder?

**Comment by beccamc** [comment]
@apacifico, thanks for reporting this problem. I've tried and cannot reproduce the error. Training succeeds for me. 

We may have fixed this bug, or it may be that the system used a different training type for me. Can you try to reproduce the problem, and send me the training log? Log is saved to the %temp% folder, and is available directly from the error dialog. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/324786b3-e2d0-47d7-8b29-0a5947659839)

**Comment by apacifico** [comment]
Hi Becca, I have opened a fresh visual studio and when I train the first time all is going well. But if I return on train action and ask  'Train Again' .
You have this error 
start nni training
|     Trainer                             RSquared Absolute-loss Squared-loss RMS-loss  Duration #Iteration      |
Trial 0 encounter error with message: columns cannot be null or empty
Parameter name: columns
Trial 1 encounter error with message: columns cannot be null or empty

So it seems when we start a new train , something is not re-initialized correctly. I imagine we can retrain the model without to close and reopen the solution or restart visual studio :)

**Comment by vzhuqin** [comment]
Not repro this issue on main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps:
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Value prediction scenario;
5. Input the file (download from: https://github.com/mdfarragher/DSC/blob/master/Regression/BikeDemandPrediction/bikedemand.csv) and select cnt column as Predict Label;
6. Click "Start training" on Train page;
7. After trained complete, click "Train again" to re-train;
8. Training complete without error.

![train again no error](https://user-images.githubusercontent.com/81727020/118425392-b2ef3600-b6fb-11eb-963d-22ff195c3acb.gif)

**Comment by beccamc** [comment]
It looks like this is fixed on our new build. It should be released in the next week or so. We can circle back and confirm the problem is fixed then. Thanks!

**Comment by apacifico** [comment]
Hello, I have access from visual studio to the preview : 16.5.02115505 of ML Builder, I see in your short video the version you are using is not the same. I confirm the first time the training is ok but I try retrain the issue I had last time is remaining with the same error.

![image](https://user-images.githubusercontent.com/824095/118770897-2622b480-b882-11eb-9a6b-0948c724512c.png)

![image](https://user-images.githubusercontent.com/824095/118771033-4fdbdb80-b882-11eb-858f-08b1385948da.png)
