### ISSUE TITLE
Code should be generated under updated model builder after renamed the mbconfig.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1446]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project with default name: **MLModel1.mbconfig**;
4. Rename the mbconfig to **Classification_MLModel1.mbconfig** for better recognition;
5. Select Text classification and Local (CPU);
6. Input the dataset , then click "Start training";
7. After trained complete, see error:
a. the generated code named start with **MLModel.**, the expected name should start with **Classification_MLModel1.**;
b. the generated code under the original model builder: **MLModel1.mbconfig**, the expected behavior should be under model builder: **Classification_MLModel1.mbconfig**;
c. should not have the  **MLModel1.mbconfig** model builder since it has been renamed.

**Screenshots**
![Genarated code location](https://user-images.githubusercontent.com/81727020/117534112-a7787c80-b022-11eb-9c42-296272e25d08.gif)

**Comment by vzhuqin** [comment]
Sorry, i forgot to verify the issue #1679 on this thread.
On Net472 on latest main 16.9.1.2155301, the generated files still cannot detect the name update of mbconfig , @zewditu could you please take a look?
![1446 repro.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2a5f9f91-8380-4809-946d-38f94c5d79ae)
If need to reopen the old issue or open new one to track, please let me know, thanks.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/c1c65d54-e034-4929-975f-50ae92029236)

**Comment by zewditu** [comment]
I reopen the original issue [1679](https://github.com/dotnet/machinelearning-modelbuilder/issues/1679)
