### ISSUE TITLE
Broken Link for "ML.NET Tutorial - Get started in 10 minutes"

### ISSUE THREAD

**Issue by Draghon** [dotnet/machinelearning-modelbuilder#1447]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): 
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
- Clear description of the problem: This part of the tutorial requires you download some sample data from an external site, https://archive.ics.uci.edu , however the site seems to be unreachable and has been for multiple days

**To Reproduce**
1. Go to the url 'https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data'
2. Click on the link 'Sentiment Labelled Sentences datasets' at the beginning of the article

**Expected behavior**
When clicking the link I expected to either be sent to a page with a zip file to download or to just start downloading said file

**Screenshots**
![image](https://user-images.githubusercontent.com/6148295/117585547-0e5c6b00-b0e1-11eb-8605-28ab5f931851.png)

**Additional context**

**Comment by beccamc** [comment]
It looks like the site is back up. Thanks for reporting this and let me know if you run into any other problems!
