### ISSUE TITLE
Sentiment Labelled Sentences datasets  can't be downloaded.

### ISSUE THREAD

**Issue by PeterSwinkels** [dotnet/machinelearning-modelbuilder#1448]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
It looks like the site is back up. Thanks for reporting this and let me know if you run into any other problems!
