### ISSUE TITLE
Time to train is not matched with .mbconfig file after reopen.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1451]
**System Information (please complete the following information):**
 - Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

**Main branch:** 
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

**Date Set:**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**

1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Recommendation scenario;
5. Select Local (CPU) environment;
6. Add data and set Sentiment column as Label;
7. Navigate to Train page: set Time to train (seconds): **30** and click "Start training" button;
8. Save the model builder after training complete;
9. Close and reopen the model builder;
10. Navigate to Train page, see error: Time to train (seconds) shows **10**, which is not matched with .mbconfig file.

**Expected behavior**
Time to train should be matched with .mbconfig file after reopen.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/117779932-b86afd00-b271-11eb-9904-b7500901f00b.png)

**Comment by beccamc** [comment]
This is a duplicate https://github.com/dotnet/machinelearning-modelbuilder/issues/1441
