### ISSUE TITLE
Confusing message at the end of the step "Generate code"

### ISSUE THREAD

**Issue by PeterSwinkels** [dotnet/machinelearning-modelbuilder#1452]
At the end of the step "Generate Code" I end up in the "Next Steps" tab in Visual Studio, I can choose to deploy model or to improve it. In both cases I get directed to a website. For the first option a webpage about how to deploy the sentiment predictor is opened regardless of the scenario. If I try to close the tab I get a dialog asking me whether I want to cancel my Model Builder session. Since it doesn't so much seems to cancel it but rather finish it this is  a rather confusing question. Also, it's unclear what is supposed to be done with all the generated code. The automatically generated comments in the code are mostly unhelpful. Also it would be nice if Machine Learning support was added for Visual Basic. Personally I can work with CS if I have to but prefer not to.

**Comment by beccamc** [comment]
@briacht please take a look at the above feedback. Thanks!

**Comment by briacht** [comment]
Hey @PeterSwinkels thanks for the feedback!

We actually have made some updates around these issues in our Preview release which you can sign up for here and get instructions on how to download: https://forms.office.com/r/A6yfGTSV2W

Would love to get your feedback on our changes here and see if this helps address the issues you brought up.

We will also look into updating our code comments to make them more helpful - can you give some examples of comments that you found unhelpful and what you might expect to see there instead?

**Comment by PeterSwinkels** [comment]
Hello and thank you for the quick reply.

I created another test project and I will rephrase my earlier statement about the comments, they aren't so much unhelpful as rather sparse in the information they provided. For example:

// This file was auto-generated by ML.NET Model Builder.

The above is an overly generic statement. I believe the comment should include information as to what purpose the file serves.  An explanation as to why a second project was generated and what the developer should do to integrate it with his project could also help. As it stands I am left with an extra project added to my solution and no idea what to do with it. Copy pasting the auto-generated Program.cs code which appears to demonstrate how to call the  image classifier (which is the scenario I chose in this particular case) results in an error when trying to run the code. The resulting output is:

================================================================================================================================================================
Unhandled Exception: System.TypeInitializationException: The type initializer for 'ConsoleApp1ML.Model.ConsumeModel' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at ConsoleApp1ML.Model.ConsumeModel..cctor()
   --- End of inner exception stack trace ---
   at ConsoleApp1ML.Model.ConsumeModel.Predict(ModelInput input)
   at ConsoleApp1ML.ConsoleApp.Program.Main(String[] args) in D:\Other\Example For Feedback To Microsoft\ConsoleApp1\ConsoleApp1\Program.cs:line 19
Press any key to continue . . .
================================================================================================================================================================

Also, why can't the developer select the auto-generated project as a startup- object? The auto-generated Program.cs does contain a Main procedure.

Peter Swinkels

________________________________

**Comment by beccamc** [comment]
Thanks for the feedback! The code files generated were updated in version 16.7.3. Take a look and if it doesn't help let me know. Please feel free to file additional issues, we appreciate your feedback!
