### ISSUE TITLE
ML.NET_Tutorial_Solution Explorer and select Add > Machine Learning(Missing)

### ISSUE THREAD

**Issue by bcramer48** [dotnet/machinelearning-modelbuilder#1455]
****System** Information (please complete the following information):**
 - Model Builder or CLI Version: Version 
 - Visual Studio Version (if applicable):2019- 16.9.5

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):ist pg. 
- Clear description of the problem:Solution Explorer and select Add > Machine Learning(Missing) 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

![ML_NET](https://user-images.githubusercontent.com/25613951/118027326-a55e3880-b316-11eb-91bc-daf7334389e2.png)

**Comment by beccamc** [comment]
@bcramer48 Sorry you ran into this problem and thanks for reporting. Can you check if the Model Builder Preview is enabled?

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/83022219-7814-4f3d-8d6a-1c62ee41b739)

If it is, can you check if the extension is installed via the extension manager in VS? (Extensions -> Manage Extensions -> Installed) 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/49661712-f85c-4ca6-9142-535992d4c5d4)

**Comment by bcramer48** [comment]
Hi Becca McHenry
Thank you for your reply.The Build Model (Preview) was not installed, but
it is now. The 'Machine Learning' is still missing.
See bellow
Thank you
[image: image.png]



Am Do., 13. Mai 2021 um 09:33 Uhr schrieb Becca McHenry <
***@***.***>:

**Comment by beccamc** [comment]
@bcramer48 Thanks for the response. Unfortunately I can't see the screenshot. Can you open the issue and upload directly? Thanks!

**Comment by bcramer48** [comment]
Hi Becca, as per your request, 
![image](https://user-images.githubusercontent.com/25613951/118559149-623c0500-b71c-11eb-888b-b51aeda3a21f.png)

**Comment by JakeRadMSFT** [comment]
Hello!
What type of project are you right clicking on?

**Comment by bcramer48** [comment]
I am starting the tutorial on "ML.NET Tutorial - Get started in 10 minutes" :Project  myMLApp.

**Comment by bcramer48** [comment]
![image](https://user-images.githubusercontent.com/25613951/118855857-21163300-b88b-11eb-8a38-43b8d9c6c870.png)

**Comment by JakeRadMSFT** [comment]
It isn't supported for VB projects at this time! We will consider adding it for VB in the future - we haven't investigated what it would take to support VB projects.

**Comment by JakeRadMSFT** [comment]
Resolving for now! But feel free to re-open if you hit anymore issues adding to projects! We already have an issue tracking VB here: 

https://github.com/dotnet/machinelearning-modelbuilder/issues/34

**Comment by bcramer48** [comment]
Hi, thank for your reply.  Just for my understanding. You mean that VB ist not supported by Git-Hub assistance? In ML.NET I  clicked "I run into an issue", clicking it I get "Report an Issue"., which took me to Git-Hub:  " dotnet /machinelearning-modelbuilder ". 
Question: Do you have idea where I can get assistance?
Thank you
