### ISSUE TITLE
Rentrancy fail after clone a repository to different virtual machine.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1456]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801(main)
- Microsoft Visual Studio Enterprise 2019: 16.9.5
- .Net: 5.0.202

**To Reproduce**
1. Trained model complete;
2. Save all files;
3. Click "Create a Git repository…" from "Git";
4. Sign in my GitHub account and click "Create and Push" button;
5. Open Visual Studio on another VM;
6. Click "Clone a repository" on Get started;
7. Enter the Repository location and the Path;
8. Click "Clone" button;
9. Open the model builder, see error: 
 a. Local (CPU)>File type:
![Recommendation Git+Rentrancy+File Fail](https://user-images.githubusercontent.com/81727020/118466059-15b0f380-b735-11eb-8b3c-009e23ace14a.gif)
 b. Local (CPU)>SQL Server type:
![Recommendation Git+Rentrancy+SQL Fail](https://user-images.githubusercontent.com/81727020/118466073-1a75a780-b735-11eb-87a0-468217a2d0f0.gif)
  c. Image Classification (Local CPU & Azure)
![Image git rentrancy fail](https://user-images.githubusercontent.com/81727020/118470487-4eeb6280-b739-11eb-80ae-7c4f513c9c80.gif)

**Expected behavior**
Rentrancy successful after checked out to different virtual machine.

**Additional context**
1. Find this issue on scenarios: Text classification, Value prediction, Image Classification, Recommendation.
2. This issue not occurs when checking in and checking out git repo from the same VM.

**Comment by vzhuqin** [comment]
This issue still occurs on main branch:16.5.25.2127102 for all scenarios.

**Comment by vzhuqin** [comment]
Test on main branch: 16.5.25.2130702 and referring the PR:https://github.com/dotnet/machinelearning-tools/pull/1097
**Scenario:** 
- Image classification 
- Text Classification 
- Value Prediction

On Consume page, do not have Code snippet and cannot add project templates. @beccamc Could you help to take a look?
![image](https://user-images.githubusercontent.com/81727020/121167943-01b86780-c885-11eb-89c5-23f1a2947c95.png)

**Comment by vzhuqin** [comment]
Object detection scenario test result on main branch: 16.5.25.2130702
No display the Data Preview and other tab under Data are disabled.
![image](https://user-images.githubusercontent.com/81727020/121283713-2c023780-c90e-11eb-86e8-d48437ace2ef.png)

**Comment by beccamc** [comment]
@vzhuqin Can we close this in favor of the new relative path behavior implemented by LittleLittleCloud?

**Comment by beccamc** [comment]
Closing this as relative path has been implemented and is being tested in another issue.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch 16.13.10.2247001.
