### ISSUE TITLE
Object detection model builder can't be pushed successfully to git repository.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1459]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.5
- .Net: 5.0.202

**Main Branch:** 
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

**Data Set:**
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#create-a-new-vott-project

**To Reproduce**
1. Train the Object detection model builder complete;
2. Save all files;
3. Click "Create a Git repository…" from "Git";
4. Sign in my GitHub account and click "Create and Push" button;
4. See error: wasn't successfully pushed.
![image](https://user-images.githubusercontent.com/81727020/118580993-71c25900-b7c3-11eb-98e0-a9d4deee4fb3.png)

**Expected behavior**
Object detection model builder can be created and pushed successfully to git repositories.

**Additional context**
1. Tried to push with git commend, show error: large files detected.
![image](https://user-images.githubusercontent.com/81727020/118581227-da113a80-b7c3-11eb-8aa8-b0a0cf3df0c1.png)
2. Two large files:
![image](https://user-images.githubusercontent.com/81727020/118581369-180e5e80-b7c4-11eb-9601-b61f2818c8f9.png)

**Comment by JakeRadMSFT** [comment]
git lfs install
git lfs track "*.zip"
git lfs track "*.onnx"
git add .gitattributes
git commit -m "add git attributes"


git lfs migrate import --include="*.zip" --everything
git lfs migrate import --include="*.onnx" --everything
git push --force

**Comment by vzhuqin** [comment]
Can be pushed successfully via git-lfs.
Download and install from: https://git-lfs.github.com/, then run above command.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0f7bbf6a-4aea-4c2f-a176-da2648fad700)
