### ISSUE TITLE
Classification works but when I try regresion I get error "modelOutput does not contain definition for 'Prediction'"

### ISSUE THREAD

**Issue by seeeme** [dotnet/machinelearning-modelbuilder#146]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/consume
Operating System: windows

This example works, but when I try using regression on same dataset I get error stated above. I am not sure how to approach this problem. I hope atteched image helps you with understanding my problem.
![Error](https://user-images.githubusercontent.com/20108110/60540286-15f5a080-9d0f-11e9-9f18-028912e6d13a.PNG)

**Comment by rustd** [comment]
@seeeme please provide step-step instructions on how to reproduce this error and the sample dataset as well.

**Comment by seeeme** [comment]
Hi,
thank you for trying to help me out.
I tried to use thi "tool" with this GUI interface described here:
https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/evaluate

I managed to make classification example work. I posted video here:
https://www.youtube.com/watch?v=ZB8CSkjQguE&feature=youtu.be

But when I try to make basically same example with using regession on another atribute, I cant test created model, because class ModelOutput does have atribute prediction.

failed attempt video on this link:
https://www.youtube.com/watch?v=eRrP9z6b_VM&feature=youtu.be

I hoped that I could use regression predictor with same code in myMLApp\Program.cs, as it was done with classification predictor.

How ModelOutput class looks like in after creating classification model can be seen on attached image.
![image](https://user-images.githubusercontent.com/20108110/60916396-81e78400-a28e-11e9-84e2-74cc85004d3d.png)

**Comment by rustd** [comment]
@JakeRadMSFT can you please look into this or reassign?

**Comment by seeeme** [comment]
I just want to know if someone can confirm that regression works in some examples when using 
automatic model builder from link bellow and presented on videos in comments above. I am not sure if it is problem with my machine or with software.

https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-model-builder

**Comment by seeeme** [comment]
OK, my bad. "Model output" class has two atributes: "Score" and "Prediction". I was only looking at "Prediction", because it gave me prediction on classification problem. It turns out, I should look at "Score" when solving regression problem.
