### ISSUE TITLE
Run WebAPI project fail: 500 internal server error in power shell.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1460]
**System Information (please complete the following information):**
 - Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.5
- .Net: 5.0.202

**Main Branch:** 
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

**Data Set:**
Value:
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv
Recommendation:
https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv
Classification:
https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Go through until training complete;
5. Added Web API project on Consume page;
6. Got URL (https://localhost:44326) was launched on F5 in visual studio;
7. Got the ModelInput from Consume page>Code snippet;
//Load sample data
var sampleData = new ValueLocalFile_MLModel1.ModelInput()
{
    Vendor_id = @"CMT",
    Rate_code = 1F,
    Passenger_count = 1F,
    Trip_time_in_secs = 474F,
    Trip_distance = 1.5F,
    Payment_type = @"CRD",
};
 
//Load model and predict output
var result = ValueLocalFile_MLModel1.Predict(sampleData);

8. Update the URL and Body content of the command: 
Invoke-RestMethod "https://localhost:44326/predict" -Method Post -Body (@{Vendor_id="CMT"; Rate_code="1F"; Passenger_count="1F"; Trip_time_in_secs="474F"; Trip_distance="1.5F"; Payment_typ="CRD"} | ConvertTo-Json) -ContentType "application/json"

9. Leave it running in VS and the browser open ;
10. Run above commend in power shell.
11. See error: The remote server returned an error: (500) Internal Server Error.
![image](https://user-images.githubusercontent.com/81727020/118582802-90761f00-b7c6-11eb-9359-fe19903610d1.png)

**Expected behavior**
WebAPI project can be run successfully in power shell.

**Additional context**
Run successfully for scenarios: 
Image classification(https://testpass.blob.core.windows.net/test-pass-data/weather.zip)
Object detection(https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#create-a-new-vott-project)
Text classification(test matrix: https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv)

**Comment by JakeRadMSFT** [comment]
@vzhuqin can you try this again without "F" in the values?

**Comment by vzhuqin** [comment]
Hi @JakeRadMSFT, I tried on Value prediction + File type, find it still occurs on main branch: 16.5.25.2127401

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9892b465-5328-4571-a2cb-1988f9e4238b)

**Comment by zewditu** [comment]
@vzhuqin thanks ! I will look it

**Comment by zewditu** [comment]
The cause of the sisses is the column names in the sample dataset are start with uppercase letters, use the same column name found in the dataset works ,![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/cfe57fb7-f4f2-4e51-86c4-3432b39da6b5)

**Comment by zewditu** [comment]
@briacht @romalpani @JakeRadMSFT  any thought on how to tell the webApi user where they found a sample data to evaluate the model?

**Comment by vzhuqin** [comment]
**Main branch with ML.Net Model Builder (Preview): 16.5.25.2127401:**

Thanks @zewditu, value prediction WebAPI project can be ran by using the same columns name as in the dataset.

But could you help to take a look other two scenarios? I try to run them use the same columns name as in the datasets, but still have 500 internal server error.

- Recommendation (https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv)

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/c6a9118b-713c-4615-acac-2b23d506deef)

- Text Classification (https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt)
 ![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a2a7062d-9f36-4a19-bb0f-2f2c1f1327ad)

**Comment by zewditu** [comment]
@vzhuqin thanks for testing other scenarios, yes you are correct it fails but  the issues is with datasets having column names that start with uppercase letters when I change the column names  in https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt into id, area, title, and description it works 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/59b3930d-a74a-4b26-b38d-02b0eb4067a8).

Does it seem that there is an issue in the data preprocessing step, @LittleLittleCloud , @beccamc , @JakeRadMSFT  any thought on this?

**Comment by zewditu** [comment]
## Recommendation 
yes it fails

**Comment by zewditu** [comment]
@vscuqin,   @LittleLittleCloud  helped me to figure out what is the cause, we need to removed double quotations from a single type column's value, you can confirm column types on the dataset in advanced options in the data tab. We can use the syntax in the code snippet, but remove "F" from single types 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/8a71e6e5-0a58-4ff5-b144-c0ead0ceb6d7)
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/2ae0d338-d8f1-4074-9b0b-6ddf021a4fb3)


## Note: 
I tested all  text scenarios it works

**Comment by vzhuqin** [comment]
Thanks @zewditu and @LittleLittleCloud , I have tried it, they can be run successfully.
Value prediction:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/71a6c211-966a-4e72-8c76-a7cb1beda31f)
Recommendation :
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7d069342-9390-4cbd-a17b-590a21d846aa)
Text classification:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4e514369-9c53-4377-ba55-b58d63115f86)
