### ISSUE TITLE
Object Detection bounding box is still the same

### ISSUE THREAD

**Issue by arafattehsin** [dotnet/machinelearning-modelbuilder#1462]
Hi Team! 

Around 3 weeks ago, I opened up an [issue](https://github.com/dotnet/machinelearning/issues/5772#issue-869558693) regarding the bounding box coordinates. I trained my model yesterday using the latest [Model Builder Preview build](https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml) but I can see that the coordinates are the same as defined in that issue.

I'd definitely appreciate any pointers if I am making any mistake in drawing those bounding boxes. 

Cheers
Arafat

**Comment by LittleLittleCloud** [comment]
Sorry for the delay. I'll help you on this, let's continue on original thread though
