### ISSUE TITLE
Wrong log file opened from error dialog

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1463]
Log file is empty, even though I've done training 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/d211dce2-063c-4cfa-999d-a3e88ed118d7)

**Comment by LittleLittleCloud** [comment]
Hi @beccamc 

I'm not able to reproduce this error, Is it possible that you are not looking at the latest log file? Model builder will create a new log file when every time you open a new instance but the output window won't be cleaned. So if you re-open a mbconfig file, its log will be written to a new place.

**Comment by beccamc** [comment]
Looked closer, the issue is we are opening the wrong log file from the error window. Below is the log opened from the error window. It's an older file from 12:00

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/e3db1f95-1a16-41f5-bb61-ce5b2fab8529)

Here is the temp folder. We have a correct log `5f7e `(started at 12:15, last updated at 12:17, the time of the experiment)
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/5ee7adcf-1999-4cc0-ba5b-82a84656de59)

**Comment by vzhuqin** [comment]
@LittleLittleCloud , this issue still appears on main build: 16.6.1.2132901, could you help to take a look?

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/89918461-1575-4000-bbb0-59fe24eef42b)

**Comment by LittleLittleCloud** [comment]
KK

**Comment by vzhuqin** [comment]
This issue not occurs on the latest main build: 16.7.0.2137001
Now the log file is named based on the model builder name, it's easy to find and compare, and the file is not empty for all model builders.
![1463 fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9fc51553-0b66-4cb0-b192-71939b67834e)
