### ISSUE TITLE
Wrong decimal separator in the generated Model.training.cs file

### ISSUE THREAD

**Issue by flokie** [dotnet/machinelearning-modelbuilder#1475]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5.0.2115505
 - Visual Studio Version: 16.10.0 preview 4

**Describe the bug**
- Clear description of the problem: It's using "," as decimal separator -probably because my regional settings?- while generating Model.training.cs file as you can see in the screenshot. Everything works fine after change it to "." as it's supposed to be.

**Screenshots**
<img width="814" alt="Screen Shot 2021-05-21 at 20 05 22" src="https://user-images.githubusercontent.com/28707189/119174322-1e753280-ba71-11eb-9fee-27ddadff8720.png">

**Comment by LittleLittleCloud** [comment]
Thanks for the feedback.

**Comment by vzhuqin** [comment]
This issue not occurs on main branch: 16.5.25.2127801
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/27fddb84-dd53-494e-8cdf-96405e7299e5)
