### ISSUE TITLE
"zsh: command not found: mlnet"

### ISSUE THREAD

**Issue by sameer-ali13** [dotnet/machinelearning-modelbuilder#1476]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: macOS Big Slur

When I run: mlnet classification --dataset "yelp_labelled.txt" --has-header false --label-col 1 --train-time 20, 

the terminal outputs "zsh: command not found: mlnet". I am not sure what to do. I have manually added ~/.dotnet/tools to my PATH as well

**Comment by LittleLittleCloud** [comment]
#1295

**Comment by LittleLittleCloud** [comment]
Hello @sameer-ali13 

Can I take a look at your $Path variable. And how do you add `~/.dotnet/tools` to your $Path variable? Is it just for current session or in .zprofile?

**Comment by sameer-ali13** [comment]
> Hello @sameer-ali13
> 
> Can I take a look at your $Path variable. And how do you add `~/.dotnet/tools` to your $Path variable? Is it just for current session or in .zprofile?

Hi! Thank you so much for the resources, attached below is what my $Path variable looks like. I used sudo nano to manually add it in. 

<img width="681" alt="Screen Shot 2021-05-26 at 3 22 01 PM" src="https://user-images.githubusercontent.com/65135205/119719160-72e42d80-be36-11eb-8a0d-68c3e890d6a6.png">

**Comment by sameer-ali13** [comment]
> Hello @sameer-ali13
> 
> Can I take a look at your $Path variable. And how do you add `~/.dotnet/tools` to your $Path variable? Is it just for current session or in .zprofile?

> Hello @sameer-ali13
> 
> Can I take a look at your $Path variable. And how do you add `~/.dotnet/tools` to your $Path variable? Is it just for current session or in .zprofile?

Hi! Thank you so much for the resources, attached below is what my $Path variable looks like. I used sudo nano to manually add it in. 

<img width="681" alt="Screen Shot 2021-05-26 at 3 22 01 PM" src="https://user-images.githubusercontent.com/65135205/119719160-72e42d80-be36-11eb-8a0d-68c3e890d6a6.png">

**Comment by LittleLittleCloud** [comment]
LGTM, can you go check your ~/.dotnet/tools folder and make sure mlnet is there?

**Comment by sameer-ali13** [comment]
> @sameer-ali13
> LGTM, can you go check your ~/.dotnet/tools folder and make sure mlnet is there?

How would I find this folder? Sorry I am kind of new at this

**Comment by sameer-ali13** [comment]
> @sameer-ali13
> LGTM, can you go check your ~/.dotnet/tools folder and make sure mlnet is there?

Hello, so I realized I was editing the bash rc file while I needed to be editing the zsrch file (which Mac uses now), and so I added this, however it is still not working. 
<img width="570" alt="Screen Shot 2021-05-27 at 1 01 13 PM" src="https://user-images.githubusercontent.com/65135205/119867254-b056c280-beeb-11eb-8175-070489fd2d31.png">

**Comment by LittleLittleCloud** [comment]
Hi @sameer-ali13 
Sorry for the late reply
> How would I find this folder? Sorry I am kind of new at this
Simply run `ls /Users/sameerali/.dotnet/tools` command and check if `mlnet ` is in the output. If not, it indicates that mlnet is not correctly installed

> Hello, so I realized I was editing the bash rc file while I needed to be editing the zsrch file (which Mac uses now), and so I added this, however it is still not working.

It looks good to me. If it doesn't work, I would replace `~` with `/Users/sameerali` and try again.
`export PATH="$PATH:/Users/sameerali/.dotnet/tools"`

And make sure you reload your .zsrch / .zprofile every time you added it by running
`source ~/.zsrch` or `source ~/.zprofile`

**Comment by LittleLittleCloud** [comment]
Close due to no response and @sameer-ali13 feel free to reopen it if necessary
