### ISSUE TITLE
The dirty status should not be displayed when opening model builder without making any changes.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1483]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.5.25.2127801
- Microsoft Visual Studio Enterprise 2019: 16.10.0
- .Net: 5.0.203

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Go through to training complete;
5. Save and close the model builder;
6. Open the model builder again and no make any changes;
7. See error: find the dirty status displays after 1-2s.

**Expected behavior**
If not do any changes for the model builder, should not have the dirty status.

**Screenshots**
![ditry status even if unchange](https://user-images.githubusercontent.com/81727020/119944547-fdf42d80-bfc6-11eb-8e31-7cc29429cbf9.gif)

**Additional context**
It also has dirty status when first opening model builder, not sure whether is an issue. 
![image](https://user-images.githubusercontent.com/81727020/119945146-a99d7d80-bfc7-11eb-9463-c9ff6d05388b.png)

**Comment by zewditu** [comment]
The reason for being dirty at the beginning is for non-mbconfig properties it set to be dirty like tab changing.
However, the Mb.config file is only dirty for the following property changes such as scenario, environment, Datasource, and training time.
But the data set path to change, column properties change, run history change does not notify

**Comment by luisquintanilla** [comment]
This isssue is not a priority at the moment. As we hear feedback from users, we can revisit.
