### ISSUE TITLE
It should display the Copy option if right click on the blank area of Code snippet.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1484]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.5.25.2127801
- Microsoft Visual Studio Enterprise 2019: 16.10.0
- .Net: 5.0.203

**Describe the bug**
**_Not sure if this is an issue, please help to confirm._**
The area of Code snippet is similar with .txt file, after selecting the text, should display copy option even if right click on the blanks area.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Go through to training complete;
5. Navigate to Consume page, right click to copy the code after selected the code snippet;
6. See error: no response if click on a blank area.

**Expected behavior**
Display the Copy option even if right click on the blank area of Code snippet.

**Screenshots**
![Copy issue](https://user-images.githubusercontent.com/81727020/119948911-e8cdcd80-bfcb-11eb-979b-e12c180042a8.gif)

**Comment by beccamc** [comment]
Jake thinks this is a problem with our Editable/Readonly state (e.g. the wrong one is true)

**Comment by vzhuqin** [comment]
Hi @LittleLittleCloud @zewditu , please see below Gif, after right click on the blank area, the selected state is lost, then click "Copy", the selected state is back, is this expected?
- ML.Net Model Builder: 16.7.2.2142301 (Main Branch)
![1484_issue.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/95526d1c-e566-4f87-8851-0a8f1c537fe6)

**Comment by zewditu** [comment]
The  fix did by the context menu non- focusable regress another accessibility issues (the user is not able to move with in context option using the keyboard)
And it is a  known issue microsoft/microsoft-ui-xaml#1801.
