### ISSUE TITLE
Issue at mlnet classification ... step

### ISSUE THREAD

**Issue by TheTeub** [dotnet/machinelearning-modelbuilder#1485]
**System Information (please complete the following information):**
 - Model Builder or CLI Version:  .NET Core 3.1 SDK (Ubuntu 16.04 LTS) mlnet 16.2.0
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: I have done previous steps without any issues. Then I have copied the command :
dav@HAL:~/myMLApp$ mlnet classification --dataset "yelp_labelled.txt" --has-header false --label-col 1 --train-time 20
2021/05/28 14:27:19 [cO] Starting MLDonkey 3.1.5 ... 
2021/05/28 14:27:19 [cO] Language EN, locale UTF-8, ulimit for open files 1024
2021/05/28 14:27:19 [cO] raised ulimit for open files from 1024 to 1048576
2021/05/28 14:27:19 [cO] MLDonkey is working in /home/dav/.mldonkey
2021/05/28 14:27:19 [Gettext] Loading language resource mlnet_strings.en_US.UTF-8
2021/05/28 14:27:19 [cO] loaded language resource file
2021/05/28 14:27:19 [DNS] Resolving [HAL] ...
2021/05/28 14:27:19 [DNS] Resolving [www.mldonkey.org] ...

Attention!
This core is running with glibc 2.23 but it was compiled with glibc 2.21.
This can lead to unexpected behaviour. Consider compiling the core yourself
or getting a binary compiled with glibc 2.21.

2021/05/28 14:27:19 [cO] Logging in /home/dav/.mldonkey/mlnet.log
mlnet: unknown option '--dataset'.
.... lot of lines then to explain the different arguments or options

I need to understand what to do ? re-compile with proper compiler (I don't know how to do!) or anything else ?
(I have tried to install the mlnet 16.1.1 as shown in the screen of previous steps, but I got exactly same issue)
Cheers,
David.

**Comment by LittleLittleCloud** [comment]
Can we have the complete log? It looks like the mlnet is installed and works except that it failed to parse options. So you might not need re-compile the core.

**Comment by TheTeub** [comment]
Hello, I gave up to make it on Linux.
I have switched to Windows 10 Version.
Goddbye

**Comment by beccamc** [comment]
Sorry you ran into this problem on Linux. If you go back to it, please reopen the issue with the log file. 

Let us know if you run into any more problems! Thanks for reporting.
