### ISSUE TITLE
Reword "Sample projects" in Consume step

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1486]
![image](https://user-images.githubusercontent.com/10437687/120036177-93d28d00-bfb4-11eb-93ba-9b1b82cfb6bf.png)

Let's try "Project templates"

**Comment by vzhuqin** [comment]
Have been reworded to "Project templates" on main branch: 16.5.25.2130701
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a120cc4f-2e14-400c-bb6a-598c0817df96)
