### ISSUE TITLE
The output did not like expected

### ISSUE THREAD

**Issue by AzmanMahyuddin** [dotnet/machinelearning-modelbuilder#1488]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable): 16.10.0

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): I ran into an issue in "consume your model" page (https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume)
- Clear description of the problem:
- The expected of the result should be like this ::
-
![output expected](https://user-images.githubusercontent.com/85119356/120207747-62311e80-c25f-11eb-805f-2d640f64de92.png)

However I receive the output "Please press any key to continue..." only in the cmd. When I press any key the cmd then will pop out. Please refer to the attachment below ::

![Problem ML](https://user-images.githubusercontent.com/85119356/120207901-8ab91880-c25f-11eb-8502-7e3815636241.png)

I already following the steps accordingly. Please help me. Thank you!

**Comment by beccamc** [comment]
@AzmanMahyuddin sorry you ran into this problem. What happens if you debug and put a breakpoint on line 17? Do you get a result?

**Comment by AzmanMahyuddin** [comment]
I get this. My cmd only open in a split second and then it closes automatically.
![problem ML 2](https://user-images.githubusercontent.com/85119356/120732502-0218d180-c518-11eb-9fd5-33a5c7b066f6.png)

**Comment by beccamc** [comment]
I know it's simple, but can you close VS and reopen this project? Usually this is a problem with VS, as it isn't even hitting our code during debugging. 

Other customers have fixed by restarting VS, or reinstalling.

**Comment by beccamc** [comment]
Any update here?

**Comment by beccamc** [comment]
Did restarting VS help? Or creating a new console application and seeing if it runs?

**Comment by beccamc** [comment]
Closing this as it seems to be a problem with VS. Please ping me if it's still happening. Thanks!
