### ISSUE TITLE
It is recommended to add a colon to separate the tag and value of the prediction result.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1489]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.5.24.2125802
- Microsoft Visual Studio Enterprise 2019: 16.9.6
- .Net: 5.0.203

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select **Image classification** scenario to train complete;
5. Add ConsoleApp project and run it;
6. See: There is no separator between the label and value of one of the prediction results. 

**Expected behavior**
It is recommended to add a colon to separate the tag and value like other prediction results.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/120443692-7d17a600-c3b9-11eb-8cc9-8f21a459d829.png)
![image](https://user-images.githubusercontent.com/81727020/120443132-ec40ca80-c3b8-11eb-8dce-01219abd7193.png)

**Comment by beccamc** [comment]
@LittleLittleCloud Were you just in this space and willing to make a quick fix?

**Comment by vzhuqin** [comment]
This issue isn't repro on main build: 16.6.3.2136604
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3dc71b65-70c5-40ef-b279-01e28c58cf1b)
