### ISSUE TITLE
Inconsistency in context menu language and 'add new item' dialog description

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#1497]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5.25.2130702
 - Visual Studio Version: 16.11 Preview 1

**Describe the bug**
- On which step of the process did you run into an issue: Right-click on the project in solution explorer to add ML model.
- Clear description of the problem:

Issue: The context menu option for adding machine learning to a project reads "Add > Machine Learning". 
Solution: As per designs, as shown in Figma here, the language should read "Add > Machine Learning Model..."

https://www.figma.com/file/qFoQ4iC27jpNZb7CCuo7Hj/?node-id=295%3A94

Issue: In the 'Add new item' dialog, the description reads "Add model builder to your web project". 
Solution: @briacht can we have a one-liner that is better than the statement above? I can work with you on that.

**Screenshots**
![image](https://user-images.githubusercontent.com/48927690/121081982-47483800-c792-11eb-9376-7eabd620b352.png)
![image](https://user-images.githubusercontent.com/48927690/121082104-73fc4f80-c792-11eb-9224-cb45aed2b9b0.png)

**Additional context**

**Comment by beccamc** [comment]
I've fixed the first issue

![image](https://user-images.githubusercontent.com/9122518/128406686-647a6e26-9b9b-4c97-b911-81c718ffc78f.png)

**Comment by beccamc** [comment]
If you want a change to the "Add model builder to your web project" update in the next week or so. Otherwise this is going on the chopping block :relaxed:

**Comment by briacht** [comment]
Hi yes! We can definitely add a better description here...

Maybe:

Use Model Builder to train an ML.NET model and add machine learning to your project.

@romalpani

**Comment by romalpani** [comment]
That sounds good, with one minor modification - based on how other files have descriptions - they all avoid the use of the action word "_use_" and keep it more like a definition.

So, here's my suggestion:

Customer clicks on the list item...
"Machine Learning Model (ML.NET)"

Description...
"A Model Builder that helps train a machine learning model using ML.NET."

Thoughts @briacht ?
