### ISSUE TITLE
Dev17 - Environment page not presented

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1498]
![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/d7578902-acdf-4ef1-b2db-81249a160300)

**Comment by LittleLittleCloud** [comment]
It amazingly recovered after a restart.. Maybe it's just something with Dev17

**Comment by beccamc** [comment]
I'm going to close this, but let's keep an eye out for it happening again. Thanks XiaoYun!
