### ISSUE TITLE
Data page: Browse input field has text misaligned

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#1499]
**System Information (please complete the following information):**
 - Model Builder Version: 16.5.25.2130702
 - Visual Studio Version

**Describe the bug**
The text inside the browse input field should be centered. It seems off to the top a little bit.

**To Reproduce**
1. Go to TextClassification
2. Click on Local CPU
3. Browse a file and see the input field populate with path.

**Screenshots**
![image](https://user-images.githubusercontent.com/48927690/121083593-7bbcf380-c794-11eb-87c0-de86a99882f9.png)

**Additional context**

**Comment by vzhuqin** [comment]
Verified on latest main build: 16.7.2.2140901
Browse input field has text center-aligned.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7ef5d750-21d6-4d27-976a-9c5430b86c86)
But can repro this issue on Data page of Image classification and Object detection scenarios, please take a look if need to adjust the alignment just like browse input field?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/48ad72bd-1334-4cd6-bc99-f53d28ac731b)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0d591f45-afee-40da-93da-69529482fd80)

**Comment by vzhuqin** [comment]
@romalpani  @beccamc  Any update on Image classification and Object detection scenarios?

**Comment by vzhuqin** [comment]
this issue has been fixed on latest main: 16.9.1.2155101
Image classification:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/f8bd2f23-8346-49a2-bf0b-4162645913a9)
Object detection:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4cc1cb2f-4e96-41a6-8a12-1e4aaebd294c)
