### ISSUE TITLE
Sometimes pop up Model Builder Error: Object reference not set to an instance of an object after clicked one scenario.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1502]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.5.25.2130702 (main branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.0
- .Net: 5.0.203

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select one scenario;
5. See error: Sometimes pop up Model Builder Error: Object reference not set to an instance of an object.

**Expected behavior**
No error prompt after clicked one scenario.

**Screenshots**
Screenshot:
![image](https://user-images.githubusercontent.com/81727020/121117922-871f2600-c84b-11eb-89bf-74e6eeac1f12.png)
GIF:
![Model builder Error2](https://user-images.githubusercontent.com/81727020/121119685-a8354600-c84e-11eb-9635-3abe74793b17.gif)

**Comment by LittleLittleCloud** [comment]
#1513

**Comment by vzhuqin** [comment]
this error also prompts when reopen the model builder or open advanced data option dialog, the occurrence frequency is about 1/5.
ML.Net Model Builder (Preview): 16.6.1.2131904 (Main Branch)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a9131883-841b-45c4-ba9c-7c4e8bf220fb)

**Comment by LittleLittleCloud** [comment]
#1513

**Comment by vzhuqin** [comment]
@beccamc  This issue also occurs on candidate build: 16.6.3.2136603

**Comment by beccamc** [comment]
Sorry for the confusion, candidate build 16.6.3.2136603 does not have this fix!

**Comment by LittleLittleCloud** [comment]
track in #1513
