### ISSUE TITLE
The ConsoleApp projects cannot be run if named the model builder with a space or hyphen (-).

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1503]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.5.25.2130702 (Main Build)
- Microsoft Visual Studio Enterprise 2019: 16.10.0
- .Net: 5.0.203

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Name the model builder with a space or hyphen (-);
5. Train the model complete;
6. Add the ConsoleApp project on Consume page;
7. Set the ConsoleApp project as startup project and click start debugging;
8. See error: pop up Microsoft Visual Studio dialog said: The debug executable ... debug profile does not exist.

**Expected behavior**
Can debug the consoleapp project successfully.
If have any requirements for the model builder name, recommend to prompt message to remind user when named.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/121281244-33bfdd00-c90a-11eb-8b6a-7c8bcb08f795.png)

**Additional context**
This issue not happen on old version: 16.5.25.2127802

**Comment by zewditu** [comment]
@vzhuqin ,  this issue is fixed in the latest main build. I think ML.Net Model Builder (Preview): 16.5.25.2130702 is not based on the latest main build.

**Comment by vzhuqin** [comment]
This issue has been fixed on main build: 16.5.25.2131501
Named the model builder with a space:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/190cdb1a-ebc8-4281-a6d6-be8b40c6c2df)
Named the model builder with hyphen (-):
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ba036ecc-e113-490e-a3fa-2207ec131882)

**Comment by vzhuqin** [comment]
@zewditu this issue happened again on latest main build: 16.6.1.2131904, could you help to take a look?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a8ec65cb-b0c0-4833-981e-0dd6c14939a5)

**Comment by zewditu** [comment]
@vzhuqin  the issue is fixed  for version  ![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/94acbce7-0095-4033-87a4-c8e9fe7af078)

![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/9937fb26-d421-4f13-badb-b64721cc3e49)

**Comment by vzhuqin** [comment]
Thanks, verified this issue was fixed on main build: 16.6.2.2135501
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a37ceefa-cea9-41c4-b670-177e1b9ceac8)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4fcc7407-3e7e-4891-bdde-46087902daab)

**Comment by vzhuqin** [comment]
@beccamc , meet this issue on Candidate build: 16.6.3.2136603, but not repro on main build: 16.6.3.2136604, please take a look.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4a71d02e-1959-4dd3-836f-cbbf15c1977c)

**Comment by beccamc** [comment]
Sorry for the confusion, candidate build 16.6.3.2136603 does not have this fix!
