### ISSUE TITLE
Ignore GUID columns

### ISSUE THREAD

**Issue by saroshwadia** [dotnet/machinelearning-modelbuilder#1504]
1] While using the Model Builder and using SQL as the Data source if I use a table that has a GUID (uniqueidentifier) Primary Key I get the following Error

![image](https://user-images.githubusercontent.com/21205744/121406123-0891b980-c91b-11eb-8031-f035d7bcec15.png)

2] When I choose Advanced data options and select "Ignore" for the Guid Columns it still seems to be still using that Guid column internally and get the same above Error.

![image](https://user-images.githubusercontent.com/21205744/121406539-7dfd8a00-c91b-11eb-906f-ad76bd38d4ce.png)

**Comment by JakeRadMSFT** [comment]
@saroshwadia we just released our new version -  Can you try it out there?

**Comment by saroshwadia** [comment]
Hi!

Is this a pre-release or GA, what is the version and is it on NuGet?

The one I'm using is "Microsoft.ML" Version="1.5.5"

Sarosh

**Comment by JakeRadMSFT** [comment]
The latest version of Model Builder on the VS Marketplace - 

https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by saroshwadia** [comment]
Hi!

Just updated the ML.NET Model Builder Extension "16.6.0.2130907"

Will give a try and let you know.

Thanks

Sarosh

**Comment by saroshwadia** [comment]
Hi!

Got it! 😊

Thanks

Sarosh

**Comment by saroshwadia** [comment]
Hi!

Gave it a try - still gives an error but continues the training.

I tried to exclude the Guid column in Advance data options setting but no luck.

***@***.***D75DE3.31386DA0]

Sarosh

**Comment by JakeRadMSFT** [comment]
@beccamc can you help look into this?

**Comment by beccamc** [comment]
There has been some discussion for this issue offline, I'll summarize here.

Problems:
1. Using SQL with a Primary Key guid columns causes error: `Bad type in ColumnTypeExtensions.NumberTypeFromType: System.Guid`
2. Ignoring this column still produces the error. 

It seems there is a limitation with ML.NET on using guids, they aren't listed in the supported types code [here](https://github.com/dotnet/machinelearning/blob/04dda55ab0902982b16309c8e151f13a53e9366d/src/Microsoft.ML.Core/Data/DataKind.cs#L293). I'll follow up with the ML.NET team on that. 

Regarding ignoring the column.  Even when columns are ignored, we still need to provide them to the database loader. Unfortunately this means you can't work around the invalid type problem by ignoring. 

At present the work arounds to this problem are:
- Delete the guid column
- Covert from uniqueidentifier type to nvarchar type
- Export data to delimited file where the guid can be read as a string

I'll follow up with the ML.NET team. Thanks for reporting this one!

**Comment by beccamc** [comment]
Status update. There are two things going on here... 

- GUID isn't a supported type by ML.NET - [issue](https://github.com/dotnet/machinelearning/issues/4583). This blocks us from being able to treat the uniqueidentifier as it's true type.
- There is a conversion bug in the new DataView extension methods that convert to a DataFrame. However, we are in the process of removing this from our code. I'll update after [this ](https://github.com/dotnet/machinelearning-tools/pull/1127)PR goes in.

**Comment by luisquintanilla** [comment]
Changing title. We don't need to enable training with GUIDs, however, we do need to honor / enforce "Ignore" selection in Advanced Data options.
