### ISSUE TITLE
Model Builder Error

### ISSUE THREAD

**Issue by sergiodelossantosjr** [dotnet/machinelearning-modelbuilder#1512]
**Model Builder Version**: 16.6.0.2130907
**Visual Studio Version**: Visual Studio 2019 Preview

**Bug description**
![image](https://user-images.githubusercontent.com/22256389/121797191-46f7e300-cc51-11eb-9072-b3c6af282400.png)

**Steps to Reproduce**
1. Choose SQL Server as data source
2. Then choose sql server table

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
@sergiodelossantosjr Sorry you ran into this issue, and thanks for reporting! Did you ignore any columns?

**Comment by beccamc** [comment]
@sergiodelossantosjr Can you give me any more details here? Can I get a description of what your data looked like? Any ignored columns? Any interesting data shapes?

**Comment by sergiodelossantosjr** [comment]
> @sergiodelossantosjr Can you give me any more details here? Can I get a description of what your data looked like? Any ignored columns? Any interesting data shapes?

Hi @beccamc sorry for my late reply, I've just included all the columns with one hundred rows of data, I can't attach my csv file because github not allowed it.
![image](https://user-images.githubusercontent.com/22256389/123668461-b682ea80-d86d-11eb-92bf-e8e5c6cd250b.png)

**Comment by beccamc** [comment]
If this is still happening, can you change your data into a .txt (should be able to safely rename) and upload it?
