### ISSUE TITLE
Should not have "Train in Azure" option on “Next steps” page for scenarios which not support Azure environment even if the data path doesn't exist.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1515]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.0.2131501 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**Describe the bug**
- On which step of the process did you run into an issue: “Next steps” page
- Clear description of the problem: "Train in Azure" is for Azure environment scenarios, should not exist on Text classification/Value prediction/Recommendation scenarios.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select one of Text classification/Value prediction/Recommendation scenarios to complete training;
5. Navigate to "Next step" page, no "Train in Azure" option;
6. But if you change the data path, then reopen the model builder to see: "Train in Azure" option will exist on "Next step" page.
7. Or if you clone repository to another VM which have different data path, see:  "Train in Azure" option will exist on "Next step" page.

**Expected behavior**
 No "Train in Azure" option on “Next steps” page for scenarios which not support Azure environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/122352293-9441c080-cf81-11eb-8171-27484b93067b.png)
Gif:
![Train in Azure](https://user-images.githubusercontent.com/81727020/122353214-6ad56480-cf82-11eb-8530-2c2b738103b8.gif)

**Additional context**
Similar closed issue #913

**Comment by zewditu** [comment]
The team had a discussion on what should be the experience when the file path is changed. I do not think we have a specific thing we decided if there is anything anyone can point me to.

I would suggest disabling all tabs after the data tab by letting the user on the data page the file does not exist on the current path.

**Comment by JakeRadMSFT** [comment]
Closing since it's an edge case and we're revisting error on load and revisiting versioning.
