### ISSUE TITLE
Model Builder Error : Unable to find method 'StartTrainingAsync/1' on {no object} 

### ISSUE THREAD

**Issue by gerwintmg** [dotnet/machinelearning-modelbuilder#1516]
**System Information (please complete the following information):**
 - Model Builder Version : 16.6.0.2130907 
 - Visual Studio Version: Microsoft Visual Studio Community 2019 Version 16.10.2

**Describe the bug**
- On which step of the process did you run into an issue:
I Pressed the "Start training" butten

- Clear description of the problem:
Model Builder Error
Unable to find method 'StartTrainingAsync/1' on {no object} for the following reasons: Deserializing JSON-RPC argument with name "config" and position 0 to type "System.String" failed: Error reading string. Unexpected token: StartObject. Path 'params[0]', line 6, position 5

**To Reproduce**
1. Go to Project context menu -> Add -> Machine learning
2. Click  "Image Classification"
3. Select Training images mine where located in "C:\temp\.."
4. Click "Train" button
5. Select "Local"
6. Click "Start training"
7. ERROR..

**Expected behavior**
I expected to start model training..

**Screenshots**
![image](https://user-images.githubusercontent.com/17082189/122358996-765e6680-cf55-11eb-93d0-1f62d3b1721a.png)

**Comment by LittleLittleCloud** [comment]
@JakeRadMSFT could it be something similar to #1513, except that the null object is training config?

@gerwintmg Could you give it a second try and see if the error still exists? If the error is still there, can we get the service hub log on your machine? You can find it through following steps
- close VS
- go to %temp%servicehub folder and delete logs
- set `ServiceHubTraceLevel` to `All`
- reopen VS and model builder, and launch the same experiment
- go to %temp%servicehub\logs folder and you should see a log file which name includes `MicrosoftMLModelBuilderAutoML`. That's the servicehub log for this service.

Regards

**Comment by gerwintmg** [comment]
@LittleLittleCloud 
the second try gives the same error.

These are 2 of the logs I got.

[EFF85C23-MicrosoftMLModelBuilderAutoML-14824-eupctufw-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/6673025/EFF85C23-MicrosoftMLModelBuilderAutoML-14824-eupctufw-1.log)
[EFF85C23-CreateAutoMLServiceAsync-26468-q3rdfaty-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/6673027/EFF85C23-CreateAutoMLServiceAsync-26468-q3rdfaty-1.log)

**Comment by LittleLittleCloud** [comment]
Thanks @gerwintmg , We are taking a look!

**Comment by LittleLittleCloud** [comment]
Hi @gerwintmg 
We might need more logs from servicehub,, can you try the previous steps again and this time just zip the entire log folder and upload here? Thanks!

**Comment by gerwintmg** [comment]
[logs.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/6684597/logs.zip)

Hope this helps :)

**Comment by MikeSifanele** [comment]
@LittleLittleCloud I also experienced the same issue. I uninstalled the `ML.NET Model Builder GPU Support (Preview)` and I started working/training.

**Comment by LittleLittleCloud** [comment]
@MikeSifanele 

Thanks for the info, are you using image classification when the error appears?

**Comment by LittleLittleCloud** [comment]
Hi @gerwintmg , Thank for the log. It still misses verbose log though, can you check if `ServiceHubTraceLevel` is set to `All` in  System variables?
![image](https://user-images.githubusercontent.com/16876986/122827554-59010380-d299-11eb-8459-d7fdb7716a4d.png)

And you will need to restart VS after setting that variable as well. After that, you should see different level of logs(verbose/information...) in log file.

![image](https://user-images.githubusercontent.com/16876986/122827394-248d4780-d299-11eb-8e95-a351bea962e9.png)

**Comment by MikeSifanele** [comment]
No, I was using the value prediction scenario.

**Comment by gerwintmg** [comment]
I did "set ServiceHubTraceLevel All" in Powershell and it was valid... (set is a alias of Set-Variable)

So now with powershell:
```powershell
[System.Environment]::SetEnvironmentVariable('ServiceHubTraceLevel','All',[System.EnvironmentVariableTarget]::User)
```


and here are new log: (no zip with all logs as some logs contained tokens, close to authentication)

[C1F86FFE-MicrosoftMLModelBuilderAutoML-8548-byh5vjhq-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/6694955/C1F86FFE-MicrosoftMLModelBuilderAutoML-8548-byh5vjhq-1.log)
[C1F86FFE-MicrosoftMLModelBuilderAutoML-8548-cahsgb4t-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/6694956/C1F86FFE-MicrosoftMLModelBuilderAutoML-8548-cahsgb4t-1.log)
[C1F86FFE-CreateAutoMLServiceAsync-hubControllerLookup-21824-adyc4en5-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/6694963/C1F86FFE-CreateAutoMLServiceAsync-hubControllerLookup-21824-adyc4en5-1.log)
[C1F86FFE-CreateAutoMLServiceAsync-hubControllerLookup-21824-feouxsnc-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/6694964/C1F86FFE-CreateAutoMLServiceAsync-hubControllerLookup-21824-feouxsnc-1.log)
[C1F86FFE-CreateAutoMLServiceAsync-hubControllerLookup-21824-nwcy3jpq-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/6694965/C1F86FFE-CreateAutoMLServiceAsync-hubControllerLookup-21824-nwcy3jpq-1.log)
[C1F86FFE-CreateAutoMLServiceAsync-21824-pabajwtk-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/6694966/C1F86FFE-CreateAutoMLServiceAsync-21824-pabajwtk-1.log)
[C1F86FFE-CreateAutoMLServiceAsync-hubControllerLookup-21824-25hbwe2v-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/6694967/C1F86FFE-CreateAutoMLServiceAsync-hubControllerLookup-21824-25hbwe2v-1.log)

**Comment by LittleLittleCloud** [comment]
Hi @gerwintmg 
Thanks for the trace logs! It's of great help to us debugging the problem you encountered.

Based on the log, it seems that the error is caused by an older ModelBuilder call into a newer version of AutoML service, which has a different signature of `StartTrainingAsync`. And also it looks like your model builder is not latest because of the missing of GPU training. Maybe the model builder extension is not updated correctly. It's also possible that something got GAC’d at some point and so an older version of the assembly ends up getting loaded.

![image](https://user-images.githubusercontent.com/16876986/122986266-12241400-d354-11eb-9e75-9e4e7c664d4c.png)

Could you do us a favor by uninstalling modelbuilder first, then re-install it from market place. The latest version should be `16.6.1`. And see if this problem go away? Since in the latest version, we shift to a [config-base training](https://devblogs.microsoft.com/dotnet/ml-net-and-model-builder-march-updates/#config-based-training-with-generated-code-behind-files), and you can use this to validate if your model builder is up-to-date

**Comment by LittleLittleCloud** [comment]
@gerwintmg 
Any updates on this issue

**Comment by LittleLittleCloud** [comment]
@gerwintmg 

we assume that the reinstallation successfully solve this issue as there's no response, feel free to reopen it and @ me if it's not.

**Comment by greg-x-Chen** [comment]
still see this issue after revert/update of ModelBuilder

**Comment by greg-x-Chen** [comment]
finally works after removed ModelBuilder with GUP support

**Comment by LittleLittleCloud** [comment]
It's probably you are having an older version of GPU extension, which confuses VisualStudio on finding the correct AutoML Service when launching ModelBuilder
