### ISSUE TITLE
Object Detection Exception Unhandled 

### ISSUE THREAD

**Issue by melissatranuw** [dotnet/machinelearning-modelbuilder#1517]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.1.0.2027905
 - Visual Studio Version: 2019

**Describe the bug**
- On which step of the process did you run into an issue: Training an Object Detection file with 
[Balloon_Subset-export.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/6672240/Balloon_Subset-export.zip)

- Clear description of the problem: Was not able to train data because was thrown an exception. All paths in json file exist. 

**To Reproduce**
1. Azure Environment
![image](https://user-images.githubusercontent.com/55814458/122461367-1ae9a400-cf68-11eb-9b25-3ac96f40ad5e.png)

2. Train json file
3. See exception error

**Screenshots**
![image](https://user-images.githubusercontent.com/55814458/122449559-d572aa00-cf5a-11eb-8551-c12a29b29ea0.png)

**Comment by vzhuqin** [comment]
Not meet any error during training Json file.
ML.Net Model Builder (Preview): 16.7.2.2141201 (Main Branch)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7f76b670-ea06-4c24-bb9b-f4605ebb4dbe)
