### ISSUE TITLE
categorical supervised learning(strings only)

### ISSUE THREAD

**Issue by Gattan-Qbit** [dotnet/machinelearning-modelbuilder#1518]
Model Builder currently supports two data sources, local files (.csv and .tsv) and SQL tables. We understand your data is in many different places and shapes. We'd like to understand where your data comes from so we can better support your scenario in Model Builder.

**Where is your data located?**
My dataset is located on my local c drive. 

**What does your data look like?**
My data is text, format is CSV file as plain text data with (12 columns+ 1 label column) = 13 columns

**Does your data require transformations?**
No

**Example**
[dataset-C.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6678339/dataset-C.txt)

**Additional context**
all numbers are categorical, I was able to produce a model in MATLAB, however, ML.net is not working with me. 
The dataset is representing a organization chart, for each job title there is a grade and categorical job type(numbers).  I am prediction the grade of the supervisor position by providing all features(12 columns).

**Comment by LittleLittleCloud** [comment]
Hi @Gattan-Qbit 

What kind of error do you get? No model produced within time budget or poor performace in accuracy?

In addition, you can set up a column as catagorical in [advanced data option window](https://devblogs.microsoft.com/dotnet/ml-net-model-builder-november-updates/#advanced-data-loading-options)

![image](https://user-images.githubusercontent.com/16876986/122606552-f526d280-d02d-11eb-8d43-fb555b6b5563.png)

**Comment by Gattan-Qbit** [comment]
yes, it worked with Text classification scenario with advanced options with text format dataset, before that I was using recommendation scenario and it did not work.
Great thanks

**Comment by beccamc** [comment]
Closing as this issue is resolved. Please @ mention us if there is anything else you need help with!
