### ISSUE TITLE
Confused about generated Model.training.cs for multiple categorical columns.

### ISSUE THREAD

**Issue by flokie** [dotnet/machinelearning-modelbuilder#1519]
**System Information (please complete the following information):**
 - Model Builder Version: 16.6.0.2130906
 - Visual Studio Version: 16.11.0 preview 2

**Describe the bug**
Firstly I'm a total newbie on ML.NET and also machine learning. I've used only Model Builder to trying stuff so far. So, I'm not sure if it's a bug or not.

I have "S" and "D" columns as categorical ones and I'm selecting them as categorical in Advanced Data Settings. But generated BuildPipeline method is identical as if I select only "S" as categorical.

Shouldn't be something like in the second screenshot that I modified as it shows as an example in the OneHotEncoding documentation?

**Screenshots**
Generated
<img width="1102" alt="Screen Shot 2021-06-19 at 11 30 55" src="https://user-images.githubusercontent.com/28707189/122637811-4b147c80-d0f9-11eb-814f-130feee8633f.png">

Modified
<img width="1101" alt="Screen Shot 2021-06-19 at 11 41 54" src="https://user-images.githubusercontent.com/28707189/122637816-5071c700-d0f9-11eb-81d0-0ac92aed42a9.png">

**Comment by LittleLittleCloud** [comment]
hi @flokie , thanks for using Model Builder!

To answer your question, `Onehot encoder` will not apply if the data type of `D` is numeric, even if `D` is marked as categoric.

**Comment by flokie** [comment]
@LittleLittleCloud Thank you for the explanation =)
