### ISSUE TITLE
Documentation Update 

### ISSUE THREAD

**Issue by melissatranuw** [dotnet/machinelearning-modelbuilder#1525]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.6.0
 - Visual Studio Version: 2019

**Describe the bug**
- On which step of the process did you run into an issue: Step "Create your App" on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create

- Clear description of the problem: When following the documentation, https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create , it suggest to "Choose the C# Console App (.NET Core) project template." but based on VS, that project name does not exist besides "Console Application" or "Console App (.NET Framework)". When choosing "Console App (.NET Framework)", and adding "Machine Learning", "Machine Learning Model (ML.NET)" does not appear in the installed.

**Expected behavior**
![image](https://user-images.githubusercontent.com/55814458/123010823-31cb3480-d374-11eb-926d-4575ceba5129.png)

**Screenshots**
When searching C# Console App (.NET Core):
![image](https://user-images.githubusercontent.com/55814458/123010913-5de6b580-d374-11eb-9127-4b0347e5cd3e.png)

When adding machine learning on Console App (.NET Framework) project:
![image](https://user-images.githubusercontent.com/55814458/123011056-9b4b4300-d374-11eb-847f-8d6622b5ed21.png)

**Comment by beccamc** [comment]
Related to https://github.com/dotnet/machinelearning-modelbuilder/issues/1511

**Comment by mrrcomp** [comment]
FYI I was still able to add the Builder to my ,net mvc project after "add machine learning" i got a popup message at the top of the ui telling me to enable it in the options of VS which i did and then i was able to fully enable the machine learning for the mvc solution.

**Comment by beccamc** [comment]
This is a duplicate. Closing.
