### ISSUE TITLE
Should not enable Save button if select multiple Label or Item purpose in advanced data option for Recommendation scenario.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1527]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.1.2131904 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Recommendation scenario and navigate to data page;
5. Open Advanced data options dialog to set the purpose;
6. See error: the save button is enabled even if I set two Label or Item purpose.

**Expected behavior**
For Recommendation, there should be exactly 1 Label and 1 User and 1 Item Column in advanced data options.

**Screenshots**
![multiple purpose save issue](https://user-images.githubusercontent.com/81727020/123216704-679b2500-d4fc-11eb-954b-d364096950ea.gif)

**Additional context**

**Comment by beccamc** [comment]
Great find Qin!

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch: 16.13.5.2221801
![image](https://user-images.githubusercontent.com/99375895/163939621-711ad6b5-5e89-4fa4-a41c-f329c8d14654.png)
![image](https://user-images.githubusercontent.com/99375895/163939684-01ab45a8-aae7-48df-8b87-4752b5fa9ffd.png)
![image](https://user-images.githubusercontent.com/99375895/163939710-219417a3-997a-4735-92c1-007e18c8a56f.png)
