### ISSUE TITLE
Model Builder Error "Value cannot be null. Parameter name: source".

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1528]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.1.2131904 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**Describe the bug**
- On which step of the process did you run into an issue: Data page
- Clear description of the problem: I'm not sure if this is an issue, this error only appears on the training complete model builder, if change the data source before training, not have this error.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Value prediction>Local (CPU) >File data source type to complete training, then save it;
5. Back to Data page, want to use SQL Server data type;
6. Click "SQL Server", prompt model builder error: "Value cannot be null. Parameter name: source"

**Expected behavior**
No error dialog switching data source between File and SQL Server.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/123223062-25c1ad00-d503-11eb-9e32-8a2cd5f15654.png)

**Additional context**

**Comment by vzhuqin** [comment]
This error also appears when back to click one scenario after trained.
![1528 error](https://user-images.githubusercontent.com/81727020/125910348-858cfa64-8033-4d38-b22d-0a3dd2566e08.gif)

**Comment by beccamc** [comment]
One of our customers ran into this during user testing.

**Comment by LittleLittleCloud** [comment]
Not reproduce on Dev17
