### ISSUE TITLE
Error message upon cancellation of training: Value cannot be null

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1536]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.6.1.2131904
 - Visual Studio Version: 16.10.2

**Describe the bug**
- On which step of the process did you run into an issue: finalizing model (after pressing cancel)
- Clear description of the problem:
After pressing cancel, the error "Value cannot be null" is received. .training.cs and .consumption.cs and .zip are created. 
After clicking "Close" no problems were observed.

**To Reproduce**
Unknown.

**Expected behavior**
No errors should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/26261427/123663047-b15a7700-d83e-11eb-8fa6-a7a4f7ceaf09.png)

**Additional context**

```
(Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-06-28 18:14:46.3452 TRACE [Source=BinarySaver; Saving, Kind=Trace] Channel finished. Elapsed 00:00:00.3242308. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-06-28 18:14:46.3452 TRACE [Source=BinarySaver; Saving, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-06-28 18:14:46.3452 TRACE [Source=Saving Schema, Kind=Trace] Channel finished. Elapsed 00:00:00.3262362. (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-06-28 18:14:46.3452 TRACE [Source=Saving Schema, Kind=Trace] Channel disposed (Microsoft.ML.ModelBuilder.Utils.Logger.Trace)
2021-06-28 18:15:10.3516 DEBUG Open Log FileC:\Users\username\AppData\Local\Temp\MLVSTools\logs\7c4eff7b-07fe-4b58-9bc1-6038c9a028ee.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
```

```
| Top 5 models explored |
------------------------------------------------------------------------------------------------------------------
| Trainer MicroAccuracy MacroAccuracy Duration #Iteration |
|130 LightGbmMulti 0.9203 0.9183 1035.1 130 | 
```

**Comment by torronen** [comment]
Here is the log file of a new run. This happened after pressing "Cancel". Then "Cancelling..." status took about 2 hours or so, with high number of system memory hard faults, and about 85% RAM consumption. Lenovo Legion, Ryzen 7 5800, 16 Gb, fixed size 368 Gb paging file set in Windows System settings.
Visual Studio Version: 16.10.3

I will keep the computer untouched for 1-2 days in case some other logs files are needed. This one was logging ALL level of service hub which I can upload if needed.

Windows Application Log had one error within the same hours in System tab, but it might be unrelated. It is in the zip file

ML Training log file:
[f6399587-5fb2-4871-a1b4-023139fbe0ca.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6744040/f6399587-5fb2-4871-a1b4-023139fbe0ca.txt)

![Capture](https://user-images.githubusercontent.com/26261427/124032399-342b2f80-da01-11eb-9602-434782b337f7.PNG)

**Comment by torronen** [comment]
It seems all files (model, consumption, training) were created and added to the project. Model makes a prediction in the Evaluate tab of the model builder. So I suppose can be considered a low priority issue.

**Comment by beccamc** [comment]
We should check if this is fixed in the 16.7 release.

**Comment by beccamc** [comment]
@torronen as always, thanks for the detailed information! Seems like there are two issues here... 

- Value cannot be null. I think this is fixed in our new build - https://marketplace.visualstudio.com/items?itemName=MLNET.07. Would  you mind trying again on the new bits?
- Cancel takes a long time and still creates code files. Is this covered by [Issue 1645](https://github.com/dotnet/machinelearning-modelbuilder/issues/1645) that you filed?

Thanks!

**Comment by torronen** [comment]
Yes, the slow cancellation covered by that issue, it's only here as they might be connected. 

I can test it and let you know if the issue reappears but I think I did not find a way to recreate it consistently.

**Comment by torronen** [comment]
I did not encounter this issue yet, but I only had 3 longer tasks with Model Builder last week. So maybe close, and then re-open if it is found again?
