### ISSUE TITLE
Suggestion: Enable horizontal scrollbar

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1539]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.1.2131904 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**Describe the bug**
- On which step of the process did you run into an issue: All tabs: Scenario, Environment, Data, Train, Evaluate, Consume, Next steps
- Clear description of the problem:  most text or button will not pop down a line on small screens, so hope to enable the horizontal scrollbar.

**To Reproduce**
Steps to reproduce the behavior (see below .GIF):
![horizontal scrollbar](https://user-images.githubusercontent.com/81727020/123731521-db597b00-d8ca-11eb-9832-33a1f4033977.gif)

**Expected behavior**
Enable horizontal scrollbar or realize the text/ button to pop to the next line on a small screen for all tabs.

**Comment by beccamc** [comment]
@romalpani What is the minimum window size we need to support?

**Comment by romalpani** [comment]
@beccamc 
Here are the guidelines for VS Win UI and resolutions. Let me know if you have any questions.
https://devdivdesignguide.azurewebsites.net/processes/craftsmanship-checklist/#resolution-and-screen-size

**Comment by beccamc** [comment]
This is a nice to have, but has not been requested by any customers. Moving to chopping block for a Jake/Bri decision  if we should invest in this.  We have previously removed horizontal scroll bars Issue [1229](https://github.com/dotnet/machinelearning-modelbuilder/issues/1229).  The experience here would have to turn on scroll when a certain **min** width is reached. 

We haven't failed any accessibility testing for the current experience.

**Comment by romalpani** [comment]
I am trying to see how the UI reacts to more scaling factors of 100%, 150%, 200%, 250% but for some reason; I am unable to scale correctly. 
If the UI is not cutting off at these scales, then I think we are fine.

**Comment by JakeRadMSFT** [comment]
By Design
