### ISSUE TITLE
Could not install Package Microsoft Ml 1.5.5

### ISSUE THREAD

**Issue by mrrcomp** [dotnet/machinelearning-modelbuilder#1541]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): Version:16.6.1.2131904
 - Visual Studio Version16.10.2

**Describe the bug**
- On which step of the process did you run into an issue:After Doing a Training at finalizing Model
- Clear description of the problem: 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/710257/123749836-86b00300-d8be-11eb-8cf3-74a995a106a3.png)

**Additional context**

**Comment by torronen** [comment]
I think .NET Framework 4.6 is not supported, and we will need to create .NET Core project to use the model builder.

Related to: https://github.com/dotnet/machinelearning-modelbuilder/issues/1511

**Comment by mrrcomp** [comment]
@torronen will i be  able to add the model to the .net mvc project after?

**Comment by torronen** [comment]
@mrrcomp Good question. I don't know. Probably at least .NET Framework 4.7.2 is needed because it supports .NET Standard 2.0. Microsoft.ML seems to be available for it.

**Comment by LittleLittleCloud** [comment]
@mrrcomp Have you tried updating your project from net462 to net472 (or other frameworks that work with netstandard2.0) and see if it resolve this issue? Otherwise it's expected that the installation package fails.

**Comment by LittleLittleCloud** [comment]
@mrrcomp 
I'm going to close this as there's no reply, feel free to reopen it and @ me if you have any other questions
