### ISSUE TITLE
model build error--- image trainning base on GPU 

### ISSUE THREAD

**Issue by zjdandy99ge** [dotnet/machinelearning-modelbuilder#1543]
2021-06-30 13:58:39.7692 DEBUG StreamJsonRpc.ConnectionLostException: 在请求完成之前, 与远程方的 JSON-RPC 连接已丢失。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__148.MoveNext()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Microsoft.ML.ModelBuilder.TrainSession.<StartAsync>d__44.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
2021-06-30 14:10:29.1972 DEBUG Open Log FileC:\Users\Thinkpad\AppData\Local\Temp\MLVSTools\logs\1c730cad-6b5e-405e-944d-943dfb32199c.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

![image](https://user-images.githubusercontent.com/72737207/123911417-5c3d7300-d9ae-11eb-949a-43b932267077.png)

![image](https://user-images.githubusercontent.com/72737207/123910535-28158280-d9ad-11eb-867b-6ce22f1dc937.png)

**Comment by zjdandy99ge** [comment]
GPU  and CUDA environment are good

**Comment by LittleLittleCloud** [comment]
The error indicates servicehub host crashes. Can you upload the log from %temp%servicehub/log here so we can take a look?

In the meanwhile, can you confirm that the version of GPU extension is identical with model builder's, and can we have your model builder version number as well?

**Comment by zjdandy99ge** [comment]
> The error indicates servicehub host crashes. Can you upload the log from %temp%servicehub/log here so we can take a look?
> 
> In the meanwhile, can you confirm that the version of GPU extension is identical with model builder's, and can we have your model builder version number as wellbo

**Comment by zjdandy99ge** [comment]
> The error indicates servicehub host crashes. Can you upload the log from %temp%servicehub/log here so we can take a look?
> 
> In the meanwhile, can you confirm that the version of GPU extension is identical with model builder's, and can we have your model builder version number as well?

both are the lastet version , include model builder and gpu extension. 
I could use the previous  vs 2019 preview  version and the related gpu extension for image trainning, but these issures appeare since I upgrad vs 2019  preview version and model biuld and gpu extension
