### ISSUE TITLE
local object detection in model builder (offline)

### ISSUE THREAD

**Issue by masgh021** [dotnet/machinelearning-modelbuilder#1545]
hello ,
is it possible local training for object detection (without azure) ?

**Comment by LittleLittleCloud** [comment]
Sorry it's not available right now.

@briacht +1 for another request for local object detection training.

**Comment by beccamc** [comment]
@masgh021 Thanks for letting us know! We're still using your previous request to track this... https://github.com/dotnet/machinelearning-modelbuilder/issues/1091

**Comment by beccamc** [comment]
Hi, I'm closing this in favor of tracking in 1091. Thanks for reporting!
