### ISSUE TITLE
Notebook regression - Compare actual values to predicted values in a scatter plot - predict label doesn't match

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1546]
![image](https://user-images.githubusercontent.com/16876986/124171598-a3367180-da5d-11eb-9602-6b4a2de8e919.png)

The predict value is from column `rate_code`

**Comment by melissatranuw** [comment]
Fixed! Thanks for catching this!
![image](https://user-images.githubusercontent.com/55814458/124183301-e0eec680-da6c-11eb-83b9-3d05c04fb9ed.png)

**Comment by melissatranuw** [comment]
Fixed! Thanks for catching this! @LittleLittleCloud 
![image](https://user-images.githubusercontent.com/55814458/124185910-6a53c800-da70-11eb-9126-ff305d394b21.png)
