### ISSUE TITLE
Generated notebook is missing nuget reference

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#1547]
![image](https://user-images.githubusercontent.com/31937616/124171851-edb7ee00-da5d-11eb-9474-3134e7c7326c.png)

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud should be able to point you to how to get the list necessary of nugets for the pipeline.

**Comment by melissatranuw** [comment]
![image](https://user-images.githubusercontent.com/55814458/124189440-8d34ab00-da75-11eb-82fd-710333f3a92d.png)
![image](https://user-images.githubusercontent.com/55814458/124189465-99206d00-da75-11eb-93b1-f83b2cffad8a.png)
Fixed! Thanks for catching this @JakeRadMSFT! All test should generate needed NuGet's in the first cell.
