### ISSUE TITLE
notebook - Microsoft.ML.AutoML not required

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1548]
We shouldn't need `Microsoft.ML.AutoML` dependency in regression.
![image](https://user-images.githubusercontent.com/16876986/124171981-1e982300-da5e-11eb-90b4-efad73197792.png)

**Comment by melissatranuw** [comment]
![image](https://user-images.githubusercontent.com/55814458/124190606-69726480-da77-11eb-993c-a1f95f6d6255.png)
Thank you!
