### ISSUE TITLE
pipeline format error

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1549]
pipeline code shouldn't have space at the begining.
![image](https://user-images.githubusercontent.com/16876986/124172262-76368e80-da5e-11eb-9813-0a8f98b1d023.png)

**Comment by melissatranuw** [comment]
![image](https://user-images.githubusercontent.com/55814458/124190993-fb7a6d00-da77-11eb-8b48-0224c31b0773.png)
Fixed! Thank you!
