### ISSUE TITLE
Suggest - get rid of explicitly defined ModelInput class

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1550]
Imaging what it will be on that 7000 column's dataset.

![image](https://user-images.githubusercontent.com/16876986/124172722-04127980-da5f-11eb-9a83-972ea3775ea7.png)

A proper way is to use `DataFrame` class, which supports loading from fixed width text file directly.

**Comment by torronen** [comment]
If ModelInput were not used and only LoadCSV is used, can model skip additional columns?

For apps having  ModelInput may have the benefit of being a list of what fields are needed for the model, and being able to read it during debugging.

**Comment by luisquintanilla** [comment]
Thanks all for the discussion. There are no plans for this at the moment, so closing for now.
