### ISSUE TITLE
LightGbm nuget is missing when best trainer is lgbm

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1551]
![image](https://user-images.githubusercontent.com/16876986/124173101-7420ff80-da5f-11eb-87a5-8c4d11df8add.png)

**Comment by melissatranuw** [comment]
![image](https://user-images.githubusercontent.com/55814458/124191585-d3d7d480-da78-11eb-9a64-50a8f09325cb.png)
![image](https://user-images.githubusercontent.com/55814458/124191601-dc300f80-da78-11eb-86ff-7a048b6fae0d.png)
I changed the pipeline cell so it should now generated needed nugets. Thanks for catching this!
