### ISSUE TITLE
Inconsistent numerical format in the value column

### ISSUE THREAD

**Issue by houghj16** [dotnet/machinelearning-modelbuilder#1552]
![image](https://user-images.githubusercontent.com/46505805/124173039-2791f000-da70-11eb-828a-41a54b2a6946.png)

Seen during the classification scenario.

**Comment by houghj16** [comment]
Suggestion - Preceding 0 should be consistently applied.

**Comment by melissatranuw** [comment]
I agree! Thank you! I decided to do no zero's 
![image](https://user-images.githubusercontent.com/55814458/124193721-354d7280-da7c-11eb-8452-5f90b7e6149b.png)
