### ISSUE TITLE
can't appear what i see in instruction

### ISSUE THREAD

**Issue by ddaa12** [dotnet/machinelearning-modelbuilder#1556]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
@ddaa12 Sorry you've run into this problem. Are you saying you don't see the "Add machine learning" in the right click menu?

**Comment by beccamc** [comment]
Are you following the instructions [here](https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install)? Did you enable the feature?

Model Builder does not work on VB projects. If you are using a VB project you won't see the option to add machine learning.

**Comment by beccamc** [comment]
@ddaa12 I don't have enough information to help solve this. Please look at our troubleshooting section for [help](https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#i-cannot-add-machine-learning-to-my-project) and re-open if none of those work. 

Thanks!
