### ISSUE TITLE
Train page - Cannot see the drop arrow for "Training setup summary"

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#1557]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:
In Text classification scenario on the Train page, "Training setup summary" section is missing the drop arrow on the right. Also, the text is not clickable. 

**To Reproduce**

**Expected behavior**
The dropdown arrow should be visible, collapsed by default. The text + the dropdown arrow should be clickable.

**Screenshots**
![image](https://user-images.githubusercontent.com/48927690/124308822-aa718400-db1e-11eb-920b-317df18c54c5.png)

**Additional context**

**Comment by vzhuqin** [comment]
I have the same issue on: 
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 2.1
- ML.Net Model Builder (Preview): 16.7.2.2140201 (Main Branch)
- .Net: 5.0.302
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/5dafabbb-ead4-4a51-bbf4-039e7b108f10)

**Comment by zewditu** [comment]
This issue is not reproducible on the latest main.
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/5ab18fd5-bd2b-48f3-a4ba-dac35114b2a5)
