### ISSUE TITLE
Remove header row from Data Preview summary count

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1569]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.2.2135501 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**Describe the bug**
- On which step of the process did you run into an issue: Data Page
- Clear description of the problem: I guess that the 10 here is meant to express the number of preview rows that do not include the header row, but the 200,001 rows is including header row. So the 10 of "10/200,001 rows" will be understood as including the number of header row, this is confusing.

**Test matrix:**
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Navigate to Data page, input the data source;
5. It is found that the number 10 of rows in the preview is ambiguous. 

**Expected behavior**
Show the correct preview number of rows seen by the naked eye, or the number 10 may need to be explained (for example, the header row is not included).

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/124887757-0ac56180-e008-11eb-8bb5-f5fded6f2856.png)
![image](https://user-images.githubusercontent.com/81727020/124888360-9ccd6a00-e008-11eb-89f1-cb4e28172a69.png)

**Additional context**

**Comment by beccamc** [comment]
@briacht and @romalpani Do we want to not include the header row in the "total row" number?

**Comment by romalpani** [comment]
I wouldn't think so. Because "number of data rows" should simply be the data rows.

**Comment by beccamc** [comment]
We should remove the header row from the reported count (if there is a header row).

**No header:** 10 of {Total rows in file} 
**Header:** 10 of {Total rows in file -1}

**Comment by romalpani** [comment]
Can a customer train with data that doesn't have a header row?

**Comment by beccamc** [comment]
Yes. No header row is even a supported option in advanced options. We show default columns names if there is not header row (col0, col1, etc.)

**Comment by vzhuqin** [comment]
Not repro this issue on main build: 16.7.2.2142301
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0848e92e-798e-42e2-9937-9483c4e9c9f8)
