### ISSUE TITLE
Remove auto adding the ML.NET NuGet and class library reference

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#157]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
We get compilation errors when a user adds a reference to the generated library project.

**To Reproduce**
1. Create a new Console app
2. Try any scenario in Model Builder and add projects 
3. add reference to class library and add code to consume the model
3. Compile
**Expected behavior**
No compilation errors

**Screenshots**

**Additional context**

The fix for now is to update the user's project to ML.NET 1.2 Nuget package.

**Comment by JakeRadMSFT** [comment]
Change nuget reference that we add to be a range - [1.0, 2.0).

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/dependencies

**Comment by JakeRadMSFT** [comment]
Also detect if they already have a reference we should prompt them to upgrade to a range reference: [1.0, 2.0).

**Comment by JakeRadMSFT** [comment]
Related: #147 #152

**Comment by rustd** [comment]
Remove auto adding the ML.NET NuGet and class library reference. We will do it in the next release as part of Code gen spec.
Currently we want to release this early next week and there are too many unknowns around what could be broken.
