### ISSUE TITLE
Suggestion: Enlarge the guided focus on "Next Steps" page.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1574]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.2.2135501 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**Describe the bug**
- On which step of the process did you run into an issue: Next steps page
- Clear description of the problem: clicking "Tab" key, find some characters seem to be overlapped by the guided focus, it looks uncomfortable, hope to enlarge the size, it is recommended to adjust to the same as the Scenario page. 

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Pass all and navigate to "Next steps" page;
4. Clicking "Tab" key, find some characters are overlapped by the guided focus

**Expected behavior**
Enlarge the guided focus on "Next Steps" page.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/125044411-84c01e00-e0ce-11eb-9af1-c0ca2f9f95a6.png)
![image](https://user-images.githubusercontent.com/81727020/125045134-3bbc9980-e0cf-11eb-8a97-abdc5d2f4ea3.png)

Guided focus on Scenario page:
![image](https://user-images.githubusercontent.com/81727020/125045024-25164280-e0cf-11eb-8e2f-45a136ce2833.png)

**Additional context**

**Comment by JakeRadMSFT** [comment]
@zewditu do the scenario and next steps page use the same style?

**Comment by beccamc** [comment]
@beccamc connect this to the title issue.

**Comment by beccamc** [comment]
Fix at the same time as https://github.com/dotnet/machinelearning-modelbuilder/issues/1675?

**Comment by beccamc** [comment]
This is low priority, closing.
