### ISSUE TITLE
A11y_Model Builder_Create New Experiment_Keyboard: Keyboard focus is going to invisible content for two tab strokes after account picker button in 'Create new experiment' button.

### ISSUE THREAD

**Issue by NiharikaTipirishetty** [dotnet/machinelearning-modelbuilder#1576]
[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**GitHubTags:**
#A11y_Model Builder; #A11yMAS; #A11yTCS; #WCAG2.4.3; #Focus Order; #Keyboard; #Win32; #DesktopApp; #A11ySev2; #ModelBuilder-Win32-Jun2021; #Visual Studio Client; 

### Environment Details:
Application name: Model Builder

### OS Details:
Windows Version 21H1 OS Build (19043.1083)
Microsoft Visual Studio 

### Repro Steps:

1. Enable ML.NET Model builder as a preview feature in tools>options>Environment>preview features.
2. Create a .NET C# project and tab till project under solution explorer and Add machine learning.
3. Tab till Image classification under scenario tab and press enter.
4. Select Azure under environment tab and tab till set up workspace and press enter.
5. In 'Create New Experiment' dialog tab till account picker control and press tab
6. Verify keyboard focus goes invisible content for two tab strokes

### Actual Result:
Keyboard focus is going to invisible content for two tab strokes after account picker button in 'Create new experiment' button.

### Expected Result:
Keyboard focus should not go to invisible content for two tab strokes after account picker button in 'Create new experiment' button. After account picker control, keyboard focus should land on 'subscriptions' dropdown, Focus order should always be continuous.

### User Impact:
Keyboard users will not understand where focus is landing and might get confused if focus is lost for 2 tab strokes continuously

**Comment by zewditu** [comment]
This is not reproducible on the current latest main.

**Comment by NiharikaTipirishetty** [comment]
Issue is fixed. After account picker, keyboard focus is going to 'Subscriptions' dropdown. Focus is not going to invisible content.

https://user-images.githubusercontent.com/83570638/128997139-ac5f88bb-93cd-4639-91dd-0b4c51baabf5.mp4

**Comment by VijayaBharathyA** [comment]
#Closed;
