### ISSUE TITLE
.mbconfig update path

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1580]
We need criteria on how to update .mbconfig from older version to newer version. Please visit the following notebook link for a proposal

https://microsoft.sharepoint.com/teams/ML.NETModelBuilder/_layouts/OneNote.aspx?id=%2Fteams%2FML.NETModelBuilder%2FSiteAssets%2FML.NET%20Model%20Builder%20Notebook&wd=target%28Dev.one%7C0CFA1AFB-A2F3-7F41-ADB6-F2123D7B9E2F%2F.mbconfig%20backward%20compatibility%7CB0E61F01-DB7C-4BAF-8BAF-C6C28175C14F%2F%29
onenote:https://microsoft.sharepoint.com/teams/ML.NETModelBuilder/SiteAssets/ML.NET%20Model%20Builder%20Notebook/Dev.one#.mbconfig%20backward%20compatibility&section-id={0CFA1AFB-A2F3-7F41-ADB6-F2123D7B9E2F}&page-id={B0E61F01-DB7C-4BAF-8BAF-C6C28175C14F}&end

**Comment by luisquintanilla** [comment]
@LittleLittleCloud I have this listed as needing docs. What's needed from a docs standpoint?

**Comment by LittleLittleCloud** [comment]
@luisquintanilla 
I was just thinking that if it's necessary to let audience know we change the schema of .mbconfig so they won't be confused ( something like why after just reopening mbconfig changes my .mbconfig file...) But a better place to mention it seems to be in release doc now.

**Comment by luisquintanilla** [comment]
Yeah. In the release notes makes sense.
