### ISSUE TITLE
Suggestion: Recover latest model after failed training

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1584]
**Is your feature request related to a problem? Please describe.**
Sometimes training may fail due to multiple reasons. Many training failures are related to various ML algorithms. Due to the variability of the algorithms, various data, and the possibility of new algorithms being introduced, it may be hard to Model Builder to catch all exceptions. Model Builder and Microsoft.ML are relatively new and bugs should be expected.

After training fails, the user is left without any results. As some of the crashes only occur rarely with some model configurations or system situations. It means the longer the training has taken the higher the chance of a crash. Unfortunately, the user is also more frustrated after waiting a long time for the training to complete.

**Describe the solution you'd like**
After seeing the Failed status on Train tab user should also see "Recover model" button.

Model recovery should be fairly simple to implement because .mbconfig already includes the history of the models explored. All model files (.zip) seem to still exist in a temporary folder in Users/AppData. 

To create the recovery function, it should:
 1. Check the best model from .mbconfig and check what is the number of said model*
 2. Copy model (e.g. 14.zip) from temp folder to project folder and add to project.
 3. Generate .consumption and .training files and add to project

*It should be ensured .mbconfig JSON keeps order, or .mbconfig should add the explicit number of the model.

**Describe alternatives you've considered**
1) Skip errors and continue to next model automatically
2) Add the model to solution and re-genereate .consumption and .training files every time a new best model is found, replacing the previous ones 
3) "Save snapshot" button to save the progress while training
4) Recovery model, with the option to select any of the other models, too, based on the history data in .mbconfig file

**Additional context**
If this could be prioritized, that would be great. 

It would make it feasible to explore longer training runs and thus find more bugs which may occur rarely, and allow to experiment with consumption of the models even if some data may cause more regulary issues.

Happy to test if a there are any preview (of the preview) versions as it would simplify my work a lot :)

**Comment by LittleLittleCloud** [comment]
Hi @torronen We are working on *Continue training* experience, which will save snapshot automatically during training and restart from the last saving point when re-launch. It should meet your request. And I can ping you for a try-out once the preview is ready

**Comment by LittleLittleCloud** [comment]
#1508
