### ISSUE TITLE
CLI auto-completion no longer working

### ISSUE THREAD

**Issue by jwood803** [dotnet/machinelearning-modelbuilder#1585]
**System Information:**
 - CLI version: 16.2.0+511cc1082bef7a4bbb2f83ad88c1c425c932079c
 - .NET Suggest: 1.1.221601

**Describe the bug**
The [CLI auto-complete](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-ml-net-cli#set-up-cli-suggestions-tab-based-auto-completion) seems to no longer work.

**To Reproduce**
1. Performed the steps from the doc
2. Auto-complete doesn't seem to work like it's shown in the GIF on the doc

**Comment by luisquintanilla** [comment]
@LittleLittleCloud can you confirm whether auto-completion can still be used. If so, how can you go about setting it up?

**Comment by LittleLittleCloud** [comment]
The auto-completion haven't been set up yet for the current mlnet.cli (the version after 0.15.1) so I'm afraid that you can't use it for now. We have a working item on it a long time ago but it's of low priority and might be already buried under the dust. The mlnet.cli on the current document is still the old one (before 0.15.1).

@briacht let me know if we want to prioritize the auto-completion of mlnet.cli. It's worth implementing and might not be an expensive one to do (I'll need to reach out to dotnet cli team to confirm it though)

**Comment by LittleLittleCloud** [comment]
trace in #1404
