### ISSUE TITLE
Suggestion: User should be able to select his own test data

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1588]
**Is your feature request related to a problem? Please describe.**
I have been skeptical if this is really needed, but it seems we have now some cases where the metrics are amazing, but the actual performance very low. At the moment we suspect the reason is the way test data has been taken for this dataset.

If the test data is not selected correctly, a wrong model may  be selected and users may expect it to perform according to the metrics.

Example: Rain prediction for construction sites has measurements from 10 places (humidity, rainfall, temperature). The goal is to predict if rain will fall within 1 hour on a specific site so the site can take appropriate steps to protect. Currently, model builder selects test data randomly. Unfortunately, some of the nearby measurements sites are heavily correlated and random sample will mean the model has already seen the answer for that moment from a nearby site. 

**Describe the solution you'd like**
We would like to separate a few specifc hours (timespan) for all sites in the test data to guarantee the model does not have seen what happens on that specifc day. CLI and API already support custom test data sets, so I believe it would be a reasonable effort to include it as an advanced feature in Model Builder. 

We will next try with ML API so we can confirm if the problem for selection of a wrong model is due to sample selection.

**Describe alternatives you've considered**
Alternatively, model builder could provide settings for how the test data should be sampled.

Alternatively, model builder could select test data from the end (like e.g. AutoKeras) so users could put the test data they want at the end. There may be cases where this is not ideal depending on the way the test data was created, but I dont have examples of it.

**Additional context**
The ways in which users can affect test data sampling is critical for selection of the correct model. Because main function, or one of them, for Model Builder is to select and finetune the best model it probably should not be ommited.

**Comment by LittleLittleCloud** [comment]
@briacht @romalpani for notification. For now, the test dataset can go with the WIP advanced training option so no UI changes will be required on the data page.

**Comment by romalpani** [comment]
@LittleLittleCloud Let's discuss this suggestion in our design sync before we add anything to Advanced data options.

**Comment by briacht** [comment]
Related to #60

**Comment by beccamc** [comment]
We're tracking this in #60. Linking the issues so that we keep these useful details.
