### ISSUE TITLE
Suggestion: return to the original add Machine Learning Model window after closing the reminder dialog.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1589]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.2.2136201 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**Describe the bug**
- On which step of the process did you run into an issue: add machine learning model
- Clear description of the problem: If a model builder with the same name already exists, it pops up a Microsoft Visual Studio dialog to remind the user, but after closed the dialog, it is found that the original window for adding a machine learning model is not returned. Originally, I wanted to go back and change the name to add it again, but I had to start from the beginning. 

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Name the model, and click "Add" button;
5. Pop up a Microsoft Visual Studio dialog that the name already exists;
6. Close the reminder dialog, find the original window for adding a machine learning model is not returned.

**Expected behavior**
The original window for adding a machine learning model can be returned so that rename the model builder directly to add again.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/125264939-ee426580-e336-11eb-9543-7671ed234d22.png)
![Same name error](https://user-images.githubusercontent.com/81727020/125266914-e257a300-e338-11eb-9c73-64710aea5b70.gif)

**Additional context**

**Comment by JakeRadMSFT** [comment]
Closing this because it's outside of our control. This is new dialog behavior.
