### ISSUE TITLE
Files without headers doesn't work

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#159]
**System Information (please complete the following information):**
 - Model Builder Version: BugBash
 - Visual Studio Version

**Describe the bug**
Columns and info about files without headers are not shown correctly.

**To Reproduce**
1. Go to 'Sentiment Analysis'
2. Upload a txt file without header (
[sentiment-yelp-test.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/3379961/sentiment-yelp-test.txt)
)
3. See error

**Expected behavior**
- The data preview should show info in all the columns
- The headers in data preview and "Columns to Predict"  drop down should have column names such as "Column0" .. "Column2" .. "ColumnN-1"
- Training should finish and I can generate and consume the code.

**Screenshots**
![image](https://user-images.githubusercontent.com/1132652/61017051-b1f25e00-a346-11e9-8d42-0848780a4f68.png)

**Additional context**

**Comment by LittleLittleCloud** [comment]
See [this](https://stackoverflow.com/questions/2940618/what-is-it-about-datatable-column-names-with-dots-that-makes-them-unsuitable-for) as reference

**Comment by LittleLittleCloud** [comment]
Either we can add support for special char like `.` or `/` in column field so it can preview the data in a correct way, or we can use it as a way to detect whether it has header or not and then use `column#` as header. Which is prefer?

My vote is for the first one, for the following reason:

- simple solution, less than ten lines of code (estimated) needed to be add
- user friendly, User see what they see, the raw data, they can decide whether they need to add header field or not

Any other ideas? @greazer @rustd @JakeRadMSFT @tbombach

**Comment by rustd** [comment]
We have other bugs tracking user input for "Has header" and separators. This is not a regression.
