### ISSUE TITLE
Selecting Model Builder in VS Installer should install the latest version of MB

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1590]
1. I modified Visual Studio 2019 and removed all instances of Model Builder.
2. I modified VS again and under .NET Core Cross plat workload, I checked ML.NET Model Builder and installed it:
![image](https://user-images.githubusercontent.com/10437687/125334114-db606e80-e2ff-11eb-8982-06160a4c30b0.png)
3. I opened VS and opened Extensions Manager and got the following version:
![image](https://user-images.githubusercontent.com/10437687/125330941-385a2580-e2fc-11eb-87ca-c8e344b7266c.png)

I would expect this to be the latest version: 16.6.1.2131904

**Comment by LittleLittleCloud** [comment]
@JakeRadMSFT  for awareness

FYI We would need QB approval on it to make any changes in dev16 released version. The next release for dev16 is 16.11 and ddl for qb approval mode on that release is 08/05
