### ISSUE TITLE
Program.cs  does not show the actual value to compare with predicted value

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1592]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
The user has to open the dataset to refer the actual value of the dataset.

**Expected behavior**
There should be text that says " Actual Fare_amount: value..."  above "predicted Fare_amount:17.482143"

**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/125363446-791a6480-e325-11eb-9efa-23af224becb3.png)

**Additional context**

**Comment by LittleLittleCloud** [comment]
@zewditu can you help look at it

**Comment by zewditu** [comment]
@LittleLittleCloud  sure!
@briacht & @romalpani  what should be the text and where to show it?

**Comment by briacht** [comment]
It should be how it was before.

Predicted Fare_amount: 17.482
Actual Fare_amount: 17.5

**Comment by zewditu** [comment]
The Program. cs template does not include this.

**Comment by zewditu** [comment]
From the text  " Using model to make single prediction -- Comparing actual Area with predicted Area from sample data..."  " "...Comparing actual Area with predicted Area from sample data..."  seems that we need to look the actual value from the sample data instead of creating a separate line "Actual Fare_amount: 17.5" .
 does it like this before @briacht ? 
 Predicted Fare_amount: 17.482
Actual Fare_amount: 17.5

I thought it was   like this 
![image](https://user-images.githubusercontent.com/36615490/126026884-6e1f56b1-194c-4d4b-af8f-28f1148e9993.png)

Correct me if I am wrong.

**Comment by briacht** [comment]
I remember having actual and predicted values near each other. Can we check previous versions?

**Comment by zewditu** [comment]
@briacht  for some reason my build failed for old commits and I am not able to get some old MB releases to show the screen shouts, However, I confirmed from the sources code used previously they were not near to each other.
But if you want values near each other now I can do it.

**Comment by briacht** [comment]
Yes let's put them near each other for easy comparison

**Comment by vzhuqin** [comment]
@zewditu The actual and predicted values are not next to each other, could you help to confirm whether this is expected now?

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/de291806-19dc-4fe5-8f15-522b7b29e14e)

**Comment by LittleLittleCloud** [comment]
It's fine,,, Quite common to have a difference between truth and predict value.

**Comment by vzhuqin** [comment]
Thanks @LittleLittleCloud , what I want to confirm is, is there no need to put the two values near each other for easy comparison? I saw zewditu and Bri discussed this in comments above.

**Comment by LittleLittleCloud** [comment]
I think it's fine for now (to have predict | actual value not close to each other). We can make them next to each other if someone asking for it.

**Comment by vzhuqin** [comment]
@LittleLittleCloud , On Binary classification, not display the actual value, is this expected?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/c73e634c-07fb-4d36-82b5-0b8346815cc4)

**Comment by LittleLittleCloud** [comment]
@vzhuqin 

Nope,,, I'll take a look

**Comment by zewditu** [comment]
@vzhuqin  are you on the latest build of Model Builder?  ![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/80188ae6-b31d-4f2b-bf09-0df1374b6256)
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/a2d94867-c70e-4470-b61a-eb4bea7f9d25)

**Comment by vzhuqin** [comment]
Hi @zewditu Yes, it is the latest main build: 16.7.4.2145201.
I try it again with the [dataset](https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv), but the values 1 and 0 are not replaced with true and false, set the "Sentiment" column to Label purpose. If I did something wrong, please let me know. 
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/68138621-6f76-4fe9-91b3-9cd311a3c91d)

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/00bab4a3-c8c7-4b09-9b52-689b61a2d717)

**Comment by briacht** [comment]
I do think that having actual and predicted value next to each other will make it a lot easier to compare and evaluate the model
