### ISSUE TITLE
The mouse scroll fails if the mouse hovers over the data area of "Data" and "Evaluate" pages.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1593]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.2.2136201 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**Describe the bug**
- On which step of the process did you run into an issue: "Data" and "Evaluate" pages
- Clear description of the problem:  I often feel that the up and down scrolling is not very smooth on "Data" and "Evaluate" pages. Today I finally found the reason, that is, when the mouse is over the Data Preview grid of Data page or the Sample data area of Evaluate page, the scrolling function fails. Please help to take a look.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Navigate to Data page, and input the data source, scroll the mouse on the data page, sometimes it is not smooth, after research found that if the mouse is hovering over the data preview grid, the scrolling function fails.
5. Navigate to Evaluate page, find that if the mouse hovers over the sample data area, the scrolling function also fails.

**Expected behavior**
The mouse scrolling experience is smooth.

**Screenshots**
Data page:
![scrolling](https://user-images.githubusercontent.com/81727020/125380909-956dde00-e3c5-11eb-8732-257f76e3f0ae.gif)

Evaluate page:
![scrolling on Evaluate](https://user-images.githubusercontent.com/81727020/125381710-f77b1300-e3c6-11eb-8287-ce05be767a4d.gif)

**Additional context**

**Comment by LittleLittleCloud** [comment]
@beccamc can you take a look?

**Comment by beccamc** [comment]
This is a known limitation of WPF. Unfortunately when hovering over a scroll area, it ignores the parent scroll area. The evaluate page is a scroll area (for when there are more fields) and the data preview grid is also a scroll area (horizontal). 

More details: https://github.com/dotnet/machinelearning-tools/pull/524 

I'm closing as won't fix. Thanks Qin!
