### ISSUE TITLE
Model path's string returns null

### ISSUE THREAD

**Issue by Hrishikesh46779** [dotnet/machinelearning-modelbuilder#1608]
In xamarin this line "public static string MLNetModelPath = Path.Combine(System.AppContext.BaseDirectory, "MLModel.zip");" throws System.ArgumentNullException: 'Value cannot be null. Parameter name: path1

![image](https://user-images.githubusercontent.com/46864647/125900658-36ea7233-2f14-45eb-9716-c174602806d4.png)

**Comment by LittleLittleCloud** [comment]
After searching around google, looks like it's a known issue in xamarin and hasn't be resolved yet.

https://github.com/xamarin/xamarin-android/issues/3489
