### ISSUE TITLE
Save button doesn't work when project type is netstandard (net472)

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1609]
**Model Builder Version**: 16.6.1

To reproduce
- create a net472 project
- add model builder
- hit ctrl + s

![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/c8bbad67-3fae-4f7a-b2c1-ec359988393b)

**Comment by LittleLittleCloud** [comment]
@JakeRadMSFT @beccamc 
This issue breaks the config-base training experience in all net472 projects (users won't be able to save .mbconfig), maybe we should consider publishing a hot fix for this bug.

**Comment by LittleLittleCloud** [comment]
@beccamc 
Unfortunately it doesn't fix #1511, I still need more time to explore on how to fix that bug but there's a workaround for#1511 though so that doesn't block customers.

**Comment by beccamc** [comment]
I didn't see the work around before. Makes sense!

**Comment by vzhuqin** [comment]
This issue not occurs on candidate build: 16.6.3.2136603
steps:

1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Framework) project template with .Net Framework 4.7.2;
3. Add model builder by right click on the project;
4. Select Text classification scenario, then hit Ctrl+s to save the model builder;

![1609-Fix.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/71b72b50-f4f0-4679-bfe9-acd3546f8bfa)
