### ISSUE TITLE
Error loading mbconfig file: The method or operation is not implemented.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1614]
**System Information (please complete the following information):**
 - Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.3.2136604 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**Describe the bug**
- On which step of the process did you run into an issue: Add Machine Learning model
- Clear description of the problem: After click "Add" button, pop up the error dialog. Close the error dialog, the model is added and trained normally.

**To Reproduce**

1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Name the model, and click "Add" button;
5. Pop up an Error dialog that Error loading mbconfig file: The method or operation is not implemented.

**Expected behavior**
No error appears during adding machine learning model.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/126095960-55befb6a-3781-44cb-9bcc-1b9ddc26ce4a.png)

**Additional context**

**Comment by LittleLittleCloud** [comment]
Thanks for finding that, this bug is caused by a recent update I made for serializing training config, I'll take a look and fix that

**Comment by vzhuqin** [comment]
Not repro this issue on main build: 16.7.0.2137701
![1614Fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/d2a8f46a-8bdc-4507-bd1b-7a68e498c946)
