### ISSUE TITLE
Model Builder Error: The process cannot access temp file as being used by another process.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1616]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.3.2136604 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**Describe the bug**
- On which step of the process did you run into an issue: Data page
- Clear description of the problem: This error has always been difficult to reproduce, and I see this error occasionally, and then when I want to reproduce it, this error dialog does not appear again. From the test records, this error has occurred since the 16.6.1.2131904 of the main build.  Today, I meet this error again, find that it appears on the Image classification or Object detection scenarios. The steps listed below can sometimes reproduce this error, please take a look.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Image classification scenario;
5. Select Local (CPU) or Azure environment;
6. Navigate to Data page, sometimes below steps will meet the error.
 a. Select the image folder, pop up the error dialog as below .gif .
 b. Select one image folder, then change to another image folder.

**Screenshots**
.gif :
![be used issue2](https://user-images.githubusercontent.com/81727020/126123731-42334925-493f-4f37-aadc-e4fe14877415.gif)

Object detection:
![image](https://user-images.githubusercontent.com/81727020/126125730-868ed2cc-1b0f-4fc0-9965-c2a77bd3d361.png)

**Additional context**
Close the error dialog, can continue to train and other steps.

**Comment by zewditu** [comment]
@vzhuqin  I am not able to reproduce these issues on our latest main.

**Comment by vzhuqin** [comment]
@zewditu This problem is a bit of a headache, when you want to reproduce it, it just doesn't appear, but it will pop up inadvertently. 

I just met this issue on latest main build: 16.7.0.2137001, please take a look.

Repro steps:
1. Create one new Model Builder;
2. Select image classification scenario;
3. Select Local (CPU) environment;
4. Input the image folder, here not issues;
5. Go back to repeat steps 2-3;
6. Input the same dataset, pop up the model builder error dialog.
![1616 repro2](https://user-images.githubusercontent.com/81727020/127084936-2ab4ca1a-371c-4cb8-8a6a-1480e5d59a2e.gif)

Error log:
[ImageLocal_MLModel1-YZVSJO.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6882217/ImageLocal_MLModel1-YZVSJO.txt)

**Comment by beccamc** [comment]
@LittleLittleCloud Any ideas what could be causing this one? I'm setting it as P2 and moving to triage.

**Comment by LittleLittleCloud** [comment]
@beccamc 
Might be caused by update handler? I'm not sure...

**Comment by beccamc** [comment]
Ahhh, yes that's a good guess. We're probably on a background thread writing to this file, open a file and kick off the same write operation, but can't because the previous is still running (and wasn't cancelled). 

Similarly, I think there was a request from one of the "%temp% file too large" issues to make these file write operations stop on cancel. We should probably make the operation cancellable and make sure we cancel if we either 1) cancel training, or 2) pick a new dataset (dependent on what files are generated where).

**Comment by beccamc** [comment]
Over a year with no updates on this issue or customers reporting. Given that it's flakey to reproduce I am closing.
