### ISSUE TITLE
Error loading mbconfig file: Required property 'FilePath' not found in JSON. Path ‘’, line 7, position 17.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1617]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.3.2136604 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Image classification or Object detection scenario;
5. Save  and close the model builder;
6. Re-open the model builder, pop up the error dialog that: Error loading mbconfig file: Required property 'FilePath' not found in JSON. Path ‘’, line 7, position 17.
7. Close the error, find that no scenario is selected.

**Expected behavior**
No error after re-open model builder after selected Image classification or Object detection scenario, and the scenario should still be selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/126129080-2bd5c100-9d26-4031-8859-e83b5d8e2f5d.png)

**Additional context**
1. This issue only occurs on Image classification and Object detection scenario.
2. This issue doesn't occur if reopen the model builder after input the data or training completed.

**Comment by zewditu** [comment]
@vzhuqin  thanks for catching this .

**Comment by LittleLittleCloud** [comment]
Thanks for finding that, this bug (along with #1614) might be introduced by the receont serializing training config PR, I'll take a look

**Comment by vzhuqin** [comment]
Not repro this issue on main build: 16.7.0.2137701
![1617Fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7beec158-a3e9-4742-93d3-b5eb623527c9)
