### ISSUE TITLE
Small Image or empty folder warning display everytime we open the .mbconfig file 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1619]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. Select image scenario 
2. choose any environment 
3. On the data page select a dataset that has less than 5 images in the class or empty images.
4. click ok on the warning 
5. Save and Close the .mbconfig file.
6. Reopen the .mbconfig file.

**Expected Experience**
Show scenario page without the warning window 

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/4c946205-af92-49c7-bade-c1b087da5ba9)

**Additional Context**
I am not sure whether it is a bug or a regular experience

**Comment by zewditu** [comment]
@briacht  any thought on this?

**Comment by briacht** [comment]
I don't think this pop-up should appear right when .mbconfig is re-opened. It can appear when they re-open mbconfig and then hit "Start training"

Thoughts @romalpani

**Comment by beccamc** [comment]
I'm pushing back that this is not high enough priority to fix. While it would be better to show this on re-train, anyone with only 5 images is using a toy dataset.  IMO not worth spending time on a fix here.

**Comment by romalpani** [comment]
As of now, I agree with what @briacht  is suggesting with having the dialog pop-up on train action. 

But things to consider for the future - 
1. Let's warn the customer at the time of adding data that their folder contains very few images. This is a data warning/error and should live there. 

2. We can also work on a mechanism to show such statuses on re-entry via the left hand wizard navigation. We do have some explorations in this area. Happy to sync.

**Comment by JakeRadMSFT** [comment]
Closing due to low priority. We can revisit with customer feedback.
