### ISSUE TITLE
add mongodb for training data 

### ISSUE THREAD

**Issue by behroozbc** [dotnet/machinelearning-modelbuilder#1622]
**Is your feature request related to a problem? Please describe.**
hi now in modelbuilder support file and sqlserver database for training data . I want to add mogodb NoSQL database for training data 
**Describe the solution you'd like**
add mongdb option for loading data  in cli and ui in visual studio

**Comment by behroozbc** [comment]
hi 
no one see this issue ??

**Comment by beccamc** [comment]
Hi @behroozbc, thanks for letting know this request. @briacht for visibility.

**Comment by luisquintanilla** [comment]
Thanks for this issue @behroozbc. There are no plans to add support for NoSQL databases to our tools. However, as we hear more feedback from users, we can reevaluate at a later date. Closing this issue for now.
