### ISSUE TITLE
The selected columns should not be lost after re-open model builder.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1624]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.3.2136604 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.3
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Data page.
- Clear description of the problem: Reopen the model builder, find that the selected columns are lost on data page. They are selected in Advanced data options.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Pass all tabs, then save and close the model builder;
5. Reopen the model builder, navigate to data page, find the selected columns are lost.

**Expected behavior**
All selected results are retained after re-entrancy.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/126425572-a867a052-7b99-4d26-ac5e-e4633ee67223.png)

**Additional context**
Not happen on candidate build: 16.6.3.2136603

**Comment by zewditu** [comment]
This  causes the issue https://github.com/dotnet/machinelearning-modelbuilder/issues/1623

**Comment by JakeRadMSFT** [comment]
@zewditu is this resolved?

**Comment by zewditu** [comment]
Nop

**Comment by beccamc** [comment]
It seems that selected columns are not being displayed on reload. We should fix this for September release
