### ISSUE TITLE
File Modification Detected dialog appears after training completed.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1625]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.3.2136603 (Candidate build)
- Microsoft Visual Studio Enterprise 2019: 16.10.3
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Train completed
- Clear description of the problem: After training completed, pop up one File Modification Detected dialog, said that the project has been modified outside the environment. I have tried the four buttons, found that the generated files .consumption.cs & .training.cs & .zip can be load to VS by clicking "Reload" or "Reload All" button, if you click "ignore" or "ignore All" buttons, it  also won't affect the next steps, can still predict the results and add project templates. Not sure if this dialog is expected, please take a look.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Framework) project template with .Net Framework 4.7.2;
3. Add model builder by right click on the project;
4. After training completed, pop up File Modification Detected dialog, said that the project has been modified outside the environment.

**Expected behavior**
Not sure if this dialog is expected behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/126442418-feaa2fff-7bf8-416f-b003-d20655878469.png)

**Additional context**
This dialog also appears on main build: 16.6.3.2136604

**Comment by zewditu** [comment]
@LittleLittleCloud  for visibility

**Comment by LittleLittleCloud** [comment]
It's expected, as Model Builder will update .csproj after training is completed.

**Comment by beccamc** [comment]
Closing as this is expected behavior.
