### ISSUE TITLE
The target framework of generated projects should not be .net core when project type is .net framework.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1626]
**System Information (please complete the following information):**

- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.3.2136603 (Candidate build)
- Microsoft Visual Studio Enterprise 2019: 16.10.3
- .Net: 5.0.302

**To Reproduce**

1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Framework) project template with .Net Framework 4.7.2;
3. Add model builder by right click on the project;
4. After training completed, navigate to Consume page and add the ConsoleApp and WebApi project templates;
5. Find that the target framework of generated projects is .net 5.0.

**Expected behavior**
When the project type is .net framework, the target framework of the generated project should be consistent with it. 

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/126457336-83687cfc-e6db-4a64-aaab-348840fb7c8d.png)

**Additional context**

**Comment by zewditu** [comment]
@briacht, @LittleLittleCloud,  @JakeRadMSFT   I remember the topic about the target framework of generated projects was discussed and we decided to make it net5.0 . 
Any thought?

**Comment by beccamc** [comment]
@zewditu Previous issue discussing this is here - https://github.com/dotnet/machinelearning-modelbuilder/issues/1384

**Comment by zewditu** [comment]
@beccamc thanks for pointing me to that discussion,
As per our previous discussion, we are waiting for customer feedback to match the target framework.

**Comment by JakeRadMSFT** [comment]
Waiting for customer feedback.
