### ISSUE TITLE
There is no mbconfig file in the generated project templates. 

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1628]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.3.2136604 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.3
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: generated projects
- Clear description of the problem: For previous main build, there is mbconfig file in the generated ConsoleApp and WebApi projects. Is this a new update? Now there is no mbconfig file and doesn't affect the running of these generated projects. 

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. After trained and added the project templates;
5. Found that there is no mbconfig file in the generated ConsoleApp and WebApi projects.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/126600988-0d198a4a-2459-4be7-b08a-6813d56931a7.png)

**Additional context**
Not occurs on candidate build: 16.6.3.2136603
Not occurs on previous main build: 16.6.2.2136201

**Comment by zewditu** [comment]
@LittleLittleCloud  is this dies to mbconfig migration ?

**Comment by LittleLittleCloud** [comment]
@zewditu Yep it's after migration, I'll push a quick fix for that

**Comment by vzhuqin** [comment]
not repro this issue on main build: 16.7.2.2140201
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/093b0021-fd93-4148-bd56-5b21ba35623c)
