### ISSUE TITLE
Wrong decimal place when showing accuracy for Image classification + Azure environment.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1633]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.3.2136604 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.3
- .Net: 5.0.302

**Test Matrix:**
https://testpass.blob.core.windows.net/test-pass-data/weather.zip (Weather folder)

**Describe the bug**
- On which step of the process did you run into an issue: Train completed
- Clear description of the problem: With the same test matrix, the previous best accuracy of training results is high to 99%.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Image classification scenario and Azure environment;
5. After training complete, found that the Best accuracy is very low, only have 0.98%.
6. Click Train again, the accuracy is also low.

**Expected behavior**
![image](https://user-images.githubusercontent.com/81727020/126746618-190e1110-9b38-4457-8014-6a046490aa07.png)

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
@vzhuqin Can you include the link to the run? I'm wondering if we are reporting with the wrong decimal place (is this supposed to be 98%?).

**Comment by vzhuqin** [comment]
@beccamc I got the same score on latest main build: 16.7.0.2137701
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/feef1bcf-5327-4d23-9b1b-8a2fb0846af7)
But the Primary metric score is 0.98222 from run link in Azure portal:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2c643661-7d75-4fd3-9061-36a47aa06fb4)
Run link in Azure portal:
https://ml.azure.com/experiments/id/891078f2-635b-4e43-849b-f5129264b1fa/runs/AutoML_e4cfa9bd-aba5-4464-9448-2eb18b1a540d?wsid=/subscriptions/83635e26-687a-4333-a2a0-33e3cd1f573a/resourceGroups/FullTestPass/providers/Microsoft.MachineLearningServices/workspaces/FullTestPass&tid=72f988bf-86f1-41af-91ab-2d7cd011db47

Output:
[https://app.zenhub.com/files/186917455/e8bf2949-b030-4014-8b5f-52b978007fc8/download](https://app.zenhub.com/files/186917455/e8bf2949-b030-4014-8b5f-52b978007fc8/download)

**Comment by beccamc** [comment]
Thanks Qin! The Azure run accuracy should be .98 out of 1. We should be reporting in model builder as 98% instead of the Azure form. Good catch! 

@zewditu I think you just did some work on displaying these values? Can you change the Azure value to show xx% instead of the decimal value?

**Comment by vzhuqin** [comment]
@beccamc  @zewditu I found the score in .mbconfig file has issue for Object detection scenario, could you help to take a look together?
I think the scores show on Train page and Azure portal is correct, but it shows 0.01 in mbconfig file.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3782041e-f7f2-4ceb-86ed-f4a424b49b44)

**Comment by LittleLittleCloud** [comment]
decimal still wrong for object detection

![image](https://user-images.githubusercontent.com/16876986/130524215-d747c421-7445-4752-8f38-fdbe8a4f72ef.png)

**Comment by vzhuqin** [comment]
This issue is fixed on main build: 16.7.4.2143102
Object detection:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/72453d5a-168f-4005-bebd-05b73ffd13c1)
Image Classification:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/584a5ece-01ea-4781-8e20-b6e54cc2d019)
