### ISSUE TITLE
Multiple versions of CUDA installed.Uninstalled all except CUDA 10.1.

### ISSUE THREAD

**Issue by hb126** [dotnet/machinelearning-modelbuilder#1642]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.6.1.2131904
 - Visual Studio Version:16.10.4

  Use [Image classification]-[Local(GPU)]-[Check compatibility],always show "Multiple versions of CUDA installed.Uninstall all except CUDA 10.1 ".
  But I only install CUDA 10.1,What is the basis for checking CUDA?

**Comment by LittleLittleCloud** [comment]
I believe we check Cuda version through system environment? @zewditu which variable are we looking into? "CUDA" or "CUDA_10_1"?

**Comment by hb126** [comment]
I delete system environment [CUDA_PATH_V10_1] show "CUDA 10.1 is missing.", but add it show "Multiple versions of CUDA installed.Uninstall all except CUDA 10.1. ".

**Comment by LittleLittleCloud** [comment]
@hb126 
Can you go check your Cuda install directory (by default it should be `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA`) and make sure there's only one Cuda10.1 folder there? I take a look at the code and it seems that if you have more than one folder in that install directory you'll get that (Multiple version) error message

**Comment by zewditu** [comment]
the variable is "CUDA_PATH"

**Comment by LittleLittleCloud** [comment]
@JakeRadMSFT  @zewditu 

The current logic of detecting installed Cuda will block the user who has multiple cudas installed, even if they correctly set cuda 10.1 as the selected Cuda. They'll need to remove all other cudas, which is not necessary.

It seems to me that multiple cuda check is unnecessary, especially when `CUDA_PATH_10_1` is set and CUDA 10.1 installation directory is set in $Path variable. Maybe we should not block user to next step when detecting multiple cuda?

#1429

**Comment by hb126** [comment]
@LittleLittleCloud @zewditu 
Thank you very much.
Yes, the problem is that there are multiple folders in the CUDA installation directory.
When installing CUDA, I installed development, documentation and samples into three folders under the CUDA directory. After I moved them into a directory, the check passed.
But I think this kind of examination seems unnecessary.

**Comment by LittleLittleCloud** [comment]
We should only check if "CUDA_PATH_V10_1" is available, to make sure Cuda v10.1 is installed. And add the path to its binary to $env:Path when training started, so cuda v10.1 is selected to use during training.

**Comment by LittleLittleCloud** [comment]
Reopen it and move it to "in review" panel

**Comment by beccamc** [comment]
@LittleLittleCloud Does the user only need to have CUDA 10.1 installed for this to work? Or does it need to be set as the "selected" CUDA?

**Comment by LittleLittleCloud** [comment]
No they don't have to, as long as Cuda 10.1 is installed and Cuda_Path_v10_1 is set (which should be set automatically when installing cuda10.1)

**Comment by luisquintanilla** [comment]
@LittleLittleCloud is this PR the only doc related requirement for this issue?

dotnet/docs#25879

**Comment by LittleLittleCloud** [comment]
Yep
