### ISSUE TITLE
DllNotFoundException during prediction

### ISSUE THREAD

**Issue by Hrishikesh46779** [dotnet/machinelearning-modelbuilder#1646]
![image](https://user-images.githubusercontent.com/46864647/127146877-bb4bcfe7-ffed-4993-b45a-0d3a05ebc606.png)
VS version- 16.10.4
Model builder version- 16.6.1.213.1904
 
I am using ml.net in xamarin.

**Comment by beccamc** [comment]
@Hrishikesh46779 Sorry you ran into this problem. Can I get some more information?

- VS Version
- Model Builder version (available via Manage Extension dialog)
- Is this a .NET Core or Framework project? Can I get the version. 

Thanks!

**Comment by beccamc** [comment]
@Hrishikesh46779 we just shipped a new version. Can you update and try again? https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by beccamc** [comment]
Closing this issue. Please reopen if you're still having problems. Thanks!
