### ISSUE TITLE
The Performent and the GPU extension Bugs

### ISSUE THREAD

**Issue by jkh675** [dotnet/machinelearning-modelbuilder#1647]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Preview 2022 and 2019

**Describe the bug**
- On Building the model:
- I run the build model for the first time it takes 5minutes and I run the training more times the speed slower and slower 5min to 10min and 30min:

**To Reproduce**
1. the machine learning page
2. click on the training button 
3. and press start
4. and do 1,2 and 3 a few times
5. then the speed of the training is slower than the first training 

**Additional context**
I use GTX1060 6GB to run the training but it happened on CPU(i5-9600k) training , and another bug is on Visual Studio 2022 i already install the GPU extension but it still warning me to install the extension 

(my eng is bad and some translations may be not be correct becuz i use Chinese ver VS so I don't know what text in eng)

**Comment by jkh675** [comment]
I solve the performance issue but it was just a temporary way, goto the windows TEMP file (%TEMP%) and delete all the files(!!!!DANGER!!!!)

**Comment by beccamc** [comment]
Thanks for reporting @jkh675, and sorry you ran into this problem. I'm glad you were able to find a work around. We are working on a fix for this. Please follow this issue - https://github.com/dotnet/machinelearning-modelbuilder/issues/320
