### ISSUE TITLE
Cannot GetLabelColumn for OD scenario on reload 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1649]
Trying to reload a v1 OD mbconfig I get an error. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/fe36c7d0-e1bc-4639-be9b-12e9b8829121)

After error message is shown, everything seems to be reloaded correctly. [https://app.zenhub.com/files/186917455/7791dfdf-c7a3-4bd4-91bc-4abcf8467692/download](https://app.zenhub.com/files/186917455/7791dfdf-c7a3-4bd4-91bc-4abcf8467692/download)

**Comment by beccamc** [comment]
@zewditu I think this regressed from the PR here - https://github.com/dotnet/machinelearning-tools/commit/186c6b8eeb3611eb962ff7b8f8d3d40f2f6c7ce6. 

Can you please take a look?

**Comment by zewditu** [comment]
I will look into it

**Comment by zewditu** [comment]
@beccamc  the issue is not reproduced from the current latest main.
when you say reload reopen an OD mbconfig file, right?

**Comment by beccamc** [comment]
Yes. Reopen an object detection model builder file. It has to be trained.

**Comment by zewditu** [comment]
Thanks, if that is the case the issue does not exist now in our latest main.
