### ISSUE TITLE
schema migration bug - Delimiter not found | FilePath not found

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1650]
**System Information (please complete the following information):**
 - Model Builder Version main
 - Visual Studio Version

```
{
  "TrainingConfigurationVersion": 0,
  "TrainingTime": 3600,
  "Scenario": {
    "ScenarioType": "Regression"
  },
  "DataSource": {
    "DataSourceType": "TabularFile",
    "FilePath": "",
    "DecimalMarker": "\u0000",
    "HasHeader": false
  },
  "Environment": {
    "EnvironmentType": "LocalCPU"
  }
}
```

### To reproduce
- create a new .mbconfig with above content
- open it!

**Comment by vzhuqin** [comment]
Verified this on latest main build: 16.7.2.2141201, @LittleLittleCloud could you help to confirm whether below steps are correct and the behavior is expected?

**Steps:**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Close the model builder;
5. Open the mbconfig file and replace the content to:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/85fb70ad-5b23-4172-8899-4be6396921c6)
6. Re-open the model builder in VS, see below behavior.

**Behavior:**
1. Scenario: Value prediction was selected.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7431e911-40bb-4fdb-8d79-9a7a4829b495)
2. Environment: selected Local(CPU) environment.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/8e34c63a-635e-4cce-b056-e8ba4845d209)
3. Data: no input data
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/831b2d5d-a10d-4fa2-83f3-d2948f0cb7d6)

**Comment by LittleLittleCloud** [comment]
Yep the behavior looks good

**Comment by vzhuqin** [comment]
Thanks xiaoyun's confirmation.
