### ISSUE TITLE
Misalignment with Environment tags

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1652]
First - "Example" is off
![image](https://user-images.githubusercontent.com/10437687/127232997-89a2d7c2-72a4-429d-8d65-9fbb9a3893a0.png)

Second - it looks like the box isn't big enough for the "Local" text:
![image](https://user-images.githubusercontent.com/10437687/127233056-b55544cd-ed27-4a19-94f4-007caf3147f5.png)

@romalpani

**Comment by romalpani** [comment]
@briacht may be this is a good opportunity to revisit the idea of having "example" tag on the cards in the first place. I don't think we necessarily need it, especially because they are already listed under a separate title. 

As far as the "local" tag screenshot - yes, that seems like a bug.

**Comment by zewditu** [comment]
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/85aa3034-66a9-421d-996c-1ff90976bde6)
 ## Fixed in our main 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/3901fbf1-2ce3-4c96-b524-c08b1018d1e0)

**Comment by vzhuqin** [comment]
Fixed on ML.Net Model Builder: 16.9.1.2155501 (Main)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/1ee28082-76d8-4727-82fc-06425bd35697)
