### ISSUE TITLE
Manually changing version to unsupported version rewrites contents of MBConfig file

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#1653]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.0.2137701
 - Visual Studio Version: 16.10.4

**Describe the bug**

Manually changing versions using the JSON Editor in VS deletes my original MBConfig file and creates a new one. 

**To Reproduce**
1. Open MBConfig file with JSON editor
2. Change version to 2
3. Save MBConfig file
4. Error dialog opens
5. Dismiss error dialog
6. New MB Config file is created.

**Expected behavior**

The contents of my MBConfig file remain the same even if it can't be read or opened.

**Screenshots**
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/46974588/127233886-6a16f99c-b008-4f33-a259-7a7227da7b82.png)
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/46974588/127233888-13cdf3e3-88e7-4461-bbc7-961eaa285d27.png)

**Comment by LittleLittleCloud** [comment]
Still can't reproduce it and my mbconfig file is not re-written even if I increase its version number. Did you accidentally hit control-s when closing mbconfig window?

**Comment by JakeRadMSFT** [comment]
@luisquintanilla @LittleLittleCloud is this a difference in settings? 

@luisquintanilla do you have an auto-save setting enabled?

**Comment by beccamc** [comment]
@luisquintanilla Thoughts on this? Important to look into?

**Comment by luisquintanilla** [comment]
Not high priority for now. Since versions and their schema aren't publicly documented, I suspect manual edits will be rare. Let's close for now and investigate if users consistently report this being an issue.
