### ISSUE TITLE
File > Save As... does not create a new .mbconfig file

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1655]
**System Information (please complete the following information):**
 - Model Builder Version: 16.6.2.21333003
 - Visual Studio Version: 16.11.0 Preview 3.0

**Describe the bug**
User may want to rename or create a new variation of an experiments. For example, user might want to ignore some of the fileds and test their impact. User will select File > Save As... to create a copy of the existing configuration file. Currently, this does not work.

**To Reproduce**
1. Open any .mbconfig file
2. Select File > Save As...
3. Observe that:
3.1. Solution Explorer has a new entry, but the file is missing
3.2. name of the existing/open .mbconfig file remains
3.3. no new files are created in the project folder

**Expected behavior**
A new .mbconfig file should be created

**Additional context**
It may need to be considered if the new .mbconfig file requires retraining, or if the .zip and generated .cs files should be copies also under the new name.

**Comment by torronen** [comment]
It seems user can easily achieve the same by manually copying and pasting the file, then renaming it and manually adding to Visual Studio solution. With this workaround, the missing of "Save As..." functionality would seem to be mostly only a usability issue.

**Comment by beccamc** [comment]
Thanks Antti! @Briacht For support and priority

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud is there another interface we need to implement?

**Comment by LittleLittleCloud** [comment]
I need to take a look,, @torronen Does directly Control-C Control-V works?

**Comment by torronen** [comment]
@LittleLittleCloud yes, it works.

**Comment by beccamc** [comment]
@zewditu Can you take a look at this one?
