### ISSUE TITLE
Suggestion: Data file path should be saved as relative path when in same or subfolder

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1656]
**Describe**
It is convenient to save some datasets on same Git repo as the model builder configuration, especially for smaller projects.
Users will pull files to their chosen folder, and the physical path on local machine will often be different.

When user create a new Model Builder configuration (.mbconfig) and selects the file, the file path is always saved as an absolute path. If user will open the JSON contents and manually edit the path to a relative path the file is no longer found in model builder.

This makes it more difficult to share Model Builder projects together with the actual project through source control, or even external hard drives because they may map differently.

**To Reproduce**
1. Create any .mbconfig file
2. Select data file in the same folder. 
3. Save and open the contents of .mbconfig. 
4. Observe that the file path is an full aboslute path on the local machine.

**Expected behavior**
1) A relative path should be saved in .mbconfig if the file is in the same or subfolder. 
Consider, if also parent paths should be allowed always or until some depth (for example, only one level up)

2) Model builder should be able to search relative paths

**Comment by beccamc** [comment]
@Torronen, yes it absolutely should! This is a blocker for sharing mbconfig files between users/machines. We need to fit this into the work queue.

**Comment by beccamc** [comment]
Would like to get this into October... may need to push to November.

**Comment by luisquintanilla** [comment]
Options:

1. Save all paths as relative paths when the .mbconfig file is created. 
2. Save full path when .mbconfig file is created. Allow user to change relative path to absolute path. Would not require changes in Model Builder. AutoML service needs to add a check whether path is absolute / relative. No .mbconfig changes required.

**Comment by luisquintanilla** [comment]
+1 Option 2

**Comment by LittleLittleCloud** [comment]
@v-Hailishi 
To validate it, you just need to 
- create classification or regression experiment
- select a file as training data (not SQL)
- train the model
- close model builder, go to .mbconfig, and change the file path to relative path that related to your mbconfig file
- reopen model builder and retrain model again, the training should success.
- reopen .mbconfig afterwards and verify the file path still be relative path.
