### ISSUE TITLE
Running two experiments at same time will mix models

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1657]
**Describe the bug**
User may decide to run two experiments on same computer. Reasons could include that there is CPU cycles available, or multiple models are left to run over the weekend. 

At the moment, all models are saved to same folder. Model Builder A and Model Builder B may replace each others models. If best models for A is 10.zip and B has 20.zip it is possible both of them get wrong models from the other. More likely, however, is that the models from the one running late are replaces.

**To Reproduce**
1. Create two mbconfig files
2. Start training on both
3. Observe %temp%/AutoML-NNI folder and notice files get overwritten.

If "lucky", the following errors may be printed in output:
```
Trial 5 encounter error with message: The process cannot access the file 'C:\Users\Antti\AppData\Local\Temp\AutoML-NNI\5.zip' because it is being used by another process.
|6    FastTreeBinary                         0.5898   0.6200   0.4875    0.2844     497.7          6             |
Trial 7 encounter error with message: The process cannot access the file 'C:\Users\Antti\AppData\Local\Temp\AutoML-NNI\7.zip' because it is being used by another process.
|7    SdcaLogisticRegressionBinary           0.5915   0.5763   0.4638    0.0000     270.1          7             |
Trial 9 encounter error with message: The process cannot access the file 'C:\Users\Antti\AppData\Local\Temp\AutoML-NNI\9.zip' because it is being used by another process.
Trial 10 encounter error with message: The process cannot access the file 'C:\Users\Antti\AppData\Local\Temp\AutoML-NNI\10.zip' because it is being used by another process.

```

**Expected behavior**
Each model builder instance should use it's own temp folder (or it's own naming scheme). 
OR
Model Builder should not allow starting two experiments at the same time.

**Additional context**
High impact issue in my workflow. Could explain some of the very bad performances even if metrics show good values.

There is a risk that a "hidden" training run is happening either due to https://github.com/dotnet/machinelearning-modelbuilder/issues/1533 or because user had closed a .mbconfig file which was doing the training.

If separate temp folders are used, could it also help fix https://github.com/dotnet/machinelearning-modelbuilder/issues/1535 ?

**Comment by LittleLittleCloud** [comment]
The older model will be replaced by new one because all model has a fix-format name.. We should create different sub-folder to save training artifacts for different experiments

**Comment by vzhuqin** [comment]
Not repro this issue on latest main build: 16.7.2.2141201
Now each experiment has its own folder under %temp%/AutoML-NNI
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/6c98a5d7-db6e-45de-8e3c-c1dd651e074e)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2a90fc27-e72b-4546-8f5b-65dc908bc148)

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/46474cd7-4deb-4091-a289-58d2a850de99)
