### ISSUE TITLE
Update Model Builder version to 1.6.0 to support ARM devices

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#1658]
As of 1.6.0, ML .NET offers support for ARM devices. Currently Model Builder trains models using version 1.5.5 which doesn't have ARM support. Therefore, users looking to use models trained with Model Builder on ARM devices (i.e. mobile apps with Xamarin) can't. Instead, they have to manually:

1. Create a new console application to retrain the model
2. Copy training pipeline into console application
3. Update ML .NET packages to 1.6.0
4. Retrain the model
5. Copy the retrained model to their application for ARM devices.

**Comment by vzhuqin** [comment]
Verified this on latest main build: 16.7.2.2141201
Microsoft.ML has been updated to 1.6.0
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/5ddd8255-3be0-463b-a7be-1558288d0a2c)
