### ISSUE TITLE
There is no the selection state of Limited scenarios.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1659]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.7.0.2137701 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.3
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Scenario page
- Clear description of the problem:  
Problem 1. When you choose one of the limited scenarios, it jumps to Consume page, then back to Scenario page, find that there is no the selection state of the limited scenario.
Problem 2. Select one supported scenario, then return to select one limited scenario, and then back to Scenario page, find that the supported scenario is selected instead of the limited scenario. I was confused about this and thought I had made a mistake, so I tried a few more times, but the result was still the same.  

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Choose Anomaly detection from Limited scenarios, it jumps to Consume page;
5. Then back to Scenario page, find that there is no the selection state of Anomaly detection scenario;
6. Select Text classification from supported scenarios, then return to re-select Anomaly detection scenario;
7. And then back to Scenario page, find that Text classification scenario is selected instead of Anomaly detection scenario. 

**Expected behavior**
1. The limited scenario should have selection state.
2. If problem 1 is expected ,  for problem 2, it should show no scenario is selected instead of the supported scenario is selected. 

**Screenshots**
![Selected state](https://user-images.githubusercontent.com/81727020/127451382-b86c58f2-68bf-42e0-b51e-1d5ff93c6ea7.gif)

**Additional context**

**Comment by beccamc** [comment]
It's difficult to support selection state for limited scenarios. Our selection state is driven by the mbconfig file, and limited scenarios there is no associated mbconfig state. I considered this too low of priority to implement a special state solution. 

Good find Qin! I'm closing this as "Wont fix" due to it being low priority. @Briacht to comment if this is high enough priority. Thank you!
