### ISSUE TITLE
Transfer issues from AutoML repo

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-modelbuilder#1665]
Of the open issues in the machinelearning-automl repo, these are still relevant:
* [Check for NA values in Boolean columns machinelearning-automl#420](https://github.com/dotnet/machinelearning-automl/issues/420)
* [Display Feature Importance machinelearning-automl#409](https://github.com/dotnet/machinelearning-automl/issues/409)
* [[CLI] Need to show additional metrics for Multi-class Classification task (Log Loss and Log Loss Reduction) machinelearning-automl#404](https://github.com/dotnet/machinelearning-automl/issues/404)
* [[CLI] Generate Test project with bulk predictions (predictions.csv) and even plotting machinelearning-automl#402](https://github.com/dotnet/machinelearning-automl/issues/402)
* [[CLI] Generate multiple models machinelearning-automl#401](https://github.com/dotnet/machinelearning-automl/issues/401)
* [[CLI] [AutoML] Manual early stopping (Key pressed and best current model generated) machinelearning-automl#399](https://github.com/dotnet/machinelearning-automl/issues/399)
* [[CLI] [AutoML API] Auto early stopping when no significant improvements to be gained anymore machinelearning-automl#398](https://github.com/dotnet/machinelearning-automl/issues/398)
* [Out-of-process run context machinelearning-automl#397](https://github.com/dotnet/machinelearning-automl/issues/397)
* [Cache trained sub-pipelines between runs machinelearning-automl#396](https://github.com/dotnet/machinelearning-automl/issues/396)
* [Cache featurized dataset before trainer machinelearning-automl#395](https://github.com/dotnet/machinelearning-automl/issues/395)
* [Set NumberOfThreads in each Trainer machinelearning-automl#394](https://github.com/dotnet/machinelearning-automl/issues/394)
* [Single Node Parallel Sweeping machinelearning-automl#393](https://github.com/dotnet/machinelearning-automl/issues/393)
* [Heuristics for high number of classes machinelearning-automl#392](https://github.com/dotnet/machinelearning-automl/issues/392)
* [Throw Error for Binary Classification w/ Wrong Label Type machinelearning-automl#386](https://github.com/dotnet/machinelearning-automl/issues/386)
* [[AutoML] [CLI] Add automatic label leakage detection machinelearning-automl#370](https://github.com/dotnet/machinelearning-automl/issues/370)
* [[CLI] Detect a new version of the Global Tool package and warn the user machinelearning-automl#360](https://github.com/dotnet/machinelearning-automl/issues/360)
* [Delete cached models files when cache directory is temp (ie it isn't changed) machinelearning-automl#353](https://github.com/dotnet/machinelearning-automl/issues/353)
* [Design issue: Stacked model support from CLI machinelearning-automl#340](https://github.com/dotnet/machinelearning-automl/issues/340)
* [Auto-convert non-float labels to float for regression AutoML experiments machinelearning-automl#320](https://github.com/dotnet/machinelearning-automl/issues/320)
* [Allow/disallowlist trainers from CLI machinelearning-automl#284](https://github.com/dotnet/machinelearning-automl/issues/284)
* [BinaryClassification learners fail  machinelearning-automl#255](https://github.com/dotnet/machinelearning-automl/issues/255)
* [Detect label leakage and warn/handle machinelearning-automl#214](https://github.com/dotnet/machinelearning-automl/issues/214)
* [Numerical columns are never inferred as categorical even though they are.  machinelearning-automl#202](https://github.com/dotnet/machinelearning-automl/issues/202)
* [Fix the error message to be more meaningful -> Schema mismatch for label column '': expected R4, got Bool' machinelearning-automl#158](https://github.com/dotnet/machinelearning-automl/issues/158)
* [Investigate and fix code that adds "auto" to hyperparameter settings machinelearning-automl#150](https://github.com/dotnet/machinelearning-automl/issues/150)
* [[AutoML] Include/exclude Cache in pipeline depending on size of datasets and tries machinelearning-automl#147](https://github.com/dotnet/machinelearning-automl/issues/147)
* [Rev transform experts to output columns with new names != original names machinelearning-automl#144](https://github.com/dotnet/machinelearning-automl/issues/144)
* [Test name transform expert machinelearning-automl#143](https://github.com/dotnet/machinelearning-automl/issues/143)
* [Investigation: Alternative methods of accessing the MLContext machinelearning-automl#127](https://github.com/dotnet/machinelearning-automl/issues/127)
* [[CLI] Do not set numFolds with a hard-coded value for the generated code for Cross-Validation? (Binary-Classification and Regression) machinelearning-automl#109](https://github.com/dotnet/machinelearning-automl/issues/109)
* [Validate Label by Task Type machinelearning-automl#91](https://github.com/dotnet/machinelearning-automl/issues/91)
* [Have calibration added to all binary classifiers. machinelearning-automl#90](https://github.com/dotnet/machinelearning-automl/issues/90)
* [Implement ToString() method in generated classes by CLI tool machinelearning-automl#78](https://github.com/dotnet/machinelearning-automl/issues/78)
* [Accept columns of type I4, and other types that are convertible to R4 machinelearning-automl#58](https://github.com/dotnet/machinelearning-automl/issues/58)
* [Sweep column purposes machinelearning-automl#54](https://github.com/dotnet/machinelearning-automl/issues/54)
* [Simplify AveragedPerceptron{iter=10}  machinelearning-automl#42](https://github.com/dotnet/machinelearning-automl/issues/42)
* [Respect ColumnPurpose.Weight machinelearning-automl#37](https://github.com/dotnet/machinelearning-automl/issues/37)

A while back, I was asked to transfer issues from the old machinelearning-automl repo. To do that, I think the repo will have to temporary be set to public (all code is already public, as it was replicated with history to the main https://github.com/dotnet/machinelearning repo). Since it's set as private, the public dotnet/machinelearning-modelbuilder (and dotnet/machinelearning) do not show as transfer targets. Once set to public (which is ok to do), the issues can be transferred.

Alternatively, we can manually recreate the issues in this repo (copy/paste to new issues here).

**Comment by justinormont** [comment]
@JakeRadMSFT : Do you have the ability to temporarily set the repo as public? It may be only the dotnet owners.

**Comment by JakeRadMSFT** [comment]
@justinormont I don't have that ability.
