### ISSUE TITLE
System out of Memory Exception during Runtime with ML.net 16.6.1.2131904 (Suspected Memory Leakage)

### ISSUE THREAD

**Issue by rahulgorai** [dotnet/machinelearning-modelbuilder#1666]
**System Information:**
 - **Model Builder 16.6.1.2131904**
 - Visual Studio Version 16.10.4

**Describe the bug**
- I have trained Model for Image Classification using 2000 Image Sets with Right and Wrong Classification after I deployed the model, with each iteration of the Image Prediction Process the Memory Usage increases and after a **'n'** no of Iteration the system runs into "System out of Memory Exception"

### Clear description of the problem:
I am building an application that will constantly take images from a camera and classify the images as wrong / right using the pretrained prediction model (Built using **ML Model Builder 16.10.4**), during both development and deployment it is noted that with each iteration of the Infinity loop that captures Image from the camera the Memory Graph Shoots up by 100 MB (Approximate Value) and finally the system crashes after certain time due to Out of Memory Exception. 

In order to have a better understanding I created a separate application with a Normal File Browser where the infinity loop was avoided, and the behavior was same, every time I uploaded a Image, the RAM / Memory Usage shoots up by 100 MB (Approximate Value)

However when I am working with **ML Builder Version 16.1.0.2027905** we don't experience any of such issues, and the system is running stable and no such memory leakage detected. I have worked on with ML Builder Version 16.1.0.2027905 with approximate 1 Lakh Images in an infinite loop for over 36 hours runtime and the system is completely stable.

I have tried with IDisposable(), GC.Collect() but no Improvement or Drop in Memory Usage Noted.

**To Reproduce**
1. Train an Image Prediction Model using Model Builder 16.6.1.2131904
2. Create an Application with Simple File Browser to run a prediction algorithm that will show the Output as Right or Wrong with Prediction Percentages
3. Every time you run the Process you will see a spike in memory usage

**Expected behavior**
The Increase in Memory Usage in each Iteration should be stopped.

**Screenshots**
The below Image was generated using Performance Profiler in Visual Studio with 2600 Images. We can see that GC is fired but the Memory Consumption is constantly increasing.

![image](https://user-images.githubusercontent.com/12544018/127962999-febf7001-f681-4681-8608-85ddd9abdb17.png)

**Sample Code**

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace MLModel
{
    public partial class Form1 : Form
    {
        string rightImg = AppDomain.CurrentDomain.BaseDirectory + "right";
        string wrongImg = AppDomain.CurrentDomain.BaseDirectory + "wrong";
        string rawImage = @"D:\rowImage";
        public Form1()
        {
            InitializeComponent();
            ImgSorting();
        }
        protected void ImgSorting()
        {
            try
            {
                if (!Directory.Exists(rightImg))
                {
                    Directory.CreateDirectory(rightImg);
                }
                if (!Directory.Exists(wrongImg))
                {
                    Directory.CreateDirectory(wrongImg);
                }
                DirectoryInfo ds = new DirectoryInfo(rawImage);
                int c = ds.GetFiles().Count();
                while (c > 0)
                {
                    DirectoryInfo di = new DirectoryInfo(rawImage);
                    string firstFileName =
                    di.GetFiles()
                    .Select(fi => fi.Name)
                    .FirstOrDefault();
                    string filePath = rawImage + "\\" + firstFileName;

                    var input = new MLModel1.ModelInput();
                    input.ImageSource = filePath;
                    MLModel1.ModelOutput resulty = MLModel1.Predict(input);
                    if (resulty.Prediction.ToString() == "Wrong")
                    {
                        string newcropFilePath = Path.Combine(wrongImg, firstFileName);
                        if (File.Exists(filePath))
                        {
                            File.Move(filePath, newcropFilePath);
                        }
                    }
                    else
                    {
                        string newcropFilePath = Path.Combine(rightImg, firstFileName);
                        if (File.Exists(filePath))
                        {
                            File.Move(filePath, newcropFilePath);
                        }
                    }                    
                   
                }
            }
            catch (Exception x)
            {
                throw x;
            }
        }
    }
}

**Comment by sudiptaBGorai** [comment]
Same problem occur with me.    Please help...

**Comment by cludogithub** [comment]
I face this issue for a loop. Inside this loop I use GC also. But still the issue is there. Please let me know how to solve this. Thank you in advance..

**Comment by sbose768** [comment]
I am experiencing similar issues with Out of Memory Exception with Build 16.6.1.2131904. After 15 - 20 mins of running the system consumes entire 16 GB of my RAM and crashes

**Comment by beccamc** [comment]
@LittleLittleCloud Can you please take a look at this?

**Comment by LittleLittleCloud** [comment]
Hi @sbose768 @rahulgorai 

Thanks for ring this bell. I'm able to reproduce it on my side. Although I don't know the actual cause, this might be related to the creation of MLContext/PredictionEngine every time `Predict` gets called.

One workaround is to use lazy-loaded PredictEngine, which should resolve the memory leak as well as increase predicting speed.

#1638 

This bug is more likely in ML.Net framework so I will transfer this issue to their repo, let us know if there's any questions.
