### ISSUE TITLE
The icons are incomplete or unclear in Blue theme.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1667]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.7.2.2140201 (Main Branch)
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 2.1
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Blue theme
- Clear description of the problem: Some icons are incomplete or unclear on Scenario, Environment, Data pages.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 Preview start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Set to Blue color theme from Tools>Options>General;
4. Add model builder by right click on the project;
5. Find that many icons on Scenario, Environment, Data pages are incomplete or unclear 

**Expected behavior**
All icons should be complete and appear clear in blue theme.

**Screenshots**
Scenario page:
![image](https://user-images.githubusercontent.com/81727020/127966628-83a39318-4db2-493c-bd8d-1d797416b9d2.png)

Environment page:
![image](https://user-images.githubusercontent.com/81727020/127966864-80a47a49-ff01-40bb-8856-f40dff780fbc.png)

Data Page:
![image](https://user-images.githubusercontent.com/81727020/127967322-f303e8f5-4f5e-4bc1-b6ab-e1119ffe380b.png)

**Additional context**
This issue not occurs on dark or light theme.

**Comment by LittleLittleCloud** [comment]
We'd better solve this before next insertion

**Comment by LittleLittleCloud** [comment]
Dev17 looks good

**Comment by vzhuqin** [comment]
Not repro this issue on:

- VS2022: Microsoft Visual Studio Enterprise 2022 main (64-bit)
Version 17.0.0 Preview 4.0 [31631.462.main]
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9b5d62f4-b872-4c73-ab0f-fce966f29b1c)
- ML.NET Model Builder: 16.7.3.2143002
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/1dccbdd6-0a4e-4634-bcb4-200ced74c310)

![1667-2_Fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3ed5f35b-6b70-4bf8-a45f-033d94dcdbb8)
