### ISSUE TITLE
Suggestion: The "Train in Azure" card title is horizontally aligned with the other two cards. 

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1675]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.7.2.2140201 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.4
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Next steps page
- Clear description of the problem: Not sure if this is by design, but i still think the alignment of the cards is as pleasing to the eye as the scenario page. 

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Image classification or Object detection scenario to complete training;
5. Navigate to Next steps page, see that the "Train in Azure" card title is not horizontally aligned with the other two.

**Expected behavior**
Please see the screenshot of Scenario page below, hope that the title of "Train in Azure" card is horizontally aligned with the other two cards. 

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/128135136-ab651586-a29a-41de-9534-0f692d64ed79.png)

Scenario page:
![image](https://user-images.githubusercontent.com/81727020/128135559-e8c9bf6c-ed50-4174-8d97-0f261e0464fd.png)

**Additional context**

**Comment by luisquintanilla** [comment]
This is not part of the model building experience, and not a high priority. Closing for now.
