### ISSUE TITLE
The predicted results in Output box is incomplete.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1676]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.7.2.2140201 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.4
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Output 
- Clear description of the problem: In Output box, the predicted value is incomplete for Value prediction and recommendation scenarios; no display predicted results for Image classification and Object detection scenarios

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Value prediction scenario to complete training;
5. Navigate to Evaluate page, click "Predict" button;
6. Looking at the Output box, found that only the label column (fare amount:) is displayed for the predicted value. 

**Expected behavior**
In Output box, display the same predicted results (fare_amount: 16.31) as the Evaluate page. 

**Screenshots**
Value prediction:
![image](https://user-images.githubusercontent.com/81727020/128161921-dcc1aff4-809e-4d4f-a51d-a1e5d849cd0a.png)
Recommendation:
![image](https://user-images.githubusercontent.com/81727020/128161956-212ec046-5de2-4f69-bc44-4b76e58e41f5.png)
**Additional context**
For Image classification and Object detection scenarios, no print the predicted results in Output box, could you help to confirm if this is an issue?
Image classification:
![image](https://user-images.githubusercontent.com/81727020/128162255-8e12a62d-7b19-4a57-a1c0-cd1a0462614f.png)

Object detection:
![image](https://user-images.githubusercontent.com/81727020/128162284-d75aa6a1-92df-430b-9db6-697b2610531d.png)

**Comment by luisquintanilla** [comment]
Issue is not a priority. Closing for now. Console output is supplementary to the main UI experience.
