### ISSUE TITLE
Cannot Add machine learning in VS2019 if installed VS2022.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1678]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.7.2.2140201 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.4
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 2.1
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Add Machine Learning in VS2019
- Clear description of the problem: This OS installed VS2022 and VS2019, the model builder is the latest main build: 16.7.2.2140201, then if you want to use VS2019 to add Machine Learning, pop up Microsoft Visual Studio dialog said: The 'ModelBuilderPackage' package did not load correctly. 

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add>Machine Learning by right click on the project;
4. Pop up Microsoft Visual Studio dialog said: The 'ModelBuilderPackage' package did not load correctly. 
![image](https://user-images.githubusercontent.com/81727020/128309198-83abd2de-d2f2-4876-94e0-3f339b5c63f1.png)
ActivityLog.xml:
[ActivityLog.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/6936842/ActivityLog.zip)

5. Restarting VS2019, this issue still occurs;
6. Also tried to uninstall and reinstall VS2019, then updated model builder to latest main build;
![image](https://user-images.githubusercontent.com/81727020/128310503-8d00c979-128a-48d0-84e2-6bc3d56d294d.png)
Updated Log:
[dd_VSIXInstaller_20210805000540_1ad0.log](https://github.com/dotnet/machinelearning-modelbuilder/files/6936821/dd_VSIXInstaller_20210805000540_1ad0.log)

7. Open Manage Extensions, find that the Installed ML.NET Model Builder is for VS2022;
![image](https://user-images.githubusercontent.com/81727020/128309685-1d1b5318-1bbe-4c8c-9289-8bcfc46486fd.png)

8. Navigate to Online>Model Builder find the model builder for VS2019 is not installed;
![image](https://user-images.githubusercontent.com/81727020/128310794-211becfa-4ea6-4e52-9f19-08559ede1a73.png)
9. Click "Download" button to install the model builder for VS2019;
10. Pop up the VSIX Installer message that this extension is already installed.
![image](https://user-images.githubusercontent.com/81727020/128310957-4ea0f45a-4098-4a8d-96b8-ddb4d6a9fb5b.png)

**Expected behavior**
VS2022 should not affect the functionality of model builder in VS2019.

**Additional context**
Not affect adding Model Builder in VS2022.

**Comment by LittleLittleCloud** [comment]
Can't reproduce it somehow, the update works normal on my computer, can you try again..
![image](https://user-images.githubusercontent.com/16876986/128759084-a8502170-e5ff-4933-995c-1a6c6cef7c45.png)

**Comment by vzhuqin** [comment]
Yes, can add machine learning in VS2019 with latest main build and installed VS2022.

**Microsoft Visual Studio Enterprise 2019 Version: 16.11.0**
![image](https://user-images.githubusercontent.com/81727020/129150731-0714cce2-244d-408f-aea1-a61c79ead846.png)
**ML.NET Model Builder version: 16.7.2.2141201**
![image](https://user-images.githubusercontent.com/81727020/129150202-dd2b7e4f-ada9-4eb1-8cbd-4052e8901b1b.png)


**But** I met another issue in VS2022 , cannot update model builder to current latest main build: 16.7.2.2141201, I'm not sure whether this behavior affects the validation result of this issue, could you help to take a look?

**Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version: 17.0.0 Preview 3.0**
![image](https://user-images.githubusercontent.com/81727020/129150385-b86d2352-1c41-4fad-9061-58a9ac3e8def.png)
**Manage Extensions:**
![image](https://user-images.githubusercontent.com/81727020/129150466-07cb02ec-3c95-47e2-979d-d0d87122ad5a.png)
![image](https://user-images.githubusercontent.com/81727020/129150586-b6221d83-08f2-4c3d-98f9-c610f3fac23c.png)
**Added Main build under Additional Extension Galleries:**
![image](https://user-images.githubusercontent.com/81727020/129151182-cfe0e914-ff1a-4bf7-a428-2484a5d5c3e8.png)

**Comment by vzhuqin** [comment]
Can repro this issue on latest main build: 16.7.2.2141802, please see below GIF.
![Repro-1678-2.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3f0dba7f-abc1-4473-86e6-51ff4e549de1)
Steps:
1. Install  VS2022 from [VS build >= 31618.209](https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build/results?buildId=5106487&view=results), and  update Model Builder to latest main build: 16.7.2.2141802 in Manage Extensions>Update box;
3. Open VS2019, add model builder by right click on C# Console App (.NET Core) project;
5. Prompt below dialog that: The 'ModelBuilderPackage' package did not correctly.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/8988e47a-948c-43aa-9a8f-80482be28ede)
6. Open Manage Extensions, find the installed ML.Net Model Builder is for 2022 instead of 2019.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/d2cfce01-e86f-4a7d-93f2-bcc85a62b7b3)

**Comment by LittleLittleCloud** [comment]
I still have trouble reproducing it
![image](https://user-images.githubusercontent.com/16876986/130522866-8d811f03-2d2f-4654-a406-dcf31a1831cf.png)


@beccamc @JakeRadMSFT @zewditu maybe give it a try and validate it?

**Comment by vzhuqin** [comment]
@LittleLittleCloud  I can repro this issue on latest main build: 16.7.4.2145201
1. This machine itself has already installed VS2022 with latest main model builder, see below screenshot:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3e0e62ba-fb16-44c1-96ad-e3e0b77ca08c)

2. Then download + install VS2019 version 16.11.2 and update the model builder to latest through Manage Extensions;

3. Open VS2019, find cannot add model builder and the installed ML.NET Model Builder is for VS2022, see below screenshots:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0be03f05-1b69-4fec-98af-95af8106399e)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/083678b8-923c-4918-9ddb-27b84731c5b0)

**Comment by beccamc** [comment]
Moving back to committed as Bri is also seeing this problem

**Comment by LittleLittleCloud** [comment]
The log 
```
    <description>CreateInstance failed for package [ModelBuilderPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{A1473B8C-F40E-4509-8A84-66BBA12B3E7F}</guid>
```

Indicates that VS2019 can't create an instance of ModelBuiler because it can't find file or assembly Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0. Which means that the model builder extension installed on VS2019 is for VS2022. The error is an expected behavior as the installed MB is for VS2022.

I'm suspecting that something wrong when @vzhuqin upgrade model builder. As the installed model builder on VS2019 was for VS2022 according to previous conversation, simply upgrading MB extension from extension manager won't fix this issue as the updated extension will still be for VS2022 only.

@vzhuqin Can you **UNINSTALL** ModelBuilder completely on VS2019 and then check two things
- try reinstall from main branch through extension manager, and see if the correct model builder is installed. You can confirm it through description, which has "for VS2019" as suffix. This is to verify that extension manager can download the correct extension after the recent feed update.
- try to install vsix directly by downloading this [vsix](https://devdiv.visualstudio.com/_apis/resources/Containers/8635926/VSSetup_Release?itemPath=VSSetup_Release%2FMicrosoft.ML.ModelBuilder.Gallery.Dev16.vsix) and double click. This is to verify that ModelBuilder VS2019 can work in VS2019.

**Comment by LittleLittleCloud** [comment]
Update

In my case, VS2019 installs ModelBuilder for VS2022 even when VS2019 ones is selected
![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/674fe4fe-65e4-4dce-ad71-7cd2e1b59818)

So it could be the regression of recent feed update in VS

**Comment by LittleLittleCloud** [comment]
Update

Install from vsix works on VS2019

![image](https://user-images.githubusercontent.com/16876986/132888219-66f8ae4b-8874-465f-8e37-0ef291ee34bf.png)

**Comment by vzhuqin** [comment]
![image](https://user-images.githubusercontent.com/81727020/133016367-5d578846-b022-4ecd-9cd5-129689317a96.png)

@LittleLittleCloud  sorry for the delay. 

- Try 1:

1. I always met error during uninstall Model builder in VS2019, so prepared one machine which only installed VS2022, then installed VS2019: 16.11.2 .
2. Update model builder for 2019 through Manager Extensions.
![image](https://user-images.githubusercontent.com/81727020/133017109-662e2e95-c5ca-422b-98ab-950a12602a17.png)
3. **Open VS2019, see model builder for 2019 is installed.**
![image](https://user-images.githubusercontent.com/81727020/133017480-b25a2946-f91b-4ed1-acf1-2e99bde679cb.png)
4. **Open VS2022, find the model builder for 2022 needs to update, so I update model builder for 2022 through Manager Extensions, open VS2022 after updated, see error: the installed ML.NET Model builder is for VS2019.** I doubt whether cannot update model builder from Main through Manage Extensions if the machine installed VS2019 and VS2022, could you help to see if which step is wrong?
![image](https://user-images.githubusercontent.com/81727020/133018464-914294f9-85a1-465b-a496-7c669ae8c6b6.png)
![image](https://user-images.githubusercontent.com/81727020/133018486-a57b6b1e-d2ec-43dd-8886-9a0cdcaa5165.png)
![image](https://user-images.githubusercontent.com/81727020/133018456-3b94f7f5-6a5e-44f1-a1e6-c0790cc5f85a.png)

Please give me some time to do  **Try 2** , will update the result later.

**Comment by vzhuqin** [comment]
Update:
As meet install trouble for VS2022 int preview, so installed VS2022 preview 4.0 to do "try 2".

**Try 2:**
1. Prepare one clean machine to install VS2022 and VS2019;
![image](https://user-images.githubusercontent.com/81727020/133212315-02a6120c-8f0f-4690-9571-d5d8b2d7ac5a.png)
![image](https://user-images.githubusercontent.com/81727020/133183742-b6052e6d-9580-481f-a46e-e89807e2ddef.png)

2. Download and install latest: 16.7.4.2146301 Microsoft.ML.ModelBuilder.Gallery.Dev16 from [vsix](https://devdiv.visualstudio.com/_apis/resources/Containers/8670182/VSSetup_Release?itemPath=VSSetup_Release%2FMicrosoft.ML.ModelBuilder.Gallery.Dev16.vsix) ;
3. **Open VS2019, see the installed model builder is correct, it is for VS2019;**
![image](https://user-images.githubusercontent.com/81727020/133212388-d1221935-f0e5-46ca-b269-c52e104490a1.png)

4. Open VS2022, update model builder for VS2022 through Manage Extensions;
![image](https://user-images.githubusercontent.com/81727020/133214414-388b69e8-4cb1-4d52-8ea9-6ba96ba7cf61.png)

**5. Issue: Find that the installed model builder is for VS2019.**
![image](https://user-images.githubusercontent.com/81727020/133213241-e7b81669-753d-4353-8c24-73125ad4b597.png)

**Comment by LittleLittleCloud** [comment]
It's probably fixed in latest VS release doesn't it? @JakeRadMSFT

**Comment by beccamc** [comment]
@vzhuqin Can you try this again and see if it still repros?

**Comment by vzhuqin** [comment]
Hi @beccamc , yes, i can repro this issue on latest main: 16.12.1.2206302
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4578a3b2-5859-4b08-9186-70340df748f5)
- Microsoft Visual Studio Enterprise 2019 Version 16.11.9
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/40665321-2d9d-4745-bb2c-d9664135f980)

- Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.5
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/310e3a31-7cb3-43be-9cdd-6040c22492bf)

**Comment by luisquintanilla** [comment]
This might be because of the private feed. Customers don't use the private feed so it might not be an issue for them. Let's validate with the package from the VS Marketplace.

**Comment by luisquintanilla** [comment]
@v-Hailishi can you please validate whether this is an issue. See comment above.

**Comment by v-Hailishi** [comment]
@luisquintanilla Following are the validate steps and results:
1. Install VS2022 Enterprise 17.1.3 with ML.NET Model builder version 16.7.4.2151101 & VS2019 Enterprise 16.11.11 with ML.NET Model builder(Preview) version 16.1.0.2027905. 
    **At this time, machine leaning can be added successfully for both VS2022&2019.**
![image](https://user-images.githubusercontent.com/99375895/162364446-99db03a7-ef60-40bc-95f6-ed2a2bb1f5e9.png)
![image](https://user-images.githubusercontent.com/99375895/162366863-aa2074ca-e969-44bf-9b67-c5a7863f16ce.png)
![image](https://user-images.githubusercontent.com/99375895/162367565-ba4a3b4c-4abd-427a-b4ed-ac9ac6a07e3a.png)

2. Update ML.NET Model builder version to **16.13.1.2210302** for VS2022 from the VS Marketplace.
    Update ML.NET Model builder version to **16.13.1.2210301** for VS2019 from the VS Marketplace.
    **At this time, machine leaning also can be added successfully for both VS2022&2019.**
![image](https://user-images.githubusercontent.com/99375895/162368244-d9ba8a09-6154-49da-9705-274f89deac81.png)
![image](https://user-images.githubusercontent.com/99375895/162368385-26a74ddf-1403-4cf7-9983-09a7de2228f3.png)

3. Add private feed [https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml](https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml) (Main branch) to VS2022&2019
![image](https://user-images.githubusercontent.com/99375895/162370216-54459677-abcd-4086-b769-e120cfe46ea3.png)

4. Update ML.NET Model builder version to the latest main branch 16.13.5.2220401 for VS2022
    **At this time, machine leaning can be added successfully for VS2022**
![image](https://user-images.githubusercontent.com/99375895/162370315-6c38462f-9e68-4a66-a20d-570559b32c8f.png)

5. Update ML.NET Model builder version to the latest main branch 16.13.5.2220401 for VS2019 from the private update.
    **At this time, cannot add machine leaning with error for VS2019. Besides, you can fine that ML.NET Model builder 2022 is installed in VS2019. **
![image](https://user-images.githubusercontent.com/99375895/162370406-b8e90d99-09da-4be5-bc88-7e9118650de1.png)
![image](https://user-images.githubusercontent.com/99375895/162371909-3afd76cd-4c2c-45df-865f-fa2befb17c33.png)
![image](https://user-images.githubusercontent.com/99375895/162372381-24f5d910-a021-4806-adfe-8473f7f5f58b.png)

**Comment by beccamc** [comment]
If I am understanding this correctly the problem will only happen if you're also subscribed to our private feed. In this case, are we okay marking this as fixed? @luisquintanilla

**Comment by luisquintanilla** [comment]
cc: @JakeRadMSFT

**Comment by luisquintanilla** [comment]
@JakeRadMSFT to look into it. It might only be an issue with private feed.

**Comment by beccamc** [comment]
Confirmed that this is related to private gallery. Closing as fixed.
