### ISSUE TITLE
The names of codebehind files are not updated after renamed of  .mbconfig file.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1679]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.7.2.2140201 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.4
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Rename model builder on Net472 project
- Clear description of the problem: On .netcore project, the names under model builder will be updated after renamed the model builder, but net472 will not.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Framework) project template with .Net Framework 4.7.2;
3. Add model builder by right click on the project;
4. Select Text classification scenario to complete training;
5. Click "Reload All" on the popped File Modification Detected dialog;
6. Save and close the model builder;
7. Under Solution Explorer, rename the model builder from "MLModel1.mbconfig" to "Advanced_MLModel1.mbconfig", see that the names of .consumption.cs, .training.cs, .zip files are not updated.

**Expected behavior**
The names under model builder are updated after renamed the model builder on Net472 project.

**Screenshots**
Net472：
![Net472rename2](https://user-images.githubusercontent.com/81727020/128328976-6dbad4ab-13e0-462c-95e7-bc17fa266286.gif)

.NetCore:
![NetCoreRename2](https://user-images.githubusercontent.com/81727020/128328991-409406de-24cb-49f1-92c4-3e58de574bc8.gif)

**Additional context**

**Comment by LittleLittleCloud** [comment]
#1446

**Comment by zewditu** [comment]
I just noticed that this issue is a little different from [1446]("https://github.com/dotnet/machinelearning-modelbuilder/issues/1446").
For this issue,  the rename has to be made after code-behind files are generated and all file names behind the .mbconfig should be updated accordingly.

**Comment by vzhuqin** [comment]
not repro this issue on main: 16.12.1.2206302
![1679_Fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/128a1c45-100d-44ad-b64f-4f18579dccf1)
