### ISSUE TITLE
[Design] Image Classification

### ISSUE THREAD

**Issue by greazer** [dotnet/machinelearning-modelbuilder#168]

**Comment by iampiyusharora** [comment]
Design Spec:

https://www.figma.com/file/DuzHSTi1JWHK6m1fkSJjvFM8/ML.NET-Deep-Learning?node-id=408%3A0

Please feel free to reach out to me if you have any questions.

**Comment by JakeRadMSFT** [comment]
Figma:

https://www.figma.com/file/DuzHSTi1JWHK6m1fkSJjvFM8/ML.NET-Deep-Learning?node-id=408%3A0
