### ISSUE TITLE
A11y_.NETWPF_ExpenseItIntro_View Expense Report_Zoom: When zooming to 200% the "names" title and the view button is getting truncated.

### ISSUE THREAD

**Issue by Blessymanna** [dotnet/machinelearning-modelbuilder#1681]
[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

GitHubTags:#A11ySev2;#A11yTCS;#A11yWCAG;#DesktopApp;#WCAG1.4.4;#DesktopApp;#Win10;#BM-.NetCore(WinFormsAndWPF)-Win32-July2021;#.NET Core;

### Environment details:
Application Name: .NET Core WPF
Microsoft .NET Core SDK Version 6.0.100-rc.1.21380.2
Windows Version: Windows10
Microsoft Visual Studio Enterprise 2022
Version 17.0.0 Preview 3.0 [31529.384.main]
### Repro Steps
 

1. Launch VS 2019 Int Preview
2. Navigate to Getting started and right click on the Expense it intro and click on build
3. Then right click on Expense it Intro then Click on Debug-->Start New Instance. 
4. Check after zooming to 200%, the names title and the view button is visible as it is or not.
### Actual Result:
After zooming to 200%, the names title and the view button is getting truncated.
### Expected Result:
After zooming to 200%, the names title and view button should not get truncated. 
### User Impact:
The users with low vision, not able to view the complete information.

**Comment by zewditu** [comment]
@Blessymanna is this a Model Builder issue?

**Comment by Blessymanna** [comment]
Closing the issue as logged in incorrect repository
