### ISSUE TITLE
The X of the project name isn't increase if there is a + in Mode Builder.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1683]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.7.2.2140201 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.4
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Adding an additional sample project
- Clear description of the problem: If there is a + in model builder name, then on Consume page, click "Add again" to add an additional project, the X in project name isn't increase.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Name the model builder "SQL+ValuePrediction_MLModel1.mbconfig";
5. Select Value prediction scenario, Local (CPU) environment;
6. Input SQL Server data;
7. Click "Start train" to complete the training;
8. Navigate to Consume page, Click "Add to solution" to add one ConsoleApp project with name "SQL+ValuePrediction_MLModel1_ConsoleApp1";
9. Click "Add again", find the project name is the same, the X isn't increase.

**Expected behavior**
According to #1330: "If adding an additional sample we should increment the X". The name of Model Builder should not affect the experience.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/128655104-8f6f7e37-b563-4014-8145-516dd371e0bc.png)

**Comment by LittleLittleCloud** [comment]
@zewditu  can you take a look?

**Comment by LittleLittleCloud** [comment]
And I believe `+` is not a legal character in project name?

**Comment by zewditu** [comment]
@LittleLittleCloud  in VS new project dialog it allows `+` in the project name, we are following the VS user experience

**Comment by romalpani** [comment]
Since "Add to solution" is a parallel to "Add new project", the validations should be the same as adding any other project through NPD. I am not sure I understand why the "x" is not incrementing if you hit "add again".

**Comment by zewditu** [comment]
VS protects as from the following characters and special case values 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/3ea88809-8876-4e1e-b019-87ec4b6817a8)

I think  we need to do our own sanitization for ModelBuilder.mbconfig file name because they will be used as part of project names in generating sample projects

**Comment by vzhuqin** [comment]
Not repro this issue on main build: 16.7.2.2141801.
The name of sample project has used '_' by default even if the model builder name has "+" or other hyphen. 
Now click "Add again", the X in the project name is increase.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/906b3283-ef83-4077-95fb-bd80e7dbfb74)
