### ISSUE TITLE
The name of the parent folder is not fully displayed on Data Preview.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1684]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.7.2.2140201 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.4
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Data Preview
- Clear description of the problem: If the parent folder name is relatively long, the un-shown part is displayed as ...,  i see the subfolders have their tooltips, it is recommendation that also add a tooltip for the parent folder name.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Image classification and Local (CPU);
5. Navigate to Data page, select a folder to input;
6. On Data Preview area, find that the parent folder name is not displayed fully.

**Expected behavior**
It is recommendation that add a tooltip for the parent folder just like the subfolders.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/128684899-d6ab6604-c92c-4cff-8404-1dc6322fb7a0.png)

**Comment by LittleLittleCloud** [comment]
@romalpani 
Any advice on this truncated folder name? Maybe similar to what we do with long column name in #1534?

**Comment by romalpani** [comment]
@LittleLittleCloud a tooltip that describes the complete name seems like a viable solution in this case - same as in #1534
