### ISSUE TITLE
Error while setting up workspace for image classification using Azure

### ISSUE THREAD

**Issue by Bhandari-Sushma** [dotnet/machinelearning-modelbuilder#1685]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): Latest
 - Visual Studio Version - 2019

**Describe the bug**
- On which step of the process did you run into an issue: while setting up the workspace to train  for image classification using Azure
- 
- Clear description of the problem:

**To Reproduce**
1. Go to 'Select Training Environment'
2. Click on 'Azure'
3. Click on "Set up workspace"
4. Select "Subscription"
5. Select "Machine Learning workspace name" 
6. Click on "New"
7. Fill the empty areas. Select Region "West Europe"
8. Click "Create"
9. Error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
What error does it say, Is that an Azure error?

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you have more questions.
