### ISSUE TITLE
Unable to find ML.Net in add new item field

### ISSUE THREAD

**Issue by AmulyaSo** [dotnet/machinelearning-modelbuilder#1686]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
@AmulyaSo Could you describe the issue you found

**Comment by LittleLittleCloud** [comment]
Close due to no respond, feel free to reopen it if you have more questions.
