### ISSUE TITLE
Training cycles for a lot of time and then cancels.

### ISSUE THREAD

**Issue by FrequentErvin** [dotnet/machinelearning-modelbuilder#1687]
**System Information (please complete the following information):**
VS 16.10.4
ML.NET Model Builder 16.6.3.2136603

**Describe the bug**
In the training phase, it would cycle (it would actually train) for a lot of time and then cancel. In the beginning, it says "GPU Service not found. Falling back to CPU AutoML Service".

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

I suspect this is because my GPU is not CUDA compatible, and that is exactly my question. Do I really need to have a CUDA-compatible GPU to run image classification with the ML.NET extension? I have a Radeon RX 570 as my GPU and I know of openCL and GCN for other GPUs but can that be applicable here?
(I am pretty new to ML.NET.)

**Comment by LittleLittleCloud** [comment]
Hi @FrequentErvin 
You don't even need a GPU to run image classification. And it seems that you are using CPU according to that "GPU Service not found. Falling back to CPU AutoML Service".

Did you see any output during those cycles? This could let us know if the training process starts or not. And could you share your log, which can be found under %temp%MLVSTools\logs,

Regards

**Comment by FrequentErvin** [comment]
Hi :)
I am indeed using CPU training for now, but I have plans on switching to another GPU. Anyway, output during these cycles was: 

```
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   2

[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Training, Dataset used: Validation, Batch Processed Count:  15, Epoch:   7, Accuracy:  0.7251852

[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Training, Dataset used:      Train, Batch Processed Count: 135, Learning Rate: 0.001768397 Epoch:  56, Accuracy:          1, Cross-Entropy: 0.08442327

[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  51

[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  51
```

These were the four distinct lines of code that kept on repeating forever until I canceled training completely. I let it cycle for hours. Now, I've updated the Model Builder and it outputs different results. By the way, my folder has 1663 images categorized into many subdirectories. This is my log:

> 2021-08-12 20:43:23.0372 INFO Set log file path to C:\Users\user\AppData\Local\Temp\MLVSTools\logs\517ea6fe-9d0b-4b45-b4b6-f83211136188.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
> 2021-08-12 20:44:03.8831 DEBUG AutoMLType: Octopus (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

And now the output just cycles for a while and then abruptly stops: 
```
[Source=AutoML, Kind=Trace] [Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Training, Dataset used: Validation, Batch Processed Count:  15, Epoch:  33, Accuracy:  0.7371428, Cross-Entropy:   1.075206
[Source=AutoML, Kind=Trace] [Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Training, Dataset used:      Train, Batch Processed Count: 133, Epoch:  34, Accuracy:          1, Cross-Entropy:  0.1088887, Learning Rate: 0.003492798
[Source=AutoML, Kind=Trace] [Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Training, Dataset used: Validation, Batch Processed Count:  15, Epoch:  34, Accuracy:  0.7371428, Cross-Entropy:   1.073938
[Source=AutoML, Kind=Trace] [Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Training, Dataset used:      Train, Batch Processed Count: 133, Epoch:  35, Accuracy:          1, Cross-Entropy:  0.1067977, Learning Rate: 0.00328323
[Source=AutoML, Kind=Trace] [Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Training, Dataset used: Validation, Batch Processed Count:  15, Epoch:  35, Accuracy:  0.7371428, Cross-Entropy:   1.072679
[Source=AutoML, Kind=Trace] [Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Training, Dataset used:      Train, Batch Processed Count: 133, Epoch:  36, Accuracy:          1, Cross-Entropy:  0.1046122, Learning Rate: 0.00328323
[Source=AutoML, Kind=Trace] [Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Training, Dataset used: Validation, Batch Processed Count:  15, Epoch:  36, Accuracy:  0.7371428, Cross-Entropy:   1.071613
```
Also this is a screenshot of the process.
![screenshot 4314](https://user-images.githubusercontent.com/75392265/129255789-ffcab85c-17cc-4870-bc6b-5e85cf243afd.jpg)

**Comment by LittleLittleCloud** [comment]
Hi @FrequentErvin 
The log looks good until training time out. Can you also put the content your .mbconfig here? I'd like to confirm if TrainingTime is set correctly.

**Comment by FrequentErvin** [comment]
Here's the config:

> {
>   "TrainingConfigurationVersion": 0,
>   "TrainingTime": 2147482,
>   "Scenario": {
>     "ScenarioType": "ImageClassification"
>   },
>   "DataSource": {
>     "DataSourceType": "Folder",
>     "FolderPath": "C:\\Users\\user\\Desktop\\krave"
>   },
>   "Environment": {
>     "EnvironmentType": "LocalCPU"
>   }
> }

So I should change the 2147482 to 2147483647?

**Comment by LittleLittleCloud** [comment]
> So I should change the 2147482 to 2147483647?

Yeah this might temporarily fix the issue you have.

> I'll try a smaller dataset, for example, the one supplied in the tutorial, and do sentiment prediction to see if that would work.

Thanks and please let us know how's that going.

**Comment by FrequentErvin** [comment]
Oh my God. I deleted the project and then started fresh out again and this time around, after a stupendous 7 hours of training, it actually worked. It created the training.cs file and it actually trained the model as it should :). I will write here for updates on the situation every so often.

**Comment by LittleLittleCloud** [comment]
Sounds good, and I strongly suggest you trying GPU, which accelerates my training ~5 times faster with a GTX1060.
