### ISSUE TITLE
accuracy is off by 2 decimal points after Azure training image class

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1689]
Accuracy should be 95% (not .95%)

![image](https://user-images.githubusercontent.com/10437687/129112944-cc058243-fb61-4e81-b8e6-452123da1bab.png)

![image](https://user-images.githubusercontent.com/10437687/129113036-9f69a2d8-6beb-4640-ad5f-5bc7474e388b.png)

**Comment by zewditu** [comment]
Close  b/c duplicated issue of  https://github.com/dotnet/machinelearning-modelbuilder/issues/1633
