### ISSUE TITLE
How do I fix this error?

### ISSUE THREAD

**Issue by Choda1** [dotnet/machinelearning-modelbuilder#1690]
위치: Microsoft.ML.AutoML.ColumnInferenceApi.InferSplit(MLContext context, TextFileSample sample, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse)
   위치: Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   위치: Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParamater config, ColumnInformation columnInformation)
   위치: Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() 파일 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:줄 112

**Comment by LittleLittleCloud** [comment]
@Choda1 

Can you share your VS version and model builder version, and a snapshot of your dataset please

**Comment by Choda1** [comment]
Visual Studio 2019 & Model Builder Version 16.1.0 & Dataset ->
[sms_spam.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/6982636/sms_spam.csv)

**Comment by LittleLittleCloud** [comment]
@Choda1 
Thanks for sharing the dataset, it looks like you are using a quite old model builder version (you might need to uninstall it in VS installer and reinstall it in market place if directly upgrade doesn't work for you), could you try upgrade your model builder to 16.6.3.* and try again?

BTW the train succeeds on my PC, with 16.6.3
![image](https://user-images.githubusercontent.com/16876986/129399763-3fe9fa97-3459-4241-b801-98751116fb16.png)

**Comment by Choda1** [comment]
Thank you :)
