### ISSUE TITLE
Model Builder Error: Sequence contains no matching element.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1692]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.7.2.2141201 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.11.0
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Data Page
- Clear description of the problem: After training complete, want to change to another dataset for training, so back to Data page, click "Browse..." button to input another dataset, pop up Model Builder Error dialog.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Text classification and Local(CPU) environment to complete training;
4. Back to Data page, click "Browse.." to re-input data source (Regardless of whether it is the same data set)；
5. Pop up Model Builder Error: Sequence contains no matching element.

**Expected behavior**
No error when re-input the data source.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/129329184-0909d5ac-e435-4934-9386-3729435b986e.png)

**Log file:**
[MLModel3-C8UUG2.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6981097/MLModel3-C8UUG2.txt)

**Additional context**
This issue doesn't appear before training.

**Comment by zewditu** [comment]
@LittleLittleCloud  @beccamc  for visibility.

**Comment by beccamc** [comment]
@v-Hailishi Can you see if this is still reproducing? Thanks!

**Comment by v-Hailishi** [comment]
@beccamc The bug is not repro on the latest main branch: 16.13.5.2217801 for both VS2019&2022.
![#1692](https://user-images.githubusercontent.com/99375895/160518830-f8e0897d-897f-40d5-930b-62b1b7d77ccb.gif)
