### ISSUE TITLE
ML.Net model file template cannot be found n Add New Item dialog box

### ISSUE THREAD

**Issue by arnabl79** [dotnet/machinelearning-modelbuilder#1693]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@arnableI79  could you tell us the steps to reproduce the issues for better investigation?

**Comment by beccamc** [comment]
Please checkout this troubleshooting section https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#i-cannot-add-machine-learning-to-my-project

@zewditu FYI we have a troubleshooting section for this.

**Comment by zewditu** [comment]
arnabl79 I hope the troubleshooting helps you.
