### ISSUE TITLE
Some text gets cut off when resized

### ISSUE THREAD

**Issue by jwood803** [dotnet/machinelearning-modelbuilder#1695]
The "Next step" and "Add to solution" button text gets cut off in dark mode.

Screenshots:
![image](https://user-images.githubusercontent.com/1578160/129476795-9e8fc7ed-4b31-4ab9-829f-08538dfa5583.png)

![image](https://user-images.githubusercontent.com/1578160/129476801-16229eab-923b-424c-a6c2-89690d6c387e.png)

When switching to light mode the text appears completely.

Screenshots:
![image](https://user-images.githubusercontent.com/1578160/129476815-f24b3936-3058-46a5-8891-b6fe45022ec9.png)

![image](https://user-images.githubusercontent.com/1578160/129476824-f3b0619e-87b6-4e7f-b686-92c2e55b3886.png)

**Comment by zewditu** [comment]
@ jwood803 when you say "in dark mode"  is that for windows or VS? 

Note: I tried it for both, I am not able to reproduce the issue.

**Comment by jwood803** [comment]
@zewditu Hi! It's dark mode in VS

**Comment by zewditu** [comment]
@jwood803, thanks for the conformation! for me no cut-off
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/b110da43-7b63-42db-acfd-fe7fa784de52)

**Comment by LittleLittleCloud** [comment]
Get it reproduced using the following setting

![image](https://user-images.githubusercontent.com/16876986/130523365-6c7890dd-7f20-49c7-b227-78c3fec7e231.png)

**Comment by zewditu** [comment]
If we reproduce it like this I do not think it is being in light and dark mode. It looks it is similar to https://github.com/dotnet/machinelearning-modelbuilder/issues/1197. 
we might need to see if we can use ellipses and tooltips but I am not sure if it is ideal on buttons .
@romalpani  any thought?

@jwood803 is this the right way to reproduce the issue?

**Comment by jwood803** [comment]
@zewditu Yep, I was able to verify on my machine that setting the font size will do that. I think dark mode is setting the font bigger than light mode is.

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.9.1.2156601

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/5cbcaab3-4d41-4d73-ac3d-3c1a9b593740)

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/38d65188-a3f8-422f-a118-69f3b4498404)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e2d82f77-489a-4e80-bd43-0c59d8b85ad1)
