### ISSUE TITLE
" How long should I train for?" should be a link 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1697]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**

**Steps to Reproduce**
1. Select any text classification scenario 
2. Use[ this]([https://app.zenhub.com/files/186917455/3f223f80-2a65-42d4-a8c5-204e00e30383/download](https://app.zenhub.com/files/186917455/3f223f80-2a65-42d4-a8c5-204e00e30383/download) .
) small dataset  
3. Start to train.
**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/5a3d0ecd-ac4d-4452-916f-854deaec24c2)_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**The Text " How long should I train for " in the error message is not a link. Is this just to point the user to click the link at the top of the page with the same text?  @romalpani  @briacht?

**Comment by beccamc** [comment]
It will probably be difficult to imbed a link inside of this error message. This is a plain text message. If we want to change how we approach this, we should probably change what it says or how it is presented. There is an issue in the "Needs design" column for this topic https://github.com/dotnet/machinelearning-modelbuilder/issues/1373

**Comment by zewditu** [comment]
Thanks, @beccamc  for the explanation, However, I  am wondering what makes it difficult to include the link inside the error message?

**Comment by beccamc** [comment]
The exception returns a plain string. We would need to write a special object that marked what part of the string was a hyperlink. We'd then need a special component to render the hyperlink inside the string. It would be easier with a plain link (e.g. www.bing.com), but we would still need to write a special component

**Comment by beccamc** [comment]
@zewditu Can I close this?

**Comment by zewditu** [comment]
Yes!
