### ISSUE TITLE
Remove NC series VMs

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1702]
Communication from Microsoft Azure team: 

**The Azure NC-series Virtual Machine sizes will be retired on 31 August 2022**

You're receiving this email because you've been a user of NC-series Azure virtual machines within the last 12 months. 

Azure NC-series virtual machines, powered by NVIDIA Tesla K80 GPUs, were introduced in 2016 and have been replaced by newer GPU virtual machines such as the NC T4 v3 which offers dramatic decreases in total cost of operation for most workloads. Additionally, support for the Tesla K80 has been deprecated as of CUDA 11.0 and may be dropped from future versions. NC-series virtual machine sizes will be retired on 31 August 2022. 

After 31 August 2022, any remaining NC virtual machines on your subscription will be set to a deallocated state, cease to be available, and will no longer incur billing charges. 

Note: This virtual machine size retirement only impacts the virtual machine sizes in the original NC, ND, and NC v2-series powered by Keppler and Pascal GPUs. (K80, P40, and P100) This retirement announcement does not apply to the newer NC v3, NC T4 v3, and ND v2-Series virtual machines. 

Required action 
We're retiring NC virtual machines on 31 August 2022. All NC virtual machines will need to be de-allocated by that date. For recommendations on which virtual machines to migrate your NC workloads to, or for help with the creation of new virtual machines, please see the [GPU compute migration guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fgpucomputemigration&data=04%7C01%7Cbeccam%40microsoft.com%7C9c389af117bf4c8e16b008d961f3867a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637648520825644910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c7RVuQG%2FY5vb5Kur1kPum98MSKx8l8%2BpYWvz9aLNSUA%3D&reserved=0). Visit the[ Azure Virtual Machine pricing page](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fpricing%2Fdetails%2Fvirtual-machines%2F&data=04%7C01%7Cbeccam%40microsoft.com%7C9c389af117bf4c8e16b008d961f3867a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637648520825644910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3v8KzRs0taeeFUAH4wwS5hh7xF2Ud17jc6Eed%2FUGv20%3D&reserved=0) for additional information.

**Comment by beccamc** [comment]
Model Builder azure dialogs recommend NC machines. We need to 
- [ ] Look at what is recommended instead 
- [ ] Update Azure Compute Dialog to support new SKU

**Comment by luisquintanilla** [comment]
## Migration Plan

P0: Replace NC v1 VM series to NC T4 v3 VM series in Azure Compute Dialog
P1: Add NC v3 VM series SKUs as compute options in Azure Compute Dialog

**Comment by zewditu** [comment]
Our current list allowed computes are 
`"STANDARD_NC6",
                "STANDARD_NC12",
                "STANDARD_NC24",
                "STANDARD_NC24R",` 

where we could get the current recommended lists ?

**Comment by luisquintanilla** [comment]
> Our current list allowed computes in Model Builder are `"STANDARD_NC6", "STANDARD_NC12", "STANDARD_NC24", "STANDARD_NC24R",`
> 
> where we could get the current recommended lists ?

The [migration guide](https://docs.microsoft.com/en-us/azure/virtual-machines/n-series-migration) lists those out. So for the current options in Model Builder they map out to the following:

| Current  SKU| Updated SKU |
| --- | --- |
| STANDARD_NC6 | Standard_NC4as_T4_v3 |
| STANDARD_NC12 | Standard_NC16as_T4_v3 |
| STANDARD_NC24 | Standard_NC64as_T4_v3 |
| STANDARD_NC24R | Standard_NC24rs_v3 |

**Comment by zewditu** [comment]
To confirm are these the right  new  C v3 VM series 
https://docs.microsoft.com/en-us/azure/virtual-machines/ncv3-series

![image](https://user-images.githubusercontent.com/36615490/187566722-100d57fe-cb62-4429-9052-b7362ee00421.png)

**Comment by luisquintanilla** [comment]
It should be the NCas* SKUs. Here's the direct mapping

https://docs.microsoft.com/en-us/azure/virtual-machines/n-series-migration#nc-series-vms-featuring-nvidia-k80-gpus

![image](https://user-images.githubusercontent.com/46974588/187714170-cf312844-a40c-44f4-aa81-493ff387e14c.png)

![image](https://user-images.githubusercontent.com/46974588/187714319-cfd922a1-09c5-4d34-b7e6-a724f148d357.png)

**Comment by luisquintanilla** [comment]
@beccamc to add more details.

Looking into whether quota availability can be queryied / displayed. Otherwise, we need to provide documentation / guidance so quota can be increased / requested.

**Comment by beccamc** [comment]
Low priority updates: 
- [ ] Update the default compute creation to be "Low Priority". This means auto-selecting "Low Priority" in the drop down but allowing users to change it. 
- [ ] Add "Low priority is selected automatically." to the tooltip explaining the computes. 

Quota updates: 
We need to surface information about the [quota](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-manage-quotas). Option one... 
1. **Can we query for what the quota is before creating the compute?** If so, let's display that to the user in the create dialog. 
2. Let's catch the create exception and show better instructions for fixing the problem.

**Comment by beccamc** [comment]
@zewditu Are you able to take on this work item? Details in the comment above.

**Comment by zewditu** [comment]
@beccamc   does tooltip make sense here?  If we make it tooltip the user should hover over on it to see the information , this has a high chance that it will be overlooked by the user.
I recommended  static information somewhere on top "Low priority is selected automatically"  
![image](https://user-images.githubusercontent.com/36615490/190324948-158ae24e-9363-4c93-b86b-69038d78522c.png)

**Comment by beccamc** [comment]
@luisquintanilla see above question

**Comment by luisquintanilla** [comment]
@zewditu Are we prepopulating the Compute priority dropdown with "Low priority"? If so, I'd be okay with keeping that information in the tooltip since the fact we're prepopulating the field implies it's the default / recommended setting.

**Comment by zewditu** [comment]
@luisquintanilla  "Are we prepopulating the Compute priority dropdown with "Low priority"?  yes

**Comment by luisquintanilla** [comment]
@zewditu just wanted to get some clarity on where the tooltip would be vs the static text. Would it be at the top where you've underlined with the red pen or would it be in the already existing tool tip for "Compute priority"? Also, what is the message you were going to use?

**Comment by zewditu** [comment]
I recommend having it at the top  where I underline it with red  because we already have a tooltip 
![image](https://user-images.githubusercontent.com/36615490/190523410-bf2296fe-032a-409d-9fd1-b5ece0f8fa98.png)

 but I am ok with adding a tooltip  but are we gonna add  a tooltip explaining two things " Priority determines cost and avaliblity of  compute" and "Low priority is selected automatically"

**Comment by zewditu** [comment]
> what is the message you were going to use?

Low priority is selected automatically

**Comment by LittleLittleCloud** [comment]
![Image](https://user-images.githubusercontent.com/16876986/197069474-6f622e5a-0f6d-4bfb-858b-b052b270acf3.png)
