### ISSUE TITLE
Double "NotStarted" status throws error for RemainingTime

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1703]
1. Reload an MBconfig file
2.  Re-train
3. See error when this.TrainStatus == NotStarted and this.AzureTrainingStatus == NotStarted

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/efaf299c-0848-4eb0-ba98-c92594a41333)

**Comment by LittleLittleCloud** [comment]
Should return `Start Train` instead ?

**Comment by beccamc** [comment]
I think that makes sense
