### ISSUE TITLE
Error window header not localized 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1704]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/fe23cf7b-22bf-4c9f-8f2b-26b1ce15c577)_
**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by vzhuqin** [comment]
Repro on latest main build: 16.7.2.2142301
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e0b64194-ddc6-4b97-94fe-ef3cd88e7a66)

**Comment by beccamc** [comment]
Looks like this is translated in the xlf files now. Can you try again Qin?

**Comment by vzhuqin** [comment]
Error window header and Close button has been localized on ML.Net Model Builder: 16.9.1.2155801 (Main)
![image](https://user-images.githubusercontent.com/81727020/140872111-1cd62765-c2dd-4129-842f-47872e9a7e91.png)
