### ISSUE TITLE
MBConfig not implemented exception for invalid file

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1705]
On file open I'm seeing a terminal error from trying to open the mbconfig. 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/0d0f90e8-6e46-4bbe-9fba-d0c2606c4c76)

Problem is happening in MBConfigConverter ReadJson(), line 130. This is only happening with one weird mbconfig file. It's empty except for a test version number. 

> {
>   "version": "42.42.42.42.4242"
> }

I have no idea how I got this particular mbconfig file. Creating and saving a new "emtpy" mbconfig doesn't produce the same type of file. It could be a fluke that I have this weird file config and we can close this issue. [Problem mbconfig](https://app.zenhub.com/files/186917455/aa49b806-9b33-4bf8-aae1-114168a90e15/download)

**Comment by beccamc** [comment]
@LittleLittleCloud Any idea how I could have gotten this strange mbconfig file. It causes a problem with mbconfig load. If we can't think of how I could have gotten this file (e.g. if we don't think customers will end up here) I'm okay closing this issue as won't fix.

**Comment by LittleLittleCloud** [comment]
Not quite clear... It's missing TrainingTime and Type, so theoretically it can't be something after v1 schema being applied.

**Comment by beccamc** [comment]
Okay, I think we should just close. I don't see many customers getting into this situation. If they have a blank project they can just start a new project.
