### ISSUE TITLE
October 2021 Release rough plan of work

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#1707]
- #1564 

- #1627 (Any Remaining Items)

- #1073
  - [x] #1750

- #1638 - @briacht @luisquintanilla @JakeRadMSFT - We need to figure out our codegen story.
  - [ ] Add Data Loading Code to Training.cs
  - [ ] #1350  - **_3 Days_**
  - [x] #1449
  - [ ] #851  - **_3 Days_**
  - [ ] #967 - **_3 Days_**
  - [ ] **Needs PM/Design** #1662

- #1635 
  - [ ] #1655 
  - [ ] #1409 
  - [ ] #1446 
  - [x] #1267 
  - [ ] #1271 
  - [ ] #1386 
  - [ ] #1483 - **_3 Days_**
  - [x] #1426 

- #1639 
  - [ ] #669 
  - [x] #1701 
  - [x] #1710 

### Future - Start Thinking About :)

- #1068 
  - [x] #994 

- #1591 
- Versioning - Needs Issue
- #1520

**Comment by luisquintanilla** [comment]
## Documentation Work Items

[September 2021](https://github.com/dotnet/docs/projects/138?card_filter_query=label%3Adotnet-ml%2Fprod)

## Areas of Focus

- Tutorial: Model Builder Image Classification Training on Azure
- Tutorial: Model Builder Recommendation
- Update code samples in documentation
- Update how to choose an algorithm & improve model accuracy

**Comment by beccamc** [comment]
This release is out. Closing.
