### ISSUE TITLE
continue training - value cannot be null Error

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1708]
1. Create new console .NET 5 app
2. Add > Machine Learning Model, rename to "SentimentModel.mbconfig"
3. Select Text classification
4. Select yelp_labelled.txt dataset
5. Choose "Sentiment" as Label column
6. Get error:

![image](https://user-images.githubusercontent.com/10437687/130277142-4110a32e-571e-4152-9b02-74dee9366239.png)

I was able to continue to Train page but when I hit Start training I got the same error. And it kept randomly popping up (it did finish training successfully).

mbconfig pasted below:

{
  "TrainingTime": 60,
  "Scenario": "Classification",
  "DataSource": {
    "Type": "TabularFile",
    "Version": 1,
    "FilePath": "C:\\Datasets\\yelp_labelled.txt",
    "Delimiter": "\t",
    "DecimalMarker": ".",
    "HasHeader": true,
    "ColumnProperties": [
      {
        "ColumnName": "Comment",
        "ColumnPurpose": "Feature",
        "ColumnDataFormat": "String",
        "IsCategorical": false,
        "Type": "Column",
        "Version": 1
      },
      {
        "ColumnName": "Sentiment",
        "ColumnPurpose": "Label",
        "ColumnDataFormat": "String",
        "IsCategorical": true,
        "Type": "Column",
        "Version": 1
      }
    ]
  },
  "Environment": {
    "Type": "LocalCPU",
    "Version": 1
  },
  "Type": "TrainingConfig",
  "Version": 1
}

**Comment by beccamc** [comment]
@briacht Thanks for filing! What version of MB were you on?

**Comment by briacht** [comment]
![image](https://user-images.githubusercontent.com/10437687/130468030-f9284a6a-c227-4662-81bc-0978e9f30191.png)
