### ISSUE TITLE
continue training - don't have option to pause training

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1709]
![image](https://user-images.githubusercontent.com/10437687/130277594-c43f1c24-1471-41c8-877f-9c62b0b228f9.png)

Can only Cancel

**Comment by briacht** [comment]
Also this is what it looks like after I finish training:

![image](https://user-images.githubusercontent.com/10437687/130277862-e44e540b-b6a0-419a-b84e-126d5abef7f4.png)

**Comment by beccamc** [comment]
@LittleLittleCloud For visibility.

**Comment by briacht** [comment]
I talked to @LittleLittleCloud and we determined that this only happens when creating new .mbconfigs. I didn't get the error when opening projects with existing .mbconfig

**Comment by beccamc** [comment]
@LittleLittleCloud Is this fixed?

**Comment by LittleLittleCloud** [comment]
Nope : - )

**Comment by luisquintanilla** [comment]
This issue might be related #1645.

**Comment by luisquintanilla** [comment]
Closing issue for now until work on Framework supports this.
