### ISSUE TITLE
Value Prediction Scenario Gives Index Out Of Bounds Of Array Error/Exception

### ISSUE THREAD

**Issue by AR0106** [dotnet/machinelearning-modelbuilder#1711]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.6.3.2136603
 - Visual Studio Version: 16.11.0

**Describe the bug**
- I ran into the issue while I was training some data with the Value Prediction Scenario and the Model Builder was going through each Regression Type after it got through the 3rd type 
- Clear description of the problem: The Model Builder fails and gives an error stating an index was out of bounds of an array, it is able to get through the first 2 or 3 regression types just fine, but then gives the previous error.

**To Reproduce**
1. When Creating a new .mbconfig file select the Value Prediction Scenario and select the Local CPU as the environment
2. Create a .csv file with the data provided in the "Additional context" section and load that
3. Select "Output" and the Label and leave all other values the same
4. Start Training for 10 seconds
5. See error

**Expected behavior**
I would expect the Model Builder to successfully complete the training, therefore allowing me to move on from there and add more data if needed.

**Screenshots**
[Model Builder Output](https://imgur.com/a/dsFydK4)

**Additional context**
The data I was using is:
Operation,Input,Output
sqrt,4,2
sqrt,9,3
sqrt,16,4
sqrt,25,5
sqrt,36,6
sqrt,49,7
sqrt,64,8
sqrt,81,9
sqrt,100,10

**Comment by vzhuqin** [comment]
@LittleLittleCloud  I can repro this issue with the provided data on latest main model builder: 16.7.4.2146502, could you help to check again?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/43303357-2de5-44c7-afb8-a16ad3533252)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/37d7e3f5-9b4b-4b2a-86c7-81eb0666c0ec)

**Comment by AR0106** [comment]
> @LittleLittleCloud I can repro this issue with the provided data on latest main model builder: 16.7.4.2146502, could you help to take a look again?
> ![image.png](https://camo.githubusercontent.com/b94924c0f8850a5a42ba040fc162856069d62fd9fc4aa89de75e7038797765b4/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630363533653439323339306130386561363136636231302f34333330333335372d326465352d343463372d616662382d613136616433353333323532)
> ![image.png](https://camo.githubusercontent.com/4f1e0fbf9d86f63b99a3c8fd6d463e4ad11472f50a2ec5fe79ece72991f8c21e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630363533653439323339306130386561363136636231302f33376437653366352d396234622d346232612d383663372d383165623036363663306563)
> ![image.png](https://camo.githubusercontent.com/6f1b5be1bf7fa02429398df4d45e549a6dcb369b951c41bc6d27a7337a529202/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630363533653439323339306130386561363136636231302f64633338666539392d383034362d346234612d393038612d323938336364323565353266)

Yes, this issue is the same one I'm getting, if that's you're asking.

**Comment by vzhuqin** [comment]
Can complete the training without error on ML.Net Model Builder: 16.9.1.2155501 (Main)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/bc8da3c4-95df-4ea2-ba20-d182e6fa74d0)
