### ISSUE TITLE
The data pre-filled on the Evaluate page is not the row 1 of the data.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1714]
**System Information (please complete the following information):**
- ML.Net Model Builder: 16.7.2.2141801 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.11.1
- Windows OS: Windows-10-Enterprise-21H1

**Describe the bug**
- On which step of the process did you run into an issue: Evaluate page
- Clear description of the problem: The description of Sample data of Evaluate page is that the pre-filled data is the row 1 of your data, but comparing the preview data of the data page, it is found that the pre-filled data is not the first row, but the second row of data. 

**To Reproduce**

1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Value prediction and Local (CPU) environment;
5. Input the dataset and complete the train;
6. Navigate to Evaluate page, find that pre-filled data is not the first row, but the second row of data, this does not match the description. 

**Expected behavior**
As described, the first row of data is pre-filled. 

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/130386379-f0bedb58-d8b3-4ee7-93cb-a862868e9919.png)
![image](https://user-images.githubusercontent.com/81727020/130386445-f7b60672-ad34-47aa-bc0d-d60bf4490b9e.png)

**Additional context**

**Comment by beccamc** [comment]
@zewditu Could this have regressed from the change you made to remove the header from the full row count?

**Comment by zewditu** [comment]
I am not sure, I will take look

**Comment by zewditu** [comment]
The cause of this issue try out values are taken from selected rowIndex +1 instead of just select index.
