### ISSUE TITLE
While Starting Train

### ISSUE THREAD

**Issue by Chittaranjandell** [dotnet/machinelearning-modelbuilder#1716]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
Hi @Chittaranjandell. I need more information to investigate this issue. Can you please include..
- Your Model builder version
- Steps  you did to get to the error 
- Screenshots

Thanks!

**Comment by beccamc** [comment]
@Chittaranjandell Any update on the above questions?

**Comment by beccamc** [comment]
Closing this issue. Please respond if you're still having problems. Thanks!
