### ISSUE TITLE
Training  status update instablity 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1718]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/b32eca54-ed17-460a-a325-4b4eb9cb15cb)

**Additional Context**
I am not sure If that is the experience we need or not after training time says remaining 1 it says -1.-2

**Comment by beccamc** [comment]
Closing as duplicate https://github.com/dotnet/machinelearning-modelbuilder/issues/1668
