### ISSUE TITLE
Change description of Data classification

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1719]
Since we changed the title from Text classification to Data classification, let's update the description as well:

![image](https://user-images.githubusercontent.com/10437687/130521193-c5e2bcdf-7dbc-408e-afb9-5e54870447d6.png)

How about "Classify tabular data into 2+ categories..." ?

@JakeRadMSFT @romalpani

**Comment by romalpani** [comment]
I think the word "Tabular" might work. In my little research, I found this poll run by Fast.ai co-founder.
![image](https://user-images.githubusercontent.com/48927690/130656540-bacc61de-6320-405d-9caf-ea063c37ee31.png)

[Link to tweet](https://twitter.com/math_rachel/status/990375128314736640?s=20)
[Link to related article](https://www.fast.ai/2018/04/29/categorical-embeddings/)

**Comment by vzhuqin** [comment]
The description has been changed.
- ML.Net Model Builder: 16.7.4.2146502 (Main Branch)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/64c25e74-a7bb-4399-a043-b217a1709a5e)
