### ISSUE TITLE
Button text is incorrect when model is Finalizing

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1721]
Button text should not say "Start training" when model is Finalizing.

![image](https://user-images.githubusercontent.com/10437687/130522419-ce6466b8-3d90-403e-988e-f80fa57c647c.png)

@romalpani What should the button say here and what should the state be?

**Comment by beccamc** [comment]
Per Jake and Becca, this isn't high pri. Closing.
