### ISSUE TITLE
Data page : Spinner, combo-box selection state, subtitle of preview section.

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#1723]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.2.2142301
 - Visual Studio Version: VS 2022 Preview 4

**Describe the bug**
- On which step of the process did you run into an issue: Data page
- Clear description of the problem:
1. Once a file is selected, the spinner for "data preview" section appears to be very big, and misplaced. 
>>>>> The spinner must appear under the title "Data preview" along with some text. Work with design for a final solution.
2. Column to predict combobox : The selection state of items in this dropdown needs padding on top and bottom. 
>>>>> Selection states must be like the main menu item selection state for the top-most item and the bottom most item. 
3. When none of the columns are ignored, the data preview section says "including 0 columns that are ignored". 
>>>>> If none of the columns are ignored, the preview section should not have the additional text "including 0 columns that are ignored."

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/48927690/130526497-f44302b7-8edb-4189-bd38-d90e369af90b.png)

![image](https://user-images.githubusercontent.com/48927690/130526893-b13b3163-4105-408e-bdb6-3ed263d3efee.png)

**Additional context**

**Comment by romalpani** [comment]
For #1 - Loading state of data preview, here's a Figma.
https://www.figma.com/file/bhdPADawiO4YQGdUNExiUc/?node-id=515%3A49175
@briacht any suggestions for the language, feel free to comment on the Figma.

**Comment by romalpani** [comment]
For #2 - Padding for selected item in drop-down.
If you notice in this screenshot, there's a bit of padding on the top of the selection area. This screenshot is of a menu item from the top bar of VS. 
![image.png](https://images.zenhubusercontent.com/5e8f93535a77012adc93d289/e8a42f79-1dc0-477d-90e8-2015d2d04922)

Whereas in the column to predict dropdown, you'll notice the padding from top is missing. 
![image.png](https://images.zenhubusercontent.com/5e8f93535a77012adc93d289/1b4a43f1-424e-4a20-b230-26446c2cfa45)

Happy to discuss in a sync later, if this is still not clear.

**Comment by romalpani** [comment]
For #3:

**When no columns are ignored:**
"10 of 100,000 rows."

**When 1 column is ignored:**
"10 of 100,000 rows, and all 7 columns (including 1 ignored column)."

**When 4 columns are ignored:**
"10 of 100,000 rows, and all 7 columns (including 4 ignored columns)."

@briacht @beccamc  - Thoughts? 
I remember some time back we had discussed the strings. Not sure if we had considered this as an option. Feels shorter.

**Comment by zewditu** [comment]
@romalpani  is "Tools" is a dropdown menu or Combobox?  in vs  combo boxes have similar appearance what we have in model builder  
![image](https://user-images.githubusercontent.com/36615490/131743189-ce5923bc-f1d6-4857-99bb-d84f1540b0d7.png)

**Comment by romalpani** [comment]
@zewditu - since the issue is at the control level, it is okay for now. Let's not make a custom control. 
Instead, if we can figure out who the owner of the original control is - maybe we can assign a bug to them informing of this issue?

**Comment by beccamc** [comment]
#### Item 1
![processingdata.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/97407556-752a-4cb2-bdd3-cad9a202ac3c)

#### Item 2
Default behavior of control 

#### Item 3

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/8bebee70-cc64-40d4-9ff4-b016370d1de0)

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/11bf1dfa-999f-401b-8151-5750ca14e56f)

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/20dacc63-e5cd-4f66-a7a3-d1c8fddb71ac)
