### ISSUE TITLE
--name (mlnet CLI) is not working

### ISSUE THREAD

**Issue by lehong3000** [dotnet/machinelearning-modelbuilder#1728]
**System Information**
 - Ubuntu 18.04

**To Reproduce**
~/.dotnet/tools/mlnet image-classification --dataset "/home/dataset" --name "MyProject"
Or
~/.dotnet/tools/mlnet image-classification --dataset "/home/dataset" --name="MyProject"

**Expected output project name**
MyProject

**Actual output project name**
SampleImageClassification

**Comment by vzhuqin** [comment]
also not repro this issue on mlnet: 16.7.5
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4f311e2d-70e0-47b8-840e-b47336895e35)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/10f19ed7-b887-4c26-b307-445b85ebcc8d)
