### ISSUE TITLE
Get code errors when copy code into app from Consume page

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1732]
I trained a model with Model Builder and then copy + pasted the code from the Consume page into a console app and got an error:

![image](https://user-images.githubusercontent.com/10437687/130813581-be9240a4-ddaf-4f72-93ea-a6e098912748.png)

This happened for both a Data classification model and a Value prediction model.

This code should run when copy + pasted into app.

**Comment by vzhuqin** [comment]
Not repro this issue on latest main build: 16.7.4.2146502

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7616f2f6-1d39-4ac0-9fd2-64e75d4d2793)
