### ISSUE TITLE
Bulk edit in Advanced Data Options

### ISSUE THREAD

**Issue by ghost** [dotnet/machinelearning-modelbuilder#1733]
**Usability Issue**
When working with a File Data Source type, the UI for Advanced Data Options is difficult to work with when there is a large number of columns and columns that have wide names.

**Request**
Can the UI be modified to make this dialog easier to use? 

**Additional context**
![image](https://user-images.githubusercontent.com/27367041/130869997-a76599dd-414e-446d-ada1-967136a579bc.png)
![image](https://user-images.githubusercontent.com/27367041/130870014-e107b108-272e-401c-8727-e533ac632563.png)
![image](https://user-images.githubusercontent.com/27367041/130870033-3f6a04fe-c172-47b2-b71e-00b7ef099822.png)

**Comment by beccamc** [comment]
Thanks for reporting @BeginTry! We've improved the visibility of column names, the fix will ship in September - Issue [1712](https://github.com/dotnet/machinelearning-modelbuilder/issues/1712). 

We've gotten other comments about problems with bulk edit. I'm going to use this issue to track.

**Comment by beccamc** [comment]
Sorry, we haven't gotten enough feedback on this to prioritize this experience. I assume your dataset had a lot of similar looking data and we didn't correctly predict the type. Can you share your dataset?

Alternatively you can open the .mbconfig file and edit the column value there. I know this isn't idea but a search and replace all can update many columns from "Single" to "String".
