### ISSUE TITLE
Model Builder Error: SQL connection is not valid. If reloading Model Builder, please re-open the SQL Source dialog to reauthenticate.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1735]
**System Information (please complete the following information):**
- ML.Net Model Builder: 16.7.2.2142501 (Main Branch)
- Windows OS: Windows-10-Enterprise-21H1
- Microsoft Visual Studio Enterprise 2019: 16.11.1

**Describe the bug**
- On which step of the process did you run into an issue: Reopen model builder
- Clear description of the problem: Input data by selecting SQL Server>Change data source...>Microsoft SQL Server>SQL Server Authentication, the error appears if reloading the model builder.

**To Reproduce**
1. [Pre-requisites](https://github.com/dotnet/machinelearning-tools/blob/main/docs/tests/Instructions/Pre-Requisites/SQLPassword.md)
2. Select Create a new project from the Visual Studio 2019 start window;
3. Choose the C# Console App (.NET Core) project template with .Net 5.0;
4. Add model builder by right click on the project;
5. Select Data classification and Local(CPU);
6. On Data page, select SQL Server>Change data source...>Microsoft SQL Server;
7. In the Connect Properties dialog, use SQL Server Authentication to connect the Server;
![image](https://user-images.githubusercontent.com/81727020/130920341-52fb64a4-f278-49ac-901d-b8439471f5cc.png)
8. Navigate to Train page to complete training;
9. Save and close the model builder;
10. Reopen the model builder, see error: prompt Model Builder Error dialog.

**Expected behavior**
No error while reloading model builder.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/130919098-48322ecd-c037-4edf-a27f-ec748301d6f8.png)
![image](https://user-images.githubusercontent.com/81727020/130919194-39ec312d-f543-44c0-aa22-0e74cad8827d.png)

**Additional context**
This issue appears on VS2019 and VS2022.

**Comment by beccamc** [comment]
This is expected. We don't store the plain text password for security reasons. @JakeRadMSFT Do you have thoughts on how we could improve this? Is there a secure way to do this? I can add more context if that would be helpful.

**Comment by beccamc** [comment]
We need to create a better reauthentication experience.

**Comment by luisquintanilla** [comment]
Tagging this as part of the #1761

**Comment by luisquintanilla** [comment]
Nevermind. Closing. This looks like a duplicate of #1899 which was unable to repro

**Comment by chanmmn** [comment]
I am having the same issue just can no longer connect to my SQL Server.
Do watch this video.
https://drive.google.com/drive/folders/1-lxvgW9ELXpC0nhr_u6qL372d8o6zqdg?usp=sharing
When can this be resolved?
