### ISSUE TITLE
Save trained models using .mlnet or .model file extension

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#1738]
**Is your feature request related to a problem? Please describe.**

Since the initial versions of ML.NET, the file extension used to save models has been *.zip*. To my knowledge, this is convention rather than a hard requirement. A *.zip* file may imply it's something you can open and inspect. For ML.NET, while you can open the *zip* file, it's not easy to inspect its contents unless you use something like Netron. Therefore, *zip* may be a misnomer and confusing. 

**Describe the solution you'd like**

Use a file extension other than *.zip* for model files like *.mlnet* or *.model* similar to how Model Builder uses *.mbconfig* for its configuration file. 

Other than clarity on what the contents of the file represent, there may be an opportunity to leverage tooling to generate schema classes. (i.e. In VS, Right-click *mymodel.mlnet* > Create input & output schema).

Here are some sample models using the *.mlnet* extension from @bartczernicki

https://github.com/bartczernicki/MLDotNet-BaseballClassification/tree/master/MLDotNet-BaseballClassification/Models/Final

**Comment by Brett-Parker** [comment]
I have always used the default .zip. I think something like .mlnet would make a lot of sense and be an easy differentiator for viewing in a file explorer.

**Comment by jwood803** [comment]
> I have always used the default .zip. I think something like .mlnet would make a lot of sense and be an easy differentiator for viewing in a file explorer.

I wonder if something can also be made or added into Netron to recognize the `.mlnet` files to be able to double click on them.

**Comment by WalternativE** [comment]
Sensible change to not draw people's attention to the archive character of the file. I still enjoy the possibility to look at the contents, though (but I'm also a weird person unpacking JARs and DOCX files from time to time).

**Comment by saint4eva** [comment]
I would prefer .mlnet file extension. And it should have a good file extension icon for easy recognition on a solution explorer.

**Comment by briacht** [comment]
Thanks for the feedback everyone!

@luisquintanilla I think we can move forward with this - .mlnet

**Comment by praveenraghuvanshi** [comment]
A good move to get away from a generalized(*.zip) to a specific(*.mlnet) file extension.
- *.zip doesn't provide an intuition of what is present.
- *.zip can be easily interpreted as a compressed set of files
- *.mlnet is explicit in expression(type, technology)
- *.mlnet is easy to filter out from a set of given files which will eventually reduce error in applicatons.

Excited to see this change coming.

**Comment by luisquintanilla** [comment]
@luisquintanilla note to self: This is part of the improve code gen story

**Comment by beccamc** [comment]
@luisquintanilla How do you envision us incorporating this into the improve generated code? You want to start using .mlnet instead of .zip in the saved model?

**Comment by luisquintanilla** [comment]
> You want to start using .mlnet instead of .zip in the saved model?

Yup. That's right. As a first step it would be just changing the extension name.
