### ISSUE TITLE
MBConfig not being updated after running mlnet cli train command

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1739]
**Model Builder Version**: _main_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
when mlnet cli finishes training with existing mbconfig, the old mbconfig is not updated with new one.

**Steps to Reproduce**
- launch an experiment using mlnet cli(any scenario other than image classification)
- retrain with generated mbconfig.
- mbconfig is not updated after retraining.

**Comment by vzhuqin** [comment]
not repro this issue on mlnet:16.7.5
Steps:

1. launch an recommendation experiment using mlnet cli :
2. Open the generated ConsoleApp project in VS2019 and VS2022;
3. Open model builder and re-trained it after changed the data option and train time;
4. Save the model builder after completed training;
5. Open the mbconfig file, see the changes have reflected in mbconfig.
