### ISSUE TITLE
Update consume step app templates to .NET 6

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#1740]
This issue extends #1605 to include the console app template. 

Consider using these templates as reference. Thanks @timheuer 

Console App: https://github.com/timheuer/MLtoolingplayground/commit/1bb576fbaf3c4e11f6bfac9cc943cc760c342994?diff=split

Web API: https://github.com/timheuer/MLtoolingplayground/commit/5ac8c1b401fc6417b07651f7a407737df996cba7

**Comment by vzhuqin** [comment]
Verified this issue on ML.Net Model Builder 2022: 16.12.1.2206901
The generated ConsoleApp project is net6.0.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/20f02d73-c542-4bce-a76b-15a1f09af5c6)
