### ISSUE TITLE
"Machine Learning" option not available when trying to Add New Item in C# project

### ISSUE THREAD

**Issue by hariniramp** [dotnet/machinelearning-modelbuilder#1741]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: not relevant yet
 - Visual Studio Version (if applicable): -

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
- Clear description of the problem: On step 2 of the tutorial, it says you should select 'ML.net model' but this option is not available to me despite completing step 1.

**To Reproduce**
1. Right-click on the myMLApp project in Solution Explorer and select Add > Machine Learning.
2. In the Add New Item dialog, make sure Machine Learning Model (ML.NET) is selected. Check to see if this is even an option. It wasn't there for me.

**Expected behavior**
I expected to see ML.NET as an option to select when adding new item.

**Screenshots**
<img width="709" alt="ml net" src="https://user-images.githubusercontent.com/42644615/131179432-756b7445-a8b0-47b4-a9a6-9a14df7f06cd.PNG">

Above, I don't see the Machine Learning/ML.NET option specified in the webpage of the tutorial.

**Additional context**

**Comment by hariniramp** [comment]
How do I find the model builder version? I've tried several places but can't seem to find it. I'm also not sure how to find out if my project is net472 or UWP. Could you help with this?

**Comment by LittleLittleCloud** [comment]
You can find it in extension manager window (Extension -> Manage Extensions), then go to Installed.

![image](https://user-images.githubusercontent.com/16876986/131380955-ba14c061-de8d-4d02-9283-65519c25d64f.png)


To find out which type of project you have, you can go to the `.csproj` file and check out the `TargetFramework` value

**Comment by hariniramp** [comment]
Okay! The version for ML.NET is 16.1.0.2027905. The type of project is net5.0. Hope this helps!

**Comment by LittleLittleCloud** [comment]
The config-base training is not available in 16.6.1, could you update your model builder extension to 16.6.3 instead?

**Comment by beccamc** [comment]
@hariniramp We just shipped a new version. Can you try to download and install? https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by beccamc** [comment]
This is expected behavior for versions earlier than 16.6.0.2130907.  Please either update via the marketplace https://marketplace.visualstudio.com/items?itemName=MLNET.07, or use right click "Add Machine Learning"

If you've updated and don't see the "Add Machine Learning" option, please refer to our [troubleshooting doc](https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#i-cannot-add-machine-learning-to-my-project). 

Please ping if none of these things work!
