### ISSUE TITLE
This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by JReverse** [dotnet/machinelearning-modelbuilder#1742]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.6.3.2136603
 - Visual Studio Version (if applicable): 17.0.3172-preview3

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): On install
- Clear description of the problem: Can't install vsix

**To Reproduce**
1. Go to download
2. Click on download
3. Scroll down to on installer

**Expected behavior**
Extension installed

**Screenshots**
![image](https://user-images.githubusercontent.com/40630518/131197568-d5a55118-f987-4e15-9bed-b26a4dd0c662.png)

**Additional context**
None

**Comment by zewditu** [comment]
did you install visual studio 2019?

**Comment by JReverse** [comment]
> did you install visual studio 2019?

I'm using 2022 Preview ill try 2019 👍
