### ISSUE TITLE
The JSON-RPC connection with the remote party was lost before the request could complete.

### ISSUE THREAD

**Issue by Aze1337** [dotnet/machinelearning-modelbuilder#1743]
Hello, I have been trying to setup image classification model with two type of Classes (bananas and grapes, 1.5k+ images each)
but I've been getting random errors while training. It never gets to the point where it works. I have tried to google the errors with no luck every time.

I have tried to train with CPU, I would get errors.
So I have decided to try to set it up for GPU (RTX 2070 SUPER, all specs below in screenshot)
with no good results. would either end up with memory issues or the "JSON-RPC connection" error...

although it does says it's compatible
![image](https://user-images.githubusercontent.com/76887650/131231042-ce5d4e4f-8336-4e79-8c2c-a7cd51d88b10.png)

![image](https://user-images.githubusercontent.com/76887650/131230974-6f11fbbe-bbd8-4e32-9759-b82bca05532c.png)

![image](https://user-images.githubusercontent.com/76887650/131231004-ac528a71-6c48-490e-a6b3-052df9b14dad.png)

My computer specs - 

![image](https://user-images.githubusercontent.com/76887650/131230941-b312f8da-9d0e-445f-893a-f0e340ac7c28.png)

error I've been getting - "The JSON-RPC connection with the remote party was lost before the request could complete."
![image](https://user-images.githubusercontent.com/76887650/131230965-70db6532-91f9-45af-853c-0da7cee631d5.png)

Do anyone here have an idea of what I could be doing wrong ? 

Thank you very much!

**Comment by beccamc** [comment]
@LittleLittleCloud Another instance of https://github.com/dotnet/machinelearning-modelbuilder/issues/1712

**Comment by LittleLittleCloud** [comment]
Hi @Aze1337 

Let's track this issue in #1712

**Comment by Aze1337** [comment]
Hello @LittleLittleCloud ,

thank you for your response, I'll look into the other thread and see if it can help me.

I tried both CPU and GPU on the original post above, when I saw that CPU wasn't working. I installed everything for the gpu to be compatible , yet same errors...



also I just tried to load the folder with the data again and I get this..

 
![image](https://user-images.githubusercontent.com/76887650/131394106-5d921e05-406e-42ce-b0e9-e6cc0c92dbc7.png)


have to reboot computer a few times to magically get it to load once.  any workaround ?

thank you very much

**Comment by LittleLittleCloud** [comment]
> have to reboot computer a few times to magically get it to load once. any workaround ?
You can just kill the Servicehub.Host.CLR.x64.exe process in task manager

Back to the topic, How's your memory usage? I notice that the size of your image folder is really large, so it could be OOM which causes the training process to be terminated by OS. Could you check the memory usage  (Both memory and GPU memory) to see if there's a spike or massive grow before the exception?

Meanwhile, could you also try the image classification in mlnet-cli? The algo it uses is identical with Model Builder, except that it doesn't use servicehub. So it might get us more error information back.

**Comment by Aze1337** [comment]
> > have to reboot computer a few times to magically get it to load once. any workaround ?
> 
> You can just kill the Servicehub.Host.CLR.x64.exe process in task manager
> 
> Back to the topic, How's your memory usage? I notice that the size of your image folder is really large, so it could be OOM which causes the training process to be terminated by OS. Could you check the memory usage (Both memory and GPU memory) to see if there's a spike or massive grow before the exception?
> 
> Meanwhile, could you also try the image classification in mlnet-cli? The algo it uses is identical with Model Builder, except that it doesn't use servicehub. So it might get us more error information back.


I have recorded a youtube video from start to when it crashes with task manager being open.
what should I do tho ? let's say it's because of how big my folders are, how can I possibly lower it ? how much is enough ect ?
thank you very much
https://youtu.be/Ysd63RFUFQU
let me know if that's enough for you

**Comment by LittleLittleCloud** [comment]
@Aze1337 

Thanks for the video, from the stream it looks like the training has started ( I assume you are using CPU) for a while, and then gets terminated because of a reason that we don't know but very possibly the memory outage. To confirm it you can use mlnet.cli, which should throw exception while getting terminated.

**Comment by Aze1337** [comment]
@LittleLittleCloud In the video, I was using GPU training. Task manager gpu usage was mostly used by OBS (the screen recorder) though.


Thank you for the commands, I'm going to try it right now.

I've ran the image classification, I'll edit this post once It's done running

![image](https://user-images.githubusercontent.com/76887650/132105098-7fc343a5-74e2-4595-95d4-14c59095f215.png)

**Comment by Aze1337** [comment]
Edit - it just crashed - https://gist.github.com/Aze1337/2d25219822496af3195f76e842bf5459
@LittleLittleCloud

**Comment by LittleLittleCloud** [comment]
@Aze1337 
>  OP_REQUIRES failed at cast_op.cc:112 : Resource exhausted: OOM when allocating tensor with shape[4257,2833,3] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu

Like I said.. it's an OOM error which happens when it tries to allocate space for tensor [4257, 2833, 3]. It's possible that some of your images have very high resolution.

You can try resizing your images to a relatively small size (224 * 224) before training. It's also good for increasing batch size and training speed.

**Comment by Aze1337** [comment]
ok
