### ISSUE TITLE
Error with Dynamic SqlCommand Query with DateTime type

### ISSUE THREAD

**Issue by BeginTry** [dotnet/machinelearning-modelbuilder#1744]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.6.3.2136603
 - Visual Studio Version VS 2019 ~ 16.11.2

**Describe the bug**
- On which step of the process did you run into an issue: Train Model
- Clear description of the problem: a SqlCommand query fails when there is a space character in a column name. Here is the query that is failing:
<br/><pre>SELECT Eastern_Daylight_Time_240, 
	CAST(Memory_Available_MBytes as REAL), 
	CAST(Processor_Total_Pct_Processor_Time as REAL), 
	CAST(System_Processor_Queue_Length as REAL), 
	CAST(Buffer_Manager_Buffer_cache_hit_ratio as REAL), 
	721 Crossdock Error Fix,
	[&lt;other columns&gt;]
FROM [dbo].[PerfmonLogsSubset]</pre>

**Screenshots**
Here is an image of the error:
![image](https://user-images.githubusercontent.com/27367041/131234846-3e289bb5-0173-4d10-bfb4-89fa0f678056.png)

**Comment by beccamc** [comment]
Thanks for reporting @BeginTry! I assume you manually edited the query string in the .mbconfig file?

**Comment by BeginTry** [comment]
@beccamc: Hmmm. The query is in the _.mbconfig_ file? I didn't know that. :)

I ended up creating a VIEW on the TABLE using aliases that didn't require QUOTENAME.

**Comment by BeginTry** [comment]
I've tried some additional testing with 16.6.3.2136603 and now I am getting a new error. The SQL table I am working with has about 50k rows and is only about 10MB. I could dump that to a separate database and provide you with a native SQL Server backup. I'm happy to do that if desired.
![image](https://user-images.githubusercontent.com/27367041/131767632-766d81fb-b5bc-40a5-b617-128a70ee8a38.png)

**Comment by beccamc** [comment]
Thanks for the follow up. Sounds like you've unblocked yourself?

We've had problems converting SQL to types that ML.NET is happy with. I'll add this issue to the SQL improvement list for investigation.

**Comment by beccamc** [comment]
Two things going on here...
1. We should surface the SQL command and allow users to manually edit if they wish. https://github.com/dotnet/machinelearning-modelbuilder/issues/1935
2. We should add DateTime support for both SQL and text types. It's available in [DbType](https://docs.microsoft.com/en-us/dotnet/api/system.data.dbtype?view=net-6.0) and in [DataKind](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.datakind?view=ml-dotnet). IIRC this means we can add support directly.

**Comment by beccamc** [comment]
DataFrame problem blocked on https://github.com/dotnet/machinelearning/issues/6213

**Comment by beccamc** [comment]
Related https://github.com/dotnet/machinelearning-modelbuilder/issues/2084

**Comment by beccamc** [comment]
We just released an [update](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022) with DateTime support. Give it a try and let me know if it works? 

If it doesn't work, are you able to share a sample of your SQL data via mdf file?

**Comment by beccamc** [comment]
Confirmed through other customer issues that DateTime now works. Please let me know if you run into any problems in the future. Thanks!
