### ISSUE TITLE
Add link to consume code doc

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#1749]
Working on a how-to doc to show how to use code generated from Consume step in Model Builder. Add a link in Consume step to point to this doc. 

dotnet/docs#25795

**Comment by beccamc** [comment]
So we need Rohan to figure out how to display this? Or is this meant to be a link at the top?

**Comment by luisquintanilla** [comment]
Some guidance would help. Its "just" adding a link in the Consume Step, kind of like there's already links to docs in other screens, but help deciding where it's most efficient is appreciated :)

**Comment by beccamc** [comment]
@luisquintanilla What's the deal with this item?

**Comment by luisquintanilla** [comment]
@beccamc there's a draft but hasn't been published. Since we're tracking it on the docs repo, I'd be okay closing this issue.
