### ISSUE TITLE
Investigate perf of hiding ignored columns

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1756]
In [PR 1035](https://github.com/dotnet/machinelearning-tools/pull/1035) we removed Ignore columns for per reasons. 

We've gotten some feedback that it would be nice to have ignore columns. Reasons to change back... 
- Bri wants ignore column back
- The string explaining what users are seeing is clunky
- It was commented on in our user study

**This issue is to investigate the perf of ignore columns on a dataset of 10,000+**

**Comment by zewditu** [comment]
validated for bug bush build 
![image](https://user-images.githubusercontent.com/36615490/207456745-fef51b59-821e-4ea9-a146-ac8bdd1d317d.png)
