### ISSUE TITLE
Sometimes the tabs after data are disabled after reloaded model builder.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1758]
**System Information (please complete the following information):**
- ML.Net Model Builder: 16.7.4.2143102 (Main Branch)
- Windows OS: Windows-10-Enterprise-21H1
- Microsoft Visual Studio Enterprise 2019: 16.11.2

**Describe the bug**
- On which step of the process did you run into an issue: Reopen model builder after complete training
- Clear description of the problem: The problem does not occur 100%, I also found it by accident, then I tried the error rate, it was about 3/10.  At present, it is found that the error rate of "Data classification + SQL" is relatively high. See below GIF:
![Reopen SQL Data](https://user-images.githubusercontent.com/81727020/131804385-e063b038-cbbe-4bbc-9124-a60c9aac40ea.gif)

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data classification and SQL Server>Microsoft SQL Server Database File to input the data source;
5. Completed training;
6. Then save+close the model builder;
7. Reopen the model builder to observe all tabs are enabled;
8. Repeat steps 6+7, sometimes found that the tabs after data are disabled after reloaded model builder.

**Expected behavior**
Every time all tabs are enabled after reloaded one trained model builder.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/131804290-af8f6e87-9dd5-4532-889a-2a854390b1c1.png)

**Comment by beccamc** [comment]
@vzhuqin Is this still happening 3/10 times?

**Comment by beccamc** [comment]
Awesome! I love it when stuff gets fixed 😄
