### ISSUE TITLE
Warning MSB4011: "xxx.props" cannot be imported.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1762]
**System Information (please complete the following information):**
 - mlnet: 16.7.5

**Describe the bug**
- On which step of the process did you run into an issue: dotnet msbuild run.proj
- Clear description of the problem: please take a look at these warning, I'm not sure if the warnings are external issue?

**To Reproduce**

1. Install MLNet CLI: dotnet tool install mlnet -g --add-source https://mlnetcli.blob.core.windows.net/mlnetcli/index.json
2. Then launch an E2E test using the command: dotnet msbuild Run.proj
4. See warning MSB4011 as below screenshot.
![image](https://user-images.githubusercontent.com/81727020/131964471-abba68f0-68e0-4a53-ba7d-bd5dc27671e4.png)

**Expected behavior**
No msbuild warning

**Comment by LittleLittleCloud** [comment]
@vzhuqin 

This warning is not from mlnet/model builder. It simply means that "xxx.props" has been imported by other .props for multiple time and you can just ignore it.
