### ISSUE TITLE
The trainer number in "Top 5 models explored" doesn't match the experiment list.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1763]
**System Information (please complete the following information):**
- mlnet: 16.7.5

**Describe the bug**
- On which step of the process did you run into an issue: Experiment Results
- Clear description of the problem: please see below screenshot:

1. In the experiment list, the number with the highest score of 0.9598 is 26, but it is displayed as 24 in the "Top 5 Models Explored". 
2. Experiment number 1 and 12 are missing, issue 1 may be caused by this.
3. The bottom area shows an additional experiment 35. similar as issue #1746
4. Not sure how to calculate "Total number of models explored", because I met that total number of models explored not include the missing experiment. 
![image](https://user-images.githubusercontent.com/81727020/131977800-77975900-8788-4946-961b-05a964340a37.png)
![image](https://user-images.githubusercontent.com/81727020/131974563-85e41420-7518-4b6f-823e-fc5f6c69261f.png)
**Total number of models explored not include the missing experiment 9:**
![image](https://user-images.githubusercontent.com/81727020/131978542-92bd59d4-a26c-423d-a384-5b364a0a8f85.png)

**To Reproduce**

1. download taxi-fare-amount dataset
2. run command mlnet regression --dataset /path/to/taxi-fare-amount --label-col fare_amount --train-time 60
3. See the output result.

**Expected behavior**
The trainer numbers are not missing and not displayed additional experiment in output.

**Comment by zewditu** [comment]
@LittleLittleCloud  for visibility.

**Comment by beccamc** [comment]
@vzhuqin This looks very similar to https://github.com/dotnet/machinelearning-modelbuilder/issues/1746.  Can these issues be combined?
