### ISSUE TITLE
Show training time is not enough when open and re-train using Model Builder.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1764]
**System Information (please complete the following information):**

- mlnet: 16.7.5

**Describe the bug**
- On which step of the process did you run into an issue: open generated mbconfig then re-train using model builder with the same train time.
- Clear description of the problem: Completed the training with 60s in mlnetcli, but open the mbconfig in VS, show the training time is not enough in model builder. i see the dataset is over 40M, so i guess this behavior is expected, could you please help to confirm? 

**To Reproduce**

1. Launch a Regression experiment using mlnet cli;
2. Open the generated ConsoleApp project in VS2019 or VS2022;
3. Open the model builder and navigate to Train page;
4. Click "Train again" button with the same train time, prompts error dialog: the training time is not enough.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/131986084-c56050d6-f375-4227-a7fb-0d97b517ab76.png)

**Comment by beccamc** [comment]
Yes, this is expected. We warn the user in the UI that the training time might not be enough.

**Comment by beccamc** [comment]
I'm going to close this. @vzhuqin Let me know if you have other questions or want further explanation
