### ISSUE TITLE
Dataset displays null in Experiment Results Summary.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1771]
**System Information (please complete the following information):**
- ML.Net Model Builder: 16.7.4.2145201 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.11.2

**Describe the bug**
- On which step of the process did you run into an issue: Experiment Results Summary
- Clear description of the problem:

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Image classification + Local(CPU);
5. Completed training without error;
6. See output box: find that "Dataset" displays null in Experiment Results Summary.

**Expected behavior**
Dataset should be displayed in Experiment Results Summary.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/132190943-43a8a5d5-b4bd-4648-bdd5-1aa4041a148a.png)

**Comment by vzhuqin** [comment]
Also happen on SQL Server data source.
- ML.Net Model Builder: 16.7.4.2145601 (Main Branch)
![image](https://user-images.githubusercontent.com/81727020/132302436-799b4dbd-b5ab-4d86-83e9-871ec2b22a9e.png)

**Comment by zewditu** [comment]
@vzhuqin looks fixed in our latest main

**Comment by beccamc** [comment]
Closing as fixed on latest main per Zewditu
