### ISSUE TITLE
Model Builder for object detection

### ISSUE THREAD

**Issue by Su-Bi-su** [dotnet/machinelearning-modelbuilder#1772]
**Is your feature request related to a problem? Please describe.**

I want to detect objects on real time using USB Logitech camera. 
I collected data using the same USB camera and performed training using Model Builder. 
The result was quite good with over 90% accuracy. 
This was good until I want to detect object on an image. 
But I want to perform object detection on real time video captured by the USB camera. 
The Model Input from the Model Builder is a string, however the real time data is captured as Bitmap. 

**Describe the solution you'd like**

I would like to use this Bitmap data from live camera for the model input. 

**Describe alternatives you've considered**
I don't know if there is any existing solution for this. 
I have used Aforge to connect and capture video from the USB camera. Now I am not able to connect this captured data to the trained model to get my desired output. 

**Additional context**
I would be really grateful if someone can suggest me how to perform real time object detection using Model Builder.

**Comment by zewditu** [comment]
@Bhandari-Sushma could you refer to a related issue [here](https://github.com/dotnet/machinelearning-modelbuilder/issues/967)

**Comment by LittleLittleCloud** [comment]
@Bhandari-Sushma 

We are working on that, and you can track the update through #967 

For now, as a workaround, you can create a new pipeline which consumes the onnx model from azure and uses bitmap as input

```
public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
{
    // Data process configuration with pipeline data transformations
    var pipeline  = mlContext.Transforms.LoadImages(outputColumnName:@"input",imageFolder:@"",inputColumnName:@"ImageSource")    .Append(mlContext.Transforms.ResizeImages(imageWidth:800,imageHeight:600,outputColumnName:@"input",inputColumnName:@"input",cropAnchor:ImageResizingEstimator.Anchor.Center,resizing:ImageResizingEstimator.ResizingKind.Fill))      
                                    .Append(mlContext.Transforms.ExtractPixels(outputColumnName:@"input",inputColumnName:@"input",colorsToExtract:ImagePixelExtractingEstimator.ColorBits.Rgb,orderOfExtraction:ImagePixelExtractingEstimator.ColorsOrder.ARGB))      
                                    .Append(mlContext.Transforms.ApplyOnnxModel(modelFile:@"C:\Users\xiaoyuz\source\repos\ConsoleApp1\object-detection_ConsoleApp1\MLModel1.onnx"));

            return pipeline;
        }
```

**Comment by Bhandari-Sushma** [comment]
@LittleLittleCloud @zewditu  Thank you for your time. This work around seems to work for me.
