### ISSUE TITLE
远程服务器返回错误: (400) 错误的请求。 Experiment name must be 1-256 characters, start with a letter or a number, and can only contain letters, numbers, underscores, and dashes.

### ISSUE THREAD

**Issue by cagy520** [dotnet/machinelearning-modelbuilder#1773]
![image](https://user-images.githubusercontent.com/9970419/132434489-e13e509e-f3eb-454d-a248-3104ff1fa408.png)

看不出来什么原因
VS2019+modelbuilder
对象检测

**Comment by LittleLittleCloud** [comment]
实验名称暂时只能由字母，数字，下划线和短划线组成，你可以把对象检测换成 objectDetection试试

**Comment by cagy520** [comment]
OK   THX
