### ISSUE TITLE
Model Builder error to add Notebook  in consume page 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1774]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. select  any scenario 
2. Complete all the steps 
3 In consume page  click on "Add to solution"

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/e8e7aa16-ec1e-4de5-995e-75bb145cca24)
**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by JakeRadMSFT** [comment]
@zewditu I think this was fixed by 

https://github.com/dotnet/machinelearning-tools/commit/82260b0b11ed92d4b2bb66af61b8cf1cfacd3feb

Can you double check this still repros in Main?

**Comment by vzhuqin** [comment]
Adding a notebook encountered another model builder error, could you please take a look?
- ML.Net Model Builder: 16.7.6.2147201 (Main)
- Notebook Editor [Preview]: 16.6.0.2147206 (Main)
- microsoft.dotnet-interactive: 1.0.246601
- Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 4.1

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/fd900df1-4744-4b9e-bb16-4666870817ab)

**Comment by vzhuqin** [comment]
Can repro the error on: 
- Notebook Editor [Preview]:0.1.0.2147707 (Main)
- ML.Net Model Builder: 16.7.6.2147701 (Main)
