### ISSUE TITLE
Model Builder throws error when first trial encounters recoverable error

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1778]
Tracking from #1602 

When the first trial encounters a recoverable error (out of memory for instance), the experiment still fails because the pipeline suggestor was not initialized correctly. And when updating the pipeline suggestor with a fail trial, it throws a null object exception.

This issue is hard to reproduce because we always start from a small model. It should be able to triggered with a VM with small RAM and a large classification dataset with lots of different labels. For example, https://github.com/dotnet/machinelearning-modelbuilder/issues/1602#issuecomment-913391805

**Comment by vzhuqin** [comment]
Can repro this issue on: 16.9.1.2156904 (Main)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7593d92a-9422-4d3e-bd55-f0a58f30ca5f)

Column settings:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/50d5e407-d394-4ebd-ba94-ff77f896456f)

**Comment by LittleLittleCloud** [comment]
Looks like the error has been fixed since the exception is "Train time finish without any model trained", which is expected

**Comment by vzhuqin** [comment]
okay, move to "Read To Ship" as the exception is expected.
