### ISSUE TITLE
"Monitor current run in Azure portal" link is not displayed on Train page after re-open model builder.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1779]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder: 16.7.4.2145801 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.11.2

**Describe the bug**
- On which step of the process did you run into an issue: Train page after reloaded model builder
- Clear description of the problem: For Azure environment, after training complete, re-open model builder, find that "Monitor current run in Azure portal" link is not displayed.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Image classification + Azure environment;
5. After training complete, save and close the model builder;
6. Re-open the model builder and navigate to Train page, see that "Monitor current run in Azure portal" link is not displayed.

**Expected behavior**
"Monitor current run in Azure portal" link is displayed on Train page after re-open model builder.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/132813510-c27eb061-1fdd-4cb1-b116-dba7fd8b1521.png)

**Comment by beccamc** [comment]
We don't have the link to the training run anymore, so this is expected behavior.

**Comment by vzhuqin** [comment]
@beccamc , Do you mean the link will also be removed during training in the future?

**Comment by beccamc** [comment]
No, I phrased this poorly. The link to the training run isn't available on reload. We don't save it, and the run might not exist in Azure anymore.

**Comment by vzhuqin** [comment]
Understood, thanks becca's explanation.
