### ISSUE TITLE
Cannot add new item ML.NET in Visual Studio 2019

### ISSUE THREAD

**Issue by ekleiman22** [dotnet/machinelearning-modelbuilder#1783]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable): 16.11.2

**Describe the bug**
- On which page of the tutorial did you run into an issue [(URL):](https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create)
- Clear description of the problem: In the Add New Item dialog:  Machine Learning Model (ML.NET) is not shown in templates

**To Reproduce**
1. Go to '...'A new Console project was created, then "Right-click on the myMLApp project in Solution Explorer and select Add > Machine Learning." was done (see screen_1.jpg)
2. Click on '....'Then "Add New Item dialog" was clicked but no ML.NET template was not shown (see screen_2.jpg)
![Screen_1](https://user-images.githubusercontent.com/7485435/133121123-d15a3885-83b1-4734-9f5d-b76abe61d7ab.JPG)
![Screen_2](https://user-images.githubusercontent.com/7485435/133121127-ec7cc87d-b8cd-41b5-8380-c56f5609a73f.JPG)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@ekleiman22 thanks for reporting the issue.  Another customer also hit the same issue could you refer it [here](https://github.com/dotnet/machinelearning-modelbuilder/issues/1741).

**Comment by ekleiman22** [comment]
Thank you. I saw the issue you referred to. Then I  updated  Model Builder to the last version and now I succeeded to add .mbconfig file to my project.
