### ISSUE TITLE
Model Builder Error

### ISSUE THREAD

**Issue by DanielStaroscik** [dotnet/machinelearning-modelbuilder#1792]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.3.2143002
 - Visual Studio Version: Community 2019 16.11.3

**Describe the bug**
- An error occurred while trying to train the model.

**Screenshots**
![image](https://user-images.githubusercontent.com/57948564/133431616-14e248c6-c4e7-4b80-814b-0a6cc6d13d43.png)

**Comment by LittleLittleCloud** [comment]
Dup of #1778
