### ISSUE TITLE
远程服务器返回错误: (401) 未经授权。 AzureML.FailureCounter

### ISSUE THREAD

**Issue by cagy520** [dotnet/machinelearning-modelbuilder#1794]
An error is reported when training the model

远程服务器返回错误: (401) 未经授权。
在 AzureML.FailureCounter.<RecordFailureWithRetryWarningAsync>d__6.MoveNext() 位置 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/FailureCounter.cs:行号 48
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 AzureML.AutoMLRunMonitoringImages.<MonitorParentRunAsync>d__1.MoveNext() 位置 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunMonitoringImages.cs:行号 145
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 AzureML.AutoMLRunnerImages.<RunAutoMLAsync>d__24.MoveNext() 位置 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:行号 186
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.<ExecuteAsync>d__14.MoveNext() 位置 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:行号 62
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() 位置 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:行号 167   在 StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()

**Comment by zewditu** [comment]
@cady520, sorry for hitting this issue, which model builder version you used?

**Comment by cagy520** [comment]
![image](https://user-images.githubusercontent.com/9970419/133714005-6b843cdc-c097-4d9b-8d94-65c7237b1cb9.png)

I downloaded the model builder on September 7

**Comment by cagy520** [comment]
Run requested 1 node(s). 'okmining' cluster is resizing. Requested VM size STANDARD_NC6 is not supported.

I can't train the model

**Comment by cagy520** [comment]
> @cady520, sorry for hitting this issue, which model builder version you used?

model builder version:16.7.3.2143002

**Comment by cagy520** [comment]
I created a new azure account to solve this problem！！！

**Comment by beccamc** [comment]
@cagy520 Did you change the compute size too?

**Comment by zewditu** [comment]
Closed, no enough information was found from the user for further investigation.
