### ISSUE TITLE
Unable to load the service index for source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json.

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#1795]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.3.2143002
 - Visual Studio Version: VS2019 16.11.3

**Describe the bug**
- On which step of the process did you run into an issue: Train
- Clear description of the problem: When the model is done training, an error `Unable to load the service index for source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json` is thrown.

**To Reproduce**

1. Select **Data classification scenario**
2. Load the [wikipedia-detox-250-line-data.tsv.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7187176/wikipedia-detox-250-line-data.tsv.txt) dataset.
    1. Select **Sentiment** as the label column
    1. Open advanced data options
        1. Set **Sentiment** data type to **Boolean**
        2. Uncheck **Categorical** checkbox for **Sentiment** column
3.  Start training

**Expected behavior**
Return a binary classification model.

![image](https://user-images.githubusercontent.com/46974588/133825122-b4aaa47d-e305-45c0-a0bf-9fd2f317fdcf.png)

[BinaryClass-5137CH.txt Log File](https://github.com/dotnet/machinelearning-modelbuilder/files/7187196/BinaryClass-5137CH.txt)

**Comment by beccamc** [comment]
@LittleLittleCloud I have no idea. Do you have insight into this?

**Comment by luisquintanilla** [comment]
Something I noticed was, the error was thrown at the end of training and both the model and training / consumption codegen were created in the project as expected.

**Comment by LittleLittleCloud** [comment]
Looks like the error in from IVsPackageInstallerServices. Can you remove that feed and try again?

**Comment by beccamc** [comment]
@luisquintanilla Is this still happening?

**Comment by luisquintanilla** [comment]
@beccamc I was not able to repro. Closing for now. Thanks.
