### ISSUE TITLE
Workspace and Compute name should not be reset after clicking Edit workspace.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1800]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- Microsoft Visual Studio Enterprise 2019: 16.11.3
- ML.Net Model Builder: 16.7.6.2146601 (Main Branch)

**Describe the bug**
- On which step of the process did you run into an issue: Edit workspace
- Clear description of the problem: sometimes Workspace name is rest, sometimes Workspace name and Compute name are reset together.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Click Object detection and Azure Environment;
5. Set up the Azure Machine Learning workspace;
6. Click "Edit workspace" button, see error: Workspace name or/and Compute name are reset.

**Expected behavior**
All values are populated after clicking Edit workspace.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/134295739-153ea4e0-86d4-4175-85a3-436addcaab36.png)
![image](https://user-images.githubusercontent.com/81727020/134295702-54cd0558-dac3-436a-ad3e-148ed35904f9.png)

**Additional context**

**Comment by beccamc** [comment]
Yeah, this is a timing issue. You'll see them flash the correct value, and then it gets reset. Flaky, and doesn't happen all the time. Good find!

**Comment by beccamc** [comment]
Time box the investigation of this.

**Comment by luisquintanilla** [comment]
This issue is not a priority at this time. As we hear more, we can investigate and reevaluate.
