### ISSUE TITLE
Model Builder Error: "The remote server returned an error: (400) Bad Request." when creating Azure experiment on Russian VS.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1802]
**System Information (please complete the following information):**
- Microsoft Visual Studio Enterprise 2019: 16.11.3
- ML.Net Model Builder: 16.7.6.2147403 (Main Branch)

**Describe the bug**
- On which step of the process did you run into an issue: VS language setting is Russian > create Azure Experiment

- Clear description of the problem: Model Builder Error:  The remote server returned an error: (400) Bad Request. Experiment name must be 1-256 characters, start with a letter or a number, and can only contain letters, numbers, underscores, and dashes.

**To Reproduce**
1. Set VS language to Russian through: Tools>Options...>International Settings>Language；
2. Close and open Visual Studio 2019, select Create a new project from the start window;
3. Choose the C# Console App (.NET Core) project template with .Net 5.0;
4. Add model builder by right click on the project;
5. Select Object detection or Image classification scenario to navigate to Environment page;
6. Select Azure and click "Set up workspace" button to open Create new experiment dialog;
7. Click "Create" button after selected the options;
8. See error: Prompts Model Builder Error:  The remote server returned an error: (400) Bad Request. Experiment name must be 1-256 characters, start with a letter or a number, and can only contain letters, numbers, underscores, and dashes.

**Expected behavior**
No error when create Azure experiment on non-English VS.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/134879298-5c0b9ccd-dbbb-4de3-a843-82671a95ba6c.png)

**Additional context**
The Experiment name: "Objectdetection" and "Imageclassification" are translated, found that if renamed the Experiment Name with the beginning of English character,  this error is not prompted.

**Comment by beccamc** [comment]
Very nice find!

**Comment by beccamc** [comment]
We should update the name to their project name instead of "Object detection." Then the error experience is acceptable.

**Comment by beccamc** [comment]
This is updated!
