### ISSUE TITLE
Model Builder Error: "The method or operation is not implemented." when adding Notebook for SQL Data source.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1805]
**System Information (please complete the following information):**
- ML.Net Model Builder: 16.7.6.2147804 (Main Branch)
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 4.1
- Notebook Editor [Preview]:0.1.0.2147804
- microsoft.dotnet-interactive:1.0.247702

**Describe the bug**
- On which step of the process did you run into an issue: SQL Data Source>Adding Notebook on Consume page
- Clear description of the problem: see the error on SQL file, not occurs on File, Folder, Json data sources.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data Classification and SQL data source;
5. Navigate to Consume page after completed training;
6. Click "Add to solution" for Interactive Notebook, and click "Add to solution" on the prompted dialog;
7. See error: Prompts Model Builder Error: The method or operation is not implemented.

**Expected behavior**
No error when adding notebook for all supported data sources.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/135204337-b68bb362-466b-4076-b7a9-25f61d11051b.png)

**Error Log**
[SQLData_MLModel1-LV3CDO.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7248853/SQLData_MLModel1-LV3CDO.txt)

**mbconfig file**
[SQLData_MLModel1.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7248880/SQLData_MLModel1.zip)

**Comment by beccamc** [comment]
We need to make a decision on the experience for this before we ship. We could block SQL case as a short term solution.

**Comment by beccamc** [comment]
For V1 release, remove option for SQL and show a string stating it isn't supported (follow environment page)

for next release this is a P1

**Comment by beccamc** [comment]
SQL is now blocked.
