### ISSUE TITLE
Consume page controls background looks wrong.

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1807]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/5b002991-665b-46c6-a29a-0d0aea7bbc99)

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/187ea0ba-bf47-4b39-b803-f7eaa49ecf39)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
@zewditu If you're already looking at a fix for this and it's easy, feel free to just do it!

**Comment by zewditu** [comment]
It is blocked by  https://github.com/dotnet/machinelearning-modelbuilder/issues/1812. This needs to open the  solution in VS2022

**Comment by vzhuqin** [comment]
Not repro this issue on:
- ML.Net Model Builder: 16.9.1.2155901 (Main)
- Microsoft Visual Studio Enterprise 2022 (64-bit) - Current: Version 17.0.0

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/f91758b9-88f2-4a76-8be8-3cde2113133b)
