### ISSUE TITLE
ML.NET Getting Started Tutorial: Out of Date

### ISSUE THREAD

**Issue by bilalchraibi** [dotnet/machinelearning-modelbuilder#1811]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.1.0.2027905
 - Visual Studio Version (if applicable): Vs 2019 Version 16.11.3

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
- Clear description of the problem: Tutorial out of date

**To Reproduce**
1. Right click on the project (.Net 5) in vs that you want to add ML to it.
2. The new ML.NET Model Builder tab is different
3. ![image](https://user-images.githubusercontent.com/44674415/135657608-92eef9c4-c351-4c44-8ca4-4a2d112a8854.png)
4. We can clearly see that we have less option on the scenarios that are proposed.

**Expected behavior**
Update the tutorial to match the latest version Visual Studio and ML.NET Builder

**Comment by beccamc** [comment]
@bilalchraibi The included screenshot is of your screen right? The tutorial shows this for me, which is correct. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/1a4cb5d9-207f-49ed-8061-ffbeefe6c4d6)

The most recent version of Model Builder includes Object Detection in the "Train with your data" scenarios. If you don't see that, can you update here https://marketplace.visualstudio.com/items?itemName=MLNET.07

Thanks for reporting!

**Comment by luisquintanilla** [comment]
Thanks for reporting this.

The [scenario step](https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/scenario) in the tutorial looks mostly accurate (when it comes to # of scenarios). However, there are a few things that need updates.

- Update Text Classification to Data Classification
- Update latest version number.

![image](https://user-images.githubusercontent.com/46974588/135918661-68a2a350-acec-459b-a2be-d78dbf315fa9.png)

**Comment by bilalchraibi** [comment]
@beccamc I had a different behavior than the one described in the tutorial, even by having visual studio and the ML Builder up-to-date. 

After a restart of my computer, everything seems to behave properly, except for those small adjustments mentioned by @luisquintanilla :

- Update Text Classification to Data Classification
- Update latest version number

You can close the issue once it is fixed 😉
