### ISSUE TITLE
Considering include version as suffix for AutoML service name for each release?

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1814]
This is because VS use service name to locate AutoML service, so if more than one AutoMLService is installed on user's machine, it's very likely that VS loads the wrong one and might causes imcompatible problem.

Like this one
https://github.com/dotnet/machinelearning-modelbuilder/issues/1516#issuecomment-933132636

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud .... I think @beccamc added better error messages when the extensions don't match ... is that enough?

**Comment by beccamc** [comment]
Correct! Instead of "GPU extension is missing" it says "Installed GPU extension version must match Model Builder extension version. Please update both the extensions
in VS extension manager."
