### ISSUE TITLE
Cannot add Console app to solution and Code snippet is empty

### ISSUE THREAD

**Issue by gavinwilliams** [dotnet/machinelearning-modelbuilder#1822]
**Model Builder Version**:  16.7.6.2150501
**Visual Studion Version**:  16.11.4

**Bug description**
Cannot add Console app to solution and Code snippet is empty

**Steps to Reproduce**
1. Add Machine Learning to project
2. Select Image Classifier
3. Train using Local CPU
4. Select image folder
5. Train
6. Press next steps
7. Click next steps on Evaluate
8. The consume tab appears

**Expected Experience**
You can copy sample code and add a console app to the solution

**Actual Experience**Con
Sample code is empty and Visual Studio crashes when you try to add it to the solution

**Additional Context**
Happens on both Windows 10 & 11

![Capture](https://user-images.githubusercontent.com/611832/136622622-96b71ad5-1b1b-4970-9b2f-5bc9adb4d0c8.PNG)

**Comment by gavinwilliams** [comment]
> hmmm  ... I can only guess based on error message but ...
> 
> Did the data location move or change? Does your data preview work on the Data tab?
> 
> You might need manually modify the mbconfig to update the path. Apologies if that's the error you're hitting ... we should have a better experience.

Nope, location hasn't changed and the preview works on the data tab.

It's a brand new project. I also have the same issue as some others (in both VS 2019 & 2022 on multiple machines) where the add new model button just opens the new file dialogue.

This has only started happening with the latest update to model builder.

**Comment by beccamc** [comment]
I know this is an older issue, but @gavinwilliams are you able to share your dataset?

**Comment by luisquintanilla** [comment]
Hi @gavinwilliams 

We believe this may not be an issue since we've had many releases since it was originally reported. If you still continue having problems, please feel free to open a new issue.
