### ISSUE TITLE
An overwrite notebook dialog will prompt when it is added immediately after adding other project templates.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1829]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 4.1
- ML.Net Model Builder: 16.7.7.2150601 (Main Branch)
- Notebook Editor [Preview]: 0.2.0.2150901
- Microsoft.dotnet-interactive: 1.0.250604

**Describe the bug**
- On which step of the process did you run into an issue: add Notebook file dialog immediately after adding other project templates.
- Clear description of the problem: I found that: if you added one ConsoleApp or WebAPI project, then immediately add Notebook file, the overwrite notebook dialog will prompt; if the notebook file is added after the interval of 3-5s, the overwrite dialog will not pop up. 

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Choose Data classification to complete training;
5. Navigate to Consume page, add ConsoleApp, WebAPI, NoteBook project template in turn. 
6. See that: if the notebook file is added immediately after other project templates, will prompt an overwrite Notebook dialog.

**Expected behavior**
Should not prompt the overwrite notebook dialog even if there is no too long time interval between 2 projects additions.

**Screenshots**
![Overwrite issue](https://user-images.githubusercontent.com/81727020/136743046-9e6b6bb0-6820-44f0-9c06-3933fe220d1d.gif)

**Additional context**
this issue does not occur when ConsoleApp and WebAPI projects are added one after another.

**Comment by zewditu** [comment]
- Model builder version 16.9.1.2152802

- Notebook Editor [Preview]: 0.2.2.2152602

- VS 2022 preview 7.0
The original and blocker issues are not reproducible.

**Comment by vzhuqin** [comment]
Yes, not repro the original issues. I will open new issue for the new error dialog.

**Comment by vzhuqin** [comment]
update, @zewditu I met this issue on Value predication scenario, please take a look?
- Notebook Editor [Preview]: 0.2.2.2152602
- ML.Net Model Builder: 16.9.1.2155101 (Main)
[Dateset](https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv)
![Repro_1829.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/f5560c18-b942-46f0-a281-881d573c2dea)

**Comment by zewditu** [comment]
The original issue is resolved.  This is a separate issue.

**Comment by zewditu** [comment]
My previous comment was not correct, I did not reproduce it correctly.
The issue has happened when we add a notebook before the add console or webApi finishes.


![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/b9122c2e-d881-4483-8952-c05eb80c44c0)

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 
- Notebook Editor [Preview]: 0.2.2.2161502
- ML.Net Model Builder: 16.9.1.2161502 (Main)

Now "Project templates" area is disabled when adding one project.
![1829 fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7fd0748f-5340-4542-8f7c-707f2bb8f507)
