### ISSUE TITLE
For file data sources the default text  for selected file text box  is empty 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#183]
**Steps to Reproduce**
1. Right click on the project and Add > Machine Learning
2. select Scenario

## Expected Experience
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/009f4b21-d13d-4a49-8273-c4859f1e9a0e)

## Actual Experience
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/5b9d823a-187c-4b05-a91b-6a1a441a0832)
**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by greazer** [comment]
I'm not sure what we should default this field with.  It seems reasonable for it to be blank.
