### ISSUE TITLE
VS 2022 can not consume the model

### ISSUE THREAD

**Issue by eduardomoraes** [dotnet/machinelearning-modelbuilder#1833]
**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):  https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
- Clear description of the problem: When I click on 'start without debug' I receive a pop up message saying 'there were build errors', and it also ask me if I would like to continue and run the last successful build.  If I click yes, there is a second error pop up message that says 'The debug executable C:\.....myMLApp.exe path specified in the myMLApp debug profile does not exist. 
I've checked the path of the message, and the executable actually doesn't exist. I dont know what happened. Should I create this manually? Or there is a configuration I need to change?

**Expected behavior**
I should receive a output, predicting whether the input statement is positive or negative.

**Screenshots**
![image](https://user-images.githubusercontent.com/387542/137176676-71ccded3-f155-4daf-8f0a-1693820657b7.png)
![image](https://user-images.githubusercontent.com/387542/137176701-0bc5b9a7-b115-4f25-a621-9af7d6721039.png)

**Comment by zewditu** [comment]
@eduardomoraes, Sorry for the confusion actually it should also work for projects targeted to .net 6.
It might not be a wise solution but could you uninstall your vs and install it. I saw a similar issue online  https://stackoverflow.com/questions/61140481/visual-studio-debug-executable-specified-in-the-debug-profile-does-not-exist.
