### ISSUE TITLE
gifhuppp

### ISSUE THREAD

**Issue by gifhuppp** [dotnet/machinelearning-modelbuilder#1835]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@gifhuppp could you tell more about the issue you found to help you better?
