### ISSUE TITLE
Code changes aren't resulting in output changes.

### ISSUE THREAD

**Issue by JasonBock** [dotnet/machinelearning-modelbuilder#1836]
**System Information (please complete the following information):**
This bug isn't related to the Model Builder, but [this page](https://devblogs.microsoft.com/dotnet/ml-net-and-model-builder-october-updates/) said to add issues here, so....I am.

**Describe the bug**
I installed the Notebook Editor (0.2.02151216) in VS 2022 Preview 5.0. I added a notebook to a project, added this code:
```
Console.WriteLine("Hello");
```
But when I run it, it never finishes.

**To Reproduce**
See previous section

**Expected behavior**
The notebook is able to run C# code

**Screenshots**
![image](https://user-images.githubusercontent.com/904213/137191288-3e3267be-24c5-457b-ae5d-d0e0949ee1e7.png)

**Additional context**

**Comment by JasonBock** [comment]
I saw [this issue](https://github.com/dotnet/machinelearning-modelbuilder/issues/1825). My `dotnet interactive` version is `1.0.251301+06badd73c27d2c2065cf835ab7bd65bccd2339ee`, but I have the latest VSIX, so....should I "downgrade" `dotnet interactive` to `1.0.247702`?

**Comment by JasonBock** [comment]
At least the notebook is running now. I'll put in separate issues for behaviors I'm seeing.

**Comment by JakeRadMSFT** [comment]
Re-opening issue to use this as tracking the issue mentioned above.
