### ISSUE TITLE
Notebook File Doesn't Detect Changes

### ISSUE THREAD

**Issue by JasonBock** [dotnet/machinelearning-modelbuilder#1837]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): Notebook Editor: 0.2.0.2151216
 - Visual Studio Version - Version 17.0.0 Preview 5.0

**Describe the bug**
Changes aren't saved until I explicitly save the document.

**To Reproduce**
1. I open a notebook
2. I change code
3. I close the notebook
4. When I open the notebook, it doesn't have my changes.

**Expected behavior**
I'd expect either a dialog asking me to save my changes.

**Screenshots**

**Additional context**

**Comment by vzhuqin** [comment]
also repro on notebook editor: Notebook Editor [Preview]: 0.2.1.2151402
