### ISSUE TITLE
Unable to split the file provided into multiple, consistent columns.

### ISSUE THREAD

**Issue by fredrick72** [dotnet/machinelearning-modelbuilder#1839]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.6.2150501
 - Visual Studio Version 16.11.3

**Describe the bug**
- On which step of the process did you run into an issue: Model Training
- Clear description of the problem: While creating an image tagging project I hit an exception after the VOTT JSON transfer to Azure

**To Reproduce**
1. Select Scenario Object Detection
2. set up Compute Environment in Azure
3. Load VOTT JSON Data
4. Train
5. See Error

**Expected behavior**
model trained and code generation for detecting objects in images with outputs for tags.

**Screenshots**
![image](https://user-images.githubusercontent.com/9309073/137289484-74dbc240-66aa-4c33-8ea6-ecc4b57eea6a.png)

**Additional context**
VOTT JSON Data : 
[Tube_Detection-export.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7344776/Tube_Detection-export.zip)
[Tube_Detection-DH6DVH.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7344807/Tube_Detection-DH6DVH.txt)

**Comment by JakeRadMSFT** [comment]
@fredrick72 Can you walk us through the steps you took?

Did you choose Object Detection on the main page? This makes it seem like it's trying to parse as CSV/TSV which I think we only do for the other scenario types.

**Comment by LittleLittleCloud** [comment]
The error indicates that the file is not in a valid fix-width tabular format. It's probably something wrong when we transfer VOTT json into csv and saved in temp folder and it would be of great help if you can upload that file for us to debug. 

The csv file is in temp folder and has a format ${GUID}-object-detection.ImageTrainData.csv.

Regards
Xiaoyun

**Comment by beccamc** [comment]
Sorry for the problem here! Would be great to see the csv file is in temp folder and has a format ${GUID}-object-detection.ImageTrainData.csv.

**Comment by beccamc** [comment]
@v-Hailishi Can you try this with the data the customer originally included?

**Comment by v-Hailishi** [comment]
@beccamc The data the customer originally provided only contains a json file, there is no any picture.
Hence I cannot see the error the customer got.
<img width="854" alt="image" src="https://user-images.githubusercontent.com/99375895/174201919-ab8bfc90-57f3-42d5-ac78-9226ae99396e.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/99375895/174204188-bf11728e-7828-40c2-a65b-95142fe1d9fd.png">

**Comment by beccamc** [comment]
Sorry for the long delay here. @fredrick72 or @JackMutobu Are you still seeing this problem? If you are, can you zip a file with your data and upload it?

**Comment by beccamc** [comment]
Sorry, we don't have enough information to fix this. If this happens again please send us a zip with your data.
