### ISSUE TITLE
Model Builder reverted to the old version after updated another extension.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1842]
**System Information (please complete the following information):**

- Windows OS: Windows-10-Enterprise-21H1
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 5.0
- ML.Net Model Builder: 16.8.3.2151403 (Main Branch)

**Describe the bug**
- On which step of the process did you run into an issue: Model Builder version reverted to one older after update other extensions in Manage Extensions.
- Clear description of the problem:

**To Reproduce**
1. Open VS2022, see the current versions are: 
- ML.Net Model Builder 2022: 16.8.3.2151403 (main)
- Notebook Editor [preview]: 0.2.1.2151309 (main)
2. Now Notebook Editor has new version in Manage Extensions>Updates .
3. Updated Notebook Editor from 0.2.1.2151309 to 0.2.1.2151402
4. Open VS2022, see issue: Model builder reverted to one old version: 16.7.3.2143002

**Expected behavior**
Model builder version should not be changed after other extensions updating.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/137425962-a010204f-9f2e-413b-ad77-867a79c203c3.png)

**Additional context**

**Comment by vzhuqin** [comment]
This issue also occurs after updated VS version.

Update Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0  to Preview 6.0 from Preview 5.0

**Comment by JakeRadMSFT** [comment]
I'm able to reproduce this issue 100% of the time. I've tried to look for any shared/conflicting VSIX ID or Package IDs but everything looks good.

We'll need to reach out to VSIX installer team to understand what is happen here. Logs don't show anything useful.

**Comment by beccamc** [comment]
Relevant discussion: https://developercommunity.visualstudio.com/t/I-cant-update-this-latest-round-of-exte/1531088

**Comment by beccamc** [comment]
https://github.com/dotnet/machinelearning-modelbuilder/issues/1952
