### ISSUE TITLE
Should keep the focus on the newly added cell in the Notebook file. 

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1846]
**System Information (please complete the following information):**
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 5.0
- ML.Net Model Builder: 16.8.3.2151403 (Main Branch)
- Notebook Editor [Preview]: 0.2.1.2151402

**Describe the bug**
- On which step of the process did you run into an issue: add blank notebook or add new cell
- Clear description of the problem: the cursor is not focused on the newly added cell or the first cell of blank Notebook file.

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Right click the ConsoleApp project>Add>New Item...>Notebook;
4. See error: the cursor is also not focused on the first blank cell.
5. Add a new cell, also not has the cursor in it.

**Expected behavior**
should keep the focus on the newly added cell or the first cell of blank notebook file.

**Screenshots**
![not focus on new cell](https://user-images.githubusercontent.com/81727020/137453561-1affc88a-1e0d-4084-8b62-39078e61907b.gif)

**Additional context**
work in VS code.
![image](https://user-images.githubusercontent.com/81727020/137453194-0ed612ec-5896-40d8-87d6-b5bd6be3e61a.png)
![image](https://user-images.githubusercontent.com/81727020/137453371-e0645c9b-1822-4f4e-a12f-b4fe2c00ff40.png)

**Comment by beccamc** [comment]
https://github.com/microsoft/VS-Notebook/issues/91

**Comment by beccamc** [comment]
Oh wait, my mistake. This is fixed. Moving this issue to valid, and closing the issue in the notebook repo

**Comment by vzhuqin** [comment]
can repro this issue on latest main:
- Notebook Editor [Preview]: 0.2.2.2156601
- ML.Net Model Builder: 16.9.1.2156601
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/75a2ae3d-7f20-4aec-846d-624844f4709b)

**Comment by zewditu** [comment]
It is focused but the difference is the focus color  has issue in the dark team

**Comment by vzhuqin** [comment]
Not repro this issue on latest main:
- ML.Net Model Builder: 16.9.1.2160201 
- Notebook Editor [Preview]: 0.2.2.2160203
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/aba46c2a-b07d-486d-ade3-b21b751b032e)
