### ISSUE TITLE
Squiggles are not displayed for the code in errors in Notebook file.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1847]
**System Information (please complete the following information):**
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 5.0
- ML.Net Model Builder: 16.8.3.2151403 (Main Branch)
- Notebook Editor [Preview]: 0.2.1.2151402

**Describe the bug**
- On which step of the process did you run into an issue: The problematic code in the cell.

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Right click the ConsoleApp project>Add>New Item...>Notebook;
4. Write invalid code in the code cell, see that Squiggles are not displayed under the code.

**Expected behavior**
Display squiggles for the code in errors in Notebook file.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/137457928-1e8a9b70-c82b-4d53-b852-32f563eee7f7.png)

**Additional context**
Work in VS Code.
![image](https://user-images.githubusercontent.com/81727020/137457983-45135b04-a519-479c-969b-0db986504973.png)

**Comment by beccamc** [comment]
Moved to https://github.com/microsoft/VS-Notebook/issues/90
