### ISSUE TITLE
The result of running in the Notebook file does not display the string with <>. 

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1848]
**System Information (please complete the following information):**

- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 5.0
- ML.Net Model Builder: 16.8.3.2151403 (Main Branch)
- Notebook Editor [Preview]: 0.2.1.2151402

**Describe the bug**
- On which step of the process did you run into an issue: run the code in https://tinyurl.com/csharp-notebook10

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Right click the ConsoleApp project>Add>New Item...>Notebook;
4. Run below code;
![image](https://user-images.githubusercontent.com/81727020/137462918-4e2f0d8e-e440-4d53-b459-653360865a8e.png)

5. See issue: the string with <> is not displayed in the result.

**Expected behavior**
Display the string with <> in result.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/137463167-c76dc9fa-9355-4f3a-a95b-7e8cee044f49.png)

**Additional context**
Work in VS Code.
![image](https://user-images.githubusercontent.com/81727020/137463014-d5f2bbf1-d3ad-427c-87a8-fb0b8ac611e3.png)

**Comment by JakeRadMSFT** [comment]
Nice find! Anything that isn't coming back as html should be html encoded before we send it
