### ISSUE TITLE
Add notebook to Solution has Model Builder error 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1849]
**Model Builder Version**: 16.8.3.2151403
**Visual Studion Version**: 17.0.0 preview 4.1

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/cd53581f-128d-40ab-981d-168360419515)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by LittleLittleCloud** [comment]
tracking in #1884
