### ISSUE TITLE
Machine Learning Model (ML.NET) not there

### ISSUE THREAD

**Issue by SKYR0M** [dotnet/machinelearning-modelbuilder#1850]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 1.5.0-preview2
 - Visual Studio Version (if applicable): Version 16.8.6

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): Page 3 (https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create)
- Clear description of the problem: When I go to add 'Machine Learning Model (ML.NET), it is not in the list of options

**To Reproduce**
1. Right click on Project
2. Click on 'Add'
3. Click on 'New Item'

**Expected behavior**
An option to add Machine Learning Model (ML.NET) should be there

**Comment by beccamc** [comment]
Any update here? Are you willing to try a VS reinstall?

**Comment by SKYR0M** [comment]
Hi apologies for the inactivity 
It now works thank you!

**Comment by beccamc** [comment]
No worries - glad it's working!
