### ISSUE TITLE
Cannot stop cell execution during running cell in Notebook file.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1852]
**System Information (please complete the following information):**

- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 5.0
- ML.Net Model Builder: 16.8.3.2151403 (Main Branch)
- Notebook Editor [Preview]: 0.2.1.2151510

**Describe the bug**
- On which step of the process did you run into an issue: running any cell
- Clear description of the problem: it always displays the run cell icon when a cell is running. So cannot stop cell execution when you want to cancel it.

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Right click the ConsoleApp project>Add>New Item...>Notebook;
4. Write some codes in a cell;
5. Run the cell, see issue: The run icon is still displayed on the left side of the cell. 

**Expected behavior**
The icon on the left side of the cell should be changed to Stop Cell during running.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/137663208-881ce67a-5f4c-4b7c-83c2-2bedb3849b15.png)

**Additional context**
Work in VS Code.
![image](https://user-images.githubusercontent.com/81727020/137663241-fa845cc6-653e-4f6c-a173-e241b6126d51.png)

**Comment by beccamc** [comment]
Moved to https://github.com/microsoft/VS-Notebook/issues/88
