### ISSUE TITLE
Error "The name 'BinaryClassification' does not exist in the current context" when running the generated projects for Data classification scenario.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1855]
**System Information (please complete the following information):**
- ML.Net Model Builder: 16.8.3.2151403 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.11.5
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 5.0

**Describe the bug**
- On which step of the process did you run into an issue: run the generated projects for Data classification scenario
- Clear description of the problem:

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data classification to complete training;
5. Navigate to Consume page, add the projects to solution;
6. Run the generated projects, see error: The name 'BinaryClassification' does not exist in the current context

**Expected behavior**
No error when running generated projects.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/137705958-6f2e20e5-d669-41b0-893a-6067d2376d94.png)

**Additional context**
Occurs on VS2019 and VS2022.

**MBConfig file**
[Data_MLModel1.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7363554/Data_MLModel1.zip)

**Comment by LittleLittleCloud** [comment]
> @LittleLittleCloud still can repro this issue on latest main: 16.9.1.2152802, could you help to further take a look?

This error is the same with #1882, I'll close this issue and tracking the error on that thread
