### ISSUE TITLE
Sometimes prompt Model Builder Error when training Data classification scenario.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1856]
**System Information (please complete the following information):**
- Microsoft Visual Studio Enterprise 2019: 16.11.5
- ML.Net Model Builder: 16.8.3.2151403 (Main Branch)

**Describe the bug**
- On which step of the process did you run into an issue: training Data classification scenario
- Clear description of the problem: This issue doesn't occur 100%, it maybe completed without error when you train it again.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data Classification>Local (CPU)>File (.csv, .tsv, .txt) and input the data source;
5. Navigate to Train page, click "Start training" button;
6. Prompt Model Builder Error when the training is about be completed.

**Expected behavior**
No error during training.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/137710592-47e41280-4113-4c0e-8d6d-67891a38630b.png)

**Error Log**
[Sentiment_MLModel1-W9LV8R.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7363807/Sentiment_MLModel1-W9LV8R.txt)

**Comment by beccamc** [comment]
Need epic for Object null errors.

**Comment by beccamc** [comment]
This shouldn't be happening anymore per XiaoYun's change https://github.com/dotnet/machinelearning-modelbuilder/issues/1513
