### ISSUE TITLE
Bug in model builder during training

### ISSUE THREAD

**Issue by ffquintella** [dotnet/machinelearning-modelbuilder#1857]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_

16.7.6

**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_
2022 (but it also happens on 2019)

**Bug description**
_A clear and concise description of what the bug is._
I receive the message:

Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()

every time I try to train the model. It eventally finish training but I can't proceed to the next task in modelbuild workflow

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
I'm using image classification with xray images as the dataset. There are 2 main categories on the directories and about 1K images on each one 

2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by ffquintella** [comment]
yes there is an error dialog and a log file 

The error dialog can be seen on the following image 
![image](https://user-images.githubusercontent.com/4389839/137826026-f4a6b5d2-0d13-4294-a51d-9758bb0b22e3.png)

And the log file is:
[MLModel1-PNHWF3.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7369398/MLModel1-PNHWF3.txt)

**Comment by ffquintella** [comment]
Just to make it easier the first line on the error dialog means:
Object reference not defined to an object instance

**Comment by ffquintella** [comment]
I didn´t find anything relevant there but here it is 
[1d5d63e0-aa53-47df-ba66-5bb9e51c3b37-MLModel1.ImageTrainData.tsv.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7447959/1d5d63e0-aa53-47df-ba66-5bb9e51c3b37-MLModel1.ImageTrainData.tsv.txt)

**Comment by ffquintella** [comment]
Another version of the file form another tria
[7419ed04-e0c3-479d-9935-9d98aec92521-MLModel1.ImageTrainData.tsv.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7447961/7419ed04-e0c3-479d-9935-9d98aec92521-MLModel1.ImageTrainData.tsv.txt)
l

**Comment by beccamc** [comment]
@v-Hailishi Can you try the large image dataset locally as well?

**Comment by v-Hailishi** [comment]
@beccamc I only have the [weather](https://testpass.blob.core.windows.net/test-pass-data/weather.zip) dataset with 1125 images.
![image](https://user-images.githubusercontent.com/99375895/165508962-04b81842-fc94-4b2c-8193-75d797161d7a.png)
This weather dataset can be trained success on the latest main branch: 16.13.5.2222101.

If this dataset size is not enough laege, could you help to provide a larger image dataset?

**Comment by beccamc** [comment]
@LittleLittleCloud Did we release that fix that allows for training with many images? That was in the last release?

**Comment by luisquintanilla** [comment]
@LittleLittleCloud @beccamc are we okay to close this issue?

**Comment by LittleLittleCloud** [comment]
I think so

@ffquintella  feel free to reopen it if you see any other issues

**Comment by luisquintanilla** [comment]
Great! Closing the issue.
