### ISSUE TITLE
Azure Dataset support

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1865]
Option for working demo: Use pipeline to download the data to the correct place for training 
- [ ] Need relative file path: https://github.com/dotnet/machinelearning-modelbuilder/issues/1656
- [ ] Download the dataset with Azure ML CLI and place in relative path specified by mbconfig file

V0: Create new dataset each time. e.g. replace blob with dataset
V1: Add dataset support with UI

Design spec - https://www.figma.com/file/qFoQ4iC27jpNZb7CCuo7Hj/Model-Builder---RM?node-id=977%3A236411

**Comment by luisquintanilla** [comment]
Realted to #1587

**Comment by luisquintanilla** [comment]
Blocked by not being able to pass list of datasets to job. @zewditu to follow up.

**Comment by luisquintanilla** [comment]
Moving to MLTables instead. Closing issue for now.
