### ISSUE TITLE
JSON Deserialize error for image classification

### ISSUE THREAD

**Issue by Adevill20** [dotnet/machinelearning-modelbuilder#1868]
**System Information (please complete the following information):**
 - 16.7.6.2150501
 - Visual Studio Version 16.11.5

**Describe the bug**
- Once I've selected image classification and the folder containing the Microsoft demo flower images ( [https://docs.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-model-builder#data] ).
- At the training step, as soon as I've started the training process of the Model Builder I get the below error.

**To Reproduce**
1. Go to select image classification.
2. Use the Microsoft demo flower dataset.
3. Start the training process.

**Expected behavior**
Model should have been built without an error.

**Error Message**
Output of Model Builder Error:
Unable to find method 'StartTrainingAsync/1' on {no object} for the following reasons: Deserializing JSON-RPC argument with name "config" and position 0 to type "Microsoft.ML.ModelBuilder.Configuration.TrainingConfiguration" failed: {
  "IsAzureTraining": false,
  "OnnxModelPath": null,
  "OnnxModelLabelPath": null,
  "TaskType": null,
  "SubscriptionId": null,
  "ResourceGroup": null,
  "ExperimentName": null,
  "WorkspaceName": null,
  "ComputeTarget": null,
  "InputFile": "C:\\Users\\Anton\\AppData\\Local\\Temp\\39be53d6-3f97-4ef3-a675-78a8b0d46cad.tsv",
  "TestFile": null,
  "ValidateFile": null,
  "LabelColumn": "Label",
  "UserColumn": null,
  "ItemColumn": null,
  "Scenario": "image-classification",
  "TempOutputDirectory": "C:\\Users\\Anton\\AppData\\Local\\Temp\\MLVSTools\\LittleBirdieML",
  "TrainTime": 2147483,
  "Name": "LittleBirdieML",
  "Verbosity": "diag",
  "ModelPath": "C:\\Users\\Anton\\AppData\\Local\\Temp\\MLVSTools\\LittleBirdieML\\LittleBirdieML.Model\\MLModel.zip",
  "IgnoredColumnNames": [],
  "RemoteInputFile": null,
  "RemoteLabelColumn": null,
  "StablePackageVersion": null,
  "UnstablePackageVersion": null,
  "TrainArtifactLoaction": null
}

**Comment by beccamc** [comment]
Any update here? Can you upload your mbconfig file?

**Comment by beccamc** [comment]
Sorry, I don't have enough info to investigate this issue. If you're still having problems please ping me. Thanks!
