### ISSUE TITLE
ONNX model generation

### ISSUE THREAD

**Issue by peter249** [dotnet/machinelearning-modelbuilder#1870]
**Is your feature request related to a problem? Please describe.**
Would save all the bother of creating it in the code

**Describe the solution you'd like**
ONNX model generated by default - or at least available by option 

**Describe alternatives you've considered**
Creating it within the generated console app

**Additional context**
none

**Comment by luisquintanilla** [comment]
Thanks all for the discussion. Closing this issue for now since it's already being tracked in #2059
