### ISSUE TITLE
[Implementation] Refactor/improve async code (and synchronous code that should be async)

### ISSUE THREAD

**Issue by tbombach** [dotnet/machinelearning-modelbuilder#188]
We have a bunch of code that should be asynchronous. This will make it more clear that these calls can take a while and the UI needs to handle this. This task involves making sure all method calls up the chain are async as well. Be sure to follow [async best practices](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx).

- Any SQL calls should be made with `DbConnection.OpenAsync()`, `DbCommand.ExecuteReaderAsync()`, `SqlDataReader.ReadAsync()`, etc.
- Any file IO should use `File.WriteAsync()`

**Comment by greazer** [comment]
I don't want to spend the time doing this unless we have clear user scenarios that are suffering because we aren't async.

**Comment by JakeRadMSFT** [comment]
We've been resolving these as we go. Closing! Thanks!
