### ISSUE TITLE
Json file path picker wrong for Object detection.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1881]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2152802
 - Microsoft Visual Studio Enterprise 2019: 16.11.5

**Describe the bug**
- On which step of the process did you run into an issue: Object Detection>Data page>select a json file
- Clear description of the problem: Click "..." to select a json file, it is defaulted to Local Disk (C), not opened to last used location.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Object detection>Azure;
5. Navigate to Data page, input the json file, re-click "...", find that it isn't opened to last used location, it is defaulted to Local Disk (C);

**Expected behavior**
should be opened to last used location.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/139401358-73c8222c-c47a-4570-96f0-93e3b94cf425.png)

**Comment by LittleLittleCloud** [comment]
@beccamc

**Comment by beccamc** [comment]
@zewditu Is this a fast fix? Time box for 30 minutes?

**Comment by zewditu** [comment]
I think we fix the same issue with Image  data picker in this PR https://github.com/dotnet/machinelearning-tools/pull/1157

**Comment by beccamc** [comment]
I'm a little confused why we need to store the "LastUsedFolder" value. I would think the experience would be this...

- If there is a selected file/folder path, open to that location 
- If there isn't a selected path, open to wherever the folder picker wants to open. 

Instead I think the experience is that if there isn't a selected path, open to the "LastUsedFolder" according to the picker?

**Comment by beccamc** [comment]
Closing this as lower priority. Tracking in data tab p1/p2 issue to be picked up at a later time.
