### ISSUE TITLE
Code gen error on Titanic dataset

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1882]
**System Information (please complete the following information):**
 - Windows OS: Windows-10-Enterprise-21H1
 - Model Builder Version (available in Manage Extensions dialog): 16.8.3

**Describe the bug**
- On which step of the process did you run into an issue: build the generated consoleApp project for data classification.
- Clear description of the problem:

**To Reproduce**
1. Run MLNet.CLI Test Pass;
![image](https://user-images.githubusercontent.com/81727020/139404709-ca378054-d44e-4e7f-a4ea-141db9af2c16.png)

2. Create dotnet-tools.json for restoring local tools
dotnet new tool-manifest

3. Install mlnet cli: 
dotnet tool install microsoft.ml.modelbuilder.cli.win64
4. Then launch an E2E test using the following command:
dotnet msbuild Run.proj

**Expected behavior**
No error and warning while E2E test.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/139405218-dbd475c7-ce8d-48ba-b453-ea56323b6859.png)

**Additional context**
no error and warning for regression and recommendation scenarios.

**Comment by vzhuqin** [comment]
can repro this issue on latest mlnet: 16.9.2
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7021f1b1-b759-44f8-a869-94d6001c0692)
Titanic dataset:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/d833b400-05a9-4439-bd48-6e66737706c5)
True-car-listing dataset:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9bc3296e-4904-4fa1-94ac-113e17c23d4c)
recommendation-ratings-train dataset:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/65156398-6e84-4cc9-bc78-635da60250a1)

**Comment by LittleLittleCloud** [comment]
The building error is a restoration failure instead of code gen error, I'll open another thread to track that.
