### ISSUE TITLE
Image scenario - notebook generation is broken

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1884]
**System Information (please complete the following information):**
 - Model Builder Version: current main 
 - Visual Studio Version

**Comment by beccamc** [comment]
This should be in the next build we release right?

**Comment by LittleLittleCloud** [comment]
Yep

**Comment by beccamc** [comment]
Is this the same as https://github.com/dotnet/machinelearning-modelbuilder/issues/1890?

**Comment by LittleLittleCloud** [comment]
Nope,, should be a different issue

**Comment by LittleLittleCloud** [comment]
#1849

**Comment by vzhuqin** [comment]
Not repro this issue on latest main.
- Notebook Editor [Preview]: 0.2.2.2155404
- ML.Net Model Builder 2022: 16.9.1.2155901

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/950ecb18-9157-4b61-ac6a-6c57b24a0722)
