### ISSUE TITLE
Model Builder Error during training if the scenario is switched from Forecasting.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1888]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2152802
 - Microsoft Visual Studio Enterprise 2019: 16.11.5

**Describe the bug**
- On which step of the process did you run into an issue: Switched the scenario from Forecasting, continue the next steps, prompts model builder error during training.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. **Select Forecasting, then back to select any other scenario;**
5. Select the environment and Input the data set;
6. Navigate to train page to start training, prompt model builder error dialog: Unable to cast object of type 'Microsoft.ML.ModelBuilder.ForecastingTrainingOption' to type 'Microsoft.ML.ModelBuilder.Configuration.TrainingOption'.

**Expected behavior**
Switched the scenarios, no error on the next steps. 

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/139639661-9e3c7db7-e404-410c-85c0-67c68c2f440e.png)

**Additional context**

**Comment by LittleLittleCloud** [comment]
won't fix
It's expected in main branch since forecasting is still in progress.

**Comment by beccamc** [comment]
Can this be closed as the feature isn't finished yet?

**Comment by LittleLittleCloud** [comment]
Since we disable forecasting, this error won't exist for October release.
