### ISSUE TITLE
Running Web API fail for Image classification.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1889]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2152802
 - Microsoft Visual Studio Enterprise 2019: 16.11.5

**Describe the bug**
- On which step of the process did you run into an issue: Image classification (Local CPU)>PowerShell run the generated Web API project

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Image classification> Local (CPU) to complete the training;
5. Click Add to solution to add the project to your current solution.
6. Run the application.
7. Open PowerShell and enter the following code where PORT is the port your application is listening on.

$body = @{
     ImageSource = Image location on your local machine
}

 Invoke-RestMethod "https://localhost:PORT/predict" -Method Post -Body ($body | ConvertTo-Json) -ContentType "application/json"

8. Run fail as below message.

**Expected behavior**
Run successful, and display the expected output.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/139642202-d64f0928-dbd1-44d1-b2c0-f9496d427f50.png)

**Comment by zewditu** [comment]
@vzhuqin   is this issue only happens for local training ? or for both local and Azure?

**Comment by vzhuqin** [comment]
@zewditu  I tried on latest main: 16.9.1.2155801 just now, it happens on Image classification ( local and Azure) and Object detection scenarios. 
Image classification:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4a8f2aec-a8b3-4748-a0c2-65a5381f0917)
Object detection:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7cfcdeea-1587-42f8-90a6-3eb64e667ee6)

**Comment by zewditu** [comment]
Have you tried `ImageSource= (Bitmap)Image.FromFile(...)`? 
![image](https://user-images.githubusercontent.com/36615490/140890325-93913171-2dbd-4765-b66d-f2e84ddb6c62.png)

**Comment by vzhuqin** [comment]
I don't know why remove the character @ , then can run successfully? get the result as below, could you help to see if this is expected?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/870b5734-505a-4fc4-afd8-0fba684605d9)

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7e004e6f-36bf-45e0-81d6-284401285828)

And if this is expect, do i need to open a new issue to update the related doc: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-model-builder#web-api
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#web-api
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b84c8370-8d55-49f7-bb1f-c2b64d741340)

**Comment by LittleLittleCloud** [comment]
The post delegate in web api dev17 needs to be updated to
![image](https://user-images.githubusercontent.com/16876986/140989471-d774041e-8728-4046-a2e9-f534c8fd9138.png)

when scenario is azure image &&  object detection.

And when scenario is local image classification, using File.LoadAllBytes to load image
![image](https://user-images.githubusercontent.com/16876986/140989678-de5bb8cc-1559-4d10-b480-32ff029147a1.png)

The same change needs to be applied to dev16 as well

**Comment by LittleLittleCloud** [comment]
@luisquintanilla  @briacht 

It's really wield to me that web api using image path as input. It means that such prediciton will only applied on images with valid path in host machine. Should we allow user to upload image instead (maybe through media type)

**Comment by LittleLittleCloud** [comment]
@vzhuqin 

To verify web api project when it's image scenaio, please use
```
Invoke-RestMethod "https://localhost:44351/predict?imagePath=\path\to\your\image" -Method Post
```

instead

The output should looks like
![image](https://user-images.githubusercontent.com/16876986/140996083-ec4f4b64-4ab0-4363-9145-de3cae3c1927.png)

**Comment by luisquintanilla** [comment]
@LittleLittleCloud good question. Uploading files might make more sense. The only concern I'd have is testing. Once you have the code generated, PowerShell makes it easy to test. I assume you should be able to upload files with PowerShell, but it's something to look into.

**Comment by vzhuqin** [comment]
@LittleLittleCloud ,it met error with your provided method. But now can get below output with docs' method.
- ML.Net Model Builder: 16.9.1.2156701 (Main)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7b25bf0e-d973-4e44-9917-4dcf2309e7e6)

**Comment by LittleLittleCloud** [comment]
@vzhuqin  the fix is not merged in yet...

**Comment by LittleLittleCloud** [comment]
The fix should merge in

**Comment by vzhuqin** [comment]
@LittleLittleCloud , the new method still not work on latest build: 16.9.1.2205302 (main branch) and 16.11.0.2162702 (xiaoyun branch), could you take a look?
One example: Image classification>Azure environment
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/f9e8f593-5b78-456a-adba-818d81724aad)

**Comment by LittleLittleCloud** [comment]
@vzhuqin 

Try using `\\` to replace `\` for image path as `\` is escape character

**Comment by vzhuqin** [comment]
@LittleLittleCloud could you help to take a look where is wrong?
- ML.Net Model Builder: 16.12.0.2206201
- Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.4
- command: Invoke-RestMethod "https://localhost:44307/predict?imagePath=C:\\Users\\vzhuqin\\Downloads\\weather\\weather\\Cloudy\\cloudy1.jpg" -Method Post
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/d8e2471a-9d8c-4a56-96f3-045473c1bfd3)

**Comment by vzhuqin** [comment]
can repro on latest main: 16.12.1.2206901
using \\ to replace \ for image path.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/5e182e88-ad3e-42e0-87f8-6693a0a6949c)

**Comment by LittleLittleCloud** [comment]
It works well on my PC...

![image](https://user-images.githubusercontent.com/16876986/154366787-8213bf7d-b598-4c5c-a4f4-0fc02bdd58b2.png)


@vzhuqin 
can you confirm that your image url is valid, and is that azure training or local training

**Comment by vzhuqin** [comment]
@LittleLittleCloud Yes, I can confirm the image url is valid , and fail on Azure and local training.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/8968039f-8878-4d63-94bf-f1918817cbbb)

**Comment by LittleLittleCloud** [comment]
@vzhuqin I just merged another fix, can you try again

**Comment by vzhuqin** [comment]
@LittleLittleCloud  I tried on Image classification (Azure & Local CPU) and Object detection scenarios with latest main: 16.13.5.2212301, this issue not occurs on VS2022, but can still be reproduced on VS2019, please take a look?

- Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.1.0
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a48846c5-4e92-448a-a1e2-b461ce79022b)
- Microsoft Visual Studio Enterprise 2019: 16.11.10
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/724822dc-8f70-4439-bc4a-58cbb6309689)

**Comment by v-Hailishi** [comment]
@LittleLittleCloud 
I tried on Image classification (Azure & Local CPU) and Object detection scenarios with latest main: 16.13.5.2216501, this issue is not repro on VS2022, but **still repro on VS2019**.
![image.png](https://images.zenhubusercontent.com/62158d7f86929a769f3d134a/c778c85c-a10e-41bb-930e-b6c40a1fb61e)

**Comment by luisquintanilla** [comment]
Closing issue since it's been fixed.
