### ISSUE TITLE
Errors for running Notebook of Object detection.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1890]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2152802
 - Notebook Editor [Preview]: 0.2.2.2152602
 - Microsoft Visual Studio Enterprise 2022 Preview (64-bit): Version 17.0.0 Preview 7.0

**Describe the bug**
- On which step of the process did you run into an issue: run the generated notebook of Object detection.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Class Library (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Select Object detection to complete the training;
5. Add Notebook on consume page;
6. Open the Notebook file and click "Run All" button;
7. See some errors after complete running.

**Expected behavior**
No error after run Notebook files.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/139644960-a1a52e95-1d88-4156-8078-1682f6f2c932.png)
![image](https://user-images.githubusercontent.com/81727020/139645329-008e8f0d-83ba-423b-812a-6960ba4a95b4.png)
![image](https://user-images.githubusercontent.com/81727020/139645348-0e4e0535-602f-4364-9cad-c21b0e7c7cef.png)
![image](https://user-images.githubusercontent.com/81727020/139645358-bc775065-7567-4661-9563-81a79aea00b7.png)
![image](https://user-images.githubusercontent.com/81727020/139645366-0b95b9d9-ea56-4097-a6f0-ce0abbd9eb60.png)

**Comment by beccamc** [comment]
I'm getting a completely different error. I think @LittleLittleCloud You changed up what is generated, and some of the problems from before aren't even in the notebook anymore? 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/fc9d67a2-16c8-4220-b3d4-11edb58397e4)

My Onnx runtime can't find OrtGetAPIBase. Are we using the right version of the onnx runtime? [https://app.zenhub.com/files/186917455/a9a8c0e7-c66d-47b1-82d2-c304a6064149/download](https://app.zenhub.com/files/186917455/a9a8c0e7-c66d-47b1-82d2-c304a6064149/download)

**Comment by LittleLittleCloud** [comment]
Looks like an onnx runtime not matching error 

@beccamc Can you update onnxruntime to 1.9.0 and run notebook again

**Comment by beccamc** [comment]
I think we're already using 1.9.0 

![image](https://user-images.githubusercontent.com/9122518/141528117-1b818950-18e4-41a0-ab65-771cb0c1a00e.png)

**Comment by LittleLittleCloud** [comment]
Is that a new model or it's an old model but the notebook is newly generated

**Comment by LittleLittleCloud** [comment]
It looks like the generated object detection notebook is still the old one. Maybe that model builder doesn't include the notebook fix yet?

**Comment by beccamc** [comment]
Running main at 1f3565a0c5ca83bc2e026a4df7501de711b2520e (latest).  I used an old mbconfig file but re-trained the model so it should be brand new. I can start a new run if this seems to be using old bits somewhere.

**Comment by LittleLittleCloud** [comment]
Meanwhile, can you try using Microsoft.ML.OnnxRuntime.Gpu 1.9.0 and see if error gone

**Comment by beccamc** [comment]
Unfortunately Microsoft.ML.OnnxRuntime.Gpu 1.9.0 didn't fix it. Re-ran everything as well and it still produced the same notebook.

**Comment by beccamc** [comment]
Michael's fix https://github.com/dotnet/interactive/issues/967 didn't resolve the problem either. Attached notebook still produces error and I think its setup right (correct me if I'm wrong) 
[NewNotebook.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7549105/NewNotebook.zip)

![image](https://user-images.githubusercontent.com/9122518/142049224-86393a8c-d7d5-48ed-8743-2aa413b1bf7e.png)

**Comment by LittleLittleCloud** [comment]
@beccamc 

Maybe try this

``` csharp

static class Library
{
    const string LibraryName = "onnxruntime";
    static Library()
    {
        NativeLibrary.SetDllImportResolver(Assembly.Load("Microsoft.ML.OnnxRuntime"), ImportResolver);
    }
    // Dummy method to force static constuctor call.
    public static void DoNothing()
    {
        display("Inside do nothing");
    }
    private static IntPtr ImportResolver(string libraryName, Assembly assembly, DllImportSearchPath? searchPath)
    {
        var fullLoc = Assembly.Load("Microsoft.ML.OnnxRuntime").Location;
        var loc = fullLoc.Substring(0, fullLoc.IndexOf("microsoft.ml.onnxruntime.managed"));
        loc += @"microsoft.ml.onnxruntime/1.6.0/runtimes/";
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            loc += "win-x64";
        else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            loc += "linux-x64";
        else
            loc += "osx-x64";
            loc +="/native/onnxruntime.dll";
        IntPtr libHandle = IntPtr.Zero;
        if (libraryName == LibraryName)
        {
            NativeLibrary.TryLoad(loc, out libHandle);
        }
        return libHandle;
    }
}
// Dummy call to force static constuctor call.
Library.DoNothing();
```

**Comment by beccamc** [comment]
Let's discuss this with interactive team.

**Comment by beccamc** [comment]
@v-Hailishi Can you see if the Notebook generated for object detection is still broken?

**Comment by v-Hailishi** [comment]
The bug is not repro on the latest main branch 16.13.5.2225301 and notebook 0.3.1.2225313.
![image](https://user-images.githubusercontent.com/99375895/166861063-604bad1d-26ca-4faf-b294-5e0b76a96bfb.png)
