### ISSUE TITLE
Error messages in the notebook file cannot be copied and not wrap.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1891]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2152802 (Main)
 - Notebook Editor [Preview]: 0.2.2.2152602

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Class Library (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Select Object detection to complete the training;
5. Add Notebook on consume page;
6. Open the Notebook file and click "Run All" button;
7. See the error messages cannot be copied, and they are not wrap, so cannot see the full error message.

**Expected behavior**
can copy+paste the error message,  and the message will wrap if too long.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/139648387-1972d669-70b3-4bb2-9595-997b5002ce01.png)

**Comment by beccamc** [comment]
This should go in the Notebook repo. I've moved it - https://github.com/microsoft/VS-Notebook/issues/99

Thanks Qin!
