### ISSUE TITLE
Model builder error while generating notebook

### ISSUE THREAD

**Issue by gruxie** [dotnet/machinelearning-modelbuilder#1893]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2155101
 - Visual Studio Version:  VS 2022 / V. 17.0.0 Preview 6.0

**Describe the bug**
Created the ML SentimenetModel project through consume (did not create notebook)
Tested the code through 2-3 cycles
Returned to the .mbconfig file -> selected "Notebook" from consume sub-menu 
Observed:  VS had the error shown in the attached log file :  Error reading Object from JsonReader. Current JsonReader item is not an object: Null. Path 'TrainingOption', line 1, position 3986.

**To Reproduce**
1. VS2022, ML builder, Notebook editors are installed and updated in Extensions
2. Create ML model as shown here https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
2. Select "data classification" / Sentiment scenario 
3. Follow instructions through "Consume"
4. Select "Notebook" from project templates

**Expected behavior**
It would generate a notebook file as shown here:  https://devblogs.microsoft.com/dotnet/ml-net-and-model-builder-october-updates/

**Additional context**
See logfile attached:   
[sentimentModel-ZJHVGL.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7454859/sentimentModel-ZJHVGL.txt)
.

**Comment by LittleLittleCloud** [comment]
Looks like you are on our latest main branch which is unstable and might be buggy, could you try the one on market place?

**Comment by LittleLittleCloud** [comment]
#1884

**Comment by LittleLittleCloud** [comment]
Should already been fixed in the main branch
