### ISSUE TITLE
The JSON-RPC connection with the remote party was lost before the request could complete.

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1894]
**Model Builder Version**: Latest  main
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/2ba506a1-dc9c-45c7-bab9-be8c70a44db9)_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context*
This issue happens for Image classification, OD scenarios, and Recommendation scenarios

**Comment by LittleLittleCloud** [comment]
Can't reproduce it on main

**Comment by zewditu** [comment]
@LittleLittleCloud   Thanks to confirm it , it is not also reproduced in my latest main just in time.

**Comment by Cagatay342** [comment]
i got same error too. Train this data for 3000 seconds with default settings. I got that error in 2 different machine with same versioned visual studio
[closedPositions.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10368055/closedPositions.csv)

**Comment by gusztavj** [comment]
Same here. Training on the same TSV data set with very similar parameters using my own ML.NET code works fast and fine.
