### ISSUE TITLE
Should not have "Train in Azure" option on "Next steps" page for scenarios that do not support Azure.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1895]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2155101 (Main)
 - Microsoft Visual Studio Enterprise 2019: 16.11.5

**Describe the bug**
- On which step of the process did you run into an issue: "Next steps" page
- Clear description of the problem: "Train in Azure" option on "Next steps" page should only show for scenarios support Azure environment, but now exists on the scenarios don't support Azure.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data classification to complete training;
5. Navigate to "Next steps" page, see issue: there is "Train in Azure" option, but the scenario doesn't support Azure.

**Expected behavior**
"Train in Azure" option on "Next steps" page should only show for scenarios support Azure environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/139774768-3eab06a5-9fd3-4fa2-a5e6-d8d177ea0e16.png)

**Comment by LittleLittleCloud** [comment]
@zewditu Can you take a look?

**Comment by beccamc** [comment]
Why does this keep regressing?

**Comment by vzhuqin** [comment]
not repro this issue on scenarios which not support azure.
- ML.Net Model Builder: 16.9.1.2155801 (Main)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9decfe07-a771-4b84-9860-92dd000961ff)
