### ISSUE TITLE
VS will crash when clicking "Train in Azure" option.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1896]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2155101 (Main)
 - Microsoft Visual Studio Enterprise 2019: 16.11.5
 - Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 7.0

**Describe the bug**
- On which step of the process did you run into an issue: "Next steps" page
- Clear description of the problem: After training completed, navigate to "Next steps" page, clicking "Train in Azure" option, VS crashed.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Image classification>Local(CPU) environment to complete training;
5. Navigate to "Next steps" page, then click "Train in Azure" option, VS crashed.

**Expected behavior**
Jump to the Environment page after clicked "Train in Azure" option, so that can use Azure to start training.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/139776830-6936ac31-bb85-4db3-9db2-70756b72cc01.png)

![image](https://user-images.githubusercontent.com/81727020/139776743-25f20261-efb3-4e37-a31c-352949950849.png)

**Comment by LittleLittleCloud** [comment]
@zewditu Can you take a look?

**Comment by beccamc** [comment]
I couldn't get a repro of this on VS2022. From your notes it seems like it was happening on both? Can you try again Qin? 

![failureAzureNextSteps.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/f529ae56-1c72-4516-95c7-aa16ec8110f0)

**Comment by vzhuqin** [comment]
Hi @beccamc, I can repro it on VS2022, my environment is:

- Windows OS: Windows 11 Enterprise 21H2
- ML.Net Model Builder: 16.9.1.2155301 (Main)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/cfd4cf26-2113-4396-94e0-57f3dc0b7bdc)
- Microsoft Visual Studio Enterprise 2022 RC (64-bit): Version 17.0.0 RC3
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2856b504-3d41-4424-a517-5bbb1a018755)
![1896Repro.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b428ccdb-ad84-4373-a538-ebd4e1174972)

**Comment by beccamc** [comment]
@zewditu Can you check this on your Windows 11 OS? I don't have Windows 11 and I'm wondering if that is what is required for the repro.

**Comment by vzhuqin** [comment]
@beccamc , I prepared one Win10 machine today, still can repro this issue.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/1a973bb7-a95d-4120-acec-0ed6134e21b7)

- Windows OS:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2e7387a9-2251-45cc-9228-31410199b519)

- VS2022:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4c5e1b82-6448-4464-8d47-612d26942cfe)

- ML.Net Model Builder 2022: 16.9.1.2155501 (Main)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2189855f-d079-43d6-a83c-71e3d7e736ba)

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.9.1.2155801
- Windows OS: Windows 11 Enterprise 21H2
- Microsoft Visual Studio Enterprise 2019: 16.11.5
- Microsoft Visual Studio Enterprise 2022 (64-bit) - Current: Version 17.0.0
![Fixed 1896.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/bcccaaed-1ef7-4b4d-9543-1847d3b21d80)
