### ISSUE TITLE
Add Notebook overwrite  user answere NO shows error window 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1898]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1.select value prediction
2. Pass all the steps  Add notebook with the same name as the existed notebook
3. Click no in the dialog window 

**Expected Experience**
Back to the parent page/consume or Do nothing

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/d421f039-8d0d-4b2e-b408-a02413f4391c)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by vzhuqin** [comment]
can repro this issue on latest main:
- Notebook Editor [Preview]: 0.2.2.2156601
- ML.Net Model Builder: 16.9.1.2156601
![1898Repro.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/c2a77758-6988-4679-8f2d-49274e87d4c9)

**Comment by zewditu** [comment]
Fixed In the latest  main

**Comment by vzhuqin** [comment]
can repro this issue on latest main: 16.9.1.2156904
Similar as https://github.com/dotnet/machinelearning-modelbuilder/issues/1829
Scenario: Image classification>Local (CPU)
![1998 repro.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/79dd1e1a-29ed-445e-ba75-ad047b2c7433)

**Comment by zewditu** [comment]
I think this issue is not reproduced on this version, I will reopen  https://github.com/dotnet/machinelearning-modelbuilder/issues/1829

**Comment by vzhuqin** [comment]
Yes, not prompt error dialog after refuse overwrite notebook.
- ML.Net Model Builder: 16.9.1.2156904 (Main)
- Notebook Editor [Preview]: 0.2.2.2156601
![1898 fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3f3acac1-b898-4712-a430-6153405a99fc)
