### ISSUE TITLE
can not install ML.NET Model Builder 

### ISSUE THREAD

**Issue by dwanboweb** [dotnet/machinelearning-modelbuilder#190]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows10
I can not install this for VS2017(Community,15.9.14),and I got a log.
Thank you.
[VSIXInstaller_103e4f40-330e-4e8a-aa8e-f0fa43713d0b.log](https://github.com/dotnet/machinelearning-samples/files/3405924/VSIXInstaller_103e4f40-330e-4e8a-aa8e-f0fa43713d0b.log)

**Comment by zewditu** [comment]
I tried to reproduce the bug by installing Vs VS2017(Community,15.9.14)   on windows 10 clean virtual machine but I can install the latest Model Builder successfully .

**Comment by dwanboweb** [comment]
Maybe there are something wrong about my VS2017.Now I installed the VS2019  instead.Thank you
