### ISSUE TITLE
Azure portal link on Train page doesn't work.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1901]
**System Information (please complete the following information):**
 - Windows OS: Windows 11 Enterprise 21H2
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2155301 (Main)
 - Microsoft Visual Studio Enterprise 2019: 16.11.5
 - Microsoft Visual Studio Enterprise 2022 RC (64-bit): Version 17.0.0 RC3

**Describe the bug**
- On which step of the process did you run into an issue: Azure portal link on Train page
- Clear description of the problem: After set Image classification>Local (CPU)>Input dataset, back to change the environment to Azure and not change the Dataset, then start to train, click the Azure portal link on Train page, it doesn't work.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4.  Select Image classification>Local (CPU)>Input dataset;
5. back to change the environment to Azure and not change the Dataset;
6. Navigate to Train page, start to train, click the Azure portal link on Train page, find the link doesn't work.

**Expected behavior**
Azure portal link on Train page works.

**Screenshots**
![azure portal link not work](https://user-images.githubusercontent.com/81727020/140465795-d44364ee-f4ae-4019-b347-4b8053ee4969.gif)

**Comment by beccamc** [comment]
Does this not work for all Azure training, or only for this case of switch from local to Azure?

**Comment by vzhuqin** [comment]
@beccamc only happen when switch from local to Azure and not change dataset.

**Comment by zewditu** [comment]
@vzhuqin thanks for the confirmation.

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.9.1.2156701
![1901 fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/64ca01f1-860e-4b4b-b31a-a545e1594621)
