### ISSUE TITLE
Parameter name issue in the generated Model.training.cs file

### ISSUE THREAD

**Issue by flokie** [dotnet/machinelearning-modelbuilder#1902]
**System Information**
- Model Builder: 16.9.1.2155301 (Latest main)
- Visual Studio: 2022 Preview 6
- Scenario: Data Classification

**Describe the bug**
- It generates "ınputColumnName" instead of "inputColumnName". Probably because of my regional settings which is Turkish. It might be related as #1475

**Screenshots**
<img width="763" alt="Screen Shot 2021-11-05 at 11 18 42" src="https://user-images.githubusercontent.com/28707189/140482479-bcb145e2-ad64-45ad-a03c-dec0395217dc.png">

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.9.1.2156601
Region: Turkey
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2a9c13f3-b23e-408a-8fc9-000b4c270731)
