### ISSUE TITLE
Code generator - forecasting notebook

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1904]

**Comment by LittleLittleCloud** [comment]
[motor-vehicle.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7499685/motor-vehicle.txt)

**Comment by vzhuqin** [comment]
@LittleLittleCloud  could you help to provide the validate steps for this issue?

**Comment by LittleLittleCloud** [comment]
It's for me to tracking down code gen, you don't need to validate this
