### ISSUE TITLE
In VS 2022 generate .NET 6 projects

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1905]
For the Project templates in VS2022, Model Builder should generate .NET 6 projects (console app, web API)

We should also update the description:

![image](https://user-images.githubusercontent.com/10437687/140814771-472eabe9-4da2-45c1-83bc-a64eaf0eb3ef.png)

Console app: a .NET console app...

(not .NET Core)

Web API description can stay the same because it is still ASP.NET Core (with .NET 6)

**Comment by vzhuqin** [comment]
In VS2022, generated projects are .Net6 on 16.9.1.2156701 (Main)
ConsoleApp:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/99823fa8-5a79-44ac-b3a1-a1c3113e3d0a)
WebAPI:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/c4ad9efd-b3ae-4bf5-b6d8-8003d258ff57)

And have updated Console app: a .NET console app...
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a00e0785-6d9f-4399-9b57-3866f6836ba8)
