### ISSUE TITLE
Unable to update, uninstall or repair Visual Studio 2019 (package Model Builder not found)

### ISSUE THREAD

**Issue by jernejk** [dotnet/machinelearning-modelbuilder#1907]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.1.0.2027905
 - Visual Studio Version: 16.11.3

**Describe the bug**
- I tried to install the latest version of ML Model Builder and it failed for Visual Studio 2019
![image](https://user-images.githubusercontent.com/5943653/140874834-c24d2071-6baa-449b-a150-29cee074b319.png)

Log error:
> 9/11/2021 4:40:29 PM - Microsoft.VisualStudio.ExtensionManager.CorruptInstanceException: VSIX Installer has encountered a problem. To troubleshoot, follow the steps here: https://aka.ms/pc5ifb ---> Microsoft.VisualStudio.Setup.Dependencies.DependencyGraphConstructionException: The dependent package of 'Microsoft.VisualStudio.Product.Enterprise,version=16.11.31702.278' cannot be found: Component.Microsoft.ML.ModelBuilder,version=16.7.6.2150501.

- Attempted to remove Visual Studio 2019 Preview 16.11.3 Preview 5 (currently I have 2019, 2019 Preview, 2022 and 2022 Preview)
![image](https://user-images.githubusercontent.com/5943653/140875059-98521950-bb15-43c0-97b7-2e272df48400.png)

- Same issue when trying to update, uninstall, repair or modify VS 2019 or 2019 Preview
- I'm unable to manually install the extension either

**Expected behavior**
For update, uninstall, repair, modify and install extensions to work.

I want to clean up my laptop with stuff I no longer need. (updating to the latest would be nice as well)

**Additional context**
I had Visual Studio 2019 and 2019 Preview since January 2020 with the latest Model Builder.
I installed Visual Studio 2022 Preview on the day of release and used Model Builder on day 1.

The strange thing I noticed is that VS 2022 Preview has Model Build 2019 probably from the time when there was no Model Builder 2022 extension.
Visual Studio 2022 Current seems to be fine, using Model Builder 2022 and was able to update the extension just fine.

**Comment by zewditu** [comment]
@jernejk sorry for hitting these issues, 
I also had the same issue. I was not able to install ModelBuilder in Vs2019, I am not able to update and uninstall vs2019 with the same error message you found.
@JakeRadMSFT , @LittleLittleCloud  and @beccamc  do you have a context on this?

**Comment by JakeRadMSFT** [comment]
@jernejk sorry for the delayed response. I think this got a bit lost throughout the holidays!

Are you still hitting this issue? I've seen this before on VS 2019 but rarely. Can you try unchecking Model Builder from the VS installer and then re-install Model Builder from the Extension Manager or from the Marketplace?

**Comment by jernejk** [comment]
Sorry for the late response but yes, I still have the same problem.
I can't install, reinstall or remove [ML.NET](http://ml.net/) Model Builder which is also blocking update/repair/uninstall of both Visual Studio 2019 and Visual Studio 2019 Preview.

![image](https://user-images.githubusercontent.com/5943653/152933286-a82a4455-0246-4397-bb8b-b5ab55835044.png)
**Figure:** Error when I try to modify Visual Studio install.

![image](https://user-images.githubusercontent.com/5943653/152933634-bbdc3d90-734d-4992-9903-4f212929e6a7.png)
**Figure:** When trying to install [ML.NET Model Builder 2019](https://marketplace.visualstudio.com/items?itemName=MLNET.07)

Error in the logs:
```
8/02/2022 4:53:05 PM - Capping recursion at 5 directories in each extension root due to 'default limit'.
8/02/2022 4:53:05 PM - Found 'C:\USERS\JK\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_FE800197\EXTENSIONS\qiuzgy1g.mdj\extension.vsixmanifest'
8/02/2022 4:53:05 PM - Skipping 'C:\Program Files (x86)\Common Files\Microsoft\ExtensionManager\Extensions' as it doesn't exist
8/02/2022 4:53:05 PM - Skipping 'C:\Users\jk\AppData\Local\Microsoft SDKs' as it doesn't exist
8/02/2022 4:53:05 PM - The extension will be upgraded from version 16.1.0.2027905.
8/02/2022 4:53:07 PM - Microsoft.VisualStudio.ExtensionManager.CorruptInstanceException: VSIX Installer has encountered a problem. To troubleshoot, follow the steps here: https://aka.ms/pc5ifb ---> Microsoft.VisualStudio.Setup.Dependencies.DependencyGraphConstructionException: The dependent package of 'Microsoft.VisualStudio.Product.Enterprise,version=16.11.31702.278' cannot be found: Component.Microsoft.ML.ModelBuilder,version=16.7.6.2150501.
   at Microsoft.VisualStudio.Setup.Engine.Initialize()
   at Microsoft.VisualStudio.Setup.Engine.GetProducts()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.IntializePackages()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisitesInternal(IInstallableExtension extension, ICollection`1 installedPackages, ICollection`1 installablePackages, ICollection`1 unresolvedReferences)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisites(IInstallableExtension extension, IEnumerable`1& installedPackages, IEnumerable`1& installablePackages, IEnumerable`1& unresolvedReferences)
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Luckily, I don't use them anymore but they do take a considerable amount of space.
Is it possible to manually remove/add the extension?

**Comment by beccamc** [comment]
I know this is a very late reply, but for others running into this issue...

_Sometimes Model Builder doesn't update correctly and VS is still referencing older Model Builder code. If uninstalling and re-installing Model Builder doesn't work, or you find yourself in a strange VS state, we recommend doing a [clean install of VS](https://docs.microsoft.com/en-us/visualstudio/install/uninstall-visual-studio?view=vs-2019#remove-all-with-installcleanupexe)._
