### ISSUE TITLE
Rename .mbconfig file does not save the Model.zip file with the right name

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1908]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/73908327-68e7-4475-8d58-b8df06572e6f)_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.9.1.2156904 
![1908 fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ac01fe42-ec38-4568-9d9e-d0506e99f408)
