### ISSUE TITLE
Display error under "Consume the model" of Notebook for Data classification.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1909]
**System Information (please complete the following information):**
- Notebook Editor [Preview]: 0.2.2.2155404
- ML.Net Model Builder 2022: 16.9.1.2155901 (Main)
- Microsoft Visual Studio Enterprise 2022 (64-bit) - Current: Version 17.0.0

**Describe the bug**
After run the generated notebook of Data classification, find that error displayed under "Consume the model". 

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Class Library (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data classification to complete the training;
5. Add Notebook on consume page;
6. Open the Notebook file and click "Run All" button;
7. Error displayed under the "Consume the model".

**Expected behavior**
No error after run Notebook files.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/141263154-6967276f-1097-4c2b-a818-d078cfdbacc3.png)

**Comment by zewditu** [comment]
This issue is fixed in our latest main.

**Comment by vzhuqin** [comment]
Hi @zewditu , could you help to kick off one new main build? I see the top five main build are all failed. The latest main build is still 16.9.1.2155901

**Comment by zewditu** [comment]
@vzhuqin Yes, you are right it seems that our remote build fails as soon as we figured it out I will kick off a new build.

**Comment by vzhuqin** [comment]
@zewditu  failed again, could you take a look?

**Comment by vzhuqin** [comment]
@zewditu , i can repro this issue on latest main:
- Notebook Editor [Preview]: 0.2.2.2156601
- ML.Net Model Builder: 16.9.1.2156601
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/d9fddbd4-e0b6-404e-b98f-f7a2e5bbea26)

**Comment by zewditu** [comment]
@vzhuqin  you can update the version to 16.9.1.2156603

**Comment by vzhuqin** [comment]
@zewditu , does this issue not occur on your side? 
I still can repro it on latest main: 16.9.1.2156604
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/103ce0a9-e4e1-43d2-937d-d60efef869c1)

**Comment by zewditu** [comment]
@ vzhuqin,  Thanks for catching this issue yes still it is reproduced from my side too.

**Comment by zewditu** [comment]
it seems that we only use the mode output template for the Notebook ModenOuput generator.
the current  template is 
`[ColumnName("PredictedLabel")]
    public <#=LabelType#> Prediction { get; set;}
 public float[] Score { get; set;}`
 if we can update it to 
``[ColumnName("PredictedLabel")]
    public <#=LabelType#> PredictedLabel { get; set;}
 public float[] Score { get; set;}`` 
will fix this issue.
It seems that .net interactive does not know a name in the column name attribute.
@LittleLittleCloud  is there an issue that will be regressed because of this update or what do you think about making the .net interactive to react column name attributes?

**Comment by vzhuqin** [comment]
Not repro this issue on latest main:
- Notebook Editor [Preview]: 0.2.2.2156601
- ML.Net Model Builder: 16.9.1.2156904 
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a62c7b38-adbd-42b4-9a1b-bed1e799b14b)
