### ISSUE TITLE
ML Sentiment Model does not populate score

### ISSUE THREAD

**Issue by johndohoneyjr** [dotnet/machinelearning-modelbuilder#1915]
Microsoft Visual Studio Community 2022
Version 17.1.0 Preview 1.0
VisualStudio.17.Preview/17.1.0-pre.1.0+31903.286
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.1.125.8155
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.1.125.8155
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.1.125.8155
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.4000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.1.125.8155
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.4000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.1.0-1.21551.6+e4419d6f6792da7011c8589ba118f59d830ca72f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.21295.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure Hive Query Language Service   2.6.4000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.4000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Node.js Tools   1.5.31027.1 Commit Hash:dac60d9b246a1d6a5daf23d223c933dbe1518465
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python - Profiling support   17.0.21295.2
Profiling support for Python projects.

Python with Pylance   17.0.21295.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.0.0.2152601+724154d925d7d9d26ebf8a73a66d5219aa320400
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.1029.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-1.21551.6+e4419d6f6792da7011c8589ba118f59d830ca72f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.21525.2+46af4a248255f4af2284883f48983fe7dd07a760
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

****************************************************************************************************

**Describe the bug**

The Sentiment score is not being populated 

            Console.WriteLine($"Data to Analyze: ", sampleData.Col0);
            Console.WriteLine($"\n\nPredicted Sentiment: {predictionResult.Prediction}\n\n");
            Console.WriteLine($"\n\nPredicted score: {predictionResult.Score}\n\n");

Debugger shows:  "\n\nPredicted score: System.Single[]\n\n"

**To Reproduce**
1. Run the demo as is, behavior does not change with sentiment

**Expected behavior**
A sentiment floating point score between {0.0..1.0}

**Screenshots**
![image](https://user-images.githubusercontent.com/42818490/141600084-beb81a73-def7-40b6-af4a-70539d0f3792.png)

**Comment by zewditu** [comment]
Sorry for hitting this issue. 
Data classification we only show the predicted class if you want to see the probability of each label for a sample data you can look at on evaluating page. 

Do you want to see the probability of each class in Program.cs?
@briacht  what is your thought?

**Comment by beccamc** [comment]
@zewditu Was this a bug in code gen that has been fixed?

**Comment by zewditu** [comment]
yes, it is already fixed

**Comment by beccamc** [comment]
This should be fixed in the latest release. Please ping me if you are still having problems. Thanks!
