### ISSUE TITLE
Value Prediction model throws "Training time finished without any models trained" exception!

### ISSUE THREAD

**Issue by khteh** [dotnet/machinelearning-modelbuilder#1919]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.6.2152701
 - Visual Studio Version: 17.0.0
![image](https://user-images.githubusercontent.com/3871483/141888356-b83ffe3a-8244-4b3c-8fa6-db65aad85957.png)
[PricePredictionRegressionModel-YMJ982.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7543025/PricePredictionRegressionModel-YMJ982.txt)

**Describe the bug**
- On which step of the process did you run into an issue: I started and stopped the **FIRST** training before it completed and then started the training again and waited for it to run to completion and bump into this exception.
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by khteh** [comment]
I deleted the model builder file and do it again and the exception doesn't happen. This time, I didn't interrupt the **first** training but let it run to completion.

**Comment by beccamc** [comment]
@vzhuqin Can you try the first set of steps with the taxi fare dataset?

1. Start training with 600 seconds 
2. Stop this first training before it completes 
3. Start the training again. See if the exception happens.

**Comment by vzhuqin** [comment]
@beccamc this issue was not reproduced on latest main: 16.9.1.2156701, also completed training after trained again, please check below gif.
![not repro1919.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3cb16ccc-5204-4e66-af81-9be4e185a6e2)

**Comment by beccamc** [comment]
We don't have enough information to investigate this (no repro).  If the problem is still happening please let me know.
