### ISSUE TITLE
Tooltip for long/large text

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1920]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2156601 (Main)
- Microsoft Visual Studio Enterprise 2019: 16.11.5

**Describe the bug**
- Set environment size to 15
![image](https://user-images.githubusercontent.com/81727020/141934035-eed5a166-f384-4950-8476-9f01e0c2db56.png)
- On which step of the process did you run into an issue: "Add to solution" button
- Clear description of the problem: When increasing the font, the "Add to solution" buttons are not all displayed, and no display their tooltips when hovering on the buttons.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. After trained;
5. Navigate to Consume page, see that: the "Add to solution" buttons are not all displayed, and no display their tooltips when hovering on the buttons. 

**Expected behavior**
tooltips can be work if the text is not all displayed. 

**Screenshots**

![image](https://user-images.githubusercontent.com/81727020/141933378-fcca5370-003b-472c-b1fb-5b049992123a.png)

**Comment by vzhuqin** [comment]
Hi @beccamc , sorry for the delay, please see below issues on two environment sizes：
**Environment size: 20**
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/914b8e2b-c9bc-43ed-8e13-d3aab47469a4)
Scenario page:
1.Tags "Local", "Azure", "Example" are cut and no tooltips.
2.Text "Feedback" is cut and no tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ca456bf6-d7f2-4001-8ff1-109b23e35365)

Environment page:
1.Text "Environment" is cut and no tooltips.
2.For Image classification: the text "you need to decide if you want to train locally or in the cloud" is cut and no tooltips.
3.Text "Edit workspace" is cut.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/c53bfe7e-7687-41d8-9b7f-e51425edd3c3)

Data page:
1.For Image classification, the folder path and  the numbers of subfolders are cut and not tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/806e8ae2-9ec9-4bcc-850d-4267be6fab95)
2.For Object detection, the path of Json file and object name are cut.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b962d25f-d0eb-4548-aaa6-60947a8653b4)

Train page:
1.Tooltips is cut.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e5baaf40-b67e-41b0-83a2-6ba50a086e35)

Evaluate page:
1.For File type dataset, the text "Click Predict to see the predicted result" is cut and no tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/38413353-2697-4348-a5a9-a6440f188330)
2.For Object detection, object name "Stop-Sign" and number "0.3" are cut.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ed8dca44-b850-4835-807e-1b97317e7e98)

Consume page:
1.Text "Consume" is cut and no tooltips.
2.Text "Add to solution" is no tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/731db86b-2408-46f6-b843-802550d97859)

Next steps page: 
1.Text "Next steps" is cut and no tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9454be0e-0705-4ff6-af68-8c941d371d03)

**Comment by vzhuqin** [comment]
**Environment size: 24**
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/17553066-5105-45d6-9436-b28d3bd6e17c)

Environment page:
1.Text "Scenario" is cut and no tooltips.
2.Tags "Local", "Azure", "Example" are cut and no tooltips.
3.Text "Feedback" is cut and no tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ba3a07bb-877c-4d30-b008-2046ee6b56e9)

Environment page:
1.Text "Environment" is cut and no tooltips.
2.For Image classification, the description "you need to decide if you want to train locally or in the cloud" is cut and no tooltips.
3.For Local (GPU) environment, the text "Microsoft Remote Display Adapter" is cut and no tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/1f09e303-055a-4c28-9f90-e838f19b222f)
4.For Azure environment, the text "Edit workspace" is cut.
5.For Object detection, the text "Local CPU and GPU training are currently not supported for Object Detection scenario." is cut and no tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4cb56d16-bbe9-4ff6-86cf-6147bfeb9c9a)


Data Page:
1.For File dataset, the text "you must add data and choose your column to predict." is cut and no tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4b53cf6e-cd3e-4cb6-b1b0-4dc7113a82e8)

2.For Recommendation, the prompt text "Select column" and the tooltips of "User column" and "Item column" are cut.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/30b1ae77-daec-4c0d-9117-c0d9982ff5f7)
2.For Image classification, the folder path and  the numbers are cut and not tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/32337896-6e80-420e-a96e-8ff251dbc354)

3.For Object detection, the path and object name are cut.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3f92022e-11af-4697-b77e-105fbdadc3f9)

Train page:
1.For File dataset, tooltips on Train page is cut.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/9fac3789-4d7c-48aa-9a30-74345dfffe39)

Evaluate page:
1.Text "Evaluate" is cut and no tooltips.
2.For File dataset, text "Click Predict to see the predicted result" is cut and no tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/549b7797-8b27-4755-a07d-eb4a88460f69)

3.For Object detection, object name "Stop-Sign" and number "0.3" are cut.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/7484faf4-36eb-4967-97a8-7aefc5d0e538)

Consume page:
1.Text "Consume" is cut and no tooltips.
2.Text "Add to solution" is no tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/203e6ae6-3a03-4b77-a2d5-a0a6c8fd8b44)

Next steps page: 
1.Text "Next steps" is cut and no tooltips.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/8ffc138e-45c4-45cd-9f1a-eb750c25c909)

**Comment by beccamc** [comment]
@JakeRadMSFT FYI here is the tooltip issue.

**Comment by v-Hailishi** [comment]
The bug is not repro on the latest main build 16.17.0.2346401 on Visual Studio Enterprise 2019: 16.11.30.
Because after changing environment size, model builder pages have no change.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/18e2e03e-c7bd-4893-b7b5-40396e400e73)
