### ISSUE TITLE
Unable to load shared library 'lib_lightgbm' or one of its dependencies on Apple Silicon

### ISSUE THREAD

**Issue by Oluwasunmibola** [dotnet/machinelearning-modelbuilder#1922]
**System Information (please complete the following information):**
 - Model Builder or CLI Version:  16.2.0
 - Visual Studio Version (if applicable): 2019

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):  https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: Unable to load shared library 'lib_lightgbm' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblib_lightgb
m, 0x0001): tried: 'liblib_lightgbm' (no such file), '/usr/local/lib/liblib_lightgbm' (no such file), '/usr/lib/liblib_lightgbm' (no such file), '/Users/samiatbola-matanmi/Projects/mlnetprac/myMLApp/lib
lib_lightgbm' (no such file), '/usr/local/lib/liblib_lightgbm' (no such file), '/usr/lib/liblib_lightgbm' (no such file)
The type initializer for 'Native' threw an exception. 

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1440" alt="Screenshot 2021-11-17 at 9 47 23 AM" src="https://user-images.githubusercontent.com/36886456/142167478-c8fdcafe-b1fe-479f-bd99-214ad1c0025b.png">
<img width="1440" alt="Screenshot 2021-11-17 at 9 47 32 AM" src="https://user-images.githubusercontent.com/36886456/142167522-c4247130-a46c-4f76-a073-2fc9bf8319ee.png">

**Additional context**

**Comment by LittleLittleCloud** [comment]
ModelBuilder && ML.Net still uses Lgbm 2.3.1, which doesn't support M1 if I recall correctly. @michaelgsharp might know more.

**Comment by michaelgsharp** [comment]
Just checked, even the latest version of LBGM doesn't have pre-compiled bits for the M1. We can't add support till they do.

**Comment by LittleLittleCloud** [comment]
Closing the issue since there's no roadmap for that for now.
