### ISSUE TITLE
Training continues without horizon value entered

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1927]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/a555b5c2-f0b0-4976-b4e2-60cf4cac7094)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.12.2.2207601
The default value is 10:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/74f3f234-3f2f-463c-9184-3865ce43dd9e)
