### ISSUE TITLE
'Input string for '...' is not in the correct format' getting this error when trying to evaluate the model

### ISSUE THREAD

**Issue by sairaj-badam** [dotnet/machinelearning-modelbuilder#1928]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.6.21.50.50.1
 - Visual Studio Version 16.11.7

**Describe the bug**
- On which step of the process did you run into an issue: After clicking 'Pridict' in step 5. Evaluate
- Clear description of the problem: Unable to Evaluate the model with sample data 

**To Reproduce**
1. Go to 'ML.NET Model Builder'
2. Click on 'Text Classification Scenario'
3. Select 'Local' and click on 'Data'
4. Provide .CSV file (sample file attached), select input and outputs, Train the Model and click pridict 
5. See error - 'Input string for the morning is not in the correct format at system.... complete error attached.

**Expected behavior**

Get the prediction for the given sample input

**Screenshots**

**Additional context**
[New Microsoft Excel Worksheet.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/7594511/New.Microsoft.Excel.Worksheet.csv)
[ML MB-Error.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7594524/ML.MB-Error.txt)

**Comment by zewditu** [comment]
The issue is not reproduced in the latest model builder 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/ff473628-06c8-44c8-9d8d-08b05b9edbbb)
