### ISSUE TITLE
Forecasting - Can't process file while being used by another process

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#1931]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.10.1.2158002
 - Visual Studio Version: Visual Studio 2022 Preview 2.0

**Describe the bug**

File being used by another process error thrown even though the file is not open anywhere when choosing time series column.

**To Reproduce**

In Data step of Forecasting scenario, try choosing the Time Series column from the dropdown or checking the "Use default index as time column" checkbox.

**Screenshots**

![image](https://user-images.githubusercontent.com/46974588/144129519-294a42b8-b156-4616-b394-e52341553c4c.png)

**Comment by LittleLittleCloud** [comment]
Can't reproduce any more, maybe it's been fixed,
