### ISSUE TITLE
Time series column tooltip should not be the same as label column  tooltip

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1932]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/e745a1ea-fc3f-4d50-9293-f3819ad08cbb)
**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by LittleLittleCloud** [comment]
@romalpani  @JakeRadMSFT 

Any idea what time column tooltip should look like?

Maybe something like 

This is the target column that you want to specify the datetime column in the input data for building the time series.

**Comment by vzhuqin** [comment]
not repro this issue on latest main:  16.12.2.2207601
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ee7b5524-f662-496b-99d8-3f2b4b36810d)

**Comment by romalpani** [comment]
@LittleLittleCloud 
Let's rename the label to "Time column". Calling it that is self-explanatory as to what that selection would mean. In which case we can get rid of the info-tip. 

![image](https://user-images.githubusercontent.com/48927690/151604917-61786d9a-2e56-44c5-a0c1-27f2e90d6e75.png)
