### ISSUE TITLE
Holding UI thread while opening file 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1933]
When I opened a forecasting file VS gave me a disabled message. It showed the busy spinner and eventually went gray.  

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/157780af-7ef7-4587-8653-455402adb03b)

I can share the file if there isn't a repo.

**Comment by LittleLittleCloud** [comment]
Can't reproduce any more, maybe it's been fixed.

**Comment by beccamc** [comment]
Okay let's close this!
