### ISSUE TITLE
Custom SQL Queries

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1935]
## Goal

Allow users to specify a custom SQL query instead of generating our own. 

## Current experience

Currently users can manually edit via the mbconfig. 

## Proposed implementation

We should surface this ability in Advanced Data Options. 

Options:

| Options | Pros | Cons | 
| --- | --- | --- |
| Any raw SQL query | User is in full control of how they query and structure their data | Adds more complexity to UI experience for complex SQL queries (JOINS) | 
| Only SELECT statement | UI experience remains mostly the same while allowing some degree of customization | User has to save query to View / Table before querying it with Model Builder | 

## To-Do

@beccamc 

- [ ] Investigate experience and limitations of using more complex SQL queries

@luisquintanilla 

- [ ] Get feedback from the community

**Comment by beccamc** [comment]
I'm leaning more towards creating a sample notebook with this information. Then users have the code to do anything and we don't need to support as much UI in Model Builder.

**Comment by luisquintanilla** [comment]
@beccamc let's start with a notebook and reevaluate based on feedback. Issue to remain open to track Notebook work.

**Comment by luisquintanilla** [comment]
@beccamc @luisquintanilla to draft UI for advanced data options in Model Builder.

**Comment by luisquintanilla** [comment]
Enabling this would require placing several constraints on users and additional engineering work to validate those constraints are satisfied. Instead we will focus on improving current experiences and document best practices for custom / complex SQL scenarios. Closing in favor of #1761
