### ISSUE TITLE
[Implement] Code generation improvements

### ISSUE THREAD

**Issue by greazer** [dotnet/machinelearning-modelbuilder#194]
See issue #76 for details

**Comment by JakeRadMSFT** [comment]
See #76 for Spec

**Comment by LittleLittleCloud** [comment]
- [x] add class `ConsumeModel` and update `Program.cs`
- [x] using different annotation head for CLI and ModelBuilder
- CLI : This is an auto-generated file by Microsoft ML.NET CLI (Command-Line Interface) tool.
- MB: This is an auto-generated file by Microsoft ML.NET Model Builder.

**Comment by LittleLittleCloud** [comment]
Changes need to be done on MB side
- [ ] see the additional code with syntactic code colorization which is consistent with current theme. (Require design? @greazer )
- [ ] add telemetry

**Comment by LittleLittleCloud** [comment]
## P0 requirements
see the [spec document](https://microsoft-my.sharepoint.com/:w:/p/brachtma/EVOoEe-O5xFOt-HZg8T_nbMB-Z9Bgigk_c_VWIC2KF5oDg?rtime=1QFpEo8b10g). The one with a `[done]` annotation means it has been implemented
