### ISSUE TITLE
Notebook is available for SQL 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1940]
I chose a Text Classification scenario with SQL. Add Notebook is an available option. It should be disabled.

**Comment by beccamc** [comment]
Looks intermittent 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/099ea9db-170e-4c55-8b2d-139a4ad33a4e)

**Comment by beccamc** [comment]
@vzhuqin Can you try to get a repro of this?

**Comment by luisquintanilla** [comment]
@beccamc this issue looks like it's ready to close.

**Comment by beccamc** [comment]
@luisquintanilla As long as we are okay with this not being supported yet!

**Comment by luisquintanilla** [comment]
Thanks for closing @beccamc. Yes. I think this is okay for now and we can discuss this as part of a larger SQL improvement story.
