### ISSUE TITLE
I couldn't see the .NET 6 Framework to choose. I've installed it. I installed VS 2022 community version.

### ISSUE THREAD

**Issue by CommandoHuan** [dotnet/machinelearning-modelbuilder#1942]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
@CommandoHuan sorry you've run into a problem! Can you provide more details on what you're trying to do or repro? Is the problem with the generated Console App or Web API? Or are you trying to add Model Builder to a .NET 6 project?

**Comment by beccamc** [comment]
Any update here?
