### ISSUE TITLE
Pre-filled the row 2 data on Evaluate page.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1946]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2160801
 - Microsoft Visual Studio Enterprise 2019: 16.11.7

**Describe the bug**
- On which step of the process did you run into an issue: Evaluate page
- Clear description of the problem: this is bug regression: https://github.com/dotnet/machinelearning-modelbuilder/issues/1714

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data predication and Local (CPU) environment;
5. Input the dataset and complete the train;
6. Navigate to Evaluate page, find that pre-filled data is not the first row.

**Expected behavior**
As described, the first row of data is pre-filled.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/145322010-eade826d-3cea-4c62-93ae-e3f893552306.png)
![image](https://user-images.githubusercontent.com/81727020/145322019-d6c0f0b1-4370-494c-a078-06afffa76d71.png)

**Comment by beccamc** [comment]
I think we've had issues with the row number of this before. Is this really providing the customer with useful information? Realistically what is a customer doing with the exact row number... if I want to open the file and look at my data I would pretty easily see it in the first 10 rows. 

@briacht and @romalpani What do you think about removing the row number and just saying "The following fields below are pre-filled by a row of your data."  

If we think this provides a benefits we can leave it. IMO it's very small benefit compared to the number of times we've had to fix a row number bug.

**Comment by zewditu** [comment]
I think it would be nice to point it is in the top ten rows of the data  by saying maybe  "The following fields below are pre-filled by a row from the top ten  of your  data ."

**Comment by beccamc** [comment]
@zewditu Do you have a PR our for this or should I ping Luis about changing it to the generic message?

**Comment by beccamc** [comment]
Change to say "The following fields are pre-filled by a row of your data."

**Comment by romalpani** [comment]
Jumping in a bit late here. 
I do agree with you @beccamc  - just keeping it generic is alright. But if we are certain that it would be one of the first 10 rows, then we should mention that too, as per @zewditu 's suggestion.

**Comment by luisquintanilla** [comment]
This issue has been labeled as stale and it looks like we already have a resolution for it. Closing it for now but if there's anything else we need to address we can do so in a new issue.
