### ISSUE TITLE
Run errors for the generated ConsoleApp project of Object detection scenario.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1948]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2161301
 - Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.2

**Describe the bug**
- On which step of the process did you run into an issue: Run the generated ConsoleApp project of Object detection
- - Clear description of the problem: **not sure if the issue is caused by the name "Object.mbconfig"? Because it is not be reproduced when the model builder is named "OD.mbconfig", please take a look?**

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project, and named "Object.mbconfig";
4. Add ConsoleApp project to solution after trained;
5. Run the generated ConsoleApp project, it displays error: Object' is an ambiguous reference between 'Object_ConsoleApp1.Object' and 'object'

**Expected behavior**
No error during running the generated projects.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/145923294-da7d7520-8cff-4824-8f55-635ba570f364.png)

**Additional context**

- mbconfig file:[Object.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7708272/Object.zip)

- Not repro on VS2019

**Comment by LittleLittleCloud** [comment]
@zewditu  looks like it's related to the PR you created (https://github.com/dotnet/machinelearning-tools/pull/1354), can you take a look?

**Comment by zewditu** [comment]
@LittleLittleCloud

**Comment by zewditu** [comment]
This issue is because the new .net 6 features a global namespace it creates type conflict between systems.Object and   and the type created in the new project

**Comment by beccamc** [comment]
@zewditu Can you circle back on this and look at the two attached issues? Ping Jake with questions.
