### ISSUE TITLE
After projects are generated, if user goes back to Evaluate and then back to Code step, it resets Code screen

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#195]
**To Reproduce**
1. Add Projects in Code Step
2. Select Data step but do not do anything else on Data screen
3. Go back to Code step -- screen is same as before
4. Go back to Evaluate step
5. Go back to Code step -- it resets back and makes users "Add Projects" again

**Expected behavior**
If user goes back to Evaluate step after Code generation and then goes back to Code step, it should behave the same as the other steps (e.g. should not reset).

**Screenshots**
![code-gen](https://user-images.githubusercontent.com/10437687/61827041-88dace80-ae18-11e9-852f-f4d7bff11633.gif)

**Comment by JakeRadMSFT** [comment]
Should be resolved or handled with reentrancy.

**Comment by JakeRadMSFT** [comment]
We also need to warn the user when they are about to perform an action that would reset a page.

For example:
If it would cause the training to reset (they would need to re-train) we should warn them.
If it would cause the data upload or download to reset we should warn them.
