### ISSUE TITLE
Version repetitive ML.Net Model Builder 2022 updates of the same version

### ISSUE THREAD

**Issue by kevison** [dotnet/machinelearning-modelbuilder#1952]
Every time I update VS 2022, I get a notification that ML.Net Model builder needs an update... However its the same version that keeps getting re-updated. From version 16.7.3.2143002 to 16.7.6.2152701.

It appears that with the last three VS 2022 I have to udpate this extension to the same version over and over again.  (see screenshot)

![image](https://user-images.githubusercontent.com/509754/146929876-2805cd0c-4834-4050-b2eb-c1997b711efa.png)

Is this a weird bug with VS 2022?

12/20/2021 This happened again... the PKGDEF extension required an update and during that update ML.NET was downgraded again and so required another ML.NET update back to the 16.7.6.2152701 version. This is really getting annoying...

thanks!

**Comment by kevison** [comment]
Today is 12/22/2021... Got notification that the PKGDEF extend had an update so updated...
![image](https://user-images.githubusercontent.com/509754/147153872-df7d3d90-34ec-4c0f-a8d1-fea423220463.png)

Watched the update take place and noticed that the MLK.NET package was once again downgraded... so I got the following to now update ML.NET after the PKGDEF extension was finished:
![image](https://user-images.githubusercontent.com/509754/147153937-2cc1ba51-9180-4c79-83aa-ba70836a27fe.png)

**Comment by zackmuc** [comment]
It's like in Groundhog Day  ..  can reproduce it :)

**Comment by zackmuc** [comment]
Same with 
![image](https://user-images.githubusercontent.com/4520343/147550970-04cf0691-064c-4a08-a86d-791a9ded6fe0.png)

**Comment by LittleLittleCloud** [comment]
We have the fix in VS which will be released on Jan/19 2022, I'll update on this thread once the fix goes out

**Comment by kevison** [comment]
awesome! thank you!

**Comment by beccamc** [comment]
The fix for this is shipped in version 16.9.3! Please give it a try and let us know if you see any problems.

**Comment by kevison** [comment]
How does this affect VS 2022 which is where I originally ran into the problem....

**Comment by nick1941** [comment]
Every time I open VS2022, I get the notification that there is an update to "ML.NET Model Builder 2022'.  However when I click the "More details" link, the "Manage Extensions" dialog box continuously shows "Retrieving information..." without ever switching to an installation.  Eventually, I close the attempted update to use VS2022.  But, the next time I start VS2022, the same thing happens again.

**Comment by beccamc** [comment]
What version of Model Builder are you on? You may need to manually update from the marketplace https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022

**Comment by nick1941** [comment]
Thanks!  Got it working now!
