### ISSUE TITLE
Expected known-size vector of Single, got Vector<Single>

### ISSUE THREAD

**Issue by newbies155** [dotnet/machinelearning-modelbuilder#1953]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.6.2150501
 - Visual Studio Version: 16.11.7

**Describe the bug**
- On which step of the process did you run into an issue: Training
- Clear description of the problem: it Expected known-size vector of Single, but it apparently got Vector<Single>
the Parameter name: inputSchema

**To Reproduce**
1. make an ML model
2. choose for the scenario "Data classification"
3. make a file named "db.txt" and put the following content in it:
spam[tab]1
not spam[tab]0
4. choose to predict col1
5. train for 60 seconds

**Expected behavior**
it is supposed to train for 60 seconds

**Screenshots**
https://prnt.sc/24j8vlp

**Additional context**

**Comment by beccamc** [comment]
Sorry for the long delay in response here. Can you include your dataset?

**Comment by beccamc** [comment]
Sorry again for the delay. Any chance you can attach the dataset?

**Comment by sbuchok** [comment]
@beccamc 
I would like to say that I got the same error. I am unable to provide the dataset as at this time as it was a direct connection to a DB. However, when I exported the data I wanted to a CSV file, it was able to read the CSV file fine and do the training. I will try to see if I can somehow sanatize the data and get you a DB backup that causes the error.

I am using 
ML.Net Model Builder 2022 Version 16.13.9.2231505
Visual Studio Enterprise 2022 (64-bit) Version 17.1.5

If you want me to create a new bug ticket I can, however, this is the same error I was getting while training.

**Comment by beccamc** [comment]
@sbuchok The dataset or even the schema would be helpful.

**Comment by sbuchok** [comment]
@beccamc I will try to have a DB backup with only the table in it and the data by end of day. I will also try to provide screenshots and an STR.

**Comment by BurntRanch** [comment]
> I don't have enough information to reproduce this problem. If you are still seeing it please open a new issue with the dataset. Thank you!

Deeply apologize for the extreme delay, i had issues for a very long time and couldn't reply and just forgot about this, i unfortunately lost my files so i am unable to provide you with the dataset.
Sorry again.

**Comment by rkpatrick** [comment]
I can duplicate it by using the UI to train with the following CSV, although if I use more rows, I don't see the error (I'm trying to train with a minimal dataset just to I can build my codebehinds and then (re)train at runtime):
```
Score,Client,DepositID
0,5540,GJ9999

```
