### ISSUE TITLE
The mbconfig file becomes unsaved after stop debugging.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1954]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.11.0.2162702
 - Microsoft Visual Studio Enterprise 2019: 16.11.8

**Describe the bug**
- On which step of the process did you run into an issue: after stop debugging, see mbconfig file state.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data classification to complete the training;
5. Navigate to Consume page and add projects to solution;
6. Save the model builder;
7. Run the one generated project;
8. Click "Stop debugging" button, see issue: the mbconfig file becomes unsaved status.

**Expected behavior**
The mbconfig file should show the saved state after stopping debugging. 

**Screenshots**
![Unsave after stop debugging](https://user-images.githubusercontent.com/81727020/147544637-0089cb54-70e4-4c31-9224-81f73941903c.gif)

**Additional context**
- mbconfig file: [Multi.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7783625/Multi.zip)
- Not occurs on latest main build: 16.9.1.2162101
![Not occus on main2](https://user-images.githubusercontent.com/81727020/147548061-0506f7aa-cc83-41ce-b3f3-8c9c812c9a2f.gif)

**Comment by LittleLittleCloud** [comment]
Hmmm that's interesting,,, two irrelavant things somehow interact with each other

**Comment by beccamc** [comment]
We don't have a consistent repro of this. @vzhuqin Have you seen this multiple times?

**Comment by vzhuqin** [comment]
@beccamc I will repro this issue on latest main when the blocked issue #1979 is fixed.

**Comment by vzhuqin** [comment]
@beccamc , i cannot repro this issue on latest main: 16.12.1.2206901

**Comment by beccamc** [comment]
I'm closing this issue. Please reopen if you see it again. Thanks Qin!
