### ISSUE TITLE
Cannot detect the train time change.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1956]
**System Information (please complete the following information):**

- Model Builder Version (available in Manage Extensions dialog): 16.11.0.2162702
- Microsoft Visual Studio Enterprise 2019: 16.11.8

**Describe the bug**
- On which step of the process did you run into an issue: Navigate to Train page, save the model builder, set train time
- Clear description of the problem: model builder cannot detect the train time change.

**To Reproduce**

1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data classification to Train page;
5. Save the model builder, then change the train time;
6. See issue: The model builder doesn't detect the time change.

**Expected behavior**
Can detect the train time change.

**Screenshots**
![Cannot detect the train time change](https://user-images.githubusercontent.com/81727020/147551490-4816b35f-b149-4c81-97a8-dba1f2b38fca.gif)

**Additional context**
Also occurs on latest main build: 16.9.1.2162101

**Comment by LittleLittleCloud** [comment]
Looks like this issue has already been fixed in latest main

**Comment by vzhuqin** [comment]
can repro this issue on latest main: 16.12.2.2207801
![1956_repro.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/50d6a553-d233-46bd-ab4e-fb7d832bd03f)

**Comment by v-Hailishi** [comment]
This issue has been fixed on Main branch version: 16.13.5.2212401
![#1956_Fixed.gif](https://images.zenhubusercontent.com/62158d7f86929a769f3d134a/c857856b-b8c7-44ed-92e0-68d3863d79cd)
