### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by chanmmn** [dotnet/machinelearning-modelbuilder#1960]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio 2022 Version 17.0.4

**Describe the bug**
- The log file as follow:
- 2022-01-01 00:38:18.2177 INFO Set log file path to C:\Users\chan-mingman\AppData\Local\Temp\MLVSTools\logs\MLModel1-QR8Y0S.txt (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-01-01 00:38:22.3640 DEBUG Object reference not set to an instance of an object.
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<ExecuteUpdateHandlerAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.Observable.ObservableModel.<HandlePropertyUpdateAsync>d__28.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

**To Reproduce**
1. Right click on Project, C# Console Project.
2. Click on Add
3. Click on Machine Learning Model...
4. Select Machine Learning Model (ML.NET)
5. Click Add.

**Expected behavior**
No error.

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
chanmmn sorry for hitting this issue.
This issue is a known issue and it is under work https://github.com/dotnet/machinelearning-modelbuilder/issues/1513

**Comment by zewditu** [comment]
@beccamc  or @LittleLittleCloud  I think we have `Object reference not set to an instance of an object` issues in several places. Are we treat them as separate issues or are all can be bundled as one related issue.
I thought it is similar to https://github.com/dotnet/machinelearning-modelbuilder/issues/1838 however the step the issue pops up is different

**Comment by beccamc** [comment]
This shouldn't repro on latest main. @vzhuqin Can you try to reproduce? 

Once we ship we need to ensure these are not happening any more in telemetry.

**Comment by vzhuqin** [comment]
Hi @beccamc , Yes, I haven't seen this error in the main build for a while, be it creating/opening the model builder, selecting a scenario or changing the settings in the advanced data options.

Not repro this issue on latest main: 16.12.0.2206201
![Issue1960not repro](https://user-images.githubusercontent.com/81727020/149254545-984f125e-27bc-431a-9e7d-3315bef45590.gif)

**Comment by beccamc** [comment]
This issue should be fixed in the latest release. Please ping or open a new issue if you're still seeing it after update. Thanks!

**Comment by HoLyDreaM** [comment]
I am getting this error in my latest version of Microsoft.ML.AutoML. But when I switch to version 0.19, the error disappears and the system starts to work. No matter what I did I couldn't solve this problem.

**Comment by beccamc** [comment]
@HoLyDreaM Are you seeing this problem in the Model Builder UI tool? Or are you writing ML.NET AutoML code and seeing the error?

**Comment by HoLyDreaM** [comment]
I am getting error on ML.NET AutoML side
