### ISSUE TITLE
ML Tutorial

### ISSUE THREAD

**Issue by nicholas-sharp** [dotnet/machinelearning-modelbuilder#1961]
Latest 2022 Visual Studio.  Following instructions found here:  https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/intro

.NET 6.0 (LTS) - or any other does not show up in the list to choose for .NET version.  It is installed.  Verified by downloading/installing separately.  Latest version to choose (even after project is set up) is 4.8.

**Comment by zewditu** [comment]
@nicholas-sharp could you check your installed run times in your VS installer individual components tab?
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/6589dca3-5d8f-4c26-9a29-074c03e960da), if they are not checked, please check them and update your installation.

**Comment by nicholas-sharp** [comment]
Thank you for your response.  I got it figured out and was able to continue with the example.  

 

    Be Blessed!

 

Nicholas Sharp



Father’s Own, Inc.

c: 828.557.3936

**Comment by zewditu** [comment]
Great!
