### ISSUE TITLE
Feature Request:  Would like mlnet to support local training for object detection

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [dotnet/machinelearning-modelbuilder#1965]
```bash
$ mlnet --version
16.2.0+511cc1082bef7a4bbb2f83ad88c1c425c932079c
```

Currently only supports local training for:
* classification
* regression
* recommendation
* image-classification

Would like to be able to locally train for object detection so I can develop on Linux

Current workaround is to use:
* Windows
* Visual Studio 2022
* Model Builder
* Azure

**Comment by zewditu** [comment]
Closed because it dup of https://github.com/dotnet/machinelearning-modelbuilder/issues/1091, please follow the progress here https://github.com/dotnet/machinelearning-modelbuilder/issues/1091
