### ISSUE TITLE
NuGet assembly failure in .Net 6 project 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1966]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Steps to Reproduce**
1. Opened an existing Value Prediciton .mbconfig
2. Retrained 
3. Saw error 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c5ef2f04-2c11-4a69-b24a-85c302d055c5)

**Comment by beccamc** [comment]
Is this issue already filed somewhere?

**Comment by zewditu** [comment]
we have this assembly loading issues 
https://github.com/dotnet/machinelearning-modelbuilder/issues/1943

https://github.com/dotnet/machinelearning-modelbuilder/issues/994

But  I am not sure if they are exactly same ,  they seems indifferent service .

**Comment by beccamc** [comment]
Has anyone else seen this problem?

**Comment by beccamc** [comment]
@beccamc  To try to reproduce.

**Comment by beccamc** [comment]
No repro
