### ISSUE TITLE
Unable to install VSIX Installer extension for VS17

### ISSUE THREAD

**Issue by ankushmadankar** [dotnet/machinelearning-modelbuilder#197]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

26/07/2019 01:46:53 PM - Microsoft VSIX Installer
26/07/2019 01:46:53 PM - -------------------------------------------
26/07/2019 01:46:53 PM - vsixinstaller.exe version:
26/07/2019 01:46:53 PM - 15.9.3041
26/07/2019 01:46:53 PM - -------------------------------------------
26/07/2019 01:46:53 PM - Command line parameters:
26/07/2019 01:46:53 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\z003v57f\Downloads\MLNET_Model_Builder.vsix
26/07/2019 01:46:53 PM - -------------------------------------------
26/07/2019 01:46:53 PM - Microsoft VSIX Installer
26/07/2019 01:46:53 PM - -------------------------------------------
26/07/2019 01:46:54 PM - Initializing Install...
26/07/2019 01:46:54 PM - Extension Details...
26/07/2019 01:46:54 PM - 	Identifier         : FE96D051-645F-4309-AE99-107A776B0DA2
26/07/2019 01:46:54 PM - 	Name               : ML.NET Model Builder (Preview)
26/07/2019 01:46:54 PM - 	Author             : Microsoft
26/07/2019 01:46:54 PM - 	Version            : 16.0.1907.1703
26/07/2019 01:46:54 PM - 	Description        : Simple UI tool to build custom machine learning models.
26/07/2019 01:46:54 PM - 	Locale             : en-US
26/07/2019 01:46:54 PM - 	MoreInfoURL        : 
26/07/2019 01:46:54 PM - 	InstalledByMSI     : False
26/07/2019 01:46:54 PM - 	SupportedFrameworkVersionRange : [4.5,)
26/07/2019 01:46:54 PM - 
26/07/2019 01:46:58 PM - 	SignatureState     : ValidSignature
26/07/2019 01:46:58 PM - 	SignedBy           : Microsoft Corporation
26/07/2019 01:46:58 PM - 	Certificate Info   : 
26/07/2019 01:46:58 PM - 		-------------------------------------------------------
26/07/2019 01:46:58 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
26/07/2019 01:46:58 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
26/07/2019 01:46:58 PM - 		[Serial Number] : 330000026ECE6AE5984BFC96A900000000026E
26/07/2019 01:46:58 PM - 		[Not Before]    : 07/09/2018 02:30:30 AM
26/07/2019 01:46:58 PM - 		[Not After]     : 07/09/2019 02:30:30 AM
26/07/2019 01:46:58 PM - 		[Thumbprint]    : 99B6246883B4B32EA59AE18B36945D205A876800
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - 	Supported Products : 
26/07/2019 01:46:58 PM - 		Microsoft.VisualStudio.Community
26/07/2019 01:46:58 PM - 			Version : [15.0.28307.665,17.0)
26/07/2019 01:46:58 PM - 		Microsoft.VisualStudio.Enterprise
26/07/2019 01:46:58 PM - 			Version : [15.0.28307.665,17.0)
26/07/2019 01:46:58 PM - 		Microsoft.VisualStudio.Pro
26/07/2019 01:46:58 PM - 			Version : [15.0.28307.665,17.0)
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - 	References         : 
26/07/2019 01:46:58 PM - 	Prerequisites      : 
26/07/2019 01:46:58 PM - 		-------------------------------------------------------
26/07/2019 01:46:58 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
26/07/2019 01:46:58 PM - 		Name         : Visual Studio core editor
26/07/2019 01:46:58 PM - 		Version      : [15.0,17.0)
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - 		-------------------------------------------------------
26/07/2019 01:46:58 PM - 		Identifier   : Microsoft.VisualStudio.Workload.NetCoreTools
26/07/2019 01:46:58 PM - 		Name         : .NET Core cross-platform development
26/07/2019 01:46:58 PM - 		Version      : [15.0,17.0)
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - 		-------------------------------------------------------
26/07/2019 01:46:58 PM - 		Identifier   : Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1
26/07/2019 01:46:58 PM - 		Name         : .NET Core 2.1 development tools
26/07/2019 01:46:58 PM - 		Version      : [15.0,17.0)
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - Signature Details...
26/07/2019 01:46:58 PM - 	Extension is signed with a valid signature.
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - Searching for applicable products...
26/07/2019 01:46:58 PM - Found installed product - Microsoft Visual Studio Premium 2012 
26/07/2019 01:46:58 PM - Found installed product - Microsoft Visual Studio Professional 2012
26/07/2019 01:46:58 PM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
26/07/2019 01:46:58 PM - Found installed product - Global Location
26/07/2019 01:46:58 PM - Found installed product - Visual Studio Enterprise 2017
26/07/2019 01:46:58 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by JakeRadMSFT** [comment]
@ankushmadankar thanks for reporting this issue. 

What version of Visual Studio 2017 do you have installed? We currently support  15.9.12 and later.

**Comment by ankushmadankar** [comment]
Microsoft Visual Studio Enterprise 2017 
Version 15.9.11
VisualStudio.15.Release/15.9.11+28307.586
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Visual C++ 2017   00369-60000-00001-AA619
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.14.20131.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.61435.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.9.03024.0
Azure Functions and Web Jobs Tools

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   11.0.183
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2017.2.2    Build 109.0.20171006.122324
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.4.21001.1 Commit Hash:8dd15923800d931b153ab9e4de74e42a74eba5e6
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61903.01040
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by ankushmadankar** [comment]
Please check readme file mention supported version as Visual Studio 2017 15.6 or later or Visual Studio 2019. Please update pre-requisite section with latest support version for tool.
