### ISSUE TITLE
Exceptions encountered when using Sentiment dataset to training model.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1971]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.11.1.2205601
 - Microsoft Visual Studio Enterprise 2019: 16.11.8

**DataSet**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**Describe the bug**
- On which step of the process did you run into an issue: Training model with Label to different data type+ column headers is "No".
- Clear description of the problem: Data classification with above Dataset, set the column title to No, training model with different data type of Label column, then encountered some exceptions, please see below details steps.

**To Reproduce**
Steps to reproduce the behavior 1:
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data classification;
5. Input the above dataset, and set the advanced as: 
"Sentiment" column is "Label with Boolean"
column headers is "No"
6. Navigate to Train page to start training, prompt Model Builder Error dialog that "Parsing failed with an exception": Could not parse value Sentiment in Line 1, column col 0"
![image](https://user-images.githubusercontent.com/81727020/148507499-e919857b-5019-4ab5-a63b-36c9c287a366.png)

Steps to reproduce the behavior 2:
1-4. same as behavior 1;
5. Input the above dataset, and set the advanced as: 
"Sentiment" column is "Label with String"
column headers is "No"
6. Complete the training without error;
7. Navigate to Evaluate page, click "Predict" button, See that: the name of the original label title "Sentiment" was output as the prediction result.
![image](https://user-images.githubusercontent.com/81727020/148506479-8faace35-7258-4677-b775-dc6598dbd602.png)

Steps to reproduce the behavior 3:

- Other steps are same, only change the Label to Single type, can complete the training without error, and the prediction result is also expected.

![image](https://user-images.githubusercontent.com/81727020/148507048-15683f5a-79ad-4cf6-a5ec-f42204b45543.png)

**Expected behavior**
I think behavior 3 is expected, behaviors 1 and 2 are issues, please take a look.

**Additional context**
I also tried Value predication and Recommendation scenarios, set the column headers to “No” to training and predict the model, no exceptions encountered.

**Comment by beccamc** [comment]
@beccamc To reproduce and see if this is due to wiping out the column data on header change.

**Comment by beccamc** [comment]
No action on this in a year. Closing as low priority
