### ISSUE TITLE
Generated namespace differs from the projects default if it has a dot character

### ISSUE THREAD

**Issue by andrasfuchs** [dotnet/machinelearning-modelbuilder#1974]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.2.2205603
 - Visual Studio Version: 17.0.4

**Describe the bug**
- On which step of the process did you run into an issue: After a successful training
- Clear description of the problem: The generated classes are in the namespace of "BBD_SleepLogger" instead of the project default "BBD.SleepLogger"

**To Reproduce**
1. Go to Solution Explorer
2. Set the name of the project to something that has "." character in it (in my case its "BBD.SleepLogger")
3. Right click on the project, Add, Machine Learning Model
4. Do the training and let the Model Builder generate the *.consumption.cs and *.training.cs classes
5. Check the namespace in these files

**Expected behavior**
I would expect to have the generated classes in the same namespace that I have in my project by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/910321/148762537-cfb40b57-77c0-4364-b9d4-f5312d32306c.png)

**Comment by beccamc** [comment]
Thanks for reporting @andrasfuchs.  I'll add this to the backlog.

**Comment by beccamc** [comment]
Possibly using the same cleaned name for the namespace as the class. @zewditu Does this relate to #1948?

**Comment by zewditu** [comment]
yes, it is to clean the namespace cleaning   I will take care of it in a separate PR.
