### ISSUE TITLE
Run WebAPI fail with Boolean data type column.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1977]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.12.0.2206201
 - Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.4

"Dataset"
https://raw.githubusercontent.com/dotnet/machinelearning/main/test/data/wikipedia-detox-250-line-data.tsv

**Describe the bug**
- On which step of the process did you run into an issue: Data classification>Run the generated WebAPI project.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Select Data classification with above dataset. set "Sentiment" column to Label;
5. Complete the training and navigate to Consume page;
6. Add Web API project to solution;
7. Fail running the Web API project with below code:
$body = @{
    SentimentText = "== OK! ==  IM GOING TO VANDALIZE WILD ONES WIKI THEN!!!"
    LoggedIn = true
}
Invoke-RestMethod "https://localhost:44309/predict" -Method Post -Body ($body | ConvertTo-Json) -ContentType "application/json"

**Expected behavior**
No error when running the generated WebAPI project.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/149273227-d1c08c83-f7a0-4383-b5ff-28cadd933bae.png)

Column setting:
![image](https://user-images.githubusercontent.com/81727020/149273595-b0bd6e06-8539-4087-a935-c63510541ed0.png)

**Comment by beccamc** [comment]
@vzhuqin What if you put true in quotes - "true"?  Is that request body generated by Model Builder?

**Comment by vzhuqin** [comment]
@beccamc , verified this issue on latest main ML.Net Model Builder: 16.12.2.2207401

- can repro this issue when put true in quotes - "true"; And yes, the original request body was copied from code snippet.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/791c1ac9-8e03-454e-aa3f-91b38f990a81)

- But if set the LoggedIn column to "String" type, can run the webapi without error.

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/228b94cc-f6a7-48f6-b452-dd4841c8329c)

**Comment by beccamc** [comment]
No action on this is over a year. Closing as low priority
