### ISSUE TITLE
A large blank area is displayed above the predicted results on Evaluate page.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1978]
**System Information (please complete the following information):**

- Model Builder Version (available in Manage Extensions dialog): 16.12.0.2206201
- Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.4

**Describe the bug**
- On which step of the process did you run into an issue: Predict results on Evaluate page.

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Select Image classification to complete the training;
5. Navigate to Evaluate page, select one image to predict the model;
6. See issue: A large blank area is displayed above the predicted results. 

**Expected behavior**
Not sure why add the large blank area, if it doesn't make sense, don't show it.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/149274495-516d0056-f522-4b7a-a732-ad1c30512cc7.png)

**Additional context**
There is a string "hello" displayed in the area for Data classification, Value predication, Recommendation.
![image](https://user-images.githubusercontent.com/81727020/149274539-db589367-e99d-4941-a2a3-954e9095fc66.png)

**Comment by beccamc** [comment]
@LittleLittleCloud Is this something from forecasting prototyping?

**Comment by LittleLittleCloud** [comment]
Yup, should be removed once linked PR checked in

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.12.1.2206901
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/601e69ca-88b2-4043-b235-f89b49361d7a)
