### ISSUE TITLE
Filenames for Model builder file including "." are cut

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1981]
I often name my models based on the dataset used. For example MyData010122.csv-LabelName-ModelBuilder.mbconfig.

If I use "." in the name as in the example above, then the name become MyData010122. 

Instead of cutting the name should the "." be replaced by another character such as "-" ?

It is low impact issue for my work. It is easy to workaround by not putting ".csv" in the name, or manually replacing it with -csv.

**Comment by beccamc** [comment]
Thanks for reporting @torronen! I'll put this on the backlog.

**Comment by beccamc** [comment]
#1948

**Comment by zewditu** [comment]
It seems that we keep "." in the file names 
![image](https://user-images.githubusercontent.com/36615490/151120193-b719f775-fa5f-4ce1-afa8-a7789193487c.png)

**Comment by torronen** [comment]
@zewditu I rested  on both VS 2019 and 2022, you are correct. 

The cutting only happens if I dont put .mbconfig in the filename field. In this case it might be reasonable to remove the invalid "extension". If user keeps .mbconfig in the filename dialog, then "." is kept as expected.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/26261427/151124065-7539be78-168d-4ce7-92f0-4341bc0f0642.png">

**Comment by zewditu** [comment]
@torronen thanks!
