### ISSUE TITLE
Update model message is wrong 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1982]
Looks like we didn't replace "filename".  The  mbconfig I opened was not named filename.mbconfig 😊

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c29edf3d-7c2e-4565-a35b-ed904af238b6)

**Comment by vzhuqin** [comment]
@beccamc , could you provide the repro steps for this issue? I cannot get the dialog now.

**Comment by beccamc** [comment]
You need to use an older version mbconfig file. Just changing the version number to something older would probably work. Let me know if it doesn't.

**Comment by beccamc** [comment]
Confirmed this is fixed: 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/89667920-eb57-46bd-8e7a-068970a72993)
