### ISSUE TITLE
Forecasting description is wrong 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1983]
This looks to be the old description from the "example scenarios?" 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/3485a2f7-18eb-441e-8ce2-360876f4b902)

**Comment by vzhuqin** [comment]
Not repro on latest main: 16.12.2.2207601
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/d7573ac8-4a92-41df-94bd-13de1b750fc0)
