### ISSUE TITLE
Provided Code has an error

### ISSUE THREAD

**Issue by geoffhirst** [dotnet/machinelearning-modelbuilder#1985]
**System Information (please complete the following information):**
OS Name	Microsoft Windows 11 Pro
Version	10.0.22000 Build 22000
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	GEOFFS-ZBOOK
System Manufacturer	HP
System Model	HP ZBook Fury 17 G7 Mobile Workstation
System Type	x64-based PC
System SKU	119W5EA#ABU
Processor	Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz, 2400 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	HP S92 Ver. 01.07.00, 04/11/2021
SMBIOS Version	3.2
Embedded Controller Version	22.73
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Product	8780
BaseBoard Version	KBC Version 16.49.00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United Kingdom
Hardware Abstraction Layer	Version = "10.0.22000.1"
Username	GEOFFS-ZBOOK\geoff
Time Zone	GMT Standard Time
Installed Physical Memory (RAM)	64.0 GB
Total Physical Memory	63.8 GB
Available Physical Memory	45.8 GB
Total Virtual Memory	73.3 GB
Available Virtual Memory	51.7 GB
Page File Space	9.50 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualisation-based security	Running
Virtualisation-based security required security properties	
Virtualisation-based security available security properties	Base Virtualisation Support, Secure Boot, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualisation
Virtualisation-based security services configured	
Virtualisation-based security services running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

**Describe the bug**
https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/consume

string sentiment = result.Prediction == 1 ? "Positive" : "Negative";

Error displayed is 
1>C:\Users\geoff\source\repos\myMLApp\myMLApp\Program.cs(12,27,12,37): error CS1061: 'SentimentModel.ModelOutput' does not contain a definition for 'Prediction' and no accessible extension method 'Prediction' accepting a first argument of type 'SentimentModel.ModelOutput' could be found (are you missing a using directive or an assembly reference?)

![image](https://user-images.githubusercontent.com/14834577/150296581-7b2a52e3-cf75-4944-a4f5-94b3949f9c95.png)

**To Reproduce**

**Expected behavior**
Expected to follow instruction.

**Screenshots**

**Additional context**
I consider myself well versed with C# but ML is new to me, so more than prepared to be told I have done something **stoopid**. :)

**Comment by beccamc** [comment]
@geoffhirst This looks like an error in our documentation. I think you might need to change `Prediction` to `PredictedLabel`.  Otherwise can you inspect that ModelOutput result and see what's available?

**Comment by andrasfuchs** [comment]
I'm not sure if it helps in your case, but I used the `result.Score` property instead for the prediction. That's an array of floats, and it is usually the first value that is important, but unfortunately its not consistent among the different algorithms. 
I described the problem [here](https://github.com/dotnet/machinelearning/issues/6037).

**Comment by geoffhirst** [comment]
Thanks guys, I did see the PredictedLabel but as I have zero experience with the library didn't want to second guess. Thanks for the clarity. Appreciated. Onwards!

**Comment by beccamc** [comment]
@luisquintanilla Looks like we've changed the model output shape without updating docs. Are you still the person to talk to about this? 😊

**Comment by luisquintanilla** [comment]
@beccamc yup. Is it just a matter of updating `Prediction` with `PredictedLabel`?

**Comment by andrasfuchs** [comment]
@luisquintanilla I don't think so. `Prediction` was a float value, and `PredictedLabel` is a `String`, right? 
Now you have the float values in the `Scores` array, and usually it's the first value that indicates the prediction confidence. This value combined with the `PredictedLabel` is the useful information for the user, I think.

So, ideally we would have a `SortedDictionary<String, Single>` on the `ModelOutput` object, containing the labels and their scores, plus we had the `PredictedLabel` and `PredictionScore` with the label and score values of the label with the highest score.

**Comment by luisquintanilla** [comment]
@andrasfuchs

For this dataset, the data type for the label or `Col1` is a float. It's still a categorical value though. Since it's a float, I don't think there's a way to map the labels to the. You're right though that in the event that it was a string, you'd be able to do that using the Slot Names property and generate a sorted dictionary.  In that case, the code would be a little more complicated and look something like the following:

```csharp
using Microsoft.ML;
using Microsoft.ML.Data;
using myMLApp;

// Add input data
var sampleData = new SentimentModel.ModelInput()
{
    Col0 = "This restaurant was wonderful."
};

// Load model and predict output of sample data
var result = SentimentModel.Predict(sampleData);

// If PredictedLabel is 1, sentiment is "Positive"; otherwise, sentiment is "Negative"
string sentiment = result.PredictedLabel == "1" ? "Positive" : "Negative";
Console.WriteLine($"Text: {sampleData.Col0}\nSentiment: {sentiment}");

var sortedLabels = GetScoresWithLabelsSorted(SentimentModel.PredictEngine.Value.OutputSchema, nameof(result.Score), result.Score);

foreach(var (k,v) in sortedLabels)
{
	Console.WriteLine($"{k}: {v}");
}

static Dictionary<string, float> GetScoresWithLabelsSorted(DataViewSchema schema, string name, float[] scores)
{
	Dictionary<string, float> result = new Dictionary<string, float>();

	var column = schema.GetColumnOrNull(name);

	var slotNames = new VBuffer<ReadOnlyMemory<char>>();
	column.Value.GetSlotNames(ref slotNames);
	var names = new string[slotNames.Length];
	var num = 0;
	foreach (var denseValue in slotNames.DenseValues())
	{
		result.Add(denseValue.ToString(), scores[num++]);
	}

	return result.OrderByDescending(c => c.Value).ToDictionary(i => i.Key, i => i.Value);
}
```

Since this is a "Hello World" tutorial just to dip your toes into ML.NET, we would prefer to keep it as simple as possible. However, we do have plans to update the following tutorial with code that shows how to map the labels to the probabilities.

https://docs.microsoft.com/dotnet/machine-learning/tutorials/github-issue-classification

**Comment by luisquintanilla** [comment]
Thanks for reporting this issue @geoffhirst. We've recently made updates to our tutorials to address this issue so I'll be closing it for now. If you have additional questions or problems, please feel free to create a new issue.
