### ISSUE TITLE
ML Model from ML.NET walkthrough 0% accuracy

### ISSUE THREAD

**Issue by kuznickic** [dotnet/machinelearning-modelbuilder#1987]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: Latest
 - Visual Studio Version (if applicable): Visual Studio 2022 / .NET 6

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: Following the tutorial, I always get 0% accuracy and the algorithm used is SdcaMaxiumEntropyMulti.  The tutorial shows about 80% and the algorithm used is LbfgsLogisticRegressionOva.

**To Reproduce**
I followed the tutorial exactly as stated on the train page of the tutorial

**Expected behavior**
Expected the accuracy to be a lot higher than 0%

**Screenshots**
![MLTrainingError](https://user-images.githubusercontent.com/15726416/150638238-e11fe72d-c770-49f4-9e9f-110e529677e6.PNG)

**Additional context**

**Comment by beccamc** [comment]
@kuznickic Sorry you encountered this issue. The problem is likely that your computer only trained one model in the 60 seconds. That's a bit unusual. Can you try training again with a longer time?

@vzhuqin Can you double check that you can't repro this on your machine in 60 seconds.

**Comment by vzhuqin** [comment]
@beccamc , i can got a good score in 60s.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/57d674ac-1553-4ff8-b267-2feeb31ed156)

I guess kuznickic select the col0 as the label column, so got the 0% accuracy.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e23e6a96-9b74-4c9a-8563-1364d80fcc52)

**Comment by beccamc** [comment]
Thank you @vzhuqin!! 

@kuznickic Did you maybe select the wrong value for label column?

**Comment by beccamc** [comment]
Any update here?

**Comment by kuznickic** [comment]
Sorry for the late response but yes I have the columns in the wrong order and the sample works perfect now.  I greatly appreciate the assistance on this.
