### ISSUE TITLE
The prediction result is not reset after training again.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1991]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): latest main (16.12.2.2207601)
 - Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.5

**Describe the bug**
- On which step of the process did you run into an issue: Display the previous Predication result on Evaluate page after training again.

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Select Forecasting scenario>Local (CPU);
5. Input the csv data source, select the predict and time series columns;
6. Navigate to Evaluate page to predict the model after training completed;
7. Back Train page, update Horizon to 20, complete train again;
8. Then navigate to Evaluate page again, see that the previous Predication result displayed there.

**Expected behavior**
The prediction result should be reset after training again.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/151313333-be81c410-1110-49d1-86af-22f87d44b0f4.png)

**Comment by vzhuqin** [comment]
Not repro this issue on latest main: 16.13.1.2210302

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0d1a1d9a-1e12-41fc-99d7-5fdb91393922)

**Comment by vzhuqin** [comment]
But find another issue is that the table frame is truncated after train again, @LittleLittleCloud please take a look?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/af43a8bb-74b3-497e-b54d-ae3017b5dbaa)

**Comment by LittleLittleCloud** [comment]
track in #2028
