### ISSUE TITLE
Run Forecasting WebAPI project errors.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1993]
**System Information (please complete the following information):**

- ML.Net Model Builder 2022: 16.12.2.2207601
- Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.5

**Describe the bug**
- On which step of the process did you run into an issue: Run Forecasting WebApi project 

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Select Forecasting scenario>Local (CPU);
5. Input the csv data source, select the predict and time series columns;
6. Add WebAPI project to solution after training completed;
7. Set the WebAPI project as Startup Project and run it;
8. Display 5 errors that: The type or namespace name 'xxxx' could not be found (are you missing a using directive or an assembly reference?)	

**Expected behavior**
No error when running forcasting WebAPI project.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/151319455-66a0d4d2-ca94-4721-a01d-67d9b22f220f.png)

**Comment by vzhuqin** [comment]
Not repro this issue on latest main:

- ML .Net Model Builder: 16.13.4.2211602

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e4a9c1df-1233-4c73-aac7-26b3f4abe03f)

**Comment by luisquintanilla** [comment]
Looks like this issue has been fixed.
