### ISSUE TITLE
All checks have failed when Create a PR which update MlNetVersion to the latest mlnet.cli version.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1995]
**System Information (please complete the following information):**
 - ML.NET: 16.12.2

**Describe the bug**
- On which step of the process did you run into an issue: MLNet.CLI Test Pass
- @LittleLittleCloud All checks have failed when Create a PR which update MlNetVersion to the latest mlnet.cli version: 16.12.2, could you help to take a look?
The corresponding PR: https://github.com/LittleLittleCloud/MLNet-Benchmark/pull/14

![image](https://user-images.githubusercontent.com/81727020/151653281-ad0b88e0-b717-4a20-ab7b-9ff7205aa331.png)

**Comment by LittleLittleCloud** [comment]
Hi @vzhuqin , I just push a fix to mlnet benchmark and you should be good to go,

**Comment by vzhuqin** [comment]
Thanks @LittleLittleCloud, success on ML.NET: 16.13.1.
PR: https://github.com/LittleLittleCloud/MLNet-Benchmark/pull/16
