### ISSUE TITLE
Suggestion: Allow to disable trainers

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1998]
**Is your feature request related to a problem? Please describe.**
Often, Model Builder runs some of the trainers fast but often starts building bigger and slower models with one or more trainers. Most of the time, FastForest may become slow. It happens on big and small datasets. For big datasets, the models may get very big, such as 3.5GB zip file (largest I've created). Currently, there is chance that some of the faster trainers would be perform better but then one of the trainers consumes huge timeshares.

Additionally, advanced users may learn more about the trainers and select algorithms with beneficial charasteristics for their use cases.

Titanic dataset (1000 + 350 items) image below. Note most trainers take <1 sec, but in this case FastTree 38 minutes. In Python, FLAML reaches 98.7% accuracy with LightGBM in 6 seconds with early stopping in  257 iterations. ML.NET might possibly have some[ misconfiguration with LightGBM](https://github.com/microsoft/FLAML/discussions/409#discussioncomment-2058431), but also I approximate LightGBM might have had only about 150 iterations in about 1 hour. It might even happent that LightGBM would not reach much more than 200 iterations during next hours because MB may soon have even slower run next (in this case it did not happen in next hour).
![kuva](https://user-images.githubusercontent.com/26261427/151836227-95161b16-a073-4960-bf04-2e1cb6a3e721.png)

Production dataset (8.5 gb) image below. Note multi-day FastForest while most others are completed in minutes.
![kuva](https://user-images.githubusercontent.com/26261427/151832811-dea8d7e5-be86-40c3-915d-f1ccd7e40268.png)

**Describe the solution you'd like**
User should be able to disable trainers, either in .mconfig as advanced feature or through Model Builder. It would allow user to complete convergence of parameters.

**Comment by LittleLittleCloud** [comment]
Yep there's a way to disable trainers through env variables, it's not mentioned in public document anywhere though (sorry about that)

![image](https://user-images.githubusercontent.com/16876986/151877707-e2227bbf-0911-41b1-892d-9c2d2a2d4b88.png)

For example, if you want to use only lgbm for binary classification, you can
`set AutoMLServiceBinaryClassifiers=LGBM`

**Comment by torronen** [comment]
Thank you. Good solution for me.

**Comment by beccamc** [comment]
@luisquintanilla Can we get this in docs?

**Comment by beccamc** [comment]
Once we document this can be closed. This is covered in the Customize training epic.

**Comment by andrasfuchs** [comment]
@torronen Did it work for you? I might be doing something wrong, but the environment variable doesn't seem to filter the trainers.

![image](https://user-images.githubusercontent.com/910321/158161535-ff393554-7a66-4063-88fc-4bf9d26b8262.png)

![image](https://user-images.githubusercontent.com/910321/158161460-b93c90d6-04e0-4be2-9bf9-a8bb3fcdcef0.png)

I use Visual Studio 17.1.1, Model Builder 2022 16.13.1.2210302, and I restarted Visual Studio after setting `AutoMLServiceBinaryClassifiers`.

@LittleLittleCloud Could you take a look if I did the configuration correctly?
