### ISSUE TITLE
Consider showing 4 digits in "Best accuracy"

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#2000]
When running high-accuracy models, small differences can be relatively big.
For example 98.6 vs 99.4% has 1.4% vs 0.6% mistakes in binary classification. 
So we could say one model is performing over 2x better even if both would round to 99% ins the summary page. 

This information may help decide if the model is useful enough for a specific use case, especially where mistakes can be expensive.

![kuva](https://user-images.githubusercontent.com/26261427/151926082-843d680c-a59f-4c28-afbc-995ed66e83e5.png)

**Comment by torronen** [comment]
Another issue with 2 digits: I can no longer search with the accuracy from the output log to see which iteration gave the best result. I usually use it to decide when I can cancel the training: if the best accuracy was found long time ago I can cancel - if recently, then I should keep training.

![kuva](https://user-images.githubusercontent.com/26261427/152545019-785d383f-f1b5-489b-a0b4-e26d8e18a03d.png)

**Comment by vzhuqin** [comment]
Not repro this issue on latest main:

- ML .Net Model Builder: 16.13.4.2211602

Scenario Data classification, Value predication, Recommendation, Image classification, Forecasting do not reproduce.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4fbe725e-a0f6-44ab-a970-521f8d6c61a9)

**Comment by luisquintanilla** [comment]
Closing this issue since it's been fixed. 

Thanks @torronen
