### ISSUE TITLE
Consider generate code to read CSV file in .training: RetrainPipeline

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#2002]
consider adding code to read CSV file in RetrainPipeline.

Microsoft.ML column inference and TextLoader detect different data types and user must manually change them.
RetrainPipeline might be more useful for the intended audience if it would include overload that allows sepcifying a csv path.

**Comment by torronen** [comment]
Example: https://github.com/torronen/lightgbm-comparison/blob/main/data/train.csv column boat

**Comment by beccamc** [comment]
@torronen Do you mean a completely new CSV? You want a code sample that shows how to read in a new .csv, infer the column types, and then use those settings?

**Comment by torronen** [comment]
Yes, something like this might make using _RetrainPipeline_ easier. Although, then maybe, overrides would be needed for list of ModelInputs (from memory, or custom storage) and read from SQL Sever.

![image](https://user-images.githubusercontent.com/26261427/152947284-1d823cbc-2e68-4382-8c85-bd16eebb9faf.png)

Myself, I am working on if we could retrain based on just the .zip file since it somewhere includes the hyperparams. Maybe, similar method could be part of the library, then the templates would not be needed here.

**Comment by torronen** [comment]
BTW, small side issue that could benefit from clarification in docs: refit vs retrain. It might only be relevant for trees, but LightGBM CLI supports refitting and retraining. Refitting uses same tree, but adjusts the values, while retraining creates a new tree. A new tree may need re-validation, refitting might be alright. 

The issue is worse when the dataset size is different. My use case is to train with large amounts of data to get the tree structure, then refit with end user data. If I would retrain with same hyperparameters the tree might be totally different and would not benefit from the initial tree based on larger datasets. On other hand, I can not ship the app with gigabytes of data for size of download, slow speed of training and, possibly, legal reasons, so retraining on client machine is not an option.

.NET LightGBM does not yet support refitting but hopefully in the future.

**Comment by beccamc** [comment]
FYI, if you install the [Notebook extension](https://marketplace.visualstudio.com/items?itemName=MLNET.notebook) and generate the code notebook we give you a similar snippet 

![Image](https://user-images.githubusercontent.com/9122518/172720274-27d7f3a1-9d8a-4295-9ca5-30ec7f484cd8.png)

@luisquintanilla I think we removed this from the code behind files. Thoughts on adding it back?

**Comment by beccamc** [comment]
@luisquintanilla I'm seeing asks for the data ingestion from a few other customers https://github.com/dotnet/machinelearning-modelbuilder/issues/1917#issuecomment-973666301

**Comment by luisquintanilla** [comment]
Thanks @torronen for the suggestion and @beccamc for looking into it. 

For the most flexibility and reusability, I think a `LoadDataFromEnumerable` method would make sense. By doing so, we wouldn't have to add the `LoadColumn` attributes to the `ModelInput` class. In the event the column order changes, you're not locked into the original ordering. Also, LoadFromEnumerable is more source agnostic. As long as you can create an `IEnumerable<ModelInput>` object, you should be able to load the data from a file, DB, JSON, etc. For deep learning scenarios that don't really load from a file or DB, this method works as well. 

```csharp
public static IDataView LoadDataFromMemory(MLContext mlContext, IEnumerable<ModelInput> data)
{
    return mlContext.Data.LoadFromEnumerable(data);
}
```

In the meantime, I've created this issue to link to our data loading documentation #2143
