### ISSUE TITLE
   at System.IO.FileInfo..ctor(String fileName)    at Microsoft.ML.ModelBuilder.Utils.Utilities.GetFileTrainTime(String filePath)    at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<StartTrainingAsync>d__109.MoveNext()

### ISSUE THREAD

**Issue by becjohnson** [dotnet/machinelearning-modelbuilder#2005]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: Model Builder
 - Visual Studio Version (if applicable): Experimental Version Visual Studio 2022

**Describe the bug**

- If you are trying to use a data-set outside of the containing folder of the solution, you will get this error.

**Expected behavior**
Expected the model to start training, got this error
"  at System.IO.FileInfo..ctor(String fileName)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.GetFileTrainTime(String filePath)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<StartTrainingAsync>d__109.MoveNext()"

**Comment by beccamc** [comment]
Sorry for the delay here @becjohnson.  To confirm, you're saying that Model builder couldn't open the file when it was in a random file location. It did work when the file was in the containing folder of the solution?

What was the full error message? Do you have a screenshot of the error?
