### ISSUE TITLE
Consider adding "Best iteration" to training window

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2007]
#2000

**Comment by beccamc** [comment]
@LittleLittleCloud you mean add all the information about the iteration to the Training page?

**Comment by luisquintanilla** [comment]
Closing this issue since related issue has been fixed and displaying output window information in UI is being tracked in #1582. If there's anything I missed, feel free to open a new issue @LittleLittleCloud
