### ISSUE TITLE
[Forecasting] Time series drop down is slow with 2000+ columns

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#2008]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.1.2210302
 - Visual Studio Version 2022

**Describe the bug**
- On which step of the process did you run into an issue: Starting new forecasting model
- Clear description of the problem: Selecting the column to use for time series is slow

**To Reproduce**
1. Create new model
2. Select forecasting
3. Select dataset with many columns (2300 in my case, dataset size 80 megabytes)
4. Try to select time series column and observe slow speed.

**Expected behavior**
Dropdown should open almost instantly if dataset has been already loaded

**Comment by torronen** [comment]
3 related issues:

1. Opening "Advanced data options..." is also slow to open, with 15-18% CPU consumption on 8-core Macbook.
2. Time label can not be selected from "Advanced data options..."
3. Search in Advanced data options is slow.

**Comment by torronen** [comment]
Similar issues on User Recommendation dropdowns. (Just tried it a bit for fun)

**Comment by beccamc** [comment]
This has been replaced with the search box. Check it out!
