### ISSUE TITLE
[Forecasting] Graph expects dataset pre-sorted

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#2009]
Data tab has new option "Graph" for forecasting task. My dataset has items in somewhat random order so the graph does not look useful.

Does the forecasting require user to pre-sort the dataset or does it do sorting itself for the training?

Time series column in Unix timestamp. . I could not find information from https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/time-series-demand-forecasting  if Unix timestamps are supported. If Unix timestamps are used, then what does "horizon" mean in the training and evaluation tabs? If I predict 10 steps to future, does it mean 10 seconds (per unix timestamp) or 10 steps of what is the average interval in the training data (such as 5 minutes per step)?

![kuva](https://user-images.githubusercontent.com/26261427/152588359-5b70da05-c57f-4a46-8564-2f24f2b6b3d5.png)

**Comment by beccamc** [comment]
@LittleLittleCloud Can you comment on the above questions?

**Comment by LittleLittleCloud** [comment]
The graph in data page will show dataset as is, while during training, if you choose `TimeStamp` as time column, it will sort out your dataset (from earlier to later) based on your time column.

The horizon is the number of values to look overhead, this value will be used to set the `horizon` in `ForecastBySsa`. So it doesn't related with time column even if you set it up.
