### ISSUE TITLE
[CLI] Generated project doesn't run or build

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2010]
**System Information (please complete the following information):**
 - CLI Version: 16.12.2+86688637e3ba4b906f5adf37b767fee124189da7
 - OS: Windows 11 & Ubuntu 20.04
 - .NET SDK: 6.0.101

**Describe the bug**
The console app project generated fails to build and run because:
- targets .NET SDK 3.1 
- is missing package references 
- is missing using statements. 
- `BuildPipeline` method uninplemented.

**To Reproduce**
1. Train a **classification** model
2. In generated project, run `dotnet build` or `dotnet run`.

**Expected behavior**

Generated project builds and runs successfully.

**Additional context**

Run output 
![image](https://user-images.githubusercontent.com/46974588/152832276-38c6fd6b-ae68-4f29-9391-ad9c61b0831b.png)

`BuildPipeline` implementation 
![image](https://user-images.githubusercontent.com/46974588/152833599-a5396cd5-8cbb-45e5-abc9-ed7d477436a7.png)

Generated project: [SampleClassification.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/8017061/SampleClassification.zip)

**Potential steps to fix**

- Add Microsoft.ML package reference to *.csproj* file
- Set target framework to .NET SDK 6.0
- Add `using Microsoft.ML;` to *.training.cs* file. Maybe even `Microsoft.ML.Data`. 
- Implement `BuildPipeline` method.

**Comment by luisquintanilla** [comment]
@LittleLittleCloud FYI

**Comment by v-Hailishi** [comment]
The bug is not repro on ML .Net CLI: 16.13.5 and Main branch: 16.13.5.2216101.
![image](https://user-images.githubusercontent.com/99375895/158095281-74cf36f0-ef8c-443c-b295-3f3aac8d00a3.png)

**Comment by luisquintanilla** [comment]
Thanks @v-Hailishi for checking. Closing this issue for now.
