### ISSUE TITLE
Found error when running replaced code on Program.cs

### ISSUE THREAD

**Issue by IzzZulfa** [dotnet/machinelearning-modelbuilder#2012]
Consume your model
The last step is to consume your trained model in the end-user application.

Replace the Program.cs code in your myMLApp project with the following code:

Program.cs

Copy
using MyMLApp;
// Add input data
var sampleData = new SentimentModel.ModelInput()
{
    Col0 = "This restaurant was wonderful."
};

// Load model and predict output of sample data
var result = SentimentModel.Predict(sampleData);

// If Prediction is 1, sentiment is "Positive"; otherwise, sentiment is "Negative"
string sentiment = result.Prediction == 1 ? "Positive" : "Negative";
Console.WriteLine($"Text: {sampleData.Col0}\nSentiment: {sentiment}");

Run myMLApp (select Ctrl+F5 or Debug > Start Without Debugging). You should see the following output, predicting whether the input statement is positive or negative.

![image](https://user-images.githubusercontent.com/61441410/152912309-76703fff-b304-4b73-95de-a1ea646ae0f7.png)

**Comment by luisquintanilla** [comment]
Thanks for reporting this issue @IzzZulfa. We've recently updated the tutorials and the issue has been resolved. If you run into additional problems or have additional questions, feel free to open a new issue.
