### ISSUE TITLE
Data Preview doesn't reset after switched Data source type.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#2013]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): ML.Net Model Builder: 16.13.1.2210302 (latest main)
 - Microsoft Visual Studio Enterprise 2019: 16.11.9
 - Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.5

**Describe the bug**
- On which step of the process did you run into an issue: Data page>Data Preview
- Clear description of the problem: Switch data source, the Data Preview doesn't reset.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data classification>Local (CPU);
5. Navigate to Data page, input File Data source;
6. Switch to "SQL Server" type, see that: Data Preview doesn't reset.

**Expected behavior**
Data Preview area should be reset after switched Data source.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/152933854-ae5bc909-6764-44e4-8289-1ed4c311b69c.png)

**Comment by vzhuqin** [comment]
@beccamc , yes, if you select other dataset, it will update to show the changed data. this issue only occurs when switching data source type.
![2013](https://user-images.githubusercontent.com/81727020/153978427-2969d8f7-a64c-4d70-9e17-0f3dced61b57.gif)

**Comment by beccamc** [comment]
We are closing this bug as a lower priority item. Although it is an error, it is low impact for customers.
