### ISSUE TITLE
The settings in Advanced Data options do not work for Forecasting.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#2015]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.1.2210302 (latest main)
 - Microsoft Visual Studio Enterprise 2019: 16.11.9

**Describe the bug**
- On which step of the process did you run into an issue: Settings in Advanced Data options

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Forecasting scenario and input data source;
5. Open Advanced data options dialog, do settings for Label,  find the settings do not work.

**Expected behavior**
The settings in Advanced Data options should work for Forecasting.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/153162595-b5fa61dd-43a8-437e-b6af-3fc851a8c9a3.png)

**Comment by beccamc** [comment]
@LittleLittleCloud Do we want this to make the current release? If so, do you want me to take a look at this?

**Comment by LittleLittleCloud** [comment]
No, we don't have plan to fix any forecasting-related issues in this release, I will move this to May release

**Comment by luisquintanilla** [comment]
Pushing to June release.

**Comment by v-Hailishi** [comment]
Verified on the latest main branch 16.13.10.2247001, the advanced data options for the forecasting scenario have been updated like blow:
![image](https://user-images.githubusercontent.com/99375895/191885568-911b5856-43ce-4012-9fb7-b03f26aba748.png)
