### ISSUE TITLE
Forecasting: cannot select the column which data type is non-Single as label.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#2023]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.2.2211002
- Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.6

**Describe the bug**
- On which step of the process did you run into an issue: Label drop-down list
- Clear description of the problem: this issue not occurs on other scenarios, all columns can be selected as label, regardless of their data type, if the data type of the label is specified, an error message will be prompted to remind you when starting training. 

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Select Forecasting>Local (CPU), and input data source;
5. Expand the Label drop-down and find that some column names cannot be seen；
6. Open Advanced data options, see the data type of these columns are not Single, if you change them to single, then will display under the Label drop-down. 

**Expected behavior**
All column names can be selected as label.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/153552906-f02704a2-87db-43b4-af76-db1e430da17f.png)

**Comment by LittleLittleCloud** [comment]
That's by design. Data type for forecasting label has to be single.

**Comment by vzhuqin** [comment]
ok, thanks confirm.

**Comment by v-Hailishi** [comment]
Closed as by design.
