### ISSUE TITLE
Forecasting: display the same predicated values.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#2024]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.2.2211002
 - Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.6

**Describe the bug**
- On which step of the process did you run into an issue: predict the model>see prediction result

**Data source**
https://github.com/dotnet/machinelearning-samples/raw/main/samples/csharp/getting-started/Forecasting_BikeSharingDemand/BikeDemandForecasting/Data/DailyDemand.mdf

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Select Forecasting and input above data source, set "TotalRentals" as Label column;
5. After complete training, navigate to Evaluate page;
6. Click "Predict" button, see that the "TotalRentals" column displays the same values.

**Expected behavior**
The predicted values should not be the same.

**Screenshots**
Data Preview:
![image](https://user-images.githubusercontent.com/81727020/153570235-66494b6b-e15f-494f-bffb-a5eca2834a3b.png)

Predicted result:
![image](https://user-images.githubusercontent.com/81727020/153570246-b85722e7-ceab-479c-a485-78517395a3a0.png)

This issue has another issue is that the TotalRentals_LB has negative value:
![image](https://user-images.githubusercontent.com/81727020/153571920-35dfb65f-a645-49a5-adfa-21098fc203dc.png)

**Comment by LittleLittleCloud** [comment]
What's the rmse result for the training, if it's not small (means the error is large between real and predict value), it's possible to have the same predicted value, and the predicted value should be close to the average value of its historical data. ( so is negative predicted value)

**Comment by vzhuqin** [comment]
From the above screenshot, the RMSE was 1356.7691,  I also tried to add the training time to train it again, the values were also more than 1000.

**Comment by LittleLittleCloud** [comment]
You can try increase horizon, and if RMSE is over 1000, then it's normal to see the predict value doesn't even close to actual value because that metric is very pool

**Comment by beccamc** [comment]
Closing this is a problem specific to this data.
