### ISSUE TITLE
Model Builder Error when adding console app to solution on Consume page.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#2025]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  16.13.3.2211104 (Latest main)
- Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.6

**Describe the bug**
- On which step of the process did you run into an issue: adding console app to solution on Consume page
- Clear description of the problem: not occur for WebAPI project and Notebook file.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Select Data classification to complete training;
5. Navigate Consume page and click Add to solution for Console App project, prompts model builder error: Object reference not set to an instance of an object.

**Expected behavior**
Can add console app project to solution successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/153791250-4e82e94a-f5cd-42fc-b909-b2b46c85ee67.png)

**Comment by v-Hailishi** [comment]
This issue has been fixed on VS2022 Main branch version: 16.13.5.2212401
![image.png](https://images.zenhubusercontent.com/62158d7f86929a769f3d134a/64b0d34a-7594-410b-9bd0-676b770f5324)

**Comment by luisquintanilla** [comment]
Issue has been fixed. Closing.
