### ISSUE TITLE
dotnet run

### ISSUE THREAD

**Issue by Youstarter** [dotnet/machinelearning-modelbuilder#2026]
Elizabethrigney and her family were locking together for the next levelbeforeshehadtalkedwithhermotherabouttheprocessofmovingonlne xtcouple**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
Sorry @Youstarter I don't have enough information to investigate this issue. If you're having a problem please answer the questions, and include screenshots. Thanks! 

Closing - happy to reopen if you're able to provide more info.
