### ISSUE TITLE
The output area of consume the model is too long.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#2027]
**System Information (please complete the following information):**
- Notebook Editor [Preview]: 0.2.3.2210803
- ML.Net Model Builder: 16.13.3.2211104
- Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.6

**Describe the bug**

- On which step of the process did you run into an issue: run notebook file

- Clear description of the problem: this issue might be not happen after re-Run All again.

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. Select Data classification to complete training;
5. Navigate Consume page and Add notebook to solution;
6. Open and run the notebook file, see the output results, find that the output area of consume the model is too long.

**Expected behavior**
The length of the output area can be automatically adjusted according to the output content. 

**Screenshots**
![output area too long](https://user-images.githubusercontent.com/81727020/153813698-b4bdc28c-e45d-4997-a1a6-6cd28ffb73ab.gif)

**Comment by beccamc** [comment]
@vzhuqin Can you move this issue to the Notebook repo? (you can just create a new issue and link)

**Comment by vzhuqin** [comment]
Moved to https://github.com/microsoft/VS-Notebook/issues/150
