### ISSUE TITLE
Unable to install ml.net on visual studio 2019 enterprise

### ISSUE THREAD

**Issue by pradhyumna85** [dotnet/machinelearning-modelbuilder#203]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
I was not able to install ml.net on Visual studio 2019 enterprise.
Operating System: windows 10
I have attached the screeshot of the error and the log file.

![Capture](https://user-images.githubusercontent.com/36568190/62426958-59c23800-b709-11e9-9cb3-5a9d5ded4dc8.JPG)
[dd_VSIXInstaller_20190804223258_6314.log](https://github.com/dotnet/machinelearning-samples/files/3465117/dd_VSIXInstaller_20190804223258_6314.log)

**Comment by greazer** [comment]
Hi @pradhyumna85, the log indicates that the installer cannot find an acceptable instance of VS 2019 installed. I assume you most certainly do, but it may be a version problem of some sort. So, can you provide a screen shot of your About dialog? Also, what path did you install VS to?

**Comment by pradhyumna85** [comment]
I had intalled visual studio in a custom location (not C drive as i was not having space) :
F:\PROGRAM FILES\visual studio 2019

I have attached the screeshot of the about screen and the installed programs(control panel)
![Capture2](https://user-images.githubusercontent.com/36568190/62682769-9082a180-b9da-11e9-9ee7-9c668222c80b.JPG)
![Capture3](https://user-images.githubusercontent.com/36568190/62682771-911b3800-b9da-11e9-9288-b15d6151f8a7.JPG)

**Comment by JakeRadMSFT** [comment]
@pradhyumna85 are you able to launch VS 2019?  If so, could you try installing model builder again?

The error "Found setup instance 14044651 but not in launchable state." implies that setup hasn't fully completed for the install.

**Comment by JakeRadMSFT** [comment]
Closing due to lack of response. If you're still hitting this issue please re-open and supply the requested information.

Thanks for reporting!
