### ISSUE TITLE
kaelynn Kha

### ISSUE THREAD

**Issue by A1Ki** [dotnet/machinelearning-modelbuilder#2031]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
Sorry, I think I'm missing context on this issue. Please add details and re-open or file a new issue. Thanks!
