### ISSUE TITLE
Need better "first use" experience

### ISSUE THREAD

**Issue by appliedmarks** [dotnet/machinelearning-modelbuilder#2034]
I just want to give the team feedback about the first-use experience given I have lots of background with .NET, but not much with machine learning, so should be the target audience.

I watched a few hours of videos, and thought "this looks simple" and then spent about 30-60 minutes trying it in VS 2022 17.1 (latest update).

I thought I would start with a simple csv file, with an input column and a TRUE/FALSE label used to attempt predictions (so only 2 columns in my dataset for training).  After 30 minutes of trying various things, I couldn't even get this to produce anything sensible.  When putting in the exact same input as my test data, it still gave 50% weighting to each of the labels.  I gave up and thought I should try a sample.

I then followed some of the links and found some sample training data.  But after spending another 30 minutes could not make any further progress (and hit lots of bugs).  

Unfortunately, I think it would have been more productive to have real "code" samples, rather than a UI, so maybe your effort is in the wrong direction.  Issues I hit included:
a) Many exceptions appearing in Visual Studio (with the ML.NET extension).
b) The bar appearing at the top "Visual Studio stopped responding for 9 seconds. Disabling the extension ML.NET Model Builder 2022 16.13.1.2210302 might help".
c) I had a real issue with the "Column to predict (label) drop down.  It seemed to not be working (on many different attempts), only to be working again if I walked away from my computer and came back 10 minutes later).  There are real usability issues with even understanding when and why it works.

My recommendation is you need to include in this tool the most basic working example, like a template you get with a new Console or Blazor app.  People need a working starting template, then if they have a good experience will continue progressing their knowledge from that base.  My experience today means I will put this down until maybe VS 2023/2024 then have another go in a few years.

Hope this feedback helps the team improve.

**Comment by beccamc** [comment]
Did some investigation into VS not responding - https://github.com/dotnet/machinelearning-modelbuilder/issues/2048

**Comment by beccamc** [comment]
Thanks for this detailed report! We've just created some Notebooks that walk you through machine learning with a code first approach. There are also end to end examples that you can modify. We are continuing to improve Model Builder, but these may be helpful for getting started! 

Repo: https://github.com/dotnet/csharp-notebooks#machine-learning

**Comment by beccamc** [comment]
Thanks again for the feedback here. We've fixed a few of the VS responsiveness issues. Additionally, you might be interested in the code samples in our Notebooks - https://github.com/dotnet/csharp-notebooks#machine-learning.  Let us know if you have any other thoughts.
