### ISSUE TITLE
Could not upgrade to version 16.13.1.2210302 on VS 2022 17.1.0

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2036]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.1.2210302
 - Visual Studio Version: 17.1

**Describe the bug**
- Could not upgrade to version 16.13.1.2210302. VSIX installer crashed during installation. 

**To Reproduce**
1. Upgrade to the latest version of Model Builder from the VS 2022 Extension Manager

**Expected behavior**
The latest version to be installed

**Additional context**
[mb-install-error-log.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/8093641/mb-install-error-log.txt)

**Comment by LittleLittleCloud** [comment]
According to log it looks like the error is not caused by model builder, can you try uninstalling model builder and reinstalling from scratch to see if problem get fixed?

**Comment by luisquintanilla** [comment]
@LittleLittleCloud I think we can close this for now. The latest version of Model Builder was installed without me really doing anything. Must've been a config issue on my end.
