### ISSUE TITLE
[Model Builder] Error training value prediction model. Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2037]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.1.2210302
 - Visual Studio Version: VS 2022 17.1

**Describe the bug**
- On which step of the process did you run into an issue: Training
- Clear description of the problem: When training kicks off, exception is immediately thrown and training stops

**To Reproduce**
1. Load data file
1. Select "Score" as the Label
1. Train a value prediction model

**Expected behavior**
Model trained successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/46974588/154636728-e3a00c92-ee20-4c2a-999d-a013c6e35cc9.png)

**Additional context**

Log file: 
[InspectionModel2-TQ24YM.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/8094939/InspectionModel2-TQ24YM.txt)

Data file: Ask for it

**Comment by LittleLittleCloud** [comment]
Not reproduce
