### ISSUE TITLE
Run the generated WebApi project error.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#2038]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.4.2211701
 - Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.1.0

**Describe the bug**
- On which step of the process did you run into an issue: Run the generated WebApi project
- Clear description of the problem: closed the Microsoft Visual Studio dialog and re-run the project, this issue not occurs.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project;
4. After trained;
5. Add WebApi project to solution on Consume page;
6. Run the generated WebAPI project, prompts Microsoft Visual Studio box said: Object reference not set to an instance of an object.

**Expected behavior**
No error when running the generated WebAPI project.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/154649664-4851fc13-b0df-41f2-baeb-323c7570e7f6.png)
![image](https://user-images.githubusercontent.com/81727020/154650149-2c468ced-d03d-49f4-b0c8-8bb36ecbf9a0.png)

**Additional context**

**Comment by LittleLittleCloud** [comment]
Looks like the error is from model builder, not web api project.

**Comment by v-Hailishi** [comment]
The bug is also repro on the latest main branch version: 16.13.5.2216001 for VS2022.

**Comment by v-Hailishi** [comment]
@beccamc the bug is still repro on the latest main branch 16.13.6.2225901 for VS2022.
![image](https://user-images.githubusercontent.com/99375895/167590555-14ebe413-7f29-4dee-9259-ea75a5a74f3f.png)

**Comment by v-Hailishi** [comment]
@beccamc The bug has been fixed on the latest main branch 16.13.6.2226601 for VS2022.
