### ISSUE TITLE
Add machine learning algorithm selection to the Consume page

### ISSUE THREAD

**Issue by andrasfuchs** [dotnet/machinelearning-modelbuilder#2041]
**Is your feature request related to a problem? Please describe.**
When we train our models Model Builder iterates through many ML algorithms, scores them, and selects the one with the highest score. There is no option now to select one particular algorithm after training, it's always automatically selected by Model Builder.

**Describe the solution you'd like**
It would be good to have a dropdown or similar selection control on the Consume page that would contain the previously tested ML algorithms. If the user selected one of them, he/she could start the code generation again based on that algorithm.
This would help greatly with scenarios when we want to test one particular algorithm or when we would prefer one over another based on other metrics, not just its score calculated by Model Builder.

**Describe alternatives you've considered**
I can wait during the training until I reach the algorithm that I would like to choose, and if I'm lucky and that has the highest yet score, I can stop the training and have the code generated for me with that algorithm. Otherwise I can't do anything to choose the algorithm manually as far as I know.

**Comment by LittleLittleCloud** [comment]
@luisquintanilla

**Comment by luisquintanilla** [comment]
Thanks @andrasfuchs. To try and consolidate requests, I'm closing this issue as duplicate of #1999.
