### ISSUE TITLE
model builder error initializer for tensorflow binding in ML.net

### ISSUE THREAD

**Issue by phatht** [dotnet/machinelearning-modelbuilder#2043]
The type initializer for 'Tensorflow.Binding' threw an exception.
![image](https://user-images.githubusercontent.com/40348487/154940713-edc3bf21-8cee-4350-97ec-9ec612cca1de.png)

Looking forward to the community's support
thanks. Phát

**Comment by LittleLittleCloud** [comment]
Which CPU and system do you have, is that a x86/arm one

**Comment by phatht** [comment]
- Thank you very much for your interest in this.
- I fixed it already, just changed my local configuration and it worked.
old system info
![image](https://user-images.githubusercontent.com/40348487/155291974-541406c7-3eed-495a-9c5f-fa67cbbfd7bc.png)
new system info
![image](https://user-images.githubusercontent.com/40348487/155291925-fe7632f1-96ee-471d-964d-ebeb75e78397.png)

Thank you very much

**Comment by LittleLittleCloud** [comment]
That's interesting, are you working on a virtual machine, it's just a bit surprising for me to see that simply change CPU information can solve this issue

**Comment by phatht** [comment]
I work on my personal machine. Because I have a reference to this problem of yours, I tried to solve it
https://github.com/dotnet/machinelearning-modelbuilder/issues/1620

thanks u.

**Comment by beccamc** [comment]
It looks like this issue has been resolved. Thank you for reporting!
