### ISSUE TITLE
mlnet: command not found

### ISSUE THREAD

**Issue by AsainPersuasion** [dotnet/machinelearning-modelbuilder#2047]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@AsainPersuasion can you tell us more about this issue? some description,  steps to reproduce and if possible the screenshots

**Comment by luisquintanilla** [comment]
Thanks for reporting this issue @AsainPersuasion . The tutorials have been recently updated so your issue may be resolved. Closing this issue for now. Feel free to open a new issues if you have additional questions or run into any problems.
