### ISSUE TITLE
Add a solution dialog should pop-up an error message if enter a Project name with a space or hyphen (-). 

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2049]
**System Information (please complete the following information):**

Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.5.2212401 (Main Build)
Microsoft Visual Studio Enterprise 2022: 17.1.0
.Net: 5.0

**To Reproduce**

1. Select Create a new project from the Visual Studio 2022 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 6.0.
3. Add model builder by right click on the project.
4. Choose a Scenario, Environment and Data.
5. Train the model complete;
6. Add the ConsoleApp project or Web API project on Consume page;
7. On the "Add a solution" dialog, enter a Project name with a space or hyphen (-). like "**ML Model1_ConsoleApp1**"
8. Set the ConsoleApp project as startup project and click start debugging;
9. See error: the debug cannot continue because exist some code error in namespace area.

**Expected behavior**
Can debug the consoleapp project successfully.
If have any requirements for the project name, recommend to prompt message to remind user when named.

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/155670795-15ff729a-00cb-4181-8203-810480fc197c.png)
![image](https://user-images.githubusercontent.com/99375895/155670817-bb7be490-0fe1-47db-9c35-2dc01f2429a0.png)

**Comment by zewditu** [comment]
This seems recent changes trigger this

**Comment by zewditu** [comment]
This is the regression of this PR https://github.com/dotnet/machinelearning-tools/pull/1390.
 The NPD is not guaranteed for clean Namespace for instance "x-y" is a legal project name however it is not a legal namespace we need to sanitize the project name. However, we have an issue  https://github.com/dotnet/machinelearning-modelbuilder/issues/1974  the namespace is different from the generated project name but this is a normal experience in Visual studio

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch version: 16.13.5.2216001 for both of VS2019 & VS2022.
When enter a project name with a space or hyphen (-), the project can be debugged successfully. 
In the code, the space or hyphen (-) is replaced with underscore (_) automatically.
![image](https://user-images.githubusercontent.com/99375895/157795030-82c37c5d-3777-43ea-83ec-9e902bbe87f8.png)
![image](https://user-images.githubusercontent.com/99375895/157795170-9f7cfeea-cf94-4f9e-919d-6fb18ff8d013.png)

**Comment by v-Hailishi** [comment]
The bug is not repro on the latest main branch version: 16.13.5.2217301 for both of VS2019 & VS2022. The space or hyphen (-) is replaced with underscore (_) automatically.
![image.png](https://images.zenhubusercontent.com/62158d7f86929a769f3d134a/e0e19187-ce61-4ac7-bc4b-6a4089f49e60)
