### ISSUE TITLE
Training has failed.

### ISSUE THREAD

**Issue by Maitrog** [dotnet/machinelearning-modelbuilder#2052]
**Model Builder Version:** 16.13.1.2210302
**Visual Studio Version:** 2022(17.1.0)

**Bug description**
I have error with training process. 

**Steps to Reproduce**
1. Mark data in vott
2. Load data in model builder from vott 
3. Start train

**Expected behavior**
Successful train

**Screenshots**
![model_builder_error](https://user-images.githubusercontent.com/35650757/156432181-b34dcaa2-f6b8-429d-b8e9-33195fc23174.png)
![more_details_in_the_azure](https://user-images.githubusercontent.com/35650757/156433310-6fe769ef-27bb-4e18-acfd-1f48111166c3.png)

**Log file attached**
[Logfile.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/8172327/Logfile.txt)

**Run id:** https://ml.azure.com/experiments/id/32c7caff-6420-4b46-8f8e-754572d6b116/runs/AutoML_e192f584-7c50-420e-9833-1ffa358a7f4f?wsid=/subscriptions/0e48bce6-76ee-42fd-b43f-fdeadfd32b9a/resourceGroups/StudyProject/providers/Microsoft.MachineLearningServices/workspaces/ML-RBCs-OD

**Comment by v-Hailishi** [comment]
This issue is also repro on Main branch version: 16.13.5.2215101 for both 2019 and 2022.

**Comment by JakeRadMSFT** [comment]
This is being resolve by the Azure team - I'll report back when the fix has been rolled out.

**Comment by v-Hailishi** [comment]
The bug has been fixed in the latest main branch version: 16.13.5.2216001 for VS2022&2019.
![image](https://user-images.githubusercontent.com/99375895/157827734-a0486003-5c6e-4fa5-9041-703c3a992825.png)

**Comment by luisquintanilla** [comment]
Closing this issue since it's been resolved.
