### ISSUE TITLE
The web API project's output object is not our expected when using Image classification model of Local(CPU).

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2053]
**System Information (please complete the following information):**

Model Builder Version (available in Manage Extensions dialog): 16.13.5.2215101 (Main)
Microsoft Visual Studio Enterprise 2022: 17.1.0

**Describe the bug**

- On which step of the process did you run into an issue: 
Running the generated WebAPI projects
- Clear description of the problem: 
The output object should like "output, prediction, score" instead of "label, ImageSource".

**To Reproduce**
   
    1. Select Create a new project from the Visual Studio 2022 start window.
    2. Choose the C# Console App (.NET Core) project template with .NET 6.0.
    3. Add model builder by right click on the project.
    4. Select Image classification to complete training.
    5. Add WebAPI project to solution on Consume page.
    6. Run the WebAPI project and use PowerShell to run it.
    7. See the output object.
    
**Expected behavior**
The output object should like "output, prediction, score".

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/156534749-91f795fa-5a26-4921-aa38-e6cfe5a6274e.png)

**Additional context**
Below is the output object when using image classification model of Azure:
![image](https://user-images.githubusercontent.com/99375895/156535105-e57d929e-99d6-4692-af99-47342a96b797.png)

**Comment by zewditu** [comment]
Thanks for catching it!
@LittleLittleCloud  do you know what causes the local image classification output is not the expected one?  Do we have a recent update that couses this?

**Comment by LittleLittleCloud** [comment]
@v-Hailishi It's just not showing all labels in one row because "imageSource" is too long, you can use `select-object` to filter on columns you want

**Comment by LittleLittleCloud** [comment]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/16876986/167725414-ca1ca703-9f7f-448d-bc93-1cc222cffdb9.png">
