### ISSUE TITLE
System errors were found in at least one of the child runs.

### ISSUE THREAD

**Issue by pinnaclx** [dotnet/machinelearning-modelbuilder#2054]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luisquintanilla** [comment]
Might be related to #2052

**Comment by luisquintanilla** [comment]
Closing this issue as duplicate of #2055
