### ISSUE TITLE
Reference "System" could not be added to project

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2057]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.3.1.2210302
 - Visual Studio Version: 17.1.0

**Describe the bug**
- On which step of the process did you run into an issue: After creating *.mbconfig* file. 
- Clear description of the problem: When adding a machine learning model to a project, the *.mbconfig file* is created but a prompt saying `Reference "System" could not be added to project...`.

**To Reproduce**

1. Right-click project
2. Add Machine Learning Model
3. Provide a name for mbconfig in new item dialog

The *.mbconfig* file is created and the popup appears.

**Expected behavior**
No error message.

**Screenshots**

![image](https://user-images.githubusercontent.com/46974588/157353132-004a3b15-a502-40f8-869f-1c2084615706.png)

**Comment by luisquintanilla** [comment]
Same issue after upgrading to 17.1.1

**Comment by beccamc** [comment]
@luisquintanilla to try to get a consistent repo

**Comment by luisquintanilla** [comment]
I have not been able to repo in the last few days. Closing this issue for now.
