### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by yshih** [dotnet/machinelearning-modelbuilder#2058]
https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/consume

Your Code use result.Prediction caused error. I think should be result.PredictedLabel

string sentiment = result.PredictedLabel == 1 ? "Positive" : "Negative";
Console.WriteLine($"Text: {sampleData.Col0}\nSentiment: {sentiment}");

**Comment by luisquintanilla** [comment]
Hi @yshih thanks for reporting this issue. We're in the process of updating the tutorial and those changes should be out shortly.

**Comment by beccamc** [comment]
Waiting for the new tutorial to merge.

**Comment by luisquintanilla** [comment]
Tutorial updates have been merged. @yshih thanks for reporting this issue. Feel free to open a new issue if you have additional question or problems.
