### ISSUE TITLE
Forecasting: Add "Console App" solution is failed with error "The parameter is incorrect" on the "Consume" page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2061]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.5.2216001 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.11); 2022(17.1.1)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: Add "Console App" solution on the "Consume" page
- Clear description of the problem: only for Forecasting scenario, add "Console App" solution is failed

**Dataset**
[https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv](url)
[https://github.com/dotnet/machinelearning-samples/raw/main/samples/csharp/getting-started/Forecasting_BikeSharingDemand/BikeDemandForecasting/Data/DailyDemand.mdf](url)

**To Reproduce**

    1. Select Create a new project from the Visual Studio 2019&2022 start window;
    2. Choose the C# Console App (.NET Core) project template with .Net 5.0&6.0;
    3. Add model builder by right click on the project;
    4. Select **Forecasting** scenario>Local (CPU);
    5. On Data page,  input the data source: forecasting.csv or SQL Server Database File;
    6. Navigate to Train page after set the data column and completed training;
    7. Add Console App project to solution on Consume page;
    8. Then you will see the error "The parameter is incorrect".

**Expected behavior**
Add Console App project to solution is successful.

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/157846094-387d54c7-177c-41b2-9a67-e057ac33c64f.png)

**Additional context**
Error info:
The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
 at EnvDTE._Solution.AddFromFile(String FileName, Boolean Exclusive)
   at Microsoft.ML.ModelBuilder.VsProjectSystem.<AddProjectAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.ConsumeViewModel.<AddProjectToSolutionAsync>d__53.MoveNext()

**Comment by luisquintanilla** [comment]
Might be related to #2025. @LittleLittleCloud to validate

**Comment by LittleLittleCloud** [comment]
Still not fix, I'll see if I can fix it before april release

**Comment by v-Hailishi** [comment]
@LittleLittleCloud  The bug has been fixed on the latest main branch 16.13.6.2226101 for both VS2019&2022.
![image](https://user-images.githubusercontent.com/99375895/168195330-64b4a443-55e1-4252-a921-013b0017a41d.png)
