### ISSUE TITLE
After I train a model, you show me Try an Image - Turn this into a Grader

### ISSUE THREAD

**Issue by DataJuggler** [dotnet/machinelearning-modelbuilder#2063]
In my very first attempt, without watching a tutorial or reading much documentation, I created a Font Image Model, by creating 241,000 text images, 1,000 for each font I have installed on my machine, each font is in its own folder. 

Very 1st attempt worked, so Kudos to you for making it simple enough even I can figure out! My model builder prototype took 2 hours thinks to my Nuget Package DataJuggler.PixelDatabase.Net and a new DrawText function. 

The Font Detector works, and sometimes you get it right, or your highest guess is correct, other times you don't even list the correct font.

Here are two suggestions after my 1st day of Model Building, which I am sure I am an "Expert" already. I just think others that are new to this (or experienced) might find these helpful.

1. After my model is trained, you show me 'Try an Image'. I try. Why not let me grade your choice? If you are right, let me pick a check mark, and mark it as 100%, so you have data to improve upon, or if wrong, use this data to improve the model next time and not suggest the wrong answer.

2. I think it would be better to let users pick the amount of time, instead of stating 'Model Builder automatically picks the amounts of time based on the size of your dataset'.

Why not keep your 'Suggested time' after analyzing a dataset, but allow users a GUI to set how long to analyze. 

I would probably pick longest for best results, over fastest, but others might want faster.

Thanks, I can add ML.NET to my resume after today. Just thought it would make your model builder better if the user had more control, rather than your 'black box' of hidden settings.

P.S. If it is better if each suggestion is in its own issue, I can do that, I just feel like your system says 'You Again' every time I provide feedback. I spend too much time in Visual Studio.

Thanks

Also, an email would be nice when you respond, but that is another issue in itself.

Happy Friday

**Comment by luisquintanilla** [comment]
Hi @DataJuggler,

Thank you for your feedback. 

1. How well your model performs is highly dependent on your data. It's recommended that you provide a representative sample so the model can learn the patterns your dataset describes. To clarify, are you asking for a feedback mechanism that guides you on ways to improve your model or to provide feedback to us on how we can improve your model? 
2. For non-deep learning scenarios (anything other than image classification and object detection), this is already the case and while a time is recommended based on the size of your data, you have the option to change the default time. For deep learning scenarios, we leverage transfer learning and don't explore algorithms, but instead update the weights of a pretrained model using your data so the default is to train until completion.

**Comment by luisquintanilla** [comment]
Closing this issue since it's stale and needs more details. 

@DataJuggler if you have additional feedback, feel free to open a new issue.
