### ISSUE TITLE
Image Classification: The environment info should be updated on the "Train" page after changing the environment. 

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2068]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.5.2216101 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.11); 2022(17.1.1)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The environment info on the "Train" page.
- Clear description of the problem: 
1. After changing the environment from "Local(CPU) to "Azure" , the environment info should be updated to "Azure" on the "Train" page. 
2. After changing the environment from "Azure" to "Local(CPU)" , the environment info should be updated to "Local(CPU)" on the "Train" page. 

**To Reproduce**
  1. Select Create a new project from the Visual Studio 2019&2022 start window;
  2. Choose the C# Console App (.NET Core) project template with .Net 5.0&6.0;
  3. Add model builder by right click on the project;
  4. Select Image Classification scenario>**Local (CPU)**;
  5. On Data page,  input the data source;
  6. The environment info is "Local (CPU)" on the "Train" page.
  7. Go back to the Environment page;
  8. Changing environment from "Local(CPU) to "Azure" and set up the namespace.
  9. Then you will see that environment info is still "Local (CPU)" on the "Train" page.

**Expected behavior**
The environment info should be updated on the "Train" page after changing the environment. 

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/158126199-3ae31faa-6eae-4c2e-bc45-f906a09a9a7f.png)
![#2068](https://user-images.githubusercontent.com/99375895/158128170-333aea05-e32f-40d3-ae0c-e9adbaa1f409.gif)

**Additional context**
The environment info will be updated unless you select a different fold on the Data page or restart the mbconfig file.

**Comment by beccamc** [comment]
@LittleLittleCloud Could this be related to the refactor you did? It looks like the updated environment variable isn't making it to the other tabs

(sorry for the confusion, I commented this in the wrong issue originally)

**Comment by v-Hailishi** [comment]
@LittleLittleCloud The bug is still repro on the latest main branch: 16.13.5.2216701 for both VS2022&2019.

**Comment by LittleLittleCloud** [comment]
The fix is in 2216801, can you revalid it again

**Comment by v-Hailishi** [comment]
@LittleLittleCloud The bug has been fixed on the latest main branch: 16.13.5.2216801 for VS2019&2022.
![#2068.gif](https://images.zenhubusercontent.com/62158d7f86929a769f3d134a/02216a52-5675-4eaa-9d09-459ac33eb769)
