### ISSUE TITLE
I ran into an issue

### ISSUE THREAD

**Issue by tonan-truong** [dotnet/machinelearning-modelbuilder#2069]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SentimentModel.ModelOutput' does not contain a definition for 'Prediction' and no accessible extension method 'Prediction' accepting a first argument of type 'SentimentModel.ModelOutput' could be found (are you missing a using directive or an assembly reference?)	myMLApp

**Comment by luisquintanilla** [comment]
Hi @tonan-truong,

Thanks for reporting this issue. We've updated our documentation since this issue was opened. If you run into additional problems, please feel free to file another issues.
