### ISSUE TITLE
Add optimization metric selection to the CLI & Model (AutoML)

### ISSUE THREAD

**Issue by likellykang** [dotnet/machinelearning-modelbuilder#207]
When running AutoML in ML.NET using CLI, the default optimizing metric is accuracy, and uses cannot change this default setting at this point. It would be great to add optimizing metric selections to the CLI.

**Comment by rustd** [comment]
Thank you for your feedback. We will add it to our backlog.

**Comment by luisquintanilla** [comment]
Closing this issue since it's already possible in the latest version of the AutoML API and being worked on as part of #2191
