### ISSUE TITLE
Forecasting: Training error with message "overflow" when setting Horizon >=18 for Data source from SQLPassword.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2073]
**System Information (please complete the following information):**

Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.5.2216801 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.11); 2022(17.1.1)
.Net: 5.0 & 6.0

**Describe the bug**

- On which step of the process did you run into an issue: Training Forecasting with Data source from SQLPassword.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv

**To Reproduce**

  1. Pre-requisite: Do [Pre-requisites/SQLPassword](https://github.com/dotnet/machinelearning-tools/blob/main/docs/tests/Instructions/Pre-Requisites/SQLPassword.md) before repro this issue.
**Note here: Change the column name "index" to "index1" when adding data "forecasting.csv" to the database. Then training Forecasting with Data source from SQLPassword can be successful.**
  2. Select Create a new project from the Visual Studio start window;
  3. Choose the C# Console App (.NET Core) project template;
  4. Add model builder by right click on the project;
  5. Select Forecasting scenario>Local (CPU);
  6. On Data page, select>SQL Server>Microsoft SQL Server>SQL Server Authentication to input the data source;
  7. Navigate to Train page after set the data column;
  8. **Set Horizon=18** and the click Start training button, prompt model builder error as below screenshot.

**Expected behavior**
No error for training Data source from SQLPassword when set Horizon >=18.
I am not sure whether the error is expected when setting Horizon >=18 for training data source from SQLPassword.

Screenshots
Data settings:
![image](https://user-images.githubusercontent.com/99375895/159229195-f89facdf-28e4-4b16-9b0f-99e508649c86.png)
![image](https://user-images.githubusercontent.com/99375895/159229375-f67a9c80-bfe3-4eca-8e35-9b757ecbcc6c.png)

Error screenshot:
![image](https://user-images.githubusercontent.com/99375895/159230053-ade38496-cee7-4056-8e27-a0564efdf778.png)

**Additional context**
When setting Horizon<=17, training data source from SQLPassword can be successfully.
![image](https://user-images.githubusercontent.com/99375895/159230791-64e4a4c9-d418-4421-a45c-faed44dbcf24.png)

**Comment by beccamc** [comment]
Agreed this is low priority. @LittleLittleCloud Any thoughts here?

**Comment by beccamc** [comment]
@v-Hailishi If you run with a few minutes training time does it finish?

**Comment by v-Hailishi** [comment]
@beccamc I tried 10 min training time, got the same error.
![image](https://user-images.githubusercontent.com/99375895/159398439-acfdf9f0-07d1-4f53-89ae-8b9ef3819c69.png)

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.14.0.2255401, directly pop-up error dialog like below.
![image](https://user-images.githubusercontent.com/99375895/200245503-8434012a-af0c-4975-b0b6-b4df3809fb58.png)
