### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by csdhall** [dotnet/machinelearning-modelbuilder#2080]
This is what I get when I follow the documentation on this link.  
https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
See screenshot and the log file attached. 
[log.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/8351966/log.txt)

![image](https://user-images.githubusercontent.com/213613/160154535-c7f57f40-90f3-48f3-a0e9-9709457b9254.png)

**Comment by luisquintanilla** [comment]
Hi @csdhall,

I was able to train using the dataset from the tutorial. Here is my setup:

- VS Version: VS2022 (17.1.1)
- Model Builder Version: 16.13.1.2210302

![image](https://user-images.githubusercontent.com/46974588/160188182-f5bdcbb6-23c7-496f-93dc-c668b6a1154b.png)

Few things I want to confirm. 

1. After you download the file, the dataset you used is the *yelp_labelled.txt*. 
2. For the "Column to predict" dropdown, you selected **col1**. The screenshot you posted shows col0 has been set as the label. col0 should be your features, or the input you're using to predict the sentiment in col1. 

![image](https://user-images.githubusercontent.com/46974588/160188559-489cbc08-bc30-422d-a8c2-6294e8a6ebe5.png)

**Comment by csdhall** [comment]
I'm using VS 2022 and 1.6 version of Model Builder. 
I tried both columns separately as there are only two columns. 
Neither of the two can be trained. 
For I tried col1 to predict. Didn't work. 
Then I tried col0 (just to see if that works), and it didn't either. 
Yes, I used this  for training is yelp_labelled.txt.
Unfortunately, I don't have VS 2017. 

Please let me know if it works for you on VS 2022?

**Comment by luisquintanilla** [comment]
That's odd. No need to test on VS2017 since Model Builder only works on VS2019 and VS2022. 

Which version of Model Builder are you using? You can check using the Extension Manager.

![image](https://user-images.githubusercontent.com/46974588/160399275-7a46ee06-d986-478f-a824-a6d538e1b7a8.png)

**Comment by zewditu** [comment]
@csdhall your model builder version 1.6 is pretty old one  could you update the model builder to the latest version

**Comment by beccamc** [comment]
@csdhall I think you selected the "Value prediction" scenario instead of "Data classification".

**Comment by beccamc** [comment]
If "Data Classification" scenario doesn't work please ping me and we will troubleshoot!
