### ISSUE TITLE
Image classification error, related to experiment/temp files

### ISSUE THREAD

**Issue by FrankvdStam** [dotnet/machinelearning-modelbuilder#2081]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.1.2210302
 - Visual Studio Version: VS2022

**Describe the bug**
- On which step of the process did you run into an issue: Training the model for a 2nd time
- Clear description of the problem: Training a model gives a vague error

**To Reproduce**
1. Create an image classifier model
2. Train the model
3. wait 2 days
4. Change the dataset
5. Retrain the model
6. Receive the error (shown in a little dialog window):

filePath cannot be null or empty
Parameter name: filePath
   at Microsoft.ML.Runtime.Contracts.CheckNonEmpty(IExceptionContext ctx, String s, String paramName)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160 (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)

To fix:
1. Observe this output:
Set log file path to C:\Users\Frank\AppData\Local\Temp\MLVSTools\logs\EldenRingGamePlayClassifier-5D4N3U.txt
start nni training
Experiment output folder: C:\Users\Frank\AppData\Local\Temp\AutoML-NNI\Experiment-R11C28
|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration

2. Have a look at the output folder, in my case C:\Users\Frank\AppData\Local\Temp\AutoML-NNI\Experiment-R11C28.
3. see how the experiment folders are last modified 2 days ago (today is the 27th, it's picking an existing experiment folder from the 25th in the aforementioned output, would expect it to be modified the 27th):

![image](https://user-images.githubusercontent.com/37239092/160285571-fb82de23-a032-4ed3-b320-61b13ec313d0.png)

4. Move all these folders somewhere else temporary
5. Rerun training: training succeeds

**Expected behavior**
Retraining the model should not fail, or a clear/helpfull error message should appear.

**Screenshots**

**Additional context**
Found a couple github threads about a path in the config not being set, that was not the case here.

![image](https://user-images.githubusercontent.com/37239092/160285712-93bf6f60-c832-4758-a2e4-734417881822.png)

**Comment by JakeRadMSFT** [comment]
Does closing Model Builder and Re-opening Model Builder resolve this issue?

**Comment by FrankvdStam** [comment]
I actually tried restarting my machine, which did not work. So no, re-opening or restart VS did not work.

**Comment by beccamc** [comment]
How many images are you trying to train?

**Comment by gsuberland** [comment]
@beccamc I've done some digging since the above comment.

The stack trace described at the top of this issue appears for almost any case where the training fails, so it doesn't actually tell us anything about what went wrong. The error in the UI is effectively useless; the actual underlying issue and stack trace will be reported in the log file.

In my case the issue is 10k or more images in the first label. See #2102 for details.

**Comment by FrankvdStam** [comment]
I have 4 labels, all below 10k images

credits       77
gameplay  9502
loading      914
credits       131

But the total amount does go over 10k.

**Comment by luisquintanilla** [comment]
Thanks all for the discussion. Closing this issue since it's already being tracked and worked on as part of #2046
