### ISSUE TITLE
After closing the notebook file, the output windows throw out error "Cannot access a disposed object".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2083]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.5.2217801 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.1.1)
Notebook version: 0.2.3.2217906

**Describe the bug**
- On which step of the process did you run into an issue:
Close the notebook file

**To Reproduce**

  1. Select Create a new project from the Visual Studio start window;
  2. Choose the C# Console App and .NET6.0 project template;
  3. Add model builder by right click on the project;
  4. Select any scenario;
  5. Completed the training.
  6. On the "Consume" page, add a notebook.
  7. Open the generated notebook file and then close it.
  8. You will see the error message from the output window.

**Expected behavior**
It should give the info like "kernel is closed or stopped" instead of throw out error.

**Screenshots:**
![image](https://user-images.githubusercontent.com/99375895/160776845-ad29280b-06b1-4f7b-a513-c50e899f097e.png)

**Additional context:**
This issue is repro on all scenarios.

**Error info:**
error: Cannot access a disposed object.
Object name: 'IInteractiveService_adf47ce7-f71e-4554-bb52-b7fe76138202'. 
    at _proxy_Microsoft.VisualStudio.Notebook.InteractiveService.Contract.IInteractiveService_adf47ce7-f71e-4554-bb52-b7fe76138202.IsRunning(CancellationToken )
   at Microsoft.VisualStudio.Notebook.Utils.DetectKernelStatusService.<ExecuteTaskAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Notebook.Utils.RepeatedTimeTaskService.<>c__DisplayClass7_0.<<ExecuteAsync>b__1>d.MoveNext()

**Comment by beccamc** [comment]
@v-Hailishi Looks like a problem with the Notebook extension. Can you re-open this in the .NET interactive repo? https://github.com/dotnet/interactive

**Comment by v-Hailishi** [comment]
Move to [https://github.com/microsoft/VS-Notebook/issues/226](https://github.com/microsoft/VS-Notebook/issues/226)
