### ISSUE TITLE
I did not open such a page to open

### ISSUE THREAD

**Issue by chanaStern** [dotnet/machinelearning-modelbuilder#2085]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
@chanaStern Sorry, I don't understand the problem. Can you provide more details and screen shots? Thanks!

**Comment by beccamc** [comment]
I don't have enough information to resolve this issue. Please add more details and I will reopen. Thanks!
