### ISSUE TITLE
Predict results based upon wrong DataFile

### ISSUE THREAD

**Issue by Elantonio** [dotnet/machinelearning-modelbuilder#2087]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- Training -> use different datafile(with anoher name)
- shows new datafile (So OK)
->Train
-> Evaluate
->predict
->Gives result based upon previous DataFile

**To Reproduce**
1. see Describe the bug*

**Expected behavior**
Giving the rigth output based upon the new Data

**Comment by beccamc** [comment]
@v-Hailishi Can you try to reproduce this please?

**Comment by Elantonio** [comment]
Hi a label Issue source coutomer was added.
The only source at customer side is making the datafile.
the rest is all MLModel.mbconfig 's doing.

**Comment by beccamc** [comment]
"Issue source: customer" just means that the issue was reported by a customer ☺️

**Comment by Elantonio** [comment]
Oops srry

**Comment by beccamc** [comment]
@Elantonio Do you still see this on [16.13.6](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022)? We weren't able to reproduce.

**Comment by Elantonio** [comment]
I’m on 1.7.1 now and that seems to work.

Thanks for your help. 
Great Work!

Best Regards, 
Elantonio.
