### ISSUE TITLE
Notebook Content Drive

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#2089]
Hey All,
Creating this issue to track an effort to create a collection of useful ML.NET Notebooks for learning ML.NET. I'd like to share these on .NET Blogs in May/June.

### Getting Started
- [x] Intro to Notebooks Series
- [ ] 01 - Intro to ML.NET Series
  - [ ] Intro to ML Concepts (with ML.NET) (@tarekgh)
  - [ ] Intro to Data and Training Pipelines
  - [ ] Intro to Evaluation

- [ ] 02 - Data Prep and Feature Engineering
  - [x]  DataFrame (@beccamc)
  - [x] IDataView (@luisquintanilla)
  - [ ] Common Feature Engineering
- [ ] 03 - Training and AutoML
  - [ ] Common Algorithms
  - [ ] Parameters
  - [ ] AutoML
- [x] 04 -Model Evaluation (@luisquintanilla )
  - [ ] What do the Metrics Mean?
  - [ ] Cross-Validation?
  - [ ] PFI
- [ ] REF - Visualizations and Graphs
  - [ ] Plotly.NET  
  - [ ] Interactive Extensions

- [ ] E2E -Binary Classification
- [ ] E2E - Classification (@jwood803)
- [ ] E2E - Regression (@JakeRadMSFT)
- [ ] E2E - Time Series Forecasting (Not in AutoML yet) 
  - [x] (@LittleLittleCloud [Forecasting as regression](https://github.com/dotnet/csharp-notebooks/pull/16))
  - [x] (@LittleLittleCloud [Forecasting using SSA](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/REF-Forecasting%20using%20SSA.ipynb))
- [ ] E2E - Recommendation (Not in AutoML yet)

### Continue Learning / Advanced

- [ ] Ref - Sweepable API
- [ ] Ref- SQL
- [ ] ...

**Comment by JakeRadMSFT** [comment]
Notebook Editor Extension:
https://marketplace.visualstudio.com/items?itemName=MLNET.notebook

**Comment by luisquintanilla** [comment]
# Notebook Hack Guidelines & Resources

## Instructions

### Prerequisites

- [Visual Studio 2022](https://visualstudio.microsoft.com/vs/)
- [Notebook Editor extension](https://marketplace.visualstudio.com/items?itemName=MLNET.notebook)

### Creating samples workflow

1. Fork the [csharp-notebooks](https://github.com/dotnet/csharp-notebooks) repo.
1.  Clone your fork.
1. Create a new branch.
1. Author notebook.
1. Create a PR .

### Found a bug?

For issues with:

- **ML.NET Docs:** Open an issue in the [dotnet/docs](https://github.com/dotnet/docs) repo,
- **Notebook Editor:** Open an issue in the [dotnet/machinelearning-modelbuilder](https://github.com/dotnet/machinelearning-modelbuilder) repo.
- **ML.NET or DataFrame**: Open an issue in the [dotnet/machinelearning](https://github.com/dotnet/machinelearning) repo.  

## Resources

### Notebook Samples

- [C# notebooks](https://github.com/dotnet/csharp-notebooks)
- [.NET interactive notebook samples](https://github.com/dotnet/interactive/tree/main/samples/notebooks)
- [ML.NET notebook samples from the community (Davi Ramos)] (https://github.com/DaviRamos/MLNetJupyter)
- [TorchSharp notebook samples](https://github.com/dotnet/TorchSharpExamples)

### Documentation

- ML.NET Documentation
	- [Machine Learning Glossary](https://docs.microsoft.com/dotnet/machine-learning/resources/glossary)
	- [Tutorials (API)]()
	- [How-To Guides (API)](https://docs.microsoft.com/dotnet/machine-learning/how-to-guides/load-data-ml-net)
	- [ML.NET API](https://docs.microsoft.com/dotnet/api/?view=ml-dotnet&preserve-view=true)
	- [DataFrame API](https://docs.microsoft.com/dotnet/api/microsoft.data.analysis?view=ml-dotnet-preview)

**Comment by beccamc** [comment]
@JakeRadMSFT Can this be closed?

**Comment by luisquintanilla** [comment]
@beccamc sorry for the delay on this. I think we can close this since most of the work is complete. Thanks
