### ISSUE TITLE
training status is still `Finalizing Model` after Time expired when training a model

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#209]
**Model Builder Version**: latest master branch

**Bug description**
if training time is not enough for one iteration, after time expired, training status should return to `start training` (or something else) instead of `finalizing model`
![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/46040992-0823-494d-9f2b-0a890b58873b)

**Step for reproducing**
- pick multiclassification scenario
- pick wikipedia-detox-250-line-data.tsv
- pick second column as label
- set training time as 10s
- click start train

** expected behavior **
10s is not enough for a round train, so output should be "time expiring...." and train status should be "start train"

** actual behavior **
output works fine, but train status stuck on `Finalizing model`

**Comment by zewditu** [comment]
This bug  is fixed indirectly with the fix of  https://app.zenhub.com/workspaces/mlnet-tools-5cde1c97e3106e39e8ae08fc/issues/dotnet/machinelearning-modelbuilder/196
Or these two bugs are  similar
