### ISSUE TITLE
ModelOutput does not contain Prediction

### ISSUE THREAD

**Issue by RichardClaxton** [dotnet/machinelearning-modelbuilder#2090]
Following the example successfully, until trying 
string sentiment = result.Prediction == 1 ? "Positive" : "Negative";
The Model that was created does not contain a Prediction definition.

Using MVC version 17.1.2
Microsoft.ML version 1.6.0

**Comment by beccamc** [comment]
@v-Hailishi Can you confirm the consume page of the tutorial is still correct? https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/consume

**Comment by v-Hailishi** [comment]
@beccamc Tried the steps using the latest main branch 16.13.5.2221401, I also met the same error just like below picture.
![image](https://user-images.githubusercontent.com/99375895/163547576-f98619aa-b77d-4d06-9483-fd679ded23d2.png)

**Comment by beccamc** [comment]
@RichardClaxton I think you need to use .PredictedLabel. 

@luisquintanilla Did this get changed in a new ML.NET version? Was there an item for updating this tutorial?

**Comment by luisquintanilla** [comment]
@RichardClaxton sorry to hear you ran into this issue. As @beccamc pointed out, try using `result.PredictedLabel` instead of `result.Prediction`. 

```csharp
using MyMLApp;
// Add input data
var sampleData = new SentimentModel.ModelInput()
{
    Col0 = "This restaurant was wonderful."
};

// Load model and predict output of sample data
var result = SentimentModel.Predict(sampleData);

// If Prediction is 1, sentiment is "Positive"; otherwise, sentiment is "Negative"
string sentiment = result.PredictedLabel== 1 ? "Positive" : "Negative";
Console.WriteLine($"Text: {sampleData.Col0}\nSentiment: {sentiment}");
```

@beccamc the changes I made were only reflected for the CLI, not Model Builder. I'll make the updates to the tutorial to fix this.

**Comment by beccamc** [comment]
@luisquintanilla Are these updates in? Can I move to done?

**Comment by luisquintanilla** [comment]
@beccamc yup. Changes are in.
