### ISSUE TITLE
The space or hyphen (-) should be replaced with underscore (_) automatically in 'xx.consumption.cs' and 'xx.training.cs' files.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2091]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.5.2220401 (Main Build)
Microsoft Visual Studio Enterprise 2022: 17.1.3
.Net: 6.0

**To Reproduce**
  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core) project template with .Net 6.0 and **give the project name with space or hyphen (-)**.
  3. Add model builder by right click on the project.
  4. Choose a Scenario, Environment and Data.
  5. Train the model complete;
  6. Start debugging this project.
  7. See error: the debug cannot continue because exist some code error in namespace area.
  
**Expected behavior**
Can debug the project successfully.
The space or hyphen (-) should be replaced with underscore (_) automatically in 'xx.consumption.cs' and 'xx.training.cs' 

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/162895152-fddf86d3-7347-45e2-b82e-b7c1fb86c17c.png)

**Gif:**
![#2091](https://user-images.githubusercontent.com/99375895/162895751-a402c4c6-1d2c-4efa-b87a-b3f927ba8a3a.gif)

**Comment by beccamc** [comment]
@zewditu Has this been addressed before?

**Comment by zewditu** [comment]
This is not exactly, we had a similar issue in generated projects this is only for mbconfig behinds

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch: 16.13.5.2222101
![image.png](https://images.zenhubusercontent.com/62158d7f86929a769f3d134a/cd284945-1be9-4db4-a964-48bebdbbf2dd)
