### ISSUE TITLE
Model builder for Visual Studio Code

### ISSUE THREAD

**Issue by ansarizafar** [dotnet/machinelearning-modelbuilder#2094]
It would be great If we have a Model builder extension for Visual Studio Code. Is there any plan to provide support for VS Code?

**Comment by beccamc** [comment]
@JakeRadMSFT and @luisquintanilla to respond. Thanks!

**Comment by luisquintanilla** [comment]
Hi @ansarizafar 

Thanks for your question. Support Model Builder in Visual Studio Code is not currently in our roadmap. If you're looking for tooling options for cross-platform scenarios, we recommend using the [ML.NET CLI](https://docs.microsoft.com/dotnet/machine-learning/how-to-guides/install-ml-net-cli?tabs=windows). 

We also encourage and promote community contributions / solutions. For example, some time ago @franzsilva created this great [VS Code extension](https://marketplace.visualstudio.com/items?itemName=franzssilva.ml-net-model-builder) that leveraged the ML.NET CLI to train ML.NET models similar to Model Builder.

**Comment by beccamc** [comment]
Thanks for providing this suggestion! Closing as this is not in the roadmap for now. Please let us know if you have any other feedback.
