### ISSUE TITLE
Once the notebook(xxx.ipynb) file is opened, the debugging button name will not change to the startup project name when selecting a different startup project.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2096]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.5.2221501 (Main Build)
Microsoft Visual Studio Enterprise 2022: 17.1.3
.Net: 6.0

**To Reproduce**
  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core) project template with .Net 6.0.
  3. Add model builder by right click on the project.
  4. Choose a Scenario, Environment and Data.
  5. Train the model complete;
  6. On the Consume page, generate Console app, Web API and **Notebook**.
  7. **At this time, when selecting a different startup project, the debugging button name will change to the startup project name.**
  8. Open the generated notebook (xxx.ipynb) file.
  9. **At this time, when selecting a different startup project, the debugging button name will not change to the startup project name.**

**Expected behavior**
Even if the notebook(xxx.ipynb) file is opened, when selecting a different startup project, the debugging button name should change to the startup project name.

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/163783843-06f6e02d-7af2-4f81-b7be-251af70bff36.png)

**Gif:**
![#2095](https://user-images.githubusercontent.com/99375895/163783951-3c11987f-ed71-4708-85dd-22007865d320.gif)

**Comment by beccamc** [comment]
@v-Hailishi Interesting bug! Can you check if this happens with other non-C# files? If you open a .txt or .png file in VS and try this, what happens? 

If it's the same behavior for other non-code files let's close this issue.

**Comment by v-Hailishi** [comment]
@beccamc 
1. When I try to open a VB file, this issue doesn't happen.
![image](https://user-images.githubusercontent.com/99375895/163906704-711b4278-9329-410d-9a3f-f4cbd34d20ad.png)
2. When I try to open a .txt file, this issue doesn't happen.
![image](https://user-images.githubusercontent.com/99375895/163907256-0d3fe9d7-7a78-44d9-9e7e-1b4bdb631d47.png)
3. When I try to open a .png file, this issue doesn't happen.
![image](https://user-images.githubusercontent.com/99375895/163907477-e0be8ccf-790c-43be-a82f-4fa4cb8d86b3.png)

**Comment by beccamc** [comment]
@JakeRadMSFT What do you want to do here?

**Comment by v-Hailishi** [comment]
The bug is not repro on the latest main branch 16.13.6.2225901.
![image](https://user-images.githubusercontent.com/99375895/167591975-60a001a9-1ee9-4b52-b27c-5f5c8e670a1c.png)
