### ISSUE TITLE
Console App (.NET Framework) project debugged failed after completed the training.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2097]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.5.2221501 (Main Build)
Microsoft Visual Studio Enterprise 2022: 17.1.3
**.Net Framework: 4.7.2**

**To Reproduce**
  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Framework) project template with .Net framework 4.7.2.
  3. Add model builder by right click on the project.
  4. Choose Data classification Scenario, Environment and Data.
  5. **At this time, the project can be debugged successfully.**
  6. Train the model complete.
  7. At this time, the project will be debugged failed with error:
  "**Microsoft.ML currently supports 'x64' and 'x86' processor architectures. Please ensure your application is targeting 'x64' or 'x86'.**"

**Expected behavior**
Console App (.NET Framework) project should be debugged successfully after completed the training.
The issue is also repro on VS2019.
The issue is not repro for Console App (.NET Core) project

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/163792494-0c8b2462-eeae-4aa4-a11f-454e64801734.png)

**More info:**
After change the platform target to 'x64' or 'x86', then try debug again, at this time, the project can debug successfully.
![image](https://user-images.githubusercontent.com/99375895/163793427-e88a80d6-5bbb-43ac-87cf-10c4125d94ba.png)

**Comment by beccamc** [comment]
@v-Hailishi What as the platform target when it failed? 

> After change the platform target to 'x64' or 'x86', then try debug again, at this time, the project can debug successfully.

Based on this is works on x64 and x86. What was it set to when it failed? Thanks!

**Comment by v-Hailishi** [comment]
@beccamc  The platform target is set to "**Any CPU**" when it failed.

**Comment by LittleLittleCloud** [comment]
I feel like we shouldn't try fix this as the debug information is very helpful in fixing eror and we don't know if host project is target to x64 or x86, maybe just put "won't fix" for this issue?

**Comment by beccamc** [comment]
I agree with XiaoYun's assessment above. We will close this issue. Thanks for finding it Haili!
