### ISSUE TITLE
Projectnames with spaces fails when namespace is generated

### ISSUE THREAD

**Issue by Moskus** [dotnet/machinelearning-modelbuilder#2098]
**System Information (please complete the following information):**
 - Model Builder Version: 16.13.1.2210302
 - Visual Studio Version: 2022 17.1.4

**Describe the bug**
The generated code for console app creates namespace names with space, resulting in errors

**To Reproduce**
1. Create a project with a space in the name
2. Go through the MLBuilder wizard
3. At the "Consume" step, add a Console App to the solution.
4. Namespaces are then generated with spaces instead of a underscore and it generates errors

**Expected behavior**
I was expecting the MLBuilder to replace ' ' with '_'

**Comment by LittleLittleCloud** [comment]
@zewditu Can you take a look

**Comment by zewditu** [comment]
It is similar to this issue https://github.com/dotnet/machinelearning-modelbuilder/issues/2091.
