### ISSUE TITLE
Recommendation: After changing the feature column 's Data type from "Single" to "String", the training should be completed successfully for Data source from SQL Server.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2099]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.5.2221801 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.11); 2022(17.1.3)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: Training Recommendation with Data source from SQLPassword and SQL Server Database File.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv
https://testpass.blob.core.windows.net/test-pass-data/iris.mdf

**To Reproduce**

  1. Pre-requisite: Do [Pre-requisites/SQLPassword](https://github.com/dotnet/machinelearning-tools/blob/main/docs/tests/Instructions/Pre-Requisites/SQLPassword.md) before repro this issue.
  2. Select Create a new project from the Visual Studio start window;
  4. Choose the C# Console App (.NET Core) project template;
  5. Add model builder by right click on the project;
  6. Select Recommendation scenario>Local (CPU);
  7. On Data page, select>SQL Server>Microsoft SQL Server>SQL Server Authentication to input the data source;
      Or select>SQL Server>Microsoft SQL Server Database File to input the data source;
  8. Choose "rating" as Label, "userId" as User, "movieId" as Item and then click "Avanced data option".
  9. Change "rating" column's Data type to "Single".
  10. Change **"timestamp"** column 's Data type from "Single" to "String" and save it.
  11. Click Start training button, prompt model builder error as below screenshot.

**Expected behavior**
The training should be completed successfully after changing the feature column 's Data type from "Single" to "String".

**Screenshots**
Data settings:
![image](https://user-images.githubusercontent.com/99375895/163953140-721d2896-513f-4d1a-b8ff-8d030635f36d.png)

Error screenshot:
![image](https://user-images.githubusercontent.com/99375895/163953707-561ed2d8-0198-4b00-ace1-dcfb5dca3978.png)

**Additional context**
When do the same thing for the .csv file data source, the training can be completed successfully.
![image](https://user-images.githubusercontent.com/99375895/163954296-fef02db2-7bd0-49d0-84e6-93989f975ff0.png)
![image](https://user-images.githubusercontent.com/99375895/163954471-20d3eff6-5895-488a-910e-06d3a83cbad3.png)

**Comment by beccamc** [comment]
If we implement the custom SQL query it would make sense to just hide the advanced data options columns.

**Comment by luisquintanilla** [comment]
Work being tracked as part of #1935. Closing for now.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.13.10.2251801
![image](https://user-images.githubusercontent.com/99375895/196650483-80f47c2b-b7fc-4269-9aec-c477c5b252c5.png)
