### ISSUE TITLE
Migrate AutoML.NET Engine to Service Hub

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#210]
We need to Migrate the AutoML.NET Engine to Service Hub to leverage the 64bit versions of AutoML.NET.

**Comment by LittleLittleCloud** [comment]
just list some work that needed to be done in my mind

- [ ] design the way of communicating and controlling between service(AutoML Engine) and client(MB) over rpc (this step doesn't need servicehub, but may require refactor over AutoMLEngine)
- [ ] pull out autoMLEngine as a separate service and register that in host (CLR.X64)
- [ ] Call that service in MB

**Comment by JakeRadMSFT** [comment]
Prototype:

https://github.com/dotnet/machinelearning-tools/pull/282
