### ISSUE TITLE
"Evaluate" does not use regional settings for number formatting (uses . instead of ,)

### ISSUE THREAD

**Issue by Moskus** [dotnet/machinelearning-modelbuilder#2100]
**System Information (please complete the following information):**
 - Model Builder Version: 16.13.1.2210302
 - Visual Studio Version: 2022 17.1.4

**Describe the bug**
Evaluating the trained model when using single data is harder because I have to swap periods for commas, as we're using commas as decimal separators here (nb-no).

**To Reproduce**
1. Set comma as decimal separator
2. Train data using Tab-separated data (or any ohter I guess). The data uses . as decimal separator.
3. Go to Evaluate.
4. The Evaluaton will fail if I don't replace periods with commas, which can be time consuming.

**Expected behavior**
The number format should use the computers regional settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/320826/163955057-1b9d11f2-54f9-4087-addb-3f4888d26a15.png)

**Comment by LittleLittleCloud** [comment]
#1913

**Comment by beccamc** [comment]
Sorry about this issue. It looks to be a duplicate of 1913. To work around the problem, you should be able to change the "." to "," 

Please follow 1913 for updates on a fix. Thanks for reporting!
