### ISSUE TITLE
Evaluate: Easier access to other test data than just row 1 

### ISSUE THREAD

**Issue by Moskus** [dotnet/machinelearning-modelbuilder#2101]
**Is your feature request related to a problem? Please describe.**
Evaluate now only loads the first line of the training data. Having the option to select other rows would be great.

**Describe the solution you'd like**
Having a button with "Previous row" and "Next row" would solve it.
It would be even better if I could choose a specific row, using a textbox for entry number and a button labeled "Fetch row".

**Describe alternatives you've considered**
This could be solved with code, but it would be easier to evaluate the selected ML model during training.

**Comment by LittleLittleCloud** [comment]
@luisquintanilla for notification

**Comment by beccamc** [comment]
Short term, let's provide a code sample for this. Is it already included in consumption code?

**Comment by Moskus** [comment]
As far as I understand, the first row is always hard coded in the consumption code too. The code can of course be changed, but for evaluation and simple testing it's actually a bit more work than having access to more rows from the Test page.

One could argue that just presenting one data point for testing could be considered somewhat limiting and even misleading.

**Comment by luisquintanilla** [comment]
@mikehulme6498 please follow this issue for developments related to your request.
