### ISSUE TITLE
filePath cannot be null or empty

### ISSUE THREAD

**Issue by muti2** [dotnet/machinelearning-modelbuilder#2103]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.1.2210302
 - Visual Studio Version: 17.2.0 Preview 4.0
 - Windows 10.0.19.044 Build 19044
 - RAM: 16 GB
 - 11th Gen Intel(R) Core(TM) i5-1135G7

**Describe the bug**
- Pictures classification
- local cpu
- data: screenshots
- file name is in logic: folder_number (screen)
- Trainer: filePath cannot be null or empty

![1](https://user-images.githubusercontent.com/72250621/165089705-f11b0985-f5bb-41d9-a270-2872db0af69e.JPG)
![folder](https://user-images.githubusercontent.com/72250621/165092207-5743dbaf-e634-475b-8914-ece3449d6004.JPG)
[MLModel1-MIJFYW.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/8554584/MLModel1-MIJFYW.txt)

**Comment by muti2** [comment]
I dont know whats happend, but i created new project with the same images and everything seems to be ok....sorry.

**Comment by sakthishock** [comment]
Try reading the logs again. For image classification model, you need at least two classifier folders (parent/dogs, parent/cats). if you only have one classifier folder, you might see this error.
