### ISSUE TITLE
When start training, it fails immediately

### ISSUE THREAD

**Issue by TheAwerx** [dotnet/machinelearning-modelbuilder#2104]
**Model Builder Version**: 16.1.0.2027905
**Visual Studio Version**: Community 2019 Version 16.11.13
.Net Framework Version: 4.8.04084

**Bug description**
![fail1](https://user-images.githubusercontent.com/48297653/165256521-2dc3eeb5-0040-4cb5-a40e-7e719da1c4de.PNG)
[fail2.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/8561255/fail2.txt)

   konum: System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   konum: Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext() /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs içinde: satır 118
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs içinde: satır 147

When I start training it fails immediately

**Comment by TheAwerx** [comment]
I had only one label/sub-folder in my main folder. When I added one more label/sub-folder, start training didn't fail. But I want to train only one label. How can I achieve that?
Thanks in advance

**Comment by zewditu** [comment]
@TheAwerx thanks for using ml.net Model Builder

1. form your UI I see that you are in a very old model builder  the latest version is 16.13.1.2210301 and you can get it at  https://marketplace.visualstudio.com/items?itemName=MLNET.07
2 To build a multiclass classification model, the number of classes needs to be 2 or greater

**Comment by TheAwerx** [comment]
> @TheAwerx thanks for using ml.net Model Builder
> 
> 1. form your UI I see that you are in a very old model builder  the latest version is 16.13.1.2210301 and you can get it at  https://marketplace.visualstudio.com/items?itemName=MLNET.07
>    2 To build a multiclass classification model, the number of classes needs to be 2 or greater

I updated my model builder to 16.13.1.2210301 version. Now another error occures. I have tried to close/reopen VS, selecting another folder then reselecting my original folder as my data, closing and reopening model builder, covering the data of classes to even number; but none of these approaches didn't solve the error. I am waiting for your help. I think my error is similar to that one #2046 
![fail1](https://user-images.githubusercontent.com/48297653/165474540-ff879975-b91d-43a0-a115-f84f9300979f.PNG)
[MLModelFoodClassifier-DPEVTE.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/8570268/MLModelFoodClassifier-DPEVTE.txt)

**Comment by zewditu** [comment]
Do you have still one subfolder  in  your main folder

**Comment by TheAwerx** [comment]
@zewditu, No I have more than 2 subfolders

**Comment by zewditu** [comment]
@TheAwerx   If you add the subfolder to the existing Mainfolder it might relate to  https://github.com/dotnet/machinelearning-modelbuilder/issues/2046.
could you try creating a new folder add your subfolders?

**Comment by zewditu** [comment]
Follow up on this issue  here  https://github.com/dotnet/machinelearning-modelbuilder/issues/2046

**Comment by TheAwerx** [comment]
Renaming the main folder solved the issue. Thanks!
