### ISSUE TITLE
Telemetry Goals 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2105]
- [ ] Project type (framework vs core) 
- [x] Model Builder funnel - [link](https://dataexplorer.azure.com/dashboards/5b95430c-93c0-4ccd-9a6c-6237ce7acfce?p-_startTime=1hours&p-_endTime=now#e91dc92b-5fc0-43bd-ac5d-c5b4f8b70b1c)
- [x] Environment information (azure/gpu/local)
- [x] Dataset information (size, column count, etc) [link](https://dataexplorer.azure.com/dashboards/5b95430c-93c0-4ccd-9a6c-6237ce7acfce?p-_startTime=1hours&p-_endTime=now#d15abd4c-5a6a-44c2-affa-29bbc460e14a)
- [x] SQL vs. CSV usage - [link](https://dataexplorer.azure.com/dashboards/5b95430c-93c0-4ccd-9a6c-6237ce7acfce?p-_startTime=1hours&p-_endTime=now#d15abd4c-5a6a-44c2-affa-29bbc460e14a) "# Users by File Type"
- [x] SQL and csv errors [goal: improve experience by tracking and fixing common errors] - [link](https://dataexplorer.azure.com/dashboards/5b95430c-93c0-4ccd-9a6c-6237ce7acfce?p-_startTime=1hours&p-_endTime=now#9f814f50-49c1-4af4-8e3e-46f7f520f019) see data failure errors
- [x] Training information (train time, models explored etc.) [link](https://dataexplorer.azure.com/dashboards/5b95430c-93c0-4ccd-9a6c-6237ce7acfce#91919d98-b85e-4cf1-9ab9-fbd713a88432??p-_startTime=1hours&p-_endTime=now)
- [x] Usage of advanced features 

Long term goals: 
- How is the model performing? We don't have a way to track this now, because once we give the user the model we don't have a way to track how it's doing. -> Long term: Retrain story? Train/test/validate dataset.
- Log train time on Azure Compute -> Long term: Official docker image? 
- [x] Make sure Azure compute from Model Builder is getting tracked. - [link](https://dataexplorer.azure.com/dashboards/5b95430c-93c0-4ccd-9a6c-6237ce7acfce?p-_startTime=1hours&p-_endTime=now&tile=55566c74-9404-4a88-958e-6dffecfdbb18) our tracked training time for Azure runs

**Comment by torronen** [comment]
Would it be possible to get summary of Telemetry visible somewhere in the UI or website? Users may sometimes work with sensitive data (E.g. "antti_torronen_health_data_and_financial_transactions.csv") so it will be good to be able to confirm what might get sent. Maybe this list is somewhere already?

**Comment by JakeRadMSFT** [comment]
@torronen - Great suggestion! I like the idea of being more open about what we're tracking. We'll look into adopting something like this to help give folks peace of mind.

For people that really want to double check our work - you can use any networking capturing to see what we capture. We abide by all the GDPR guidelines and processes for privacy and PII information.

There is also an option to opt out: https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-experience-improvement-program?view=vs-2022#opt-in-or-out

We hope you stay opted in though - the telemetry is valuable for us to know what features are being used most and what we should invest in.

**Comment by beccamc** [comment]
Moving to next release. Need to figure out code for logging project type.

**Comment by luisquintanilla** [comment]
Work item complete.
