### ISSUE TITLE
PredictedLabel 

### ISSUE THREAD

**Issue by ericc8321** [dotnet/machinelearning-modelbuilder#2107]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luisquintanilla** [comment]
Hi @ericc8321 

Could you please provide more details about your issue.

**Comment by beccamc** [comment]
I suspect this is a duplicate of https://github.com/dotnet/machinelearning-modelbuilder/issues/2128
