### ISSUE TITLE
A column ignored in advanced option in forcasting still  avalible as an option for Label column 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2112]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/167723539-bd387ed9-c614-4506-8894-a83ee3ce3ef9.png)

**Additional context**

**Comment by zewditu** [comment]
In general, the refresh between advanced option and the combo box is too slow for other scenarios too.

**Comment by beccamc** [comment]
None of the column settings are applicable to Forecasting (@LittleLittleCloud to confirm). We should hide the Column Settings tab.

**Comment by luisquintanilla** [comment]
Duplicate of #2115
