### ISSUE TITLE
GPU validation section should be themed

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2113]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): main
 - Visual Studio Version Dev17
<img width="290" alt="image" src="https://user-images.githubusercontent.com/16876986/167723720-8d02c2b1-20ce-4a34-9c44-9418aa690d85.png">

**Comment by beccamc** [comment]
@v-Hailishi Can you validate if this is fixed?

**Comment by v-Hailishi** [comment]
@beccamc The bug is not repro on the latest main branch: 16.13.10.2245501
![image](https://user-images.githubusercontent.com/99375895/189011987-dd977c4e-6a6f-45c7-8bb3-86d26e305f68.png)
