### ISSUE TITLE
Install Cuda Link when Cuda is installed

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#2116]
"Install Cuda" link is showing up when it doesn't need to.

![image](https://user-images.githubusercontent.com/31937616/167728963-a3752880-e5db-417b-8ce4-05ca3e8d54fe.png)

**Comment by luisquintanilla** [comment]
Related to #2123

**Comment by beccamc** [comment]
@zewditu Can you just include a screenshot of the fix in the bug, then I think we can close.

**Comment by zewditu** [comment]
![Image](https://user-images.githubusercontent.com/36615490/174855423-60cc7b64-67b0-480c-9c2b-a6454e1bf68b.png)
