### ISSUE TITLE
Add support for ML.NET SaveAsText Format

### ISSUE THREAD

**Issue by evo11x** [dotnet/machinelearning-modelbuilder#212]
**System Information:**
 - Model Builder Version: 16.0.1907.1703
 - Visual Studio Version: 2017 15.9.13

I export my current ML.Net Data to a CSV with this function

using (var stream = File.Create("c:\\temp\\aidata.csv"))
             mlContext.Data.SaveAsText(trainData, stream);          
The saved data looks ok, but when I try to load the CSV with the ML.Net Model Builder 

I get this error: Data Error: Unable to infer column types of the file provided.

Note: I also have vector columns in the CSV

The CSV file looks like this (I have removed some colums to be smaller).

https://pastebin.com/xBBrpcaM

If I load the data file with mlContext.Data.LoadFromTextFile("c:\temp\aidata.csv"); it loads it without any error, but the Model Builder fails to load it.

**Comment by JakeRadMSFT** [comment]
It does not look like SaveAsText generated a valid CSV nor TSV. We can look into what format it's generating. 

What was the original data source?

**Comment by evo11x** [comment]
The original data source is built at runtime from lists, then saved with SaveAsText and the model builder cannot load it.

**Comment by evo11x** [comment]
Here is my complete CSV file saved with SaveAsText
https://file.io/UvlDDi

**Comment by beccamc** [comment]
Thanks for reporting! We're tracking this fix in #946. Please look there for updates. Thank you!
