### ISSUE TITLE
command not found: mlnet

### ISSUE THREAD

**Issue by Harshwardhanpjadhav** [dotnet/machinelearning-modelbuilder#2120]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
Are you running in MacOS or windows

**Comment by beccamc** [comment]
Sorry we don't have enough information to investigate. Please fill out the template if you still need help. Thanks!
