### ISSUE TITLE
Data classification: The mbconfig file would be abnormal closed after clicking the "Reload" or "Reload All" button on the Train page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2121]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.6.2226601 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.2.0)
**.Net Framework: 4.7.2**

**Describe the bug**
- On which step of the process did you run into an issue: 
  Click the "Reload" button on the Train page.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv 

**To Reproduce**

1. Select Create a new project from the Visual Studio start window;
2. Choose the C# Console App (**.NET Framework**) and .NET Framework 4.7.2 project template;
3. Add model builder by right click on the project;
4. Select Data classification scenario>Local (CPU);
5. On Data page, input the data source, then start training.
6. After training is done, click "Reload" or "Reload All" button on the pop-up dialog.
9. The mbconfig file would be abnormal closed.

**Expected behavior**
After you click the "Reload" button, the mbconfig file should be reload instead of abnormal closed.

**Gif:**
![#2120](https://user-images.githubusercontent.com/99375895/168745052-22c65f49-c3bc-4a56-b5fc-8c1b39773d2b.gif)

**Additional context:**
The bug is only repro on VS2022, not repro on VS2019.

**Comment by LittleLittleCloud** [comment]
We probably won't fix that, it's out of our control on how reload works in VS.

**Comment by v-Hailishi** [comment]
The bug is not repro on the latest VS version 17.2.6.
