### ISSUE TITLE
When using Visual Studio 2022, if the GPU extension is missing you send the user to 2019 Extension

### ISSUE THREAD

**Issue by DataJuggler** [dotnet/machinelearning-modelbuilder#2123]
I have to go the Marketplace and search to get find this link:

https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilderGPU2022

This happens on the screen when you are creating a new model in VS 2022. I selected local GPU. If VS detects the extension is missing, user is shown a link 'Get Extension'.

That link goes to 2019. It should go to the 2022 version if current VS version is 2022.

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! We'll get this taken care of!

**Comment by luisquintanilla** [comment]
This is WIP and PR is under review

cc @zewditu

**Comment by DifferentialityDevelopment** [comment]
The documentation here on how to add GPU support for the Model Builder in 2022 also links to the 2019 visual studio extension
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder
But I was able to install it by searching for the extension in Visual Studio 2022, perhaps add a link to the 2022 version in the documentation.

**Comment by beccamc** [comment]
@luisquintanilla Can you update the link to install the version in the doc above? Maybe two links that go to either 2019 or 2022

https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder

**Comment by luisquintanilla** [comment]
Done. PR pending review / merge. dotnet/docs#30786

**Comment by davidbuckleyni** [comment]
This link seems to be now invlaid showing a 404 page the link here sends to 404 

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/5619229/08f4bd5d-459f-4632-8176-80d78fbad47b)


![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/5619229/a2f07517-94f3-4e71-89c1-c0a9cacce59c)

Just to prove i have a 3070 ti laptop legion 5 i pro intel cpu and nvida 3070ti

**Comment by davidbuckleyni** [comment]
I also hit a block when come ot the docs form the above link

https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilderGPU2022

Coming from this 

https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder

When I try to install 10.1 nvdia cuda it says unsupported visual studio version when i have release and preview installed on same machine


![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/5619229/ebdf7132-075d-4606-9ab6-5364fd1a38f4)


![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/5619229/7f05c5ae-f1e6-42f4-baf6-90916398e86d)

Cuda version attempting to install as per instructions 

cuda_10.1.243_426.00_win10

https://developer.nvidia.com/cuda-10.1-download-archive-update2?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal

When you see below i get the following error

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/5619229/eb4fc569-157f-48fa-b7e5-ef78a696e81e)

**Comment by davidbuckleyni** [comment]
> @luisquintanilla Can you update the link to install the version in the doc above? Maybe two links that go to either 2019 or 2022
> 
> https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder

This is now invalid see my post above @luisquintanilla

**Comment by davidbuckleyni** [comment]
For people with issues this is the version u need for 2022 and nvida

**Comment by davidbuckleyni** [comment]
But it still does not solve the GPU extension is missing problem

**Comment by luisquintanilla** [comment]
@davidbuckleyni since the release in February, the GPU extension is no longer a requirement. 

https://devblogs.microsoft.com/dotnet/sentence-similarity-mlnet-model-builder/#model-builder-gpu-extension-no-longer-required

Can you please try upgrading to the latest version. 

https://learn.microsoft.com/dotnet/machine-learning/how-to-guides/install-model-builder?tabs=visual-studio-2022#uninstall-model-builder

**Comment by davidbuckleyni** [comment]
> [luisquintanilla](/luisquintanilla)

Well the installer is still broken as thats how i got to that point so please investigate with the visual studio team @luisquintanilla  the extension worked for me thanks

**Comment by davidbuckleyni** [comment]
@luisquintanilla  it still has not fixed the issue after installing the extension above the gpu mode is still disabled I have a legion 5i pro with NVIDA 3070 TI which is a supported card.

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/5619229/921c401f-310a-45eb-b084-677eebbefcda)

**Comment by GiaNTizmO** [comment]
> @luisquintanilla it still has not fixed the issue after installing the extension above the gpu mode is still disabled I have a legion 5i pro with NVIDA 3070 TI which is a supported card.
> 
> ![image](https://user-images.githubusercontent.com/5619229/246624746-921c401f-310a-45eb-b084-677eebbefcda.png)

Same too. Require GPU Extension while choose Local GPU Training.
Latest ML.NET Extension on my Visual Studio 2022 Preview

**Comment by luisquintanilla** [comment]
@DataJuggler @davidbuckleyni what scenario are you seeing this in?

**Comment by davidbuckleyni** [comment]
What u mean what scneriao its clear from above screen shot vs 2022 and file new Machine Learning ?

**Comment by luisquintanilla** [comment]
> What u mean what @DataJuggler @luisquintanilla scneriao its clear from above screen shot vs 2022 and file new Machine Learning ?

It's not clear from the screenshots unless I missed it. Is it Image Classification, Text Classification, Sentence Similarity, Object Detection?

**Comment by JamulusUser** [comment]
Once again:
the link to "Install Extension" is invalid. Is there a correct one?

17.6.4 Visual Studio 2022 version 17.6.4
released June 20th, 2023
Everything up to date with Visual Studio Installer

Installation of CUDA according to:
https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder
CUDA v10.1
cuDNN v7.6.4 for CUDA 10.1


![cuda](https://github.com/dotnet/machinelearning-modelbuilder/assets/38150953/02d98909-307b-4b2f-b460-bb7da2cfb594)

**Comment by JamulusUser** [comment]
I was able to fix the problem by simply installing the following:

https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022

I actually thought the Visual Studio Installer always updates everything automatically...

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/38150953/16bf14c4-f521-4db2-864c-d61bd65b0194)

**Comment by davidbuckleyni** [comment]
I still get this 

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/5619229/97247fd6-adf5-4c8c-9d46-88e73690bce5)

Even though my card is mobile
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/5619229/4b249a0e-7310-47c0-9ab3-374493dac7ef)
