### ISSUE TITLE
Change variable name from PredictedLabel

### ISSUE THREAD

**Issue by madison-passolano-ub** [dotnet/machinelearning-modelbuilder#2128]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable): 2022

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/consume 
- Clear description of the problem: on the Consume your model page, look at line 12 of the example Program.cs code. result.PredictedLabel should be result.Prediction. 

**To Reproduce**
1. follow the ML.NET Tutorial - Get started in 10 minutes https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/intro
2. on the Consume your model page, when you paste the sample Program.cs code into VS, you will receive an error saying that there is no instance of result.PredictedLabel. 

**Expected behavior**
What should happen is that you copy and run the code and receive whether or not the sampleData is positive or negative based on the prediction from the machine learning algorithm. 

**Screenshots**
Correct version: 
![Screenshot 2022-05-24 161311](https://user-images.githubusercontent.com/106165411/170133615-e3cae11f-e92c-45d8-a0f7-7c9f574e24a5.png)

Provided, incorrect version from tutorial: 
![Screenshot 2022-05-24 161440](https://user-images.githubusercontent.com/106165411/170133638-9e0686f9-6ab3-488b-b4d7-3443792554d7.png)

**Additional context**
I believe this is wrong because the result.PredictedLabel does not exist. I found the correct variable name by looking at the member variables of the class ModelOutput deom the *.consumptions.cs file.

**Comment by luisquintanilla** [comment]
Hi @madison-passolano-ub,

Which version of Model Builder are you using? If possible could you try to update to the latest version? 

Here's some instructions on how to update the extension: 

https://docs.microsoft.com/dotnet/machine-learning/how-to-guides/install-model-builder?tabs=visual-studio-2022#upgrade-model-builder

That worked for me. Here's the version I'm using.

![image](https://user-images.githubusercontent.com/46974588/170605367-f73f8bc7-6c3c-4498-9d31-b2100da7df1f.png)

Let us know if you're still having issues after updating Model Builder.

**Comment by beccamc** [comment]
Hi, please take a look at our troubleshooting doc on this issue if you're still having problems https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#cannot-run-code-from-tutorial-because-predictedlabel-does-not-exist
