### ISSUE TITLE
Please add code to do cross validation.

### ISSUE THREAD

**Issue by CBrauer** [dotnet/machinelearning-modelbuilder#2129]
I have three datasets: train, validate, and test.

Please consider adding the option to use all these datasets.
In paticular, do cross validation on the validate dataset.

**Comment by CBrauer** [comment]
Hi Becca,

 

Thanks for the notebook reference.

I have a question and I cannot find an answer. I’m interested in using Platt probability calculations.

I am wondering if it is possible to tell AutoML to calculate the Platt probabilities.

Any suggestions, or references, will be greatly appreciated.

 

Charles

**Comment by luisquintanilla** [comment]
cc @LittleLittleCloud

**Comment by LittleLittleCloud** [comment]
`LightGbm`, `FastTree`,  `Sdca` and `Lbfgs` should already use platt as calibrator so you can just use `Probabilities` column from `model.Transform`. For `FastForest`, you need to manually calibrate the model and here's [how](https://github.com/dotnet/machinelearning/issues/6120#issuecomment-1062339650) to do it.

**Comment by luisquintanilla** [comment]
Thanks @LittleLittleCloud. 

@CBrauer if you have additional questions, please feel free to create a new issue.
