### ISSUE TITLE
Model Builder generate invalid namespace for generated models

### ISSUE THREAD

**Issue by habib-developer** [dotnet/machinelearning-modelbuilder#213]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1907.1703
 - Visual Studio Version: 16.1.6

**Describe the bug**
The model builder generates invalid namespace if there is space in Project name.

**To Reproduce**
1. Make a project with the name containing space between words for instance "Semantic Analysis"
2. Right-Click on project > Add > Machine learning > Semantic Analysis
3. After every step, the model has been built, Try to build your model. 
4. It shows that your namespace "Semantic Analysis" is not valid because it contains space in names.

**Expected behavior**
The model builder should generate a namespace without space and space should be replaced by an underscore(_). For instance, if the project name is "Semantic Analysis" the generated model namespace should be "Semantic_Analysis".

**Comment by LittleLittleCloud** [comment]
It's a bug in `Code Generator`, I can take a look @JakeRadMSFT

**Comment by LittleLittleCloud** [comment]
> It's a bug in `Code Generator`, I can take a look @JakeRadMSFT

fixed

**Comment by habib-developer** [comment]
Thanks

**Comment by habib-developer** [comment]
Thanks
