### ISSUE TITLE
Retro Action items 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2130]
## April Retro actions 
| Responsibl |Action item    | Status |Comment|
|----------|-------------|------|------|
| Zewditu| Tracking board for action items| Done |This issue is used as tracking board |
| Everyone| Hold retros for specific topics on things that go very well or very poorly|  |
| Luis/Jake/Becca | New Github board | Done |
|| Complete vision doc. Share a new cohesive vision externally|No informatiton|
|Luis/Jake  |Harness power users. Maybe for panel?|Done|

**Comment by luisquintanilla** [comment]
@zewditu thanks for putting this together. Closing for now since most of the items on here are complete.
