### ISSUE TITLE
m,

### ISSUE THREAD

**Issue by Camkonrad** [dotnet/machinelearning-modelbuilder#2131]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by zewditu** [comment]
@Camkonrad could you tell us more  about your issue, it seems that it is just the template.

**Comment by beccamc** [comment]
Sorry @Camkonrad we need more information to solve this issue. Please file a new issue if you're still having problems. Thanks!
