### ISSUE TITLE
Suggestion: Update Model Builder to include support for NPU / TPU devices (USB or PCI-E) and non-CUDA GPUs

### ISSUE THREAD

**Issue by tauheedul** [dotnet/machinelearning-modelbuilder#2133]
Extend Model Builder support to include PCI-E or USB Machine Learning Accelerator processors e.g. NPU / TPU devices and non-CUDA Graphics cards

Laptops have limited processing power and not all developers are using CUDA powered Desktop workstations.
In some cases Developers may want to give their devices a boost using non-traditional processors. 

Examples include 
- PCI-E Accelerator based on Google Coral Edge TPU (CRL-G18U-P3DF)
- PCI-E Field Programmable Gate Array devices
- USB Google Coral Edge Accelerator
- USB Intel Movidius Neural Compute Stick

Potential application
The extension could list all possible processors available on a Desktop / Laptop and allow Developers to point to specific devices for training the model

These processors are optimised for the workload and could perform significantly better than regular CPUs and GPUs

**Comment by luisquintanilla** [comment]
Hi @tauheedul 

Thanks for this request. Currently ML.NET does not support this therefore it's not possible to enable this functionality in Model Builder. As a result, there are no plans to work on this at this time. As the ML.NET framework evaluates expanding support for these devices, Model Builder will reevaluate as well. 

Closing this issue for now
