### ISSUE TITLE
Telemetry complete Training  Event does not calculate the actual training time correctly at random 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#214]
- Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**
1. select scenario
2. select data 
3. Upload data
4. select train tab
6 set train time
7.click start training button

**Expected behavior**
**Screenshots**
![Capture.PNG](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/9ed4e9c2-c5ee-46f1-920b-4e23c9d67a85)
![Capture.PNG](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/38af0d75-8068-45b0-a67a-73aea036e814)**System Information (please complete the following information):**
**Additional context**

**Comment by JakeRadMSFT** [comment]
Please fill out the bug template (add more details, repro steps, and a GIF or images to this bug)

**Comment by zewditu** [comment]
@briacht   could you confirm what is really actual training duration mean, is that the duration from process start to stop ? or to the end of traning time

**Comment by justinormont** [comment]
Currently the time to generate the Visual Studio project is not included in the time. 

Most runtimes should be longer than 10 seconds (aim at ~150 model created). Hence I wouldn't be worried about the missing six seconds.

**Comment by briacht** [comment]
It would be from when the user selects "Start training" to when the Evaluate screen is available to them

**Comment by zewditu** [comment]
I think  this is what the current one is working, from user selects start training till evaluate tab is activated   . @JakeRadMSFT   what is your feedback?

**Comment by JakeRadMSFT** [comment]
By design
