### ISSUE TITLE
Update training.cs code-behind

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2143]
1. Add XML documentation to `RetrainPipeline` method:

```csharp
/// <summary>
/// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
/// </summary>
/// <param name="mlContext"></param>
/// <param name="trainData"></param>
/// <returns></returns>
public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
{
}
```

2. Change MLContext param name in `RetraionPipeline` to `mlContext` like the `BuildPipeline` model. 

 
![image](https://user-images.githubusercontent.com/46974588/172729258-e7f36e80-c77f-430c-955e-e3ddd3773176.png)

**Comment by beccamc** [comment]
@zewditu Would you be able to do this for the May release?

**Comment by beccamc** [comment]
![image](https://user-images.githubusercontent.com/9122518/174856569-3d503e38-dcb4-465c-964e-cff367986f89.png)
