### ISSUE TITLE
Unable the start program

### ISSUE THREAD

**Issue by Idaogah** [dotnet/machinelearning-modelbuilder#2149]
**System Information (please complete the following information):**

Hello,

It's  my first time to use ML.NET.
I ran into debugging issues while trying run my sample sentiment classification model. 
I was the final stage where I have to consume myMLApp. 
Please, see the screenshot. 

<img width="325" alt="t2" src="https://user-images.githubusercontent.com/77480065/173225526-58d2d7c0-64e8-4cdb-99c1-1c97ca320486.PNG">
<img width="328" alt="t1" src="https://user-images.githubusercontent.com/77480065/173225527-cb022eea-5f9e-4180-b1cd-f8bdacf250a6.PNG">

**Comment by beccamc** [comment]
@Idaogah Sorry you ran into this problem. What was the build error?

**Comment by beccamc** [comment]
When you build the project in VS does it show anything in the "Erro List"?

**Comment by Idaogah** [comment]
No. Everything works perfectly including testing.

**Comment by beccamc** [comment]
Apologies for the delay here. Is this error still happening?

**Comment by beccamc** [comment]
Any update here on getting the details of the build error?

**Comment by beccamc** [comment]
I don't have enough information to investigate this issue. if you're still seeing a problem please comment with more info.
