### ISSUE TITLE
Telemetry property "IsProjectAddSuccessful" is wrong if user declines to overwrite existing projects

### ISSUE THREAD

**Issue by tbombach** [dotnet/machinelearning-modelbuilder#215]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1908.1402
 - Visual Studio Version: 2019

**Describe the bug**
We log a telemetry point called `vs/modelbuilder/projectadded` when the user clicks "Add projects" in the Code tab. There is a property called `ModelBuilder.IsProjectAddSuccessful`, to track whether or not the project could be added successfully. This property doesn't get set to `False` when the user doesn't overwrite an existing project.

**To Reproduce**
*[Install and run the VS Telemetry Monitor](https://wiki.vsdata.io/visual_studio_telemetry_monitor?s[]=monitor). Restart VS (or the experimental instance) so that the monitor will capture telemetry*

1. Select a valid scenario and dataset, and successfully complete training.
2. Advance to the "Code" tab
3. Click the "Add projects" button. Observe that there is an event logged called `vs/modelbuilder/projectadded`, with the property `ModelBuilder.IsProjectAddSuccessful` set to `True`. This is expected
4. Go back to the `Evaluate` tab, then to the `Code` tab again
5. Click "Add projects" button again. There should be a warning that an existing project will be overwritten. Click "No" on this dialog, which will prevent the projects from being added to the solution.
6. Observe that there is another telemetry event `vs/modelbuilder/projectadded` logged and the property `ModelBuilder.IsProjectAdd` is set to `True`, but it should be `False`

**Expected behavior**
When the user chooses **not** to overwrite their project, the property `ModelBuilder.IsProjectAdd` should be false

**Screenshots**
### Overwrite dialog
![Screenshot (23)](https://user-images.githubusercontent.com/779479/63047649-b5b75a00-be89-11e9-897a-d678e73e3170.png)

### Telemetry monitor
![Screenshot (24)](https://user-images.githubusercontent.com/779479/63047667-c10a8580-be89-11e9-905f-4f9319bed555.png)

**Comment by JakeRadMSFT** [comment]
IsProjectAdded = false
UserOptedToOverwrite = false

Also reduce to one dialog

**Comment by zewditu** [comment]
what is UserOptedToOverwrite when the solution does not contain the two projects?
 or could we make enums for  UserOptedToOverwrite  { false, true, ?)?
