### ISSUE TITLE
Environment (GPU) accessibility  issues 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2155]
![image](https://user-images.githubusercontent.com/36615490/173460626-fb629cbd-fde6-4149-b913-b34e3ca84053.png)

**Comment by beccamc** [comment]
![image](https://user-images.githubusercontent.com/9122518/173701828-1568141a-992f-4a58-907f-acb1a3dabb2b.png)

**Comment by beccamc** [comment]
Validated by Zewditu
