### ISSUE TITLE
Model builder error window Acessibility 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2156]
![image](https://user-images.githubusercontent.com/36615490/173461573-cc5d7454-cdfc-4079-bbec-baa8cc46e6d7.png)

**Comment by beccamc** [comment]
![image](https://user-images.githubusercontent.com/9122518/173689491-8421c32f-e8f1-48d5-b06e-3b4adb33beb4.png)

**Comment by beccamc** [comment]
Validated by Zewditu
