### ISSUE TITLE
Forecasting data page acessiblity issue 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2158]
![image](https://user-images.githubusercontent.com/36615490/173464936-3a3f610c-1882-44e4-8282-886b8c62dcaa.png)

**Comment by beccamc** [comment]
![image](https://user-images.githubusercontent.com/9122518/173696552-99d7fca7-37f2-4d91-8d56-2b9324ab0f53.png)

**Comment by beccamc** [comment]
Validated by Zewditu
