### ISSUE TITLE
Forecasting evaluate page accessiblity issue 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2159]
![image](https://user-images.githubusercontent.com/36615490/173465504-6257ea65-78cb-4e53-b0cf-a5b1488009b3.png)

**Comment by beccamc** [comment]
![image](https://user-images.githubusercontent.com/9122518/173700003-82aabad8-9d49-4d23-8bf2-1ec576e7a927.png)

**Comment by beccamc** [comment]
Validated by Zewditu
