### ISSUE TITLE
Displaying "Finalizing model " when the traning failed  after status displyinhg  into "Finalizing model". It falshed "Failed"  then back to finalizing model 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#216]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_Displaying "Finalizing model " when the training failed  after status displaying  "Finalizing model". It fleshed "Failed"  then back to finalizing model .
**Steps to Reproduce**
1. selected price -prediction   scenario
2. select data ---> upload wiki statement
3.Train --> click start training 

**Expected Experience**
Status : "Failed. See more in Output Pane.";
**Actual Experience**
Status:  "Finalizing model"![Media1.gif](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/9ee4764d-cd9d-4ae9-a366-1b91edeb44d0)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by JakeRadMSFT** [comment]
Doesn't repro in latest build.
