### ISSUE TITLE
Although I have installed Notebook Editor in advance, I still need to install it on the Consume page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2160]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.8.2231401 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.2.2)
Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue:
Generated Notebook on the Consume page.

**To Reproduce**
**Pre-Requisites: Install the latest Notebook Editor: 0.3.4.2231003 from private feed https://privategallery.blob.core.windows.net/notebook-gallery/refs/heads/main/atom.xml**
<img width="471" alt="image" src="https://user-images.githubusercontent.com/99375895/173493276-ddd236fa-1528-4d26-a36a-f6a0fd9fc6e5.png">
  1. Select Create a new project from the Visual Studio start window;
  2. Choose the C# Console App and .NET6.0 project template;
  3. Add model builder by right click on the project;
  4. Select any scenario;
  5. Completed the training.
  6. On the "Consume" page, you will see that you still need to install Notebook Editor.
      After you click "Install Notebook" link to download and install it, it will be failed with error "The extension is already installed to all applicable product".

**Expected behavior**
You can generated Notebook successfully on the Consume page.

**Screenshots:**
![image](https://user-images.githubusercontent.com/99375895/173493740-d7eb3f79-227e-4f92-947f-0f5def2fba14.png)

**Additional context:**
If you didn't install Notebook Editor in advance, then install it directly from Consume page, it is also failed with below error.
6/13/2022 9:40:33 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

<img width="645" alt="image" src="https://user-images.githubusercontent.com/99375895/173494654-d65054c0-6375-4edb-8d92-eb57e5298ce8.png">

**Comment by beccamc** [comment]
@v-Hailishi Does this only happen when you're using the private feed?

**Comment by beccamc** [comment]
Never mind! I found the problem

**Comment by beccamc** [comment]
@JakeRadMSFT What do you think we should do for VS 2019? Not show the Notebook extension at all? Change then link to say something about VS 2022?

**Comment by v-Hailishi** [comment]
@beccamc The Notebook description to include that the extension is required has been changed and link has been changed to always be "add to solution" on the latest main branch: 16.13.9.2237501 for both VS2019&VS2022.
![image](https://user-images.githubusercontent.com/99375895/180914433-50b7f5eb-cc0f-40a9-ae5a-e0c3b24b3b47.png)
