### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by flowerdna** [dotnet/machinelearning-modelbuilder#2162]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
Please fill the template so we can help

**Comment by LittleLittleCloud** [comment]
close due to no response, feel free to reopen it if you have any questions
