### ISSUE TITLE
Error CS0103"The name 'context' does not exist in the current context" occurs when running generated Console App project and Web API project

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2164]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.8.2231501 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.2.2)
Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue:
Running the generated Console App project and Web API project for any scenario.

**To Reproduce**

  1. Select Create a new project from the Visual Studio start window;
  2. Choose the C# Console App and .NET6.0 project template;
  3. Add model builder by right click on the project;
  4. Select any scenario;
  5. Completed the training.
  6. On the "Consume" page, add Console App project, and Web API project.
  7. Running the generated Console App project and Web API project, you will see the error:
      "**The name 'context' does not exist in the current context**"

**Expected behavior**
Generated Console App project and Web API project can run successfully.

**Screenshots:**
<img width="659" alt="image" src="https://user-images.githubusercontent.com/99375895/173782298-7277fe76-4e3d-4e83-abf5-1365ce7dbbf8.png">

**Additional context:**
When you manually **change "context" to "mlContext"**, generated Console App project and Web API project can run successfully.
![image](https://user-images.githubusercontent.com/99375895/173782959-5fbd039a-ebad-4111-b430-9b3771888d13.png)

**Comment by LittleLittleCloud** [comment]
@zewditu

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch 16.13.9.2231506.
