### ISSUE TITLE
Datetime doesn't create correctly in code snippet

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2167]
<img width="439" alt="image" src="https://user-images.githubusercontent.com/16876986/173954674-7a271c8b-8722-4956-a54d-fbd9a057b8b9.png">

**Comment by LittleLittleCloud** [comment]
@beccamc 
If code snippet doesn't work, it's likely console app also doesn't work, we might want to fix this before release

**Comment by luisquintanilla** [comment]
@LittleLittleCloud good find. @beccamc I'm okay to ship this release without this fix as long as we make the changes in the next release.
