### ISSUE TITLE
Model Builder Cofiguration Page is Showing a Discrepant Value

### ISSUE THREAD

**Issue by PauloFilho852** [dotnet/machinelearning-modelbuilder#2170]
- Model Builder Version 16.13.9.2231505 
 - Visual Studio Version 17.2.4

**Describe the bug**
-In model bulding cofiguration page,  on value prediction mode, when evaluating the model, there is showing a discrepant value, even with 95% of model's accuracy. Despite that, the model is running regularly on the application. 
- Althoug the trained model is working regularly in the application, it has two three differents outputs for the same input (one in the provided console application by the model builder and another on the real application).

**Comment by LittleLittleCloud** [comment]
@PauloFilho852 thanks for reporting that issue, can you provide a minimal reproduction example for us, or small pieces of dataset, or training log? As the more information you provided, more helpful it will be for us to locate problems.

**Comment by PauloFilho852** [comment]
@LittleLittleCloud 
![imagem1](https://user-images.githubusercontent.com/56146300/174920764-7eeb2eb7-fa6c-4022-9c2f-e394b731e0c2.PNG)
![imagem2](https://user-images.githubusercontent.com/56146300/174920792-bc6c743d-2bee-49d7-8df3-132ddc4fe396.PNG)
![imagem3](https://user-images.githubusercontent.com/56146300/174920801-66876db3-6acf-410d-81d6-f47b5a7af583.PNG)

**Comment by LittleLittleCloud** [comment]
Have you tried re-run console app and re-try out in model builder consume page, and is the result deterministic?

And I noticed that in your laptop price predictor, ram type is capital (DDR), while in console app it's small letter (ddr). (and the GPU brand). Since either hash encoding or text featurizer is case sensitive, can you update them to match what it is in train dataset and try prediction again?

**Comment by PauloFilho852** [comment]
I converted all the letters to lowercase. I tested it several times and there are always different outputs between the console app and my application. But the big problem is the outlier on the model review page.

**Comment by LittleLittleCloud** [comment]
Got it, I assume it's probably because of the digital separator causes the inference engine fail to parse it to the right numeric value. Would you mind sharing with us a subset of your dataset so we can make a minimal reproduce?

**Comment by PauloFilho852** [comment]
You are right. The decimal separator is causing the error. Should be the model buider configaration page prepared to multiculture scenarios?

**Comment by PauloFilho852** [comment]
I suggest to adapt the Model Builder Configuration Page to multicultural when reading the data to perform the evaluation of the model.
