### ISSUE TITLE
Problem parsing decimal values like 1.1 when training the model on french system 

### ISSUE THREAD

**Issue by Philippe-Laval** [dotnet/machinelearning-modelbuilder#2171]
I was following the documentation :
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices-with-model-builder

When training the model, I got a problem with the CSV file containing decimal values for an-US like 1.1
Working with a french system, the value should be 1,1 to be parsed properly.
In the GUI, you should add a way to select the numerical settings in use.

   à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   à Microsoft.ML.ModelBuilder.AutoMLService.Proposer.HyperParameterProposer.Propose(TrialParameter trialParameter) dans /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/HyperParameterProposer.cs:ligne 66
   à Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() dans /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:ligne 61
   à Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() dans /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:ligne 136
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() dans /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:ligne 167   à StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()

**Comment by beccamc** [comment]
Sorry you ran into this problem! We have a setting for this in the GUI.  Open the "Advanced data option" link on the Data tab and go to Data formatting. You can select the decimal separator style. 

![image](https://user-images.githubusercontent.com/9122518/174874613-8a6fdc7d-2a8f-4ab4-9066-57085e5e00b1.png)

This should fix the error, but let us know if it doesn't. You can share you dataset and we can debug the problem.

**Comment by Philippe-Laval** [comment]
Hello,

Thanks for your reply. 
I tried again with the advanced settings setup correctly for the data (which is displayed properly in the column settings). I got the same exception (it seems the settings are not taken into account) during training of the model.
Regards
Philippe

**Comment by beccamc** [comment]
@Philippe-Laval Can you share your dataset? Or a partial dataset?

**Comment by beccamc** [comment]
Any update here? Can we see the dataset?

I would also make sure you're on the latest version - [16.13.10.2241902](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022)

**Comment by beccamc** [comment]
Sorry, I don't have enough information to investigate this issue. If you're still seeing this problem, a sample of your dataset would be helpful. Thanks!
