### ISSUE TITLE
Predicted value is always Zero 0

### ISSUE THREAD

**Issue by aminm1364** [dotnet/machinelearning-modelbuilder#2178]
**System Information (please complete the following information):**
 - OS & Version: Windows 11
 - ML.NET Version: ML.NET v16.13.9.2231505
 - .NET Version: .NET 6.0
 - Visual studio 2022 v17.2.5

**Describe the bug**
I am using the ```50 startups``` dataset (https://www.kaggle.com/datasets/farhanmd29/50-startups) and ```value prediction``` scenario.
after training the model (for about 1 minute), the predicted value is always zero!

**To Reproduce**
1. Download the ```50 startups``` dataset (https://www.kaggle.com/datasets/farhanmd29/50-startups)
2. Create a new ML.Net model
3. Choose the ```Value prediction``` scenario
4. In the ```Data``` step, Choose the ```Profit``` as the label
5. Train the model and go to the ```Next step```
6. Click on the ```Predict``` and check the Result.

**Screenshots, Code, Sample Projects**
![image](https://user-images.githubusercontent.com/27787679/176183078-701348ed-31df-4036-a019-2995f0b143cb.png)

Thank you in advance for any help.
Cheers :)

**Comment by aminm1364** [comment]
Hello @luisquintanilla,

and thanks for the reply.
I'm afraid those zeros are actually part of the Dataset and they're not missing data. 
Moreover, as an AutoML, I expect that the library can handle these kinds of data cleaning as well, which I believe ML.Net does.

Best,
Amin

**Comment by luisquintanilla** [comment]
@LittleLittleCloud do you know how AutoML handles outliers?

**Comment by beccamc** [comment]
@aminm1364 Any luck with the above advice?

**Comment by beccamc** [comment]
Thanks for reporting this problem. Please clear out the cache in %temp%AutoML-NNI and launch a new experiment to resolve this issue. If you're still having a problem please comment and we'll try to help out. Thanks!
