### ISSUE TITLE
A11y_Model Builder_Train_Focus Order: After entering “Training setup summary” control to expand/collapse, focus is shifting to whole train window.

### ISSUE THREAD

**Issue by manaswita-chougule** [dotnet/machinelearning-modelbuilder#2186]
### GitHubTags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #Visual Studio Client; #SH-ModelBuilder-Win32-Jun2022; #Win32; #WCAG2.4.3; #Focus Order;

### Environment Details:
Application Name: Model Builder
Windows Version: Windows 11 22H2 OS Builder 25145.1011
Visual Studio: Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.3.0 Preview 2.0

### Repro Steps:

1. Install Visual studio and open Visual studio
2. Navigate to C# project name and right click on it
3. Navigate to "Add" button and press enter
4. Navigate to "Machine learning model" and press enter
5. "Add new item" popup will open
6. Navigate to "Add" button and press enter
7. "Select scenario" popup will open and select "Forecasting" scenario
8. "Select training environment" page will open then select "Next step"
9. Tab till "Train" and press enter
10. Tab till "Training Setup Summary"and press enter.
11. Check whether the after entering “Training setup summary” control to expand/collapse, focus is shifting to whole train window or not.

### Actual Result:
After entering “Training setup summary” control to expand/collapse, focus is shifting to whole train window 

### Expected Result:
Focus should shift to remain on the same control afeter performing expand/collapse.

![After entering “Training setup summary” control to expandcollapse, focus is shifting to whole train window](https://user-images.githubusercontent.com/91586101/177050004-39bf09ed-ffe4-4f9c-bca0-40ab3c5474f2.gif)

**Comment by beccamc** [comment]
@manaswita-chougule  Please verify this on build 16.13.10.2241902 available from the Marketplace https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022

**Comment by manaswita-chougule** [comment]
Verified the issue in below environment:
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.4.0 Preview 1.0

The issue is fixed, hence closing the bug. Please find below attachment for reference.
![2186_train_focus order_fixed](https://user-images.githubusercontent.com/91586101/187127473-b1549dc6-1987-48e8-8d1f-3660d320c9c7.gif)
