### ISSUE TITLE
[DataFrame] IDataView <-> DataFrame Interop

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2192]
Interop between the IDataView and DataFrame is currently possible except when working with the following types:

- VectorDataViewType
- DateTimeDataViewType
- KeyDataViewType (UInt)

This causes calls to `.ToDataFrame()` to throw an error.

Add support for the data types listed above to enable deeper interop between DataFrame and IDataView.

**Comment by luisquintanilla** [comment]
DateTime and Vector complete. KeyType still pending implementation. Moving to December 2022

dotnet/machinelearning#6409

**Comment by luisquintanilla** [comment]
Stopping investingation into KeyDataViewType since we don't expect users to work with raw UInt data and instead use ValueToKey, KeyToValue transforms.

**Comment by beccamc** [comment]
@luisquintanilla I'm closing this as it won't be a priority from the MB side, and we have fixed the main pain points here :)

**Comment by luisquintanilla** [comment]
Sounds good. Thank you.
