### ISSUE TITLE
[Forecasting] Investigate auto-regressive algorithms

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2193]
Investigate auto-regressive algorithms:

- ARIMA
- SARIMA

To see what it would take to bring them to ML.NET

**Comment by luisquintanilla** [comment]
@LittleLittleCloud has code to train ARIMA model. Needs assistance from @michaelgsharp to integrate into ML.NET
@luisquintanilla to set up knowledge transfer session.

**Comment by LameuleFR** [comment]
Closed as completed but ARIMA is still unavailable in ML.Net
