### ISSUE TITLE
JSON input data source type

### ISSUE THREAD

**Issue by johnrickabe** [dotnet/machinelearning-modelbuilder#2194]
It's not really burden to convert JSON to CSV but having this feature would be great. :)

**Comment by JakeRadMSFT** [comment]
@johnrickabe thanks for reaching out!

Is it one or many JSON files? Is it an array of objects that are all the same shape?

**Comment by beccamc** [comment]
@johnrickabe We have a code sample for this! Take a look at our set of Notebooks, specifically [Data Preparation and Feature Engineering](https://github.com/beccamc/csharp-notebooks/blob/main/machine-learning/02-Data%20Preparation%20and%20Feature%20Engineering.ipynb) in the section **Loading in memory collection**. If you train with a .csv Model Builder we will generate sample Notebooks and code for you to use a baseline. 

Let me know if you have questions! We are looking to improve our notebooks and documentation so your feedback is appreciated.
