### ISSUE TITLE
[Notebooks] Create notebooks for limited scenarios

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2198]
In Model Builder we currently have the following unsupported scenarios:

- Anomaly Detection
- Clustering

Make the experience interactive and ready-to-run

- [ ] Creating notebooks for unsupported scenarios.
- [ ] Exposing notebooks in the Scenario screen.
  - [ ] Prompt installation of Notebook Editor extension 
  - [ ] Download scenario notebook
  - [ ] Launch scenario notebook in Visual Studio

**Comment by beccamc** [comment]
@luisquintanilla Should we close this?

**Comment by luisquintanilla** [comment]
Yup. Closing now
