### ISSUE TITLE
Get errors from SQL hangs the UI

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#22]
sometimes, we will get errors from SQL eg. accessing tables you don't have access to. (database_firewalls). Today the tool just hangs

![image](https://user-images.githubusercontent.com/1132652/57114123-9c383b00-6cfc-11e9-8ca8-8bde52e9dc5c.png)

**Comment by LittleLittleCloud** [comment]
appear again on Master commit 48cb2bcecffff82ab150e89d3343bfff4fc4b387, will take a look
