### ISSUE TITLE
mlnet regression cli model classed cannot be used to load data from csv

### ISSUE THREAD

**Issue by superichmann** [dotnet/machinelearning-modelbuilder#2206]
**System Information:**
 - OS & Version: Windows 10
 - ML.NET Version: tried on latest(`1.71`) and latest prerelease (`2.0.0-preview.22313.1`)
 - .NET Version: 6
 - cli version: `16.13.9+3066041f1761935763bdd267a9bcbb64cb3ec543`

**Describe the bug**
After creating the model C# files with the cli I am trying to test it on test data.

I receive the following error when trying to load from CSV:
`System.InvalidOperationException: 'Property 'A' is missing the LoadColumnAttribute attribute'` where 'A' is the first column within the CSV file.

**To Reproduce**
1. Download 3 csvs from below to an empty folder
2. Run the following command from the same folder : `mlnet regression --dataset random_train.csv --label-col D --cache Off --test-dataset random_test.csv --train-time 20`
3. Open the newly created SampleRegression.csproj in Visual Studio
4. Add the following line to the beginning main function in program.cs: `IDataView testData = mlContext.Data.LoadFromTextFile<SampleRegression.ModelInput>("random_validation.csv", separatorChar: ',', hasHeader: true);`

**Expected behavior**
The testData IDataView should be populated with the data from the csv ready for ML operations.

**Screenshots, Code, Sample Projects**
3 csv files are attached.
[random_test.csv](https://github.com/dotnet/machinelearning/files/9200515/random_test.csv)
[random_train.csv](https://github.com/dotnet/machinelearning/files/9200516/random_train.csv)
[random_validation.csv](https://github.com/dotnet/machinelearning/files/9200517/random_validation.csv)

**Note**: I would like on a later stage to get the r2 for the data via `mlContext.Regression.Evaluate`

**Comment by luisquintanilla** [comment]
Would you be able to provide what your model input / output class look like? At first glance, I suspect the reason for your issue is that the generated input class doesn't have the LoadColumn attributes. As a result, when trying to load the file, it doesn't know the index of the columns. I would recommend adding the LoadColumn attribute to each of the properties in ModelInput for it to work. Here are some samples of how to do that. 

https://docs.microsoft.com/dotnet/machine-learning/how-to-guides/load-data-ml-net#annotating-the-data-model-with-column-attributes

**Comment by superichmann** [comment]
Hi Luis, thanks for the quick response!

I have tried the `Enumerable<ModelInput>` method as well before posting here but it didn't work :(

I have managed to solve this by adding `LoadColumn(n)` with numbering to all of the data members.

I think that mlnet cli should populate the class with the necessary attributes in order for the csv loader to work properly without any changes :)
