### ISSUE TITLE
Training result section is missing on the Training page for all scenarios.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2208]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.9.2237801 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.17); 2022(17.2.6)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training result section is missing on the Training page for all scenarios.

**TestMatrix**
• Text Classification:
https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv
• Value prediction:
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv
• Recommendation:
https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv
• Image Classification:
https://testpass.blob.core.windows.net/test-pass-data/weather.zip
• Object detection:
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#create-a-new-vott-project
• Forecasting
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv

**To Reproduce**

  1. Pre-requisite: Do [Pre-requisites/SQLPassword](https://github.com/dotnet/machinelearning-tools/blob/main/docs/tests/Instructions/Pre-Requisites/SQLPassword.md) before repro this issue.
  2. Select Create a new project from the Visual Studio start window.
  3. Choose the C# Console App (.NET Core) project template.
  4. Add model builder by right click on the project.
  5. Select any scenario.
  6. On Data page, select the data source and label column.
  7. Click Start training button to finish Training, **then you will see that Training result section is missing**.
  8. On the Evaluate page, **the value of the best model section is also displayed improperly**. 

**Expected behavior**
Training result section and best model section should be displayed properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/181672299-73a636f5-c636-4aba-88ed-ebbe3a8069c4.png)
![image](https://user-images.githubusercontent.com/99375895/181673274-25bcffc6-7615-4031-a6f6-09ace39b427c.png)

**Comment by LittleLittleCloud** [comment]
This issue is already fixed in this PR
https://github.com/dotnet/machinelearning-tools/pull/1496

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch on the latest main branch 16.13.9.2240801 for both VS2019&2022.
![image](https://user-images.githubusercontent.com/99375895/183872700-def8d160-8842-49a6-9615-aeff4a556018.png)
![image](https://user-images.githubusercontent.com/99375895/183872540-bf147f5c-29ce-4d03-b1cd-0c4e72f48755.png)
