### ISSUE TITLE
Azure auth fail

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2214]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/16876986/183742069-960363ba-04ce-4de4-9750-07a85e8d7666.png">

**Comment by beccamc** [comment]
Is this a ship blocker? Or did you decide that this could be fixed later? @LittleLittleCloud Did you speak about this yesterday at standup?

**Comment by LittleLittleCloud** [comment]
It should be fixed already
