### ISSUE TITLE
Column separator option cannot be changed successful on the "Advanced data options->Data formatting" dialog.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2215]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2 
ML.Net Model Builder 2019&2022: 16.13.9.2241103 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.18); 2022(17.3.0)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Column separator cannot be changed successful on the "Advanced data options->Data formatting" dialog.

**To Reproduce**

  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select any scenario.
  5. On Data page, select the data source and label column, then click "Advanced data option..." link.
  6. Click "Data formatting" tab on the "Advanced data options" dialog.
  7. Change "Column separator" option to the other item, then click "Save" button.
  8. Open the "Advanced data options->Data formatting" dialog again and you will see that the value of Column separator option is still the original one.

**Expected behavior**
Column separator option should be changed successful.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/184326088-a5b4c1f4-4475-4b28-ab19-ce30beef659e.png)

**Gif**
![#2215](https://user-images.githubusercontent.com/99375895/184326409-6b2ce658-a21d-4bf0-a9a0-bcdd411cd970.gif)

**Comment by beccamc** [comment]
The root cause was that the call to update columns was failing to return the new columns. This made the whole update process cancel.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch: 16.13.9.2241702 for both VS2022&2019.
