### ISSUE TITLE
Data classification: VS would be crashed after click "Start training" button when choosing "Title" column as Label.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2216]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.9.2241103 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.18); 2022(17.3.0)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
VS would be crashed after click "Start training" button when choosing "Title" column as Label.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt

**To Reproduce**

  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification** scenario.
  5. On Data page, select the data source **"issues.tsv.txt"** and choose **"Title"** column as label.
  6. On the Train page, click "Start training" button, sometimes you will see that VS crash.

**Expected behavior**
Training is failed with error message and VS should not crash.

**Gif**
![#2216](https://user-images.githubusercontent.com/99375895/184337816-ffaf3270-3be7-4d8f-a1ea-4b905e421f7b.gif)

**Additional context:**
The bug is repro on both VS2022&VS2019.
Sometimes training is failed with error message normally.
![image](https://user-images.githubusercontent.com/99375895/184339063-794e4f3e-1437-431a-ba3a-de943171f5aa.png)

**Comment by beccamc** [comment]
This is a problem with the machine. It's out of memory. Closing as a not Model Builder issue.

**Comment by v-Hailishi** [comment]
@beccamc But testing the previous version in the same machine, VS crash and VS restarting never happen.
