### ISSUE TITLE
[proposal] validation datasource format in mbconfig

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2217]
This issue discusses how to save validation datasource in mbconfig

## Context on `DataSource`
All data-related informations, like data schema, parsing option, are saved in `DataSource` section in `.mbconfig`. It currently has four major types, which can be observed in `DataSource.Type` field.
- SQL
- TabularFile
- Folder
- Vott

Among those four types, `SQL` and `TabularFile` are for tabular-formatted datasource, like csv or tsv and are used in classification/regression/recommendation/forcasting. `Folder` is for image classification scenario and `Vott` for object detection. Moreover, `SQL` and `TabularFile` both contain a field called `ColumnProperties`, which is where the dataset schema is saved.

In this issue, we only talking about adding validation dataset for `TabularFile`, `SQL` and `Folder`.

## How is validation dataset created in the current `.mbconfig`
The `DataSource` in the current `.mbconfig` only allows a single datasource, which prevents model builder from using a separate data as validation. During training, that single data source will be split as train-test or cross-validation dataset based on its size, which impairs training performance.

## How will validation data be added to the current `.mbconfig`
The general idea is, for `SQL` and `TabularFile`, replacing them with a new `DataSource.Type` called `Tabular`, which includes three fields: `train`, `validate` and `schema`. In those three fields, `train` and `validate` will save parsing information and are used for loading data, which can be either a file or from SQL server. And `schema` will save schema, aka `ColumnProperties`. 

For `Folder` type, since there's no schema for this datasource type, only the `train` and `validate` fields will be added.

### Tabular
Current format
```json
"DataSource": {
    "Type": "TabularFile",
    "Version": 1,
    "FilePath": "iris.csv",
    "Delimiter": ",",
    "DecimalMarker": ".",
    "HasHeader": true,
    "ColumnProperties": [
      {
        "ColumnName": "sepal_length",
        "ColumnPurpose": "Feature",
        "ColumnDataFormat": "Single",
        "IsCategorical": false,
        "Type": "Column",
        "Version": 1
      },
      {
        "ColumnName": "sepal_width",
        "ColumnPurpose": "Feature",
        "ColumnDataFormat": "Single",
        "IsCategorical": false,
        "Type": "Column",
        "Version": 1
      },
      {
        "ColumnName": "petal_length",
        "ColumnPurpose": "Feature",
        "ColumnDataFormat": "Single",
        "IsCategorical": false,
        "Type": "Column",
        "Version": 1
      },
      {
        "ColumnName": "petal_width",
        "ColumnPurpose": "Feature",
        "ColumnDataFormat": "Single",
        "IsCategorical": false,
        "Type": "Column",
        "Version": 1
      },
      {
        "ColumnName": "species",
        "ColumnPurpose": "Label",
        "ColumnDataFormat": "String",
        "IsCategorical": true,
        "Type": "Column",
        "Version": 1
      }
    ]
  },
```

Updated format
(if `Validate` section is null, it means no validation data is provided and the validation datasource will be split from the `Train` datasource like the old time.)

```json
"DataSource": {
    "Type": "Tabluar",
    "Version": 1,
    "Train": {
      "Type": "File",
      "FilePath": "iris.csv",
      "Delimiter": ",",
      "DecimalMarker": ".",
      "HasHeader": true
    },
    "Schema": [
      {
        "ColumnName": "sepal_length",
        "ColumnPurpose": "Feature",
        "ColumnDataFormat": "Single",
        "IsCategorical": false,
        "Type": "Column",
        "Version": 1
      },
      {
        "ColumnName": "sepal_width",
        "ColumnPurpose": "Feature",
        "ColumnDataFormat": "Single",
        "IsCategorical": false,
        "Type": "Column",
        "Version": 1
      },
      {
        "ColumnName": "petal_length",
        "ColumnPurpose": "Feature",
        "ColumnDataFormat": "Single",
        "IsCategorical": false,
        "Type": "Column",
        "Version": 1
      },
      {
        "ColumnName": "petal_width",
        "ColumnPurpose": "Feature",
        "ColumnDataFormat": "Single",
        "IsCategorical": false,
        "Type": "Column",
        "Version": 1
      },
      {
        "ColumnName": "species",
        "ColumnPurpose": "Label",
        "ColumnDataFormat": "String",
        "IsCategorical": true,
        "Type": "Column",
        "Version": 1
      }
    ]
  }
```

`Train` and `Validate` can be different data source. For example, `Train` can be from file, and `Validate` can be from sql

```json
"DataSource": {
    "Type": "Tabluar",
    "Version": 1,
    "Train": {
      "Type": "File",
      "Version": 0,
      "FilePath": "/path/to/file",
      "Delimiter": ",",
      "DecimalMarker": ".",
      "HasHeader": true
    },
    "Validate":{
        "Type": "SQL",
        "Version": 0,
    }
  }
```

### Folder

current format
```json
  "DataSource": {
    "Type": "Folder",
    "Version": 1,
    "FolderPath": "WeatherData2"
  },
```

updated format
```json
  "DataSource": {
    "Type": "Folder",
    "Version": 1,
    "Train":  "/path/to/folder",    
    "Validate": "/path/to/folder",
  },
```

**Comment by LittleLittleCloud** [comment]
#60

**Comment by LittleLittleCloud** [comment]
@luisquintanilla @beccamc  @zewditu @JakeRadMSFT

**Comment by luisquintanilla** [comment]
Thanks for this detailed writeup @littlelittlecloud.

LGTM.

**Comment by luisquintanilla** [comment]
File paths are the only data source option for now. If we want more data sources in the future, we may want to go with this approach. Closing for now.
