### ISSUE TITLE
Forecasting: Generated Console App cannot run on .NET6.0 in VS2022.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2220]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.9.2241702 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.0)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Generated Console App cannot run on .NET6.0 in VS2022 for Forecasting scenario.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Forecasting** scenario.
  5. On Data page, select the data source and then completed the training.
  6. On the Consume page, click "Add to solution" button to generate a Console App.
  7. Choose the generated Console App as startup project and then run it.
  8. **You will see that it reminded you need to install .NET5.0.**

**Expected behavior**
The generated Console App should run successfully.
The default Target Framework should be 6.0 for the generated Console App.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/185527063-572582a8-f022-4a0a-b5f7-8b3b08f568a1.png)

**Additional context:**
1. The default Target Framework is 5.0 for the generated Console App.
![image](https://user-images.githubusercontent.com/99375895/188114609-367129db-6c26-420f-8b64-3e4abc6ccd1d.png)
2. After you installing **.NET5.0** from https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64, the generated Console App can run successfully.

**Comment by luisquintanilla** [comment]
May be related to #2401.

**Comment by zewditu** [comment]
The generated project always targeted to .net 5

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.2.2306903.
<img width="493" alt="image" src="https://user-images.githubusercontent.com/99375895/213665090-5f368321-3d16-4c08-b5ed-7adc12edb546.png">
