### ISSUE TITLE
Model Builder Error

### ISSUE THREAD

**Issue by kitosd** [dotnet/machinelearning-modelbuilder#2221]
**System Information (please complete the following information):**
 - Model Builder Version : 16.1.0.20.27905
 - Visual Studio Version : 16.11.18

Bug description
With freshly-updated [as of today, 2022-08-19] VS2019 and model builder, I tried to use the new ML builder wizard "Value prediction". It failed with an exception: Method not found: 'System.Collections.Generic.IEnumerable1<System.ValueTuple2<Microsoft.ML.AutoML.RunDetail`1<!!0>,Int32>> Microsoft.ML.AutoML.BestResultUtil.GetTopNRunResults

Steps to Reproduce

Installed latest VS 2019 and updated Model Builder to latest version
Create new project. Right click on project -> Add -> "Machine Learning"
Choose image classification, "Local ML", Next.
As input, choose an appropriate folder, observe "data preview" looks like I expected, with images being shown under various classifications
Train, Start Training.
Expected Experience
Pretty much what I'd expect from the tutorial, and of a wizard.

Actual Experience
Shortly after click "start training", I get this:
"GPU Service not found. Falling back to CPU AutoML Service."

Moments later, this exception:
Method not found: 'System.Collections.Generic.IEnumerable1<System.ValueTuple2<Microsoft.ML.AutoML.RunDetail1<!!0>,Int32>> Microsoft.ML.AutoML.BestResultUtil.GetTopNRunResults(System.Collections.Generic.IEnumerable1<Microsoft.ML.AutoML.RunDetail1<!!0>>, Microsoft.ML.AutoML.IMetricsAgent1<!!0>, Int32, Boolean)'.
at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment3.<ExecuteAsync>d__21.MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment3.ExecuteAsync(IDataView trainData, IDataView validateData, ColumnInformation columnInformation, Nullable1 userCancellationToken, Nullable`1 timeout)
at Microsoft.ML.ModelBuilder.AutoMLEngine.d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 147

**Comment by beccamc** [comment]
Sorry you ran into this problem! To be clear you are using...

- VS 2019
- Image classification scenario
- GPU training environment 

Is this correct?

**Comment by kitosd** [comment]
> Sorry you ran into this problem! To be clear you are using...
> 
> 
> 
> - VS 2019
> 
> - Image classification scenario
> 
> - GPU training environment 
> 
> 
> 
> Is this correct? 

•VS2019 
yes

•Image classification scenario
yes but every scenario doesn't work

•GPU training environment 
yes both GPU and CPU

**Comment by beccamc** [comment]
Can you update your Model Builder to the latest version - [16.13.10.2241901](https://marketplace.visualstudio.com/items?itemName=MLNET.07)

**Comment by beccamc** [comment]
Any update with the latest version of Model builder?

**Comment by kitosd** [comment]
> Any update with the latest version of Model builder?

I cannot update 16.13.10.2241901
I have this Install error

Microsoft.VisualStudio.Setup.PackageFailureException:
Package 'Incredibuild' failed to download;Package 'Unity3d.x64' failed to download; 'Linux.GCC.arm_none_eabi' failed to download; 'Microsoft.VisualStudio.WorkflowManagerTools.Msi' failed to download;

**Comment by beccamc** [comment]
I haven't seen that before. It could be a problem with the VS version. Are you able to update any other extensions?

Looks like a similar problem in [this thread](https://social.msdn.microsoft.com/Forums/vstudio/en-US/ee1259f1-97df-45e8-8729-973c73ce5e4b/microsoftvisualstudiosetuppackagefailureexception-package?forum=vssetup). Can you update VS successfully? What version of VS are you on?

**Comment by kitosd** [comment]
> I haven't seen that before. It could be a problem with the VS version. Are you able to update any other extensions?
> 
> 
> 
> Looks like a similar problem in [this thread](https://social.msdn.microsoft.com/Forums/vstudio/en-US/ee1259f1-97df-45e8-8729-973c73ce5e4b/microsoftvisualstudiosetuppackagefailureexception-package?forum=vssetup). Can you update VS successfully? What version of VS are you on?

VS version is 16.11.18
I can update successfully

**Comment by kitosd** [comment]
I tried uninstall and re-Install model Builder Extension. 
This is the Install Log. Sorry, the result include Japanese Language

2022/09/29 18:25:44 - Failed to create scheduled task: UpdateConfiguration_S-1-5-82-3006700770-424185619-1745488364-794895919-4004696415
2022/09/29 18:25:44 - Failed to create the update configuration task for user IIS APPPOOL\DefaultAppPool: (9,79):UserId:S-1-5-82-3006700770-424185619-1745488364-794895919-4004696415
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.8: 現在の OS のバージョン '10.0.19043.0' は、サポートされるバージョンの範囲 '[6.2,6.3)' に含まれていません。
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.81: 現在の OS のバージョン '10.0.19043.0' は、サポートされるバージョンの範囲 '[6.3,6.4)' に含まれていません。
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.Net.4.7.2.FullRedist: 現在の OS のバージョン '10.0.19043.0' は、サポートされるバージョンの範囲 '[6.1.1,10.0.16299]' に含まれていません。
2022/09/29 18:25:52 - Windows Installer found the package 'Microsoft.VisualStudio.FileHandler.Msi,version=16.11.31503.54,chip=x86' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
2022/09/29 18:25:52 - Windows Installer found the package 'Microsoft.VisualStudio.FileHandler.Msi,version=16.11.31503.54,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.VisualStudio.Debugger.DbgHelp.Win8: 現在の OS のバージョン '10.0.19043.0' は、サポートされるバージョンの範囲 '[6.1,6.3]' に含まれていません。
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8: 現在の OS のバージョン '10.0.19043.0' は、サポートされるバージョンの範囲 '[6.1,6.3]' に含まれていません。
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8: 現在の OS のバージョン '10.0.19043.0' は、サポートされるバージョンの範囲 '[6.1,6.3]' に含まれていません。
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.VisualStudio.NuGet.PowershellBindingRedirect: 現在の OS のバージョン '10.0.19043.0' は、サポートされるバージョンの範囲 '[6.1,6.2)' に含まれていません。
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.7: 現在の OS のバージョン '10.0.19043.0' は、サポートされるバージョンの範囲 '[6.1,6.2)' に含まれていません。
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.DiagnosticsHub.KB2882822.Win7: 現在の OS のバージョン '10.0.19043.0' は、サポートされるバージョンの範囲 '[6.1,6.2)' に含まれていません。
2022/09/29 18:25:52 - Windows Installer found the package 'Microsoft.VisualStudio.AspNetDiagnosticPack.Msi,version=16.11.110.1451' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.Net.4.8.FullRedist: 現在の OS のバージョン '10.0.19043.0' は、サポートされるバージョンの範囲 '[6.1.1,10.0.17763]' に含まれていません。
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.Azure.PowerShell: 必要な条件を満たしていません: Not Powershell5
2022/09/29 18:25:52 - Skipping non-applicable package Microsoft.VisualStudio.OfficeDeveloperTools.WindowsIdentityFoundation.Msu: 現在の OS のバージョン '10.0.19043.0' は、サポートされるバージョンの範囲 '(,6.2)' に含まれていません。
2022/09/29 18:25:52 - Windows Installer found the package 'Microsoft.NetCore.TargetingPack.5.0.5.0.0,version=16.11.32901.82,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
2022/09/29 18:28:54 - Package 'Unity3d.x64,version=7.0,chip=x64' failed to download from 'https://go.microsoft.com/fwlink/?linkid=2167741'. WebClient download failed: リモート サーバーに接続できません。. Bits download failed: エラー コンテキスト: BG_ERROR_CONTEXT_REMOTE_FILE、エラー コード: -2145844845. WinInet download failed: Function: HttpQueryInfo-ResponseCode, HR: -2147024493, Message: Url 'https://public-cdn.cloud.unity3d.com/hub/2.4.4/UnityHubSetup.exe', Signature: PackageId=Unity3d.x64;PackageAction=DownloadPackage;ReturnCode=0x80131500
2022/09/29 18:28:54 - Skipping Install of 'Unity3d.x64,version=7.0,chip=x64' since the package or a parent package had a vital failure.
2022/09/29 18:28:54 - Skipping cache of package 'Unity3d.x64,version=7.0,chip=x64' since the package or a parent package had a vital failure.
2022/09/29 18:28:54 - Skipping cache of package 'Component.UnityEngine.x64,version=16.10.31205.252' since the package or a parent package had a vital failure.
2022/09/29 18:29:50 - インストール エラー : System.AggregateException: 1 つ以上のエラーが発生しました。 ---> Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Unity3d.x64' failed to download
   場所 Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   場所 Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   場所 Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   場所 Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   場所 Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0() 場所 D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\SetupEngine\SetupEngineService.cs:行 50
   場所 System.Threading.Tasks.Task`1.InnerInvoke()
   場所 System.Threading.Tasks.Task.Execute()
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 Microsoft.VisualStudio.ExtensionManager.SetupEngineService.Install() 場所 D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\SetupEngine\SetupEngineService.cs:行 50
   場所 Microsoft.VisualStudio.ExtensionManager.InstallModule.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension) 場所 D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:行 1030
   場所 Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion) 場所 D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:行 265
   場所 Microsoft.VisualStudio.ExtensionManager.InstallModule.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion) 場所 D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:行 399
   場所 Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp) 場所 D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:行 901
---> (内部例外 #0) Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Unity3d.x64' failed to download
   場所 Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   場所 Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   場所 Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   場所 Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   場所 Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0() 場所 D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\SetupEngine\SetupEngineService.cs:行 50
   場所 System.Threading.Tasks.Task`1.InnerInvoke()
   場所 System.Threading.Tasks.Task.Execute()<---

**Comment by kitosd** [comment]
I couldn't understand it,so I posted all Install Log.

**Comment by beccamc** [comment]
Okay, I think you answered in another issue, but is upgrading to VS 2022 an option?

**Comment by kitosd** [comment]
yes, I have installed VS2022 and try ModelBuilder,but I have same error

**Comment by kitosd** [comment]
Yes.
but I will uninstall and re-install.

**Comment by beccamc** [comment]
Are you able to share your dataset with us?

**Comment by kitosd** [comment]
I tried this tutorial. so,I think my dataset isn't problem.

https://learn.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices

**Comment by beccamc** [comment]
I'm confused if you're doing image classification or value prediction? What scenario are you doing?

**Comment by kitosd** [comment]
Sorry,I tried both scenarios. 

This dataset is in case of value prediction.

https://learn.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices

**Comment by beccamc** [comment]
So Model Builder isn't working for any scenario, on both VS 2022 and VS 2019. And you're using the default dataset from the tutorial? 

The original error looks like it was maybe a configuration problem and starting a new .mbconfig file would resolve the issue.

**Comment by beccamc** [comment]
Did starting a new mbconfig file solve the problem?

**Comment by zewditu** [comment]
@kitosd  if you still hit the issue feel free to reopen the issue.
