### ISSUE TITLE
zsh: command not found: mlnet

### ISSUE THREAD

**Issue by AbdallahR99** [dotnet/machinelearning-modelbuilder#2222]
I can't use `mlnet` command it's always shows `zsh: command not found: mlnet`

I tried to add in the environment but still not works

works only when I use `~/.dotnet/tools/mlnet` instead

here is the `PATH` value: `PATH=/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Python.framework/Versions/3.10/bin` 

my macOS informations: macOS Big Sur 11.6.8 (20G730)

**Comment by beccamc** [comment]
@LittleLittleCloud Can you provide some guidance here?

**Comment by LittleLittleCloud** [comment]
Can you try replace alias `~` with it's full path (I remember it's /user/home or so?) and try again. If I recall correctly, there's issue with dotnet tool that can't parse `~` correctly

**Comment by luisquintanilla** [comment]
You'll need to give mlnet executable permissions and include mlnet to the system path. Instructions on how to do this should appear in the terminal when you install mlnet (or any global tool).

@LittleLittleCloud do we have those instructions so I can update the docs with them?

**Comment by beccamc** [comment]
@LittleLittleCloud Are there instructions for Luis? (see above)

**Comment by luisquintanilla** [comment]
See #2409 for answer. Closing this issue since there's a PR to address this issue in dotnet/docs#33384
