### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error	CS1061	'SentimentModel.ModelOutput' does not contain a definition for 'PredictedLabel' and no accessible extension method 'PredictedLabel' accepting a first argument of type 'SentimentModel.ModelOutput' could be found (are you missing a using directive or an assembly reference?)	myMLApp	C:\Users\Andrej\source\repos\myMLApp\myMLApp\Program.cs	15	Active

### ISSUE THREAD

**Issue by 1gituser** [dotnet/machinelearning-modelbuilder#2229]
**System Information (please complete the following information):**
 - Model Builder or CLI Version:  2022
 - Visual Studio Version (if applicable):2022

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/consume
- Clear description of the problem: Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SentimentModel.ModelOutput' does not contain a definition for 'PredictedLabel' and no accessible extension method 'PredictedLabel' accepting a first argument of type 'SentimentModel.ModelOutput' could be found (are you missing a using directive or an assembly reference?)	myMLApp	C:\Users\Andrej\source\repos\myMLApp\myMLApp\Program.cs	15	Active

**To Reproduce**

1. Go to 'program.cs' and replace the code with the one from the tutorial:

using MyMLApp;
// Add input data
var sampleData = new SentimentModel.ModelInput()
{
    Col0 = "This restaurant was wonderful."
};

// Load model and predict output of sample data
var result = SentimentModel.Predict(sampleData);

// If Prediction is 1, sentiment is "Positive"; otherwise, sentiment is "Negative"
var sentiment = result.PredictedLabel == 1 ? "Positive" : "Negative";
Console.WriteLine($"Text: {sampleData.Col0}\nSentiment: {sentiment}");

2. run it with or without debugging, F5 or Ctrl+F5 and you get the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SentimentModel.ModelOutput' does not contain a definition for 'PredictedLabel' and no accessible extension method 'PredictedLabel' accepting a first argument of type 'SentimentModel.ModelOutput' could be found (are you missing a using directive or an assembly reference?)	myMLApp	C:\Users\Andrej\source\repos\myMLApp\myMLApp\Program.cs	15	Active

Please advise.

Thanks and regards,

**Comment by beccamc** [comment]
Sorry you ran into this problem! This is probably happening because you're on an older version of ML.NET 

> In a newer version of ML.NET the property Prediction was renamed to PredictedLabel. You are referencing an older version of ML.NET. There are a few options for resolving this.
> 
> 1. Change PredictedLabel to Prediction.
> 2. Update ML.NET to 1.7.1
> 3. Update Model Builder version to the latest and re-train the model

**Comment by beccamc** [comment]
Please refer to the troubleshooting doc for more info. https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md
