### ISSUE TITLE
Should not generate DataModels folder

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#223]
**System Information (please complete the following information):**
 - Model Builder Version: Model Builder Version: 16.0.1909.402
 - Visual Studio Version: VS Enterprise 2019 (v. 16.2.3)

**Describe the bug**
When Model Builder generates the projects, there should not be a DataModels folder; ConsumeModel.cs, ModelInput.cs, and ModelOutput.cs should all be at same level as MLModel.zip in the project, not in a separate folder.

**To Reproduce**
1. In Code step, select Add Projects
2. See Solution Explorer
3. If you try to follow Next Steps, won't work correctly because of namespaces because it is set up as if there is no extra folder level

**Expected behavior**
No DataModels folder; consumption code should work without extra myAppML.Model.DataModels namespace

**Screenshots**
![image](https://user-images.githubusercontent.com/10437687/64366571-5f8e9000-cfcb-11e9-990c-95f5103ceeaa.png)

**Comment by LittleLittleCloud** [comment]
switch to the latest [build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3019744) and that problem should be solved

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud  Can you verify it's fixed and resolve.

**Comment by LittleLittleCloud** [comment]
fixed
