### ISSUE TITLE
filePath cannot be null or empty 参数名: filePath

### ISSUE THREAD

**Issue by philix615** [dotnet/machinelearning-modelbuilder#2230]
在 Microsoft.ML.Runtime.Contracts.CheckNonEmpty(IExceptionContext ctx, String s, String paramName)
   在 Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   在 Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() 位置 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:行号 236
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() 位置 /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:行号 161

**Comment by beccamc** [comment]
Can you make sure you're on the latest version of Model Builder? https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022

**Comment by beccamc** [comment]
Any update on the latest version of Model Builder?

**Comment by beccamc** [comment]
Sorry, I don't have enough information to investigate. If this is still a problem in the latest version feel free to ping me to re-open.
