### ISSUE TITLE
Image classification-Azure: Training failed when you create and use a "Standard_NC24" or "Standard_NC24r" size compute.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2233]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.10.2243103
**URL: https://privategallery.blob.core.windows.net/gallery/refs/heads/u/zewd/UpdateVmsHotFix/atom.xml**
Microsoft Visual Studio Enterprise: 2019(16.11.18); 2022(17.3.0)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training failed when you create and use a "Standard_NC24" or "Standard_NC24r" size compute for Image classification-Azure scenario.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/weather.zip

**To Reproduce**

  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select "Image classification>Azure" and then click "Set up workspace" button on the Environment page.
  5. On the "Create new experiment" dialog, choose Subscription and Workspace, then click "New..." link next to "Compute name" option.
  6. On the "Create new compute" dialog, give the compute name, then **select "Standard_NC24" or "Standard_NC24r" compute size** to complete the Environment selection. 
  7. On the Data page, choose large size images folder (Contains 1125 images).
  8. On the "Training" page, you will see the training is failed with error.
     **There is not enough GPU memory on the machine to do the requested operation. Please try running the experiment on a VM with higher GPU memory, decrease the batch size or image size.**

**Expected behavior**
Training should be successful when you create and use a "Standard_NC24" or "Standard_NC24r" size compute.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/188074732-1632c8e9-acb2-40f7-8e05-b7a670fb15c0.png)
![image](https://user-images.githubusercontent.com/99375895/188086573-90502ef5-7bd1-45c1-b9d8-138276ea7eca.png)
![image](https://user-images.githubusercontent.com/99375895/188076518-aa0f6a3c-b550-4010-82e4-7c478c28f9e2.png)
![image](https://user-images.githubusercontent.com/99375895/188076649-816e151d-97b6-4052-8634-bcf551cefaed.png)

**Additional context:**
1. Repro on both of VS2022&2019.
2. If I choose small size image folder (Contains 64 images), training can be successful.
3. The bug is not repro when you create and use a "Standard_NC6" or "Standard_NC12" size compute.
4. RunID: https://ml.azure.com/experiments/id/891078f2-635b-4e43-849b-f5129264b1fa/runs/AutoML_53a4146f-0395-4312-a5d2-b0867e4cd9e8?wsid=/subscriptions/83635e26-687a-4333-a2a0-33e3cd1f573a/resourceGroups/FullTestPass/providers/Microsoft.MachineLearningServices/workspaces/FullTestPass&tid=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by beccamc** [comment]
@zewditu Can you look at this? Is this the right list of computes?

**Comment by zewditu** [comment]
I used the old  vm-sizes to create  compute .

@v-Hailishi  are you able to get successful run  for already created computes with this vm-sizes? becouse Still we let userds to use existing computes with this vm-sizes

**Comment by v-Hailishi** [comment]
@zewditu I am able to get successful run for already created computes with "Standard_NC6" or "Standard_NC12" vm-sizes.
But I am not sure for "Standard_NC24" and "Standard_NC24r" vm-sizes, because I have no these size computes before.

**Comment by v-Hailishi** [comment]
The bug is also repro on the main branch: 16.13.10.2245501.

**Comment by v-Hailishi** [comment]
Verified on the /u/zewd/UpdateVmsHotFix/ version 16.13.10.2245201 and main branch: 16.13.10.2245501
1.	The Azure computes size have been updated like below.
![image](https://user-images.githubusercontent.com/99375895/188582891-1c21b6ca-fd5f-4aa6-96f8-a6916d7ab112.png)

2.	When creating all new computes with **Dedicated** priority, I met the error message like below.
I also tried to increase the vCPU quotas for Standard NCv3 family vCPU, but I cannot find "Standard NCv3 family vCPU" quota under subscription "ML.NET Model Builder Demo" on the My quotas page. Could you help to take a look?
![image](https://user-images.githubusercontent.com/99375895/188583046-37d7ea44-ad1d-4d36-b5e4-d58adce38db2.png)
![image](https://user-images.githubusercontent.com/99375895/188583112-c876da3a-1288-4ce5-97b2-d0a822471272.png)

3.	When creating all new computes with **Low** priority, they can be created successfully. But the training is always pending on "Provisioning compute..." step like below.
![image](https://user-images.githubusercontent.com/99375895/188583222-5079fe72-9646-4427-8b26-3b9dda93578a.png)
![image](https://user-images.githubusercontent.com/99375895/188583287-e7fc95b0-fa13-481d-a560-71299222c183.png)

**Comment by beccamc** [comment]
Tracking this in https://github.com/dotnet/machinelearning-modelbuilder/issues/1702
