### ISSUE TITLE
Recommendation: The predicted rating is garbled on the Evaluate page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2235]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.10.2245501 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.18); 2022(17.3.0)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The predicted rating is garbled on the Evaluate page for Recommendation scenario.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv
https://testpass.blob.core.windows.net/test-pass-data/iris.mdf

**To Reproduce**

  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **Recommendation** scenario.
  5. On Data page, select the data source and completed the training. 
  6. On the Evaluate page, click "Predict" button and check the evaluate results.

**Expected behavior**
The predicted rating is accurate and has no garbled on the Evaluate page.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/188558483-b89f054d-0151-4dab-a459-56c759368d28.png)

**Additional context:**
![image](https://user-images.githubusercontent.com/99375895/188558542-8931723e-4684-4dae-81a9-22325529a896.png)

**Comment by LittleLittleCloud** [comment]
can't reproduce in latest main

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch: 16.13.10.2245801
![image](https://user-images.githubusercontent.com/99375895/189254529-2dda6fb7-e89f-4eeb-afe2-17f3d7c6566b.png)
