### ISSUE TITLE
Recommendation: Generated Web API is running failed with error 500.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2236]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.10.2242201 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.18); 2022(17.3.0)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Generated Web API is running failed with error 500 Recommendation scenario.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv
https://testpass.blob.core.windows.net/test-pass-data/iris.mdf

**To Reproduce**

  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select "Recommendation" scenario to complete the training;
  5. Click "Add to solution" to add the Web Api project to your current solution.
  6. Run the application.
  7. Open PowerShell and enter the following code where PORT is the port your application is listening on.
      **$body = @{ 
	UserId = 1
	MovieId = 3
      }
      Invoke-RestMethod  "https://localhost:PORT/predict"-Method Post -Body ($body | ConvertTo-Json) -ContentType "application/json"**

**Expected behavior**
Run successful and display the expected output.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/188560427-40a5de7a-71cb-48dd-b811-60f347c93bb9.png)

**Additional context:**
Repro on both of VS2022&2019.

**Comment by LittleLittleCloud** [comment]
Verify on latest main and no reproduce

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch: 16.13.10.2245801
![image](https://user-images.githubusercontent.com/99375895/189254655-d527cfcd-4ff6-45b5-8434-197efd57973b.png)
