### ISSUE TITLE
Prediction result from Azure image classification is rediculous

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2239]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/16876986/189246597-1c437092-5f43-41bb-8559-d310eb879ee4.png">

This is because the normalizer layer is missing from onnx model

<img width="632" alt="image" src="https://user-images.githubusercontent.com/16876986/189246450-6e7d04f0-9f24-489d-9396-bc15fa211b7a.png">

To fix this, we need to set `enable_onnx_normalization` to true in `AmlJsonSettingString` when kicking off aml job, for both object detection and image classification.

**Comment by zewditu** [comment]
Now we do not have `AmlJsonsetting` , we use the sdk, hence the sdk should have a way  to enable  `enable_onnx_normalization `
