### ISSUE TITLE
Change default state for Code step

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#224]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1909.402
 - Visual Studio Version: VS Enterprise 2019 (v. 16.2.3)

**Describe the bug**
The new project names are shown before projects are generated (before the user selects Add Projects).

**To Reproduce**
1. Select Add Projects in Code step

**Screenshots**
![image](https://user-images.githubusercontent.com/10437687/64369293-ded29280-cfd0-11e9-959e-24d31a92b9ff.png)

**Expected behavior**
Default text:
Add the machine learning model and the projects and references for model consumption and training to your solution.

Updated text after projects are generated:
Add the machine learning model and the projects and references for model consumption (myAppML.Model) and training (myAppML.ConsoleApp) to your solution.

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud Can you change the text to "Add the machine learning model and the projects and references for model consumption and training to your solution." and keep it static (not changing).

Pranav approved the static behavior .
