### ISSUE TITLE
Training failed with model builder error on the Training page for all scenarios.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2240]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2019&2022: 16.13.10.2245801 (Main Build)
Microsoft Visual Studio Enterprise: 2019(16.11.18); 2022(17.3.0)
.Net: 5.0 & 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training failed with model builder error on the Training page for Data classification scenario.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv 
https://github.com/dotnet/machinelearning-samples/raw/main/samples/modelbuilder/MulticlassClassification_RestaurantViolations/RestaurantScores.zip

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select "Data classification" scenario and data source;
  5. Click "Start training" button on the Train page.
  
**Expected behavior**
Training should be successful on the Training page.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/189263333-123e8752-4bb3-4e0c-b3ef-34936fb9c582.png)
![image](https://user-images.githubusercontent.com/99375895/189297876-47b219fb-9db3-4e9c-b2a6-61d8008c2891.png)

**Additional context:**
1. On VS2019, all scenarios are failed.
2. On VS2022, only Image classification-Azure and Object detection scenarios failed.

**Comment by LittleLittleCloud** [comment]
the image classification and object detection error should be fixed by this [PR](https://github.com/dotnet/machinelearning-tools/pull/1523)

**Comment by v-Hailishi** [comment]
Verified on the latest main branch 16.13.10.2246201, the bug has been fixed for Image classification-Azure and Object detection scenarios on VS2022.

**Comment by v-Hailishi** [comment]
The bug is only fixed on VS2022, but still repro on VS2019.

**Comment by LittleLittleCloud** [comment]
THe fix for VS2019 is not check in yet
https://github.com/dotnet/machinelearning-tools/pull/1526

**Comment by beccamc** [comment]
Moving to current milestone for 2019 fix.

**Comment by LittleLittleCloud** [comment]
@v-Hailishi the fix for VS2019 should be checked in.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main branch 16.13.10.2246901 for VS2019.

**Comment by luisquintanilla** [comment]
@LittleLittleCloud I see this has been resolved. Are we okay to close?

**Comment by beccamc** [comment]
This looks verified by v-Hailishi. I'm closing.
