### ISSUE TITLE
Notebook is generated failed with error "Value cannot be null".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2241]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2245801 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.0)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Notebook is generated failed on the Consume page.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv
https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Data classification" or "Value predication" or "Recommendation" or "Forecasting"** scenario and data source to complete the training;
  5. Click "Add to solution" button next to "Notebook" section on the Consume page.
  6. On the "Add Notebook" dialog, give the Notebook name, then click "Add solution" button.
   
**Expected behavior**
The notebook should be generated successfully. 

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/189281265-31cb0133-e21d-42f0-8be1-080b583d2e82.png)

**Additional context:**
Repro on: Data classification, Value predication, Recommendation, Forecasting scenarios.

**Comment by beccamc** [comment]
Removing Notebook https://github.com/dotnet/machinelearning-tools/pull/1555
