### ISSUE TITLE
Compare AutoML InferColumns to PROSE column inference 

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2243]
In Model Builder and the ML.NET CLI, we leverage the PROSE set of libraries to infer column types on a dataset.

The AutoML API provides the `InferColumns` method which has a different implementation. [Sample](https://gist.github.com/luisquintanilla/fa3e8d1fb61c7f8669be179efe4e0bae)

Compare both approaches based on:

- Time
- Accuracy / Correctness

 Use the benchmark results to align both implementations with the one that works best.

**Comment by beccamc** [comment]
Unfortunately the PROSE license won't work for open source. We need to drop this investigation.
