### ISSUE TITLE
Forecasting: The name of the best accuracy is missing and the value for it is wrong in Training results.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2246]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2246501 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.0)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The name of the best accuracy is missing and the value for it is wrong in Training results.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv
https://github.com/dotnet/machinelearning-samples/raw/main/samples/csharp/getting-started/Forecasting_BikeSharingDemand/BikeDemandForecasting/Data/DailyDemand.mdf

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select ** "Forecasting" ** scenario and data source to complete the training;
  5. Check the training results on the Train page.
  6. You will see that the name of the best accuracy is missing and the value for it is wrong.
  
**Expected behavior**
The name and value of the best accuracy should be displayed well.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/190572129-f19f897c-f76c-47c4-a74f-cf0504b3d721.png)

**Additional context:**
![image](https://user-images.githubusercontent.com/99375895/190572231-087864fa-a461-4fb2-9b9d-64328e4d7afc.png)

**Comment by LittleLittleCloud** [comment]
should already be fixed in main

**Comment by v-Hailishi** [comment]
@LittleLittleCloud The bug is still repro on the latest main branch: 16.13.10.2246901

**Comment by LittleLittleCloud** [comment]
We just update latest main and it should be 16.13.10.2247001 now

**Comment by v-Hailishi** [comment]
Still repro on the latest main branch: 16.13.10.2247001

**Comment by luisquintanilla** [comment]
Unable to repro in latest build 16.14.0.2252005

![Image](https://user-images.githubusercontent.com/46974588/197071663-11121cff-e559-4d11-85e4-d35b58f4d53f.png)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build:
![image](https://user-images.githubusercontent.com/99375895/197479157-32aa65b0-9ca9-4a34-9d40-462030533ab4.png)
