### ISSUE TITLE
Change PredictedLabel to Prediction

### ISSUE THREAD

**Issue by severalpens** [dotnet/machinelearning-modelbuilder#2248]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/consume
- Clear description of the problem:
`SentimentModel.ModelOutpu`t does not contain a definition for `PredictedLabel`.

Fixed by changing `PredictedLabel ` to `Prediction`

**To Reproduce**
1. Go to '[...](https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/consume)'
2. Paste code
4. See error:
 ```Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SentimentModel.ModelOutput' does not contain a definition for 'PredictedLabel' and no accessible extension method 'PredictedLabel' accepting a first argument of type 'SentimentModel.ModelOutput' could be found (are you missing a using directive or an assembly reference?)	myMLApp	```


**Expected behavior**
Successful build

**Comment by LittleLittleCloud** [comment]
which version of cli are you using

**Comment by beccamc** [comment]
@v-Hailishi Can you confirm this works on the latest CLI version?

**Comment by v-Hailishi** [comment]
@beccamc  The bug is not repro on the latest main build:  16.13.10.2251201, I can run the project successfully.
![image](https://user-images.githubusercontent.com/99375895/195560905-b02cabf3-7a19-43b5-aafd-fbf7e790a369.png)

**Comment by beccamc** [comment]
Thanks for reporting @severalpens! We have confirmed this is fixed in a new version.
