### ISSUE TITLE
In a .NET Core Console App, reference to model class library is not added

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#225]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1909.402
 - Visual Studio Version: VS Enterprise 2019 (v. 16.2.3)

**Describe the bug**
When you add projects in the Code generation step, reference to the class library project is not added.

**To Reproduce**
1. Create .NET Core Console App
2. Choose any scenario and train the model
3. Select Add Projects in Code step

**Screenshots**

**Expected behavior**
Reference to the class library is added.

**Comment by JakeRadMSFT** [comment]
Can't repro. Can you verify with latest build?
