### ISSUE TITLE
Label column purpose in Advanced Data Options is set to Feature 

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2253]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.10.2245901
 - Visual Studio Version: VS 2022 17.3.4

**Describe the bug**
- On which step of the process did you run into an issue: Data
- Clear description of the problem: 

Column purpose doesn't match between main Data page and Advanced Data Options dialog. 

The column purpose in Advanced Data Options shows the selected Label columns as `Feature`

**To Reproduce**
1. Select Forecasting scenario
2. Load data from SQL Server
3. Select Label column
4. Open Advanced Data Options dialog

**Expected behavior**

Advanced Data Options and main Data page should be in sync.

**Screenshots**

![image](https://user-images.githubusercontent.com/46974588/191819768-a99482bc-8735-4b5b-92c8-382b7c70ad7b.png)

**Comment by beccamc** [comment]
We removed support for column settings in forecasting 

![image](https://user-images.githubusercontent.com/9122518/192878606-fdbbb509-8d85-4741-82cd-f097982e420f.png)

I don't have a repro in the other scenarios. 

![image](https://user-images.githubusercontent.com/9122518/192878753-191fea9f-56cf-4307-8672-32de4e169555.png)
