### ISSUE TITLE
Load IDataView in generated console project

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2257]
Image Classification 
- [x] Read from memory - [Issue](https://github.com/dotnet/machinelearning-modelbuilder/issues/851) 

Text 
- [x] Load into IDataView from csv
- [x] Load into IDataView from SQL

**Comment by luisquintanilla** [comment]
@beccamc I think this is a good candidate to track in #1638

**Comment by beccamc** [comment]
Project with notes that Luis and I discussed for how training file should look: 
[SQLExampleCode.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/9668056/SQLExampleCode.zip)

**Comment by beccamc** [comment]
PR with updated IDataView code for text scenarios. https://github.com/dotnet/machinelearning-tools/pull/1620

**Comment by beccamc** [comment]
Here are the sample training files for image and text. [SampleTraining.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/10179555/SampleTraining.zip)

**Comment by beccamc** [comment]
Note: we need to add the file header and separator information for the file

**Comment by beccamc** [comment]
This has been validated in bug bashes. One outstanding issue - https://github.com/dotnet/machinelearning-modelbuilder/issues/2440
