### ISSUE TITLE
Data Preview summary does not clear if select new scenario

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#226]
**System Information (please complete the following information):**
-Model Builder Version: 16.0.1909.402
-Visual Studio Version: VS Enterprise 2019 (v. 16.2.3)

**To Reproduce**
1. Upload dataset
![image](https://user-images.githubusercontent.com/10437687/64451571-5835b800-d099-11e9-959d-b0394f8d1621.png)

2. Go back to Scenario and choose another scenario
![image](https://user-images.githubusercontent.com/10437687/64451712-9c28bd00-d099-11e9-80ec-ce17d92cc3ad.png)

3. Data Preview Summary still there
![image](https://user-images.githubusercontent.com/10437687/64451689-8b784700-d099-11e9-998f-5c72fab9c0e9.png)

**Expected behavior**
Selecting a new scenario should clear out Data Preview summary.

**Comment by JakeRadMSFT** [comment]
@tbombach Can you see if this repros after your changes?

**Comment by tbombach** [comment]
No repro - tested this after my changes
