### ISSUE TITLE
Data classification: Training is pending on "Finalizing model..." step when choosing "ID" or "Title" or "Description" column as Label.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2263]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2247801 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training is pending on "Finalizing model..." step when choosing "ID" or "Title" or "Description "column as Label.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt

**To Reproduce**

  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification** scenario.
  5. On Data page, select the data source **"issues.tsv.txt"** and choose **"ID" or "Title" or "Description"** column as label.
  6. On the Train page, click "Start training" button, you will see that training is pending on "Finalizing model..." step.

**Expected behavior**
Training should be failed with model builder error message.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/193201604-ec07b077-c3f8-4111-b7d9-e47852807e85.png)

**Comment by luisquintanilla** [comment]
@v-Hailishi Thanks for looking into this. Since ID, Title, Description are technically valid inputs, it shouldn't fail. The user needs to provide the correct column they're looking to predict. 

Question: Does training ever finish?

**Comment by v-Hailishi** [comment]
@luisquintanilla The training always stay on "Finalizing model...", never finished.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.15.0.2320602.
![image](https://user-images.githubusercontent.com/99375895/230568398-67782ae2-877d-4f98-979f-da89cd5670fc.png)
