### ISSUE TITLE
程序包还原失败

### ISSUE THREAD

**Issue by heidirac** [dotnet/machinelearning-modelbuilder#2268]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.10.2241902
 - Visual Studio Version 2022 17.3.4

**Describe the bug**
- On which step of the process did you run into an issue:训练
- Clear description of the problem:训练结束的时候出现：Model builder错误  提示：程序包还原失败

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
dup of #2138

**Comment by luisquintanilla** [comment]
> dup of #2138 you can refer to this comment for a quick fix [#2138 (comment)](https://github.com/dotnet/machinelearning-modelbuilder/issues/2138#issuecomment-1159092539)

Are we okay to close this issue then since it sounds like it's resolved and there's a workaround in the meantime?
