### ISSUE TITLE
Data classification: Evaluate Metric name "MacroAccuracy" is missing on the Evaluate page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2271]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2250701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Evaluate Metric name "MacroAccuracy" is missing on the Evaluate page for Data classification scenario.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv 

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification** scenario.
  5. On Data page, select the data source and choose **Sentiment** column as label.
  6. On the Train page, click "Start training" button to complete the training. (**The default Metric is "Macro-Accuracy"**)
  7. On the Evaluate page, you will see that Evaluate Metric name "MacroAccuracy" is missing.

**Expected behavior**
Evaluate Metric name "MacroAccuracy" should be displayed normally. 

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/194822338-3a630458-4ebf-4d1f-ab0a-ba5eb077f66e.png)

**Comment by beccamc** [comment]
@zewditu It seems like this one should be included in the current milestone too.

**Comment by zewditu** [comment]
Note able to reproduce it on latest main 



![Image](https://user-images.githubusercontent.com/36615490/196815933-924fef62-8d87-44fc-8b63-b47a4697b36f.png)

**Comment by v-Hailishi** [comment]
@zewditu I can still repro this bug on the latest main build: 16.13.10.2251901.
The bug is only repro when you directly using metric "Macro-Accuracy" and never change the metric.
Once you have changed the metric and re-use metric "Macro-Accuracy", the bug will not repro.

**Comment by zewditu** [comment]
I am following the step strictly but am still not able to reproduce it, please check it again on the latest main build.

**Comment by v-Hailishi** [comment]
@zewditu The bug has been fixed on the latest main build: 16.14.0.2252005
<img width="378" alt="image" src="https://user-images.githubusercontent.com/99375895/197167062-20fa9931-3782-4e44-a2cd-d9000b9fb832.png">

**Comment by v-Hailishi** [comment]
Closed as fixed
