### ISSUE TITLE
Data classification: The best model and its value are wrong for the metric "Log-Loss Reduction" on the Train and Evaluate page.  

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2273]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2250701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The best model and its value are wrong for the metric "Log-Loss Reduction" on the Train and Evaluate page for Data classification scenario.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv 

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification** scenario.
  5. On Data page, select the data source and choose **Sentiment** column as label.
  6. On the Train page, click "Advanced training options..." link, then choose another metric like "**Log-Loss Reduction**" and save it.
  7. Click "Start training" button to complete the training, you will see the best model and its value are wrong on the Train and Evaluate page.

**Expected behavior**
The best model and its value should be correct on the Train and Evaluate page. 

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/194980632-5268da42-25dc-4c70-bf60-c4d343f99c35.png)

**Comment by v-Hailishi** [comment]
The bug is also repro on evaluation metrics "**AUC**", "**AUCPR**" and "**F1-score**" for Binary Classification.
![image](https://user-images.githubusercontent.com/99375895/195059616-cc47b844-cc46-4d1d-a921-13333ce26b3b.png)
![image](https://user-images.githubusercontent.com/99375895/195059864-104e89b8-780c-42e1-85fa-c73b6fdac668.png)
![image](https://user-images.githubusercontent.com/99375895/195059901-a65d1685-da06-4fc9-98ab-ba5a737f193f.png)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2252103
![image](https://user-images.githubusercontent.com/99375895/197462398-6f3c2116-1e7f-47f8-9667-8f9b7c86891a.png)
![image](https://user-images.githubusercontent.com/99375895/197463083-c6b19c37-8069-4afc-b5a4-28ec9d3184ed.png)
![image](https://user-images.githubusercontent.com/99375895/197463405-9e8864ef-bf92-4313-8cf1-cc50ed47a99f.png)
![image](https://user-images.githubusercontent.com/99375895/197463718-29b73bb0-8c6c-41a6-a7c2-aef3e6f17290.png)

**Comment by zewditu** [comment]
Verified by the tester .
