### ISSUE TITLE
Advanced data option is enabled before dataset is chosen 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2275]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/194908879-03470eea-d562-4677-8a5e-c17824ec47c8.png)

**Additional context**

**Comment by luisquintanilla** [comment]
I was unable to repro in build 16.14.0.2252005



![Image](https://user-images.githubusercontent.com/46974588/197067125-d6266372-1b9c-4e3e-b288-a5d250f0c4e5.png)

**Comment by zewditu** [comment]
Validated
