### ISSUE TITLE
Local image classfication is failed 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2278]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/195009670-1d61efe8-c6fa-423e-b50d-be8084f7cf38.png)

**Additional context**
This is from the latest main

**Comment by beccamc** [comment]
Is this a consistent repro? @v-Hailishi Have you seen this problem?

**Comment by v-Hailishi** [comment]
@beccamc Yes, this bug is repro in the latest main build: 16.13.10.2251201
![image](https://user-images.githubusercontent.com/99375895/195742699-f1be87c7-232f-401f-b770-43ba5ddea27e.png)

**Comment by luisquintanilla** [comment]
@beccamc I see you merged a PR for this. Are we okay to close?

**Comment by beccamc** [comment]
Do we care about getting things validated? This is sitting in the validate column.

**Comment by luisquintanilla** [comment]
Whoops! I missed that. Let's validate.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2252005
<img width="338" alt="image" src="https://user-images.githubusercontent.com/99375895/197092489-8e906840-88c4-4c21-8ae1-34ff5bee533a.png">
