### ISSUE TITLE
when i try to reference the ML model in my program it says it cannot be referenced . 

### ISSUE THREAD

**Issue by Hirad2hhk** [dotnet/machinelearning-modelbuilder#228]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Here is the error message:Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'MLAppML' could not be found (are you missing a using directive or an assembly reference?)	myMLApp	C:\Users\Hirad2HHK\source\repos\myMLApp\myMLApp\Program.cs	7	Active
And there is warning that says:
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The project 'myMLAppML.Model' cannot be referenced. The referenced project is targeted to a different framework family (.NETCoreApp)	myMLApp

**Comment by JakeRadMSFT** [comment]
@Hirad2hhk, 
Thanks for reporting this issue! This should be fixed in our upcoming release. We've added support for .NET Standard and .NET Framework projects.

Cheers,
Jake

**Comment by loicns** [comment]
Hello,
Please let us know if there are any workaround. I am stuck with the same issue.
Thanks,
Loic

**Comment by SignedYoursTruly** [comment]
Hello,
Is there a valid workaround or update put out yet? I am stuck with this issue as well.
Thank you,
YoursTruly
