### ISSUE TITLE
Value predication: The value for the best evaluation metric "RSquared" is wrong on the Evaluate page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2280]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2250701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The value for the best evaluation metric "RSquared" is wrong on the Evaluate page for Value predication scenario.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Value predication** scenario.
  5. On Data page, select the data source and choose **fare_amount** column as label.
  6. On the Train page, click "Start training" button to complete the training. (**The default Metric is "RSquared"**)
  7. On the Evaluate page, you will see that the value for the best evaluate metric "RSquared" is wrong.

**Expected behavior**
The value for the best evaluation metric "RSquared" should be correct. 

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/195014744-f47eb44e-e76c-42a2-8417-07eab4cd97c6.png)

**Comment by zewditu** [comment]
I am not able to reproduce it on the latest main

**Comment by v-Hailishi** [comment]
@zewditu Yes, the bug is not repro on the latest main build: 16.13.10.2251901
![image](https://user-images.githubusercontent.com/99375895/196838603-304ca5f1-5719-4975-9d53-22574d8af7cc.png)

**Comment by zewditu** [comment]
validated
