### ISSUE TITLE
Value predication: Word "rmse" should be capitalized to "RMSE" on the Train page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2281]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2250701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Word "rmse" should be capitalized to "RMSE" on the Train page for Value predication scenario.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Value predication** scenario.
  5. On Data page, select the data source and choose **fare_amount** column as label.
  6. On the Train page, click "Advanced training options..." link, then choose metric "RMSE" and save it.
  7. Click "Start training" button to complete the training, you will see that word "RMSE" is lowercase on the Train page.

**Expected behavior**
Word "rmse" should be capitalized to "RMSE" on the Train page.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/195017748-498770fd-0666-4307-bdb1-0be96d0523e0.png)

**Comment by v-Hailishi** [comment]
The bug is also repro on Forecasting scenario.
![image](https://user-images.githubusercontent.com/99375895/195055651-d8e30ce1-5622-437a-8ca9-afbcc8164657.png)

**Comment by LittleLittleCloud** [comment]
Verified on 16.4.0
