### ISSUE TITLE
Value predication: The generated Console App and Web Api projects run failed when using metric "RMSE" or "MSE".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2282]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2250701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The generated Console App and Web Api projects run failed when using metric "RMSE" or "MSE" for Value predication scenario.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Value predication** scenario.
  5. On Data page, select the data source and choose **fare_amount** column as label.
  6. On the Train page, click "Advanced training options..." link, then choose metric **"RMSE" or "MSE"** and save it.
  7. Click "Start training" button to complete the training.
  8. Click "Add to solution" button on the Consume page to generate Console App and Web Api projects.
  9. Run the generated Console App and Web Api projects.

**Expected behavior**
The generated Console App and Web Api projects should run successfully when using metric "RMSE" or "MSE".

**Screenshot**
RMSE:
![image](https://user-images.githubusercontent.com/99375895/195023262-7daf3c5d-42bd-491b-b2d4-0a48fcf68672.png)

MSE:
![image](https://user-images.githubusercontent.com/99375895/195023351-866e4b97-dfa1-4287-bfd1-47598c58fa64.png)

**Additional context:**
The generated Console App and Web Api projects can run successfully when using metric "**RSquared**".

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.13.10.2251301
![image](https://user-images.githubusercontent.com/99375895/195781737-d78b5740-a638-42b4-8905-e87d77e4aaa7.png)
![image](https://user-images.githubusercontent.com/99375895/195781530-71882040-2df2-4d88-83ba-5e85e00904a9.png)

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.13.10.2251301, the bug is only repro for metric "RMSE" when training SQL server data.

**Comment by luisquintanilla** [comment]
Related to #2293

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2252402
![image](https://user-images.githubusercontent.com/99375895/197745989-c964bc68-ece7-41c0-97ba-793d49984ea4.png)
