### ISSUE TITLE
Recommendation: There is no "Advanced training options..." functional on the "Train" page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2283]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2250701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
There is no "Advanced training options..." functional on the "Train" page for Recommendation scenario.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Recommendation** scenario. 
  5. On Data page, select the data source and choose "rating" as Label, "userId" as User, "movieId" as Item.
  6. On the Train page, you will see that there is no "Advanced training options..." functional.

**Expected behavior**
There is "Advanced training options..." functional on the "Train" page.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/195057940-11349ae3-655d-4716-9db0-ccdf48fc950f.png)

**Comment by zewditu** [comment]
The PR is out for it https://github.com/dotnet/machinelearning-tools/pull/1549

**Comment by beccamc** [comment]
Closing until the PR goes in.
