### ISSUE TITLE
The generated Console App project run failed when training the SQL data.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2288]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2251301 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The generated Console App project run failed when training the SQL data.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Value predication** scenario.
  5. On Data page, select the **SQL data** and choose **fare_amount** column as label.
  6. On the Train page, click "Start training" button to complete the training.
  8. Click "Add to solution" button on the Consume page to generate **Console App** project.
  9. Run the generated Console App project.

**Expected behavior**
The generated Console App project should run successfully when training the SQL data.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/195772134-3fcdca8b-219e-49dd-a2e4-8e9138a9ebb8.png)

**Additional context:**
The bug is repro on **Data classification, Value predication, Recommendation** scenarios.

**Comment by beccamc** [comment]
Good find! I forgot to add the SqlClientFactory reference.
