### ISSUE TITLE
Data classification: Symbol ":" is missing in the training result on the Train page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2289]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2251301 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Symbol ":" is missing in the training result on the Train page for Data classification scenario.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv 
https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt
https://github.com/dotnet/machinelearning-samples/raw/main/samples/modelbuilder/MulticlassClassification_RestaurantViolations/RestaurantScores.zip

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification** scenario.
  5. On Data page, select the data source and choose **Sentiment** column as label.
  6. On the Train page, click "Start training" button to complete the training. (**The default Metric is "Macro-Accuracy"**)
  7. You will see that symbol ":" is missing in the training result.

**Expected behavior**
Symbol ":" should be displayed normally. 

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/195807835-de1c5eb4-d705-4a8c-8876-7e84a56e88d1.png)
![image](https://user-images.githubusercontent.com/99375895/195807659-bf8b3a62-8ab7-41a8-a391-48cf0057e4fd.png)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2252402
![image](https://user-images.githubusercontent.com/99375895/197747989-9fd24645-1c31-4dac-8071-001046ae1a92.png)

**Comment by beccamc** [comment]
@v-Hailishi Can you start doing something new? When you validate a bug you've filed as fixed please close the bug too. Thanks!
