### ISSUE TITLE
Feature Engineering updates

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#229]
- [x] Disable Label and Feature dropdowns until dataset is selected
- [x] Disable Feature dropdown until Label is selected
- [x] Fix issue where feature column is added back to the data preview grid to the left of the label. This happens when the feature appears before the label in the original data set.
- [x] Default state:
  Column to Predict (Label): [Select column]
  Input Columns (Features): [Select column(s)]
- [x] Remove Label from Feature dropdown list
- [x] Remove "(Feature)" text from Data Preview
- [x] Data Preview summary examples (note, it's dynamic; Feature vs Features based on =1, >1):

  10 of 100,001 rows. 7 of 7 columns. [This is default when dataset is loaded before Label / Feature selection]
  10 of 100,001 rows. 7 of 7 columns (1 Label, 6 Features). [This is default after Label is selected)
  10 of 100,001 rows. 2 of 7 columns (1 Label, 1 Feature).
  10 of 100,001 rows. 4 of 7 columns (1 Label, 3 Features).

- [x] Update Evaluate screen; ex:

  ML Task: binary-classification
  Dataset: dataset.csv
  Column to Predict (Label): Column0
  **Input Columns (Features): Column1, Column2, Column3, Column4, Column5, + 10 more. Show more**
  Best Model: AveragedPerceptronBinary
  Best Model Accuracy: 93.75%
  Training Time: 10.44 seconds
  Models Explored (Total): 16
- From mock-up: 
![image](https://user-images.githubusercontent.com/10437687/64568933-ef587500-d310-11e9-90d9-84ee66c56741.png)

**Comment by rustd** [comment]
Default state in data screen is not fixed. It should be 


Column to Predict (Label): [Select column]
**Input Columns (Features): [Select column(s)]**
