### ISSUE TITLE
nothing happens when I choose sql server and then click browse

### ISSUE THREAD

**Issue by jlshattuck** [dotnet/machinelearning-modelbuilder#2290]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 1.71
 - Visual Studio Version (if applicable): Version 17.3.6
:

**To Reproduce**
1. Go to model builder
2. Click Data Classification
3. select local cpu
4. click SQL Server
5. Click browse

**Expected behavior**
show me a sql connection dialog

**Comment by beccamc** [comment]
Sorry you ran into this! Can you please update Model Builder to version 16.13.10? https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022

**Comment by beccamc** [comment]
Also can you make sure you have SQL tools installed for your VS build...

![image](https://user-images.githubusercontent.com/9122518/196807469-743f6ae2-bdb7-4d91-a1b9-0d75d984562a.png)

**Comment by beccamc** [comment]
Any update with the above?

**Comment by beccamc** [comment]
Please try the above! If it doesn't work ping me.
