### ISSUE TITLE
Recommendation: Evaluate Metric name "RSquared" or "RMSE" or "MSE" is missing on the Train and Evaluate pages.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2291]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2251401 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Evaluate Metric name "RSquared" or "RMSE" or "MSE" is missing on the Train and Evaluate pages for Recommendation scenario.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Recommendation** scenario.
  5. On Data page, select the data source and choose **Rating** column as label.
  6. On the Train page, choose any metric (**"RSquared" or "RMSE" or "MSE"**), then click "Start training" button to complete the training.
  7. You will see that Evaluate Metric name "RSquared" or "RMSE" or "MSE" is missing.

**Expected behavior**
Evaluate Metric name "RSquared" or "RMSE" or "MSE" should be displayed normally. 

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/196108659-b8ec83f3-7160-4c09-b65c-c5f97ddb4b6b.png)

**Comment by luisquintanilla** [comment]
Recommendation scenario related to #2292 and #2293

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2252402
![image](https://user-images.githubusercontent.com/99375895/197749340-cb801a75-fce6-4be2-9916-62abb9a21054.png)
