### ISSUE TITLE
Recommendation: The predicted rating is garbled on the Evaluate page when using metric "RMSE" or "MSE".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2292]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2251401 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The predicted rating is garbled on the Evaluate page for Recommendation scenario.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv
https://testpass.blob.core.windows.net/test-pass-data/iris.mdf

**To Reproduce**

  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Recommendation** scenario.
  5. On Data page, select the data source 
  6. On the Train page, choose metric "RMSE" or "MSE", then completed the training. 
  7. On the Evaluate page, click "Predict" button and check the evaluate results.

**Expected behavior**
There is no garbled on the Evaluate page.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/196125197-9f735ce3-1990-461c-9476-3dd8acf137b1.png)

**Additional context:**
The bug is not repro when using metric "RSquared".

**Comment by luisquintanilla** [comment]
Looks like this is related to #2293. The recommendation scenario with these metrics seems to be the issue.

**Comment by zewditu** [comment]
I think the value we got for  RMSE and MSE  is 0.0000, I think that might create undefined prediction.
@v-Hailishi  are you able to try for non-zero values
@LittleLittleCloud  any thought on this ?

**Comment by zewditu** [comment]
@LittleLittleCloud  does this caused by this ml.net issue https://github.com/dotnet/machinelearning/issues/6361

**Comment by zewditu** [comment]
This seems triggered by this Ml.Net issue https://github.com/dotnet/machinelearning/issues/6361
