### ISSUE TITLE
Recommendation: Generated Web API is running failed with error 500 when using metric "RMSE" or "MSE".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2293]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2251401 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Generated Web API is running failed with error 500 when using metric "RMSE" or "MSE" for Recommendation scenario.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv
https://testpass.blob.core.windows.net/test-pass-data/iris.mdf

**To Reproduce**

  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Recommendation** scenario.
  5. On Data page, select the data source 
  6. On the Train page, choose metric "RMSE" or "MSE", then completed the training. 
  7. Click "Add to solution" to add the Web Api project to your current solution.
  8. Run the application.
  9. Open PowerShell and enter the following code where PORT is the port your application is listening on.
     **$body = @{
     UserId = 1
     MovieId = 3
    }
    Invoke-RestMethod "[https://localhost:PORT/predict"-Method](https://localhost:PORT/predict%22-Method) Post -Body ($body | ConvertTo-Json) -ContentType "application/json"**

**Expected behavior**
Run successful and display the expected output.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/196126165-4140e422-c76a-4370-9a3e-3cfdb679186c.png)

**Additional context:**
The bug is not repro when using metric "RSquared".

**Comment by luisquintanilla** [comment]
Interesting...I'm not sure how the metric has an effect on the deployment. The HTTP 500 error to me sounds like an issue with codegen rather than the model. @v-Hailishi can you please confirm whether this is something you experience when choosing the Console App template.

**Comment by v-Hailishi** [comment]
@luisquintanilla Tried on the latest main build 16.13.10.2251901, I can still reproduce this bug.
It only repro when using metric "RMSE" or "MSE", not repro when using metric "RSquared".
The generated console app project can run successfully, but the predicted result contains garbage. you can get details from bug https://github.com/dotnet/machinelearning-modelbuilder/issues/2292

**Comment by luisquintanilla** [comment]
Thanks for confirming @v-Hailishi
