### ISSUE TITLE
Data classification: Training failed with model builder error "Index was outside the bounds of the array".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2294]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.22513701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training failed with model builder error "Index was outside the bounds of the array" when choosing "SentimentText" as Label and using metric "Log-Loss Reduction".

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification** scenario.
  5. On Data page, select the data source and choose **SentimentText** column as label.
  6. On the Train page, choose metric "**Log-Loss Reduction**", then click "Start training" button.
  7. You will see that training failed with model builder error "Index was outside the bounds of the array".

**Expected behavior**
Training successful.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/196319564-a481d6c9-d42e-4978-af4b-0bafefc31b5d.png)

**Additional context:**
After the error occurs, .mbconfig file cannot be saved successfully with error "Value cannot be null".
![#2294](https://user-images.githubusercontent.com/99375895/196320948-9170f042-4442-4cb4-9edb-8cb5ce2b8c9d.gif)

**Comment by zewditu** [comment]
This issue happens when The logloss- reduction is infinity.

@LittleLittleCloud   how we are dealing with infinity values metrics?

**Comment by luisquintanilla** [comment]
May be related to dotnet/machinelearning#6361

**Comment by LittleLittleCloud** [comment]
Model Builder still uses mlnet 2.0 so the fix is not introduced yet

**Comment by v-Hailishi** [comment]
The bug is still repro on the latest main build 16.14.2.2306101
![Image](https://user-images.githubusercontent.com/99375895/212035249-f6c93d18-5ea5-45a5-a6d3-bc5cc23e41f6.png)

**Comment by LittleLittleCloud** [comment]
The fix should checked in now

**Comment by v-Hailishi** [comment]
@LittleLittleCloud The training is still failed on the latest main build 16.14.3.2307701.
![#2294](https://user-images.githubusercontent.com/99375895/215716337-41a79eb8-c5b8-415e-8ea1-5676fb811c6c.gif)

**Comment by luisquintanilla** [comment]
This error was fixed. New issue created to track throwing a better error when no suitable model found. #2500
