### ISSUE TITLE
Value predication: Training failed with model builder error after changing the feature column 's Data type from "String" to "Single".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2295]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2251801 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training failed with model builder error after changing the feature column 's Data type from "String" to "Single".

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/iris.mdf

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Value predication** scenario.
  5. On Data page, select the data source and choose **fare_amount** column as label.
  6. Change **"rate_code" or "passenger_count" or "trip_distance"** column's Data type from "String" to "Single".
  7. On the Train page, you will see that training failed with model builder error "Splitter/consolidator worker encountered exception while consuming source data".

**Expected behavior**
Training successful.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/203674407-d04af336-c434-4f49-972e-23d7db4c7bfc.png)

**Additional context:**

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2253101
![1](https://user-images.githubusercontent.com/99375895/199204490-195bd01c-9d30-42ef-958e-f86082d36d2a.png)
![image](https://user-images.githubusercontent.com/99375895/199204573-cd596c42-ebdd-449e-a382-cdd872318179.png)

**Comment by v-Hailishi** [comment]
The bug is repro again on the latest main build: 16.14.0.2255803
![image](https://user-images.githubusercontent.com/99375895/201048165-a9fdf7b5-62e1-425b-8289-b2ed9de97331.png)

**Comment by luisquintanilla** [comment]
@v-Hailishi do we have a consistent repro? Can we please validate whether it's been fixed in the latest build. Thanks!

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.0.2261401
![image](https://user-images.githubusercontent.com/99375895/207803220-569efbb2-7661-4cbb-92d4-a10f5ef18811.png)
