### ISSUE TITLE
Object detection & Image classification-Azure: Training failed.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2297]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.13.10.2251901 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Azure scenarios training failed.

**Data Source**
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#create-a-new-vott-project
https://testpass.blob.core.windows.net/test-pass-data/weather.zip

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Object detection or Image classification-Azure** scenario.
  5. On Data page, select the data source.
  6. You will see that training failed with model builder error.

**Expected behavior**
Training successful.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/196920964-5ef1b8d0-1958-48f6-b343-96f6c5e2108a.png)

**Additional context:**
ImageClassification: https://ml.azure.com/experiments/id/891078f2-635b-4e43-849b-f5129264b1fa/runs/lrglhhyispyybem?wsid=/subscriptions/83635e26-687a-4333-a2a0-33e3cd1f573a/resourceGroups/FullTestPass/providers/Microsoft.MachineLearningServices/workspaces/FullTestPass&tid=72f988bf-86f1-41af-91ab-2d7cd011db47
Object detection: https://ml.azure.com/experiments/id/8ad34cd8-0b2e-445b-a3a7-5760c3306ece/runs/vdzvrhcxhstvjhk?wsid=/subscriptions/83635e26-687a-4333-a2a0-33e3cd1f573a/resourceGroups/FullTestPass/providers/Microsoft.MachineLearningServices/workspaces/FullTestPass&tid=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2252005
![image](https://user-images.githubusercontent.com/99375895/197127811-091dc57b-7aed-4930-9c1c-ef25b773eb7b.png)

**Comment by beccamc** [comment]
Is this still happening? In the bug bash yesterday both worked for me?

**Comment by v-Hailishi** [comment]
@beccamc Yes, the bug has been fixed now.
