### ISSUE TITLE
RMSE is negative

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2298]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  latest main
 - Visual Studio Version
<img width="449" alt="image" src="https://user-images.githubusercontent.com/16876986/197066659-60021aae-ab91-4877-98b5-2f0e8cf233d1.png">

**Comment by luisquintanilla** [comment]
Issue is done. Closing
