### ISSUE TITLE
Clean Up UI

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#23]
- [ ] Checkbox should appear training finishes in the progress section
- [ ] Add summary of total rows and cols
- [ ] Training progess default text "Start training to see progress and results" should go away once you start training
- [ ] Text for default states are missing (default value of inputs and sections)

**Comment by JakeRadMSFT** [comment]
@rustd, Can you review these?

**Comment by rustd** [comment]
Made a pass with the latest build and added some more. Major work is spacing/ checkbox after training and default text should match figma.

**Comment by rustd** [comment]
@JakeRadMSFT we re-triaged the issues. Can you please add the costing for these?
