### ISSUE TITLE
LogLoss is labeled as MacroAcuracy in data classification 

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2300]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  16.4.0
 - Visual Studio Version

<img width="877" alt="image" src="https://user-images.githubusercontent.com/16876986/197067354-5dc47063-9361-4911-ad58-e650b8d4fb36.png">

**Comment by zewditu** [comment]
@luisquintanilla  this is based on this work item detail https://github.com/dotnet/machinelearning-modelbuilder/issues/2191, are you able to comment what is missed here?

**Comment by zewditu** [comment]
Duplicate issue  https://github.com/dotnet/machinelearning-modelbuilder/issues/2273
