### ISSUE TITLE
Save is not enabled after I make a change in trianers in advanced option

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2301]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.4.0
 - Visual Studio Version

## Step to reproduce
- pick data classification
- go to advanced trainer option
- unselect some trianers
- saved button is not enabled.
<img width="718" alt="image" src="https://user-images.githubusercontent.com/16876986/197067678-3ef915f6-894c-40dc-baa0-afbe9d9c38d1.png">

**Comment by JakeRadMSFT** [comment]
#2299
