### ISSUE TITLE
Start training button should be disabled during cancelling training

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2302]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  16.4.0
 - Visual Studio Version

After I click on Cancelling, the Training button is still enabled which means I can kick off another training before the current one get cancelled

<img width="311" alt="image" src="https://user-images.githubusercontent.com/16876986/197070091-067a54af-6730-4e39-81f4-4ec1e40020a8.png">

**Comment by luisquintanilla** [comment]
Validated. Okay to close.
