### ISSUE TITLE
Azure Storage Account  not shown

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2304]
1. Image classification scenario
2. Storage account isn't shown in the preview info. This was both for a new compute and existing compute. 

![image](https://user-images.githubusercontent.com/9122518/197070303-864bb011-a210-413f-8603-5374f9fddc42.png)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2252604
![image](https://user-images.githubusercontent.com/99375895/198227045-19471e7a-c3fe-43af-963d-686e62982be7.png)
