### ISSUE TITLE
SQL Loading Tables Blocks UI Thread

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#2305]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.14.0.2252005
 - Visual Studio Version: VS 2022

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**
1. Select a SQL Data Source from file (I think from server would work too)
2. See error

**Screenshots**
<img width="953" alt="image" src="https://user-images.githubusercontent.com/31937616/197071109-6c3b9360-69a1-4ea1-aa5c-3c5fdce7d935.png">

**Additional context**

**Comment by beccamc** [comment]
@JakeRadMSFT Can you verify this? I wasn't getting the Visual Studio banner on my machine.
