### ISSUE TITLE
When we switch from multi to binary data classification and vice versa  there is no metric selected by default

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2307]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**
1. Go to ' scenario page '
2.  select Data classification
3.  Choose multi classification data
4. Move to train page and click on advanced training option  change some settings and save
5. back to data page and choose to binary type data 
6. Go to training page advanced training option dialog 

**Expected behavior**
![image](https://user-images.githubusercontent.com/36615490/197074740-5e896593-4a38-4b0c-8980-adc971410829.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/197074663-67a7b2da-0b9f-478f-a591-b315ec373c93.png)

**Additional context**

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2255702
![image](https://user-images.githubusercontent.com/99375895/200494247-4e696d97-b197-414e-bbd4-9f5374d26201.png)
![image](https://user-images.githubusercontent.com/99375895/200494285-e247cf25-fcc6-4539-a6dd-f889997fc65c.png)
