### ISSUE TITLE
Replace Bitmap with MLImage for image classification and object detection

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2308]
ML.Net removes dependency from Bitmap image and replace it with MLImage in [this PR](https://github.com/dotnet/machinelearning/pull/6363/files), which breaks the object detection and image classification in model builder. The following change needs to be made
- [x] use MLImage as input for image-related training
- [x] update code generator to generate correct model input class
- [x] (maybe) increase mbconfig version, as the old model won't be able to load in model builder because of this breaking change

And other than that, we also need to wait the next mlnet release so that removing bitmap pr can be available for the public

**Comment by LittleLittleCloud** [comment]
@luisquintanilla for notification.

**Comment by luisquintanilla** [comment]
@LittleLittleCloud we need to be on the latest release because of the updates being made to the Text Classification paths right? So this would for sure break the local image scenarios.

**Comment by LittleLittleCloud** [comment]
@luisquintanilla yep

**Comment by luisquintanilla** [comment]
@LittleLittleCloud to update issue.
