### ISSUE TITLE
Forecasting: "Time to train" and "Horizon" functional are deleted on the Train page, is it expected?

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2310]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2252103 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
"Time to train" and "Horizon" functional are deleted on the Train page.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Forecasting** scenario.
  5. On Data page, select the data source and choose **sinx** column as label.
  6. On the Train page, you will see that "Time to train" and "Horizon" functional are deleted.

**Expected behavior**
I want to know whether is this expected?

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/197500846-442e6c76-e3ab-4318-9d6d-be4de6e0f35a.png)

**Comment by zewditu** [comment]
@LittleLittleCloud confirmed us it is a bug.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2253101
![image](https://user-images.githubusercontent.com/99375895/199149746-9ebdefd0-93ac-486c-adde-51b21fecce6b.png)
