### ISSUE TITLE
Data classification: First letter should be capitalized on the Train and Evaluate pages when using metric "Log-Loss Reduction".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2311]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2252402 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
First letter should be capitalized on the Train and Evaluate pages.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification** scenario.
  5. On Data page, select the data source and choose **Sentiment** column as label.
  6. On the Train page, click "Advanced training options..." link, then choose metric "**Log-Loss Reduction**" and save it.
  7. Click "Start training" button to complete the training.

**Expected behavior**
First letter should be capitalized on the Train and Evaluate pages.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/197729247-840b975c-d724-4a71-8299-b9454ba07202.png)

**Comment by v-Hailishi** [comment]
The bug is also repro on metric "**Accuracy**" for Binary classification scenario.
![image](https://user-images.githubusercontent.com/99375895/197730239-1ba11b77-f7fe-4f25-88af-52b597b758be.png)

**Comment by v-Hailishi** [comment]
The bug is still repro on the latest main build: 16.14.0.2255401
![image](https://user-images.githubusercontent.com/99375895/200238390-bc71e1c0-754d-4517-a96e-8066ccb62f4c.png)

**Comment by luisquintanilla** [comment]
Good catch @v-Hailishi. 

@JakeRadMSFT will reach out.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.3.2311302.
![image](https://user-images.githubusercontent.com/99375895/218654695-8480a24c-361f-4d6c-a6d2-51d9c8c08c34.png)
