### ISSUE TITLE
Forecasting: Some trainer numbers are missing and non-continuously on the Output window.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2313]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2252402 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Some trainer numbers are missing and non-continuously on the Output window.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Forecasting** scenario.
  5. On Data page, select the data source and choose "**sinx**" column as label.
  6. On the Train page, click "Advanced training options..." link, then choose metric and save it.
  7. Click "Start training" button to complete the training and then check the output window.

**Expected behavior**
Trainer numbers should be continuously on the Output window.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/197733563-567ae720-f328-4c5d-9d64-22866f0fd501.png)

**Comment by zewditu** [comment]
I think the issue here is it should display only the top 5, the index is the index of selected trainers

**Comment by v-Hailishi** [comment]
The bug is still repro on the latest main build: 16.14.0.2255401
![image](https://user-images.githubusercontent.com/99375895/200242806-40ddde1f-8182-4353-a2da-5c1b7c34472a.png)

**Comment by luisquintanilla** [comment]
Thanks for reporting this issue @v-Hailishi. The output window is meant to be a quick spot check. As long as the UI shows the correct information, we're okay deprioritizing this. Closing for now and will wait for additional feedback.
