### ISSUE TITLE
Forecasting: The value for metric "MAPE" should be non-negative.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2314]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2252402 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The value for metric "MAPE" should be non-negative.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Forecasting** scenario.
  5. On Data page, select the data source and choose "**sinx**" column as label.
  6. On the Train page, click "Advanced training options..." link, then choose metric "MAPE" and save it.
  7. Click "Start training" button to complete the training.

**Expected behavior**
The value for metric "MAPE" should be non-negative.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/197734945-0f1fdaa5-6e86-45e6-96c3-a47270600ed8.png)

**Comment by zewditu** [comment]
Technically this is not MAPE rather RMSE, however is that allowed to have negative values to RMSE?
related issue https://github.com/dotnet/machinelearning-modelbuilder/issues/2315

**Comment by zewditu** [comment]
Not  bale t reproduce on the latest main

**Comment by zewditu** [comment]
We discussed offline we @LittleLittleCloud I confirmed that the results are MAPE.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2255401
![image](https://user-images.githubusercontent.com/99375895/200253591-5153dc06-bc77-4a0f-ba06-b4cc7ac95b70.png)

**Comment by v-Hailishi** [comment]
Verified on the latest main build: 16.14.0.2255702, the bug is still repro for File and SQL Password data, not repro for Microsoft SQL Server Database File data.
![image](https://user-images.githubusercontent.com/99375895/200508171-050503f1-b408-4dda-b53a-6bb07e623f9a.png)
![image](https://user-images.githubusercontent.com/99375895/200508266-efd6dcf8-60fd-416e-8e7c-832eff617668.png)
![image](https://user-images.githubusercontent.com/99375895/200508409-188549a3-ee76-4df2-a619-016c5755e0c0.png)

**Comment by luisquintanilla** [comment]
@zewditu @LittleLittleCloud what are the next steps for this one?

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.2.2306903.
![image](https://user-images.githubusercontent.com/99375895/213652709-ac8b040d-58e5-407c-bbf6-8cf28f1516d4.png)
![image](https://user-images.githubusercontent.com/99375895/213653515-d40e93a9-84a4-43c6-b9da-a16449da6d8c.png)
