### ISSUE TITLE
Data classification: "Experiment Results" was displayed on the wrong place in the output window when choosing "SentimentText" column as Label.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2316]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2252502 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
"Experiment Results" was displayed on the wrong place in the output window when choosing "SentimentText" column as Label.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification** scenario.
  5. On Data page, select the data source and choose **SentimentText** column as label.
  6. On the Train page, click "Start training" button to complete the training.
  7. You will see that "Experiment Results" was displayed on the wrong place in the output window.

**Expected behavior**
"Experiment Results" should be displayed on the right place in the output window.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/197921058-1f9ec303-2e2c-4879-84ce-68b0ac5f986f.png)

**Additional context:**
The bug is not repro when choosing "**Sentiment**" column as Label.
![image](https://user-images.githubusercontent.com/99375895/197921182-8d655b57-b59d-40b1-a74d-b6cab614be98.png)

**Comment by LittleLittleCloud** [comment]
The cause is because the experiment result summary comes from service hub process and code generating log comes from decent process. So we can't guarantee the appear order for those output messages 

Unfortunately I cannot figure out any easy fix for this issue. And since the log from output window is mostly for tracing info purpose so its also fine to me to just have the output as is for now. 

In the long run, we can move the experiment result summary to model builder ui 

@luisquintanilla @JakeRadMSFT for notification

**Comment by luisquintanilla** [comment]
@LittleLittleCloud to confirm, this issue is only with the output window. Is that correct?

**Comment by zewditu** [comment]
> @LittleLittleCloud to confirm, this issue is only with the output window. Is that correct?

@luisquintanilla , yes, it is just a matter of order to display code generated log and train summary in output window only

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.14.0.2257101, when the training status showing completed, the output windows is still in progress.
![#2389](https://user-images.githubusercontent.com/99375895/203458831-7b296594-7fbb-4585-913a-d5b875ab817f.gif)

**Comment by zewditu** [comment]
@v-Hailishi  I think this is a separate issue, this thread is for the order  outputs.
are you able to open another issue for this

**Comment by luisquintanilla** [comment]
@v-Hailishi thanks for reporting this issue. A few questions:

- Is this a consistent repro?
- Does the UI in Model Builder show the correct information?

**Comment by v-Hailishi** [comment]
@luisquintanilla Verified on the latest main build 16.14.0.2261401, just like bug https://github.com/dotnet/machinelearning-modelbuilder/issues/2407, When the training status showing completed, the output windows is still in progress.
of course, the UI in Model Builder show the correct information.

**Comment by zewditu** [comment]
> The cause is because the experiment result summary comes from service hub process and code generating log comes from decent process. So we can't guarantee the appear order for those output messages
> 
> Unfortunately I cannot figure out any easy fix for this issue. And since the log from output window is mostly for tracing info purpose so its also fine to me to just have the output as is for now.
> 
> In the long run, we can move the experiment result summary to model builder ui
> 
> @luisquintanilla @JakeRadMSFT for notification

For this reason, the UI show the correct information, the same to https://github.com/dotnet/machinelearning-modelbuilder/issues/2407 are we able to close this issue?
@luisquintanilla ?

**Comment by luisquintanilla** [comment]
Maybe. If this only affects Model Builder I think we're okay to close because our "source of truth" is what's displayed in the UI. However, what impact, if any, does this have on the CLI?

**Comment by zewditu** [comment]
@LittleLittleCloud  do you know about the impact on CLI?

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.3.2311302.
![image](https://user-images.githubusercontent.com/99375895/218671333-6c85b6aa-5ab1-4d9a-a11d-a6874193ec8e.png)

Besides, also not repro in the CLI output.
<img width="705" alt="image" src="https://user-images.githubusercontent.com/99375895/218672845-eef9567d-bc82-4238-a466-acbc0e9d84d8.png">
