### ISSUE TITLE
Text-classification score should be calibrated and normalized to 1

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2317]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luisquintanilla** [comment]
@zewditu is this for training or evaluation / code-gen?

**Comment by zewditu** [comment]
Evaluation
