### ISSUE TITLE
Text/Image/Data classification descriptions are confusing 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2318]
I'm a little confused by the various titles, images, and descriptions of classification. 

My main issue is...
- Graphic used for Image and Text match (and the scenarios are next to each other)
- Description for Image and Data match more closely. 

Maybe this would be fixed by the new graphic we're supposed to be getting? I just know I would be confused as a customer. 

![image](https://user-images.githubusercontent.com/9122518/198144165-fac709d5-6f83-4da3-befa-110b0efd411f.png)

**Comment by beccamc** [comment]
We need to add the new scenario to the doc link here! I would say that's a blocking issue.

**Comment by luisquintanilla** [comment]
@beccamc can you post the link we need to update docs for.

**Comment by beccamc** [comment]
Yes! https://aka.ms/vsmbscenario

**Comment by luisquintanilla** [comment]
@beccamc here's the PR I'm using to track the doc work for these scenarios. 

https://github.com/dotnet/docs/pull/32065

**Comment by luisquintanilla** [comment]
cc @zewditu

**Comment by luisquintanilla** [comment]
Action Items

- [ ] Update data classification description to: "Classify tabular data (numeric, categorical, text) into 2+ categories. e.g. categorize flowers based on petal size and width measurements"
- [ ] Update Text classification description to: "Assign a label or category to raw text data. e.g. sentiment analysis on customer review."
- [ ] Docs: Add information about models in [link](https://learn.microsoft.com/dotnet/machine-learning/automate-training-with-model-builder#which-machine-learning-scenario-is-right-for-me)
- [ ] Update Text classification title from "Text Classification" to "Text classification"
- [ ] Move value prediction to 4th position (after Data, Image, Text classification scenarios).

**Comment by LittleLittleCloud** [comment]
Would it be better to change `Language` to `Nature Language Processing`

**Comment by luisquintanilla** [comment]
> Would it be better to change `Language` to `Nature Language Processing`

Maybe. I could go with either. That's what most places refer to it as. I went with language to keep it short.

**Comment by beccamc** [comment]
I like Natural Language Processing but I have no data backed explanation for why.

**Comment by luisquintanilla** [comment]
> I like Natural Language Processing but I have no data backed explanation for why.

I think people are familiar with this concept and there's several examples where that's the term used. So if anything I have no real reason behind "Language" other than it's shorter.

**Azure ML**

![image](https://user-images.githubusercontent.com/46974588/199339065-d3e08eb2-e47c-441a-b054-ba8356d355ed.png)


**HuggingFace**

![image](https://user-images.githubusercontent.com/46974588/199339201-f591c49b-157a-4738-8a70-cbb305342492.png)
