### ISSUE TITLE
Image Classification GPU training not work for VS2022 after 17.3.0

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2319]
Verify that it works on 17.2.7. But not for VS after 17.3.0. It's probably because VS servicehub hanging cin/cout

One work-around is to disable tf logging by setting TF_CPP_MIN_LOG_LEVEL to 3 in environment.

**Comment by beccamc** [comment]
Good close per Luis.

**Comment by LittleLittleCloud** [comment]
Should be fixed for VS after v17.4.3
