### ISSUE TITLE
All scenarios: Message dialog "Version string portion was too short or too long." would be pop-up when training again.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2320]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2252604 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Message dialog "Version string portion was too short or too long." would be pop-up when training again.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification** scenario.
  5. On Data page, select the data source and choose **Sentiment** column as label.
  6. On the Train page, click "Start training" button to complete the training. (**In the first time, there is not any message dialog pop-up**.)
  7. Click "**Train again**" button. then you will see that message dialog "Version string portion was too short or too long." pop-up.

**Expected behavior**
There is no message dialog pop-up when training again.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/198236775-b5e8da67-c0fe-4d45-911f-599aa0630d8c.png)

**Additional context:**
The following is the first-time training screenshot.
![image](https://user-images.githubusercontent.com/99375895/198237083-1e1d6605-748c-43d2-b36b-89ca14653f06.png)

**Comment by zewditu** [comment]
This is because we used a preview version of ml.net "2.0.0-preview.22313.1"  because our touch sharp needs this version , I think this will be gone after Nov 6 when we have a release version of ml net

**Comment by zewditu** [comment]
@luisquintanilla  is the.net conf. before the next release of ml net? if so we have to turn off this error message otherwise we are fine.

**Comment by luisquintanilla** [comment]
@zewditu we release at the same time.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2255702
![image](https://user-images.githubusercontent.com/99375895/200494934-ba34e9b8-011b-460b-ba43-8bff697dcab3.png)
