### ISSUE TITLE
Image classification-Azure&Object detection: The generated Console App and Web Api projects run failed.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2323]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2252604 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The generated Console App and Web Api projects are run failed.

**TestMatrix**
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#create-a-new-vott-project

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Object detection" or "Image classification-Azure"** scenario and data source to complete the training.
  5. Click "Add to solution" button on the Consume page to generate Console App and Web Api projects.
  6. Run the generated Console App and Web Api projects.
  
**Expected behavior**
The generated Console App and Web Api projects should run successfully.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/198252266-dc6bb0a5-d36a-401a-aa79-0ac549025957.png)

**Comment by LittleLittleCloud** [comment]
This is expected as `MLImage` is still in preview and hasn't been released yet. Once's the latest ml.net with MLImage get released, this issue would go away

**Comment by LittleLittleCloud** [comment]
tracking in #2342
