### ISSUE TITLE
GPU docs for Text Classification

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2326]
What if my GPU isn't compatible? Do we give any guidance? (I assume the answer is no)

![image](https://user-images.githubusercontent.com/9122518/198394438-ad3960a9-2e60-45ee-a706-a7872c826194.png)

Proposed change: This doc (linked to from the environment page) should have information GPU requirements for text classification. 
https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder

**Comment by beccamc** [comment]
@JakeRadMSFT and @LittleLittleCloud What is actually required for text GPU training? 

Do I need both the [Prereq](https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder#prerequisites) and [Dependencies](https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder#install-dependencies) listed in the docs?

**Comment by LittleLittleCloud** [comment]
@beccamc No based on my understand, as long as you have a cuda-supported GPU you can run text GPU training

**Comment by luisquintanilla** [comment]
Action Items: 

- [ ] Upgrade image classification to H2
- [ ] Move install dependencies under image classification section
- [ ] Move NVIDIA account under image classification section

**Comment by luisquintanilla** [comment]
PR Merged. Moving to done
