### ISSUE TITLE
Allow users to stop training (instead of cancelling) if there's any model found

### ISSUE THREAD

**Issue by tbombach** [dotnet/machinelearning-modelbuilder#233]
**Is your feature request related to a problem? Please describe.**
Currently, clicking the cancel button will prevent MB from generating a model based on the training so far. This is fine if there isn't a model found yet, but if AutoML has found a model the user may want to use that training result and continue to code generation.

**Describe the solution you'd like**
- "Cancel training" should change to "Stop training"
- When "Stop training" is pressed, AutoMLEngine should cancel the training task and use the best iteration so far to generate the model. The status should change to "Finalizing model" (since AutoML needs to save the model to disk)

**Comment by beccamc** [comment]
@LittleLittleCloud Is this possible with AutoML right now? I know we pass the cancellation token on to AutoML. If we cancel, is there still some way to get results back from AutoML?

**Comment by LittleLittleCloud** [comment]
@briacht 
We shall be able to implement "Cancel training"|"Stop training"|"Resume training" under the current AutoML/TrainingConfig architecure, any ideas on how these features should look like?

**Comment by LittleLittleCloud** [comment]
> @briacht
> We shall be able to implement "Cancel training"|"Suspend training"|"Resume training" under the current AutoML/TrainingConfig architecure, any ideas on how these features should look like?

**Comment by vzhuqin** [comment]
@LittleLittleCloud  @beccamc could you help to answer below question?

Validate this issue on https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
 - Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Clicked "Stop training" after noticed the training results, see:
1. the message changed to "Cancelling";
2. changed to "x seconds remaining...";
3. after ran the time, the message changed to "Finalizing model...";
4. changed to "Training complete";
**The question is: the message doesn't change to "Finalizing model" directly after click "Stop training", is that expected?**
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/2aeaba72-fd9c-4f72-a05b-b6dbd7e7eb7f)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/21a20d3d-6286-481c-84c4-083b0a4e6d04)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4b1d47a4-ce5a-4301-8052-a7df2ba78dc6)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/692b8510-2311-4b55-ad5f-a5edc6f7a7b3)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/d1fe2376-73fe-4ac8-860c-3d0787a18e49)

**Comment by beccamc** [comment]
@LittleLittleCloud Can you help here?

**Comment by vzhuqin** [comment]
Verified this issue on main branch:
If have training results, then click click "Stop training":
The status changes to "Cancelling...">"Finalizing model...">"Training complete".  @LittleLittleCloud could you help to confirm whether this is the expected experience?
![233.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/ee1c7b64-bb38-4138-9f0d-3c22d81540b7)

**Comment by beccamc** [comment]
Looking at this more closely, yes I believe this is the correct experience. After training we do a few things to finish training, like generate the code files. That should be what's happening while "Finalizing model" is showing. This is fixed as expected. Thanks Qin!

**Comment by vzhuqin** [comment]
Thanks confirmation @beccamc
