### ISSUE TITLE
[Deep Learning] Add Sentence Similarity Scenario to Model Builder

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2330]
### Frontend

- [x] #2336
- [x] #2337

### Backend

- [x] #2338

## Summary

ML.NET now supports Sentence Similarity powered by TorchSharp. Add Sentence Similarity as one of the supported language scenarios in Model Builder.

- Supported Training Environments
  - Local CPU
  - Local GPU
- Supported Data Formats
  - File
  - SQL 

### Scenario 

- Users should be able to select Sentence Similiary as one of the supported scenarios.

### Environment

- Users should be able to train locally on CPU
- Users should be able to train locally on GPU

### Data

- Users should be able to use a delimited file for training
- Users should be able to use a SQL table for training
- Users should be able to select a single column containing raw text as their feature / text column (the text they want to compare).
- Users should be able to select a single column containing raw text as their feature / text column (the text they want to compare against).
- Users should be able to select a single column containing the label. The label is a number which indicates the similarity between both sentence features.

Data for this scenario is expected to be tabular. This includes the already supported File and SQL formats like other scenarios. Like other scenarios, users should be able to select a single column as the label column. However, one distinction for this scenario is, users can only choose two columns as the feature. These feature columns should be raw text. 

### Scenario 

- Add a new tile for Sentence Similarity as one of the supported scenarios.
  - Tile details:
    - Title: Sentence similarity 
    - Description: Compare how similar two sentences are, e.g. display most relevant results from a search query.
    - Icon: TBD
    - Environment Tag: Local, Local GPU
    - Order: After Text classification in Language scenario category.

### Environment

- Local CPU
- Local GPU

### Data

- Data Source Type:
  - File
  - SQL
- Column to Predict (Dropdown)
- 2 Text Column (Dropdown)

### Train

Same as other scenarios

### Evaluate

Same as other scenarios

### Consume

Same as other scenarios

## Dependencies / Non-Goals

For the initial implementation, since the Sentence Similarity API is not currently implemented in the ML.NET CLI, it's not a priority to enable training on Azure as an environment.

**Comment by zewditu** [comment]
Check lists https://github.com/dotnet/machinelearning-modelbuilder/issues/2335

**Comment by luisquintanilla** [comment]
Done!
