### ISSUE TITLE
[Deep Learning] Add support for local environments to Object Detection Scenario in Model Builder

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2333]
## Summary

Support local training environments for the Object Detection Scenario:

- Supported Training environments
  - Local CPU
  - Local GPU

## Dependencies

- [x] ML.NET framework needs to add the API to enable this scenario.

## Related issues

- #1091

**Comment by Aeroverra** [comment]
Would love to see this. I learn on my self hosted personal project then I bring that skill to work and host it on Azure. :)

**Comment by HowToGibbon** [comment]
Was the local button removed after it has been released?
This article had it available: https://devblogs.microsoft.com/dotnet/object-detection-ml-dotnet-model-builder/

**Comment by luisquintanilla** [comment]
> Was the local button removed after it has been released? This article had it available: https://devblogs.microsoft.com/dotnet/object-detection-ml-dotnet-model-builder/

It should be there. 

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/46974588/2714196a-7388-456c-891d-0d9d0fe018f6)

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/46974588/41af7c48-49b1-41c6-8b80-102ac63418c2)
