### ISSUE TITLE
Implement Sentence Similarity SweepableEstimator in ML.NET

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2338]

**Comment by luisquintanilla** [comment]
Investigate whether the Text Classification Sweepable Estimator can be reused since the inputs are the same, the only things that change are the API call and output.

**Comment by kobubu** [comment]
Guys, thank you for your work on ml.net but right now I have so many questions.
What is the purpose of training your own model for sentence similarity? If I need to calculate a bleu score or levenstein distance between 2 sentences it's much easier to implement already existing algorithms.
Is there a working example on how to use your sentence similarity scheme?  As far as I understood, first I need to calculate levenstein distance or bleu score, etc. Then I make a dataset with reference, target and score and then I can train a model to find bleu score which I've already found?
What languages I should use to train a sentence similarity model? What are requirements to dataset? A little tutorial would help a lot. (Right now I couldn't find any)
