### ISSUE TITLE
Add method to load from DataFrame

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2339]

**Comment by beccamc** [comment]
@luisquintanilla what are we trying to accomplish with this? Show how to load data into a DataFrame? Or use/convert a DataFrame for training?

**Comment by luisquintanilla** [comment]
@beccamc 

Good question. The first. Although thinking about it some more, I'm not sure how well this fits in the Model Builder use case because we generate the input and output classes for users. 

The advantage that the DataFrame gives you is, there's less need for you to specify model schema because those are inferred by the DataFrame. 

However, for large datasets, this may cause a problem because DataFrame expects data to fit into memory. 

I think for the time being, we can close this issue. I am already [tracking](https://github.com/dotnet/docs/issues/32112) a work item to add a document to MSFT docs showing how to use the DataFrame. We also already have the notebook you created showcasing it as well so I think **let's document first and monitor feedback later**. 

Thoughts?

**Comment by beccamc** [comment]
Yes I think that's a good idea! This is probably more useful in samples than our generated code. Let's close for now and revisit with feedback.
