### ISSUE TITLE
Implement mlnet telemetry in AutoMLService

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#234]
- [ ] `ApplicationExitEvent`
- [x] `ExperimentCompletedEvent`
- [x] `ExperimentIterationCompletedEvent`
- [x] `InferColumnsEvent`
- [ ] `MLNetCommandEvent`
- [x] `SystemInfoEvent`

`ApplicationExistEvent` and `MLNetCommandEvent` won't be implemented inside Model Builder cause it's mlnet cli specific

**Comment by LittleLittleCloud** [comment]
those telemetries are ones that implemented in cli, so we'd better do the same thing in AutoMLService so `ML.NET` can still fetch data from it's users

@justinormont Please take a look and see if I miss something

**Comment by JakeRadMSFT** [comment]
@justinormont, it'll probably end up in out VS Telemetry. We'll have to work with Duy on how to join it with CLI data.

**Comment by justinormont** [comment]
Any solution is fine. It seem dual logging is more simple for the moment. Other choices I see is forwarding between services, or giving AutoML folks read access into your telemetry stores.

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud I think it's logging things twice.

![image.png](https://images.zenhubusercontent.com/5cde1c65e3106e39e8ae08f2/57b30bc2-e046-4c9f-90c2-31382304fcaa)

**Comment by LittleLittleCloud** [comment]
Seems I forget to unsubscribe AutoML events, it will be fixed at once

**Comment by JakeRadMSFT** [comment]
Sends Duplicate Events

**Comment by JakeRadMSFT** [comment]
Doesn't send the model builder session id.
