### ISSUE TITLE
Capitalize computer vision

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2340]
VS Version: 17.3.6
MB Version: 16.14.0.2255301

Capitalize "vision" in "Computer vision"

![image](https://user-images.githubusercontent.com/46974588/199793895-7210daac-0279-4a2a-8e2c-d2fef9ab06d9.png)

**Comment by beccamc** [comment]
Why are we capitalizing Computer Vision when the scenarios only capitalize the first word?

**Comment by beccamc** [comment]
Oh I see. Natural Language Processing is all caps.

**Comment by luisquintanilla** [comment]
Yeah. I think in general these tasks are capitalized. Not the highest priority item but I see you already opened a PR. Thanks

**Comment by beccamc** [comment]
Validate 

![Image](https://user-images.githubusercontent.com/9122518/200695545-c3d83a17-b36a-4754-be3b-b5406427ee4f.png)
