### ISSUE TITLE
Text classification  API spell error in training.cs

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2341]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  latest main
 - Visual Studio Version
![image](https://user-images.githubusercontent.com/16876986/199795314-bed2ea2e-fd20-4350-9bc6-bafebcb86416.png)

Also `labelColumn` is missing

**Comment by luisquintanilla** [comment]
Validated. Fixed. Closing this issue
