### ISSUE TITLE
Azure image classification console app program.cs should use MLImage to load image from file

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2342]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): main
 
![image](https://user-images.githubusercontent.com/16876986/199796709-1854fa4a-1797-49c6-b85e-b7dd8eafbbe5.png)

should be

```csharp

// This file was auto-generated by ML.NET Model Builder. 

using AzureImage_ConsoleApp2;
using Microsoft.ML.Data;
// Create single instance of sample data from first line of dataset for model input
var image = MLImage.CreateFromFile(@"C:\Users\xiaoyuz\Desktop\WeatherData2\Cloudy\cloudy1.jpg");
AzureImage.ModelInput sampleData = new AzureImage.ModelInput()
{
    ImageSource = image,
};
// Make a single prediction on the sample data and print results
var predictionResult = AzureImage.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Label value: {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");


````

**Comment by v-Hailishi** [comment]
Verified on the latest main build: 16.14.0.2255702, the generated Console app project can be run successfully.
But the generated Web Api project still run failed.
![image](https://user-images.githubusercontent.com/99375895/200530167-9cee6862-c146-4ca1-9488-ddecf086f656.png)
![image](https://user-images.githubusercontent.com/99375895/200530203-8203007c-24be-4904-a3db-aa2225140736.png)
