### ISSUE TITLE
Unclear whether image classification is training on local GPU - Workaround: Set environment variable TF_CPP_MIN_LOG_LEVEL=3

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2343]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.14.0.2255301
 - Visual Studio Version: 17.3.6

**Describe the bug**
Training image classification scenario doesn't produce display progress in the output window making it difficult to know whether any progress is happening. When training is cancelled, it just hangs. 

**To Reproduce**

Train image classification scenario on local GPU environment.

**Expected behavior**
Progress displays in output window and training completes successfully.

**Screenshots**

## Training

![image](https://user-images.githubusercontent.com/46974588/199809138-5c8bacee-a153-4d6b-8b91-7b0a5fd1e61a.png)

## Cancel training

![image](https://user-images.githubusercontent.com/46974588/199809183-68952fe8-decb-49c3-941c-796d1daf2d63.png)

**Additional context**

[ImageClassification-FHT35X.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/9932186/ImageClassification-FHT35X.txt)

**Comment by JakeRadMSFT** [comment]
I hit this and tried to set set TF_CPP_MIN_LOG_LEVEL=3 from developer command prompt.

**Comment by LittleLittleCloud** [comment]
#https://github.com/dotnet/machinelearning-modelbuilder/issues/2319

**Comment by JakeRadMSFT** [comment]
> I hit this and tried to `set TF_CPP_MIN_LOG_LEVEL=3` from developer command prompt.

Nevermind - this did work!

**Comment by luisquintanilla** [comment]
Okay to not hold the release for this issue since VS will be fixing in December and we have a known workaround.

**Comment by luisquintanilla** [comment]
Add workaround to release notes.

**Comment by beccamc** [comment]
Included in release notes https://github.com/dotnet/machinelearning-modelbuilder/blob/main/docs/release-notes/16.14.0.md
