### ISSUE TITLE
Text classification train time link should be hidden

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2345]
"How long should I train for?" should be hidden for the Text classification scenario. It should follow what we do for image/object where it trains for as long as required. 

![image](https://user-images.githubusercontent.com/9122518/199822817-c56030b0-91b5-4312-8f03-b9526035b13c.png)

It should look like this...
![image](https://user-images.githubusercontent.com/9122518/199823022-5875169f-7d93-4948-8da7-f57eec0c1f20.png)

**Comment by zewditu** [comment]
Should it look like image  train page 
or Object as follows 
![image](https://user-images.githubusercontent.com/36615490/199896427-2eb7d7b2-6063-4810-94f6-3de8a9791ec8.png)

**Comment by beccamc** [comment]
Validated.
