### ISSUE TITLE
Tabular text should wrap instead of getting cut off.

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#2350]
Tabular text should wrap instead of getting cut off.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/31937616/200442297-8c4ad722-c9be-4083-89e6-0660a990121d.png">

**Comment by beccamc** [comment]
Finished! Closing.

**Comment by luisquintanilla** [comment]
Validated
