### ISSUE TITLE
Some initial letters should be capitalized, and some rows should not be indented in the Output window.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2352]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2255401 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Some initial letters should be capitalized and some rows should not be indented in the Output window.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select any scenario.
  5. On Data page, select the data source and then completed the training.
  6. In the Output window, you will see that some initial letters were lowercase, and some rows were indented.

**Expected behavior**
Some initial letters should be capitalized, and some rows should not be indented in the Output window.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/200463911-3fea8ffc-5e32-45d0-b05e-09465aca92bf.png)
![image](https://user-images.githubusercontent.com/99375895/200463996-9a00eef5-545a-4bd1-9f4c-16ddd0c4d007.png)
![image](https://user-images.githubusercontent.com/99375895/200465624-f288fee8-e100-4a7f-a518-8b0dc71b6e49.png)

**Additional context:**

**Comment by beccamc** [comment]
A lot of this is just informational logging. We are okay with this not being uniform. Closing. Thanks!
