### ISSUE TITLE
Enable GPU scoring in codegen for Text Classification

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2356]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.14.0.2255703
 - Visual Studio Version: 17.3.6

**Describe the bug**
- Clear description of the problem:
When Local GPU is selected as an environment, the `CreatePredictionEngine` method in *.consumption.cs* should be set to use GPU.

```csharp
private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
{
    var mlContext = new MLContext();
    mlContext.GpuDeviceId = 0;
    mlContext.FallbackToCpu = false;
    ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
    return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
}
```

**To Reproduce**

Train a model using Text Classification scenario.

**Expected behavior**

GPU should be used for scoring.

**Comment by homersimpsons197** [comment]
Hi Mr.Quintanilla, i have a little problem. I'm trying to access "Text classification" on the model builder but it dont give me the option to choose it, i only have 6 scenarios and text classification is missing. All updates are made and etc. Can you explain me why is this happening?
Thank you

**Comment by luisquintanilla** [comment]
@homersimpsons197 which version of Visual Studio and Model Builder are you using?

**Comment by homersimpsons197** [comment]
Oh sry Mr.Quintilla, i got it working finally, Model Builder was showing a green check but needed to get updated anyway... Sry and also a big thank you for fast answer. May i ask you a question?

**Comment by homersimpsons197** [comment]
Do you have an email or a way i can send you a message if its possible?

**Comment by luisquintanilla** [comment]
> Do you have an email or a way i can send you a message if its possible?

Sure. Feel free to send me a message at Luis.Quintanilla@microsoft.com

**Comment by homersimpsons197** [comment]
Thank you, i appreciate!

**Comment by luisquintanilla** [comment]
Validated. Moving to done
