### ISSUE TITLE
Cuda is not available for GPU Text classification

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2357]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.14.0

**Describe the bug**
For the Text Classification scenario... on the environment tab it shows that the machine has a Cuda compatible GPU. However, when training there is an error: "cuda is not available, please confirm you have a cuda-support gpu". 

**To Reproduce**
1. Select Text- classification scenario
2. Select GPU
3. Select data
4. Train

**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/200651256-85aa69f6-7937-4bf9-9c2c-d10a18be2a2a.png)

**Additional context**
![image](https://user-images.githubusercontent.com/36615490/200651591-2b58a3e6-40fd-4e56-8574-462e6a293bc9.png)

**Comment by JakeRadMSFT** [comment]
Can you try updating your graphics card?

https://www.nvidia.com/Download/driverResults.aspx/192967/en-us/

**Comment by zewditu** [comment]
Updating driver from version 461.40 to 526.47 fix the issue

**Comment by beccamc** [comment]
@zewditu Can you add some more information about what you used to update this driver so customers can follow the steps if they run into this?
