### ISSUE TITLE
Text classification: The output results have problem for the generated Console app and Web Api projects.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2360]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2255803 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The output results have problem for the generated Console app and Web Api projects.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Text classification"** scenario and data source to complete the training.
  5. Click "Add to solution" button on the Consume page to generate Console App and Web Api projects.
  6. Run the generated Console App and Web Api projects and check their output results.
  
**Expected behavior**
The output results have no problem.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/200764507-5a822e4a-3af2-45c0-a1e9-d7df2da0c761.png)

**Comment by zewditu** [comment]
On latest main
 WebApi  for Text- classification
![image](https://user-images.githubusercontent.com/36615490/200916042-ae9c8115-4372-4a21-86cb-349f382fa682.png)

WebApi for data- multiclassification
![image](https://user-images.githubusercontent.com/36615490/200917017-f0431879-0dc7-4d20-9745-af108d02e532.png)

it seems that something is off for both ? 
@luisquintanilla

**Comment by v-Hailishi** [comment]
Verified on the latest main build:16.14.0.2256401, the bug is still repro for generated Web API project.
![image](https://user-images.githubusercontent.com/99375895/201895320-9eacdbe1-1408-46c8-98a2-44aec2a3c707.png)

**Comment by luisquintanilla** [comment]
It's okay for text and data classification scenario API outputs not to match because while for text classification we expect input to always to text, it's not always the case for data classification. Moving to validation.

**Comment by v-Hailishi** [comment]
Verified on the latest main build:16.14.0.2256701, the bug is still repro for generated Web API project. for API output, the score value is incorrect. It should be like **{0.83....., 0.17....}** (Their sum should be **1**).
![image](https://user-images.githubusercontent.com/99375895/202633350-3a55b927-d4d0-4c58-bd8c-8a483f89d03f.png)

**Comment by zewditu** [comment]
@v-Hailishi thanks for catching this issue , it is related to this https://github.com/dotnet/machinelearning-modelbuilder/issues/2317

**Comment by zewditu** [comment]
This is prediction result calibration or sum to 1 issue.

We fix this  https://github.com/dotnet/machinelearning-modelbuilder/issues/2317 for evaluate page from Model builder  temporarily , in the webApi we used `predictionEnginePool.Predict()`which is in Ml.Net
I think this issue should be transferred to ML.net

**Comment by zewditu** [comment]
we can make code gen update to fix this from model builder as well

**Comment by zewditu** [comment]
I proposed the code update to calibrate prediction results in web app for text- classification.
Only for the case of text classification Add the following method in a generated project consumption code 
` public static async Task<ModelOutput> CreatePredictEnginePollWebApp(PredictionEnginePool<ModelInput, ModelOutput> predictionEnginePool, MLModel2.ModelInput input)
    {
        var output = await Task.FromResult(predictionEnginePool.Predict(input));
        var scores = output.Score;
        // To get scores sum up to 1
        var exp = scores.Select(x => (float)Math.Exp(x));
        var softMaxScores = exp.Select(x => x / exp.Sum()).ToArray();
        output.Score = softMaxScores;
        return output;

    }`

**Comment by luisquintanilla** [comment]
> I proposed the following code update to calibrate prediction results in web app for text- classification. Only for the case of text classification Add the following method in a generated project consumption code ![image](https://user-images.githubusercontent.com/36615490/205417632-cdf5d3c4-0f25-4e23-8811-304075096786.png)
> 
> Pass this method as handler in Programs.cs ![image](https://user-images.githubusercontent.com/36615490/205417676-574a25f0-af3a-49fe-8ea7-e3b8a5dcd9b0.png)
> 
> @luisquintanilla @LittleLittleCloud ?

What that method does is part of the prediction, rather than creating a web app with PredictionEnginePool. I think the current method is called `Predict`, so I would suggest keeping that name.

**Comment by LittleLittleCloud** [comment]
In the long run, I would propose putting the softmax as an option in TextClassification trainer so the final score from TextClassification trainer will sum up to one. What you think @luisquintanilla @michaelgsharp

**Comment by luisquintanilla** [comment]
> In the long run, I would propose putting the softmax as an option in TextClassification trainer so the final score from TextClassification trainer will sum up to one.

Would this be a one off or something that the other deep learning classification models (i.e. object detection, image classification) would benefit from?
