### ISSUE TITLE
Text classification: Save button should be disabled if select multiple Text purpose in advanced data option.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2366]
**System Information (please complete the following information):**
- Windows OS: Windows-11-Enterprise-21H2
- ML.Net Model Builder 2022: 16.13.10.2256001 (Main Build)
- Microsoft Visual Studio Enterprise: 2022(17.3.6)
- Net: 6.0

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 6.0;
3. Add model builder by right click on the project.
4. Select **Text classification** scenario and navigate to data page.
5. Open Advanced data options dialog to set two **Text** purpose.
6. You will see the save button is still enabled.

**Expected behavior**
Save button should be disabled if select multiple Text purpose in advanced data option.

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/201313700-2fc89882-d29f-4ef1-860d-c6a3a67c38e4.png)

**Additional context**

**Comment by torronen** [comment]
I think now it makes the rest of the fields "Features", also just randomly selects one as Text. 
Are others auto-ignored? If they are ignored, then it is also confusing they are marked as features. In this case, I think, maybe, Save button should also be disabled if there are Features which can not be used by Text Classification.

If they are not ignored, it would be good to have some explanation which field to select "Text" and which to select "Feature".

**Comment by zewditu** [comment]
@torronen  yes  we have some confusing things around here, we have work item(https://github.com/dotnet/machinelearning-modelbuilder/issues/2296) probably we will resolve them for the next release.
Technically if a column is not "Label" or "Text" it does not have purpose or it is ignored, however it still shows as "Feature" which does not make sense .

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2256701
![image](https://user-images.githubusercontent.com/99375895/202670622-49807cdc-f210-4ce7-9bbf-60ced63d0985.png)
