### ISSUE TITLE
No Fut

### ISSUE THREAD

**Issue by ratropedro21** [dotnet/machinelearning-modelbuilder#2373]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@ratropedro21 are you able to add more information? Like steps the reproduce the issue .

**Comment by beccamc** [comment]
Sorry we don't have enough information to address this issue. Feel free to open a new issue if you're still experiencing problems.
