### ISSUE TITLE
Add Text-Classification  scenario icon 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2374]
Design and all other resources found at https://github.com/rnd-pm-ux-design-amandas/d3-work-items/issues/128

**Comment by beccamc** [comment]
@zewditu I think this is done. Can you link the PR and update this issue?

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build: 16.14.0.2256701
![image](https://user-images.githubusercontent.com/99375895/202608279-a7986d43-dbb6-4df6-ac6f-f0c14808ff6f.png)
