### ISSUE TITLE
Image classification-Azure&Object detection: The generated Web Api project run failed.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2376]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2256401 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The generated Web Api project run failed.

**TestMatrix**
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#create-a-new-vott-project

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Object detection" or "Image classification-Azure"** scenario and data source to complete the training.
  5. Click "Add to solution" button on the Consume page to generate **Web Api** projects.
  6. Run the generated Web Api projects.
  
**Expected behavior**
The generated Web Api project should run successfully.

**Screenshot**
<img width="532" alt="image" src="https://user-images.githubusercontent.com/99375895/201881835-7cbef482-5277-4964-b65a-c43ec3e8d934.png">

**Additional context**
The generated Console App project can run successfully.

**Comment by zewditu** [comment]
This one  seems  related  to https://github.com/dotnet/machinelearning-modelbuilder/issues/2323,

**Comment by zewditu** [comment]
@LittleLittleCloud  this should be fixed by this PR  https://github.com/dotnet/machinelearning-tools/pull/1597 in the release version,  right?

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.0.2260101
![image](https://user-images.githubusercontent.com/99375895/205248827-f5e5fc19-d6d2-4038-a802-9afdf5952cb1.png)
