### ISSUE TITLE
Ignore non-label columns (recommendation, text classification, Sentence similarity, ...)

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2378]
For the following scenarios we do not have feature column, hence if the column is not one of the label columns it should be ignored automatically. 

- Recommendation  =>  not (Label or user or Item) =ignore
- Text-classification => not ( Label or text) =ignore
- Sentence similarity => not (Label or sentence one or sentence two) =ignore

**Comment by beccamc** [comment]
This is a dupe of https://github.com/dotnet/machinelearning-modelbuilder/issues/2296
