### ISSUE TITLE
reference to libtorch-cuda

### ISSUE THREAD

**Issue by IzzyHibbert** [dotnet/machinelearning-modelbuilder#2379]
**System Information (please complete the following information):**
 - OS & Version: WIN 11
 - ML.NET Version: 2.0.0
 - .NET Framework : 4.8

**Describe the bug**

Trying to start the training with GPU, for a TEXT CLASSIFICATION scenario.
As soon as the training stage starts, it throws an error like :

```
This application or script uses TorchSharp but doesn't contain a reference to libtorch-cuda-11.3-win-x64, Version=1.11.0.1.

Consider referencing one of the combination packages TorchSharp-cpu, TorchSharp-cuda-linux, TorchSharp-cuda-windows or call System.Runtime.InteropServices.NativeLibrary.Load(path-to-LibTorchSharp.dll) explicitly for a Python install of pytorch. See https://github.com/dotnet/TorchSharp/issues/169.".

For CUDA, you may need to call 'TorchSharp.torch.InitializeDeviceType(TorchSharp.DeviceType.CUDA)' before any use of TorchSharp CUDA packages from scripts or notebooks.

Trace from LoadNativeBackend:

TorchSharp: LoadNativeBackend: Initialising native backend, useCudaBackend = True

Step 1 - First try regular load of native libtorch binaries.

    Try loading Windows cuda native components
    Trying to load native component cudnn_adv_infer64_8 relative to c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\55zi5gdd.vbo\AutoMLService\TorchSharp.dll
    Failed to load native component cudnn_adv_infer64_8 relative to c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\55zi5gdd.vbo\AutoMLService\TorchSharp.dll
    Trying to load native component cudnn_adv_train64_8 relative to c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\55zi5gdd.vbo\AutoMLService\TorchSharp.dll
    Failed to load native component cudnn_adv_train64_8 relative to c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\55zi5gdd.vbo\AutoMLService\TorchSharp.dll
    Trying to load native component cudnn_cnn_infer64_8 relative to c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\55zi5gdd.vbo\AutoMLService\TorchSharp.dll
    Failed to load native component cudnn_cnn_infer64_8 relative to c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\55zi5gdd.vbo\AutoMLService\TorchSharp.dll
    Trying to load native component cudnn_cnn_train64_8 relative to c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\55zi5gdd.vbo\AutoMLService\TorchSharp.dll
    Failed to load native component cudnn_cnn_train64_8 relative to c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\55zi5gdd.vbo\AutoMLService\TorchSharp.dll
    Trying to load native component cudnn_
```

**To Reproduce**
Open Model Builder, Select Text Classification and LOCAL (GPU), then it throws the error message

**Expected behavior**
Expected: To continue the training.

**Comment by beccamc** [comment]
@JakeRadMSFT Thoughts on this?

**Comment by ccaven** [comment]
I'm not using model builder, but I will add that the same error occurs when I try to use TorchSharp with Unity Game Engine. Could be helpful in diagnosing where the problem is.

**Comment by bush-dev** [comment]
I've encountered the same error while trying to use SentenceSimilarity API.

**Comment by JakeRadMSFT** [comment]
Can you try deleting the folder 'torchsharp-cuda-windows.0.96.7' from  '%temp%\ModelBuilder' and try again?

**Comment by Ha5her** [comment]
I was having the same issue. Deleting the "cuda" folder from "%Temp%\ModelBuilder" fix the issue. 

Looking further I notice the directory was only 80kb... Which only contained cache and config files.

Reran the model builder, The directory is now 3.43GB and everything is working perfect!

**Comment by IzzyHibbert** [comment]
Even in my case, "%temp%\ModelBuilder" did the job and fixed it.
Closing

**Comment by smtmRadu** [comment]
> I'm not using model builder, but I will add that the same error occurs when I try to use TorchSharp with Unity Game Engine. Could be helpful in diagnosing where the problem is.

Did you managed to make it work in Unity? I'm still struggling with this for days.
