### ISSUE TITLE
Can't bind the IDataView column 'text' of type 'String' to field or property 'Text' of type 'System.Single[]

### ISSUE THREAD

**Issue by AlbelTec** [dotnet/machinelearning-modelbuilder#2382]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): **16.14.0.2255902**
 - Visual Studio Version : **2022**

**Describe the bug**
- On which step of the process did you run into an issue: **at runtime consumption**
- Clear description of the problem:
The template MLClassifier.consumption.cs generated by MLBuilder raise an error (as shown in the screenshot) when trying the classify a text.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/111683547/202551210-f817c589-1e91-43b3-8127-5ded96576541.png)

**Additional context**

**Comment by zewditu** [comment]
Note able to reproduce on 
Model Builder Version : 16.14.0.2255902
Visual Studio Version : 2022

**Comment by AlbelTec** [comment]
Solved. This was due to misconfiguration of inputcolumn.

**Comment by pjsgsy** [comment]
Just to add - I am facing the same issues after using model builder. Added some additional columns and all trains fine etc., but in use, get the Can't bind the IDataView column 'col39' of type 'Key<UInt32, 0-2>' to field or property 'Col39' of type 'System.Single'. The Col39 was the old class holder, so I even though a new column was selected in training etc., and it all worked after, this is being left and not updated somewhere.
