### ISSUE TITLE
Text classification: The Code snippet would be blank on the Consume page after you close and reopen .mbconfig file.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2383]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.0.2256701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.1)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The Code snippet would be blank on the Consume page after you close and reopen .mbconfig file.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Text classification"** scenario and data source to complete the training.
  5. Go to the Consume page, at this time, the Code snippet is displayed normally.
  6. Close and reopen .mbconfig file, go to the Consume page again, at this time, the Code snippet is blank.
  
**Expected behavior**
The Code snippet should be diapled normally on the Consume page after you close and reopen .mbconfig file.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/202669931-a6e3426a-6a96-43bb-8ae1-f5b7ddba9e27.png)

**Additional context**

**Comment by beccamc** [comment]
@JakeRadMSFT Maybe you can help me with this. The root cause here is that on reload of the text classification model we are missing 'LibTorchSharp'. I assume during training this DLL is loaded, and when we reload this DLL is missing. Do you know how I resolve this?

![image](https://user-images.githubusercontent.com/9122518/205149114-765fd761-4d14-45f4-bc8d-3f8ea08558eb.png)

**Comment by zewditu** [comment]
@beccamc  before we  load model
`// add runtime to env
            var path = Environment.GetEnvironmentVariable("Path");
            if (!path.Contains(runtimeFolder))
            {
                var newPath = $"{runtimeFolder};{path}";
                Environment.SetEnvironmentVariable("Path", newPath);
            }`

**Comment by zewditu** [comment]
The fix of this issue  https://github.com/dotnet/machinelearning-modelbuilder/issues/2398 might fix this

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.0.2260501
![image](https://user-images.githubusercontent.com/99375895/206336865-96d2cb5d-3fcd-42f3-8c8a-5bce0e86b516.png)

**Comment by luisquintanilla** [comment]
Validated
