### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by kalyan12346** [dotnet/machinelearning-modelbuilder#2384]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
sorry @kalyan12346 I don't have enough information for this issue. Can you complete the information?

**Comment by beccamc** [comment]
I'm assuming this is an early draft of https://github.com/dotnet/machinelearning-modelbuilder/issues/2385. Closing!
