### ISSUE TITLE
About Program.cs in .nett

### ISSUE THREAD

**Issue by kalyan12346** [dotnet/machinelearning-modelbuilder#2385]
Hello, I am getting error in the program.cs for sentimental analysis. here by i am attaching the screen shot 
![Screenshot (3)](https://user-images.githubusercontent.com/104155930/202688541-9ba5b8bd-53dd-4dc6-b28e-c218bf78ffbe.png)

**Comment by beccamc** [comment]
Something went wrong with code gen here. Can you re-run through Model Builder? 

It looks like "SentimentModel" is the wrong name and based on your solution explorer it may be called MLModel1

**Comment by zewditu** [comment]
This is resolved
