### ISSUE TITLE
Fast Forest Regression Index out of bounds

### ISSUE THREAD

**Issue by johnalamina** [dotnet/machinelearning-modelbuilder#2389]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: V9SGE1
 - Visual Studio Version (if applicable): 2022

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): Training page
![image](https://user-images.githubusercontent.com/54987004/203777554-8256ebfd-a707-4a15-bf9a-913d60e3808d.png)

- Clear description of the problem:
Training using Fast Forest regression after 2 seconds gives an index out-of-bounds error

**To Reproduce**
1. Open model builder
2. Select "predict a value"
3. Go to 'Model builder'
4. Select the model ('data' pasted below)
5. Select 'Score' as prediction
6. Click next 
7. Click start to start training
8. Exception window pops up.
9. See error pasted below

   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.PipelineProposer.Propose(TrialParameter trialParameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/PipelineProposer.cs:line 97
   at Microsoft.ML.ModelBuilder.AutoMLService.Proposer.Controller.Propose() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Proposer/Controller.cs:line 59
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.<ExecuteAsync>d__15.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 167   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<<StartTrainingAsync>b__109_0>d.MoveNext()
**Expected behavior**

I expect training with output model.zip/

**Screenshots**
![image](https://user-images.githubusercontent.com/54987004/203778738-83432a8b-a7b4-41ed-8cf8-4456e770fc25.png)

**Additional context**
CPU: AMD Ryzen 5

'Data'
Cond1,Cond2,PreXD,PostXD,Score
66.67,66.67,47,1023,1.423553
66.67,66.67,47,1023,3.993136
66.67,66.67,47,1023,1.660233
66.67,66.67,47,1023,2.377717
66.67,66.67,47,1023,0.809677
66.67,66.67,47,1023,1.58775
66.67,66.67,1023,63,1.201184
66.67,66.67,1023,63,1.341092
66.67,66.67,1023,63,1.693922
66.67,66.67,1023,63,0.873457
66.67,66.67,1023,63,0.939619
66.67,66.67,1023,63,2.44428
66.67,66.67,47,47,2.576402
66.67,66.67,47,100,2.595958
66.67,66.67,47,200,3.21301
66.67,66.67,47,500,3.012121
66.67,66.67,47,1000,3.032865
66.67,66.67,47,65535,3.023405
66.67,66.67,100,47,2.520967
66.67,66.67,100,100,2.974832
66.67,66.67,100,200,2.924051
66.67,66.67,100,500,3.014729
66.67,66.67,100,1000,2.974242
66.67,66.67,100,65535,2.995159
66.67,66.67,200,47,2.947701
66.67,66.67,200,100,2.696682
66.67,66.67,200,200,2.758642
66.67,66.67,200,500,2.738569
66.67,66.67,200,1000,2.690072
66.67,66.67,200,65535,2.68556
66.67,66.67,500,47,2.464327
66.67,66.67,500,100,2.515622
66.67,66.67,500,200,2.511951
66.67,66.67,500,500,2.490351
66.67,66.67,500,1000,2.476886
66.67,66.67,500,65535,2.501954
66.67,66.67,1000,47,2.48658
66.67,66.67,1000,100,2.47831
66.67,66.67,1000,200,2.46709
66.67,66.67,1000,500,2.506087
66.67,66.67,1000,1000,2.456704
66.67,66.67,1000,65535,2.465004
66.67,66.67,65535,47,2.480195
66.67,66.67,65535,100,2.496002
66.67,66.67,65535,200,2.475872
66.67,66.67,65535,500,2.451888
66.67,66.67,65535,1000,2.443831
66.67,66.67,65535,65535,2.454969
66.67,66.67,47,47,1.59437
66.67,66.67,47,100,1.599719
66.67,66.67,47,200,1.718281
66.67,66.67,47,500,1.696483
66.67,66.67,47,1000,1.703426
66.67,66.67,47,65535,1.680624
66.67,66.67,100,47,1.597991
66.67,66.67,100,100,1.689249
66.67,66.67,100,200,1.669466
66.67,66.67,100,500,1.680925
66.67,66.67,100,1000,1.700536
66.67,66.67,100,65535,1.713711
66.67,66.67,200,47,1.765431
66.67,66.67,200,100,1.697051
66.67,66.67,200,200,1.716511
66.67,66.67,200,500,1.727008
66.67,66.67,200,1000,1.719836
66.67,66.67,200,65535,1.715129
66.67,66.67,500,47,1.75071
66.67,66.67,500,100,1.756529
66.67,66.67,500,200,1.741125
66.67,66.67,500,500,1.745199
66.67,66.67,500,1000,1.736374
66.67,66.67,500,65535,1.736886
66.67,66.67,1000,47,1.755545
66.67,66.67,1000,100,1.764492
66.67,66.67,1000,200,1.749207
66.67,66.67,1000,500,1.753723
66.67,66.67,1000,1000,1.747081
66.67,66.67,1000,65535,1.742958
66.67,66.67,65535,47,1.763199
66.67,66.67,65535,100,1.748055
66.67,66.67,65535,200,1.751993
66.67,66.67,65535,500,1.737374
66.67,66.67,65535,1000,1.754306
66.67,66.67,65535,65535,1.743476

**Comment by zewditu** [comment]
@LittleLittleCloud  is this  related to this issue https://github.com/dotnet/machinelearning-modelbuilder/issues/1602

**Comment by LittleLittleCloud** [comment]
@zewditu yep
@johnalamina  Looks like you are not playing the latest model builder. We have checked in a fix for this issue on ml.net side which has been released. Could you update your model builder and try again

**Comment by LittleLittleCloud** [comment]
Well looks like the fix on ml.net just checked in. So we need to wait for the next model builder release to fix this issue

https://github.com/dotnet/machinelearning/pull/6430#event-7906117734

**Comment by beccamc** [comment]
Blocked on next Model Builder release

**Comment by luisquintanilla** [comment]
Related to #2294. Moved to validate

**Comment by LittleLittleCloud** [comment]
Validated and succeed.
