### ISSUE TITLE
Ran into error with timing logic?

### ISSUE THREAD

**Issue by Vivraan** [dotnet/machinelearning-modelbuilder#2390]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 2.0.0
 - Visual Studio Version (if applicable): 17.4.1

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: Tried training with the data attached:  [knot_data_overhand_old.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10106115/knot_data_overhand_old.csv)

**To Reproduce**
1. Follow steps on the page exactly.
1. See error.

**Expected behavior**

I expected there to be some trained model files. Instead, I got this error: 
[error.log](https://github.com/dotnet/machinelearning-modelbuilder/files/10106120/error.log)

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@Vivraan  sorry for hitting the issue ,  form the log I understand that it seems `Training time finished without any models trained` issue ,  are you able to increase your train time and try again?

**Comment by Vivraan** [comment]
> @Vivraan sorry for hitting the issue , form the log I understand that it seems `Training time finished without any models trained` issue , are you able to increase your train time and try again?

I tried it with two different training times, 60s and 300s, and in both cases I hit the same error.

**Comment by beccamc** [comment]
@v-Hailishi Can you test with the attached dataset? 

@Vivraan This may be that ML.Net is struggling to train here because you only have one label instance. Are you able to add more data? Non-overhead examples?

**Comment by v-Hailishi** [comment]
@beccamc Tried on the main build 16.14.0.2257101, I choose "**Data classification**" scenario and column "**col0**" as Label, I got the below error.
![image](https://user-images.githubusercontent.com/99375895/204943921-f9e59986-a12e-4a76-9845-9343b1737543.png)
![image](https://user-images.githubusercontent.com/99375895/204944271-f17c1d49-f75e-4cc0-92a1-4c2dd0cfed50.png)

**Comment by Vivraan** [comment]
> @v-Hailishi Can you test with the attached dataset?
> 
> @Vivraan This may be that ML.Net is struggling to train here because you only have one label instance. Are you able to add more data? Non-overhead examples?

I will try adding more data to test this weekend.

**Comment by Vivraan** [comment]
Could I also know what the issue is? I urgently need to work on this data.

**Comment by luisquintanilla** [comment]
> Could I also know what the issue is? I urgently need to work on this data.

Completely speculating here but I assume you're trying to predict the first column using data from the other columns. I suspect the issue as Becca pointed out is that you only have one category in that first column: *overhand*. In order to classify items, you need to have at least two categories. If you have examples of other categories, I would recommend adding them to your dataset and trying to train again.

**Comment by zewditu** [comment]
@Vivraan  I was just test it by  adding a dummy category "underhand" to your dataset it seems work.
[knot_data_overhand_old (1).csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10136042/knot_data_overhand_old.1.csv)

**Comment by Vivraan** [comment]
> @Vivraan I was just test it by adding a dummy category "underhand" to your dataset it seems work. [knot_data_overhand_old (1).csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10136042/knot_data_overhand_old.1.csv)

Got it, I'll try adding more labelled data to my training sample with a separate label.

**Comment by beccamc** [comment]
Glad it was resolved! Let us know if you run into anything else.
