### ISSUE TITLE
Telemetry Asks Fall 22

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2393]
Ongoing issue to check on telemetry that we would need to make sure we have.
- [x] How many users are training via GPU - Training run method [dashboard](https://dataexplorer.azure.com/dashboards/5b95430c-93c0-4ccd-9a6c-6237ce7acfce?p-_startTime=1hours&p-_endTime=now&tile=fb9ae7fb-c4fd-425e-8266-35af0adcc7d5)
- [x] Nuget usage related to data prep - [dashboard](https://dataexplorer.azure.com/dashboards/5b95430c-93c0-4ccd-9a6c-6237ce7acfce?p-_startTime=1hours&p-_endTime=now&tile=a9a6a4e6-030b-4379-9216-3da78606d1e5)

**Comment by beccamc** [comment]
@luisquintanilla This shows the number of training runs with GPU vs. other methods. Do we want information about users too?

**Comment by luisquintanilla** [comment]
> This shows the number of training runs with GPU vs. other methods.

@beccamc I can't think of anything beyond what's there now. We would already be able to filter for unique runs right?

**Comment by beccamc** [comment]
> We would already be able to filter for unique runs right?

@luisquintanilla Current dashboard is of unique training runs

**Comment by beccamc** [comment]
@luisquintanilla  For nuget usage of Microsoft.Data.Analysis, is there an ML.NET usage dashboard somewhere? In model builder we have a dashboard for various "ML.NET" nugets. Wondering if there is another dashboard elsewhere that has the correct guids for these nugets. 

If nothing already exists, it looks like we need workload tags for these?

**Comment by luisquintanilla** [comment]
> > We would already be able to filter for unique runs right?
> 
> @luisquintanilla Current dashboard is of unique training runs

Great. I think that might be enough then.

> @luisquintanilla For nuget usage of Microsoft.Data.Analysis, is there an ML.NET usage dashboard somewhere? In model builder we have a dashboard for various "ML.NET" nugets. Wondering if there is another dashboard elsewhere that has the correct guids for these nugets.
> 
> If nothing already exists, it looks like we need workload tags for these?

Not that I'm aware of, but I don't think there is additional information we need to create a dashboard specifically for Microsoft.Data.Analysis.

**Comment by beccamc** [comment]
Maybe we should just chat quickly, but how do you want to measure "Nuget usage related to data prep"? Don't we need to track the Microsoft.Data.Analysis namespace?

**Comment by beccamc** [comment]
These are resolved. Closing.
