### ISSUE TITLE
Image classification code should use MLImage

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2395]
The code generated by Model Builder for Image classification (local) generates a byte[] for the image source type. This should be an MLImage like object detection scenario. 

![image](https://user-images.githubusercontent.com/9122518/204899263-97b37825-0780-449d-80f5-460dca451539.png)

**Comment by zewditu** [comment]
I investigated a little bit  Mlmage  is a replacement to Bitmaps not bytes , local image uses bytes  hence we need to keep that  why? I do not know , originally local image and Azure image classification uses different image types  hence we just replace bitmap with MLIMage for Azure  image and object.

**Comment by beccamc** [comment]
Thanks Zewditu! That sounds good, we can close this.
