### ISSUE TITLE
The target framework version should be .NET7.0 for the generated projects when training on the .NET7.0 project.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2401]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.0.2260101 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.1)
.Net: 7.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The target framework version should be .NET7.0 for the generated projects when training on the .NET7.0 project.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core**7.0**) project template.
  3. Add model builder by right click on the project.
  4. Select any scenario.
  5. On Data page, select the data source and complete the training.
  6. On the Consume page, click "Add to solution" button to generate the Console App and Web API projects.
  7. Check the target framework version for the generated projects, you will see that:
      a. For **Forecasting** scenario, the target framework version is **NET5.0**.
      b. For other scenarios, the target framework version is **NET6.0**.

**Expected behavior**
The target framework version should be .NET7.0.

**Screenshot**

![image](https://user-images.githubusercontent.com/99375895/205243038-64df91d0-c4fa-4ef5-b07d-1181d928b4c1.png)

**Additional context**

**Comment by luisquintanilla** [comment]
@luisquintanilla to add details. For generated project templates it's okay that it targets the latest LTS version.

**Comment by luisquintanilla** [comment]
Closing this issue since we expect generated projects to be on the latest long-term support version (LTS).
