### ISSUE TITLE
Data classification: When the training status showing completed, the output windows is still in progress.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2407]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2257101 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.1)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
When the training status showing completed, the output windows is still in progress.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification** scenario.
  5. On Data page, select the data source and choose **Sentiment** column as label.
  6. On the Train page, click "Start training" button to complete the training.
  7. You will see that when the training status showing completed, the output windows are still in progress.

**Expected behavior**
When the training status showing completed, the output windows also should be completed.

**Gif**
![#2407](https://user-images.githubusercontent.com/99375895/206064056-c7e0be29-653b-48be-8563-a50291783fb6.gif)

**Additional context:**

**Comment by luisquintanilla** [comment]
Hi @v-Hailishi,

Thanks for reporting this issue. Since there's a slight delay, we're okay with this for now. As we hear additional feedback we can look into it. Closing for now.
