### ISSUE TITLE
ML.NET Tutorial Issue

### ISSUE THREAD

**Issue by aayushh-patell** [dotnet/machinelearning-modelbuilder#2409]
**System Information (please complete the following information):**

 - Model Builder or CLI Version: MacOS Terminal Version Version 2.13 (447)
 - Visual Studio Version (if applicable): N/A

**Describe the bug**

- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: I was following the machine learning tutorial in the link above, but I ran into an error when writing my terminal commands

**To Reproduce**

1. dotnet tool install -g mlnet-osx-arm64
2. ** Locate to designated folder on system **
3. mkdir MachineLearningTutorial
4. cd MachineLearningTutorial
5. mlnet classification --dataset "yelp_labelled.txt" --label-col 1 --has-header false --name SentimentModel  --train-time 60
6. ** Error occurs: "zsh: command not found: mlnet" **

**Expected behaviour**

I expected the ML.NET CLI to output the data I was searching for

**Screenshots**

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/76638947/206823978-3011d5ff-4de3-4996-b7f8-a1c533b95c89.png">

**Additional context**

**Comment by viettham1998** [comment]
I think you can open a new terminal window and run again.

**Comment by luisquintanilla** [comment]
Hi @aayushh-patell

Thanks for reporting this issue. I believe the issue is you're using zsh. 

![image](https://user-images.githubusercontent.com/46974588/207723486-3544cdb9-1a6c-4a95-a9c8-632cf6c23499.png)

@LittleLittleCloud what are the commands to provide these permissions?

Related to #1476

**Comment by luisquintanilla** [comment]
Action plan:

- [ ] Update getting started tutorial on dotnet website.
- [ ] Update CLI installation instructions.

**Comment by LittleLittleCloud** [comment]
@luisquintanilla I believe the command is 
```
chmod +x /path/to/mlnet
```
