### ISSUE TITLE
Confusion in the README

### ISSUE THREAD

**Issue by keyedit** [dotnet/machinelearning-modelbuilder#241]
Quote from your ReadMe:
_We currently support .tsv, .csv and SQL as the data-types you can use as datasets for the Model Builder. The files should have a header row. For this preview Model Builder does not support *.txt files or ';' separated or ',' separated files_

Perhaps there is a subtle difference between CSV files and ',' separated files in the ML/Model Builder world that I'm not getting. Is it possible to clarify what this means as CSV and ',' separated are the same thing to me :)

**Comment by JakeRadMSFT** [comment]
https://github.com/dotnet/machinelearning-samples/blob/master/modelbuilder/readme.md#Data

@keyedit, I agree it's confusing. The readme is trying to describe that we support .csv and .tsv files but we don't support files with a .TXT extension that for example AppleTypes.txt that happens to have csv-like format in it. 

@rustd, Can we update our documentation?

**Comment by briacht** [comment]
As a quick fix, I've updated the wording to make it more clear (and now we support .txt files):

"We currently support .tsv, .csv, .txt, and SQL as the data types you can use as datasets for Model Builder. If you have a .txt file, columns should be separated with ',' or ';' or '/t'. The files must have a header row."

I am going to update the whole README with our most recent feature updates, including for image classification.

**Comment by briacht** [comment]
We removed the README and added all info into Docs: https://docs.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-model-builder#data

**Comment by beccamc** [comment]
Closing this as the information has been updated in the docs.
