### ISSUE TITLE
Train results have a RSquared value <0

### ISSUE THREAD

**Issue by Elantonio** [dotnet/machinelearning-modelbuilder#2411]
**System Information (please complete the following information):**
 - Model Builder Version ML.NET 2.0.0
 - Visual Studio Version VS2022

**Describe the bug**
 
- Clear description of the problem:
Returns  Rsquared values smaller than 0.
Statistically if should be >= 0 and <= 1

**To Reproduce**
- Modeltraining (MLModel1.mbconfig)
- environment Local CPU (i9)
- Train

**Expected behavior**
a value bigger or equal t o 0

**Screenshots**
![image](https://user-images.githubusercontent.com/7442635/206921463-5c3a4b6d-15dc-44bc-844c-8ed0652f31cc.png)

**Comment by zewditu** [comment]
It seems also not sorted well 
![image](https://user-images.githubusercontent.com/36615490/207145257-b2f8c9aa-5f00-4460-95a1-10d350d55b18.png)

**Comment by LittleLittleCloud** [comment]
RSquare can be less than zero, see this [explanation](https://github.com/dotnet/machinelearning/issues/6437)
