### ISSUE TITLE
Do not allow generated sample projects have the same name with mbconfig File

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2412]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**
1. Go to  any  scenario
2. complete all the steps
3.Add we Api or console app projects with the same name of mbconfig file

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
We have two options 

1. Disabled the UI to add project if we provide a name the same  mbconfig file.
2. Just sanitized the namespace if it is equal to the mbconfig

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.2.2306101
<img width="613" alt="image" src="https://user-images.githubusercontent.com/99375895/212036939-1be4b58a-397f-4644-bb74-eac21eff0839.png">
