### ISSUE TITLE
Next Step after adding Data data

### ISSUE THREAD

**Issue by Arody0007** [dotnet/machinelearning-modelbuilder#2414]
In ML.NET Tutorial after adding the data the next step is not working despite following the instruction given in the tutorial

**Comment by zewditu** [comment]
@Arody0007   depending on the scenario you have to select label columns 
what is the scenario you are using?
are you able to send us the scree shout of data page.

**Comment by zewditu** [comment]
Closed b/c not enough information to move forward. If you still hit the issue let us know
