### ISSUE TITLE
Data page does not update fast when we switch between data source types.

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2417]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/207697906-9ce342cc-7f9a-4d3c-93ec-70505458dd08.png)

**Additional context**

**Comment by luisquintanilla** [comment]
@zewditu can you please add more details to this. Thanks

**Comment by zewditu** [comment]
Not able to reproduce the issue consistently.
Close until someone else hits it again.
