### ISSUE TITLE
Data classification: The generated Console App and Web API projects are running failed.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2418]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.0.2261401 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.1)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The generated Console App is running failed.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv
SQL Password

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Data classification** scenario.
  5. On Data page, select the data source and choose **Sentiment** column as label.
  6. On the Train page, click "Start training" button to complete the training.
  7. Click "Add to solution" button on the Consume page to generate Console App project.
  8. Run the generated Console App project.

**Expected behavior**
The generated Console App project should be running successfully.

**Screenshots**
File:
![image](https://user-images.githubusercontent.com/99375895/207821874-2c95a495-c253-410c-aaed-917b13ed1c9d.png)
SQL Password:
![image](https://user-images.githubusercontent.com/99375895/207821951-ce932746-d083-4635-b3c4-63114da32140.png)

**Additional context:**

**Comment by v-Hailishi** [comment]
The bug is also repro for **Text classification** scenario: The generated Console App project is running failed; the generated Web API project is running successfully.
![image](https://user-images.githubusercontent.com/99375895/207831712-0087f2de-b6ec-4a3f-a120-d1ebd2e904cb.png)

**Comment by zewditu** [comment]
Regressed by this PR https://github.com/dotnet/machinelearning-tools/pull/1624.

**Comment by beccamc** [comment]
Thanks for finding this @v-Hailishi! 

Dev team - possible root cause is that this is binary classification?

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.14.0.2262002, the bug is repro on **Data classification, Value predication, Recommendation, Forecasting, Text classification** scenarios.

**Comment by zewditu** [comment]
For  this
![image](https://user-images.githubusercontent.com/36615490/210424374-50ff6360-a35e-4f9e-86d9-1fe2f6b1a2ca.png)
 binary is not an issue , it happens for text classification types such as data-classification(binary and multi) and Text- classification but it is not consistence

**Comment by zewditu** [comment]
It is not reproduceable from the latest main
![image](https://user-images.githubusercontent.com/36615490/210433276-def06c75-2c95-41c7-8536-94759e453624.png)

**Comment by zewditu** [comment]
Code behind generation missed  installation of  `System.Data.SqlClient`
![image](https://user-images.githubusercontent.com/36615490/210433797-aee51f2f-8e7f-45d6-9359-8e25548f3b0f.png)

**Comment by zewditu** [comment]
@v-Hailishi  FYI: to validate code in the generated project we should use the newly mbconfig file, if you use old mbconfig file you might get some errors

**Comment by JakeRadMSFT** [comment]
We're going to change our code to convert to strings for now in AutoML pipelines and CodeGen. We'll also look into supporting other types in ML.NET. 

@michaelgsharp has something that we've briefly tested and it works.

**Comment by JakeRadMSFT** [comment]
For AutoML we can try the following change:

https://github.com/dotnet/machinelearning/blob/a758217121c85cf5af9a2ea3f759feae2020d7b5/src/Microsoft.ML.AutoML/SweepableEstimator/Estimators/MapValueToKey.cs#L11


Change to something like this:
.Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"Label",inputColumnName:@"Label", addKeyValueAnnotationsAsText: true))

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.14.2.2306001, the generated Console App and Web API projects are still running failed on scenarios: **Data classification, Value predication, Recommendation, Forecasting, Text classification** scenarios.
The following are the details:

- Data classification

1.1 File1 (https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv)
Console App:
![image](https://user-images.githubusercontent.com/99375895/211751121-d0393727-7431-42b5-bb9e-b4f2998f6599.png)
Web API:
![image](https://user-images.githubusercontent.com/99375895/211751468-61d8e987-3fd5-472e-ab8e-32b3d6b58597.png)

1.2 File2 (https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt)
Console App: **Run successful**
<img width="949" alt="image" src="https://user-images.githubusercontent.com/99375895/211761055-5860826c-2e57-431a-b032-353088a9e71a.png">
Web API:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/99375895/211761326-8b537e00-52f4-4afe-80c2-e81a91821eda.png">

1.3 Microsoft SQL Server: Binary (SQL Password)
Console App:
![image](https://user-images.githubusercontent.com/99375895/211751229-923e4e0b-2e42-4a11-acdb-e71bda69f58d.png)
Web API:
![image](https://user-images.githubusercontent.com/99375895/211751269-4561df4c-ce39-41dd-907f-3d09979072d0.png)

1.4 Microsoft SQL Server Database File (https://github.com/dotnet/machinelearning-samples/raw/main/samples/modelbuilder/MulticlassClassification_RestaurantViolations/RestaurantScores.zip)
Console App: **Run successful**
![image](https://user-images.githubusercontent.com/99375895/211756137-b00309eb-4636-4db5-bd1c-ddfe140a675d.png)
Web API:
![image](https://user-images.githubusercontent.com/99375895/211756701-eeada417-eb72-4e73-b0c3-c247b3e91b47.png)

- Value predication:
The generated Console App project is running successfully; the generated Web API project is running fail.

Console App: **Run successful**
<img width="544" alt="image" src="https://user-images.githubusercontent.com/99375895/211759423-8fe75d1d-1ca6-4a0a-8d30-ad61efe4d9ee.png">

Web API:
File:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/99375895/211759803-4cb3a5bc-931f-4a2d-ab20-d1e562295a8c.png">
SQL:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/99375895/211762370-b54cc405-cb3b-40b3-b80e-f682e769e511.png">

- Recommendation:
The generated Console App project is running successfully; the generated Web API project is running fail.

Console App: **Run successful**
<img width="715" alt="image" src="https://user-images.githubusercontent.com/99375895/211763965-e7e79a73-9f7b-4449-8f78-a427368905c2.png">

Web API:
File:
<img width="723" alt="image" src="https://user-images.githubusercontent.com/99375895/211764351-e8c1b0de-6ea8-4d88-9af8-c7298fb9d203.png">
SQL:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/99375895/211765264-ff0ff198-ffb8-4d6a-9ea7-58154f949227.png">

- Forecasting:
Both of the generated Console App and Web API projects are still running failed

File: 
<img width="716" alt="image" src="https://user-images.githubusercontent.com/99375895/211767353-eec16e90-a362-453f-9c08-40bfc729f97e.png">
SQL:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/99375895/211769085-c16007a4-e82c-496e-8bf6-705501da5b9d.png">

- Text classification:

Console App: 
<img width="690" alt="image" src="https://user-images.githubusercontent.com/99375895/211773685-2bc1b103-00dc-4d6f-a79c-7670b5999a95.png">

Web API:
File:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/99375895/211774003-4aa74ded-a217-43ab-bef1-f73e0374f7cb.png">
SQL:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/99375895/211776660-cf8780c6-7c7c-4c8c-a276-e8e50a5acf0c.png">

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.14.2.2306101, the generated Console App and Web API projects are still running failed on scenarios: **Data classification, Value predication, Recommendation, Forecasting, Image Classification-Local, Text classification** scenarios.
The following are the details:

- Data classification

1.1 File1 (https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv)
Console App: **Run successful**
<img width="495" alt="image" src="https://user-images.githubusercontent.com/99375895/211950097-ede22cc8-0a30-489c-b03e-ab40aad80198.png">
Web API:
![image](https://user-images.githubusercontent.com/99375895/211751468-61d8e987-3fd5-472e-ab8e-32b3d6b58597.png)

1.2 File2 (https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt)
Console App: 
<img width="908" alt="image" src="https://user-images.githubusercontent.com/99375895/211953533-4bc522c4-f42a-405b-81c9-d8af711068f2.png">
Web API:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/99375895/211761326-8b537e00-52f4-4afe-80c2-e81a91821eda.png">

1.3 Microsoft SQL Server: Binary (SQL Password)
Console App:
![image](https://user-images.githubusercontent.com/99375895/211751229-923e4e0b-2e42-4a11-acdb-e71bda69f58d.png)
Web API:
![image](https://user-images.githubusercontent.com/99375895/211751269-4561df4c-ce39-41dd-907f-3d09979072d0.png)

1.4 Microsoft SQL Server Database File (https://github.com/dotnet/machinelearning-samples/raw/main/samples/modelbuilder/MulticlassClassification_RestaurantViolations/RestaurantScores.zip)
Console App: 
<img width="729" alt="image" src="https://user-images.githubusercontent.com/99375895/211951047-66b7d3a3-9d0c-4717-934f-756c57e13114.png">
Web API:
![image](https://user-images.githubusercontent.com/99375895/211756701-eeada417-eb72-4e73-b0c3-c247b3e91b47.png)

- Value predication & Recommendation:
The generated Console App project is running successfully; the generated Web API project is running fail.

Web API:
File:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/99375895/211759803-4cb3a5bc-931f-4a2d-ab20-d1e562295a8c.png">
SQL:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/99375895/211762370-b54cc405-cb3b-40b3-b80e-f682e769e511.png">

- Forecasting:
Both of the generated Console App and Web API projects are still running failed.

File: 
<img width="716" alt="image" src="https://user-images.githubusercontent.com/99375895/211767353-eec16e90-a362-453f-9c08-40bfc729f97e.png">
SQL:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/99375895/211769085-c16007a4-e82c-496e-8bf6-705501da5b9d.png">

- Image Classification-Local:
The generated Console App project is running fail; the generated Web API project is running successfully.

Console App: 
<img width="896" alt="image" src="https://user-images.githubusercontent.com/99375895/211956377-15ab3e4e-4ff2-4940-af76-c6701aa58c62.png">


- Text classification:
The generated Console App project is running successfully; the generated Web API project is running fail.

Console App: **Run successful**
<img width="528" alt="image" src="https://user-images.githubusercontent.com/99375895/211963345-77553aa9-9ddc-491a-92f6-d97caeef0d26.png">

Web API:
File:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/99375895/211774003-4aa74ded-a217-43ab-bef1-f73e0374f7cb.png">
SQL:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/99375895/211776660-cf8780c6-7c7c-4c8c-a276-e8e50a5acf0c.png">

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.14.2.2306701, the generated Console App and Web API projects are still running failed on scenarios: **Data classification, Value predication, Recommendation, Forecasting, Image Classification-Local, Object detection, Text classification** scenarios.
The following are the details:

- Data classification

1.1 File (https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv)
Console App: Run successful
Web API: Failed (After removing the unnecessary using directive, can run successful)
![image](https://user-images.githubusercontent.com/99375895/213097769-f3c0f75f-b69c-497d-a10a-24cfc5620762.png)

1.2 Microsoft SQL Server: Binary (SQL Password)
Console App: Failed
<img width="700" alt="image" src="https://user-images.githubusercontent.com/99375895/213089949-672f5549-f961-4bbc-b44d-74e962099cdd.png">
Web API: Failed
<img width="699" alt="image" src="https://user-images.githubusercontent.com/99375895/213091947-f7cbdc14-05cb-41b4-91d4-7157e2f01052.png">
After removing the unnecessary using directive, still run failed.
<img width="693" alt="image" src="https://user-images.githubusercontent.com/99375895/213092222-08b1df73-4f0c-47c3-b9d3-4e725529afa8.png">

1.3 Microsoft SQL Server Database File (https://github.com/dotnet/machinelearning-samples/raw/main/samples/modelbuilder/MulticlassClassification_RestaurantViolations/RestaurantScores.zip)
Console App: Run successful
Web API: Failed
<img width="699" alt="image" src="https://user-images.githubusercontent.com/99375895/213091947-f7cbdc14-05cb-41b4-91d4-7157e2f01052.png">
After removing the unnecessary using directive, still run failed.
<img width="690" alt="image" src="https://user-images.githubusercontent.com/99375895/213093057-2068c072-4143-4632-b56d-992a4c63c3db.png">

- Value predication & Recommendation:
The generated Console App project is running successfully; the generated Web API project is running fail.

Web API: 
File: (After removing the unnecessary using directive, can run successful)
<img width="714" alt="image" src="https://user-images.githubusercontent.com/99375895/213096139-dde1ef93-ae72-4055-9f48-3170fd6f99b2.png">
SQL: 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/99375895/213096139-dde1ef93-ae72-4055-9f48-3170fd6f99b2.png">
After removing the unnecessary using directive, still run failed.
<img width="714" alt="image" src="https://user-images.githubusercontent.com/99375895/213097007-80414217-a100-43c9-825c-049833614acc.png">

- Forecasting:
Both of the generated Console App and Web API projects are still running failed.

File: 
Console App:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/99375895/213102347-02f303b6-c327-4287-a5ce-1b735613ef76.png">
Web API:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/99375895/213102527-1c138ba7-f736-408e-a377-a66855e027a3.png">

SQL:
Console App:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/99375895/213103902-cedde53f-7914-4813-9274-ab86773b037c.png">
Web API:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/99375895/213104208-96aded00-cf05-43ca-a915-6d85cf1cf646.png">


- Image Classification-Local & Object detection:
The generated Console App project is running successfully; the generated Web API project is running failed.

Web API: (After removing the unnecessary using directive, can run successful)
<img width="697" alt="image" src="https://user-images.githubusercontent.com/99375895/213105801-e3802000-f234-4611-95e4-66e5d3847cd0.png">

- Text classification:
The generated Console App project is running successfully; the generated Web API project is running fail.

Web API:
File: Failed (After removing the unnecessary using directive, can run successful)
<img width="698" alt="image" src="https://user-images.githubusercontent.com/99375895/213113802-2a50bc7b-ca0f-46ad-bb6e-2e3539b4e0ff.png">

SQL:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/99375895/213115867-124bdbfb-d0a6-447c-b356-dc25dd8fe5d8.png">
After removing the unnecessary using directive, still run failed.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/99375895/213116006-ad94475d-226c-4116-968e-bf1c814abe33.png">

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.14.2.2306903, the generated Console App and Web API projects are still running failed on scenarios: **Data classification, Value predication, Recommendation, Forecasting, Text classification** scenarios.
The following are the details:

- Data classification

1.1 File (https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv)
Console App: Run successful
Web API: Run successful

1.2 Microsoft SQL Server: Binary (SQL Password)
Console App: Failed
![image](https://user-images.githubusercontent.com/99375895/213615862-80e5da36-1065-4c13-b1a6-220fc13156ef.png)
Web API: Failed
<img width="698" alt="image" src="https://user-images.githubusercontent.com/99375895/213616489-aadddf79-6465-4f96-8871-bedf3828e71a.png">

1.3 Microsoft SQL Server Database File (https://github.com/dotnet/machinelearning-samples/raw/main/samples/modelbuilder/MulticlassClassification_RestaurantViolations/RestaurantScores.zip)
Console App: Run successful
Web API: Failed (After choosing "Use local version '4.8.3'" can run successful.)
<img width="706" alt="image" src="https://user-images.githubusercontent.com/99375895/213617554-4e380b77-accf-499e-938d-5fad2deb0f97.png">

- Value predication & Recommendation & Text classification:
The generated Console App project is running successfully; the generated Web API project is running fail.

Web API: 
File: Run successful
SQL: Failed (After choosing "Use local version '4.8.3'" can run successful.)
<img width="755" alt="image" src="https://user-images.githubusercontent.com/99375895/213618951-d7296424-1333-41f7-ad0f-5ebff30fa5d7.png">

- Forecasting:
Both of the generated Console App and Web API projects are still running failed.

File: 
Console App: Failed (After choosing "using System.IO;" can run successful.)
<img width="746" alt="image" src="https://user-images.githubusercontent.com/99375895/213628718-573ee3d8-3d63-4da0-9326-392b62c20df0.png">
Web API: Failed
<img width="707" alt="image" src="https://user-images.githubusercontent.com/99375895/213632947-601fa704-3597-4591-af76-187f5ce6ea50.png">

SQL:
Console App: Failed (After choosing "using Microsoft.ML.Data;" and "using System.IO;" and "Use local version '4.8.3'" can run successful.)
<img width="861" alt="image" src="https://user-images.githubusercontent.com/99375895/213630851-317be63e-2f31-4633-8a10-a9dcc5bccfdf.png">
Web API: Failed
<img width="702" alt="image" src="https://user-images.githubusercontent.com/99375895/213104208-96aded00-cf05-43ca-a915-6d85cf1cf646.png">

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.14.3.2307701, the generated Console App and Web API projects are still running failed on scenarios: **Data classification**.

- Data classification
Only failed for Microsoft SQL Server: Binary (SQL Password)
Console App: Failed
<img width="552" alt="image" src="https://user-images.githubusercontent.com/99375895/215692139-68f50fb6-4117-4126-b19f-80a4411e9e65.png">
Web API: Failed
<img width="555" alt="image" src="https://user-images.githubusercontent.com/99375895/215692488-e68304b8-44f1-4dd2-84e9-16342fae3980.png">

**Comment by zewditu** [comment]
@v-Hailishi   what do you mean SQL password? is that a dataset,  are you able to share your dataset? thanks

**Comment by v-Hailishi** [comment]
@zewditu "SQL password" just means I use the SQL Server Authentication to log on to the server.
![image](https://user-images.githubusercontent.com/99375895/215921978-0d7c1140-e984-4490-9559-062f59e89913.png)

Besides, in the database, I use the dataset "https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv".
<img width="394" alt="image" src="https://user-images.githubusercontent.com/99375895/215922647-ade9a6c8-7ff2-4529-9db3-ba84b1ef04c9.png">

**Comment by beccamc** [comment]
@zewditu This isn't regarding SQL. You can repro this by using a boolean type. I used the yelp dataset and set the prediction column to type boolean 

![image](https://user-images.githubusercontent.com/9122518/216398549-4baf2415-6bbb-49f8-9a87-7706c385de58.png)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.3.2310605.
![image](https://user-images.githubusercontent.com/99375895/217138637-d9b57e86-c25f-49f1-82f1-37e185db8f20.png)
