### ISSUE TITLE
Custom Scenario is Missing

### ISSUE THREAD

**Issue by luxzz** [dotnet/machinelearning-modelbuilder#2422]
![Untitledxx](https://user-images.githubusercontent.com/30105939/208274237-f013cc05-844d-4b9d-b897-df805c88c1fa.png)

**Comment by beccamc** [comment]
@luxzz What would you like to do with the custom scenario? What type of training would it be?

**Comment by beccamc** [comment]
We don't have enough information to help here. Feel free to comment if you can let us know more about what you're trying to do!
