### ISSUE TITLE
Got stucked in MLNET tutorial

### ISSUE THREAD

**Issue by FeiWang93** [dotnet/machinelearning-modelbuilder#2426]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.14.0+4be0d1bbdd23182e304cd74a8b833c40fd980be3
 - Visual Studio Version (if applicable): 1.74.2

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: my command line shows me many lines of problems after I entered the command "mlnet classification --dataset "yelp_labelled.txt" --label-col 1 --has-header false --name SentimentModel  --train-time 60"

**Screenshots**
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/48781553/209520426-f34027c8-2b0b-47bc-8cd1-959b4f08a0f9.png">

**Additional context**
How to solve this?

**Comment by LittleLittleCloud** [comment]
dup of https://github.com/dotnet/machinelearning-modelbuilder/issues/2406
