### ISSUE TITLE
GPU training takes ages without ending VS 20 min CPU 

### ISSUE THREAD

**Issue by IzzyHibbert** [dotnet/machinelearning-modelbuilder#2428]
**System Information (please complete the following information):**
 - Model Builder 2022, version 16.14.0
 - VS Community 2022
I was trying to use Model Builder with GPU in order to build an image classification model..
My setup includes an Nvidia RTX 2060, with the dataset of 880 images in 9 classes.
The machine where I am doing this test is a Win 11, where I am conected remotely (RDP). Connecting directly does not change.

**Describe the bug**

Summary: **training starts, never ends, stays almost at no GPU consumption**

Before the training starts I can see that all the prerequisites are ok :

![Env_ok](https://user-images.githubusercontent.com/45388237/209800337-db818272-d86a-4898-a6c9-23f68123cde5.png)

Also another detail from CUDA installed :

![CUDA-INSTALLED](https://user-images.githubusercontent.com/45388237/209800618-96b010e5-6fd2-4200-850e-05a2146c976d.png)

The training starts fine but the process goes per hours, withouth ending. I actually left it running for almost a night and no results.
I noticed that the GPU almost never properly runs, being just a bit over zero.

![TRAIING AND GPU DETAILS](https://user-images.githubusercontent.com/45388237/209800863-20472983-a4f1-42a3-80c1-3af34a2120e7.png)

See another view here:

![GPU-OFF](https://user-images.githubusercontent.com/45388237/209801115-ef5e3113-d053-416a-b456-dec598b152b6.png)

If I move the same stuff to **CPU training, it does the job in 20 minutes**.

**To Reproduce**
After selecting the initial parameters (GPU here), the training starts and does not end. CPU training for the same dataset does a 20 min training..

**Expected behavior**
I would say I should have a training completed in less time than the CPU time, with an attempt to use a GPU

**Comment by IzzyHibbert** [comment]
Hi @zewditu any chance to get a review of the case ? Any other info you might need from my side to help you with more ?

**Comment by zewditu** [comment]
@IzzyHibbert  sorry for delay and hitting the issue,  from your environment tab screenshot it looks like everything is ok .
we will  start to investigate it.
For any case you can refer this doc related to image GPU training  https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder

**Comment by JakeRadMSFT** [comment]
@IzzyHibbert - are you seeing anything in the output window?

**Comment by IzzyHibbert** [comment]
Hi @JakeRadMSFT 

I am not getting any output at all. Not even after all night of process. In other words training starts and did not manage to have an end.

In the below screenshot you see that the scenario is GPU, training started, but GPU resources (left side) are almost doing NOTHING.

![Resources](https://user-images.githubusercontent.com/45388237/216764460-5e52ee69-f437-452c-ad3f-bd755da39b33.png)

If you want to have a look at the log, you can find it [here](https://pastebin.com/Zj0YsnhT)

**Comment by IzzyHibbert** [comment]
I suspect this issue is just GPU training not really working in Model Builder as mentioned [here](https://github.com/dotnet/machinelearning-modelbuilder/issues/2479)

**Comment by IzzyHibbert** [comment]
Today I made an update of Model Builder, to version 17.14.3.23
Repeated the test: training Image Classification with GPU.
Same result: training starts, nothing happens at the GPU level (resource is not starting to work, or progress) and  no error messages.
It's basically the same issue I documented in December.

I also made a test with text classification (using GPU in MB vers. 17.14.3) and seems to work. Looks then that issue is specific of Image Classification.

**Comment by IzzyHibbert** [comment]
Not sure if this is of any help for @JakeRadMSFT and @LittleLittleCloud .

I tried to further investigate the issue by myself. There was an issue for Image Classification, with a solution helping to debug without Model Builder [it's here](https://github.com/dotnet/machinelearning-modelbuilder/issues/1081#issuecomment-720664989).
There's one difference: in my case no errors are displayed in VS during training and no errors in the log.

I **took the sample project I found there** and it happens that **my training fails with an error** :


_Tensorflow.TensorflowException
  HResult=0x80131500
  Message=2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v2_50/conv1/Conv2D}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v2_50/conv1/Conv2D}}]]
	 [[resnet_v2_50/SpatialSqueeze/_7]]
0 successful operations.
0 derived errors ignored.
  Source=Microsoft.ML.TensorFlow
  StackTrace:
   at Microsoft.ML.TensorFlow.TensorFlowUtils.Runner.Run()
   at Microsoft.ML.Vision.ImageClassificationTrainer.CacheFeaturizedImagesToDisk(IDataView input, String labelColumnName, String imageColumnName, ImageProcessor imageProcessor, String inputTensorName, String outputTensorName, String cacheFilePath, Dataset dataset, Action`1 metricsCallback, Nullable`1 validationFraction)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at ImageClassification.Train.Program.Main() in D:\MLNET\IMAGE-CLASSIFICATION-SAMPLE\ImageClassification.Train\Program.cs:line 94_


I am using :
CUDA 10.1
cuDNN 7.6.4
which is the correct setup for Model Builder.

This is VS 

![Screenshot DETAILS IMAGE C](https://user-images.githubusercontent.com/45388237/220560289-decb2f42-f7d5-4778-9038-1c917fc9e433.png)

While this one is shows the consolle view of the project, together with GPU resource in use during the training  

![GPU_ALLOCATE](https://user-images.githubusercontent.com/45388237/220560460-16c15288-0bff-4ec1-b9dd-4f8cdc7ad1a3.png)

My 2 cents:
I can now finally exclude an issue in my setup (GPU starts correctly with the project of @LittleLittleCloud  ). In that project training stops for the error message detailed above, while Model Builder shows no progression and no errors (pretty much the topic of the issue). So I'd say it's a bug in Model Builder for image classification training with GPU.

**Comment by LittleLittleCloud** [comment]
Thanks for the investigation @IzzyHibbert ! that does help a lot

this reminds me of this [issue](https://github.com/dotnet/machinelearning-modelbuilder/issues/2343), which looks quite similar. Can  you share with us your VS version and try work-around mentioned there?

**Comment by IzzyHibbert** [comment]
Some updates @LittleLittleCloud ..

All the above work was made with VS 17.3
I tried to set `TF_CPP_MIN_LOG_LEVEL=3` from developer command prompt and to repeat the training on the sample project without Model Builder. It failed with the same issue as above reported.

After that, I decide to upgrade VS to latest: 17.5
I have tried again to repeat the training of my solution just by using Model Builder, but this time....

1) I saw that the GPU started to work as soon as training started [this is dfferent from version VS 17.3]. I noticed it from the task manager details.. 
2) I saw after a minute that an error was thrown. See the image here : 

![VS new](https://user-images.githubusercontent.com/45388237/221215698-c1d633ac-523e-4325-b15f-2daffa9bd7ca.png)

You can notice that the **error message is the same that I re-created with version 17.3 and your solution** in fact this error did not happen before in Model Builder, but it was also reported that GPU was not seen working at all..). 
The screenshot shows both GPU memory allocated (meaning now working) and error message `Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above`

[ID-GPU-3646EB.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/10825723/ID-GPU-3646EB.txt)

After that, I also have tried to retry your solution (no model builder), this time with VS 17.5 with `set TF_CPP_MIN_LOG_LEVEL=3` from developer command prompt. 
Situation does not change: the error messagge seems the same I have found behind the scenes in VS 17.3 and your solution and now with VS upgrade (17.5) thrown in Model Builder. See the screenshot :

![Error details](https://user-images.githubusercontent.com/45388237/221217702-4be393f0-6115-4780-b7e5-6bd39640248b.png)


What can we say ?

- With **17.3** or with **17.5** there were different behaviors. In **17.3** GPU did not start imho.
- With **17.3** and your solution I managed to get `Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above`
- With **17.5** now MB behaves correctly (GPU start to work as soon as training starts). Error message is thrown, even when using  `set TF_CPP_MIN_LOG_LEVEL=3` from developer command prompt. 

Final test: I used once again MB in VS 17.5 but this time I added command `set TF_CPP_MIN_LOG_LEVEL=3`.
Adding the command did not change the result, see here : 

![From MB with command](https://user-images.githubusercontent.com/45388237/221222003-8a2e7c5c-1910-4b36-82dd-86050a30ab89.png)

For this last attempt a detailed log file is available : 

[ID-GPU-Z3JNB5_with command.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/10825925/ID-GPU-Z3JNB5_with.command.txt)

**Comment by IzzyHibbert** [comment]
It's not solved, but I have just created [2530](https://github.com/dotnet/machinelearning-modelbuilder/issues/2530)  with a proper title and a clear description.
Still experiencing the bug with Model builder 17.14.4.

**Comment by LittleLittleCloud** [comment]
@IzzyHibbert Thanks for the reply, now we find something new here

<img width="688" alt="image" src="https://user-images.githubusercontent.com/16876986/224788158-63139a07-d9e2-4035-b79f-1791be3b4cb3.png">

It indicates that cudnn fails to get enough memory when initializing. And on stackoverflow I find someone also hitting that issue  as well. Under that issue one solution looks very promising

https://stackoverflow.com/a/65203824

Can you try that in `ImageClassification` and see if it resolves cudnn error you encounter? Thanks!
