### ISSUE TITLE
Model Builder Error: Index was outside the bounds of the array (Forecasting scenario)

### ISSUE THREAD

**Issue by rgoudie** [dotnet/machinelearning-modelbuilder#2429]
**System Information (please complete the following information):**
 - Model Builder Version: 16.14.0.2255902
 - Visual Studio Version: Visual Studio Community 2022 version 17.4.3
 - Windows version: Windows 10 Home version 10.0.19044

**Describe the bug**
- **Train** step throws exception. See attached screenshot.

**To Reproduce**
1. Create new Windows Console solution using either .NET 6 or .NET 7.
2. Add Model Builder to project.
3. Select **Forecasting** scenario.
4. Load CSV file, select last column as **Column to predict** and the first column (formatted date/time string) as the **Time series** column.
5. Leave **Time to train** at default value.
6. Set **Horizon** to 1.

**Date File**
The data file is a CSV file with 26 columns and 34,435 rows. The first column is a formatted date/time string (_tried with and without double-quotes_). The remaining columns are all non-normalized floating-point values.

**Expected behavior**
Training should complete without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/34731480/210027455-7b12356e-1f0a-4d44-9bde-6733bcd5c59f.png)

**Additional context**
Exception is thrown with both .NET 6 and .NET 7.
Exception is thrown with metrics RMSE and MAE.

(If I use the MAPE metric, then the exception is just "overflow".)

**Comment by zewditu** [comment]
@rgoudie  note able to reproduce it for me using  the data below
[Binance_BTCUSDT_1h.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10340366/Binance_BTCUSDT_1h.csv)
are you able to share us your dataset?

**Comment by rgoudie** [comment]
Sorry for the late reply. No notifications (or they went to spam). I will close the issue as it is too old.
