### ISSUE TITLE
Can i need to select model in step Avaluate

### ISSUE THREAD

**Issue by ctphu** [dotnet/machinelearning-modelbuilder#2432]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by luisquintanilla** [comment]
Hi @ctphu 

Can you please provide more details on what your issue / request is?

**Comment by beccamc** [comment]
@ctphu We don't have enough information to investigate this issue. If you're still having problems please re-open with more details. Screenshots and descriptions of what you would like to happen help a lot!
