### ISSUE TITLE
Images are missing for all scenarios on the "Select a scenario" page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2435]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.2.2306001 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.1)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Images are missing for all scenarios on the "Select a scenario" page.

**Data Source**

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Check all images on the "Select a scenario" page.

**Expected behavior**
All imaged should be displayed well.

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/211809263-fa4d463d-a143-4f08-8300-fb8407a9c885.png)

**Additional context:**
After running the following command: **devenv.exe /clearCache**, the bug is still present.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.2.2306101
<img width="717" alt="image" src="https://user-images.githubusercontent.com/99375895/211947817-746c08ef-607d-43f4-8594-af8278a20ec0.png">

**Comment by v-Hailishi** [comment]
The bug is repro again on the latest main build: 16.14.2.2306903.
![image](https://user-images.githubusercontent.com/99375895/213613594-51fd4392-beed-4ef6-8c8c-ee64afb481a9.png)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.3.2307701.
<img width="488" alt="image" src="https://user-images.githubusercontent.com/99375895/215696612-d2824e14-2aae-4ea0-b295-7f9088849d6e.png">

**Comment by v-Hailishi** [comment]
The bug is repro again on the latest main build: 17.14.3.2310301.
<img width="480" alt="image" src="https://user-images.githubusercontent.com/99375895/216865731-58eca842-2ef2-45e5-8873-62c09ae5c4d3.png">

**Comment by beccamc** [comment]
@JakeRadMSFT have we decided to just ignore this problem?

**Comment by JakeRadMSFT** [comment]
Duplicate: #1930
