### ISSUE TITLE
Image classification-Azure: The generated Console App is running failed.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2436]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.2.2306001 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.1)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The generated Console App is running failed for Image classification-Azure scenario.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/weather.zip

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Image classification - Azure** scenario.
  5. On Data page, select the data source.
  6. On the Train page, click "Start training" button to complete the training.
  7. Click "Add to solution" button on the Consume page to generate Console App project.
  8. Run the generated Console App project.

**Expected behavior**
The generated Console App project should be running successfully.

**Screenshots**
<img width="825" alt="image" src="https://user-images.githubusercontent.com/99375895/211812608-c5ca0294-9acb-432e-acd4-4daaeb7fc911.png">

**Additional context:**
The bug is not repro for Image classification-Local and Object detection scenarios.

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.14.2.2306101, both of the generated Console App and Web API projects are running failed.
<img width="764" alt="image" src="https://user-images.githubusercontent.com/99375895/211960664-08e999cb-ecfc-44cb-983a-0a9188fade6d.png">

**Comment by zewditu** [comment]
Azure image Output model missed column "Label"

**Comment by v-Hailishi** [comment]
Verified on the latest main build 16.14.2.2306701, both of the generated Console App and Web API projects are running failed.
Console App:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/99375895/211960664-08e999cb-ecfc-44cb-983a-0a9188fade6d.png">

Web API:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/99375895/213111470-44a22fb0-65f3-49b6-a556-6ba9475537fa.png">
After removing the unnecessary using directive, still run failed.
<img width="698" alt="image" src="https://user-images.githubusercontent.com/99375895/213111967-2f02629b-5f11-4415-b9d9-3ddf8f4b1198.png">

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.2.2306903.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/99375895/213639296-036bb92a-bcb3-49d6-b021-293f83a80ca1.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/99375895/213639351-97a54336-7f6b-4582-9eae-174e8dc179a2.png">
