### ISSUE TITLE
Text classification: Training failed with error "Column 'Sentiment' has type Boolean which does not support missing values, so we cannot filter on them".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2437]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.2.2306001 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.1)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The generated Console App is running failed.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv
SQL Password
<img width="675" alt="image" src="https://user-images.githubusercontent.com/99375895/211821454-9221e28e-4414-4810-ab64-365f7339f144.png">

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Text classification** scenario.
  5. On Data page, select the "Microsoft SQL Server" data source and choose Sentiment column as label and SentimentText column as Text. (The default data type for **Sentiment** column is "**Boolean**")
  6. On the Train page, click "Start training" button to start the training.
  7. **Training failed with error "Column 'Sentiment' has type Boolean which does not support missing values, so we cannot filter on them".**
  8. Go back to Data page, change **Sentiment** column's data type to "**String**" and train again.
  9. **Training failed with error "Column 'Sentiment' has type String which does not support missing values, so we cannot filter on them".**
  10. Go back to Data page, change **Sentiment** column's data type to "**Single**" and train again.
  11. **Training is completed successfully**.

**Expected behavior**
I am not sure whether the situation for step7 and step9 are expected or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/211824328-29792f6e-0e85-41e0-9fc0-03d1d92ff590.png)
![image](https://user-images.githubusercontent.com/99375895/211824346-f8d0dae6-321c-4974-8f53-4b6e898ef450.png)
![image](https://user-images.githubusercontent.com/99375895/211824384-53a80c24-09d8-422a-8e37-975e57eab61c.png)

**Additional context:**

**Comment by LittleLittleCloud** [comment]
Also happen if label type is text
<img width="434" alt="image" src="https://user-images.githubusercontent.com/16876986/211918415-d709f54c-eb0a-40e4-8e4b-3a5df5f9e12b.png">

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.3.2307701
![image](https://user-images.githubusercontent.com/99375895/215700541-c277d327-dae7-4989-b567-2f445b0b7b98.png)
