### ISSUE TITLE
Sample project generation  using old mbconfig file(model.zip)  failed 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2438]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luisquintanilla** [comment]
Related to #2439
