### ISSUE TITLE
Console app throws exception on predict

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#2441]
This is using the iris dataset.

<img width="864" alt="image" src="https://user-images.githubusercontent.com/31937616/211921323-1f4990d5-66e0-4613-becd-2f0ae2e27de9.png">

**Comment by JakeRadMSFT** [comment]
For strings it should be  - 

var keyNames = new VBuffer<ReadOnlyMemory<char>>();

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.2.2306903.
<img width="814" alt="image" src="https://user-images.githubusercontent.com/99375895/213656303-a572e15e-ea9f-4fb0-8782-5ddb7c7d4392.png">
![image](https://user-images.githubusercontent.com/99375895/213656461-a02e97f2-617f-4fba-984a-573a2c55fab3.png)
