### ISSUE TITLE
webapi build fail for classification

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2442]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  main
 - Visual Studio Version: VS 2022

**Describe the bug**
- .training.cs uses namespace while .consumption.cs doesn't.
- the following building errors show in .training.cs

<img width="987" alt="image" src="https://user-images.githubusercontent.com/16876986/211921800-2cc45d45-96c6-4bd6-91d1-44a5761cc0e4.png">

**To Reproduce**
- kick off training using titanic data
- generate web api

## Suggest fix
enabling `ImplicitUsings` in Web Api csproj and remove namespace in .training.cs

**Comment by beccamc** [comment]
@v-Hailishi Can you validate this please?

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.3.2307701, Web API build success for classification.
