### ISSUE TITLE
Trim non-Windows .NET dependencies

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2443]
When installing the Model Builder VSIX there are Mono dependencies that are installed. 

![image](https://user-images.githubusercontent.com/46974588/211923076-292c60dc-88da-4289-800c-c3f34e560b14.png)

Since we expect Model Builder to run on Windows platforms, it might make sense to remove those dependencies if possible to trim down the package size.

**Comment by JakeRadMSFT** [comment]
Our dependencies are super slim:

	<Dependencies>
		<Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" d:Source="Manual" Version="[4.5,)" />
	</Dependencies>
	<Prerequisites>
		<Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0,18.0)" DisplayName="Visual Studio core editor" />
	</Prerequisites>
	
Not sure why VS was installing those.

**Comment by JakeRadMSFT** [comment]
These are pretty universal - I'd recommend we close this as won't fix.

**Comment by luisquintanilla** [comment]
Thanks for looking into this @JakeRadMSFT. Closing.
