### ISSUE TITLE
Image classification - Click on refresh button crashes VS when folder path is empty

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2444]

**Comment by luisquintanilla** [comment]
Quick Fix: Disable refresh button when folder path is empty.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.3.2307701.
![image](https://user-images.githubusercontent.com/99375895/215449747-7870a325-e99e-472a-a15f-f20c6fd25ec7.png)
