### ISSUE TITLE
Formatting and comments for generated training code 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2445]
1. There should be newlines between these methods... 

![image](https://user-images.githubusercontent.com/9122518/211925452-6daeab9a-c415-4749-8fba-8d6153b199ab.png)

2. This comment for Train() and SaveModel() methods should now say ".mlnet" instead of zip 
`/// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>`

3. Method signature for LoadIDataViewFromDatabase shouldn't have the comment about sql reference 
```
/// <summary>
/// Load an IDataView from a database source.
/// </summary>
```

4. Let's remove the reference to loading data from the RetrainModel summary and instead put it in the LoadData summary. 
LoadData
```
        /// <summary>
        /// Load an IDataView from a database source. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
```

RetrainModel: 
```
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process.
        /// </summary>
```

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.2.2306903.
1. 
<img width="858" alt="image" src="https://user-images.githubusercontent.com/99375895/213659962-276bcd54-1006-4d76-9df7-65a3a2e03cc4.png">
2. 
![image](https://user-images.githubusercontent.com/99375895/213660584-65be6a66-ad7e-415d-bae1-86e2c41d87fe.png)
3.
<img width="790" alt="image" src="https://user-images.githubusercontent.com/99375895/213661341-d02671f1-e87b-492f-9e54-1d868b1bd9ce.png">
4.  
<img width="590" alt="image" src="https://user-images.githubusercontent.com/99375895/213662463-878db9ff-101d-41e2-9e4a-69b00cfece78.png">
