### ISSUE TITLE
TextClassification trainer spell error

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2446]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): main
 - Visual Studio Version: VS2022
<img width="272" alt="image" src="https://user-images.githubusercontent.com/16876986/211926092-f397e4d9-0a9a-462d-942f-a877b233b850.png">

Should be `TextClassification`

This bug is caused by a spell error in ml.net, which has been fixed in nightly build. We just need to update mlnet to introduce the fix

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.3.2307701.
![image](https://user-images.githubusercontent.com/99375895/215707784-9fe6dc44-11ad-47a5-b91d-1a218b1d04cf.png)
