### ISSUE TITLE
SlotNames comment should be updated

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2447]
Let's update the comment about slot names... 

![image](https://user-images.githubusercontent.com/9122518/211926939-0a6ee70f-4098-4351-8d02-d7719a213774.png)

This should work... 

```
            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value. 
            var keyNames = new VBuffer<string>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
```

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.2.2306903.
<img width="801" alt="image" src="https://user-images.githubusercontent.com/99375895/213657070-32e01865-d7d1-4763-9158-b52f5e62567e.png">
