### ISSUE TITLE
Add "Predict" method back instead of only PredictAllLabels

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2449]
We've changed Predict to PredictAll Labels. Now our generated code snippet doesn't work. 

![image](https://user-images.githubusercontent.com/9122518/212121941-19854fed-48d5-46a3-ac73-4d06cbb035bb.png)

**Comment by beccamc** [comment]
Alternatively we could update the generated code snippet to "PredictAllLabels". @JakeRadMSFT I think when we spoke about this you wanted to keep the predict method?

**Comment by luisquintanilla** [comment]
Predict method to be added back in.

**Comment by zewditu** [comment]
Instead of having both predict and PredictAllLabels why do we rename  PredictAllLabels to Predict?  PredictAllLabels might be more intuitive than predict how ever it is obvious to predict all labels.

**Comment by beccamc** [comment]
@JakeRadMSFT Can you remind why you wanted to keep the Predict method with just the result?
