### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error	CS0246	The type or namespace name 'ValueTask' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by sdnyanesh352** [dotnet/machinelearning-modelbuilder#2451]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_ 2019

**Bug description**
I am using 2019 visual studio 4.7.2 dot net

**Steps to Reproduce**
1. _ Feature file ` Feature: YoutubeSeachFeature
	In order to test search functionality on youtube

@scopedNinding
Scenario: youtube should seach for the given keyword and should navigate to search
	Given I have navigated to youtube website
	And I have entered India as search keyword
	When I press the seach button
	Then I sjould be navigate to seach results page`

2. _ `using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using System;
using System.Threading.Tasks;
using TechTalk.SpecFlow;

namespace SeleniumSpecflow.StepBindings
{
    [Binding]

    public class YoutubeSeachFeatureSteps :IDisposable
        
    {
        private String searchKeyword;
        private ChromeDriver chromeDriver;
        public YoutubeSeachFeatureSteps() => chromeDriver = new ChromeDriver();
        [Given(@"I have navigated to youtube website")]
        public void GivenIHaveNavigatedToYoutubeWebsite()
        {
            chromeDriver.Navigate().GoToUrl("https://www.youtube.com");
            Assert.IsTrue(chromeDriver.Title.ToLower().Contains("youtube"));
        }
        
        [Given(@"I have entered (.*) as search keyword")]
        public ValueTask GivenIHaveEnteredIndiaAsSearchKeyword(String searchString)
        {
            this.searchKeyword = searchString = searchString.ToLower();
            var searchInputBox = chromeDriver.FindElement(By.Id("search"));
            var wait = new WebDriverWait(chromeDriver, TimeSpan.FromSeconds(2));
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("search")));
            searchInputBox.SendKeys(searchKeyword);
            return new ValueTask();
        }

       

        [When(@"I press the seach button")]
        public void WhenIPressTheSeachButton()
        {
            var searchButton = chromeDriver.FindElement(By.XPath("/html/body/div[1]/div[3]/form/div[1]/div[1]/div[4]/center/input[1]"));
            searchButton.Click();
        }
        
        [Then(@"I sjould be navigate to seach results page")]
        public void ThenISjouldBeNavigateToSeachResultsPage()
        {
            //System.Threading.Thread.Sleep(2000);
            Assert.IsTrue(chromeDriver.Url.ToLower().Contains(searchKeyword));
        }
        public void Dispose()
        {
            if (chromeDriver != null)
            {

                chromeDriver.Dispose();
                chromeDriver = null;
            }
        }
    }
}
`

**Expected Experience**
_A It should launch chrome and open youtube and search for india ._

**Actual Experience**
_getting this error 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ValueTask' could not be found (are you missing a using directive or an assembly reference?)	SeleniumSpecflow	C:\Users\dnysom6w\source\repos\SeleniumSpecflow\SeleniumSpecflow\obj\Debug\NUnit.AssemblyHooks.cs	23	Active
._

**Comment by luisquintanilla** [comment]
Hi @sdnyanesh352,

Is this issue with [ML.NET Model Builder](https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet/model-builder)?

**Comment by luisquintanilla** [comment]
@sdnyanesh352

Closing this issue as it does not appear to be related to ML.NET or Model Builder.
