### ISSUE TITLE
Terminology for sentence similarity "label" 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2452]
I'm confused by the terminology used for sentence similarity columns. Specifically the term "label" doesn't make sense to me here. Maybe changing to "Column to predict (relevance)" Or another word? 

![image](https://user-images.githubusercontent.com/9122518/213298450-46ad4e50-d0f5-4ef9-b544-3b4eff0f399b.png)

**Comment by beccamc** [comment]
@luisquintanilla for comments

**Comment by zewditu** [comment]
@luisquintanilla could suggest tooltip text?


![Image](https://user-images.githubusercontent.com/36615490/214230078-b0c0b7d1-c1a6-43b1-9eb3-9182902920ed.png)

**Comment by zewditu** [comment]
For the source and comparison sentence there are my suggestion , open to any comment. 
## Source sentence
" Sentence compared against the comparison sentence. "
## Caparison sentence
 "Source sentence compared how similar to it."

**Comment by beccamc** [comment]
@zewditu Do you still need strings here?

**Comment by zewditu** [comment]
@luisquintanilla  @beccamc  if you are ok with the above text, they are already in

**Comment by luisquintanilla** [comment]
@beccamc @zewditu looking at this some more, what are the thoughts around using these names for the columns?

Source -> Sentence 1
Comparison -> Sentence 2

Something like this (excuse my Paint skills)

![image](https://user-images.githubusercontent.com/46974588/217356081-9d2637a3-2b3c-4548-ab64-fc2ea1c47d6f.png)


A few reasons for this:

1. The order of these doesn't matter. All that matters is you have two text columns you will be comparing.
2. I believe in the API it's called sentence1ColumnName and sentence2ColumnName.

**Comment by zewditu** [comment]
yes,  the ApI parameters are called  sentence1ColumnName and sentence2ColumnName, however we adopted "Source Sentence  "and "Comparison sentences" form [Hugging face](https://huggingface.co/tasks/sentence-similarity).

For me Luis's proposal also works.
@luisquintanilla  just to confirm no tooltip for setence1 and sentence 2, right?

**Comment by luisquintanilla** [comment]
@zewditu I think no tooltip for the individual sentences makes sense. I don't think they'd add any additional / more useful information other than saying "Sentence to be compared against sentence x" which I don't think is useful. Feel free to push back on that though.

**Comment by luisquintanilla** [comment]
Closing since a PR was merged addressing this issue.
