### ISSUE TITLE
Pearson Correlation needs documentation

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2453]
Sentence similarity used Pearson Correlation us an optimizing metric, However, we do not have any documentation for the user that explains or deals with Pearson Correlation.

**Comment by beccamc** [comment]
@luisquintanilla I moved this to March, but does this need to be in for February?

**Comment by luisquintanilla** [comment]
@beccamc Since it's what we're using as our perf metric this release, let's do it in Feb.
