### ISSUE TITLE
All scenarios: The training results are missing on the Train page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2455]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.2.2306903 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The training results are missing on the Train page.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/weather.zip

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select any scenario.
  5. On Data page, select the data source.6
  6. On the Train page, click "Start training" button to complete the training.
  7. You will see that the training results are missing on the Train page.

**Expected behavior**
The training results should be displayed well.

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/213671452-b665794a-7bfb-42aa-a69b-d2c54d1cf7f8.png)

**Additional context:**
After you saved and re-open the .mbconfig file again, the training results would be displayed well.
![image](https://user-images.githubusercontent.com/99375895/213671806-8291b392-2a6b-468c-b3b9-ab6f106721a1.png)

**Comment by luisquintanilla** [comment]
@v-Hailishi does this only happen on Azure environments or local as well?

**Comment by v-Hailishi** [comment]
@luisquintanilla This issue happens on all scenarios (happen on both of Azure and local environments).

**Comment by beccamc** [comment]
I'm not seeing this anymore. Are you @v-Hailishi?  I can investigate further if you are. 
![image](https://user-images.githubusercontent.com/9122518/218187552-aad6d28f-daa2-48c6-897e-070da9975403.png)

**Comment by v-Hailishi** [comment]
The bug is still repro on the latest main build 17.14.3.2311302.
![image](https://user-images.githubusercontent.com/99375895/218669157-6e5d7cdb-454b-41f9-8977-4dd26cbbdb5c.png)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.4.2316701.
![image](https://user-images.githubusercontent.com/99375895/226317193-b106879d-bca4-407c-b966-0662000a8d31.png)
