### ISSUE TITLE
The graphic used for "Sentence similarity" are the same graphic used for "Image classification".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2461]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.3.2307701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The graphic used for sentence similarity are the same graphic used for image classification.

**Data Source**

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Check the graphic used for "Sentence similarity".

**Expected behavior**
Should use the new graphic for "Sentence similarity".

**Screenshots**
![image](https://user-images.githubusercontent.com/99375895/215408338-074384bd-90ab-4845-800f-18fc55a3466c.png)

**Additional context:**
Need add the new scenario to the doc link https://learn.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-model-builder#which-machine-learning-scenario-is-right-for-me

**Comment by luisquintanilla** [comment]
Hi @v-Hailishi,

Thanks for reporting this. This is a placeholder for now. When we get the icons in the next few days we'll replace with the correct one. Closing this issue for now.
