### ISSUE TITLE
Sentence similarity: The Console App and Web API projects are generated failed on the Consume page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2463]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.3.2307701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The Console App and Web API projects are generated failed on the Consume page.

**TestMatrix**
[home-depot-sentence-similarity-small.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10534387/home-depot-sentence-similarity-small.csv)

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Sentence similarity"** scenario and data source to complete the training.
  5. Go to the Consume page, click "Add to solution" button to generate Console App and Web API projects.
  6. This time Console App and Web API projects can be generated successful.
  7. **Close and re-open .mbconfig file.**
  8. Go to the Consume page, click "Add to solution" button to generate Console App and Web API projects.
  9. This time Console App and Web API projects are generated failed.
  
**Expected behavior**
The Console App and Web API projects should be generated successful on the Consume page.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/215444488-515b27ff-b3b3-4ea0-b063-75297fe7e20b.png)

**Additional context**

**Comment by zewditu** [comment]
@v-Hailishi  have you trained a new model or used an existing trained model?

**Comment by v-Hailishi** [comment]
@zewditu When I completed the training and go to the Consume page, Console App and Web API projects can be generated successful.
But once you close and then re-open .mbconfig file, Console App and Web API projects would be generated failed.

**Comment by zewditu** [comment]
@v-Hailishi  thanks  for tried it , the fix for it is  out , not yet checked in

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.3.2310301
![image](https://user-images.githubusercontent.com/99375895/216943022-288fc402-694c-447b-874b-2326523985e5.png)
