### ISSUE TITLE
Forecasting: The drop-down list is blank after choosing the data source on the Data page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2467]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.3.2307701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The drop-down list is blank after choosing the data source on the Data page.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Forecasting"** scenario and on the Data page, choose the data source.
  5. Choose the column to predict, then you will see that drop-down list is blank.
  
**Expected behavior**
The drop-down list content should be displayed normally.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/215641392-e7eb8a3b-da92-419e-a597-421ea74ec408.png)

**Additional context**

**Comment by beccamc** [comment]
@v-Hailishi is this a consistent issue? When you re-opened the Column to predict dropdown was the list populated? In other words, did it just take a bit to load?

**Comment by v-Hailishi** [comment]
@beccamc No matter how many times I re-opened the column to predict, the dropdown is always blank

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.3.2310902
<img width="357" alt="image" src="https://user-images.githubusercontent.com/99375895/218061013-4c880e7e-67bf-47c5-a50b-fcc48d85b20b.png">

**Comment by JBGitHub11** [comment]
I'm seeing this same issue today
