### ISSUE TITLE
Text classification: The generated console app project is running failed with error "Fallback to CPU is false but no GPU detected.".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2468]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.3.2307701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The generated console app project is running failed with error "Fallback to CPU is false but no GPU detected.".

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Text classification"** scenario and data source to complete the training.
  5. Go to the Consume page, click "Add to solution" button to generate Console App project.
  6. Run the generate Console App project.
  
**Expected behavior**
The generated console app project should be running successfully.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/215684099-123d9b8a-9d7a-4838-9291-c7f8dd475c76.png)

**Additional context**
The generated Web API project can be running successfully.

**Comment by zewditu** [comment]
How GPU is not detected  because  the generated code is using a GPU trained model?

- @v-hailishi  are you using a different machine to run console app?
- Or  framework issue ?
@LittleLittleCloud , @JakeRadMSFT , @luisquintanilla  thought on this?

**Comment by v-Hailishi** [comment]
@zewditu I used the same machine to run console app, this error only repro on **Text classification** scenario.
Besides, this model was trained on CPU.

**Comment by zewditu** [comment]
@v-Hailishi  thanks  if this is trained with CPU the problem is with code template.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.3.2310301
<img width="518" alt="image" src="https://user-images.githubusercontent.com/99375895/216934015-ba7ceb69-815d-4cef-9acc-9a649829aba4.png">
