### ISSUE TITLE
Data Preview fails when SQL Server input table schema is not dbo

### ISSUE THREAD

**Issue by dporterf** [dotnet/machinelearning-modelbuilder#247]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1909.2101
 - Visual Studio Version 15.9.13

**Describe the bug**
Data Preview fails when SQL Server input table schema is not dbo

**To Reproduce**
1. Go to '2. Data'
2. Click on 'Input and choose SQL Server'
3. Click on 'Table Name' and choose a table that you know does not have a database schema of dbo
4. See error in screenshot.

**Expected behavior**
Data Preview will work.

**Screenshots**
![image](https://user-images.githubusercontent.com/18315597/65557356-e3aba780-dee7-11e9-89ef-d1c719d95f47.png)

**Comment by JakeRadMSFT** [comment]
Try to continue gracefully - if it isn't expensive.
Fall back if "difficult" - error message

**Comment by Alex-Torres** [comment]
Experiencing the same problem @dporterf  reported.

**Comment by beccamc** [comment]
Validated with guest schema
