### ISSUE TITLE
Zip files are no longer being generated.

### ISSUE THREAD

**Issue by gbanuk2** [dotnet/machinelearning-modelbuilder#2482]
I upgraded to the latest version of mlnet and it's no longer producing a .zip file with the training data. It used to put a .zip file of the model in the output directory that could then be used for predictions. 

C:\pubtemp\training>mlnet --version
16.14.3+6339da337d983ad1fdc2f07f36f9a4dec448ece8

Command I'm using: 
mlnet classification --dataset "Material.csv" --label-col 1 --name "Material" --train-time 15

The output directory:
02/10/2023  01:49 PM             4,998 Material.consumption.cs
02/10/2023  01:49 PM               785 Material.csproj
02/10/2023  01:49 PM             4,333 Material.mbconfig
02/10/2023  01:49 PM           730,288 Material.mlnet
02/10/2023  01:49 PM             5,259 Material.training.cs
02/10/2023  01:49 PM             1,276 Program.cs

**Comment by beccamc** [comment]
The .mlnet file generated has replaced the zip. It works exactly the same and the generated code should reference it.

**Comment by gbanuk2** [comment]
ah ok, i guess this isn't an issue then.

**Comment by beccamc** [comment]
@gbanuk2 Did something not work? Or you were just expecting to see the zip (as usual) and didn't realize the .mlnet had replaced it? Very reasonable that you didn't know this was different.

**Comment by gbanuk2** [comment]
We have a process that automatically copies the .zip files when done training the data. It broke after upgrading mlnet because the zip files no longer existed. I can simply change the extension of the files it's looking for though as long as the contents are the same.
