### ISSUE TITLE
model builder should allow for me to get the model directly

### ISSUE THREAD

**Issue by scottfavre** [dotnet/machinelearning-modelbuilder#2486]
**Is your feature request related to a problem? Please describe.**

When iterating on an ML model (e.g., tweaking training data or column definitions), there's no way to just save the model to an existing project or overwrite a previously saved model:

![image](https://user-images.githubusercontent.com/150353/218559055-900ce0f5-e823-4103-8dd8-2f83b0043dc3.png)

**Describe the solution you'd like**
It would be nice to be able to just save the model the way it was saved last time, without having to create a new project.

**Comment by beccamc** [comment]
@scottfavre In our most recent [release](https://github.com/dotnet/machinelearning-modelbuilder/blob/main/docs/release-notes/16.14.2.md) we changed the model extension from .zip to .mlnet. Is that the problem you're experiencing here?

**Comment by scottfavre** [comment]
Oh hah. My mistake. If I had expanded the model node in the solution explorer I would have seen that the model is right there:

<img width="134" alt="image" src="https://user-images.githubusercontent.com/150353/218759514-e59f51ad-01a5-43d8-b4b5-866eb606b4fb.png">

Thanks, closing this issue,
