### ISSUE TITLE
Save button in advanced data options is enabled by default without any change

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2487]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**
1. Go to any advanced data option supported scenario
2. Go to the data page and uploaded the dataset.
3. Click on the advanced data option link.

**Expected behavior**
Save button should be disabled as long as there is no update 
**Screenshots**

https://user-images.githubusercontent.com/36615490/223355650-a6168ef3-c4b7-4acb-a114-d2da4750b09b.mp4

**Additional context**

**Comment by luisquintanilla** [comment]
@zewditu can you please add more details when you get a chance. Thanks.

**Comment by zewditu** [comment]
Added  to steps to reproduce section

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.4.2316301.
![image](https://user-images.githubusercontent.com/99375895/224869384-6d6bda08-46b2-42d3-beac-c1f0f01227de.png)
