### ISSUE TITLE
TorchSharp versions mismatch in output window.

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2488]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 17.14.3.2311302
 - Visual Studio Version: VS2022 17.4.4

**Describe the bug**

When training a scenario that uses TorchSharp, there is a mismatch in the output window between the version that's installed and the version displayed after training.

**Installing**

`2023-02-13 17:22:06.2356 DEBUG C:\Users\luquinta.REDMOND\AppData\Local\Temp\ModelBuilder\torchsharp-cuda.0.98.3+1.11.0.1\obj`

**After Training** 

`2023-02-13 17:25:37.2029 INFO Installing nuget package, package ID: TorchSharp-cuda-windows, package Version: 0.98.1 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)`

**To Reproduce**

Train a Sentence Similarity model using local GPU environment.

**Expected behavior**

The output should display the same version.

**Additional context**

[Log MLModel1-7EINXS.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/10735859/MLModel1-7EINXS.txt)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.4.2312404
![image](https://user-images.githubusercontent.com/99375895/221504298-39058ce7-a478-4931-b418-09e46b4228c8.png)
