### ISSUE TITLE
djones 

### ISSUE THREAD

**Issue by Djonesr** [dotnet/machinelearning-modelbuilder#2490]
Model Builder currently supports two data sources, local files (.csv and .tsv) and SQL tables. We understand your data is in many different places and shapes. We'd like to understand where your data comes from so we can better support your scenario in Model Builder.

**Where is your data located?**
A clear and concise description of where you data is. i.e. Local json file, Cosmos DB,  [...]

**What does your data look like?**
A clear and concise description of what format your data is in. Is it tabular? Is it in JSON format? 

**Does your data require transformations?**
A clear and concise description of the state of your data. Does it have many missing values? Is much of it irrelevant? 

**Example**
If possible, a small example of your data (inline or attached file).

**Additional context**
Add any other context or information you'd like to give us.

**Comment by beccamc** [comment]
Sorry, I'm not sure about the feedback here. Please add more details and I will reopen.
