### ISSUE TITLE
report bug in vs

### ISSUE THREAD

**Issue by Djonesr** [dotnet/machinelearning-modelbuilder#2492]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
Sorry, I don't have enough information to investigate this issue. Please add more details and I will reopen.
