### ISSUE TITLE
Sentence similarity: The placeholder string "Select column" is missing for drop-down list under "Sentence 2" option on the Data page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2495]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.3.2311403 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The placeholder string "Select column" is missing on the Data page.

**TestMatrix**
[home-depot-sentence-similarity-small.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10534387/home-depot-sentence-similarity-small.csv)

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Sentence similarity"** scenario.
  5. On Data page, choose the data source and select the column for three options like below.
![image](https://user-images.githubusercontent.com/99375895/218961971-1c5e7d61-4631-413f-b8b8-00bf7507540a.png)
  6. Choose "search_term" column as **Sentence 1**.
  7. Then you will see that the placeholder string "Select column" is missing for drop-down list under "Sentence 2" option.
  
**Expected behavior**
The placeholder string "Select column" should be displayed well for drop-down list under "Sentence 2" option.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/218963737-d68b8581-b443-400e-adf7-e558f5d4fded.png)

**Additional context**

**Comment by zewditu** [comment]
I am not able to reproduce it  in the latest main 

![Image](https://user-images.githubusercontent.com/36615490/223597830-99a9f563-c209-458c-9cc4-5ecacae52ae8.png)

**Comment by v-Hailishi** [comment]
@zewditu You can get the repro steps from blew gif:
![#2495](https://user-images.githubusercontent.com/99375895/223680893-8137ce7e-f7e2-43f7-a2ea-84fb5cdb0e3d.gif)

**Comment by zewditu** [comment]
@v-Hailishi  got it! thanks

**Comment by zewditu** [comment]
Could you test with latest main ?

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.4.2316401.
![image](https://user-images.githubusercontent.com/99375895/225249718-349d8a94-cbcb-4f85-a0f4-34712145b0d9.png)
