### ISSUE TITLE
All scenarios: Evaluate failed with error "Could not find a part of the path '...\MLModel.mlnet'" when using the model cloned from GitHub.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2496]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.3.2311403 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.4)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Evaluate failed with error "Could not find a part of the path '...\MLModel.mlnet'" when using the model cloned from GitHub.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select any scenario.
  5. On the Data page, choose the data source to complete the training.
  6. Save All Files, then create a new repository and push to GitHub.
  7. **Check out to different computer or virtual machine**.
  8. Open the cloned Model Builder and go to Evaluate page.
  9. Click "Predict" button, then you will see that evaluate is failed.

**Expected behavior**
Evaluate should be successful.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/218985190-33fb0a85-6add-4f2c-883b-880d83a35801.png)

**Additional context**
https://github.com/v-Hailishi/Data-classification-Bug

**Comment by LittleLittleCloud** [comment]
This is expected, as we still record full-path for model file. However you can fix it by manually change the model path to relative path of .mbconfig file

**Comment by v-Hailishi** [comment]
The bug can be fixed by manually change the model path to relative path of .mbconfig file.
