### ISSUE TITLE
mlnet possible memory leak

### ISSUE THREAD

**Issue by soenneker** [dotnet/machinelearning-modelbuilder#2497]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.14.3

**Describe the bug**
I'm running a training command (`mlnet train --training-config redacted.mbconfig -v diag`) using linear regression and it's consuming unlimited amounts of memory as the job continues.

This is causing my Azure ML cluster instance (Linux) to run out of memory. I've replicated this locally on my Windows workstation.

It will deallocate some memory after a trial, but not the full amount. For example:

Trial 1: 0GB -> 2GB
Trial 2: 1GB -> 4GB
Trial 3: 2GB -> 7GB
Trial 4: 6GB -> 14GB
...

If I run this process for an hour it will eat all 32GB of the AML instance before the end pretty easily.

This is during trial 5:
![image](https://user-images.githubusercontent.com/4441470/219133433-1a08690f-8a29-45cd-8b63-f88a7469d43b.png)

![image](https://user-images.githubusercontent.com/4441470/219133596-64c30d34-bffb-4a81-b11e-d2885509b5ee.png)

The data I'm using is not a large amount, it's only 80k rows (~3MB) with 5 columns. I'm using only LightGBM which I suspect could be a source of the issue. The data set works well for LightGBM, with fairly accurate predictions, so I'd prefer to stick with that.

I can understand LightGBM needs enormous amounts of memory - but is it possible to simply stop the experiment early if it's detected that the memory needs of the algorithm are greater than the hardware can supply?

Are there any knobs or levers I can adjust to reduce the memory consumption? Obviously reducing the runtime of the job is one, but I'd like a more resilient solution as the data changes since this is automated.

Thanks!

**Comment by LittleLittleCloud** [comment]
Thanks for reporting that, right now with mlnet-cli there's no way to limit memory usage, but with AutoML.Net it allows you to limit memory usage for each trial. AutoML.Net powers mlnet-cli on automl training.

You can find more details in this link:
https://github.com/dotnet/machinelearning/pull/6305

In the meantime, You are right that LightGbm consumes tons of memory, and the default search space for LightGbm is also very large, which in some way also make things worse. So another way to avoid OOM error is to use a smaller search space for LightGbm, which you can refer to this [link](https://github.com/dotnet/machinelearning/issues/6465#issuecomment-1335148576) on how to

**Comment by soenneker** [comment]
Thanks for the info @LittleLittleCloud. I'm assuming there isn't a way to configure any of this within the .mbconfig, correct?

I'm utilizing the mlnet cli to leverage AML, and without the ability change this within the config it seems like there may not be a solution. Is that right?

**Comment by LittleLittleCloud** [comment]
Well if you are using commandJob for your mlnet cli, there's large chance that you can run AutoML.Net directly as well

Here's an example
https://github.com/LittleLittleCloud/CUP98

**Comment by luisquintanilla** [comment]
Thanks for reporting this @soenneker and @LittleLittleCloud for looking into it.

Since a workaround has been suggested and issue #2507 is looking into addressing this issue, I'm closing this one. @soenneker please follow any progress on that issue.
