### ISSUE TITLE
Visual Studio cannot find Machine Learning Workspace

### ISSUE THREAD

**Issue by ktravelet** [dotnet/machinelearning-modelbuilder#2498]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.4.2151101
 - Visual Studio Version: Enterprise 2022 - Preview, Version 17.3.0 Preview 2.0

**Describe the bug**
- Model Builder says "The subscription does not contain any Azure Machine Learning workspaces", however there is one

**To Reproduce**
- Following: https://learn.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder
- I created a Machine Learning Workspace using the Model Builder "new" button
- The resources all are created in Azure Portal (see screenshot below)
- Try and select the newly created Azure Machine Learning workspace

**Expected behavior**
Model Builder should see and allow to select the newly created Azure Machine Learning workspace

**Screenshots**
![image](https://user-images.githubusercontent.com/14185506/219229676-7206e0e1-5d63-4961-b478-e3d54eb07780.png)
![image](https://user-images.githubusercontent.com/14185506/219229788-4425e6d0-73f3-487a-bfbc-ad711c3ca3d1.png)

**Comment by LittleLittleCloud** [comment]
It's might be delaying? Does this issue still exists after 5 days?

**Comment by ktravelet** [comment]
It's working now on my side. I'm getting extremely inconsistent delayed times. Sometimes it picks it up near instantly while other times it just don't seem to work.

**Comment by zewditu** [comment]
@ktravelet  if you still hit this issue, feel free to open it.
