### ISSUE TITLE
Sentence similarity: Training failed with error "Package restore failed." when installing package "Microsoft.ML.TorchSharp".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2499]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.3.2311501 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.5)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training failed with error "Package restore failed." when installing package "Microsoft.ML.TorchSharp".

**TestMatrix**
[home-depot-sentence-similarity-small.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10534387/home-depot-sentence-similarity-small.csv)

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Sentence similarity"** scenario.
  5. On Data page, choose the data source and select the column for three options.
  6. Click "Start training" button on the Train page.
  
**Expected behavior**
Training successful.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/219288079-1a1499c5-a13f-4a2f-939b-b4d2bdf418bf.png)

**Additional context**
The bug is also repro on "**Text classification**" scenario.
![image](https://user-images.githubusercontent.com/99375895/219288271-6927168e-d8fe-4596-b128-689854ed89b1.png)

**Comment by LittleLittleCloud** [comment]
Package version for `Microsoft.ML.TorchSharp` should be 0.21.0.

**Comment by luisquintanilla** [comment]
@v-Hailishi can you please validate this has been fixed. Thanks

**Comment by v-Hailishi** [comment]
The bug has been fixed in the latest main build 17.14.3.2312303.
<img width="317" alt="image" src="https://user-images.githubusercontent.com/99375895/221128954-9e4b067b-54d5-4a5d-a85e-3fe2be1fef6f.png">
<img width="356" alt="image" src="https://user-images.githubusercontent.com/99375895/221129015-07eb8e17-06e3-42ba-a848-ea2c83554ece.png">
