### ISSUE TITLE
Fix reset state when options/ pages are changed

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#25]
Data screen was still loaded

![image](https://user-images.githubusercontent.com/1132652/57162048-fccd8380-6da1-11e9-9e35-175d76543677.png)

**Comment by LittleLittleCloud** [comment]
@rustd the reload seems to work fine on my machine, can you show more info about how to reproduce it?

**Comment by greazer** [comment]
@rustd, please provide details per @LittleLittleCloud then assign back to him (if necessary)

**Comment by rustd** [comment]
Repro steps:
1. Launch Model Builder
2. Select Sentiment Analysis
3. Upload a csv file
4. See Data Preview loaded with the data in the datagrid
5. Go back to Scenario screen
6. Select Issue classification
7. Goto Data tab

Expected
Data Preview should be empty

Actual
Data preview has the grid
![image](https://user-images.githubusercontent.com/1132652/59709690-36284a00-91bc-11e9-8cca-c3abea931e41.png)
