### ISSUE TITLE
I wasn't able to download the program or open it.

### ISSUE THREAD

**Issue by xavvvvi** [dotnet/machinelearning-modelbuilder#2502]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
Can you give more information on the issue you have.

**Comment by zewditu** [comment]
We are not able to  look into the issue b/c we do not have enough information
