### ISSUE TITLE
Add more advanced training option

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2507]
- `MaximumMemoryUsageInByte`
- `Tuning algo` (smac | cfo | eci-cfo | random | grid | auto-zero )
- max-model

Also, adding a summary section in training option to reveal those options will be helpful

#1666

**Comment by luisquintanilla** [comment]
Already in API, needs to be exposed in advanced training options.

**Comment by luisquintanilla** [comment]
Scenarios: 

- Tuner (smac | cfo | eci-cfo | random | grid)
  - Tabular scenarios
- AutoZero
  - Deep Learning Senarios
- MaximumMemoryUsageInByte
  - All scenarios (tabular to benefit from it most)
- max-model
  - All AutoML scenarios
  - DL defaults to 1.

**Comment by LittleLittleCloud** [comment]
Tab head for advanced training option
- Tuner
 - tuner
- Stop strategy
 - Max model
 - MaximumMemoryUsageInByte
- Sample strategy
 - start from subsample (only available for train-validation split or validation file split)

**Comment by luisquintanilla** [comment]
@luisquintanilla to sign off on UI.

**Comment by luisquintanilla** [comment]
Keeping this open to rework some of these descriptions. 



![Image](https://github.com/dotnet/machinelearning-modelbuilder/assets/46974588/4a3319e0-4fe1-4297-9991-afde97e164ee)

**Comment by luisquintanilla** [comment]
Validated
