### ISSUE TITLE
"Package restore failed" in following the ML.NET tutorial

### ISSUE THREAD

**Issue by GRawhideMart** [dotnet/machinelearning-modelbuilder#2509]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: Model Builder 17.14.3.2310103
 - Visual Studio Version (if applicable): 2022

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: The training process cannot finalize, because it throws an error "Packages restore failed"

**To Reproduce**
1. Open Visual Studio
2. Setup a new empty project with template "C# console app"
3. Add a Machine Learning Model
4. Follow the wizard (as described in the tutorial)
5. When traning finalizes, see error

**Expected behavior**
Error dialog not to appear. The training ends and I can see a model, however I cannot be sure it is the right one since I can't know the implications of this error.

**Screenshots**
![image](https://user-images.githubusercontent.com/62698128/220957619-1c0b1923-bb1e-4368-9cd5-cfb5def9dae5.png)

**Additional context**
I am a beginner in C# and .NET, so it is possible this problem has an elementary solution.

**Comment by LittleLittleCloud** [comment]
The error indicates that model builder fails to install Microsoft.ML 2.0.0 in your project. The fail reason can be various: doens't connect to right feed/internet connection...  It's not a fatal error and you can always install Microsoft.ML 2.0.0 manually as a workaround

**Comment by luisquintanilla** [comment]
@LittleLittleCloud is there anything that needs to be done on our end for this issue?

**Comment by LittleLittleCloud** [comment]
@luisquintanilla Not on the end of ModelBuilder on my point of view. Internet connection / wrong feed configuration are the most likely cause of this restoration failure

**Comment by luisquintanilla** [comment]
Sounds good. Closing this issue then since it doesn't appear to be a Model Builder issue. Thanks.

@GRawhideMart if you run into additional problems, feel free to raise another issue.
