### ISSUE TITLE
Cannot run Arm64 version on Mac OS with M1/.net 7

### ISSUE THREAD

**Issue by rmagruder** [dotnet/machinelearning-modelbuilder#2512]
Followed instructions to install and run the ML.NET Tooling on MacOS on an M1 MacBook Pro with .net 7 installed.

dotnet tool install -g mlnet-osx-arm64 

Tools directory '/Users/randy.magruder/.dotnet/tools' is not currently on the PATH environment variable.
If you are using zsh, you can add it to your profile by running the following command:

cat << \EOF >> ~/.zprofile
# Add .NET Core SDK tools
export PATH="$PATH:/Users/randy.magruder/.dotnet/tools"
EOF

And run `zsh -l` to make it available for current session.

You can only add it to the current session by running the following command:

export PATH="$PATH:/Users/XXXXXXXXXXX/.dotnet/tools"

You can invoke the tool using the following command: mlnet
Tool 'mlnet-osx-arm64' (version '16.14.3') was successfully installed.
 ~ % ~/.dotnet/tools/mlnet                   

Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/XXXXXXXXXXXX/.dotnet/tools/.store/mlnet-osx-arm64/16.14.3/mlnet-osx-arm64/16.14.3/tools/net6.0/any/mlnet-osx-arm64.dll'. An attempt was made to load a program with an incorrect format.

File name: '/Users/XXXXXXXXXXXX/.dotnet/tools/.store/mlnet-osx-arm64/16.14.3/mlnet-osx-arm64/16.14.3/tools/net6.0/any/mlnet-osx-arm64.dll'
zsh: abort      ~/.dotnet/tools/mlnet

**Comment by LittleLittleCloud** [comment]
Hi @rmagruder I have some trouble reproducing the issue you have on M1/.net6. My assumption is you don't have dotnet 6.* installed on your system?

**Comment by luisquintanilla** [comment]
Tutorial merged.

**Comment by rmagruder** [comment]
I will try again!
