### ISSUE TITLE
Data classification&Value predication&Recommendation&Forecasting&Text classification&Sentence similarity: Training failed.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2514]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.4.2315101 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.5)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training failed for Data classification&Value predication&Recommendation&Forecasting&Text classification&Sentence similarity scenarios.

**TestMatrix**
[home-depot-sentence-similarity-small.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10534387/home-depot-sentence-similarity-small.csv)

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Data classificatio or Value predication or Recommendation or Forecasting or Text classification or Sentence similarity"** scenario.
  5. On Data page, choose the data source.
  6. Click "Start training" button on the Train page.
  
**Expected behavior**
Training successful.

**Screenshot**
Data classification:
![image](https://user-images.githubusercontent.com/99375895/222317492-ab75072c-b4be-46fb-b11d-750fdc6cdad4.png)

Value predication & Recommendation & Forecasting & Text classification & Sentence similarity:
![image](https://user-images.githubusercontent.com/99375895/222317573-03b392f9-6e50-4ff7-9f90-e73a4cdcdd68.png)

**Additional context**
The bug is not repro for Image classification and Object detection scenarios.

**Comment by zewditu** [comment]
@v-Hailishi  the main is now broken by ongoing work to enable the validation dataset selection.
I will let you know when things are done.

**Comment by v-Hailishi** [comment]
The bug is still repro on the latest main build 17.14.4.2315701.

**Comment by zewditu** [comment]
@v-Hailishi  thanks for your patience , you can test it now

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.4.2316001(The failed build [#20230310.1 • quick fix for main break (#1698)](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7450575&view=results)).
![image](https://user-images.githubusercontent.com/99375895/224623148-a63f00e4-839d-4342-a338-a928d79d598f.png)
