### ISSUE TITLE
ML dotnet on linux doesn't work

### ISSUE THREAD

**Issue by ionutzzzzz** [dotnet/machinelearning-modelbuilder#2516]
I try to use the 'mlnet' command from the linux terminal, but I get the "command not found" error. I have already installed the tool using dotnet but I can't solve the problem with the path. Personally, I like to use Parrot os (debian distribution).

**Comment by luisquintanilla** [comment]
Hi @ionutzzzzz 

I assume that this might be because you need to give the ML.NET CLI executable permissions. Something like 

```bash
chmod +x /path/to/mlnet
```

Or calling it with the full path 

```bash
~/.dotnet/tools/mlnet
```

**Comment by luisquintanilla** [comment]
Closign since this has already been added to the documentation and tutorials.
