### ISSUE TITLE
Image Classifier is significantly more accurate when trained with CPU vs GPU

### ISSUE THREAD

**Issue by mg-yolo-enterprises** [dotnet/machinelearning-modelbuilder#2517]
Possibly related to #2466 opened by @FaithlessDbo

**System Information:**
 - Windows 11 22H2
 - Model Builder 2022 (17.14.4.2313404)
 - Visual Studio Version: 17.4.3
 - Target Framework Version: 6.0
 - For both CPU and GPU operations: 
   - Microsoft.ML 2.0.0 package
   - Microsoft.ML.Vision 2.0.0 package
 - For CPU operations: 
   - SciSharp.TensorFlow.Redist 2.3.1 package
 - For GPU operations: 
   - SciSharp.TensorFlow.Redist-Windows-GPU 2.3.1 package
   - CUDA 10.1
   - cuDNN 7.6.4
   - NVIDIA driver 531.14 for NVIDIA RTX A2000 Laptop GPU
 
**Describe the bug:**
Model Builder was used to create an image classifier trained on CPU-local. The dataset was comprised of 20,972 total images over 2 categories. **MicroAccuracy was 0.9995** in 4581sec. Scores using this model are almost always >99%. These are really terrific results, but predictions complete in ~200ms which does not meet production requirements for speed.

To achieve faster predictions, a second ML.NET model was attempted to be trained using the same dataset on the same computer, but using GPU-local training. In this case, everything appeared to work as expected without errors, with training completing much faster. However, **the GPU MicroAccuracy achieved was only 0.7312.** This is significantly lower than with the CPU training. Prediction scores using this model are around 50% (usually 52%/48%).

_**Why would a GPU-trained model have a lower accuracy compared to a CPU-trained model using an identical dataset?**_

Please review the screenshots and log files provided below. I'm happy to work with you to reproduce this issue or provide further logging. Thank you!

### CPU Model:

        {
          "Scenario": "ImageClassification",
          "DataSource": {
            "Type": "Folder",
            "Version": 1,
            "FolderPath": "D:\\Data Labeling\\Labeled Dataset 1\\Png"
          },
          "Environment": {
            "Type": "LocalCPU",
            "Version": 1
          },
          "Type": "TrainingConfig",
          "Version": 4,
          "TrainingOption": {
            "Version": 0,
            "Type": "ClassificationTrainingOption",
            "TrainingTime": 2147483647,
            "Seed": 0
          }
        }

![Packages Screenshot](https://user-images.githubusercontent.com/117874236/223312689-8f9383b8-7346-441c-b376-d5c26ba6bb85.png)

![Training Environment Screenshot](https://user-images.githubusercontent.com/117874236/223312734-67ea887b-f7ed-4da3-88fc-c3e877d81ceb.png)

![Data Screenshot](https://user-images.githubusercontent.com/117874236/223312753-ef3fc785-c803-41dc-8f61-4da40f88caab.png)

![Results Screenshot 1](https://user-images.githubusercontent.com/117874236/223312794-e7732ca9-770f-42bb-93e4-9b9441aaf1ca.png)

![Results Screenshot 3](https://user-images.githubusercontent.com/117874236/223312820-c11108a6-f79e-47e7-bdc7-910a038acef0.png)

_**Log File:**_
[MLModel_CPU-81N5HX.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/10905093/MLModel_CPU-81N5HX.txt)

### GPU Model:

        {
          "Scenario": "ImageClassification",
          "DataSource": {
            "Type": "Folder",
            "Version": 1,
            "FolderPath": "D:\\Data Labeling\\Labeled Dataset 1\\Png"
          },
          "Environment": {
            "Type": "LocalGPU",
            "Version": 1
          },
          "Type": "TrainingConfig",
          "Version": 4,
          "TrainingOption": {
            "Version": 0,
            "Type": "ClassificationTrainingOption",
            "TrainingTime": 2147483647,
            "Seed": 0
          }
        }

![Packages Screenshot](https://user-images.githubusercontent.com/117874236/223313353-d4a33a3b-03e0-4f89-bfa0-ba55a9b381ad.png)

![Training Environment Screenshot](https://user-images.githubusercontent.com/117874236/223313378-fd9d91df-fbe6-4613-8f9f-9a0f25889773.png)

![Data Screenshot](https://user-images.githubusercontent.com/117874236/223313397-623787ec-8f32-4ffc-a2fc-a683813048f4.png)

![Results Screenshot 1](https://user-images.githubusercontent.com/117874236/223313410-ca69044a-1850-4000-80d5-64da69fc3516.png)

![Results Screenshot 3](https://user-images.githubusercontent.com/117874236/223313421-89716954-485c-4731-9b3c-a2ef7f9c9eb9.png)

_**Log File:**_
[MLModel_GPU-AWA83L.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/10905122/MLModel_GPU-AWA83L.txt)

**Comment by zewditu** [comment]
@mg-yolo-enterprises   this is very interesting question " Why would a GPU-trained model have a lower accuracy compared to a CPU-trained model using an identical dataset?"
And thank you very much for the detailed information.
@LittleLittleCloud  & @JakeRadMSFT  thoughts ?

**Comment by FaithlessDbo** [comment]
@mg-yolo-enterprises This is indeed what I'm experiencing. Thanks for the mention and the far more detailed version of the issue at hand.

**Comment by LittleLittleCloud** [comment]
I don't have the answer right now, The cause of the difference in training performance between CPU and GPU can be various: a bug in cuda/cudnn, different accuracy in float operation, different initialize seeds... It's difficult to say which exactly could be the possible reason that cause this training performance difference.

It would be helpful if you can provide with us your dataset for reproduction, otherwise we can try reproducing it on other open-source project as well but that might cause more time.

In the meanwhile, the work-around you can try is
- training using larger epoch in GPU training. It requires you to use ML.Net framework as ModelBuilder doesn't allow you to customize epoch number. It would be a lovely feature for deep-learning scenario though @luisquintanilla 
- training using cpu and inferencing using gpu. The model should use the same weight for cpu/gpu training and you can still use gpu for inferencing even if model is trained on cpu
