### ISSUE TITLE
Input Columns / Feature Selection - Combobox does not scroll

### ISSUE THREAD

**Issue by DomG81** [dotnet/machinelearning-modelbuilder#252]
**System Information (please complete the following information):**
 - 16.0.1909.2101
 - Visual Studio 2019

**Bug**
When selecting a file / table with more than 7 columns, there is no way to scroll to select / deselect features, rendering it extremely limiting to say the least.

**To Reproduce**
1. Go to Scenario and select scenario.
2. Click on 'select a file' and select a file with more than 7 columns. I have 33 columns.
3. Select 'Column to Predict'
4. Open Input Columns (Features) selection.
5. Cannot select / deselect / scroll to other columns,

**Expected behavior**
I should be able to select / deselect / scroll to features in the same way as 'Column to Predict'

**Comment by beccamc** [comment]
I've reproduced with over 7 columns of data. @DomG81 Thanks for reporting!

The problem is `<Popup Name="ColumnPopup" ` has a fixed height of 235. We need to add a scrollbar to this.

**Comment by rustd** [comment]
Should we hotfix this one? Customers are reporting this through other channels as well. https://marketplace.visualstudio.com/items?itemName=MLNET.07&ssr=false#qna

**Comment by aslotte** [comment]
I've run into this issue as well. Thank you @DomG81 for reporting it!

**Comment by snympi** [comment]
Similarly I was looking through reports to find a way to report this issue too. Great tool in VS but not being able to deselect features was tedious because I had to fix the data instead. Thanks for a great tool guys!
