### ISSUE TITLE
All scenarios: "Next step" button on the Environment page is disabled, hence we cannot continue the next steps.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2523]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.4.2315802 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.5)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
"Next step" button on the Environment page is disabled, hence we cannot continue the next steps.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select any scenario.
  5. Then go to the Environment page, you will see that "Next step" button is disabled.
  
**Expected behavior**
"Next step" button on the Environment page should be enabled.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/223896207-a1c34d3d-94fa-478a-b3a0-d54ccc9ec7a8.png)

**Additional context**
For **Image classification & Object detection**, if you choose the **Azure** environment, VS would be crashed.
![#2523_1](https://user-images.githubusercontent.com/99375895/223896993-aeba959a-b14f-4521-a483-89479f84fd83.gif)
![#2523_2](https://user-images.githubusercontent.com/99375895/223897012-cd4188b9-1cb3-47c1-b37b-2f063bec5ec4.gif)

**Comment by zewditu** [comment]
It seems that the change in this PR creates these issue  https://github.com/dotnet/machinelearning-tools/pull/1696

**Comment by v-Hailishi** [comment]
The bug is also repro on the latest main build:17.14.4.2315901
![image](https://user-images.githubusercontent.com/99375895/224200521-4bad54de-2df2-4fb3-a59e-2d6023af1804.png)
![image](https://user-images.githubusercontent.com/99375895/224200577-d0c6301f-a5a4-431e-8f5c-6b1b1eb13101.png)

**Comment by v-Hailishi** [comment]
The bug is still repro on the latest main build :17.14.4.2315901

**Comment by zewditu** [comment]
are you on the latest one ? this is the screenshot from the latest main
https://user-images.githubusercontent.com/36615490/224234327-4ebf21ca-0d47-4eee-8e90-4e7586976b03.mp4

**Comment by v-Hailishi** [comment]
The "Next step" button can be enabled, but the "train" cannot proceed after the next step.
![image](https://user-images.githubusercontent.com/99375895/224237787-074bed7d-4485-470c-a4b1-d39e12e618ac.png)

**Comment by zewditu** [comment]
I think our build missed something  from  my end everything looks working ok

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.4.2316001(The failed build [#20230310.1 • quick fix for main break (#1698)](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7450575&view=results)).
<img width="369" alt="image" src="https://user-images.githubusercontent.com/99375895/224622554-00dc1b0f-a03c-4dcd-b47b-1e027c99fa89.png">
