### ISSUE TITLE
Image Classification Data Preview UI fixes

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#253]
- [x]  Bold header text
- [x] Change header background color (Sync with design)
- [x] Make folder less long
- [x] Add scrollbar

**Comment by unescrews** [comment]
Does scrollbar refer to scrolling capabilities for this dropdown? If not, I think a scrollbar here would be highly appreciated.

![image](https://user-images.githubusercontent.com/23142144/65838242-6d50e000-e301-11e9-98f8-405026ecb634.png)
