### ISSUE TITLE
Image classification doesn't work with GPU

### ISSUE THREAD

**Issue by IzzyHibbert** [dotnet/machinelearning-modelbuilder#2530]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  **17.14.4**
 - Visual Studio Version: **Visual Studio Community 2022** 

**Describe the bug**
I already founded that using GPU in Image classification does not work with previous versions of Model Builder. 
Same with latest version 17.14.4 that does not requires GPU extension.
Since the bug I previously reported has been open for 3 months [(here)](https://github.com/dotnet/machinelearning-modelbuilder/issues/2428) with no progress, I hope that this time, by modifying the title of the  bug and shortening the details will help getting a fix asap.

- Clear description of the problem:

**To Reproduce**
1.Select Image Classification Scenario
2.Select GPU as training environment
![Requirements](https://user-images.githubusercontent.com/45388237/224538231-549668c2-a6fd-4095-8718-94fead5662d4.png)
3. Press "Next" and start the training
4. Error comes (2 minutes after it starts)
![Error](https://user-images.githubusercontent.com/45388237/224538432-9c971675-83cf-4a0e-ba33-33cc4b33ea5b.png)
5.Details of the log file
[ID-GPU-833T4G.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/10950550/ID-GPU-833T4G.txt)

**Expected behavior**
It should complete the training successfully

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
Maybe try setting `TF_FORCE_GPU_ALLOW_GROWTH` to true to resolve cudnn_initialize_error?

source: TF_FORCE_GPU_ALLOW_GROWTH

**Comment by IzzyHibbert** [comment]
Dear @LittleLittleCloud 
the hint you suggested

![Env_change](https://user-images.githubusercontent.com/45388237/225386347-c3c92f0b-e5b2-4566-97bd-bd1e61a879a6.jpg)

did not change the result. Still same KO.

See the log:
[error.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/10982724/error.txt)

No I do not have cuda/cudnn more than that. In one of the images I posted above you see that recognizes another graphic card because I am running it on a remote session.

**Comment by IzzyHibbert** [comment]
Yes, this last hint :
`true`
instead of `TRUE` made the trick. 
It now runs smoothly and complete the training in just 4 minutes. Awesome @LittleLittleCloud  , thanks.

Would be good to make it running without this manual addiction. Not sure if possible. Closing this 
THANKS !!

**Comment by LittleLittleCloud** [comment]
@IzzyHibbert 
Glad to see your issue get resolved. And for sure it's possible to set `TF_FORCE_GPU_ALLOW_GROWTH` flag in ModelBuilder. We'll set that flag in the next release of ModelBuilder
