### ISSUE TITLE
Data classification&Value predication: The space or hyphen (-) should be replaced with underscore (_) automatically in 'xx.evaluate.cs' file.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2540]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.4.2316401 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.5)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The space or hyphen (-) should be replaced with underscore (_) automatically in 'xx.evaluate.cs' file.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project and **give the mbconfig file name with space or hyphen (-).**
  4. Select "Data classification" or "Value predication" scenario.
  5. On the Data page, choose the data source to complete the training.
  6. Start debugging this project.
  7. See error: the debug cannot continue because exist some code error in class name area.
  
**Expected behavior**
Can debug the project successfully.
The space or hyphen (-) should be replaced with underscore (_) automatically in ''xx.evaluate.cs' file

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/225851436-3d458f8d-d00c-4964-9b64-354664954b78.png)

**Additional context**
For other scenarios, there is no 'xx.evaluate.cs' file generated.

**Comment by zewditu** [comment]
Class name used is not sanitized

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.4.2317901.
![image](https://user-images.githubusercontent.com/99375895/228707646-2f9bf1cb-b5c3-47c6-a2a1-dff57d308254.png)
