### ISSUE TITLE
a code was not created like in the ML.NET Tutorial 

### ISSUE THREAD

**Issue by ramini0530** [dotnet/machinelearning-modelbuilder#2542]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@ramini0530  could you provide more information?

**Comment by zewditu** [comment]
Don't have enough information to investigate.
