### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by RaHorusFreak** [dotnet/machinelearning-modelbuilder#2543]
**Model Builder Version**: _17.14.4.2312404_
**Visual Studion Version**: _17.4.5_

This is not a bug, this is a general question. I used to download ML.NET packages from the marketplace, but i´ve noticed that in the last release, there´s no ML.NET Model Builder GPU Support. Does the new ML.NET extension supports GPU procesing? Am I missing something? Thanks in andvance, and sorry about the question.

**Comment by zewditu** [comment]
@RaHorusFreak  no need to say sorry for a question you are welcome for any questions and asking clarification for ambiguities
Starting our latest release, the Model Builder GPU extension is no longer required. for More detail please look at the release blog post 
https://devblogs.microsoft.com/dotnet/sentence-similarity-mlnet-model-builder/#model-builder-gpu-extension-no-longer-required

**Comment by JakeRadMSFT** [comment]
Resolving - GPU support is now built into the main extension.
