### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by anujchaudhary93** [dotnet/machinelearning-modelbuilder#255]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows 10 Home
Not able to install.

![ML Error](https://user-images.githubusercontent.com/35482089/65867248-b0f42a00-e393-11e9-8d88-1036dc7e53c0.png)
![vs v](https://user-images.githubusercontent.com/35482089/65867642-6a52ff80-e394-11e9-82b5-714b3a3518f7.png)

**Comment by JakeRadMSFT** [comment]
Closing due to lack of response. If you're still hitting this issue please re-open and we'll work to resolve the issue.
