### ISSUE TITLE
I can't get the .onnx file from the evaluate, there's nowhere to click Export

### ISSUE THREAD

**Issue by LeDucPr** [dotnet/machinelearning-modelbuilder#2551]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
The onnx file should be saved under the same location with your .mbconfig. Can you check if onnx file is there?

**Comment by JakeRadMSFT** [comment]
@luisquintanilla please add more details
