### ISSUE TITLE
File opened in Excel can't be read ... we should provide a better error message

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#2554]
1. Using titanic dataset split some rows off for validate 
2. Change column type to Boolean in Advanced Data
3. Set validate dataset to the smaller datataset
4. Train
<img width="402" alt="image" src="https://user-images.githubusercontent.com/31937616/227356774-3e973f7e-cd8e-4370-9e33-6bcc375646d5.png">

**Comment by zewditu** [comment]
@JakeRadMSFT  I think it is because you   change the column type if it is because of excel it should say  the file is being used by another process
![image](https://user-images.githubusercontent.com/36615490/228987464-0c7adff0-0442-48f8-a41e-6dbee59008b0.png)

**Comment by v-Hailishi** [comment]
@zewditu Yes, you are right. If it is because of excel it should say the file is being used by another process.
