### ISSUE TITLE
Tutorial consume model

### ISSUE THREAD

**Issue by S170714** [dotnet/machinelearning-modelbuilder#2558]
[**System](url) Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@S170714  can you tell us more information about the issue?  such as steps how to reproduce it.

**Comment by zewditu** [comment]
@S170714 , there is no enough information to investigate more.

Feel free to reopen the issue with more information.
