### ISSUE TITLE
Data classification: Training time finished without completing a trial run when using metric "Log-Loss Reduction" to train "Microsoft SQL Server Database File" data.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2560]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.4.2317401 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.2)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training time finished without completing a trial run when using metric "Log-Loss Reduction" to train "Microsoft SQL Server Database File" data.

**TestMatrix**
https://github.com/dotnet/machinelearning-samples/raw/main/samples/modelbuilder/MulticlassClassification_RestaurantViolations/RestaurantScores.zip

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Data classification** scenario.
  5. On Data page, choose the "**Microsoft SQL Server Database File**" data source.
  6. Click the "Advanced data options..." link, go to the "Validation data" tab, choose the third option and browse the file like below.
![image](https://user-images.githubusercontent.com/99375895/227829972-58f3665f-471d-432d-a267-8d07546e5fa7.png)
  7. On the Train page, choose "**Log-Loss Reduction**" metric.
  8. Click "Start training" button to training, you will see that training time finished without completing a trial run.
  
**Expected behavior**
Training successful. 

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/227830549-5003049b-6182-4332-a529-f4f3af088b5d.png)

**Additional context** 
When choosing the other 3 metric, the training can be completed successfully, but the values of all models are zero.
![image](https://user-images.githubusercontent.com/99375895/227831948-289ba1f0-ec5b-4047-99c7-c11e5671d801.png)

**Comment by zewditu** [comment]
@LittleLittleCloud  what is special for "Log-Loss Reduction" for separate dataset set validation option ?

**Comment by LittleLittleCloud** [comment]
@v-Hailishi I actually have some trouble reproducing this issue. Which label are you using as prediction label

**Comment by v-Hailishi** [comment]
@LittleLittleCloud I used "**RiskCategory**" column as prediction label.
But verified on the latest main build 17.14.4.2318101, the bug has been fixed.
![image](https://user-images.githubusercontent.com/99375895/229395170-f864c6cf-aa0c-4b85-b01f-226f681a8133.png)
