### ISSUE TITLE
SQL training: Training would be failed if setting ignored columns in advanced data option

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2561]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.4.2317401 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.2)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training would be failed if you change the validation data strategy for SQL Server data.

**TestMatrix**
[home-depot-sentence-similarity-small.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10534387/home-depot-sentence-similarity-small.csv)

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Sentence similarity"** scenario.
  5. On Data page, choose the "**Microsoft SQL Server **" data source.
  6. Click the "Advanced data options..." link, go to the "Validation data" tab, choose the other option.
  7. On the Train page, click "Start training" button to training, you will see that training would be failed.
  
**Expected behavior**
Training successful. 

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/227906114-10af1d18-abfc-4606-9d13-65ccaac395b7.png)

**Additional context** 
If you don't change the validation data strategy, the training can be successful.

**Comment by LittleLittleCloud** [comment]
Update the title to reflect the root cause

other scenarios also hit this issue with ignored column
<img width="559" alt="image" src="https://user-images.githubusercontent.com/16876986/230170213-38eb8fa1-3556-415b-ba35-f2ca89d2b9b8.png">

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.15.0.2320602.
![image](https://user-images.githubusercontent.com/99375895/230532969-7093f23a-99bb-46dc-8c6d-85f9fc43f340.png)
