### ISSUE TITLE
Data classification: Predicted failed with error "Column 'Probability' not found" for Microsoft SQL Server data source when using metric "F1". 

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2563]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.4.2317701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.2)
.Net: 6.0,7.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Predict failed with error "Column 'Probability' not found" for Microsoft SQL Server data source when using metric "F1". 

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Open Visual Studio app.
  2. Select Create a new project from the Visual Studio start window.
  3. Choose the C# Console App (.NET Core) project template.
  4. Add model builder by right click on the project.
  5. Select **"Data classification** scenario.
  6. On Data page, choose the "**Microsoft SQL Server**" data source and .
  7. Click the "Advanced data options..." link, go to the "Validation data" tab, choose the second option "**Split (Training/Validation)**".
  8. On the Train page, choose "**F1**" metric and keep "**60**" seconds training time.
  9. Click "Start training" button to completed training.
  10. If the best model trainer is "**FastForestBinary**", then go to Evaluate page, the prediction would be failed.
  
**Expected behavior**
Prediction should be successful.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/228157360-de6114df-af2f-48bc-9b48-4add8094dec7.png)

**Additional context** 
Only if the following 4 conditions are met at the same time, I can repro this bug:
1. Select the "Split (Training/Validation)" validation data strategy.
2. Select "F1" metric.
3. Keep "60" seconds training time.
4. The best model trainer should be "FastForestBinary".
![#2563](https://user-images.githubusercontent.com/99375895/228159911-006c3cad-6af4-4de7-b280-96b6c1e9f363.gif)

**Comment by LittleLittleCloud** [comment]
Probability only exists for calibrated trainer. But not all trainers in AutoML has been calibrated. I'll push a fix

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.15.0.2320602.
![image](https://user-images.githubusercontent.com/99375895/230522759-df364505-ecab-473a-9cd7-89078b609631.png)
