### ISSUE TITLE
Data classification: Training would be failed when choosing the third validation data strategy for SQL Server data.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2564]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.4.2317701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.2)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training would be failed when choosing the third validation data strategy for SQL Server data.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Data classification** scenario.
  5. On Data page, choose the "**Microsoft SQL Server**" data source.
  6. Click the "Advanced data options..." link, go to the "Validation data" tab, choose the third option and browse the file like below.
![image](https://user-images.githubusercontent.com/99375895/228163089-3dda0ca9-40d3-48f3-970f-66866c9c0ca0.png)
  7. Click "Start training" button to training, you will see that training failed with error "Splitter/consolidator worker encountered exception while consuming source data".
  
**Expected behavior**
Training successful. 

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/228163328-1484834c-763f-428f-ae4a-9d5c1c1c72f5.png)

**Additional context**

**Comment by v-Hailishi** [comment]
The bug is also repro on "**Text classification**" when choosing the third validation data strategy for both of **Microsoft SQL Server and Microsoft SQL Server Database File** data.
![image](https://user-images.githubusercontent.com/99375895/228192053-c5d81b96-63ff-419d-a909-b7c2eb77ec95.png)

**Comment by v-Hailishi** [comment]
@zewditu No, I didn't open my file in excel.

**Comment by zewditu** [comment]
@v-Hailishi  thanks for confirming, better error message is a good fix for it.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.4.2318101
![image](https://user-images.githubusercontent.com/99375895/229400257-8a972ca4-1ca3-4d08-b9e1-139e4bde28ec.png)
