### ISSUE TITLE
Recover from interrupted training sessions

### ISSUE THREAD

**Issue by johnseed** [dotnet/machinelearning-modelbuilder#2567]
**Is your feature request related to a problem? Please describe.**

I often experience frustration when the training process gets disrupted. The model builder displays the message "A network issue has been detected. Please check your internet and try again. If this issue continues, please select "No" and report this issue." Clicking 'Yes' repeats the message box, while clicking 'No' ends the training session. However, the Azure training might have already completed or still be running. If I click 'Train' again, it starts a new training job without utilizing the completed job. The last Azure training was successful, just model builder get disrupted, so why not just resume from there, complete the remaining steps, and generate the code?

**Describe the solution you'd like**

I would like the option to select previously trained models from Azure and generate code from them. I've observed that the models downloaded from Azure ML Studio are in the format _model_impl_6owkjg40.pt, and not the .mlnet file that the program actually uses. It would be helpful to have the ability to "convert" .pt files to .mlnet files. This way, when training with a large amount of data, there's no need to worry about power outages or network disconnects and start over from scratch.

**Describe alternatives you've considered**
Is there a way to use the model trained from Azure ML Studio directly? The file format is .pt. If I could convert it to .onnx, then to .mlnet, I would be able to consume the model without using the builder.

**Additional context**
```
---------------------------
Polling Error
---------------------------
A network issue has been detected. Please check your internet and try again. If this issue continues, please select "No" and report this issue. 
Would you like to retry?
---------------------------
Yes   No   
---------------------------
The remote server returned an error: (401) Unauthorized.
   at AzureML.FailureCounter.<RecordFailureWithRetryWarningAsync>d__6.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/FailureCounter.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at AzureML.AutoMLRunMonitoringImages.<MonitorParentRunAsync>d__1.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunMonitoringImages.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AzureML.AutoMLRunnerImages.<RunAutoMLAsync>d__24.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 190
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.<ExecuteAsync>d__14.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160

   Please include run id https://ml.azure.com/experiments/id/e4961238-f655-4902-912d-47ce3e6b390c/runs/AutoML_60ef38b2-a352-4d51-ac10-97f9c2a10651?wsid=/subscriptions/3b0f1aa0-54a3-4a6e-ace1-9621f9efdc37/resourceGroups/Cloud/providers/Microsoft.MachineLearningServices/workspaces/Cloud in the report
```

**Comment by LittleLittleCloud** [comment]
ModelBuilder actually looks for .onnx model to download, and failing to find .onnx model might be the reason why this train doesn't complete in model builder. We'll take a look

**Comment by johnseed** [comment]
> ModelBuilder actually looks for .onnx model to download, and failing to find .onnx model might be the reason why this train doesn't complete in model builder. We'll take a look

My training usually takes 1-2 hours to complete. About an hour in, a network issue message box appears. When I click "No," it displays "The remote server returned an error: (401) Unauthorized." However, the Azure ML Studio training job has not finished yet.
![image](https://user-images.githubusercontent.com/48501700/229297624-b5e4b3d3-18c8-4047-9d42-5bbf633e2b6f.png)

**Comment by LittleLittleCloud** [comment]
@johnseed This might be because the token expired after 30 minutes. Thanks for letting us know and we will take a look

**Comment by LittleLittleCloud** [comment]
Hi @johnseed. @zewditu has pushed the fix for this issue into main already which will soon go out later this week. That should fix the `.onnx` not generating error.

> My training usually takes 1-2 hours to complete. About an hour in, a network issue message box appears. When I click "No," it displays "The remote server returned an error: (401) Unauthorized." However, the Azure ML Studio training job has not finished yet. ![image](https://user-images.githubusercontent.com/48501700/229297624-b5e4b3d3-18c8-4047-9d42-5bbf633e2b6f.png)

The prompt appears when token expired, and clicking yes will just refresh the token and won't restart the training. The next time when you see this message, you can just click yes without worrying it disrupted your training.

> Describe alternatives you've considered
Is there a way to use the model trained from Azure ML Studio directly? The file format is .pt. If I could convert it to .onnx, then to .mlnet, I would be able to consume the model without using the builder.

Yes, as I mentioned earlier, you need to download .onnx model instead of .pt. And once you download .onnx, you can create your .mlnet using the following code (this is also what model builder does behind)

```csharp
public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Label")]
            public string Label { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"ImageSource")]
            public byte[] ImageSource { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MyModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public string[] ObjectTags = new string[] { "a", "b", "c", };

            [ColumnName("boxes")]
            public float[] Boxes { get; set; } = new float[0];

            [ColumnName("labels")]
            public long[] Labels { get; set; } = new long[0];

            [ColumnName("scores")]
            public float[] Scores { get; set; } = new float[0];

            public BoundingBox[] BoundingBoxes
            {
                get
                {
                    var boundingBoxes = Enumerable.Range(0, this.Labels.Length)
                              .Select((index) =>
                              {
                                  var boxes = this.Boxes;
                                  var scores = this.Scores;
                                  var labels = this.Labels;

                                  return new BoundingBox()
                                  {
                                      Left = boxes[index * 4],
                                      Top = boxes[(index * 4) + 1],
                                      Right = boxes[(index * 4) + 2],
                                      Bottom = boxes[(index * 4) + 3],
                                      Score = scores[index],
                                      Label = this.ObjectTags[labels[index]],
                                  };
                              }).ToArray();
                    return boundingBoxes;
                }
            }

            public override string ToString()
            {
                return string.Join("\n", this.BoundingBoxes.Select(x => x.ToString()));
            }

            public class BoundingBox
            {
                public float Top;

                public float Left;

                public float Right;

                public float Bottom;

                public string Label;

                public float Score;

                public override string ToString()
                {
                    return $"Top: {this.Top}, Left: {this.Left}, Right: {this.Right}, Bottom: {this.Bottom}, Label: {this.Label}, Score: {this.Score}";
                }
            }
        }

            var pipeline = mlContext.Transforms.ResizeImages(outputColumnName:@"input1",inputColumnName:@"input1",imageHeight:600,imageWidth:800,cropAnchor:ImageResizingEstimator.Anchor.Center,resizing:ImageResizingEstimator.ResizingKind.Fill)      
                                    .Append(mlContext.Transforms.ExtractPixels(outputColumnName:@"input1",inputColumnName:@"input1",colorsToExtract:ImagePixelExtractingEstimator.ColorBits.Rgb,orderOfExtraction:ImagePixelExtractingEstimator.ColorsOrder.ARGB,outputAsFloatArray:true))      
                                    .Append(mlContext.Transforms.ApplyOnnxModel(modelFile:@"/path/to/onnx.onnx",fallbackToCpu:true));

    var model = pipeline.Fit(mlContext.Data.LoadFromEnumerable<ModelInput>(// sample input);
```

Or you can simply call `BuildPipeline` from .training.cs if you already have code behind file generated

**Comment by luisquintanilla** [comment]
@v-Hailishi can you please validate that this issue has been resolved in the latest version. Thanks!

**Comment by v-Hailishi** [comment]
@luisquintanilla Verified on the latest main build 17.16.0.2330901.
When I click "Yes", it will just refresh the token and continue the training.
When I click "No" it displays error "Object reference not set to an instance of an object."
