### ISSUE TITLE
AUC is not defined when there is no positive class in the data

### ISSUE THREAD

**Issue by hamzasaeed2029** [dotnet/machinelearning-modelbuilder#257]
![Annotation 2019-09-28 161153](https://user-images.githubusercontent.com/55932058/65823413-b83bfc00-e20a-11e9-9c5b-42e80b7a3572.png)
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows
Training failed with the exception: System.ArgumentOutOfRangeException: AUC is not defined when there is no positive class in the data

Also Visual studio 2019 is crashing few times whenever I upload csv data file or start training

**Comment by JakeRadMSFT** [comment]
Hello!
Sorry you're hitting this issue. What dataset are you training with?

**Comment by hamzasaeed2029** [comment]
> Hello!
> Sorry you're hitting this issue. What dataset are you training with?

**Comment by hamzasaeed2029** [comment]
> Hello!
> Sorry you're hitting this issue. What dataset are you training with?

![Annotation 2019-10-04 221727](https://user-images.githubusercontent.com/55932058/66226671-3a577500-e690-11e9-8b80-da357d4fc7bb.png)

This is the recent screenshot of error in output pane

**Comment by DeanRIowa** [comment]
I am receiving the same error, anyone know of a fix?  I have changed the data quite a bit and still receive the same error.

My data:
![image](https://user-images.githubusercontent.com/12719668/66716646-ab381480-ed95-11e9-9c64-710061047bc4.png)

**Comment by dpnebert** [comment]
Not sure if this has been resolved yet, but I simply copy my dataset, and pasted it to the bottom several times.  I went from about 100 lines to about 2700 lines.  Now it works.  Seems just needs to be a larger than the 2kb I was using.

**Comment by justinormont** [comment]
Currently the best you can do is collect additional data. 

More background info on the error here: 
https://github.com/dotnet/machinelearning-modelbuilder/issues/148

@dpnebert: replicating the dataset rows before splitting will cause data leakage, as a copy of the same row will exist in both the training split and the testing splits. This will cause your reported scores to be artificially high, the for the sweeping process to locate a non-useful model.

**Comment by KiransHub** [comment]
Hi guys, 

I'm using a 50KB csv file and I'm encountering the same issue so I don't think it's always to do with the size of your dataset.

**Comment by dpnebert** [comment]
My issue was I had (many) duplicate rows in my dataset.  Like justinormont
pointed out, the
rows you train with can match any rows you test with.

Can you verify your testing data is different than the training data?

**Comment by KiransHub** [comment]
Sorry, I thought I'd deleted my comment. After posting I investigated
further and found that the Python library I was using to create the CSV was
not outputting what I had expected.

**Comment by dpnebert** [comment]
I wondered where that went.  No worries.  I’m a newbie and any info is good
info.

**Comment by hamzasaeed2029** [comment]
> Not sure if this has been resolved yet, but I simply copy my dataset, and pasted it to the bottom several times. I went from about 100 lines to about 2700 lines. Now it works. Seems just needs to be a larger than the 2kb I was using.

FINALLY! thanks a lot for this trick. it really works like a charm!

**Comment by dpnebert** [comment]
No!  I learned quickly that you can use the same row to train and test.
You need to verify the (20% or whatever you train your model with) has
unique rows.  Or as far as I’ve learned.  Search the internet for
datasets.  There are so many available and you might save yourself a bunch
of work.  I am not the authority on ML and I’m pretty much guessing.

**Comment by anilindorkar** [comment]
Make sure your Test and Training data must have true and false both kind of data, My Problem resolved once I included true and false, both kind of data in the Test and Training file/dataset.
