### ISSUE TITLE
The default value is blank on the "Advanced data options->Validation data" dialog for SQL Server data.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2570]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.4.2317901 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.2)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The default value is blank on the "Advanced data options->Validation data" dialog for SQL Server data.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select any scenario.
  5. On Data page, choose the **SQL Server** data source.
  6. Click the "Advanced data options..." link, go to the "Validation data" tab.
  7. You will that the default value is blank.
  
**Expected behavior**
The default value shouldn't be blank.
![image](https://user-images.githubusercontent.com/99375895/228712442-83d23537-ad0d-4e0d-aa7b-aadca4b4438e.png)

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/228712406-51f794a8-bd76-4cda-9798-a967da3d28ef.png)

**Additional context**

**Comment by zewditu** [comment]
@v-Hailishi , I am not able to reproduce it  on the latest main.
![image](https://user-images.githubusercontent.com/36615490/228740921-6dddedac-cc76-4dbd-893a-25b5cc1c7f3b.png)

**Comment by v-Hailishi** [comment]
@zewditu you need to create a new mbconfig file, then this bug can be reproduced.

**Comment by zewditu** [comment]
Set validation option  just after table selected was not done, thanks for caching it.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.14.4.2318101.
![image](https://user-images.githubusercontent.com/99375895/229668107-46c6b3a5-60b1-4f84-a5e2-7e652aeccc20.png)
