### ISSUE TITLE
Forecasting: Training failed with error "overflow" when choosing "index1" column as time series for Microsoft SQL Server data.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2572]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.4.2316701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.2)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training failed with error "overflow" when choosing "index1" column as time series for Microsoft SQL Server data.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv

**To Reproduce**
  1. Using attached file to create Microsoft SQL Server data.
  2. Select Create a new project from the Visual Studio start window.
  3. Choose the C# Console App (.NET Core) project template.
  4. Add model builder by right click on the project.
  5. Select **Forecasting** scenario.
  6. Go to the Data page, choose the **Microsoft SQL Server** data source and **"index1" column as time series** like below.
![image](https://user-images.githubusercontent.com/99375895/229010794-380422d2-0fc0-42a6-911c-3ce7e6baab96.png)
  7. Click the "Advanced data options..." link, go to the "Validation data" tab, choose the **"Cross validation" or "Split"** strategy.
  8. On the Train page, click "Strat training" button, then you will see the training is failed.
  
**Expected behavior**
Training should be successful.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/229011512-d07ba7ae-ce84-4d11-b875-84d830ca53a2.png)

**Additional context**
The bug is not repro if you choose the third validation data strategy or choose other column as time series.

**Comment by zewditu** [comment]
@v-Hailishi  does this happen only for SQl data source?

**Comment by zewditu** [comment]
This happens when a metric is Nan, @LittleLittleCloud  do you have context on this? why the calculated metric is NaN?

**Comment by v-Hailishi** [comment]
@zewditu Yes, this happens only for SQL data source.

**Comment by v-Hailishi** [comment]
@zewditu Verified on the latest main build 17.15.0.2320602, training is still failed with another new error like below.
I am not able to get any successful run.  The metric for all completed trials are NaN.
![image](https://user-images.githubusercontent.com/99375895/230523802-245d649f-08e6-42e5-a715-2ccc89348865.png)

**Comment by zewditu** [comment]
@LittleLittleCloud  I think this is expected  and the error message is clean ,  from the output it  seems that the metrices for all completed  trials are NaN

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.15.0.2321001.
![image](https://user-images.githubusercontent.com/99375895/231117665-97d680cb-20c9-43ba-93e7-217b3d4d1348.png)
