### ISSUE TITLE
Model Builder Error

### ISSUE THREAD

**Issue by CBrauer** [dotnet/machinelearning-modelbuilder#2574]
Model Builder thew the following error:
![ModelBuildeError](https://user-images.githubusercontent.com/1317234/229313197-3379280f-5b69-4cd6-ab9f-7806a6104c53.PNG)
Charles

**Comment by zewditu** [comment]
@CBrauer  can you tell us more about it? 
what is the version of ML.Net Model builder?
if you are not on the latest, could you update it? try it and let us know if you still hot the issue
