### ISSUE TITLE
Sentence similarity: Training time finished without completing a trial run to train .csv file.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2575]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.14.4.2318101 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.2)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training time finished without completing a trial run to train .csv file.

**TestMatrix**
[home-depot-sentence-similarity-small.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10534387/home-depot-sentence-similarity-small.csv)

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Sentence similarity"** scenario.
  5. On Data page, choose the attached .csv data source and set the three options like below.
![image](https://user-images.githubusercontent.com/99375895/229479935-2eec7cdd-8657-4f58-aaba-2d08848b150c.png)
  6. On the Train page, click "Start training" button to training, you will see that training would be failed.
  
**Expected behavior**
Training successful. 

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/229479783-0ff0bd51-936a-4e30-821e-f234ca8d721d.png)

**Additional context**

**Comment by LittleLittleCloud** [comment]
NaN would not be counted as successful trial so the error is expected. I update the error message in ml.net repo so it would be more explanatory.

**Comment by zewditu** [comment]
@LittleLittleCloud  are we able to close this issue if you already updated the message in ml.net repo?

**Comment by LittleLittleCloud** [comment]
Yep

**Comment by v-Hailishi** [comment]
@LittleLittleCloud I re-opened this bug, please help to resolve it.
<img width="555" alt="image" src="https://user-images.githubusercontent.com/99375895/230533858-41a72b02-b784-47fb-a19d-f25006d7678a.png">

**Comment by LittleLittleCloud** [comment]
@v-Hailishi Thanks for verifying this issue and alarm the bell. The root cause of this issue is still because of dataset (too many bad values in search term). We will explore how can we provide a better experience (like throw a warning message) instead of fail after training.

@JakeRadMSFT @luisquintanilla I move this issue to April release for now and let's discuss offline on what kind of action we want to take when training / validation dataset is full of bad values

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.15.0.2321601.
![image](https://user-images.githubusercontent.com/99375895/232427192-67d438c3-2d23-43e7-b16e-f0a95a131403.png)
![image](https://user-images.githubusercontent.com/99375895/232428765-5e9cb2e5-d8bb-4dd5-9ef7-423530b7fe97.png)
