### ISSUE TITLE
Data page for text scenarios is messed 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2576]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version
![image](https://user-images.githubusercontent.com/36615490/230166129-582491da-2949-4943-95f4-492aa549d07a.png)

**Comment by zewditu** [comment]
I  dig a little bit it is the regression of  this PR https://github.com/dotnet/machinelearning-tools/pull/1725

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.15.0.2320602.
<img width="374" alt="image" src="https://user-images.githubusercontent.com/99375895/230522006-75c49171-7d64-4801-93db-3c53c81f23c0.png">
