### ISSUE TITLE
*.map.json not nested under mbconfig

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#2581]
Azure Object Detection:
<img width="181" alt="image" src="https://user-images.githubusercontent.com/31937616/231285203-aef3a61c-d29f-4287-9042-27e37ea2aa60.png">

We should add it here and anywhere else we handle nesting logic.

https://github.com/dotnet/machinelearning-tools/blob/main/src/Microsoft.ML.ModelBuilder/relatedFiles.pkgdef

**Comment by JakeRadMSFT** [comment]
Azure Image Classification too:

<img width="174" alt="image" src="https://user-images.githubusercontent.com/31937616/231286405-deaea565-8636-45e3-999c-8a69e0493221.png">

**Comment by zewditu** [comment]
Adding into `related.pkgdef.cs` is the only place we missed.
