### ISSUE TITLE
Validation data not abiding by types in advanced data options.

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#2582]
1.  Pick titanic dataset
2. Label is survived but change type to string or boolean
3. Pick titanic dataset again or another validation file that has same columns and types
4. Try to train.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/31937616/231291187-bc9bea53-7797-4f65-a1e3-f53dde1ce110.png">

**Comment by LittleLittleCloud** [comment]
I would suspect this bug also appears when you update any column type in advanced option using either text data source or sql data source. As we don't respect train dataset's schema when parsing validation dataset.

I still feel like the right solution is simply create text loader for validation dataset based on training dataset's schema only. And we will get a validation dataset loading error from text loader during training time if both validation and training dataset's schema doesn't match.

**Comment by JakeRadMSFT** [comment]
> I still feel like the right solution is simply create text loader for validation dataset based on training dataset's schema only. And we will get a validation dataset loading error from text loader during training time if both validation and training dataset's schema doesn't match.

Zewditu and I chatted offline.

1. Infer Validation Schema based on  Validation Dataset
1. Check that Validation Dataset has all required Feature and Label columns (name only)
   - If train dataset didn't have column names in it then ignore this check
1. Override column type/purpose from Advanced Data options for Training Dataset
   - Ignore all the ignored columns
