### ISSUE TITLE
machine learning model not showing 

### ISSUE THREAD

**Issue by richard75** [dotnet/machinelearning-modelbuilder#2583]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@richard75  did you download and install ML.net Model Builder from the visual studio marketplace https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022

 ## OR 
look at this for more detailed steps
https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-model-builder?tabs=visual-studio-2022

**Comment by JakeRadMSFT** [comment]
@richard75 this issues doesn't have enough information. Please try one of Zewditu's suggestions or re-open issue with more details so we can help you out!
