### ISSUE TITLE
GPU extension missing "Install extension" link 404s

### ISSUE THREAD

**Issue by kelson-dev** [dotnet/machinelearning-modelbuilder#2588]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  16.13.9.2235601
 - Visual Studio Version 17.5.4

**Describe the bug**
Link to install "GPU extension" 404s
https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilderGPU2022

**To Reproduce**
1. Add a Machine Learning Model to a project
2. Select a scenario that supports local GPU training
3. Requirements for local GPU training show "GPU extension is missing" with "Install extension"
4. Clicking the "Install extension" link gives a 404 error https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilderGPU2022

**Expected behavior**
The extension is found

**Screenshots**
![image](https://user-images.githubusercontent.com/67489978/232255924-337544c1-eb66-481d-982b-b09cf320947d.png)

**Comment by JakeRadMSFT** [comment]
@kelson-dev can you update to the latest model builder? The gpu extension isn't needed anymore - it's built in to the MB extension in later versions.

@luisquintanilla can we update that aka.ms link to point to our docs?

**Comment by JakeRadMSFT** [comment]
Closing for now - GPU Extension is built into main extension now. Just need to upgrade.

Please re-open if this doesn't solve the issue for you!

Thanks for reaching out!
