### ISSUE TITLE
The result, Is Toxic, is always true.

### ISSUE THREAD

**Issue by schan** [dotnet/machinelearning-modelbuilder#259]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

I changed the input.SentimentText to the following values and the result, Is Toxic, is always true.

- Hello
- Good morning
- etc...

**Comment by rustd** [comment]
This depends on the dataset you used for training. You will have to try different samples to see the result.  For e.g. the following text should give you a false result
"I'm not sure either. I think it has something to do with merely ahistoricals"

**Comment by justinormont** [comment]
This is due to the small size of the dataset sample used in the [getting started guide](https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train). See https://github.com/dotnet/machinelearning-modelbuilder/issues/323.
