### ISSUE TITLE
myMLAppML.Model is not compatible with netcoreapp2.1

### ISSUE THREAD

**Issue by DougSteiert** [dotnet/machinelearning-modelbuilder#260]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

The exact error I am getting is: 

`Project mMLApp.ML.Model is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Project myMLAppML.Model supports: netstandard2.1 (.NETStandard,Version=v2.1)`

I am not really sure what went wrong, as I created this projected exactly as the tutorial said to do, yet somehow I ended up not being able to run this.

**Comment by twsI** [comment]
.NET Standard 2.1 requires .NET Core 3.0. In order to use it with .NET Core 2.1, you should check whether you can downgrade the myMLAppML.Model project to .NET Standard 2.0

**Comment by win32nipuh** [comment]
I have solved this issue: 
1. Downloaded and install the required SDK
2. VS: Tools->Tools -> Options -> Projects and Solutions -> .NET Core
unchecked the Use Preview ....
3. Optional yet one:  Build Debug/Release x64 (no Any CPU)

**Comment by rustd** [comment]
Model Builder targets .NET Standard 2.1 requires .NET Core 3.0. @natke can we please update our docs to list this as a minimum requirement.

**Comment by natke** [comment]
Sure. Is this where we should add it? https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-model-builder#pre-requisites

What is the actual pre-requisite? @rustd

**Comment by rustd** [comment]
Yes.
Pre-req: "Model Builder targets .NET Standard 2.1 which requires .NET Core 3.0."
