### ISSUE TITLE
Sentence similarity: Project debug failed with error "Two TorchSharp runtime packages have been referenced (both libtorch-cpu and libtorch-cuda)".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2606]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022:  17.15.0.2322401 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.2)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Project running failed with error "Two TorchSharp runtime packages have been referenced (both libtorch-cpu and libtorch-cuda)".

**TestMatrix**
[home-depot-sentence-similarity-small.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/10534387/home-depot-sentence-similarity-small.csv)

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Sentence similarity"** scenario.
  5. On Data page, choose the attached .csv data source and set the three options like below.
![image](https://user-images.githubusercontent.com/99375895/229479935-2eec7cdd-8657-4f58-aaba-2d08848b150c.png)
  6. On the Train page, click "Start training" button to complete the training.
  7. Press "F5" to debug the project.
  
**Expected behavior**
Project debug successful.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/234810434-440a2f97-a3c0-4794-92d5-8868aaad0387.png)

**Additional context** 
1. There are many errors in "consumption.cs" and "training.cs" files.
![image](https://user-images.githubusercontent.com/99375895/234811937-b9fcccf7-984f-4031-940a-272f5cbd3c86.png)
![image](https://user-images.githubusercontent.com/99375895/234811772-651a609f-6019-4e5b-b239-4c25a85e2f8b.png)

2. The issue is not repro in the generated Console App and Web API projects.

**Comment by JakeRadMSFT** [comment]
@v-Hailishi did you try training using GPU and CPU at some point for that project? Does removing one of them from CSPROJ work?

**Comment by v-Hailishi** [comment]
@JakeRadMSFT The bug occurs after training "Sentence similarity" scenario successfully using CPU. 
The bug would be fixed if you delete the error condition in "libtorch-cpu.targets" file.
![image](https://user-images.githubusercontent.com/99375895/235037285-91b1a70f-2ce1-4f36-b4f7-8f5c11d80a49.png)

**Comment by JakeRadMSFT** [comment]
@v-Hailishi can you share your csproj?

**Comment by v-Hailishi** [comment]
@JakeRadMSFT Attached my csproj.
[ConsoleApp4.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/11394995/ConsoleApp4.zip)

**Comment by zewditu** [comment]
The two torchs (torch cpu and toch GPU ) are installed in the same project we need to check if there is a different torch and then remove it

**Comment by v-Hailishi** [comment]
The bug is still repro on the latest main build 17.16.0.2326803.
<img width="535" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/c0398353-990e-4681-b98d-dca2085b028f">
<img width="533" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/e57b0e96-4534-43d0-b48c-32b476c8ea06">

**Comment by luisquintanilla** [comment]
Closing since it's been fixed in MB.

**Comment by luisquintanilla** [comment]
@zewditu can you please look into this. Thanks.

**Comment by zewditu** [comment]
@v-Hailishi  does it only happen for sentence similarity? unfortunately, my machine is not able to train sentence similarity scenarios,
originally two torchsharp runtime issue was the issue of all torch based scenario such as text classification, sentence similarity, and  local object detection, now I am not able to reproduce on local object detection
could you send me the project  after you reproduce it

**Comment by v-Hailishi** [comment]
@zewditu The bug only happens for sentence similarity.
[Sentence_similarity.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/11552651/Sentence_similarity.zip)

**Comment by luisquintanilla** [comment]
@zewditu can't repro. @LittleLittleCloud to try and repo.

**Comment by LittleLittleCloud** [comment]
@v-Hailishi 
I can't reproduce this issue on a newly-created project

You're hitting this issue probably because the project already has two torchsharp runtime installed? In that case model builder won't install torchsharp runtime because it's there. In the meantime, it also won't remove the other torchsharp runtime because model builder tries making as less change as possible to user's project, even it's in error state.

**Comment by v-Hailishi** [comment]
@LittleLittleCloud Verified on the latest main build 17.16.0.2331402, I can still reproduce it on a fresh-new project.
On the Output window, you will see that the two torchsharp runtime are installed automatically.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/79ad953e-eb0a-47a9-87e1-5f195707ce53)

**Comment by LittleLittleCloud** [comment]
Kk thanks. Just to confirm if you are running cpu training.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.16.0.2332301.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/6f6b1973-f7cf-49d8-bbfc-635b0d47119b)
