### ISSUE TITLE
Ml.NET Finalizing Model stuck forever

### ISSUE THREAD

**Issue by chanmmn** [dotnet/machinelearning-modelbuilder#2615]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  17.15.0.2321042
 - Visual Studio Version 2022 
 -  I connect SQL Server 2022
 - Table with 336447 rows and 9 columns.

**Describe the bug**
- Train (Training)
- Clear description of the problem: The Finalizing Model, finalizing forever. I waited at least for 4 hours. 

**To Reproduce**
Please watch the video in the link below. The training time I purposely set to 2 minutes because of the video recording time. I was running for 10 minutes actually.  The log is also at the folder below. 
https://drive.google.com/drive/folders/12tV2M9IV2onX7LxBo6CpPCcVYGwbU6e_?usp=share_link

**Expected behavior**
Complete the training.

**Screenshots**
In the video inside the folder:
https://drive.google.com/drive/folders/12tV2M9IV2onX7LxBo6CpPCcVYGwbU6e_?usp=share_link

**Additional context**

**Comment by LittleLittleCloud** [comment]
From the log it seems that the experiment is keeping running after time being used up. Although on the UI, it shows `finalizing`, it's actually still wait for the current trial to be cancelled, which takes ~ 1 or 2 hours based on the log you share.

The reason why the trial takes that much time to be canceled is probably because you are using `lbfgs`, where the computing-intense part is done in unmanaged code and there's no good way to terminate the process from managed code. Considering the size of your dataset it's likely for the `lbfgs` trainer to use that much time running unmanaged computing code. Maybe you can try some tree-based method like `fast-tree`, `fast-forest`, `lgbm` and see how it goes

**Comment by LittleLittleCloud** [comment]
Hi @chanmmn The error message basically means it fails to complete a trial within given time budget.

I would suggest just increase your training budget and see how it goes. Considering the size of your dataset, 10 minutes probably won't be long enough

**Comment by chanmmn** [comment]
Hi @LittleLittleCloud ,
Thanks for your prompt reply.
I added 40 minutes but still facing error. This latest log file I uploaded to:
https://drive.google.com/drive/folders/12tV2M9IV2onX7LxBo6CpPCcVYGwbU6e_?usp=share_link
By the way I have also reduced the row to around 216k.

**Comment by chanmmn** [comment]
Thanks @LittleLittleCloud 
But no luck .. I I run around 1 hour and 40 minutes. 
I added to new log file, MLModel1-QDX67K.txt and screen captured, MLTrainingProblem13May23.png to the link below.
https://drive.google.com/drive/folders/12tV2M9IV2onX7LxBo6CpPCcVYGwbU6e_?usp=share_link

**Comment by LittleLittleCloud** [comment]
From the log it seems that you still need more time. It's a bit wield to see a trial take that much long time to finish. Can you share the schema of your data? Maybe there're a lot of text features in your dataset?

**Comment by chanmmn** [comment]
I added 2 png files
NoAdvancedTrainingOption.png
AdvancedTrainingOption.png
at
https://drive.google.com/drive/folders/12tV2M9IV2onX7LxBo6CpPCcVYGwbU6e_?usp=share_link
The machine with No Advanced Training Option (NoAdvancedTrainingOption.png) can complete the training with 1800 second and run without error.
The machine with Advanced Training Option (AdvancedTrainingOption.png) will have error even I put up to 4800.

**Comment by LittleLittleCloud** [comment]
KK, can you share with us the model builder version of both Advanced training option and no advanced training option? Looks like they are different.

**Comment by chanmmn** [comment]
I added 2 files:
MLModel2-8CEBSH (AdvancedTrainingOption).txt
MLModel1-GE5NLY (NoAdvancedTrainingOption).txt
into
https://drive.google.com/drive/folders/12tV2M9IV2onX7LxBo6CpPCcVYGwbU6e_?usp=share_link
The MLModel1-GE5NLY (NoAdvancedTrainingOption).txt is the one with No Advanced Training Option and the training can be successful. 
The MLModel2-8CEBSH (AdvancedTrainingOption).txt is the with No Advanced Training Option and the training Failed.
