### ISSUE TITLE
Vott image preview looks off 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2617]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/236068496-47bd083d-19d3-4371-8ce7-5402bec561fc.png)

**Additional context**

**Comment by JakeRadMSFT** [comment]
Did you update the paths in the vott file? Can you share an example path?

**Comment by zewditu** [comment]
Yes, it is because of the path.
