### ISSUE TITLE
Image Classification included in Custom Scenario

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#262]

**Comment by beccamc** [comment]
https://microsoft-my.sharepoint.com/:w:/p/pranavra/ESWn2bMMqk5Pos4y-i7tmGABPz_3dt-7nROjuA-U3gPtPg?e=7iowCU

**Comment by beccamc** [comment]
@briacht I think this is something you're checking on in the user studies? Do we want to add Image Classification in the custom scenario? Or should we push this until we understand if it makes sense to users?

**Comment by briacht** [comment]
Nope we don't need to add image classification to custom scenario now.

Users understood that putting images into categories would be under "image classification"; actually a majority of users thought that "custom scenario" meant something that was more complex than the other scenarios offered.
