### ISSUE TITLE
Local object Detection training option UI needs tooltip

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2624]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

## Options in the UI
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/36615490/f8636c6b-5e24-4cdb-ab9b-72bfea25c287)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luisquintanilla** [comment]
| Option | Tooltip Text | 
| --- | --- |
| Epoch | Number of cycles to run training for |
| Width | Width to scale original image to |
| Height | Height to scale original image to |
| Score threshold | Confidence score an object was detected in a bounding box |
| IoU threshold | Overlap between actual boxes and detected boxes |
