### ISSUE TITLE
Choose data source not appearing when choose SQL Server as Input (intermittent  problem)

### ISSUE THREAD

**Issue by chanmmn** [dotnet/machinelearning-modelbuilder#2625]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version 2019 4.8.09032

**Describe the bug**
- At the Data step
- Click SQL Server but the Choose data source... not appearing (the problem is intermittent )

**To Reproduce**
Please see the video CannotBrowseSQLServer.mp4 in the link below.
https://drive.google.com/drive/folders/12tV2M9IV2onX7LxBo6CpPCcVYGwbU6e_?usp=share_link

**Expected behavior**
Choose data source appears.

**Screenshots**
Please see the video CannotBrowseSQLServer.mp4 in the link below.
https://drive.google.com/drive/folders/12tV2M9IV2onX7LxBo6CpPCcVYGwbU6e_?usp=share_link

**Additional context**

**Comment by LittleLittleCloud** [comment]
Dup of #2622 

We're fixing this bug. As a workaround, you can save and close .mbconfig, then reopen it. In most of cases the sql input window should re-appear
