### ISSUE TITLE
Object detection-Local: Word "mAP50" should be capitalized to "MAP50" on the "Train" page.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2626]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.16.0.2326001 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.5)
.Net: 6.0, 7.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Word "mAP50" should be capitalized to "MAP50" on the "Train" page.

**TestMatrix**

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Object detection"** scenario.
  5. Choose "**Local**" environment and data source to complete the training.
  6. Check word "mAP50" in training result.
  
**Expected behavior**
Word "mAP50" should be capitalized to "MAP50".

**Screenshot**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/9f627fa5-cdfa-46db-873d-0740159b733a)

**Additional context**

**Comment by luisquintanilla** [comment]
Thanks for reporting this issue @v-Hailishi. However, that's the abbreviation used for the mean average precision metric. 

https://towardsdatascience.com/on-object-detection-metrics-with-worked-example-216f173ed31e

> Average Precision (AP) and **mean Average Precision (mAP)** are the most popular metrics used to evaluate object detection models

Closing this issue for now.
