### ISSUE TITLE
Unable to select the column

### ISSUE THREAD

**Issue by Nick-Baker64** [dotnet/machinelearning-modelbuilder#2637]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 17.15.0.2321402
 - Visual Studio Version 17.5.5

**Describe the bug**
- On which step of the process did you run into an issue: Add data
- Clear description of the problem: I have added a data source file, but when I try to select the column to predict, the selct column dropdown is blank, even though col0 and col1 are visible in the data preview.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
![Screenshot ML  2023-05-16 143255](https://github.com/dotnet/machinelearning-modelbuilder/assets/84718824/8154cf71-97a6-41ca-9760-40c8eb2bf6c4)

**Comment by LittleLittleCloud** [comment]
Dup of #2622
