### ISSUE TITLE
it

### ISSUE THREAD

**Issue by viprobelk** [dotnet/machinelearning-modelbuilder#2638]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luisquintanilla** [comment]
We need more details to complete this. Closing due to no response. @viprobelk please feel free to open a new issue with more details so we can help you.
