### ISSUE TITLE
specify a relative path for `ModelFilePath` in `.mbconfig` file.

### ISSUE THREAD

**Issue by lgong-rms** [dotnet/machinelearning-modelbuilder#2639]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 17.15.0.2321402
 - Visual Studio Version: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.6.0

**Describe the bug**
- On which step of the process did you run into an issue: after the training is completed.
- Clear description of the problem: the relative path specified for `ModelFilePath` is relative to `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\ServiceHub\Hosts\ServiceHub.Host.netfx.x64\` instead of the location of the `.mbconfig` file or the project where the Machine Learning Model is added. 

**To Reproduce**
1. create a C# project
2. add a machine learning model to the project by right clicking on the project and then Add -> Machine Learning Model.
3. open the `.mbconfig` file as source code by right clicking it and the  `Open With...` -> Source Code (Text) Editor.
4. set `ModelFilePath` to a relative path, e.g., `Models\\foobar.mlnet` 
5. save the file and then double clik it to open its UI.
6. specify the training dataset and train
8. See the model is generated in `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\ServiceHub\Hosts\ServiceHub.Host.netfx.x64\Models\foobar.mlnet`

**Expected behavior**
what I expected to happen is that the model is generated in a place relative to the location of the `.mbconfig` file or the project where the machine model is added.

**Additional context**
`ModelFilePath` seems not to recognize environment variables (such as %TEMP%) nor visual studio context variables (such as $(Solution)).

**Comment by LittleLittleCloud** [comment]
Thanks for the suggestion. @luisquintanilla Maybe  we can make that change in next release?

**Comment by GKrivosheev-rms** [comment]
The problem with current behaviour is that the code will only work on original dev's machine. If the file is checked into source control and cloned onto other machine at different location it will not work.  
Extra credit:  Add support for env variables or MSBUILD variables in that path.

**Comment by LittleLittleCloud** [comment]
action item
- enable loading model from relative path for `ModelFilePath`

**Comment by v-Hailishi** [comment]
Verified on the latest main build 17.16.0.2330901, ModelFilePath still use the **absolute path** in .mbconfig file.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/2d9dd691-52a8-4657-b9a6-346fe5bb136f)

**Comment by LittleLittleCloud** [comment]
Yup that’s expected. The model path will still be the full path after training which is to maintain backward compatibility. What has been changed is model builder should be able to load model if the model path is manually updated to relative path in mbconfig

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by v-Hailishi** [comment]
@LittleLittleCloud Yes, Model builder is able to load model after the model path is manually updated to relative path in mbconfig file.
