### ISSUE TITLE
Object detection-Local-Vott: The best model's value is zero, predicted failed and the generated console app project is running failed.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2642]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.16.0.2326803 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.5)
.Net: 6.0, 7.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The best model's value is zero, predicted failed and the generated console app project is running failed.

**TestMatrix**
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#create-a-new-vott-project

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select "**Object detection**" scenario.
  5. Choose "**Local**" environment.
  6. On the Data page, choose "**Vott**" data source to complete the training.
  7. You will see that the best model's value is zero.
  8. On the Consume page, predicted failed with error "No BBox detected".
  9. Go to the Consume page, click "Add to solution" button to generate the Console App and Web API projects.
  10. The generated console app project is running failed, the generated Web API project's output is empty.
  
**Expected behavior**
The best model's value is expected, predicted successfully and the generated projects are running successfully.

**Screenshot**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/b264d87c-ea33-4b1d-b608-d9518a0c5ad6)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/437863af-1cfe-4e99-915c-b7137ca01658)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/aa0fd2c4-482d-47eb-a1c7-ea94048ec92b)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/8eca91bf-a2e5-4d97-9fb7-e4d8b4ad6aa8)

**Additional context**
1. The bug is not repro on Object detection-Local-**Coco** scenario.
2. I have already tried some times, sometimes even though it is not zero, the score is also very low.

**Comment by zewditu** [comment]
@v-Hailishi  at the current state public release and main have the same status of code generation, I am not able to reproduce it ,
could you share your dataset

**Comment by zewditu** [comment]
I also test it in main , it is not reproducible.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/36615490/2355de86-1267-41f7-a662-f21c12e707ba)

**Comment by v-Hailishi** [comment]
@zewditu I have shared my dataset in teams.
<img width="354" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/eb028851-c697-451f-8e9d-78a4a952fbd8">

**Comment by zewditu** [comment]
I think it is specific to the dataset set

**Comment by luisquintanilla** [comment]
In code-behind, let's make sure to add a check that there are bounding boxes. If not, just mention no bounding boxes found, don't throw an exception.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.16.0.2328101.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/bcd7bf29-27c9-4bd7-b66a-4676e3c2450e)

**Comment by oybekrustamov** [comment]
Where we get the 17.16.0.2328101 version? The latest version in VS2022 is: 17.16.0.2326802?
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/49331271/ba677b0c-a5ba-4cf8-b5c3-1946174fd0d0)

**Comment by jsivanarayana** [comment]
in latest version 17.18.2.2415501 also we getting same error
