### ISSUE TITLE
Model Builder | Selecting a file without file type crashes Visual Studio

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#265]
@aslotte commented on [Thu Oct 03 2019](https://github.com/dotnet/machinelearning/issues/4287)

### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 

### Issue

- **What did you do?** I downloaded the data for spam detection (ML samples)
- **What happened?** When I opened the Model Builder in Visual studio and selected the training file, Visual Studio hangs and eventually crashes. Setting the file type to .tsv makes it work.
- **What did you expect?** A reasonable error message would be useful, e.g. "Please indicate if this file is tab- or comma-separated"

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

---

@aslotte commented on [Thu Oct 03 2019](https://github.com/dotnet/machinelearning/issues/4287#issuecomment-538092965)

I see the same issue occurring for a .csv file.
In this case when I'm trying to upload the `taxi-fare-train.csv` file found in the /machinelearning-samples/datasets folder

---

@aslotte commented on [Thu Oct 03 2019](https://github.com/dotnet/machinelearning/issues/4287#issuecomment-538094891)

This was due to the file being opened in Excel (duh...)
Visual Studio just crashes, and there is no warning message.

**Comment by Elantonio** [comment]
just opening a csv makes vs2017 crash. no errors, no warnings

**Comment by telmo-rodrigues** [comment]
**If** you have your file **opened** and its **locked**  and you open it with Model Builder, it will crash due to the file lock. I've managed to reproduce this behavior every time.

**Comment by Elantonio** [comment]
> **If** you have your file **opened** and its **locked** and you open it with Model Builder, it will crash due to the file lock. I've managed to reproduce this behavior every time.

That's obvious! But it's not  the case here.
switching to format wit \t delimiters worked.

**Comment by LittleLittleCloud** [comment]
should be a dup of #232
