### ISSUE TITLE
A11y_Model Builder_Train_Advance Training Options_AI4D: (devenv/radio button 'Root Mean Squared Error (RMSE) - It is always non-negative, and values closer to 0.00 are better.') An element's IsOffScreen property must be false when its clickable point is on-screen.

### ISSUE THREAD

**Issue by Samhitha66** [dotnet/machinelearning-modelbuilder#2653]
### GitHubTags

#WCAG4.2.1; #A11ySev2; #A11yTCS; #A11yWCAG2.1; #DesktopApp; #Win11; #Visual Studio Client; #SH_ModelBuilder_Win32_May2023; #Object Information; #Win32; #Benchmark; #AI4D; #A11yAuto;

### Environment Details

Application Name: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.6.1
Microsoft Windows 11 Enterprise 10.0.22621 Build 22621

### Repro steps

1. Launch the Visual Studio with at least one of the .NET workload.
2. Tab till enable ML.NET Model Builder (Tools -> Options -> Environment -> Preview Features) and select it.
3. Create a new .NET project or open an existing .NET project.
4. Open context menu(Right-click) of the project in the solution explorer.
5. Tab till Add and then tab till Machine Learning Model and press enter.
6. Model Builder dialog will open. 
7. Complete the required details of All the three(scenario, environment, data) steps.
8. Train screen will appear. Tab till Advance Training Option and press enter.
9. Optimizing Metric screen will appear.
10. Turn on AI4D
11. Verify whether we are getting AI bug like An element's IsOffScreen property must be false when its clickable point is on-screen or not.

Issue observed throughout the application.

The following accessibility issue needs investigation.

### App
devenv

### Element path
 radio button 'Root Mean Squared Error (RMSE) - It is always non-negative, and values closer to 0.00 are better.'

### Issue Details
 An element's IsOffScreen property must be false when its clickable point is on-screen. [Section 508 502.3.1](https://www.access-board.gov/ict/#502-interoperability-assistive-technology)

### How To Fix
 If the element's ClickablePoint property is correct, set the element's IsOffScreen property to false.
If the element's ClickablePoint property is incorrect, please ensure it returns the correct value.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

### Attachment
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/80a6718a-489b-4a70-9ef9-cb6b29aff511)
![MicrosoftTeams-image (11)](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/420430df-51fd-4bb7-b894-6bc16c7d3375)

**Comment by zewditu** [comment]
I am not able to reproduce it
