### ISSUE TITLE
Object detection data page spinning forever when wrong data format is selected 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2664]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**
1. Select Object detection
2. Select envoronment
3. Got to the data page
4. Vott is checked by defalut
5. Browse to a file  coco data format

**Expected behavior**
Tell wrong data format is selected 
**Screenshots**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/36615490/6a0b643e-890e-4a61-baec-e8c6ef06d9ff)

**Additional context**

**Comment by los93sol** [comment]
I'm having the same issue, but my data is actually in Vott format

**Comment by zewditu** [comment]
@los93sol  your data is vott format,  are you selecting Vott radio button on the data page?

**Comment by los93sol** [comment]
It’s preselected as Vott and just spins forever

**Comment by luisquintanilla** [comment]
Workaround: Select the right data format.

**Comment by los93sol** [comment]
In my case the format is correct and ores selected, changing it does nothing

**Comment by zewditu** [comment]
@los93sol  did you check  image file path in the json?

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.16.0.2332001.
<img width="433" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/82bd4679-0968-45b9-ac30-9dbdcec79515">
