### ISSUE TITLE
A11y_Model Builder_Data_Advance Data Options_Usability:When Keyboard focus lands on the search field, the place holder text given in that field is disappeared.  

### ISSUE THREAD

**Issue by Samhitha66** [dotnet/machinelearning-modelbuilder#2665]
### GitHubTags

#A11yUsable; #A11ySev4; #A11yTCS; #DesktopApp; #Win11; #Visual Studio Client; #SH_ModelBuilder_Win32_May2023; #Win32; #Benchmark; 

### Environment Details

Application Name: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.6.1
Microsoft Windows 11 Enterprise 10.0.22621 Build 22621

### Repro steps

1. Launch the Visual Studio with at least one of the .NET workload.
2. Tab till enable ML.NET Model Builder (Tools -> Options -> Environment -> Preview Features) and select it.
3. Create a new .NET project or open an existing .NET project.
4. Open context menu(Right-click) of the project in the solution explorer.
5. Tab till Add and then tab till Machine Learning Model and press enter.
6. Model Builder dialog will open.
7. Tab till Data tab and press enter.
8. Tab till "Advanced Data Options" button and press enter.
9. Verify whether when keyboard focus lands on the search field, the place holder text given in that field is disappearing or not.

### Actual Result

When Keyboard focus lands on the search field, the place holder text given in that field is disappeared.  

Issue observed throughout the application.

### Expected Result

When Keyboard focus lands on the search field, the place holder text given in that field should not disappear.  

### User Impact

Users does not get the information regarding the placeholder text present in the field if, it was disappeared on the receiving the keyboard focus. 

### Attachment
![Bug_Place holder](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/b3288e78-0de4-4426-9fc2-f94d52ae3686)

**Comment by zewditu** [comment]
@Samhitha66, ready to validate by Model builder version :16.17.0.2332602

**Comment by Samhitha66** [comment]
Regressed the issue in the below environment
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.6.4
The issue is fixed. Hence closing the bug.
Please find the attachment for the reference.
#Regressed:06-30-23; #Closed;
![Fixed](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/0b475fe2-a59f-4ef9-b73c-cdc865a65df4)
