### ISSUE TITLE
A11y_Model Builder_consume_Web API Add To Solution_Label in Name: Visual label name is not matching with the programmatical label name for "Add again" button present in the "Consume" screen.

### ISSUE THREAD

**Issue by Samhitha66** [dotnet/machinelearning-modelbuilder#2669]
### GitHubTags

#WCAG2.5.3; #A11ySev2; #A11yTCS; #A11yWCAG2.1; #DesktopApp; #Win11; #Visual Studio Client; #SH_ModelBuilder_Win32_May2023; #Label in Name; #Win32; #Benchmark;

### Environment Details

Application Name: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.6.1
Microsoft Windows 11 Enterprise 10.0.22621 Build 22621

### Repro Steps

1. Launch the Visual Studio with at least one of the .NET workload.
2. Tab till enable ML.NET Model Builder (Tools -> Options -> Environment -> Preview Features) and select it.
3. Create a new .NET project or open an existing .NET project.
4. Open context menu(Right-click) of the project in the solution explorer.
5. Tab till Add and then tab till Machine Learning Model and press enter.
6. Model Builder dialog will open. 
7. Open context menu(Right-click) of the project in the solution explorer.
8. Tab till Add and then tab till Machine Learning Model and press enter.
9. Model Builder dialog will open. 
10. Complete the required details of All the three(scenario, environment, data, Train, Evaluate) steps.
11. Consume screen will appear. Tab till Add To Solution button under Web API tile button and press enter.
12. Tab till "Add Again" button after adding the solution"
13. Verify whether the visual label name is matching with the programmatical label name for "Add again" button present in the "Consume" screen or not.

### Actual Result

Visual label name is not matching with the programmatical label name for "Add again" button present in the "Consume" screen.

Issue observed throughout the application.

### Expected Result

Visual label name should match with the programmatical label name for "Add again" buttons present in the "Consume" screen.

### User Impact
Speech to text Viewer may face difficulty in accessing the control if visually present name and programmatically defined name are different.

### Attachment
![Bug_Label in Name](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/ecbc79a9-c88f-49f8-a16d-683e1ac0f564)

**Comment by zewditu** [comment]
@Samhitha66 , use [this ](https://microsoft.sharepoint.com/sites/PrivateBuildforAccessibility/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FPrivateBuildforAccessibility%2FShared%20Documents%2FMicrosoft%2EML%2EModelBuilder%2Evsix&parent=%2Fsites%2FPrivateBuildforAccessibility%2FShared%20Documents) build  to validate this issue.

**Comment by Samhitha66** [comment]
@zewditu 
Regressed the issue in the below environmnet
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.8.0 Preview 1.0 [33912.440.main]
The issue is fixed. Hence closing this bug.
Please find the attachment for the reference.
#Regressed:07-25-23; #Closed;
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/4ef593fb-6dc4-4aef-91d4-3071dc090495)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/03647d0d-7688-4876-b027-ace0a40b059d)
