### ISSUE TITLE
CS0579 Duplicate 'System.Reflection.Assembly...' errors when using model builder with web app bot

### ISSUE THREAD

**Issue by Veroni4ka** [dotnet/machinelearning-modelbuilder#268]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1908.1402 & 16.0.1909.2101
 - Visual Studio Version: 16.3.1

**Describe the bug**
When using the model builder with Azure generated Web App Bot building the solution results in several CS0579 Duplicate 'System.Reflection.Assembly...' errors. 

**To Reproduce**
1. create an Azure Web App Bot (Echo Bot)
2. download the code
3. add ML using Model Builder
4. 2 new projects will be added to the solution, but also they’ll be added inside the EchoBot project  
5. add Microsoft.ML libraries to the bot project and build the solution (see the 1st screenshot)
6. several CS0579 Duplicate 'System.Reflection.Assembly...' errors appear in the build output in Visual studio, resulting in build fail (see the 2nd screenshot)
 
**Expected behavior**
No errors should appear, the solution should be built successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/12057824/66450948-6c6a2d80-ea28-11e9-8ba1-dd932b1cb5ef.png)
![image](https://user-images.githubusercontent.com/12057824/66450960-7429d200-ea28-11e9-8ae5-009dc0335e4e.png)

**Additional context**
I had email conversation regarding this bug with Cesar and Jake (my initial email was from 9/24)

**Comment by JakeRadMSFT** [comment]
Thanks for opening an issue!

It looks like this is because the .sln and .csproj are in the same folder. We should detect this case and exclude the folders from the .csproj.

**Comment by JakeRadMSFT** [comment]
Using this bug: #359 to track this issue.
