### ISSUE TITLE
A11y_Model Builder_Recommendation_Data_Info and Relationships: Screen reader is reading the Path information which is present in the "Data" screen twice.

### ISSUE THREAD

**Issue by Samhitha66** [dotnet/machinelearning-modelbuilder#2686]
### GitHubTags

#A11ySev3; #A11yTCS; #A11yWCAG2.1; #DesktopApp; #Win11; #Visual Studio Client; #SH_ModelBuilder_Win32_May2023; #Screenreader; #Narrator; #FTP; #Win32; #Benchmark; #NVDA; #STP; #Info and Relationships; #WCAG1.3.1;

### Actual Result
Screen reader is reading the Path information which is present in the "Data" screen twice.

Issue observed throughout the application.

Issue reproducible with NVDA.

### Expected Result
Screen reader should not read the Path information which is present in the "Data" screen twice.

### Environment Details
Application Name: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.6.1
Microsoft Windows 11 Enterprise 10.0.22621 Build 22621
Screen reader: Narrator, NVDA

### Repro Steps

1. Turn on Narrator/NVDA
2. Launch the Visual Studio with at least one of the .NET workload.
3. Tab till enable ML.NET Model Builder (Tools -> Options -> Environment -> Preview Features) and select it.
4. Create a new .NET project or open an existing .NET project.
5. Open context menu(Right-click) of the project in the solution explorer.
6. Tab till Add and then tab till Machine Learning Model and press enter.
7. Model Builder dialog will open. Tab till Scenario tab.
8. Select Scenario screen will appear.
9. Tab till "Recommendation" and press enter.
10. Setup environment screen will appear, Tab till Local CPU tile and select it.
11. Tab till Next button and press enter.
12. Data screen will appear.
13. Tab till path after connecting to server.
14. Verify whether the screen reader is reading the Path information which is present in the "Data" screen twice or not.

### User Impact

Screen reader user will not be able to get the proper information regarding the Path.

### Attachment
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/96fa36f2-2a15-48e2-aed7-32a6ef3b6e9e)
![Bug_Twice_Narrator](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/87918b78-f232-41f8-9399-653af129e5f0)
![Bug_Twice_NVDA](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/0860c807-c102-4f01-8c15-090b72c26031)

**Comment by zewditu** [comment]
are we able to keep the control type custom but change localizedcontrolType to  because the narrator use LocalizedcontroType to announce the control type

**Comment by zewditu** [comment]
@Samhitha66, ready to validate by Model builder version 16.17.0.2332602.

**Comment by Samhitha66** [comment]
Regressed the issue in the below environment
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.6.4
The issue is fixed. Hence closing the bug.
Please find the attachment for the reference.
#Regressed:06-30-23; #Closed;
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/5fdeb98d-3f33-4c96-a482-8965c10fc5a1)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/35d79eec-2562-4bf8-8f33-3a1c159b6a09)
