### ISSUE TITLE
I can't start training. 

### ISSUE THREAD

**Issue by AndreyTat1** [dotnet/machinelearning-modelbuilder#2688]
Torch runtime cannot be installed when Visual Studio is an elevated 'Admin' mode. Please use Model Builder from a non-elevated Visual Studio.
It says to me that I can’t start the training while I’m logged in as an administrator, how can I fix this

**Comment by AndreyTat1** [comment]
> 
I resolved the issue. I just created a new user on a computer that does not have administrator rights and gave him the rights to all the files that I need and everything worked, maybe it seems like some kind of trifling task, but it put me in a stupor. Maybe someone else will need it, so here's the solution, and I close the question.

**Comment by DeveloperNo579212** [comment]
A workaround to install torchsharp from aside is possible also?

**Comment by LittleLittleCloud** [comment]
> A workaround to install torchsharp from aside is possible also?

Yep, you can manually run the command under the designated work folder
