### ISSUE TITLE
ML.NET Model Builder creating muliple targets

### ISSUE THREAD

**Issue by fswitz** [dotnet/machinelearning-modelbuilder#269]
**System Information (please complete the following information):**
-- Model Builder Version: 16.0.1909.2101
--Visual Studio Version : 2019 16.3.2

**Describe the bug**
When adding the Machine Learning projects to a solution, different versions of frameworks/targets are created. 

Project:  WpfApp6 Target Framework .NET Framework 4.7.2
Project:  WpfApp6ML.ConsoleApp Target Framework  Net Core 2.1
Project: WpfApp6ML.Model Target Framework  .NET Standard 2.0

When I try to add the "using "WpfApp6ML.Model" to my WpfApp6 I get a "assembly or type not found error message" "type or namespace not found"

**To Reproduce**
1. Create a new WPF .Net project
2. Click Add "Machine Learning"
3. Verify the Project Properties ,  See what is created.

**Expected behavior**
Targets should be consistent for the ML.NET projects that are added. 

**Screenshots**

**Additional context**

**Comment by JakeRadMSFT** [comment]
Resolved in #271
