### ISSUE TITLE
All Scenarios: The "Data formatting" page is blank.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2690]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.16.0.2330501 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.5)
.Net: 6.0, 7.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The "Data formatting" page is blank.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select any scenario.
  5. On Data page, choose the data source.
  6. Click the "Advanced data options..." link, go to the "Data formatting" tab.
  
**Expected behavior**
The "Data formatting" page should be displayed normally.

**Screenshot**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/362e22c3-5e8c-48bc-96f4-1b1631348318)

**Additional context**

**Comment by zewditu** [comment]
Duplicate to https://github.com/dotnet/machinelearning-modelbuilder/issues/2709

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.16.0.2332001.
<img width="323" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/b01ca803-b579-4652-85d9-4089a7e03c8a">
