### ISSUE TITLE
I want my ML.NET model to work on my local page 

### ISSUE THREAD

**Issue by AndreyTat1** [dotnet/machinelearning-modelbuilder#2693]
Hello how can I do so what would this model work on my local page on the Internet? I have a button "Download photo" that takes a photo from the computer and in theory my model should process this photo and answer what it depicts how to implement it?

**Comment by luisquintanilla** [comment]
Hi @AndreyTat1,

Here are a few tutorials that show how to train computer vision models in ML.NET.

- https://learn.microsoft.com/dotnet/machine-learning/tutorials/image-classification-model-builder
- https://learn.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder

You might also choose to use an off-the-shelf ONNX model. This shows how to use those.

- https://learn.microsoft.com/dotnet/machine-learning/tutorials/object-detection-onnx

These tutorials show how to use an ML model in a Razor Pages app as well as an ASP.NET Core API and Azure Functions

- https://learn.microsoft.com/dotnet/machine-learning/tutorials/sentiment-analysis-model-builder
- https://learn.microsoft.com/dotnet/machine-learning/how-to-guides/serve-model-serverless-azure-functions-ml-net
- https://learn.microsoft.com/dotnet/machine-learning/how-to-guides/serve-model-web-api-ml-net
