### ISSUE TITLE
Where we get the 17.16.0.2328101 version? The latest version in VS2022 is: 17.16.0.2326802?

### ISSUE THREAD

**Issue by oybekrustamov** [dotnet/machinelearning-modelbuilder#2703]
Where we get the 17.16.0.2328101 version? The latest version in VS2022 is: 17.16.0.2326802?
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/49331271/ba677b0c-a5ba-4cf8-b5c3-1946174fd0d0)

_Originally posted by @oybekrustamov in https://github.com/dotnet/machinelearning-modelbuilder/issues/2642#issuecomment-1588632815_

**Comment by LittleLittleCloud** [comment]
@oybekrustamov It's internel build. The post you see if from our tester and we haven't release the fixed build yet
