### ISSUE TITLE
A11y_Model Builder_Model Builder_Data_Usability:Keyboard focus is going to non interactive content after expanding/Collapsing the "Show Undetected objects".

### ISSUE THREAD

**Issue by Samhitha66** [dotnet/machinelearning-modelbuilder#2704]
### GitHubTags

#A11ySev4; #A11yTCS; #A11yUsable; #DesktopApp; #Win11; #Visual Studio Client; #SH_ModelBuilder_Win32_May2023; #FTP; #Win32; #Benchmark;

### Environment Details

Application Name: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.6.2
Microsoft Windows 11 Enterprise 10.0.22621 Build 22621

### Repro steps

1. Launch the Visual Studio with at least one of the .NET workload.
2. Tab till enable ML.NET Model Builder (Tools -> Options -> Environment -> Preview Features) and select it.
3. Create a new .NET project or open an existing .NET project.
4. Open context menu(Right-click) of the project in the solution explorer.
5. Tab till Add and then tab till Machine Learning Model and press enter.
6. Model Builder dialog will open. Tab till Scenario tab.
7. Select Scenario screen will appear.
8. Tab till "Object detection" and press enter.
9. Setup environemnt screen will appear, Tab till Local CPU tile and select it.
10. Tab till Next button and press enter.
11. Data screen will appear.
12. Verify whether the Keyboard focus is going to non interactive content after expanding/Collapsing the "Show Undetected objects" or not.

### Actual Result

Keyboard focus is going to non interactive content after expanding/Collapsing the "Show Undetected objects".

### Expected Result

Keyboard focus should not move to non interactive content after expanding/Collapsing the "Show Undetected objects".

### User Impact

Keyboard users will face difficulty while navigating if keyboard focus is going to the non-interactive element.

### Attachment

![Bug_Non interactive_Usability](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/8e3d55a6-e086-4ec8-830c-57dde6019789)

**Comment by zewditu** [comment]
@Samhitha66   this  can be validated by a private build you can download from [here](https://microsoft.sharepoint.com/sites/PrivateBuildforAccessibility/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FPrivateBuildforAccessibility%2FShared%20Documents%2FMicrosoft%2EML%2EModelBuilder%20%2821%29%2Evsix&parent=%2Fsites%2FPrivateBuildforAccessibility%2FShared%20Documents
)

**Comment by Samhitha66** [comment]
@zewditu
We don't have access for the link which you provided in the above comment.
Please provide us the access. So that we will verify this bug.
#Regressed:07-13-23; #Pendinginput;

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/049db2e8-bf3a-4c88-a878-e29fcefaa4fc)

**Comment by Samhitha66** [comment]
@zewditu 
Regressed the issue in the below environment
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.8.0 Preview 1.0 [33912.440.main]
The issue is fixed. Hence closing the bug.
#Regressed:07-14-23; #Close;
![Bug_Focus Usability](https://github.com/dotnet/machinelearning-modelbuilder/assets/99243079/5048c67e-3dff-4cef-89ab-c98cd68ca832)
