### ISSUE TITLE
Advanced data data formating Tab is empty

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2709]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**Expected behavior**

**Screenshots**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/36615490/0b7843da-47b3-44f3-be21-18d229cea122)

**Additional context**
It is for all text-based scnearios

**Comment by luisquintanilla** [comment]
+1 I was able to repro as well.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.16.0.2332001.
<img width="330" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/9a37cf12-0a68-41d0-9327-7bd519ef0669">
