### ISSUE TITLE
ML.NET Model Builder can't find type or namespace

### ISSUE THREAD

**Issue by fswitz** [dotnet/machinelearning-modelbuilder#271]
I'm creating a simple ML WPF app with projects added with the ML Model Builder. 

The Model and Console App projects are added to the solution.  However, when I go to add the 

"using WpfApp2ML.Model;" to my main xaml.cs file "WpfApp2" I get the following error. 

"The type or namespace name 'WpfApp2ML.model' cannot be found...

This is the required step in the Code section of the "Build Your Machine Learning Model"  

Step 2. Consume the Model

Add the following using  …...using WpfApp2ML.Model;

This use to work just fine.  

I'm using Version 16.0.1909.2101 of the Model Builder

VS 2019 Community 16.3.2

**Comment by JakeRadMSFT** [comment]
Related #269. @fswitz  is #269 the same issue?

**Comment by fswitz** [comment]
Yes , this is the same issue

**Comment by fswitz** [comment]
Add the reference to the ML.Model  in the project "References" of the main app fixed the problem.  (methinks)
