### ISSUE TITLE
Tooltip is open by default

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2710]
<img width="933" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/16876986/1b6943a8-cf9f-40f4-a5ae-8638fb08ce62">

**Comment by luisquintanilla** [comment]
+1 This happens in stop strategy as well. 

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/46974588/e1f317fc-3948-4cc0-ab16-afc3282e6364)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the main build 17.16.0.2331601.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/f8bef2ef-43e2-4ad4-a1da-7b756a85f9d3)
