### ISSUE TITLE
Label and icon not aligned 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2711]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/36615490/b5552ce5-1365-43f1-819b-8bfefe472ea0)
**Additional context**

**Comment by v-Hailishi** [comment]
The bug has been fixed on the main build 17.16.0.2331601.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/e0c55c17-58be-4333-be2d-1afbdbc40578)
