### ISSUE TITLE
Training fails immediately for data classification scenario

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2712]
Configuration:

start multiclass classification
Evaluate Metric: MacroAccuracy
Available Trainers: SDCA,LBFGS,LGBM,FASTTREE,FASTFOREST
Training time in second: 10
Max Model To Explore: 20
Maximum Memory Usage in MB: 50
Tuner: grid

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/46974588/628b2dc9-327c-4f0c-b2d3-d7cf27cd5f05)

Log File: 
[MLModel2-3CCFN1.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/11750332/MLModel2-3CCFN1.txt)

**Comment by luisquintanilla** [comment]
This was due to memory being too low (50MB).

**Comment by LittleLittleCloud** [comment]
Fix: set minimum memory restriction to 500MB

**Comment by v-Hailishi** [comment]
The bug has been fixed on the main build 17.16.0.2331601.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/cf2f6c40-a31e-4a07-a44d-050ad03180e3)
