### ISSUE TITLE
Use same wording for time to train labels

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2713]
Use **Time to Train (seconds)** for both labels.

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/46974588/113240ef-eb93-467b-92ee-de2c8c4418a4)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the main build 17.16.0.2331601.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/8fd6be0a-043e-4d65-a228-af55df75d824)
