### ISSUE TITLE
I cant select the "Column To Predict"

### ISSUE THREAD

**Issue by dakyion** [dotnet/machinelearning-modelbuilder#273]
Hi, I am trying to test and learn ml.net so a followed the tutorial on MS website

A problem encountered on [https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data]()
**Operating System**: _windows 10_
**Visual Studio Version**: _Community 2019 16.2.3_ 
I am using the example from the link above 
It ordered me to download that .tsv file 
When I enter the link provided I go to a page with special text format 
I save it as .tsv file into the project folder 
 I choose the right scenario and then I choose **File** as a source of input
When **selecting the file** I can't browse to it, 
so I tried copying file name, and **selecting column** didn't work, I tried copying the full directory link of the file, the same problem 

I wish you fix the problem or show me a way to do that.

This is the link I used 
[https://raw.githubusercontent.com/dotnet/machinelearning/master/test/data/wikipedia-detox-250-line-data.tsv]()

and Thanks!

**Comment by JakeRadMSFT** [comment]
@dakyion closing this issue due to lack of response. If you're still running into this issue with the latest model builder version please re-open!
