### ISSUE TITLE
Local object detection doesn't work

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2730]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  Dev16 latest main
 - Visual Studio Version

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.17.0.2332602.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/3108cefd-15a5-4164-b852-0531abdd0819)
