### ISSUE TITLE
Add object detection to the ML.NET CLI

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2736]
Add object detection (local) scenario to ML.NET CLI.

**Comment by LittleLittleCloud** [comment]
Proposed CLI command


## subcommand
object-detection

## available options
### Dataset option
- dataset // path to dataset label file, can be coco/vott or tsv(if supported)
- test-dataset // path to test-dataset
### Train option
- device // cuda or cpu .default is cpu,
- width // resize width, default is 800
- height // resize height, default is 600
- batch // batch size, default is 20
- epoch // epoch size, default is 10
- seed // default is null
- score-threshold // default is 0.95
- iou-threshold // default is ??
### Output option
- name // output project name
- output // output folder

### Other option
- verbose
- log-file-path

**Comment by LittleLittleCloud** [comment]
released in `16.17.17`
