### ISSUE TITLE
Forecasting scenario graph is not able to preview 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2743]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/36615490/de74e137-255a-43c6-97db-c8240429a7c1)

**To Reproduce**
1. Go to Forecasting scenario
2. Select data set 
3. Click Graph Radio button

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.17.0.2350402.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/a2ba3fac-25ce-4e93-9cb8-bdfa0c3979dc)
