### ISSUE TITLE
I Ran Into a Problem

### ISSUE THREAD

**Issue by khalidAlmadani98** [dotnet/machinelearning-modelbuilder#2744]
**System Information (please complete the following information):**
 - Model Builder or CLI Version:  I could'nt find it 
 - Visual Studio Version (if applicable): v17.5.4
 
**when I copied the code I had errors**
- On which page of the tutorial did you run into an issue ([URL](https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/consume)):
- Clear description of the problem:
- when I copied the code I had errors
- The problem is about version of c#

**To Reproduce**
1. Go to 'Program.cs'
2. Click on 'the code'
3. paste 'code'

**Expected behavior**
I expected that when I copy the code it will have no errors and run smoothly 

**Screenshots**

<img width="558" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/78568064/21b8721a-271b-45f6-b16c-120f4c520bba">

<img width="636" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/78568064/ce5e312b-50f5-4599-bb30-82235f41307e">

<img width="594" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/78568064/0c22a599-3031-4796-939d-691ae9da71e3">

<img width="722" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/78568064/52e48195-8542-4083-8140-f5e890d1f5b4">

<img width="752" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/78568064/4f21a102-0864-4f46-be30-e547bf64b61d">

**Additional context**

**Comment by LittleLittleCloud** [comment]
The generated code from model builder requires a higher lang version, maybe add that in your .csproj?

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/16876986/f2278a15-f046-448d-b41a-09f9da9112c8)

**Comment by LittleLittleCloud** [comment]
Close due to no respond. feel free to reopen it if you have further question
