### ISSUE TITLE
Text classification: The prediction score should be calibrated and normalized to 1 for the generated Console App and Web API projects.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2746]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.17.0.2336301 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.5)
.Net: 6.0, 7.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The prediction score should be calibrated and normalized to 1.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select "Text classification" scenario.
  5. Choose "**Local (CPU)**" environment.
  6. On the Data page, choose data source to complete the training.
  7. Go to the Consume page, click "Add to solution" button to generate the Console App and Web API projects.
  8. Debug the generated Console App and Web API projects and check the prediction score.
  
**Expected behavior**
The prediction score should be calibrated and normalized to 1.

**Screenshot**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/04462712-6894-4d67-906b-6f4fb73f5466)

**Additional context**

**Comment by v-Hailishi** [comment]
This issue has been discussed in bug #2360, but it was closed. Hence, I open this new bug to tracking the issue.

**Comment by LittleLittleCloud** [comment]
@zewditu Can you take a look at it?

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.17.0.2340401.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/f7062ad8-90e0-4536-8788-e42303916ac3)
