### ISSUE TITLE
error after train model

### ISSUE THREAD

**Issue by sh653** [dotnet/machinelearning-modelbuilder#2752]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
Can you provide more details on the error you have.

**Comment by LittleLittleCloud** [comment]
@sh653 Can you combine your issue into one and try avoiding pasting stacktrace in the title?

**Comment by LittleLittleCloud** [comment]
close due to no respond, feel free to reopen it if you have any other issues.
