### ISSUE TITLE
Possible Missing Feature

### ISSUE THREAD

**Issue by BrandonHilligenn** [dotnet/machinelearning-modelbuilder#2754]
**System Information (please complete the following information):**
 - Model Builder Version 17.17.0.2332602: 
 - Visual Studio Version 17.5.5

**Describe the bug**
- On which step of the process did you run into an issue: Selecting a scenario.
- Clear description of the problem: I am trying to create a custom scenario using the model builder but the option to create a custom scenario is not visible on the model builder UI anymore, and I cannot seem to find it. 

**To Reproduce**
1. Add Machine Learning Model to project
2. See available scenarios

**Expected behavior**
To be able to see and use the custom scenario

**Additional context**

**Comment by LittleLittleCloud** [comment]
The custom scenario was removed long time ago. Can you let us know which specific scenario you want to create for the "custom scenario"?

**Comment by LittleLittleCloud** [comment]
close due to no respond, feel free to reopen it if you have any other issues.

**Comment by madcodres** [comment]
i tried to create a question answering model, the training section has no responding. Still showing training.
