### ISSUE TITLE
Model Builder Error: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by rgoudie** [dotnet/machinelearning-modelbuilder#2755]
**System Information:**
 - Model Builder Version: **16.14.0.2255902**
 - NuGet version of Microsoft.ML: **2.01**
 - Visual Studio Version: **17.6.5**

**Describe the bug**
- An exception is thrown during the **Train** step of the Forecasting scenario.
- I have a TSV file with numeric data. The file contains 552,671 lines and is 61,584,631 bytes.

**To Reproduce**
1. Start the Forecasting scenario.
2. Load the TSV file and select the **TARGET** column as the column to predict and the **DateTime** column as the Time series column.
3. Advance to the **Train** step.
4. Enter 11000 as the time to train (seconds) and 1 as the Horizon.
5. Wait a few minutes and the exception will be thrown.

**Expected behavior**
Step completes without an exception being thrown.

**Screenshots**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/34731480/863561ac-bf63-48ce-970c-eda53b67d730)

**Additional context**
I can provide a private 7z archive copy of the TSV file.

**Comment by LittleLittleCloud** [comment]
@rgoudie We pushed a fix in the latest release which haven't been inserted into visual studio yet. Try updating model builder to latest version (17.16.*)

**Comment by rgoudie** [comment]
I am experiencing connection issues when trying to access the Update tab in the Manage Extensions window. I will try again to update my extensions at a later date.

**Comment by rgoudie** [comment]
I managed to update the ML.NET Model Builder 2022 extension to version 17.17.0.2332602 and it worked to completion without throwing any exceptions. Thanks!
