### ISSUE TITLE
No se puede encontrar una parte de la ruta de acceso '.\_124820758_pug1.jpg'.

### ISSUE THREAD

**Issue by Code-Innpulsa** [dotnet/machinelearning-modelbuilder#2756]
en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   en Microsoft.ML.Data.ImageLoadingTransformer.Mapper.<>c__DisplayClass4_0.<MakeGetterImageDataViewType>b__1(MLImage& dst)
   en Microsoft.ML.Transforms.Image.ImageResizingTransformer.Mapper.<>c__DisplayClass3_0.<MakeGetter>b__1(MLImage& dst)
   en Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionTrainer.Trainer.PrepareData(ValueGetter`1 labelGetter, ValueGetter`1 imageGetter, ValueGetter`1 boundingBoxGetter)
   en Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionTrainer.Trainer.TrainStep(IHost host, DataViewRowCursor cursor, ValueGetter`1 boundingBoxGetter, ValueGetter`1 imageGetter, ValueGetter`1 labelGetter, IProgressChannel pch)
   en Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionTrainer.Trainer.Train(IHost host, IDataView input, IProgressChannel pch)
   en Microsoft.ML.TorchSharp.AutoFormerV2.ObjectDetectionTrainer.Fit(IDataView input)
   en Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   en Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   en Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   en Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.ML.ModelBuilder.AutoMLService.LocalObjectDetectionExperiment.<ExecuteAsync>d__13.MoveNext() en /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalObjectDetectionExperiment.cs:línea 133
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__21.MoveNext() en /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:línea 169

**Comment by LittleLittleCloud** [comment]
I don't know this language but based on my guess it's grumbing about missing file. Can you check if all path exist in your label file?

**Comment by LittleLittleCloud** [comment]
close due to no respond, feel free to reopen it if you have any other issues.
