### ISSUE TITLE
column to predict is not getting loaded even if I give a simple 3 column CSV

### ISSUE THREAD

**Issue by haligeorge** [dotnet/machinelearning-modelbuilder#2758]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
@haligeorge Can I have the dataset you have for debugging, thanks

**Comment by LittleLittleCloud** [comment]
Close due to no respond, feel free to reopen it if you have any other questions
