### ISSUE TITLE
Try It Out - Working with Sparse Data

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#276]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1910.901
 - Visual Studio Version: VS 2017 15.9.16

When the file contains sparse/missing data, not all values in the *Try your model* are filled in. Therefore, the model can't really be tried. 

![image](https://user-images.githubusercontent.com/46974588/66523115-14c9d180-eabd-11e9-811b-d984e24fdb3c.png)

**Comment by JakeRadMSFT** [comment]
Thanks for filing this issue!

**Comment by zewditu** [comment]
@luisquintanilla  can I have the dataset you used to reproduce the bug ?

**Comment by luisquintanilla** [comment]
The dataset can be downloaded from the following [link](https://data.sfgov.org/api/views/pyih-qa8i/rows.csv?accessType=DOWNLOAD)

**Comment by JakeRadMSFT** [comment]
Let's look at the first 10 and see if there is a "best" row- one the has all the column filled out or most columns filled out. If not default to first row.

Update text to say using row 1 or row 7, etc..

**Comment by LittleLittleCloud** [comment]
![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/eb2c86ab-4465-43e9-8068-977962649bbd)
Still get this error
Maybe we need to improve error msg here, by telling user which field/input string is missing/in wrong format

**Comment by zewditu** [comment]
Yes, we should work on data validation

**Comment by LittleLittleCloud** [comment]
We should allow user not fill all fields in try it out, at least `AutoMLService` supports that (it will just fill the empty field with default value)

**Comment by zewditu** [comment]
How we decided that  default value?

**Comment by LittleLittleCloud** [comment]
Just null should be fine. Let me double check

**Comment by LittleLittleCloud** [comment]
I can fix that in AutoMLService, it seems to be a bug in that. No worries
