### ISSUE TITLE
Visual Studio is not working. If I try to create a new project in Visual Studio it takes forever ...?

### ISSUE THREAD

**Issue by chalnicolas** [dotnet/machinelearning-modelbuilder#2760]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable): 2022

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
Which project are you trying to create

**Comment by LittleLittleCloud** [comment]
Close due to no respond. Feel free to reopen this issue if you have any further questions
