### ISSUE TITLE
Add AMD/ROCM support to ML.NET

### ISSUE THREAD

**Issue by Selbyl** [dotnet/machinelearning-modelbuilder#2764]
ROCM is being supported more on Windows recently. 

I know AMD isn't as popular as Nvidia for AI, but is ther any future of updating ml.net to support PyTorch with ROCM?

**Comment by LittleLittleCloud** [comment]
The torch support from ML.Net is powered by torchsharp. So it will be depends on whether ROCM support is on torchsharp's roadmap.

**Comment by luisquintanilla** [comment]
Hi @Selbyl,

Thanks for opening this issue. Since this work would happen in the framework, I've opened an issue in that repo and you can track progress there. Closing this issue.

dotnet/machinelearning#6899
