### ISSUE TITLE
ModelBuilder is unable to download resnet_v2_50_299.meta

### ISSUE THREAD

**Issue by fmmsainco** [dotnet/machinelearning-modelbuilder#2771]
Model Builder is unable to download resnet_v2_50_299.meta file when it does training 

[Source=AutoMLExperiment-ChildContext, Kind=Info] [Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] Downloading resnet_v2_50_299.meta from https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta to C:\Users\fmmsa\AppData\Local\Temp\MLNET\resnet_v2_50_299.meta

**Comment by LittleLittleCloud** [comment]
@fmmsainco maybe a transient bug on resource server, can you try again?

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it for further questions
