### ISSUE TITLE
Model Builder. 

### ISSUE THREAD

**Issue by Suriyan1993** [dotnet/machinelearning-modelbuilder#2772]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luisquintanilla** [comment]
Hi @Suriyan1993 

Based on this issue we don't know what errors / issues you're running into. Please feel free to open a new issue with more details so we can best assist you.
