### ISSUE TITLE
Results of Try your model for image stays even when select "Test another image"

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#278]
In Evalute - Try your model, when you upload an image and predict, then click "Test another image", the Results stay there, even though there is no image preview. When you select the new image, the results for the last image are still there until you hit "Predict" again

1. Add sunny image and hit Predict:
![image](https://user-images.githubusercontent.com/10437687/66524659-e5f53080-eaa7-11e9-96f8-d2794fdb6530.png)

2. Remove sunny image:
![image](https://user-images.githubusercontent.com/10437687/66524648-daa20500-eaa7-11e9-93f0-1f3793161f53.png)

3. Add new image (but don't hit Predict):
![image](https://user-images.githubusercontent.com/10437687/66524629-c9f18f00-eaa7-11e9-8ec2-c0f4b244b122.png)

**Comment by JakeRadMSFT** [comment]
Thanks for reporting Bri!
