### ISSUE TITLE
not able to install this extension on my windows 11 on arm system

### ISSUE THREAD

**Issue by SCIEN-00** [dotnet/machinelearning-modelbuilder#2783]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 17.17.0.2332602
 - Visual Studio Version 17.7.6
 - Processor: Snapdragon (TM) 7c @ 2.40 GHz   2.40 GHz
 - Installed RAM: 8,00 GB (7,57 GB usable)
 - System type: 64-bit operating system, ARM-based processor
 - Edition: Windows 11 Pro
 - Version: 23H2
 - OS build: 22631.2506
 - Experience: Windows Feature Experience Pack 1000.22677.1000.0

**Describe the bug**
While trying to install model builder I got error
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/11405851/5273cc09-efa2-4462-9fa8-82c6248bd315)

It seems that the issue is that I have ARM64 system.
In GitHub under [Prerequisites](https://github.com/dotnet/machinelearning-modelbuilder#prerequisites) or limitation there is no mentioned about processor architecture requirement. It would be nice to add this bit of information.

**Comment by LittleLittleCloud** [comment]
@SCIEN-00 Thanks for reporting this. We just push a fix on our main branch which upgraded VS SDK build tools to support arm64 device and that build will be included in the next release

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.17.0.2360101.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/c4eb4633-d669-4b11-973d-c762f439ca90)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/bdc9c310-b38d-4399-84b6-edf74db61251)
