### ISSUE TITLE
After adding the data when we are selecting the column to predict, at that time we are not getting any value in dropdown.

### ISSUE THREAD

**Issue by Shalin005** [dotnet/machinelearning-modelbuilder#2786]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 17.17.0
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/data
- Clear description of the problem: After adding the data when we are selecting the column to predict, at that time we are not getting any value in dropdown.

**To Reproduce**
1. Go to 'SentimentModel.mbconfig'
2. Click on 'data'
3. Scroll down to 'column to predict'

**Expected behavior**
after clicking on the column to predict dropdown, we are not getting any value.
It should display col0 and col1.

**Screenshots**
![Screenshot (83)](https://github.com/dotnet/machinelearning-modelbuilder/assets/150894727/68d516fc-016f-4f5f-93e8-0ad60db20f58)

**Comment by samirkatore** [comment]
I am facing the same issue, I see this issue is closed but with no resolution, or am I missing anything here?
