### ISSUE TITLE
Extra commas + extra/missing spaces

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#279]
In the Evaluate - Details, there is a space between some of the Input Column (Feature) names and the commas AND there is an extra comma at the end:
![image](https://user-images.githubusercontent.com/10437687/66525099-3a4ce000-eaa9-11e9-8e2d-3d216a938290.png)

In Code - 3. Improve your model, a space was removed beween "or" and "learn":
![image](https://user-images.githubusercontent.com/10437687/66525137-5fd9e980-eaa9-11e9-91a6-6f1c18a7e1a2.png)

Also in Code, the project names were added back before the projects are actually generated:
![image](https://user-images.githubusercontent.com/10437687/66525249-b21b0a80-eaa9-11e9-9b44-d610e35e5b7e.png)

**Comment by zewditu** [comment]
@briacht  what is should be displayed  here when we landed to Code page 
![Capturebug.PNG](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/ef2f32cc-de38-49d1-924b-1bd824e8e733)


or could we make it empty until the user clicks add project?

**Comment by briacht** [comment]
@zewditu "Add the machine learning model and the projects and references for model consumption, training, and testing to your solution."

**Comment by LittleLittleCloud** [comment]
validate on VS2019, VS 2019 preview
