### ISSUE TITLE
Model Builder threw an exception at the completion stage of model training.

### ISSUE THREAD

**Issue by SKYC829** [dotnet/machinelearning-modelbuilder#2792]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  
17.15.0.2337001
 - Visual Studio Version
 17.8.2

**Describe the bug**
After completing model training, when attempting to add the Microsoft.ML package to the project in Model Builder, an exception occurred: Couldn't find project named xxxx.csproj (Microsoft.ML.ModelBuilder.Utils.Logger.Info). Exception message: Value cannot be null, parameter name: project.

**To Reproduce**
1. Prepare training data
2. Choose environment
3. Begin traning and wait for finish.

**Expected behavior**

**Screenshots**
![图片](https://github.com/dotnet/machinelearning-modelbuilder/assets/60951390/82cfe64b-d8cf-403f-a100-49db60601ceb)

**Additional context**
logfile:
[BaiduNewsModel-WPNRZM.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/13522509/BaiduNewsModel-WPNRZM.txt)

**Comment by LittleLittleCloud** [comment]
Could you upgrade your ModelBuilder to v17.17.*? We published a fix for that issue in the last release.
