### ISSUE TITLE
Question Answering: Training failed with error "Splitter/consolidator worker encountered exception while consuming source data".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2793]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.17.0.2357101 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.7.7)
.Net: 6.0,7.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training failed with error "Splitter/consolidator worker encountered exception while consuming source data".

**TestMatrix**
[squad-train.tsv.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/13522925/squad-train.tsv.zip)

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Question Answering"** scenario.
  5. On Data page, choose the data source, column and data type like below.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/2d25cef5-98a8-4e8f-9be9-4317f14153ea)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/f836c5ca-7a2e-44bb-916c-5ba302680505)
  6. On the Train page. click "Start training".
  
**Expected behavior**
Training successfully.

**Screenshot**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/7cba6ba6-9a95-4171-b6ac-142bfd60e580)

**Additional context**
Adding attached file to SQL Server and using SQL Server file to train, training is also failed.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/78912939-b663-4486-ba82-acf580d0cb97)

**Comment by zewditu** [comment]
log file : [QAlogFile.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/13530917/QAlogFile.txt)

**Comment by v-Hailishi** [comment]
@zewditu Verified on the latest main build 17.17.0.2360601, the message dialog can tell which row has a bad data when using file data.
[squad-train.tsv.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/13608240/squad-train.tsv.zip)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/24ad85fa-b9b8-453c-ae8b-f44c44b1d961)
After changing the bad data, the training can start, but the output window still prompts there are 295 format errors.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/4f84e08d-6df1-4b7b-9ce1-4b468a6837da)

**Besides the training is still failed with error "Splitter/consolidator worker encountered exception while consuming source data" when using SQL server data.**
[test_SQL_DB.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/13596862/test_SQL_DB.zip)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/269a05a3-f73c-4422-902d-124c6d0abafb)

**Comment by v-Hailishi** [comment]
The bug can be fixed on the latest main build 17.17.0.2406001 after doing the following resolution.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/22f0cd49-ce56-45c4-9dd8-310d5afe0b96)

1. For file data, after adding extra quotes around texts, you need to close the dataset, don't open it in Excel.
2. For SQL server data, when import the text file in SQL Server, you need to change the data type to "Text" for columns "context, question, answer".
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/699e512c-220e-43d2-bfde-30d4e51927eb)
