### ISSUE TITLE
Sentence similarity: Error pop-up when you generate the console app project at the first time.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2794]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.17.0.2357101 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.7.7)
.Net: 6.0,7.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Error pop-up when you click the "Add console app to solution" link at the first time.

**TestMatrix**
Error pop-up when you generate the console app project at the first time.

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select **"Sentence similarity"** scenario.
  5. On Data page, choose the data source to complete the training.
  6. On the Consume page, click the "Add console app to solution" link, then click "Add" button.
  7. You will see the pop-up error "**The JSON-RPC connection with the remote party was lost before the request could complete**".
  
**Expected behavior**
The console app project can be generated successfully at the first time.

**Screenshot**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/20402932-b230-4a8d-a4d3-76813273fb0b)

**Additional context**
1. If you click the "Add console app to solution" link to generate again, it can be successfully.
2. Sometimes this error also repro on the Train page for "Forecasting", "Object detection", "Text classification" scenario.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/805c2019-2a22-41bc-9e76-54104f740ad6)

**Comment by v-Hailishi** [comment]
@LittleLittleCloud Verified on the latest main build 17.17.0.2362801, The bug is still repro on scenarios: Forecasting, Text classification, Sentence similarity.
1. Forecasting: Choosing "**random**" tuners to train SQL Server data source, the training would be failed.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/833a02f4-d256-4f9b-820d-a3153906bbb8)
2. Text classification: 
   -- Choosing **"Cross validation"** data strategy, the training would be failed.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/bea38dc9-c7ba-48f8-afac-c6487626d34a)
   -- Choosing "Split" data strategy, the training can be successfully, but it is failed when you generate the console app project at the first time.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/73986d56-5f45-442e-bcf2-74ce45595404)
3. Sentence similarity: 
   -- Choosing **"Cross validation"** data strategy, the training would be failed.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/fc750c86-b9f3-4ba2-9d6e-c1e1bc75c1ad)
  -- Choosing "Split" data strategy, the training can be successfully, but it is failed when you generate the console app project at the first time.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/79992c11-8301-49ef-ac6a-038c19ccacf7)

**Comment by LittleLittleCloud** [comment]
I wonder if it's related to loading/reloading torch model according to what I found from event viewer

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/16876986/5c8c9158-53c9-4b3f-9d7f-603e0a06ed61)

**Comment by v-Hailishi** [comment]
The bug is not repro on the "u/xiaoyun/0125" build [17.17.17.2407507](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8977838&view=results).
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/4107fd87-e5ba-4ffc-841a-09d44c75b97e)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/6f94185f-5c21-486a-9a7d-86a11a9cef41)

**Comment by Megasoft2** [comment]
Hi. Based on Ml.NET and Nvidia. (VS 2022)
Any resolution?

Sincerely.

**Comment by LittleLittleCloud** [comment]
@Megasoft2 which model builder version are you using

**Comment by Megasoft2** [comment]
Hi @LittleLittleCloud 
Based on VS 2022 Preview 3.0 -> Natural Language Processing: Text Classification (Preview)
It worked for me

Thx.
Greetings.
