### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#280]
Add additional information logged to Logger.cs

1. Print stack trace etc. to console so customers can send it to us
2. Include more description in error message (e.g. You've hit an unexpected exception - "blah blah".  Please see console for more details.

**Comment by JakeRadMSFT** [comment]
Lets try to get this in for Ignite.

**Comment by LittleLittleCloud** [comment]
[#PR](https://github.com/dotnet/machinelearning-tools/pull/373)
