### ISSUE TITLE
Error on multiclass TryItOut with binary data

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#281]
**Model Builder Version**: master

**Bug description**
Getting error `Invalid call to GetGetter` while using Try it Out. My data set is binary (forgery or not forgery), but I chose multi-class for training. It passed training, but has this error when I Try it Out. 

**Steps to Reproduce**
1. Use attached data set
2.  Select multi-class scenario
3. Go to Try your Model. Click Predict 

[dataset](https://app.zenhub.com/files/186917455/0c57f7d4-1943-43b3-bf46-0484304411bc/download)

StackTrace	"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__94`1.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.ML.ModelBuilder.AutoMLServiceFactory.AutoMLServiceProxy.<PredictMultiClassClassificationAsync>d__10.MoveNext() in C:\\Repos\\ML.NET\\Microsoft.ML.ModelBuilder\\AutoMLServiceFactory.cs:line 61\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.ML.ModelBuilder.TrainSession.<PredictMultiClassClassificationAsync>d__33.MoveNext() in C:\\Repos\\ML.NET\\Microsoft.ML.ModelBuilder\\TrainSession.cs:line 97\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.ML.ModelBuilder.TrainModelToolWindowControl.<TryItOut_Click>d__63.MoveNext() in C:\\Repos\\ML.NET\\Microsoft.ML.ModelBuilder\\ToolWindows\\TrainModelToolWindowControl.xaml.cs:line 1208"	string

**Comment by JakeRadMSFT** [comment]
Error is because label column isn't strings. It's trying to convert numbers back to labels but the labels were number originally. I'll handle that case :)

**Comment by JakeRadMSFT** [comment]
Related  #277
