### ISSUE TITLE
Issue Classification scenario crashes VS

### ISSUE THREAD

**Issue by tmeschter** [dotnet/machinelearning-modelbuilder#282]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1909.2101
 - Visual Studio Version: 16.3.4

**Describe the bug**

When trying to load a .tsv file in the Issue Classification scenario VS crashes with the following dialog:

![image](https://user-images.githubusercontent.com/10506730/66684758-a0fc0600-ec2f-11e9-89ba-42adc6e1aa95.png)

**To Reproduce**
1. Create a new .NET Core 3.0 Console Application.
2. Right-click on the project and select "Add | Machine Learning".
3. Click "Issue Classification"
4. Select the ProjectSystemIssueLabels.tsv file (from the ProjectSystemIssues.zip file below)
5. VS crashes with an "unknown software exception".

[ProjectSystemIssues.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/3719606/ProjectSystemIssues.zip)

**Expected behavior**

.tsv file is loaded successfully.

**Comment by JakeRadMSFT** [comment]
@tmeschter is there anything else using that file? I think this might be a known issue that we're fixing in the next release.

**Comment by tmeschter** [comment]
@JakeRadMSFT I don't believe anything else was using that file, no.

**Comment by JakeRadMSFT** [comment]
This should be resolved in latest release. Please re-open if you're still hitting this issue.
