### ISSUE TITLE
It is not predicting rather doing pop up for error  "col1 was expected to be Single but couldn't be parsed"

### ISSUE THREAD

**Issue by KumarChandra-iima** [dotnet/machinelearning-modelbuilder#2820]
Unsure what went wrong that it is not working.

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/155680429/0febc88b-60ae-4c93-8c9c-13eb7eb77639)

**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@KumarChandra-iima what your scenario is your scenario?
could you double check the datatype of col1 in advanced data option? 
it seem that its type is "Single" but the value you provided is not able to be parsed into type single.
If you tell us more detailed information we can help more .

**Comment by KumarChandra-iima** [comment]
Fixed!

Actually I was supposed to use the other column. only column configuration
was required to be adjusted.
