### ISSUE TITLE
Object Detection-Local: The generated Console App and Web API projects are running failed.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2829]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.17.17.2407507 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.2.0)
.Net Core: 6.0,7.0,8.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The generated Console App and Web API projects are running failed.

**TestMatrix**
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder#create-a-new-vott-project

**To Reproduce**

1. Select Create a new project from the Visual Studio start window.
2. Choose the C# Console App (.NET Core) project template.
3. Add model builder by right click on the project.
4. Select "Object Detection" scenario>Local (CPU).
5. On Data page, choose the data source to completed training.
6. Go to the Consume page, click "Add to solution" button to generate Console App and Web API projects.
7. Run the generated Console App and Web API projects.

**Expected behavior**
The generated Console App and Web API projects should be running successfully.

**Gif:**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/75c96f32-ca7b-4b43-a566-547b98a52702)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/fc7eabcb-e572-49f6-b8da-cef65eea3098)

**Additional context:**
The bug is repro on scenarios: Object Detection-Local, Text classification, Sentence similarity, Question Answering.

- Text classification
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/12549bb4-037f-432b-beac-17388fd783c9)

- Sentence similarity, Question Answering
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/f8e1bf58-2dec-43f1-a19c-050e7f22cff4)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/4c69061f-7a09-4125-b832-42498e180271)

**Comment by zewditu** [comment]
I think it is Torchsharp version conflict could you try from the latest main?  We updated it.

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.17.17.2408101.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/8365fdb2-b3cb-47e1-8011-fe664ef5eaf4)
