### ISSUE TITLE
Sentence similarity: Training failed with error "Training time finished without completing a successful trial." when training file data source.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2837]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.17.17.2408103 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.8.5)
.Net Core: 6.0,7.0,8.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training failed with error "Training time finished without completing a successful trial." when training file data source.

**TestMatrix**
https://github.com/dotnet/machinelearning-modelbuilder/files/10534387/home-depot-sentence-similarity-small.csv

**To Reproduce**

1. Select Create a new project from the Visual Studio start window.
2. Choose the C# Console App (.NET Core) project template.
3. Add model builder by right click on the project.
4. Select "Sentence similarity" scenario.
5. On the Data page, choose the **file** data source.
6. On the Train page, click "Start training" button, you will see the error message "Training time finished without completing a successful trial.

**Expected behavior**
Training successful.

**Screenshot:**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/e4cca14d-d6d6-436f-b463-c82f59f9b233)

**Additional context:**
The bug is **not repro** when training the SQL server data. I generated the SQL Server data using the same text [file](https://github.com/dotnet/machinelearning-modelbuilder/files/10534387/home-depot-sentence-similarity-small.csv).

**Comment by zewditu** [comment]
What is your advanced data option data formatting settings?

**Comment by v-Hailishi** [comment]
@zewditu My advanced data option data formatting settings just like below, "Allow quoting" is NO by default.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/6f05d303-c5e0-46f3-ab92-bd152e0d7f11)

After making it to "Yes", the training can be successfully. **Hence is above fails expected?**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/5fd73557-9646-4906-8d43-3ac82bcc732a)
