### ISSUE TITLE
mlnet cli incorrectly parsing training data

### ISSUE THREAD

**Issue by earle36** [dotnet/machinelearning-modelbuilder#2848]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): mlnet cli version 16.8.0
 - Visual Studio Version: n/a

**Describe the bug**
- On which step of the process did you run into an issue:  using mlnet classification generated csproj code
- Clear description of the problem: my multi class classification dataset is a csv that contains double quotes on some row columns since the text in the column contains commas. Using the mlnet cli to create a new classification model with the csv that contains this type of data results in a model that contains many classes that are inadvertently added due to incorrect parsing of the csv during training. 

It looks like it was introduced with the addition of the new allowQuoting flag in the mlcontext.Data.LoadFromTextFile<>() method in Version 3.0.1 of Microsoft.ML package.

I noticed in the generated class a new const RetrainAllowQuoting was added to the file - but it the value is false which tipped me off that is likely the culprit. 

May want to add allowQuoting parameter to the cli tool or correctly determine the value  prior to training and creating the model.

**To Reproduce**
1. Create a 2 column csv (with header row). The first column will contain data that is double quoted and contain text with commas e.g. “this is , by far, the best cheesecake I’ve ever had”, while the second column contains the label for the row. Add several rows with this type of data and only have 2 different labels in the 2nd column.
2. Train a model using mlnet classification—dataset “your dataset” —has-header true
3. Run the sample generated project and observe more model classes than expected are present.
4. Also observe the RetrainAllowQuoting const is set to false in the .training.cs file.

**Expected behavior**

add allowQuoting parameter to the cli tool or correctly determine the value prior to training and creating the model so the model has the correct expected number of classes.

**Screenshots**

**Additional context**

**Comment by LittleLittleCloud** [comment]
@earle36 I'm working on adding `allowQuoting` option to cli, so is it possible to share the dataset with us so we can verify the fix?

Thanks

**Comment by earle36** [comment]
Unfortunately I'm unable to share that dataset due to restrictions with work but I've created a sample and was able to reproduce the issue...

[SampleData.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/14274871/SampleData.csv)

 Hopefully this helps!

**Comment by LittleLittleCloud** [comment]
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/16876986/4e084d4b-63bf-4ab6-b219-c1d48e4ce308)

fix verified, will make a publish later today

The fix adds an `--allow-quote` flag in cli which default to false, so you might want to explicitly set it to true in your command line

**Comment by earle36** [comment]
That’s wonderful news!

**Comment by LittleLittleCloud** [comment]
FYI I just released the new cli (16.18.2). It may take a while for the package to show on nuget though

**Comment by earle36** [comment]
I have installed the latest and verified it’s working as expected now using the new allow-quote flag.
Thanks!

**Comment by dliedke** [comment]
Thanks a lot for the new option! Worked fine here! "--allow-quote true" option working for CSV with double quotes.
