### ISSUE TITLE
The type or namespace "ML" does not exist in the namespace "Microsoft"

### ISSUE THREAD

**Issue by htzhang2** [dotnet/machinelearning-modelbuilder#2851]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable): 2022 version 17.9.0

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/consume
- Clear description of the problem: Compile error

**To Reproduce**

**Expected behavior**
ML.Net nuget package is added after consume stage.

**Screenshots**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/4983284/72a76893-dae2-4de2-a25c-e02c01ce23c4)

**Additional context**

**Comment by zewditu** [comment]
@htzhang2  What version of Model Builder you use? The latest version should be "17.17.0.2332602", If not please update and try it out .
Thanks

**Comment by htzhang2** [comment]
where to check version of Model Builder from VS 2022?

**Comment by htzhang2** [comment]
ML.Net Model Builder version is 17.17.0.2332602:

![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/4983284/71fb5f46-2b68-44e3-9d50-3042fbe40c56)

**Comment by htzhang2** [comment]
Resolved the problem by unchecking local package source folder

**Comment by 4C00FF** [comment]
Where is that?
