### ISSUE TITLE
Image classification & Object detection: Training failed when choosing Azure environment.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2855]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.18.2.2411602 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.8.7)
.Net Core: 6.0,7.0,8.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training failed when choosing Azure environment.

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/weather.zip

**To Reproduce**

1. Select Create a new project from the Visual Studio start window.
2. Choose the C# Console App (.NET Core) project template.
3. Add model builder by right click on the project.
4. Select "Image classification or Object Detection" scenario.
5. Choose Azure environment and set up the workspace.
6. On the Data page, choose the data source.
7. On the Train page, click "Start training" button, you will see that the training failed.

**Expected behavior**
Training successful.

**Screenshot:**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/18d6e323-99d7-4c9e-9492-da40365ad566)

**Additional context:**
The bug is not repro when choosing Local environment.

**Comment by LittleLittleCloud** [comment]
@v-Hailishi I accidently prune the key vault of eastUSws workspace,, sorry about that

If you try the following workspace the azure training will work
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/16876986/d4cea3d8-7ccf-45c0-9bc0-22ea8a036c9c)

**Comment by v-Hailishi** [comment]
After changing to another workspace on the Environment page, the training would be successful.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/eedb2833-c835-4594-9c23-7212d35f8fb4)
