### ISSUE TITLE
Sentence similarity: Training failed when choosing File Validation Option to training SQL Server data.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2857]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.18.2.2411602 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.8.7)
.Net Core: 6.0,7.0,8.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Training filed when choosing File Validation Option.

**TestMatrix**
https://github.com/dotnet/machinelearning-modelbuilder/files/10534387/home-depot-sentence-similarity-small.csv

**To Reproduce**

1. Select Create a new project from the Visual Studio start window.
2. Choose the C# Console App (.NET Core) project template.
3. Add model builder by right click on the project.
4. Select "Sentence similarity" scenario.
5. On the Data page, choose the SQL Server data source, then choosing File Validation Option on the "Advanced data options" dialog.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/90107b05-22de-4030-9d24-e069d50460cf)
6. On the Train page, click "Start training" button, you will see that the training failed.

**Expected behavior**
Training successful.

**Screenshot:**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/180c8cd2-077a-43d5-82f6-4cbf80d42719)

**Additional context:**
The bug is not repro when choosing Cross validation or Split validation option.

**Comment by zewditu** [comment]
@v-Hailishi , this is related with data formatting option in advanced data options, if you make  allow quote set to yes it will work 
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/36615490/ad90defe-20d5-43f3-8861-c5f29a8fbcee)

**Comment by v-Hailishi** [comment]
@zewditu Sorry I am not clear the data source. I have updated the title and the repro steps. When training the SQL server data, it is not supporting the data formatting.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/60fe6deb-1a82-4cb4-ab69-40e9b00dae2f)

**Comment by zewditu** [comment]
Got it, thanks,

**Comment by zewditu** [comment]
Long term fix  work item https://github.com/dotnet/machinelearning-modelbuilder/issues/2861
