### ISSUE TITLE
Did not get 5 models explored and  also accuracy is 68%

### ISSUE THREAD

**Issue by alruba** [dotnet/machinelearning-modelbuilder#286]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/evaluate
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by natke** [comment]
Sure, no worries!

**Comment by beccamc** [comment]
I see the documentation has been added to make it clear we show up to 5 models. Closing this issue.
