### ISSUE TITLE
MICROSOFT.ML not found

### ISSUE THREAD

**Issue by karan2489** [dotnet/machinelearning-modelbuilder#287]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment]
@karan2489 please report back if this resolved the issue for you.

**Comment by JakeRadMSFT** [comment]
Closing due to lack of response. If you're still hitting this issue please re-open and we'll work to resolve the issue.

Thanks for reporting!
