### ISSUE TITLE
Model Builder Erroe

### ISSUE THREAD

**Issue by SelecEmb1** [dotnet/machinelearning-modelbuilder#2874]
![ModelBuilderError](https://github.com/dotnet/machinelearning-modelbuilder/assets/149349922/0dcbac28-41dc-433b-ae6f-33df0aa0e368)

**Comment by LittleLittleCloud** [comment]
Which version are you using, if you are using the latest version, we provide an option to disable that elevation check

**Comment by LittleLittleCloud** [comment]
Close due to no response
