### ISSUE TITLE
Evaluate / Try it out clean up

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#288]
- [ ] Too much spacing between columns in Top models table; e.g. rank will always be 1-5, so should have less space; space between other metrics can be decreased as well
- [ ] Not enough padding between side of table and "Rank"
![image](https://user-images.githubusercontent.com/10437687/66788569-e5d8a480-ee9c-11e9-972e-e04822c25e02.png)

- [ ] Include option for "All compatible image files" and make it the default in File Explorer -- otherwise hides how many pictures are actually in the folder (this is when adding photo in Try it out)
![image](https://user-images.githubusercontent.com/10437687/66790048-10c5f700-eea3-11e9-886f-1eaf0b664fe2.png)
![image](https://user-images.githubusercontent.com/10437687/66790102-4539b300-eea3-11e9-99b8-2fdb1e8016bc.png)

**Comment by JakeRadMSFT** [comment]
Thanks Bri!
