### ISSUE TITLE
JSON-RPC

### ISSUE THREAD

**Issue by bryfu** [dotnet/machinelearning-modelbuilder#2889]
**System Information (please complete the following information):**
 - Model Builder Version (latest)
 - Visual Studio Version (latest)

**Describe the bug**
Exception after training data. The JSON-RPC connection with the remote party was lost before the request could complete.

**To Reproduce**
1. Setup the model builder and train data
2. Eventually I got this exception: The JSON-RPC connection with the remote party was lost before the request could complete.

**Expected behavior**
The error should not occur think

**Screenshots**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/161733089/7dfc4423-7e21-446a-98d4-4d8aeb9aa38b)

**Comment by LittleLittleCloud** [comment]
Which version of model builder are you using

**Comment by bryfu** [comment]
I thought I had the latest versions, but there was already a new version. I updated VS and ML.NET to the latest. All work fine now.
