### ISSUE TITLE
Image classification & Object detection: Cannot create a new workspace for Azure environment.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2902]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-23H2
ML.Net Model Builder 2022: 17.18.2.2421201 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.9.6)
.Net Core: 6.0,7.0,8.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Cannot create a new workspace for Azure environment.

**TestMatrix**

**To Reproduce**

1. Select Create a new project from the Visual Studio start window.
2. Choose the C# Console App (.NET Core) project template.
3. Add model builder by right click on the project.
4. Select "Image classification or Object detection" scenario.
5. On the "Environment" page, choose "Azure" option and then click "Set up workspace" button.
6. Choose "ML.NET Model Builder Demo" subscription and then click "New Workspace" link.
7. Provide the name, regions, RG on the "Create new workspace" dialog, then click "Create" button.
8. Model Builder error occurs: **Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=4.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)**

**Expected behavior**
Workspace can be created successfully.

**Screenshot:**
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/f8a81092-dae6-4365-9467-2ebb73d6b43e)

**Additional context:**

**Comment by LittleLittleCloud** [comment]
This exception is caused because model builder refers to `Microsoft.IdentityModel.Clients.ActiveDirectory v5.2.0` while one of model builder's dependencies, `Microsoft.Azure.Management.Fluent` refers to `Microsoft.IdentityModel.Clients.ActiveDirectory v4.3.0`.

## Why we didn't see this error before
Probably because `Microsoft.IdentityModel.Clients.ActiveDirectory v4.3.0` is shipped inside VS, but not any more for latest released VS

## What's the fix?
The Microsoft.Azure.Management.Fluent is marked as deprecated and we should upgrade to use https://www.nuget.org/packages/Azure.ResourceManager/

**Comment by v-Hailishi** [comment]
@LittleLittleCloud After Installing the NuGet package "Azure.ResourceManager", the error is still existed.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/06646ecd-8a0f-4247-9474-b5ccfc24e2e9)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/5667019b-5526-4550-87c3-a79863c04330)

**Comment by LittleLittleCloud** [comment]
@v-Hailishi The error is inside model builder extension and can't be fixed on the user side.

Also can you test the latest released model builder on VS 17.9.6 to see if workspace creation has the similar error?

**Comment by v-Hailishi** [comment]
@LittleLittleCloud  The bug is still repro on the latest "LittleLittleCloud-patch-3" branch build 17.18.2.2421601.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/3d3c9b97-44a0-4eec-8e84-af96cd552ecb)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 17.18.2.2421801.
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/2e6570f1-9bcf-47a5-bbf5-ea44f8bf42ec)
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/ea315f4d-bc08-4398-af15-7e24bb79ab4f)
