### ISSUE TITLE
Telemetry bug - stepchangedevent

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#292]
**Model Builder Version**: 16.0.1909.2101
**Visual Studion Version**: VS Enterprise 2019 Preview - v 16.3.0 Preview 4

**Bug description**
The **vs/modelbuilder/stepchangedevent** Property **modelbuilder.navigationtrigger** is incorrect when you go from Scenario to another step by using the step tabs. Instead of having modelbuilder.navigationtrigger = UserClickedStepTab for this, it always has modelbuilder.navigationtrigger = UserClickedScenario

**Steps to Reproduce**
1. Open VS Tel Mon and VS.
2. Open Model Builder and select Sentiment Analysis scenario which brings you to Data step -- stepchangedevent says Navigation Trigger is UserClickedScenario which is correct
3. From Data step, go back to Scenario step by clicking Scenario tab -- stepchangedevent says correct Navigation Trigger (UserClickedStepTab)
4. From Scenario tab, instead of selecting another scenario, click on the Data step tab -- stepchangedevent is incorrect and says NavigationTrigger is UserClickedScenario (should be UserClickedStepTab)
	
It seems that anytime a user navigates from the Scenario screen to another step, it counts it as UserClickedScenario, which is not true in all cases.

**Comment by zewditu** [comment]
Thanks @briacht
