### ISSUE TITLE
The prediction code always predicts 0 but when tried in the Evaluate tab it always works (a value other than 0)

### ISSUE THREAD

**Issue by EndermanPC** [dotnet/machinelearning-modelbuilder#2947]
**System Information:**
 - Model Builder Version17.15.0.2337001
 - Visual Studio Version 2022

I created a machine learning model, everything's fine
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/88751712/3eae4d97-e4ad-4d2c-b375-1bed09d684f6)
By this image, you see that model working normal
But when I use the code by the model builder:
```cs
using ConsoleApp2;

//Load sample data
var sampleData = new MLModel1.ModelInput()
{
    Device = 1F,
    Temperature = 20F,
    Weather = 1F,
    Time = 2F,
};

//Load model and predict output
var result = MLModel1.Predict(sampleData);
Console.WriteLine(result.Predict);
```
The output alway is 0 or the predict alway is 0:
![image](https://github.com/dotnet/machinelearning-modelbuilder/assets/88751712/65b6cbc2-29a4-4dc4-a3b0-5f74aa4fb9d5)

**Comment by LittleLittleCloud** [comment]
That's odd,, is it possible for you to share dataset so I can try reproduce it on my end?

**Comment by EndermanPC** [comment]
> That's odd,, is it possible for you to share dataset so I can try reproduce it on my end?

Well, I tested on a lot of datasets, but you can try with a 3 column dataset:
```
a, b, c
1, 2, 3
1, 3, 4
3, 4, 5
4, 5, 6
3, 5, 6
2, 4, 5
... (1994 more rows)
```
Sorry because I lost the dataset file, but in general with any data I get a prediction of 0.

**Comment by joramkuntze** [comment]
Did you fix it. I have the same issue.
