### ISSUE TITLE
Telemetry Updates

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#295]
- [ ] Add Session ID GUID to every event. (Zewditu)
- [ ] On first launch log StepChanged with no source and target =  Scenario (Zewditu)
- [ ] Log hashed dataset filename (Zewditu)
- [ ] Log hashed dataset first row (usually headers) (Zewditu)
- [ ] Better Error Logging (Single Event with Identifying Property). (Xiaoyun)
- [ ]  Number of Columns(Already done), # of Selected Features (Zewditu)
- [x] Try It Out Telemetry Select Predict and Count. Was data changed or did they use pre-filled. (Xiaoyun)
- [ ] Accuracy of Model (Zewditu)
- [x] Training time (Not logging training time in trainingstarted event) (Xiaoyun)
- [x] Training duration (Not logging actual duration in trainingcompleted event) (Xiaoyun)
- [ ] Total models explored (Already done but it has bug ) + highest accuracy (Zewditu)
- [x] How many times user has added project in Code screen (already done)

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud can you take better logging of Error to telemetry.

**Comment by LittleLittleCloud** [comment]
@JakeRadMSFT what's Training time and Training duration mean?

**Comment by zewditu** [comment]
@JakeRadMSFT and @briacht  for hashed data-set file name and header , is that for all  data source types  ?

do we need to hashed image file name, sql table name?  sql column names?

**Comment by zewditu** [comment]
@JakeRadMSFT  what is the difference between  Accuracy of Model  and  Highest accuracy . I thought they are the same , is that right?
