### ISSUE TITLE
Visual Studio crashes after adding the example .tsv file

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#298]
@Sebastian949494 commented on [Tue Oct 22 2019](https://github.com/dotnet/machinelearning-samples/issues/709)

Problem related to the following link:
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data

When I created a .tsv file from the dataset with Visual Studio 2019 as shown in the example, the IDE crashed without any further information.

Best regards,
Sebastian

**Comment by LittleLittleCloud** [comment]
@Sebastian949494 what's the name of file you created, is that end of .tsv/.txt/.csv or other extension?

**Comment by Sebastian949494** [comment]
Full file name: 
wikipedia-detox-250-line-data.tsv

**Comment by habib-developer** [comment]
This issue mostly encounters when the dataset file is not in the proper format.

**Comment by JakeRadMSFT** [comment]
Was the file open in Excel or any other program? This might be related to a known issue.
