### ISSUE TITLE
ML.NET ISSUE

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#299]
@Kiansniper2005 commented on [Mon Oct 21 2019](https://github.com/dotnet/machinelearning-samples/issues/707)

Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I right click on mlMLApp and add, there isn't an option there called machine learning. I ran the only .exe in the Microsoft.ML.ModelBuilder. The .exe was called: lightgbm.exe.

**Comment by Axiverse** [comment]
Install it: https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install

**Comment by JakeRadMSFT** [comment]
@Kiansniper2005 were you able to get it successfully installed?

**Comment by Kiansniper2005** [comment]
Yes

**Comment by JakeRadMSFT** [comment]
Resolved.
