### ISSUE TITLE
I installed the extensions and im not getting the option to add machine learning to my project

### ISSUE THREAD

**Issue by nikhilbatta** [dotnet/machinelearning-modelbuilder#300]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I installed the extensions and im not getting the option to add machine learning to my project.
running on windows

**Comment by JakeRadMSFT** [comment]
Duplicate #206

**Comment by JakeRadMSFT** [comment]
We're tracking this issue with #206. Thanks for reporting!
