### ISSUE TITLE
providing data sources from excel file  crash visual studio while the Excel- file is opened 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#301]
**Model Builder Version**: _16.0.1910.901
**Visual Studio Version**:  vs Enterprise 2019, v-16.3.7

**Bug description**
After you choose a scenario and arrived at data page  and then choose  excel file which is already opened behind  makes the Vs crashed. 

**Steps to Reproduce**
1. Open model builder
2. select  price prediction scenario.
3. Open you data-set in excel 
4. while your data-set file is opened in excel select  that opened file from model builder's  select file section 

**Expected Experience**
The selected file top ten  rows previewed and  the user able to select label and feature columns
Or 
Let the user there is an error and make sure to fix that to continue. 

**Actual Experience**
Vs crashed

**Comment by LittleLittleCloud** [comment]
Validate on VS2019 VS2019 preview

**Comment by beccamc** [comment]
Validated that an error message is shown ![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/a98ca069-88c1-4cda-9def-3b1d7bcb8c82)
