### ISSUE TITLE
Try It Out Image Reset

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#307]
1. Try out an image
2. Click "Test another image"
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/40f27d3e-e7c1-4df1-a2d3-73433d8a39af)
3. The Image and the **results should be cleared and button should be disabled**![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/f5e522ab-839e-44c4-85f2-ac14f836eace)

**Comment by LittleLittleCloud** [comment]
validate on VS2019 and VS2019 preview
