### ISSUE TITLE
Instructions on how to format image data

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#309]
This was looked at in the user testing. confirm with Bri and Kaitlin what approach we want here

**Comment by JakeRadMSFT** [comment]
Please " Add string to explain how we shrink and crop an image for image classification." as we discussed from Bug Bash.

**Comment by beccamc** [comment]
https://www.figma.com/file/LPBWMBvD3XdgLkWwAL9KkH/Image-Classification-Quick-Pulse-%E2%80%93-Kaitlin?node-id=38%3A15691
