### ISSUE TITLE
ML.NET CLI Asks

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#31]
### File
- [x]  Better CSV/TSV Support
  - [ ] Related: #156 
- [ ]  Support for non en-US Region formats in Windows

### SQL
 - [x] Handle SQL as a Source for both training and project generation
   - [ ] Related: #26

## Training 
- [x] Send errors immediately, don't wait until entire train time has passed.
   - [ ] Related: #133

## Code Generation
 - [ ] Option to specify full project name for generated Model project
   - [ ] Related: #129, #96
 - [ ] Option to specify full project name for generated Console App
   - [ ] Related: #129, #96
 - [ ] Option to only generate projects not solution file.
   - [ ] Related: #129, #96 
 - [ ] Set CopyAlways  = true for MLModel.zip in Model project.
 - [ ] Floating point numbers using current culture. Doesn't result in working project.
   - [ ] See #174 and dotnet/machinelearning#3677

**Comment by rustd** [comment]
#73 and #74 should address file parsing issues.
#76 for Code generation

We need SQL support from ML.NET
