### ISSUE TITLE
Show Best DNN-Architecture and accuracy when training IMAGE CLASSIFIER

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning-modelbuilder#312]
when training, and it says "**Best Accuracy and Best Algorithm**" it is not showing anything..

![image](https://user-images.githubusercontent.com/1712635/68261269-639f5400-fff4-11e9-8804-65da812d38d5.png)

I think that in the place for "Best Algorithm" we should show the best DNN-Architecture so far plus you could also get feedback/accuracy from it if using the callback function or the MLContext log filter.

So, it could display something like:
 
```
Best accuracy: 89%
Best DNN architecture: Inception v3
```

or

```
Best accuracy: 89%
Best base model: Inception v3
```

Other DNN architectures we support are:
	ResNet v2 101
	ResNet v2 500
	MobileNet

**Comment by briacht** [comment]
Best model: Inception v3
Best accuracy: 89%

**Comment by codemzs** [comment]
@CESARDELATORRE sweeping is disabled hence it will just use the defaults. Lets enable sweeping when GPU support is added otherwise model builder will take forever to get a model.

**Comment by JakeRadMSFT** [comment]
Won't fixing for now. This hasn't shown up as an issue from customers or user testing.
