### ISSUE TITLE
Predict input error handling

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#314]
We should...
1. Disable predict button if something is empty? (I know some entries may have empty fields, but if we throw an error every time we should just disable the button) 
2. Say which input wasn't in the right format. The message "input string was not in correct format" doesn't direct me to the right one. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c4c1a0cb-a5ac-4ca6-80a9-f8bc152e4092)

**Comment by beccamc** [comment]
I would say "Input string for [Feature 2, Feature 3, etc.] is not in a correct format." in the error message

**Comment by briacht** [comment]
1. Yes, if any field is empty, just disable the button (and maybe highlight the textbox red indicating a value is missing -- confirm w/ Kaitlin)
2. Can we do this: 
"Input string for Feature 2 is not in the correct format."
"Input strings for Feature 2 and Feature 3 are not in the correct format."
"Input strings for Feature 1, Feature 2, and Feature 3 are not in the correct format."

**Comment by beccamc** [comment]
Validated
