### ISSUE TITLE
Remove the horizontal separator bars from each page to reduce clutter and update color for remaining separators 

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#315]
@kawilkin Can you identify which ones just so it's clear?

**Comment by kawilkin** [comment]
@JakeRadMSFT  does this help? ![Frame 1](https://user-images.githubusercontent.com/47866467/68338260-ef69bc80-0096-11ea-83c8-9d3c1ef8731f.png)

**Comment by beccamc** [comment]
Validated!
