### ISSUE TITLE
For images, don't let user specify time.

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#317]
Open output window while training.

**Comment by kawilkin** [comment]
Figma link: https://www.figma.com/file/LPBWMBvD3XdgLkWwAL9KkH/Image-Classification-Quick-Pulse-%E2%80%93-Kaitlin?node-id=46%3A0

**Train mock - before training**
![Train mock -  before training](https://user-images.githubusercontent.com/47866467/68430470-f52dd380-0164-11ea-8b85-72b8025e90cb.png)

**Train mock - while training**
![Train mock - while training](https://user-images.githubusercontent.com/47866467/68430471-f52dd380-0164-11ea-93cb-8669c7cf3a02.png)

**Evaluate mock**
![Evaluate mock](https://user-images.githubusercontent.com/47866467/68430468-f52dd380-0164-11ea-8508-82ad01bd7715.png)

**Comment by justinormont** [comment]
We will be moving to sweeping for images. For this we'd want the user to specify a time. Hence this change to remove the time field will be temporary.

Ideally, we should be recommending the time based on the specifics of their dataset and hardware.

**Comment by JakeRadMSFT** [comment]
@justinormont until cancel actually works ... we shouldn't really be letting the user specify a time. It's misleading. We can revisit ... and file bugs we need fixed :)
