### ISSUE TITLE
When an exception is hit  at the data page  previous  state is not  cleared or rested  

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#324]
**Model Builder Version**: 16.0.1911.601
**Visual Studion Version**: _2019 professional

**Bug description**

**Steps to Reproduce**
1. Be at data page  
2. select file 
3. select  a bad  file format
4. close error dialog

**Expected Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/421a594c-acff-45af-be79-b38367ee9b98)
**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/16cf4732-a758-43b9-96e9-0bf8f9b1f739)![image.png]
The data page is not cleared 

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by briacht** [comment]
If a user selects a valid dataset (and can choose labels / features) and then goes back and chooses an invalid dataset, I think it's ok to leave the previous selection rather than clearing it. However, we need to make sure that they know the dataset selected is the previous dataset, not the one that got the error.

**Comment by briacht** [comment]
How does this sound: "Invalid file type. This file will not be used, and Model Builder will keep the last acceptable file selected."

**Comment by beccamc** [comment]
@briacht Does it still make sense if this is my first selection (no previous acceptable file selected)? If yes, then I think it sounds good!

**Comment by briacht** [comment]
Do we need to have the same dialog for both cases? Also we could even remind them of the valid file types.

If it's the first selection, something like:
"Invalid file type. This file will not be used. Try selecting another file (.csv, .tsv, or .txt). Click **here** to learn more about valid file types."

Where **here** = http://aka.ms/vsmbdata

**Comment by JakeRadMSFT** [comment]
Still repros for me:

![image.png](https://images.zenhubusercontent.com/5cde1c65e3106e39e8ae08f2/213abe2e-a071-44b0-9890-b0f48d4fbb4f)

![image.png](https://images.zenhubusercontent.com/5cde1c65e3106e39e8ae08f2/d8f1c7cc-5b11-4f23-ab13-aa323f52db72)

**Comment by JakeRadMSFT** [comment]
Didn't seem to do the right thing for Text Scenarios either.

**Comment by beccamc** [comment]
This bug fixed only for bad file _formats_ (e.g. not .csv or .tsv). Basically it checks if it's a valid file extension before setting fileName to the new file. If it's a bad file type then it doesn't overwrite and tells the user it's using the previous file.

It doesn't revert the selection once we start processing the file. In other words, if you pick BadFile.tsv and we can't process it, we aren't keeping around the previous file you chose and reverting it back.  Same is true for images. When you pick a folder we accept it and then check if the structure underneath is valid. 

I spoke with Bri and she is fine with it

[5:09 PM] Bri Achtman
    oh that's totally fine
​[5:09 PM] Bri Achtman
    People can go back and choose the correct file

**Comment by beccamc** [comment]
Closing. Will reopen if customers hit.
