### ISSUE TITLE
Bug Bash Part 2: Bugs --> 6/7 fixed 

### ISSUE THREAD

**Issue by kawilkin** [dotnet/machinelearning-modelbuilder#326]
### fixed 
1. **Data screen:** "next step.." action falls below the fold, but it looks like there is enough room above the fold to have it visible without scrolling.
<img width="1552" alt="Screen Shot 2019-11-06 at 2 32 58 PM" src="https://user-images.githubusercontent.com/47866467/68347997-8d688180-00ad-11ea-830b-fccfb1d905dd.png">
## fixed
2. **Data screen:** Align "select folder" with "Input"
<img width="531" alt="Screen Shot 2019-11-06 at 3 38 40 PM" src="https://user-images.githubusercontent.com/47866467/68348054-c0127a00-00ad-11ea-9033-f671db2b87bd.png">
## not fixed
3. **Train screen:** It looks like there is a little blue dot on the upper right-hand corner of the tooltip icon. We should also eventually switch to using the image service. The info tip should be center-aligned vertically with the text.
<img width="305" alt="Screen Shot 2019-11-06 at 3 49 37 PM" src="https://user-images.githubusercontent.com/47866467/68348109-e6381a00-00ad-11ea-971a-d6d7909b271b.png">
## fixed
4. **Evaluate screen:** "Predict starts to fall off the screen. We can probably fix this by fixing the spacing between "Output" and the pivots, as well as between the overview section and "try your model"
<img width="251" alt="Screen Shot 2019-11-06 at 2 47 33 PM copy 2" src="https://user-images.githubusercontent.com/47866467/68348211-2bf4e280-00ae-11ea-9888-c5b04468ae46.png">
<img width="1552" alt="Screen Shot 2019-11-06 at 2 47 33 PM copy" src="https://user-images.githubusercontent.com/47866467/68348215-30210000-00ae-11ea-8961-665806e404d1.png">
## fixed
5. **Evaluate screen:** Once the user selects the image from "Browse.." it should automatically start the prediction. 
 ## fixed
6. **Evaluate screen:** When the user selects "Test another image" it should clear the image and automatically launch "browse." Right now it is acting more like a "clear" experience instead of "try another..."
 ##  fixed
7. **Evaluate screen:** Switch "test another image" to "try another image" so it is consistent with the section header.

**Comment by zewditu** [comment]
@kawilkin  if we automatically start prediction  without clicking  the button what the the purpose of "predict button"

**Comment by beccamc** [comment]
@kawilkin  For #1, the example used in the screenshot has only 8 images. Right now we're set for 12 images, which is why the button falls below the fold. 

We're always keeping the size of the grid at 12 images, even if there aren't that many. This is because the button would jump up and down navigating between folders (i.e. 2 images in cows and 12 in horses would produce different heights).  We had discussed this and determined..
1) Most people probably won't have less than 12 images and 
2) We didn't want the screen jumping up and down. 

I hear you on the button falling below the fold. Should we decrease the number of images to 8 so the button appears in a better place all the time? 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/1db3daea-2be6-4059-915f-51dbf418afb9)

**Comment by kawilkin** [comment]
@beccamc I think decreasing it to 8 would be best. Our goal is to just build confidence that the images were imported, right? I think having 8 is fine because it'll still give you the preview, but keeps the button above the fold. 

Another idea would be to make those buttons sticky and always have them visible on smaller screens and then if the screen expands to a larger size, they could just sit at the bottom of the content instead of all the way at the bottom of the screen. But that might be odd on more complex pages like the evaluate page 🧐

**Comment by kawilkin** [comment]
> @kawilkin if we automatically start prediction without clicking the button what the the purpose of "predict button"

@zewditu if we automatically predict, I think we could go ahead and remove the predict button.

**Comment by beccamc** [comment]
@kawilkin Awesome thank you!
