### ISSUE TITLE
In image classification filtering  bad files from folder without letting the user 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#328]
**Model Builder Version**: 16.0.1911.601
**Visual Studion Version**: 2019 professional 

**Bug description**
In image classification we just filtered out bad data types from parent and sub folders without telling the users  
**Steps to Reproduce**
1. prepared folder that contain sub-folders and some others files ( it could be text or image)
2.  in the sub-folders add supported images and some other unsupported image files and text files 
3. use that folder for image training

**Expected Experience**
Letting  the user some unsupported/ bad files  files are filtered
**Actual Experience**
just filtering  supported files 
**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by zewditu** [comment]
@briacht  any thought on this .

**Comment by briacht** [comment]
We already tell users the "Supported file formats" on the Data page, I don't think we need anything more than this in the UI. We can add a blurb in the Doc's Data section: https://github.com/dotnet/machinelearning-samples/blob/master/modelbuilder/readme.md#data
