### ISSUE TITLE
Change to *ML.ConsoleApp.CreateSingleDataSample()

### ISSUE THREAD

**Issue by JustMakeItEasy** [dotnet/machinelearning-modelbuilder#329]
Just a suggestion on the default script CreateSingleDataSample to randomly return a model to test against from the original set?

`var modelList =  mlContext.Data.CreateEnumerable<ModelInput>(dataView, false);`
`Random random = new Random();`
`int randomIndex = random.Next(modelList.Count());`
`ModelInput sampleForPrediction = modelList.ElementAt(randomIndex);`

**Comment by JakeRadMSFT** [comment]
Thanks for the suggestion!

**Comment by briacht** [comment]
@JustMakeItEasy, do you mean randomly generate an input for the model rather than selecting the first item from your dataset to test?

**Comment by JustMakeItEasy** [comment]
@briacht  just selecting one item from the set to test against. It's handy to see the model compare against a few different results, not just the first one. I.e. the first item could be 25% out but the next two could be bang on. 

Maybe even iterate the first 5 rows?
`namespace TestML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Users\SimonCurtis\Documents\view.csv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            IEnumerable<ModelInput> sampleData = CreateSingleDataSample(DATA_FILEPATH);

            foreach (ModelInput modelInput in sampleData)
            {
                // Make a single prediction on the sample data and print results
                ModelOutput predictionResult = ConsumeModel.Predict(modelInput);

                Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");
                Console.WriteLine($"Material_Code: {modelInput.Material_Code}");
                Console.WriteLine($"Case_Code: {modelInput.Case_Code}");
                Console.WriteLine($"Flute_Type: {modelInput.Flute_Type}");
                Console.WriteLine($"Unit_Group: {modelInput.Unit_Group}");
                Console.WriteLine($"Length: {modelInput.Length}");
                Console.WriteLine($"Width: {modelInput.Width}");
                Console.WriteLine($"Height: {modelInput.Height}");
                Console.WriteLine($"Type_Of_Join: {modelInput.Type_Of_Join}");
                Console.WriteLine($"Print_Type: {modelInput.Print_Type}");
                Console.WriteLine($"Pallet_Qty: {modelInput.Pallet_Qty}");
                Console.WriteLine($"Bundle_Qty: {modelInput.Bundle_Qty}");
                Console.WriteLine($"Sheet_A_Qty_1000: {modelInput.Sheet_A_Qty_1000}");
                Console.WriteLine($"Sheet_A_Width: {modelInput.Sheet_A_Width}");
                Console.WriteLine($"Sheet_A_Length: {modelInput.Sheet_A_Length}");
                Console.WriteLine($"Customer_Code: {modelInput.Customer_Code}");
                Console.WriteLine($"Quantity: {modelInput.Quantity}");
                Console.WriteLine($"\n\nActual Price: {modelInput.Price} \nPredicted Price: {predictionResult.Score}\n\n");
                Console.WriteLine("=============== Press any key to go to the next model ===============");
                Console.ReadKey();
                Console.Clear();
            }

            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static IEnumerable<ModelInput> CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)

            return mlContext.Data.CreateEnumerable<ModelInput>(dataView, false).Take(5);
        }
        #endregion
    }
}
`

**Comment by Nicklas9822** [comment]
@simon-curtis Hi, Could you show me the Model Input please cause i have a similar project and i want to iterate the rows of the dataset. My problem that all the data is going in the first column which in your case is Material_Code and of course i need the data to be in its appropriate column. Thanks in advance

**Comment by simon-curtis** [comment]
@Nicklas9822 the model should be generated automatically for you based on the data you have given the trainer. I don't have the data from my request as it was from an old place of work.

**Comment by Nicklas9822** [comment]
@simon-curtis Yes, exactly but at default it's for the first row only. Now i followed your code so it could iterate the rows but now the data is all being sent to the first column instead of their proper columns. as you can see in the image

![image](https://user-images.githubusercontent.com/25117293/81939045-1a107100-95f6-11ea-9877-296ec280594b.png)

**Comment by Nicklas9822** [comment]
There are no examples online on this :/

**Comment by simon-curtis** [comment]
@Nicklas9822 could you send me your code?

**Comment by Nicklas9822** [comment]
Yes sure

`
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.ML;
using PlayerPredictionSkillsSet1ML.Model;

namespace PlayerPredictionSkillsSet1ML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Users\Nicholas\AppData\Local\Temp\ee44620c-ed47-4355-b736-94faf81b1d39.tsv";

        static void Main(string[] args)
        {
            ModelBuilder.CreateModel();

            // Create single instance of sample data from first line of dataset for model input
            IEnumerable<ModelInput> sampleData = CreateSingleDataSample(DATA_FILEPATH);

            foreach (IEnumerable<ModelInput> modelInput in sampleData)
            {
                // Make a single prediction on the sample data and print results
                ModelOutput predictionResult = ConsumeModel.Predict(modelInput);

                Console.WriteLine("Using model to make single prediction -- Comparing actual Position with predicted Position from sample data...\n\n");
                Console.WriteLine($"name: {modelInput.Name}");
                Console.WriteLine($"sprint_speed: {modelInput.Sprint_speed}");
                Console.WriteLine($"acceleration: {modelInput.Acceleration}");
                Console.WriteLine($"finishing: {modelInput.Finishing}");
                Console.WriteLine($"long_shots: {modelInput.Long_shots}");
                Console.WriteLine($"crossing: {modelInput.Crossing}");
                Console.WriteLine($"short_passing: {modelInput.Short_passing}");
                Console.WriteLine($"agility: {modelInput.Agility}");
                Console.WriteLine($"balance: {modelInput.Balance}");
                Console.WriteLine($"interceptions: {modelInput.Interceptions}");
                Console.WriteLine($"sliding_tackle: {modelInput.Sliding_tackle}");
                Console.WriteLine($"aggression: {modelInput.Aggression}");
                Console.WriteLine($"jumping: {modelInput.Jumping}");
                Console.WriteLine($"gk_reflexes: {modelInput.Gk_reflexes}");
                Console.WriteLine($"gk_diving: {modelInput.Gk_diving}");
                Console.WriteLine($"\n\nActual Position: {modelInput.Position} \nPredicted Position value {predictionResult.Prediction}\nPredicted Position scores: [{String.Join(",", predictionResult.Score)}]\n\n");
                Console.WriteLine("=============== End of process, hit any key to finish ===============");
                Console.ReadKey();
                Console.Clear();
            }
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static IEnumerable<ModelInput> CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)

            return mlContext.Data.CreateEnumerable<ModelInput>(dataView, false).Take(5);
        }
        #endregion
    }
}`

**Comment by simon-curtis** [comment]
@Nicklas9822 can you set a break point on:
`Console.WriteLine($"name: {modelInput.Name}");`

And then hover over modelInput and it will show you the members inside, could you screenshot that for me?

**Comment by Nicklas9822** [comment]
![errorml](https://user-images.githubusercontent.com/25117293/81939882-34971a00-95f7-11ea-929d-5a134eba1aeb.png)

**Comment by simon-curtis** [comment]
@Nicklas9822 Seems like the code behind isn't splitting your data, because you are using tabs ("\t").

```
// Create single instance of sample data from first line of dataset for model input
IEnumerable<ModelInput> sampleData = CreateSingleDataSample(DATA_FILEPATH);
```

What format is your data in? CSV

**Comment by Nicklas9822** [comment]
It's in SQL Format using SSMS 2018

**Comment by simon-curtis** [comment]
Ahh okay, so I've just seen on their Docs

> Model Builder supports datasets in .tsv, .csv, .txt formats, as well as SQL database format. If you have a .txt file, columns should be separated with ,, ; or /t and the file must have a header row.

Just as a test, can you change any "\t" characters in your physical file to "/t" and try again?

**Comment by Nicklas9822** [comment]
I dont have /t in the db

**Comment by simon-curtis** [comment]
Look for 
`private const string DATA_FILEPATH = @"C:\Users\Nicholas\AppData\Local\Temp\ee44620c-ed47-4355-b736-94faf81b1d39.tsv";`

And change it there

**Comment by Nicklas9822** [comment]
Okay il try

**Comment by Nicklas9822** [comment]
![image](https://user-images.githubusercontent.com/25117293/81941485-2ea23880-95f9-11ea-84ad-ee443f879bc9.png)

**Comment by Nicklas9822** [comment]
There wasnt any of them

**Comment by simon-curtis** [comment]
Okay, copy the contents of that file into https://onlinecsvtools.com/convert-tsv-to-csv .

In the options section, set the separator to $

![image](https://user-images.githubusercontent.com/43214378/81942642-488c4d00-95f2-11ea-8654-52c85a220857.png)

Once done, save the new CSV as `data.tsv` to the desktop. _(yes, definately .tsv)_

Now open that new tsv file in notepad and do a replace all on `$` with `/t`

`private const string DATA_FILEPATH = @"C:\Users\Nicholas\AppData\Local\Temp\ee44620c-ed47-4355-b736-94faf81b1d39.tsv";`
to 
`private const string DATA_FILEPATH = @"C:\Users\Nicholas\Desktop\data.tsv";`

Now try and run your program.

**Comment by Nicklas9822** [comment]
This is the result

![image](https://user-images.githubusercontent.com/25117293/81943428-a8d3bc80-95fb-11ea-8b09-36a7e3cb890b.png)

**Comment by simon-curtis** [comment]
Ohh, okay. This looks like they aren't separating tsv files at all.

Just while I get a temporary solution for you, could you try converting to a normal CSV and see if that works?

**Comment by Nicklas9822** [comment]
I use a CSV so?

**Comment by simon-curtis** [comment]
Neither, just use simple `,` so it should look like this:
`Messi,85,90,70`

**Comment by Nicklas9822** [comment]
Ok i figured it out i used a normal CSV with only the columns i need and it worked. Thanks for the help

**Comment by Nicklas9822** [comment]
![image](https://user-images.githubusercontent.com/25117293/81946196-5ac0b800-95ff-11ea-9538-ca12673fd37b.png)

**Comment by simon-curtis** [comment]
OOHHHHH I've also just realised the code error. 

If you look at the CreateSingleDataSample() method. The mlContext.Data.LoadFromTextFile() method is using `','` as the separatorChar. You should be able to change this to `"/t"` _(note, that its using double quotes " not single quotes ')_

```
// Change this code to create your own sample data
#region CreateSingleDataSample
// Method to load single row of dataset to try a single prediction
private static IEnumerable<ModelInput> CreateSingleDataSample(string dataFilePath)
{
    // Create MLContext
    MLContext mlContext = new MLContext();

    // Load dataset
    IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                    path: dataFilePath,
                                    hasHeader: true,
                                    separatorChar: ',',
                                    allowQuoting: true,
                                    allowSparse: false);

    // Use first line of dataset as model input
    // You can replace this with new test data (hardcoded or from end-user application)

    return mlContext.Data.CreateEnumerable<ModelInput>(dataView, false).Take(5);
}
#endregion
```

**Comment by Nicklas9822** [comment]
Yes, thanks that was the problem

**Comment by Nicklas9822** [comment]
@simon-curtis You have any idea maybe for the score to automatically turn it into percentage instead of the multiple numbers?

**Comment by simon-curtis** [comment]
When you are outputting to the console?

**Comment by Nicklas9822** [comment]
Yes, exactly

**Comment by simon-curtis** [comment]
Easiest thing to do is just do 

`Console.WriteLine(“Acceleration: { modelInput.Acceleration / 100 }%”);`

**Comment by Nicklas9822** [comment]
No, i want it for the Predictions Scores which are at the bottom

![81943428-a8d3bc80-95fb-11ea-8b09-36a7e3cb890b](https://user-images.githubusercontent.com/25117293/82019111-edf10080-9686-11ea-9037-2e34b114bafa.png)

**Comment by Nicklas9822** [comment]
It is a float array

**Comment by simon-curtis** [comment]
I don't really know what 'Predicted Position scores' actually means. But if you want to display these as one percentage, then you probably want the average.
```
using System.Linq;
...
Console.WriteLine($"Predicted Position scores: {predictionResult.Score.Average()}%");
```

**Comment by Nicklas9822** [comment]
Oh okay, so i think i cant turn them into percentage each score instead of the average

**Comment by simon-curtis** [comment]
Can you use paint or something to show me what you want the end result to look like?

**Comment by Nicklas9822** [comment]
Basically just the Scores Array which amounts to 10 scores in total and turn them into percentage so they could be read easier

**Comment by Nicklas9822** [comment]
So instead of 10 decimal numbers i would have 10 percentages

**Comment by simon-curtis** [comment]
Like this:

```
using System;
using System.Collections.Generic;
using System.Linq;
...

List<string> percentages = predictionResult.Score
	.Select(score => score.ToString("P"))
	.ToList<string>();
		
string percentageString = string.Join(", ", percentages);
		
Console.WriteLine("Predicted Position scores: " + percentageString);
```

outputs: `Predicted Position scores: 12.34%, 31.21%, 15.51%`
