### ISSUE TITLE
Try It Out Image is cut off

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#330]
Using the attached image in try it out, the image is cut off. I think we're passing the full thing to training. We should display the full image 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/873e9168-4a34-4d82-b47b-d02f60b19095)

The full image: 
![pencil.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/6a117efc-4013-45a5-a40f-a078370e37d0)

**Comment by zewditu** [comment]
do't we have image size restriction?

**Comment by beccamc** [comment]
Validated.
