### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by Jricklefs** [dotnet/machinelearning-modelbuilder#335]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

When I follow the steps and attempt to run program throws  Duplicate system.Reflection.AssemblyCompanyAttribute' attribute

**Comment by JakeRadMSFT** [comment]
Thanks for reporting. Are the project and solution in the same folder? Can you share a screenshot of VS?

**Comment by Jricklefs** [comment]
yes they are. It was on my work PC I just went through the tutorial. I was using VS 2019 Pro. and it would keep throwing an error when I went to run. I could re build it here if need be.   I spent most of that day working through tuts. which one was this?  I belive it a ML one but don't remember which. 
JD Ricklefs 

    On Friday, November 15, 2019, 11:48:22 AM CST, Jake <notifications@github.com> wrote:  
 
 
Thanks for reporting. Are the project and solution in the same folder? Can you share a screenshot of VS?

**Comment by Jricklefs** [comment]
I just went throught the tutorial again with a clean build of VS COmmunity and I get the same errors. Let me know if there is some way to fix it . thanks. 
ML.NET Tutorial | Get started in 10 minutes | .NET

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
ML.NET Tutorial | Get started in 10 minutes | .NET

Step-by-step instructions for building a simple prediction model with ML.NET on Windows, Linux, or macOS. ML.NET...
 |

 |

 |









JD Ricklefs 

    On Friday, November 15, 2019, 04:44:27 PM CST, joseph ricklefs <josephricklefs@yahoo.com> wrote:  
 
 yes they are. It was on my work PC I just went through the tutorial. I was using VS 2019 Pro. and it would keep throwing an error when I went to run. I could re build it here if need be.   I spent most of that day working through tuts. which one was this?  I belive it a ML one but don't remember which. 
JD Ricklefs 

    On Friday, November 15, 2019, 11:48:22 AM CST, Jake <notifications@github.com> wrote:  
 
 
Thanks for reporting. Are the project and solution in the same folder? Can you share a screenshot of VS?

**Comment by JakeRadMSFT** [comment]
Exclude the folders from the original project you did "Add Machine Learning" on.

**Comment by JakeRadMSFT** [comment]
Can you share a screenshot of your solution explorer?

**Comment by Jricklefs** [comment]
you already suggested the fix a few days back
Jake <notifications@github.com>To:dotnet/machinelearning-modelbuilderCc:Joe Ricklefs,AuthorNov 21 at 2:58 PM
Exclude the folders from the original project you did "Add Machine Learning" on.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


JD Ricklefs 

    On Monday, December 2, 2019, 02:34:20 PM CST, Jake <notifications@github.com> wrote:  
 
 
Can you share a screenshot of your solution explorer?

**Comment by JakeRadMSFT** [comment]
Sorry, did this resolve the issue?

**Comment by JakeRadMSFT** [comment]
I believe this is the same issue as #359

**Comment by Jricklefs** [comment]
Yup

Sent from Yahoo Mail on Android 
 
  On Wed, Dec 11, 2019 at 3:23 PM, Jake<notifications@github.com> wrote:   
I believe this is the same issue as #359

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! We have a fixed checked in and it'll go out with our next release.
