### ISSUE TITLE
Error "Failed. See more in Output panel" but it is empty

### ISSUE THREAD

**Issue by nhgiangivs** [dotnet/machinelearning-modelbuilder#337]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1911.1103
 - Visual Studio Version : 2017

**Describe the bug**
I'm newbie start with ML.NET, but i cant not trained model when using Model Builder, please help me!
Error "Failed. See more in Output panel" when training model using Model Builder

**To Reproduce**
1. Add  -> Machine Learning 
2. Scenario -> Issue Classification 
3. Data -> File -> corefx-issues-train.tsv -> column to Predict (Label) ->"Area"
4. Start Train -> Error

**Screenshots**
![image](https://user-images.githubusercontent.com/50438794/68673734-00c73300-0587-11ea-9baf-883036138948.png)

[ModelBuilderError.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/3836237/ModelBuilderError.zip)

**Comment by JakeRadMSFT** [comment]
Thanks for reproting! We'll look into it.

**Comment by arnorad** [comment]
Getting the same error, on latest version of VS 2019 community edition. Not sure if that's a clue

**Comment by Scootiebup** [comment]
I too, just recently, am experiencing the “Failed. See more in Output Pane” message.
Until yesterday I could train different scenarios without issue.  Now, I can’t seem to create an Issue Classification model.  However, the Price Prediction scenario generates just fine. Shown below is the output for Price Prediction first, then the attempt for Issue Classification. My guess is that the ”failed” message appears because there is no Trainer explored/listed when training goes to finalize the model. 
![output](https://user-images.githubusercontent.com/58052303/69379084-b415e300-0c7d-11ea-92e3-6a6106c3a25f.jpg)

**Comment by patrickbloemhof** [comment]
I'm also getting this error, when I try to train a custom model for multi classification.

**Comment by Scootiebup** [comment]
One thing that I found to be successful was to increase the training time. I was originally training 35,000 rows at 10 mins (600 seconds) with no trainer explored.  When I trained at 20 mins (1200 seconds), trainers started to show up and I was able to finalize a model. I would imagine that if I added even more training time that more trainers would be explored. This was for Issue Classification model.

**Comment by patrickbloemhof** [comment]
> One thing that I found to be successful was to increase the training time. I was originally training 35,000 rows at 10 mins (600 seconds) with no trainer explored. When I trained at 20 mins (1200 seconds), trainers started to show up and I was able to finalize a model. I would imagine that if I added even more training time that more trainers would be explored. This was for Issue Classification model.

Thanks for your tip. I have 25,000 rows. With 20 min training it said failed. Then I did 10 min and it worked and generated a model. Only it dont work well, I have 25 different categorys in my traning data, is this possible to predict with one model?

**Comment by Scootiebup** [comment]
Well, I would consider 25 different categories (feature data) a little too many to use in a single model.    I was doing this as well , but found that when I reduce the feature data the model performed much better.  Also, large text columns, as in paragraphs of text, take a lot of time to train. When I want to return multiple predicted values (labels), I create multiple models, each returning a different prediction which I can pass to another model as input data. This allows me to group the data to return more specific predictions.

**Comment by patrickbloemhof** [comment]
> Well, I would consider 25 different categories (feature data) a little too many to use in a single model. I was doing this as well , but found that when I reduce the feature data the model performed much better. Also, large text columns, as in paragraphs of text, take a lot of time to train. When I want to return multiple predicted values (labels), I create multiple models, each returning a different prediction which I can pass to another model as input data. This allows me to group the data to return more specific predictions.

Alright thanks. But I did mean 25 different categories as in labels(to predict) with one model. Indeed, if you use lesser data as features the model gets better.

**Comment by LittleLittleCloud** [comment]
Hi @nhgiangivs, could you try increasing the training time to see if the error went? usually that dataset requires ~30s to get the first result. And if time is too short, and when training finished without any model generated, that will cause an error

In the meantime, in your case, the error should be "Training time finished without any models trained.", and we don't show this error in the output window, instead we prompt an error window to notify. But somehow that window doesn't show. Could you double-check and see if it's been concealed behind the main window?

**Comment by LittleLittleCloud** [comment]
The latest released ModelBuilder doesn't include that error handler PR, therefore it won't through an error window. That PR will be included in the next release.

**Comment by maximeozenne** [comment]
Hello,

I have the exact same issue when I try to use the Issue Classification on custom dataset.

I connected to my database and try to classify our tickets based on their title (here, Features) : 

![image](https://user-images.githubusercontent.com/12842987/74420135-3eb84980-4e4b-11ea-8cb1-d769f29105dc.png)

When I click on Start Training, I instantly get the "Failed. See more in Output Pane." error and the Output Pane is empty : 

![image](https://user-images.githubusercontent.com/12842987/74420287-758e5f80-4e4b-11ea-9bf2-54b097d6ab0e.png)

I tried to reduce the dataset (from 100,000 rows to 1,000) and I also increased the time to train up to 1,800 seconds but I still get the error instantly.

My dataset is purely french. Could that be a problem ? For example, does the "RemoveDefaultStopWords" function work with french words ?

**Comment by tborgesvieira** [comment]
I had the problem and solved it by changing the double value separator of "," with "."

After that I had no more problems

**Comment by FlixMa** [comment]
I am having the same issue.
As I am using a SQL Server as a datasource I would like to know how I can change the 'locale' so the wizard exports the table's float values with "." instead of "," (Indeed the file downloaded to %temp% contains on the "german windows" commas as a seperator).

**Comment by hellomrsun** [comment]
I've met the same error.
|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |

Because I have a large data set, and the train time is short, and it stopped each time with a MoveNext() exception.

I trained a smaller data set with longer train time, it worked.
So it's just the train time was not long enough.
