### ISSUE TITLE
Add support for VB.Net Projects

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#34]
https://github.com/dotnet/machinelearning/issues/3679

**Comment by Nukepayload2** [comment]
If you need help testing the VB.Net tooling support, please `@` me. I really want to enhance my VB.Net windows apps with ML.Net .

**Comment by JakeRadMSFT** [comment]
@Nukepayload2 what is the blocking issue? You should be able to call into our consume model functions from VB.NET.

**Comment by Nukepayload2** [comment]
@JakeRadMSFT The model builder can only generate c# code. We have to convert the generated code to VB.NET manually, because it's difficult for our team to maintain c# code.

**Comment by JakeRadMSFT** [comment]
At this time we're only planning to have limited support for VB (by leveraging C# code and libraries). Resolving this issue - we can revisit if more customers request VB.
