### ISSUE TITLE
Instrumentation needs to be culture invariant 

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-modelbuilder#345]
CLI (and likely Model Builder) telemetry uses local formatting for numbers. Some cultures use commas to denote their [decimal separator](https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_decimal_comma) (Brazil, France, Russia, ...x74 countries).

Example from our logs:
> `..., "Duration":"430,4808", ...` (note the comma)

This example should have a period: `430.4808` (culture invariant)

Currently, this causes under-counting of our user usage, as all non-parsable values are filled w/ zero.

**Work:**
We need to log with culture invariant floats.

**Comment by briacht** [comment]
This will affect actual train duration and eval metrics (accuracy, etc.), so we should definitely fix this. @JakeRadMSFT can you work with @justinormont on this; he has an idea on how to fix it.

**Comment by beccamc** [comment]
We are using local culture to display results here. The bug is that we're supposed to be using the period decimal separator? Don't we want to display to our customers in their expected culture?

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/af36cdfd-78ca-4de0-a838-4198412a21c6)

If the problem here is telemetry, can we fix this by not relying on the duration number (or accuracy, or whatever) to determine our user count?  I think I may be missing something in the goal here.

**Comment by beccamc** [comment]
This should be fixed. 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/01dfbb63-d154-4d31-bf7f-bae1b763a830)

**Comment by justinormont** [comment]
Thanks. 

Have you looked into Ints/Longs?

In fixing the ML․NET side, beyond just floats, we also figured out that we need to use `CultureInvariant` for Ints/Longs, as a variety of cultures use another representation of integers, mainly in negative signs, but also in other unexpected ways.

Some examples: 
* ar-SA (Arabic):   "؜-1" -- includes a non-printable [Arabic letter mark](https://en.wikipedia.org/wiki/Arabic_letter_mark) (`&#1564;`)
* fi-FI (Finnish): "−1" -- not an ascii minus sign, a Unicode [U+2212](https://www.compart.com/en/unicode/U+2212)
* he-IL (Hebrew): "‎-1" -- looks the same but has a non-printable [Unicode left-to-right mark](https://en.wikipedia.org/wiki/Left-to-right_mark) (`&lrm;`)

@mstfbl and I created sample code which tested all .NET cultures: https://dotnetfiddle.net/LtAtoi

**Comment by beccamc** [comment]
@justinormont Thanks for the additional info. I'll check these instances out.

**Comment by justinormont** [comment]
General solution was ensuring that, for all numerics:
 `x.ToString()` was changed to `x.ToString(CultureInfo.InvariantCulture)`.

To verify we finally fix it, we added a unit test, which tested `en-US`, `ar-SA`, and `pl-PL` on a full run of the AutoML code:
https://github.com/ptelman/machinelearning/blob/e37266442984e5f39205f09c0481ef6aee2bf074/test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs#L108-L157

**Comment by JakeRadMSFT** [comment]
Closing for now - this hasn't come up with our latest numbers/dashboards.
