### ISSUE TITLE
Installation florbs

### ISSUE THREAD

**Issue by walkerjian** [dotnet/machinelearning-modelbuilder#346]
Problem encountered on 
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: macOS Catalina
```
wali@cat ~ % cat << \EOF >> ~/.zprofile
# Add .NET Core SDK tools
export PATH="$PATH:/Users/wali/.dotnet/tools"
EOF


wali@cat ~ % cat ~/.zprofile 

# Setting PATH for Python 3.8
# The original version is saved in .zprofile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PATH}"
export PATH
# Add .NET Core SDK tools
export PATH="$PATH:/Users/wali/.dotnet/tools"
wali@cat ~ % zsh -l
wali@cat ~ % mlnet
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
wali@cat ~ % 
```
so ml.net wants a specific framework, which is ok I guess... Except that the pwnload button on the ml.net page want to DOWNLOAD THE LATEST FRAMEWORK instead of the one specifically asked for. So I pwnloaded the 2.1.xxx from here 

https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-2.1.802-macos-x64-installer

and now have the dilemma of wondering if I can install side by side or the old framework fubars the new one...

arghhh

I will bounce the box and try again but really...

and the insistence on mark-down with our any discernible way to turn it off has just wasted some of life and destroyed some more of my soul and given me the LIVING SCREAMING SHITS!!!!

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! We're prioritizing a transition to latest .NET Core.

**Comment by walkerjian** [comment]
Thanks Jake, and for the love of all things green and good, can you tell me if there is a way to just have plaintext for the error report, instead of markdown, which looks like a dogs breakfast… I just died a little bit trying to just get a plain old paste of plain old text because I am a plain old man...

**Comment by JakeRadMSFT** [comment]
Updated your comment to do what you want I believe you wanted to do. You can "edit" it to see what I did ... because of markup it's hard to describe :)

**Comment by JakeRadMSFT** [comment]
Also I believe they can be installed side by side!

**Comment by JakeRadMSFT** [comment]
@walkerjian resolving this issue for now. If you're still hitting issues, please re-open! Thanks!
