### ISSUE TITLE
Use GPU (Cuda) to improve training performance

### ISSUE THREAD

**Issue by ganchito55** [dotnet/machinelearning-modelbuilder#348]
I have already followed [these instructions](https://github.com/dotnet/machinelearning/blob/master/docs/api-reference/tensorflow-usage.md) to allow the GPU (cuda) support. However when I choose "Image classification", all training operations are executed in my CPU.

I'd be good if ModelBuilder could detect the GPU support and use it instead of CPU for image classification problems.

**Comment by JakeRadMSFT** [comment]
We're looking into adding this feature for the next release.

**Comment by CESARDELATORRE** [comment]
Right, GPU is still not enabled in Model Builder, for now, if you want to use GPU you need to use the API, like in this sample using the API:

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Training
