### ISSUE TITLE
Customer feedback: SQL database with 400 tables crashes VS. Table dropdown doesn't load

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#35]
Some customers reported this issue at the booth. There was not much detail beyond this. Key was large databases.

**Comment by tbombach** [comment]
We checked in a fix that we don't load a default table and a default column. So there should be less of a lag after selecting a database, but it doesn't fix the issue completely. More work to do on this one to figure out how to handle large SQL dbs

**Comment by rustd** [comment]
Add a spinner for loading tables and cols.

**Comment by rustd** [comment]
Jim wants to investigate to solve this without spinner. Basically is there a deeper root cause of connecting to large database/ tables.

**Comment by JakeRadMSFT** [comment]
Closing until more customer reports.
