### ISSUE TITLE
getting started tutorial

### ISSUE THREAD

**Issue by gerardgiraffe** [dotnet/machinelearning-modelbuilder#350]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Duplicate System.Reflections.Assembly errors 
I may have made a mistake but this is the error I get and I am not sure how to fix it

**Comment by JakeRadMSFT** [comment]
Are the project and solution in the same folder? Can you share a screenshot of VS?

**Comment by gerardgiraffe** [comment]
Thanks Jake sorry it took me so long to reply

**Comment by JakeRadMSFT** [comment]
@gerardgiraffe has this been resolved? Hopefully, making sure the project and solution aren't in the same folder (a check box when creating the project). If they are, you can fix it but excluding the folders that are causing duplicates.

If you share screenshots of your solution explorer, I can be more specific. 

We're going to resolve this issue in a future release.

**Comment by gerardgiraffe** [comment]
Thanks jake I am new to github so sorry for the delay in responding I followed the instructions and the project and solution are not in the same folder can send you a screenshot when I get home. By the way this a fantastic piece of work from your team and I will be using it with my students

GerardGiraffe
