### ISSUE TITLE
Compatible framework version was not found

### ISSUE THREAD

**Issue by greenLogic** [dotnet/machinelearning-modelbuilder#357]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: macos

Mac OS X Catalina. Dotnet 3.0 installed and found.

When using the following command:

`mlnet auto-train --task binary-classification --dataset "wikipedia-detox-250-line-data.tsv" --label-column-name "Sentiment" --max-exploration-time 10`

The result was:
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```

Thanks

**Comment by JakeRadMSFT** [comment]
Thanks for reporting. We're planning to support .NET Core 3.0 in the next release.

**Comment by justinormont** [comment]
In the meantime, you can install an x64 version of .NET Core 2.1.x:
https://dotnet.microsoft.com/download/dotnet-core/2.1

You can have both 3.0 & 2.1 installed.

**Comment by greenLogic** [comment]
Thanks a lot, I will install the requested version and finish the tutorial.
