### ISSUE TITLE
Issue with Solution and Project in same folder.

### ISSUE THREAD

**Issue by salman123-cyber** [dotnet/machinelearning-modelbuilder#359]
![Screenshot (119)](https://user-images.githubusercontent.com/52010988/69278521-52656280-0c04-11ea-904d-7b5a006cba20.png)
![Screenshot (120)](https://user-images.githubusercontent.com/52010988/69278548-61e4ab80-0c04-11ea-9081-9fe9d7f4c6c0.png)

Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows 10 64 bit
Visual Studio 2019

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! Based on the screenshots it looks like your project was created in the same folder as the solution. You'll have to exclude the two folders from MyMLApp as it's trying to treat them as source folders.

**Comment by LittleLittleCloud** [comment]
Validated in VS 2019 preview
