### ISSUE TITLE
Boolean column values should not be shown as checkboxes in Model Builder

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#36]
For Binary-classification scenarios, it is common to have values (0/1 or T/F). We show these values as checkboxes in the Data step. We should change the behavior to show the orig value vs checkboxes

[buildcustomerreviews.txt](https://github.com/dotnet/machinelearning-tools/files/3159768/buildcustomerreviews.txt)

![image](https://user-images.githubusercontent.com/1132652/57416936-3691f600-71b7-11e9-9c73-3c98c1bc2c64.png)

**Comment by LittleLittleCloud** [comment]
Is that only shows on SQL selection?
Can you just check the type of that column, to see if it's Bit or not( if it's Bit it is expected to be shown as checkbox in DataView)
