### ISSUE TITLE
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.

### ISSUE THREAD

**Issue by justbirdie** [dotnet/machinelearning-modelbuilder#360]
Hey guys sorry for noob question i just following a tutorial installing dotnet for ML.NET and everything went well until this error comes[](url)
![Screenshot from 2019-11-21 22-29-34](https://user-images.githubusercontent.com/45404643/69351812-78474180-0cae-11ea-830f-ce1fa1b09246.png)
this is my version of mlnet
![Screenshot from 2019-11-21 22-30-50](https://user-images.githubusercontent.com/45404643/69351910-9ad95a80-0cae-11ea-8795-b5ada7e137c0.png)
my dotnet of version is 3.0.101
should i installing the previous version to be able for me to following my tutorial again?

thx for the attention

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! We're planning to add support for 3.* releases of .NET Core. For now you'll have to install 2.1.0.

**Comment by JakeRadMSFT** [comment]
Tracking with #256. Resolving as duplicate. For now please install  .NET Core 2.1.0.
