### ISSUE TITLE
Status still "training" after cancel training

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#365]
I hit cancel training (no models had been found at this point) and got this:

![image](https://user-images.githubusercontent.com/10437687/69464386-3a005f80-0d4c-11ea-8942-755790b34ad7.png)

**Comment by LittleLittleCloud** [comment]
Not work on CPU image training, vs 2019-preview

**Comment by beccamc** [comment]
Validated. ![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/769e4a9d-a6b4-4aa0-b2a1-9e9e19b061f0)
