### ISSUE TITLE
Navigation not consistent (buttons vs links)

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#366]
Data (button):
![image](https://user-images.githubusercontent.com/10437687/69464615-c01ca600-0d4c-11ea-93f9-cdc916fcd05e.png)

Also do we need that "Next step" text there if there's already a button? Seems repetitive / like waste of a line of space

Evaluate (link):
![image](https://user-images.githubusercontent.com/10437687/69464560-9f545080-0d4c-11ea-98e9-01b86b6ccfff.png)

**Comment by zewditu** [comment]
Already fixed, late PR merge  during bug-bush .
