### ISSUE TITLE
Spacing weird in Next steps (Evaluate step)

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#367]
![image](https://user-images.githubusercontent.com/10437687/69464760-41743880-0d4d-11ea-8a19-399a24bc14ff.png)

@kawilkin

**Comment by zewditu** [comment]
This one fixed based on  https://app.zenhub.com/workspaces/mlnet-tools-5cde1c97e3106e39e8ae08fc/issues/dotnet/machinelearning-modelbuilder/367

**Comment by beccamc** [comment]
I think this was fixed based on https://app.zenhub.com/workspaces/mlnet-tools-5cde1c97e3106e39e8ae08fc/issues/dotnet/machinelearning-modelbuilder/352
