### ISSUE TITLE
Scrolling only works with scroll bar

### ISSUE THREAD

**Issue by kawilkin** [dotnet/machinelearning-modelbuilder#368]
1. Scrolling on "data" page is only working when you use the scroll bar on the righthand side (can't scroll with mouse pad). This is a problem for both the scrollable section

2. There should be 4px of padding between "In WebApplication5, add the following directive in the file where you consume the model:" and the box containing the code snippet
<img width="846" alt="Screen Shot 2019-11-22 at 2 28 22 PM" src="https://user-images.githubusercontent.com/47866467/69464923-935c9480-0d34-11ea-9bf6-e4da89412813.png">

**Comment by beccamc** [comment]
#2 fixed previously.
