### ISSUE TITLE
Error in installation of Model builder

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#37]
https://github.com/dotnet/machinelearning-samples/issues/431

Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows
![image](https://user-images.githubusercontent.com/39820111/57428152-adc19b80-7244-11e9-990b-88f2ebc5b9d8.png)

Please see the path error in attached image.

**Comment by JakeRadMSFT** [comment]
> Does Visual Studio run successfully? I've only seen this issue when there is a problem installing Visual Studio.
> 
> Do you see any issues if you open up Visual Studio Installer?
> 
> Thanks for reporting!

I asked customer for more details but never received any. I'm assuming my updated pre-reqs should solve this issue.

**Comment by santoshdwive** [comment]
I also face same issuse instralling Model Builder. I have VS 2019 installed.
