### ISSUE TITLE
Try it out - regression has label column name but classification does not in Result

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#371]
Also one says _Result_, and one says _Results_, should be consistent.

Regression:
![image](https://user-images.githubusercontent.com/10437687/69465044-10e0ce80-0d4e-11ea-9662-8751c07cccd0.png)

Classification:
![image](https://user-images.githubusercontent.com/10437687/69465118-45548a80-0d4e-11ea-9461-33597d1cd3e9.png)

**Comment by beccamc** [comment]
Labels shown in sentiment analysis 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/8f020470-1994-448d-9c91-70ba95e29f71)
