### ISSUE TITLE
Custom scenario broken

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#373]
1. No scenarios are available in dropdown
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/9434bbec-8964-4d8b-96ac-8071a1179f14)

2. The spacing is off
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/6571ece7-2f97-4ad4-a77b-ffe372c1cbe6)

**Comment by LittleLittleCloud** [comment]
The recommendation is not appeared in drop down list.

**Comment by beccamc** [comment]
@LittleLittleCloud  It looks to me like this is working. Are you seeing something different?

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/5efdd86f-314b-47e4-9872-8483eb9efb36)

**Comment by beccamc** [comment]
Per Jake this doesn't need to work with recommendation. Moving to ready to ship.
