### ISSUE TITLE
Issue Classification/and other scenerio doesn't work after image classification

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#375]
reproduce:
- try one of the first three scenarios
- then try image classification ( you don't have to wait it finished, just cancel that) (notice the exception thrown by tensorflow, it should also be a bug)
- then try one of first three scenarios again, training never ends, and cancel not work.

**Comment by beccamc** [comment]
@LittleLittleCloud Will this issue be fixed in your PR 429?

**Comment by LittleLittleCloud** [comment]
Yep

**Comment by beccamc** [comment]
Validated working.
