### ISSUE TITLE
Data screen textboxes - default states

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#376]
Defaults should be the same -- either all should be empty (no text) before a database/file is selected, or all should have the text. @kawilkin Do you know which is better?

Also inconsistent capitalization (Select Table vs Select column)

![image](https://user-images.githubusercontent.com/10437687/69465354-f65b2500-0d4e-11ea-9700-d55c447c7aeb.png)

![image](https://user-images.githubusercontent.com/10437687/69465503-5782f880-0d4f-11ea-9500-d2d172e83abb.png)

Also having a blank drop-down (this is before the user selects a SQL Server database) is weird; this textbook should maybe be disabled if a database isn't selected?
![image](https://user-images.githubusercontent.com/10437687/69465439-2c000e00-0d4f-11ea-96b7-2e4840308b70.png)

**Comment by kawilkin** [comment]
@briacht They should all have the helper text

**Comment by beccamc** [comment]
It looks like some of these are still missing helper text: 

Recommendation Data screen:
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/edb91f4d-947a-4ffb-a749-2622692c576b)

Sentiment Data screen:
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/bc06e23a-4c0f-456b-86b6-a4108f083d3a)

SQL Recommendation 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c78d33be-76dc-42a0-8029-4f030a285d64)

@zewditu When did the PR to fix this go in? I don't see it in the build for the bug bash today. Is this maybe missing from the build I was looking at?

**Comment by zewditu** [comment]
@beccamc  This was the PR https://github.com/dotnet/machinelearning-tools/pull/462

**Comment by JakeRadMSFT** [comment]
![image.png](https://images.zenhubusercontent.com/5cde1c65e3106e39e8ae08f2/43e3d240-0bee-49e4-8c37-934f9c830375)

It looks like it repros when you change scenario after training.

**Comment by beccamc** [comment]
This looks fine on first load. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/844b4ce3-7957-43a5-ad15-ec69ebd0e5ae)

I don't think this is high priority for users returning to train screen and picking a new scenario.
