### ISSUE TITLE
i have an issue downloading it

### ISSUE THREAD

**Issue by jessicarojas1** [dotnet/machinelearning-modelbuilder#387]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment]
Can you please provide more information?

**Comment by JakeRadMSFT** [comment]
Closing this issue for now. Please re-open if you're still hitting this issue and include more details.
