### ISSUE TITLE
While training an image classification model, I was not able to train

### ISSUE THREAD

**Issue by Technocrux** [dotnet/machinelearning-modelbuilder#389]
Metadata KeyValues does not exist

above error comes when i train a folder images, with two folders each having one image

**Comment by JakeRadMSFT** [comment]
I think that's just too small of a dataset. Model Builder splits up your dataset as part of the training process and there is no way to split one image.

**Comment by JakeRadMSFT** [comment]
@Technocrux did trying a larger dataset resolve the issue?

**Comment by Technocrux** [comment]
No Sir, same issue with large dataset as well

**Comment by JakeRadMSFT** [comment]
Can you share your dataset?

**Comment by JakeRadMSFT** [comment]
@Technocrux I believe the next release of Model Builder will have a fix for this issue. If you share your dataset we'll try to validate before release. Otherwise, I'll update this issue when we've pushed a release.
