### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by bespiloy** [dotnet/machinelearning-modelbuilder#390]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I'm using Visual Studio 2019 in Windows 10 (64-bit) operating system. I compiled the generated code as instructed from the https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume page. The compilation error is below:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'I:\Projects\Sixwise\HRI_Dev\ResearchAndDevelopment\myMLApp\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	myMLApp	C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'I:\Projects\Sixwise\HRI_Dev\ResearchAndDevelopment\myMLApp\myMLAppML.Model\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	myMLAppML.Model	C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	

Hope to hear from you soon. Thank you.

**Comment by LittleLittleCloud** [comment]
It seems that you need to run NuGet restore first before building. Try running nuget restore in Visual Studio and your problem should be gone.

**Comment by JakeRadMSFT** [comment]
Did restoring NuGet's resolve the build issue?

**Comment by bespiloy** [comment]
Sorry for the late reply. Yes doing NuGet restore solved the problem. I followed the Restore packages automatically using Visual Studio instruction from https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore link. Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JakeRadMSFT** [comment]
Awesome! Closing as resolved.
