### ISSUE TITLE
Modelbuilder 80% trainingsdata and 20% testdata

### ISSUE THREAD

**Issue by patrickbloemhof** [dotnet/machinelearning-modelbuilder#391]
Where can I acces the 20% testdata that not has been used by the modelbuilder?
Cant findt out where it writes it to.

Thanks

**Comment by LittleLittleCloud** [comment]
ModelBuilder uses either train/test split or cross-validation on your training dataset depend on how many pieces of data you have, and at the current point, ModelBuilder doesn't save the train/test split result on user's input data.

Hope this answers your question.
