### ISSUE TITLE
How to use the model trained by ML.NET under .Net Framework?

### ISSUE THREAD

**Issue by sannisy** [dotnet/machinelearning-modelbuilder#393]
I got the trained model by using ML.NET Model Builder, but when I used the model in a Winforms Application targeted to .Net Framework, some errors occurred, I want to know how to use the trained model under .Net Framework in Winforms?

**Comment by JakeRadMSFT** [comment]
What errors are you hitting? Can you send a screenshot of solution explorer?

**Comment by JakeRadMSFT** [comment]
Hello!
Closing for now ... Please re-open with more details if you're still hitting this issue.
