### ISSUE TITLE
Wrong Folder Picker

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#394]
**Describe the bug**
We use a folder picker that doesn't match other folder pickers in VS. It also doesn't open to last used location.

**Expected behavior**
Same folder picker behavior as rest of VS

**Screenshots**
Should be this:
![image](https://user-images.githubusercontent.com/31937616/70187384-e4f50f80-16a2-11ea-9d55-2aa650f93d33.png)

**Comment by JakeRadMSFT** [comment]
https://github.com/dotnet/machinelearning-tools/pull/1157

**Comment by vzhuqin** [comment]
Not repro this issue on latest main build: 16.7.2.2140901
![394 fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/22e5792d-ce22-45bb-aa9c-903f38189f99)
