### ISSUE TITLE
Clipboard copy error

### ISSUE THREAD

**Issue by Bish0pQ** [dotnet/machinelearning-modelbuilder#399]
**System Information (please complete the following information):**
 - Operating system: Windows 10 x64
-  .NET Framework version: 4.8.03752
 - Visual Studio 2019 (16.4.1)

**Describe the bug**
When trying to copy the sample code that was generated from the ModelBuilder, I got a message that the ModelBuilder threw an exception about the clipboard.

It did actually copy to clipboard so it's not that that's not working.

**To Reproduce**
Follow the tutorial and copy the sample code. I tested this on a different device (with the same setup) and there this problem didn't occur.

**Screenshots**
![download (1)](https://user-images.githubusercontent.com/25036990/70666533-1b1c2b80-1c6f-11ea-88bb-04b4066797bb.png)

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! We'll try to track this down

**Comment by beccamc** [comment]
Validation for this would just be make sure copy still works (both Ctrl + C and right click copy)
