### ISSUE TITLE
EMNIST Dataset issue

### ISSUE THREAD

**Issue by ibrahimqureshae** [dotnet/machinelearning-modelbuilder#403]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

I wanted to use model builder for training my model, when i give it the emnist dataset it doesnt let me train the data, it just doesnt enable the next option to train the data, and it doesnt show the data preview! any help? any suggestions?

**Comment by JakeRadMSFT** [comment]
Can you share screenshots and the dataset?

**Comment by ibrahimqureshae** [comment]
Link to the dataset: https://www.kaggle.com/crawford/emnist
I cannot provide screenshots at the moment, the problem was that train data was not being enabled as i suspect the dataset wasn't being read properly, so there is an issue.

**Comment by beccamc** [comment]
This isn't fixed. Loading the data preview visualization locks takes forever and locks VS.

**Comment by beccamc** [comment]
The perf for large datasets has been improved! Please try our newest build https://marketplace.visualstudio.com/items?itemName=MLNET.07. 

I've tested with datasets as large as EMNIST. Please give it a try and let me know if you run into problems. Thanks!
