### ISSUE TITLE
Failure to run ML code from ML Builder

### ISSUE THREAD

**Issue by sprinsen** [dotnet/machinelearning-modelbuilder#406]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows
Environment: Visual Studio 2017

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Could not load file or assembly 'Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

I keep getting this error even after installing NuGet as told by the online help I received so far. Any help at all resolving this would be greatly appreciated, thank you.

**Comment by JakeRadMSFT** [comment]
Did you perform a NuGet restore? Usually this is done automatically by VS but you might have to do it manually.

**Comment by JakeRadMSFT** [comment]
@sprinsen Hopefully a NuGet restore is the only thing that was needed! 

Please re-open this issue if you're still unable to run.
