### ISSUE TITLE
Unable to retrain model without updating MODEL_FILEPATH when project has a dot in the name

### ISSUE THREAD

**Issue by jernejk** [dotnet/machinelearning-modelbuilder#407]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1911.1103
 - Visual Studio Version 16.4.1

**Describe the bug**
When generating the code on a project that contains a `.`, it will translate that to `_`.
This works OK for everything except when you have to retrain your model, where you need to replace `_` to `.` in `ModelBuilder.cs` for variable `MODEL_FILEPATH`.

![image](https://user-images.githubusercontent.com/5943653/71045452-b38b4200-2180-11ea-800c-4d74a9ecd778.png)

**To Reproduce**
1. Start Machine Learning wizard from a project with a `.` in the name (e.g. `MLSample.SimpleTransactionTagging`)
2. Generate code for multi-class classification
3. Attempt to regenerate the model via `ModelBuilder.CreateModel();` 
4. It will fail because `MODEL_FILEPATH` in `ModelBuilder.cs` isn't correct

**Expected behavior**
The path should be correct. (why there was a need to convert `.` to `_` in the first place?)

**Screenshots**
![image](https://user-images.githubusercontent.com/5943653/71047063-16cba300-2186-11ea-9bc5-7de005ecef90.png)

**Additional context**
I have full steps on my blog.
https://jkdev.me/machine-learning-that-is-actually-easy/

Below the video, there are instructions in screenshots to replicate the issue. ("Updated demo (screenshots)")

The video also contains the same issue but is made with a prior version.
A similar issue has been present across a couple of versions but this specific one persisted over the last 2 versions.

I wanted to fix it myself by forking the code but I realized that the code is not available.

Can you please fix this, as it impacts every single time I demonstrate ML .NET to students, clients, and devs.

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! You're bugs are excellently reported!

We're considering going open source and feedback like yours and a willingness to fix it definitely motivated me to push from our side :). 

@LittleLittleCloud Can you look into this?

**Comment by LittleLittleCloud** [comment]
Yeah, it seems to be a bug in old CodeGen. It should be fixed after the Azure CodeGen PR get checked in
