### ISSUE TITLE
Status: Failed. See more in Output Pane. But there is no information or exception in the output pane

### ISSUE THREAD

**Issue by kartikdash1** [dotnet/machinelearning-modelbuilder#408]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment]
Duplicate of #402
