### ISSUE TITLE
Better control what type of column (forcing text feature when appropriate)

### ISSUE THREAD

**Issue by jernejk** [dotnet/machinelearning-modelbuilder#409]
Hi ML team,

I love ML.NET and I have done a tour around Australia to show Aussies how they can start their first ML prototype without investing too much time in learning ML.

ML.NET Model Builder is an incredible tool, to get started and the latest version even allows me to demonstrate that you can go a long way by just understanding a little about data science and ML.

The issue I'm consistently having is that some of my columns are consistently being used as "Categorical/One hot hash" but I really need it to be text feature. An example of a misclassified column is a bank transaction description, which contains random numbers for the same label.

The way I solve this problem is to show how to push Model Builder benefits to the max, then generate code and modify that behavior in code.

![image](https://user-images.githubusercontent.com/5943653/71088306-d736a280-21e9-11ea-9a64-90f10e9ecd02.png)
**Figure: I just change 1 line in ModelBuilder.cs in BuildTrainingPipeline.**

You can see my demo on my blog (there is a video and below that screenshots).
https://jkdev.me/machine-learning-that-is-actually-easy/

**Describe the solution you'd like**
I would like to be able to force specific columns to be either categorical or text features.

Being able to ignore columns was a huge step forward!

**Describe alternatives you've considered**
To help devs and make my life easier, I built my own "Model Builder" that generates code but I'm hoping that ML.NET Model Builder will make that obsolete. :)

https://jernejk.github.io/AutoML.CodeGenerator/

![image](https://user-images.githubusercontent.com/5943653/71088648-a7d46580-21ea-11ea-9b12-2430e1184136.png)

**Comment by JakeRadMSFT** [comment]
Thanks for reporting @jernejk!

@LittleLittleCloud and @justinormont is this an infer columns problem in AutoML? 

Should only the label column be one-hot or how should we decide between one-hot and just a text featurize?

**Comment by justinormont** [comment]
### Auto-inferencing for string columns
The column purpose inferencing for string columns is located here:  https://github.com/dotnet/machinelearning/blob/54b2b041da42b18f947b5833e64c9763108c7d32/src/Microsoft.ML.AutoML/ColumnInference/PurposeInference.cs#L151-L158
```c#
                            if (cardinalityRatio < 0.7)
                                column.SuggestedPurpose = ColumnPurpose.CategoricalFeature;
                            // (note: the columns.Count() == 1 condition below, in case a dataset has only
                            // a 'name' and a 'label' column, forces what would be an 'ignore' column to become a text feature)
                            else if (cardinalityRatio >= 0.85 && (avgLength > 30 || avgSpaces >= 1 || columns.Count() == 1))
                                column.SuggestedPurpose = ColumnPurpose.TextFeature;
                            else if (cardinalityRatio >= 0.9)
                                column.SuggestedPurpose = ColumnPurpose.Ignore;
```

This section of code is deciding between categorical, free text, or to ignore the string column. 

@jernejk's example is being inferred as `ColumnPurpose.CategoricalFeature` since it has repeating values (`cardinalityRatio < 0.7`). What a user could do is ensure the values are more unique, and then have more than one space in them, or ensure they are longer (>30 chars). 

There is a bug where this code is counting missing values towards the unique count; I have a [pull request](https://github.com/dotnet/machinelearning/pull/3880) out for this bug. The PR is waiting on the CLI to move to master first to allow for easier testing.

### Modify column purposes in Model Builder

@JakeRadMSFT: Does Model Builder have inputs for the ColumnPupose for each column?

One of the advantages of calling the ML.NET AutoML API directly (instead of wrapping the CLI), is you can first call the inferColumns API, then modify the column purposes, before running the main of the AutoML call.

In the example by @jernejk, assuming you expose a column purpose drop-down for each column in the Model Builder GUI, you'll want to remove the given column from `columnInfo.CategoricalColumnNames` array and add the column name to `columnInfo.TextColumnNames` array.

**Comment by JakeRadMSFT** [comment]
Thanks @justinormont!

**Comment by jernejk** [comment]
Thanks @justinormont!
Does this mean I can get latest version of CLI and replace the one installed by Model Builder?

I found the source code for AutoML, is this also where CLI code is or is it closed source as well?
https://github.com/dotnet/machinelearning/tree/master/src

**Comment by justinormont** [comment]
Quite welcome @jernejk! 

We haven't shipped a new [CLI version](https://www.nuget.org/packages/MLNet/) in a while, and will start shipping regularly once it's moved to master from the [AutoML feature branch](https://github.com/dotnet/machinelearning/tree/features/automl) branch ([PR for this move](https://github.com/dotnet/machinelearning/pull/4496)). 

The CLI is open source and you can build it: _(instructions are for OSX)_
```bash
cd ~/Documents/src/machinelearning/src/mlnet/ || say "fix paths in this script"
#git fetch upstream && git checkout features/automl && git merge upstream/features/automl
dotnet tool uninstall -g mlnet
git submodule update --init || say "submodule update failed"
time ../../build.sh --CleanAllProjects || say "clean failed"
time ../../build.sh -Release --CleanAllProjects || say "clean failed"
time ../../build.sh -Release && time ../../build.sh -Release --RunTests || say "release build failed"
time ../../build.sh -Release -buildpackages || say "build packages failed"
time dotnet tool install -g mlnet --version `ls ~/Documents/src/machinelearning/bin/packages/mlnet.*.nupkg | sed -E 's/.*mlnet\.(.*)\.nupkg/\1/'` --add-source ~/Documents/src/machinelearning/bin/packages/ || say "nuget tool install failed"
mlnet --version && say version success || say version run failed
```

Model Builder has moved from wrapping the CLI, to directly calling the AutoML API; hence Model Builder now has the ability to add user control of the [ColumnPurpose](https://github.com/dotnet/machinelearning/blob/ee8418a4ea7f64b97db06675855d5c6aa6bb72ba/src/Microsoft.ML.AutoML/ColumnInference/ColumnPurpose.cs) of each column. Model Builder hasn't implemented the GUI required for the user to adjust the results of [automated column purpose detection](https://github.com/dotnet/machinelearning/blob/54b2b041da42b18f947b5833e64c9763108c7d32/src/Microsoft.ML.AutoML/ColumnInference/PurposeInference.cs#L113-L218).

All that said, your best option my be to use the AutoML API directly, as it will let you modify the column purposes ([example](https://github.com/dotnet/machinelearning-samples/blob/5831bdd9bea8e42e1d3e4967486653a5df1abe4c/samples/csharp/getting-started/AdvancedExperiment_AutoML/README.md#step-4-edit-inferred-column-information)). The other route, mentioned above is to ensure the values in your text column are mostly unique (>0.70), and then have more than one space in them, or ensure they are long (>30 chars).

**Comment by jernejk** [comment]
I was hoping I could patch Model Builder by changing AutoML CLI.

The reason I'm interested to fix this via Model Builder is because it's so much easier to introduce people to ML then say writing code.
I have presented ML.NET at 10 different events (including Global AI Bootcamp) around Australia and feedback as well as impact was amazing! Most people wanted to try Model Builder and there are a few solutions at the moment being tested for production. (even in government)

On 1st of February I'll be leading first AI HackDay focused on Microsoft AI tech. The focus will be on Cognitive Services but I'll also add ML.NET, Azure ML and Azure bots. I want people to stay think about what can be solved with ML and how to get started as well as the caveats that comes with AI.

I have started to work on my own UI that generates the code for AutoML but I'm not sure if that's the right approach. (client-side Blazor which can't use ML.NET)
https://jernejk.github.io/AutoML.CodeGenerator/

For myself I'm perfectly happy to start project with AutoML, in fact I occasionally use the website above so that I don't have to write all of that code. :)

**Comment by beccamc** [comment]
@jernejk This issue has been dormant for a while, but wanted to let you know we shipped this feature with our November release! 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/92ad1fbd-31c6-4d43-932f-ace883cd662f)

**Comment by jernejk** [comment]
Thank you, this was a big issue that quite a few people encounter and I'm thrilled to update my workshops and talks to include this. 😊
This will also massively simplify my demos!
