### ISSUE TITLE
Model builder error. Unable to train the data from sql server

### ISSUE THREAD

**Issue by Deepak50** [dotnet/machinelearning-modelbuilder#411]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows 10
I'm running visual Studio 2017 community edition. I've downloaded the ml. Net model builder extension for the same. I was building a price prediction model using the model builder. The model builder takes the table from the sql server as input but im unable to train the model. Whenever I hit the train button I get the error which reads: "model builder hit an unexpected error: could not load file or assembly 'netstandard, version=2.0.0.0 , culture=neutral, publickeytoken=cc7b13ffcd2ddd51 or one of its dependencies. The system cannot find the file specified. at Microsoft. ML. ModelBuilder. TrainModelToolWindowControl. TrainSession_OnStatusChangeEventHandler(Object sender.,StatusChangedEventArgs e) at Microsoft. ML. ModelBuilder. TrainModelToolWindowControl. <StartTrainibg_Click>d_29.MoveNext()"

I've tried uninstalling and reinstalling the model builder and looked up on the internet for fix but couldn't find any.. 
Any kind of help or suggestion is much appreciated..

**Comment by JakeRadMSFT** [comment]
We'll take a look!

**Comment by Deepak50** [comment]
I just fixed this error now. The problem was I was running .Net framework 4.6.1. Now that I've updated my windows 10 to latest 1903 version, I'm able to deploy .Net framework 4.8 in it. So the error doesn't show up anymore. Thanks for all the help
