### ISSUE TITLE
ML.NET needs pipeline cancel (image classification in particular)

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#413]
Steps to reproduce:
- open task manager
- start image training, find the x64 process and take down the memory usage.
- cancel and switch to another scenario, start training. the memory usage should drop down vastly, but it doesn't
- after the new training complete, the memory usage for x64 process is still quite high

We do have to actually CANCEL the training process. It's highly important, especially to compute-intense tasks like image classification. Or it will significantly affect other running tasks. (In my case it almost freeze my laptop even after I hit cancel, and task manager shows both CPU and memory usage are quite high, it doesn't recover until I kill the service process)

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! I agree, lets push on ML.NET to support a true cancel.

**Comment by JakeRadMSFT** [comment]
Can you open a bug in ML.NET repo (or find one) and reference it here?

**Comment by LittleLittleCloud** [comment]
[Issue](https://github.com/dotnet/machinelearning/issues/4632) in machine learning
