### ISSUE TITLE
Bugs when executing: .exe file in debug file doesn't exist

### ISSUE THREAD

**Issue by JiaqiCChen123** [dotnet/machinelearning-modelbuilder#414]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When running the project, I encounter this issue. 
![image](https://user-images.githubusercontent.com/52721866/71493770-356d1200-27f6-11ea-9161-415fb5b4f56b.png)
And the exe file doesn't exits indeed, but why

**Comment by JiaqiCChen123** [comment]
Problems fixed. Remember not to choose "Place solution and project in the same directory", or there will be no execute file when debugging .

**Comment by JakeRadMSFT** [comment]
I’m glad you found a work around! Sorry for the delayed response. We have a fix for solution and projects in same folder that will go out in the next release.

Cheers!
Jake
