### ISSUE TITLE
issue in training model builder

### ISSUE THREAD

**Issue by lohumi** [dotnet/machinelearning-modelbuilder#415]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
When clicking on start training button, it shows Status as **failed**. below is the output result. 

> |     Trainer                              Accuracy      AUC    AUPRC  F1-score  Duration #Iteration             |

Please assist on this issue. 
Thanks
 Neeraj

**Comment by LittleLittleCloud** [comment]
Thanks for your feedback, we will see what we can help here.

Other than failed, is there any other exception information shows in the output panel? Or Exception window?

**Comment by lohumi** [comment]
Hello, This  issue is fixed now.  .NET  core SDK was missing in my pc, which is causing this problem. now it is resolved.

**Comment by justinormont** [comment]
@LittleLittleCloud : Would it be possible to check for a suitable version of the .NET SDK before the 1st AutoML API call?
