### ISSUE TITLE
Improve Parsing Error Description (Add Details and Line Numbers)

### ISSUE THREAD

**Issue by boazeg** [dotnet/machinelearning-modelbuilder#416]
**Model Builder Version**: 16.0.1911.1103
**Visual Studion Version**: 15.9.18

**Bug description**
Trying to load a .csv file as input fails with Unrecognized data format exception. However, no indication to row number, column number.
The file contains ~85K rows which makes it hard to spot a specific problematic record. Furthermore, I'm able to load the file in Excel with no issue (which probably means it is valid csv)

**Steps to Reproduce**
1. Create a large (~85K records, ~1K columns each, all numerical numbers - floats) feature file in .csv format
2. Try to load it as input in the model builder
3. Hit the exception after ~20 seconds. In addition, VS complains that your extension is unresponsive and suggesting to disable it... Should probably consider moving the load into a separate thread rather than the UI one...

**Expected Experience**
File is loaded correctly, or if there is indeed a problem, a better indicator of what's wrong and where in the file (row number, column number/name, etc.)

**Actual Experience**
Exception is shown, which does not help figuring out what is wrong and where. Also, can't seem to copy the exception text.
**Additional Context**
None.

**Comment by LittleLittleCloud** [comment]
Thanks for the feedback, if possible could you provide us the data file you use? It would be of great help

**Comment by boazeg** [comment]
I can't share the data, however, if you want to share a debug version of the plug-in and I can rerun with it and share debug output with you.

**Comment by JakeRadMSFT** [comment]
Hmm, we have similar issues when CSVs have quotes containing newline or commas in the columns. Can you take a look and see if there is anything special with the CSV with quotes?

We're hoping to get a fix for quotes containing newlines or commas in an upcoming release.

**Comment by boazeg** [comment]
Good catch @JakeRadMSFT - that was indeed the problem with my data - I had column names containing commas.

With that said, this issue is more about the lack of good error info when failure occurs - at a minimum a column/row number should be returned to the user.

**Comment by JakeRadMSFT** [comment]
Thanks @Boazeg! We're working on improving our parsing. I'll use this issue to improve parse error descriptions.

**Comment by JakeRadMSFT** [comment]
@boazeg can you try with the latest version of Model Builder? We've made a lot of improvements in this space.

**Comment by beccamc** [comment]
We've made tons of improvements here, but it seems that we still have a problem with mismatched header columns (extra random columns in the header). We should show something more descriptive than this 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/2d0d47d2-5e2d-41a5-89e1-62eba7c7d78f)

**Comment by beccamc** [comment]
We now show a descriptive message like...

`Parsing failed with an exception: Could not parse value P in line 99, column PavedDrive`
