### ISSUE TITLE
ML.net Model Builder

### ISSUE THREAD

**Issue by odia-o** [dotnet/machinelearning-modelbuilder#419]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment]
@odia-o This issue doesn't have any information relating to a bug. Closing this issue for now.

Please re-open with more information.
