### ISSUE TITLE
Train and Evaluate order

### ISSUE THREAD

**Issue by vamsitp** [dotnet/machinelearning-modelbuilder#421]
The auto-generated `CreateModel()` method in `ModelBuilder.cs` class calls `Evaluate()` first and then `TrainModel()`, while the Model-Builder UI/Designer shows the **_3.Train_** tab first and then **_4. Evaluate_**. Should the code be corrected to have the right order?

![image](https://user-images.githubusercontent.com/1181198/71825357-b57e5c00-30c1-11ea-85dd-802a17013bd9.png)

**Comment by JakeRadMSFT** [comment]
@briacht thoughts?

**Comment by briacht** [comment]
It works both ways, but I agree it would make sense for the steps in code to be in the same order outlined in the UI.

**Comment by LittleLittleCloud** [comment]
It will go with #397
move it to april milestone
