### ISSUE TITLE
Could not load file or assembly 'Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

### ISSUE THREAD

**Issue by Chaopeng-Wu** [dotnet/machinelearning-modelbuilder#422]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows 10
visual studio 2019. \

this is code:
![QQ截图20200107150743](https://user-images.githubusercontent.com/51105048/71875521-83233c00-315f-11ea-9058-94ade9435f65.png)

this is execute result:
![QQ截图20200107150959](https://user-images.githubusercontent.com/51105048/71875660-cb425e80-315f-11ea-9dbb-fe28b08193f0.png)

thank you help.

**Comment by Chaopeng-Wu** [comment]
I scan problem of other ask. he final solution is reinstall visual studio.
Now I have a one of option...it just have a bit  metaphysics...

**Comment by LittleLittleCloud** [comment]
Thanks for your feedback

Could you check if Microsoft.ML is installed correctly, Seems that it can't load the right assembly.

**Comment by Chaopeng-Wu** [comment]
when i install Microsoft.ML,Seems that it is complete correctly. No any exception.

**Comment by Chaopeng-Wu** [comment]
All step is Final and successful.
And predication can be used normally.
![QQ截图20200110095802](https://user-images.githubusercontent.com/51105048/72119535-b6e4a880-338f-11ea-8554-9978b5c36fa9.png)

**Comment by LittleLittleCloud** [comment]
It looks like a bug to me. Model Builder should install Microsoft.ML automatically in generated console app and Model project.

If possible, could you create a new project and start a new train to see if the DLL not found exception happened again? And also check if Microsoft.ML installed correctly in generated consoleApp and Model project? Thanks!

**Comment by Chaopeng-Wu** [comment]
Yes， It is happened again in new project.
![QQ截图20200113101459](https://user-images.githubusercontent.com/51105048/72230070-32dc2c00-35ee-11ea-8d03-7e071353cc60.png)

**Comment by Chaopeng-Wu** [comment]
![QQ截图20200113102315](https://user-images.githubusercontent.com/51105048/72230172-bc8bf980-35ee-11ea-9dcb-4e39d56709c9.png)

**Comment by LittleLittleCloud** [comment]
Is your project target to net framework instead of netcore app?

We have a known issue that on net framework, like net472, the generated project doesn't work because of missing dll.

#274

**Comment by LittleLittleCloud** [comment]
And after you install Microsoft.ML, Did you encounter another error? (Unable to load DLL 'CpuMathNative': The specified module could not be found.)

**Comment by Chaopeng-Wu** [comment]
Yes! I'm successful on NetCore.
![QQ截图20200115084925](https://user-images.githubusercontent.com/51105048/72395426-6ea0fe00-3774-11ea-9f05-43d7bbf3d02a.png)

**Comment by Chaopeng-Wu** [comment]
Summary:
    The case will happen on net framework.(I'm  used .Net framework 4.7.2)
    Use net core can be work successful.
    Thank you vary mush for your help.

**Comment by philiplai** [comment]
But I need this to work on .NET framework.  Any workaround solutions?

**Comment by infiniteloopltd** [comment]
Just to verify @Chaopeng-Wu 's solution, this error can be avoided by using .net core instead of .NET standard.

**Comment by beccamc** [comment]
@philiplai Sorry for the delay in response. Solution below..

This is a bug in the .NET Full Framework non-SDK-style project format. We are pursing a permanent fix with the .NET team. 
 
To get unblocked, upgrade your .NET Framework project to use the [SDK-style](https://docs.microsoft.com/en-us/dotnet/standard/frameworks), or start a new project using .NET Core. Checkout this [blog ](https://www.hanselman.com/blog/UpgradingAnExistingNETProjectFilesToTheLeanNewCSPROJFormatFromNETCore.aspx) by Scott Hanselman for more help.
 
If you can't upgrade to the SDK-style, use the following to get unblocked with the non-SDK-style project format..

1. Set the target platform to x64
`<PlatformTarget>x64</PlatformTarget>`
 
2. Add a package reference to your project for [Microsoft.ML](https://www.nuget.org/packages/Microsoft.ML) (latest version) 
`<PackageReference Include="Microsoft.ML" Version="1.5.0-preview" />`

**Comment by ssriram30** [comment]
> Thanks for your feedback
> 
> Could you check if Microsoft.ML is installed correctly, Seems that it can't load the right assembly.

If i try to install Microsoft.ML, then am try to build , am faced below error :

**Comment by nhannt201** [comment]
> @philiplai Sorry for the delay in response. Solution below..
> 
> This is a bug in the .NET Full Framework non-SDK-style project format. We are pursing a permanent fix with the .NET team.
> 
> To get unblocked, upgrade your .NET Framework project to use the [SDK-style](https://docs.microsoft.com/en-us/dotnet/standard/frameworks), or start a new project using .NET Core. Checkout this [blog ](https://www.hanselman.com/blog/UpgradingAnExistingNETProjectFilesToTheLeanNewCSPROJFormatFromNETCore.aspx) by Scott Hanselman for more help.
> 
> If you can't upgrade to the SDK-style, use the following to get unblocked with the non-SDK-style project format..
> 
> 1. Set the target platform to x64
>    `<PlatformTarget>x64</PlatformTarget>`
> 2. Add a package reference to your project for [Microsoft.ML](https://www.nuget.org/packages/Microsoft.ML) (latest version)
>    `<PackageReference Include="Microsoft.ML" Version="1.5.0-preview" />`

This got my Project working again, thank you!
