### ISSUE TITLE
After I set the target .NET framework to netstandard2, I ran into the following error.

### ISSUE THREAD

**Issue by philiplai** [dotnet/machinelearning-modelbuilder#424]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at SentimentAnalysis.Program.Main(String[] args)

I was using SentimentAnalysis example

**Comment by Chaopeng-Wu** [comment]
You can try reinstall visual studio.

**Comment by JakeRadMSFT** [comment]
We'll take a look!

**Comment by LittleLittleCloud** [comment]
#442

**Comment by philiplai** [comment]
I reinstalled visual studio.  Same problem.  Any other clues?

**Comment by LittleLittleCloud** [comment]
There's a known issue that Microsoft.ML doesn't work well with net framework, target to netcoreapp2.0 or higher and your problem should be fixed.

See this issue for more information #274 and #422 

Thanks @Chaopeng-Wu for reaching out to help

**Comment by LittleLittleCloud** [comment]
If you really have to target to net472, here's a workaround: ( a temporary workaround)

- install Microsoft.ML (and other dependency under generated .Model project) in your host project.
- target your host project to x64 (some of it's dependency dll can only run on x64 platform)
- run your project, you might have CpuMathNativeDLL not found issue, see next step
- build generated .ConsoleApp and go to its bin folder, copy CpuMathNative.Dll and all other DLL ends with Native to your host project's bin folder
- re-run your project, Now it should run successfully

**Comment by Chaopeng-Wu** [comment]
Nice.

**Comment by beccamc** [comment]
This is a bug in the .NET Full Framework non-SDK-style project format. We are pursing a permanent fix with the .NET team. 
 
To get unblocked, upgrade your .NET Framework project to use the [SDK-style](https://docs.microsoft.com/en-us/dotnet/standard/frameworks), or start a new project using .NET Core. Checkout this [blog ](https://www.hanselman.com/blog/UpgradingAnExistingNETProjectFilesToTheLeanNewCSPROJFormatFromNETCore.aspx) by Scott Hanselman for more help.
 
If you can't upgrade to the SDK-style, use the following to get unblocked with the non-SDK-style project format..

1. Set the target platform to x64
`<PlatformTarget>x64</PlatformTarget>`
 
2. Add a package reference to your project for [Microsoft.ML](https://www.nuget.org/packages/Microsoft.ML) (latest version) 
`<PackageReference Include="Microsoft.ML" Version="1.5.0-preview" />`

Hope this helps!

**Comment by beccamc** [comment]
Closing, please see workaround above. If you're still experiencing this problem please ping me and we'll reopen the issue. Thanks!
