### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by Fathyg** [dotnet/machinelearning-modelbuilder#425]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I can't download ML.NET Model Builder,
My operating system is windows 10 Pro,
The error message: 
This site can’t be reachedmlnet.gallerycdn.vsassets.io’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by JakeRadMSFT** [comment]
Hello,
This might have just been an intermittent problem. Could you try downloading and installing again?

**Comment by beccamc** [comment]
@Fathyg  Any luck downloading an installing again?

**Comment by beccamc** [comment]
Closing this issue. Please reopen if you're still having a problem!
