### ISSUE TITLE
mL installation issue

### ISSUE THREAD

**Issue by kamlesh48** [dotnet/machinelearning-modelbuilder#426]
when I install on ML.net it give error like : 
The extension is not installable on any currently installed product.

On my machine have  vs community 2017  version 15.6.6
plz help ...

**Comment by JakeRadMSFT** [comment]
Please update to latest version of VS 2017 or use VS 2019

**Comment by beccamc** [comment]
@kamlesh48 Friendly ping. Do you still need help on this? Did updating the version help?

**Comment by beccamc** [comment]
@kamlesh48 Thanks for reporting! We're closing this issue. If you're still experiencing a problem please comment or reopen.
