### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by GabKavinsky** [dotnet/machinelearning-modelbuilder#429]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: macos

So, to make a long story short, in the section ''Consume your model'' you asked us to enter the command, ''dotnet add package Microsoft.ML --version 1.0.0'' so I followed the instructions, but I got this error code: NU1605. After a few minutes of intense reflection, I managed to fix the problem. In fact, I just had to change the version to ''1.3.1''. For people who don't know much about programming, this is a complicated problem to solve. Maybe you should clarify this for future readers. Have a nice day! I using MacOS Catalina 10.15.2

**Comment by JakeRadMSFT** [comment]
@natke can we update the Mac documentation to add a newer ml.net package?

**Comment by natke** [comment]
Hey @JakeRadMSFT. This is actually on the dotnet website, something @briacht can probably address. But the same issue may exist on the docs website. I will look into this

**Comment by JakeRadMSFT** [comment]
Ah! Thanks @natke!

**Comment by briacht** [comment]
Good catch! I've updated the version to "1.4.0" in the Getting Started tutorial "Consume" step.
