### ISSUE TITLE
ML.Net Model Builder installation issue

### ISSUE THREAD

**Issue by swetashetye** [dotnet/machinelearning-modelbuilder#431]
**Model Builder Version**: 16.0.1911.1103
**Visual Studion Version**: VS 2019 Community 
**Bug description**
While installing ML.Net Model Builder, getting an error "Object reference not set to an instance of an object."

**Steps to Reproduce**
1. Downloaded the ML.NET Model Builder from https://marketplace.visualstudio.com/items?itemName=MLNET.07&ssr=false#overview 
2. After clicking on exe and getting an error of Object reference not set to an instance of an object.

**Expected Experience**
Successful Installation

**Actual Experience**
"Object reference not set to an instance of an object" Error as attached 

Log file

10-01-2020 05:26:09 PM - Microsoft VSIX Installer
10-01-2020 05:26:09 PM - -------------------------------------------
10-01-2020 05:26:09 PM - vsixinstaller.exe version:
10-01-2020 05:26:09 PM - 16.4.1057
10-01-2020 05:26:09 PM - -------------------------------------------
10-01-2020 05:26:09 PM - Command line parameters:
10-01-2020 05:26:09 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\user\Downloads\Microsoft.ML.ModelBuilder.vsix
10-01-2020 05:26:09 PM - -------------------------------------------
10-01-2020 05:26:09 PM - Microsoft VSIX Installer
10-01-2020 05:26:09 PM - -------------------------------------------
10-01-2020 05:26:39 PM - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Setup.Cache.Instance.get_SupportsExtensions()
   at VSIXInstaller.SetupExtensions.GetLaunchableInstances(IQuery query)
   at VSIXInstaller.SupportedSKUs.EnumerateIsolatedInstalls(Action`1 callback)
   at VSIXInstaller.SupportedSKUs.AddInstalledLocationBasedSKUs(IntPtr userToken)
   at VSIXInstaller.SupportedSKUs.InitializeSupportedSKUs(IntPtr userToken)
   at VSIXInstaller.ExtensionService.InitializeSupportedSKUs(ICommandLineData cmdLineData, IntPtr duplicatedUserToken)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by bezchristo** [comment]
Having same issue on the latest version of VS 2017

**Comment by JakeRadMSFT** [comment]
@swetashetye and @bezchristo - Are there anymore logs?  I'll follow up with our VSIX installer team.

**Comment by swetashetye** [comment]
> @swetashetye and @bezchristo - Are there anymore logs? I'll follow up with our VSIX installer team.

No more logs. The only one which is attached above.

**Comment by bezchristo** [comment]
Ok so this seems to have something to do with a broken instance in the following directory:
C:\ProgramData\Microsoft\VisualStudio\Packages\_Instances

I had one folder in there which had some missing files. I moved it to a temp directory and then tried the install again. It worked.

For more info check this link: https://developercommunity.visualstudio.com/content/problem/32018/vsixinstallerexe-cant-install-extensions-when-visu.html

**Comment by swetashetye** [comment]
@bezchristo thanks.  It worked for me.
