### ISSUE TITLE
Trailing comma in header crashes AutoML wizard & VS 2019

### ISSUE THREAD

**Issue by ericjohannsen** [dotnet/machinelearning-modelbuilder#432]
### System information

- Windows 10
- .NET Core 3.0.

### Issue

- Used the AutoML plugin in VS2019 (right-click project/Add/Machine learning)
- VS2019 crashed to the desktop
- The wizard did its thing.

### Source code / logs

The issue is caused by a trailing comma in the header. Our data extraction tool created a CSV header like:

C1, C2, C3,..CMany,Label,

Removing the trailing comma (in a text editor, or by opening the CSV in Excel and saving it) corrects the issue.

**Comment by LittleLittleCloud** [comment]
I just try to reproduce it in current model builder, now for trailing comma case,  it throws a data error ("Unrecognized data format. Please check the input file to make sure it is a valid comma or tab separated file") which is expected. So @ericjohannsen the current release should already fix your problem. 
Thanks for your feedback

**Comment by LittleLittleCloud** [comment]
Validated by Xiaoyun in VS2019

**Comment by zewditu** [comment]
Validated:  it shows the following data error and expected 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/6b0c6747-d253-4a53-a5ef-f7005c881184)

**Comment by zewditu** [comment]
I think this one should be moved to close  instead of ready to ship
