### ISSUE TITLE
Duplicate Assembly Attribute errors when try Getting Started project

### ISSUE THREAD

**Issue by s386** [dotnet/machinelearning-modelbuilder#433]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Hi.  I am trying the simple 'Getting Started' step by step project on the website, and I keep getting these errors on build (see below).  Any idea the cause?  I have windows 10 and visual studio 2019

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0579	Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute	TryML2	C:\Users\John\source\repos\TryML2\obj\Debug\netcoreapp3.1\TryML2.AssemblyInfo.cs	14	N/A
Error	CS0579	Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute	TryML2	C:\Users\John\source\repos\TryML2\obj\Debug\netcoreapp3.1\TryML2.AssemblyInfo.cs	15	N/A
Error	CS0579	Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute	TryML2	C:\Users\John\source\repos\TryML2\obj\Debug\netcoreapp3.1\TryML2.AssemblyInfo.cs	16	N/A
Error	CS0579	Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute	TryML2	C:\Users\John\source\repos\TryML2\obj\Debug\netcoreapp3.1\TryML2.AssemblyInfo.cs	17	N/A
Error	CS0579	Duplicate 'System.Reflection.AssemblyProductAttribute' attribute	TryML2	C:\Users\John\source\repos\TryML2\obj\Debug\netcoreapp3.1\TryML2.AssemblyInfo.cs	18	N/A
Error	CS0579	Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute	TryML2	C:\Users\John\source\repos\TryML2\obj\Debug\netcoreapp3.1\TryML2.AssemblyInfo.cs	19	N/A
Error	CS0579	Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute	TryML2	C:\Users\John\source\repos\TryML2\obj\Debug\netcoreapp3.1\TryML2.AssemblyInfo.cs	20	N/A
Error	CS0246	The type or namespace name 'MyMLAppML' could not be found (are you missing a using directive or an assembly reference?)	TryML2	C:\Users\John\source\repos\TryML2\Program.cs	2	N/A

**Comment by JakeRadMSFT** [comment]
This is because the project is setup in "Project in same folder as Solution". We have a fix for this in the next release.

To work around this until then, ensure the solution (.sln) and project (.csproj) are in separate folders. This is an option when creating the project from scratch.
