### ISSUE TITLE
Model builder  dont work correct

### ISSUE THREAD

**Issue by behroozbc** [dotnet/machinelearning-modelbuilder#435]
### System information

- **OS version/distro**:Windows 10.0.18363
- **.NET Version (eg., dotnet --info)**: 3.1.100

### Issue

- **What did you do?**
i want to make model with model builder 
- **What happened?**
i train i have issue 
issue message is 'see in output panel but in output panel i dont see anything 

### Source code / logs

![image](https://user-images.githubusercontent.com/20381616/72297071-51830700-3670-11ea-8fdc-91e7495b6244.png)

**Comment by LittleLittleCloud** [comment]
Thanks for your feedback.

Could we know which system language do you have?

regards

**Comment by behroozbc** [comment]
i have two language in my system 
Persian and English 
display language is English 
please fix it

**Comment by LittleLittleCloud** [comment]
Thanks @behroozbc , we will take a look
It should be a dup of #363, which will be fixed in the next release. I will go test on the fixed version to see if problem gone.

**Comment by JakeRadMSFT** [comment]
@behroozbc can you try the latest version? We've made some updates to parsing in this release.

**Comment by behroozbc** [comment]
![image](https://user-images.githubusercontent.com/20381616/75774502-62ddbb00-5d65-11ea-8fe3-85c0c3dbb661.png)
when i want update

**Comment by behroozbc** [comment]
i reinstall 
but know i get this

 
![image](https://user-images.githubusercontent.com/20381616/75781471-80655180-5d72-11ea-95d7-52f45cccc4fb.png)

**Comment by LittleLittleCloud** [comment]
Based on the exception you get, it seems that you are having dataset with special format. 

Currently, we only support csv\tsv\ simple delimiter file ending in txt without special annotation, some csv file might have comment at header and that will cause an exception in data page. 

Could we have the dataset you have, that will be of great help for us to investigate the error you have. Thanks

**Comment by LittleLittleCloud** [comment]
Hi @behroozbc

This error should be fixed in the latest release, just upgrade to latest version of ModelBuilder and have fun

![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/ac636e77-a721-4bdf-89e5-5f857867c3e7)

**Comment by behroozbc** [comment]
Okay I try this in last version
