### ISSUE TITLE
Make stable/unstable versions args optional for CLI and ModelBuilder 

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/machinelearning-modelbuilder#436]
e.g. currently in the CLI, auto-train command also takes extra parameters below:
```
> mlnet auto-train --task binary-classification --dataset wikiDetoxAnnotated40kRows.tsv --label-column-name Label --max-exploration-time 180 -S 0.17.0-preview-28416-2 -U 0.17.0-preview-28416-2
```

Where new arguments are:
```
-S or --stable-package-version
-U or --unstable-package-version
```

We can make these arguments optional, since we ship the CLI (and ModelBuilder) with a certain Automl / ML.NET the version is already known.

**Comment by LittleLittleCloud** [comment]
@briacht Should we keep those parameters in next release? They are new parameters, and could be confusing to our users
