### ISSUE TITLE
In Image Classification data page, if switch to train page before image loading completely, visual studio will crash

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#437]
step to reproduce:
- pick image classification.
- load a large dataset (weather for example)
- proceed to train page quickly(before loading animation finish)
- boom!!!

**Comment by beccamc** [comment]
Fixed with https://github.com/dotnet/machinelearning-tools/pull/454 ![ImageLoadingProblem.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/b5bef8d4-76fd-4821-a0ad-8319f7d90aee)
