### ISSUE TITLE
ML Task And Dataset in  Evaluate Page are Empty 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#438]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
The issue happened  for the first time  training 

**Steps to Reproduce**
1. select recommendation scenario
2. Upload dataset
3. Train
4. Go to Evaluate page 
5. detail tab

**Expected Experience**

![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/9eeaf6bb-3ae2-44a2-8ccb-8e60c87a3a24)
**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/39be1c27-0801-4ef8-b76f-bb1640b74943)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
Validated
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c18ad9ac-2bd3-4867-826e-01fea675f9cb)
