### ISSUE TITLE
Recommendation - Evaluate models explored table items not aligned

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#439]
![image](https://user-images.githubusercontent.com/10437687/72480441-47662300-37ac-11ea-8280-edfe5d4f07f0.png)

**Comment by beccamc** [comment]
Validated.
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/6e05b331-eaff-46e7-bd4d-e7b453bd0a76)
