### ISSUE TITLE
Capitalization in Evaluate "Next step"

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#440]
"Next Step" -> "Next step"
![image](https://user-images.githubusercontent.com/10437687/72480586-bf344d80-37ac-11ea-99bb-655c867f5a8f.png)

**Comment by beccamc** [comment]
Validated 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/773eeaad-205e-4605-8b91-fd3b8788976d)
