### ISSUE TITLE
Try it out - keep top 5 recommended items if userid does not change

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#441]
**Current behavior**
1. User hits "Predict" in Try it out for user and item
2. Users gets predicted rating for user + item combo AND user gets top 5 recommendations
3. User changes item but leaves user the same and hits "Predict"
4. Both user + item combo and top 5 recommendation predictions are recalculated

**Expected behavior**
If user keeps the same userId but changes the item, the user + item combo rating prediction should be recalculated, but the top 5 recommendations for the user should not be

**Comment by beccamc** [comment]
Validated ![recommendUser.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/4f7177b4-47a8-4583-adc7-21175d4cd046)
