### ISSUE TITLE
Try it out - user / item do not exist errors

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#442]
1. Instead of just having "user" or "item", can we use the specific Feature name?

![image](https://user-images.githubusercontent.com/10437687/72481065-2d2d4480-37ae-11ea-9fdb-ae528f667ea2.png)

![image](https://user-images.githubusercontent.com/10437687/72481183-872e0a00-37ae-11ea-97af-1da1eace9036.png)

2. Should be space in between "." and "Try" (for warning dialog when both user and item are not existing)
![image](https://user-images.githubusercontent.com/10437687/72481248-c8261e80-37ae-11ea-8652-3b6307890353.png)

3. Not as important, but if the user tries to input a user or item that does not exist, is it possible to keep a list of this or something so that if they try the same one again they don't have to wait as long to get the error?

**Comment by beccamc** [comment]
Validated
