### ISSUE TITLE
Try it out - double spinners

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#443]
1. Hit "Predict"
2. Wait for first prediction (user + item rating prediction) to show up
3. Hit "Predict" again before Top 5 recommendations are done
4. Get the following:
![image](https://user-images.githubusercontent.com/10437687/72481521-a6796700-37af-11ea-9b5d-c6b0f283150b.png)

**Comment by JakeRadMSFT** [comment]
Where should spinners be? Where should it be when the first result finishes and we're waiting for the top 5?

**Comment by briacht** [comment]
When they hit "Predict":

![image](https://user-images.githubusercontent.com/10437687/72846102-be8c3300-3c54-11ea-8b09-61d48c420612.png)


After first result finishes and waiting on second one:

![image](https://user-images.githubusercontent.com/10437687/72846136-d2d03000-3c54-11ea-9bcd-96ebd39b76cd.png)

It works correctly when you hit Predict once, but if you hit Predict again while it's trying to get the second result, that's when the double spinner happens

**Comment by beccamc** [comment]
Validated only one spinner at a time.
