### ISSUE TITLE
Generated console app error

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#444]
In the myAppML.ConsoleApp, get the following code:
![image](https://user-images.githubusercontent.com/10437687/72481609-eb050280-37af-11ea-85da-f355f51c7a15.png)

Which results in following error:
![image](https://user-images.githubusercontent.com/10437687/72481649-0bcd5800-37b0-11ea-9e56-529633045e70.png)

If you remove quotation marks it fixes the issue:
![image](https://user-images.githubusercontent.com/10437687/72481691-31f2f800-37b0-11ea-8d98-c0c2734e6dff.png)

**Comment by LittleLittleCloud** [comment]
AFAIK @beccamc is working on a fix for that

**Comment by LittleLittleCloud** [comment]
[In CodeGenerator, Recommendation scenario Training cause null reference Exception](https://github.com/dotnet/machinelearning/issues/4579)
