### ISSUE TITLE
Can't find column in Input Schema during prediction

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#445]
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/4f173e4c-e6e5-46eb-99cf-0fdc4ce63842)

Using attached data set.  Pulled from https://www.kaggle.com/zynicide/wine-reviews. Things I did to the attached data set (changes from the dataset available on kaggle)... 

1. I removed the @ in the twitter handles
2. Changed the "," in the wine descriptions to a space

I was able to train on this dataset, but rain into an error on the Evaluate screen.

**Comment by beccamc** [comment]
Here is the edited dataset. Let me know if you can't use it! https://microsoft-my.sharepoint.com/:u:/p/beccam/EUrzD6gWHl9Dt_a4m88eR6AB_Jll-IByMwobxYek2Tr8AA?e=lYed58

**Comment by beccamc** [comment]
This still happened. @zewditu Was this moved to validated by mistake?
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/534b9cd0-7cf8-436a-b1e3-8e9331f554c9)

**Comment by zewditu** [comment]
@beccamc   make sure that you have to be on updated branch this one is la ready fixed  by https://github.com/dotnet/machinelearning-tools/pull/479, but if still there is an issue let me know

**Comment by beccamc** [comment]
Validated.
