### ISSUE TITLE
Visual Studio.Net-ML.Net-Model Training-Failed. See more in Output pane

### ISSUE THREAD

**Issue by deepak102ind** [dotnet/machinelearning-modelbuilder#446]
Hi, I am trying ML.net to train the model and frequently getting stuck with <Failed. See more in Output pan> message. I see the following in the output window. 

Add MLSecondCML.Model
|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |

The data is from an csv file. I have windows 10 laptop with Visual Studio 2019. The csv is public data file about online retail data. I could import it into SQL Server, so the structure is good. 

Tried the same on various csv. Some of them works but others dont. If I know where in the CSV did the process stop, must have helped me understand better. 

Look forward to your help. 
Deepak

 Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by beccamc** [comment]
Thanks for reporting @deepak102ind! This data set is failing consistently, is that correct? Can you add a link to the data set you're using so we can take a look?

**Comment by beccamc** [comment]
@deepak102ind Friendly ping. If this is still an issue can you provide the data set?

**Comment by beccamc** [comment]
@deepak102ind  Thanks for reporting! I'm closing this issue. If you're still experiencing a problem please comment or reopen.
