### ISSUE TITLE
Imported type conflicts

### ISSUE THREAD

**Issue by cblake78** [dotnet/machinelearning-modelbuilder#447]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have 12 of the following conflicts when running on VS2019.

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0436	The type 'ConsumeModel' in 'C:\Users\cody.blake\source\MLNet\myMLApp\myMLAppML.Model\ConsumeModel.cs' conflicts with the imported type 'ConsumeModel' in 'myMLAppML.Model, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\cody.blake\source\MLNet\myMLApp\myMLAppML.Model\ConsumeModel.cs'.	myMLApp	C:\Users\cody.blake\source\MLNet\myMLApp\Program.cs	15	Active

**Comment by beccamc** [comment]
@cblake78 Thanks for reporting. I haven't seen this before and haven't been able to repro. 

It looks like you were following the tutorial from the beginning and made a new project. I assume you don't have any other classes called ConsumeModel? There is only one ConsumeModel in myMlAppML.Model? 

If its just the sample project, could you zip and upload it?

**Comment by beccamc** [comment]
@cblake78 Friendly ping! Is this still an issue? If it is, can you upload the zipped project please?

**Comment by cblake78** [comment]
Sorry, it's taken me so long to get back to you.  Attached is a Google
Drive link of my project.
 myMLApp.zip
<https://drive.google.com/file/d/1pdYYgUbWHWcPzvKW8D0eHb7sCMr8d7C-/view?usp=drive_web>

**Comment by beccamc** [comment]
@cblake78 This bug was happening because your project has the solution and csproj in the same folder. We've fixed this! If you run the latest version of model builder on this solution again it will work. You'll need to re-run our code generation to get a working model. 

Thanks for reporting!
