### ISSUE TITLE
ModelBuilder works with full Net Framework

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#451]
Model Builder currently doesn't work with net framework, and it has already been a problem that requires to be fixed since we have already received several customers' reports complain about that. We need to either update our documentation to emphasize the fact that model builder currently only supports net core app. Or enhance modelbuilder to make it support full net framework.

**Comment by JakeRadMSFT** [comment]
Added instructions to Trouble Shooting Doc
https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md
