### ISSUE TITLE
Azure Attach Telemetry

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#456]
Figure out what Telemetry we want to capture for Azure. 

- [x] Whether training local or in Azure
- [x] Accuracy of model
- [x] Model Builder training time (from when user hits "Start training" to user is able to move to Evaluate step; would it be possible to break it up into uploading data, training in azure, downloading model, etc?
- [ ] AzureML training time - can we get the actual experiment hours back from Azure?
- [x] Any errors
- [x] Whether user creates new or chooses existing: subscription, workspace, compute, experiment (capture non PII)
- [x] If a user tries to Cancel training
- [x] Not sure if we do this for local images already: # of classes, # images total, size of dataset

**Comment by briacht** [comment]
- Whether training local or in Azure
- Accuracy of model
- Model Builder training time (from when user hits "Start training" to user is able to move to Evaluate step; would it be possible to break it up into uploading data, training in azure, downloading model, etc?
- AzureML training time - can we get the actual experiment hours back from Azure?
- Any errors
- Whether user creates new or chooses existing: subscription, workspace, compute, experiment
- If a user tries to Cancel training
- Not sure if we do this for local images already: # of classes, # images total, size of dataset
- Can we get amount of $$ spent in Azure for training?

**Comment by beccamc** [comment]
@briacht This all sounds reasonable. I think we can break timings down into download, upload and training. 

The only thing I think we **can't** get is $$ spent in Azure. I doubt this info comes back in the experiment payload. I will look around to confirm.
