### ISSUE TITLE
Dealing with model in VS solution

### ISSUE THREAD

**Issue by ddobric** [dotnet/machinelearning-modelbuilder#458]
Have few recommendations (questions) regarding using of the model:

1. How to open trained/saved model?
After restart of VS, I would expect to see the model file in the list of project files.

2. Missing Training project in solution
It would be great to have the training project in the solution. The training can be started in this case from the code or from the model visual.

Thanks.

**Comment by beccamc** [comment]
Thanks for reporting @ddobric. 

1. You model is persisted in your code in the MLModel.zip. It seems like that's not what you'd expect or how you'd like to use the model. Can you tell me how you want to use that persisted model?
2. @briacht Can you help here?

**Comment by briacht** [comment]
Hey @ddobric

The the training project is included in the generated code (specifically in the ConsoleApp as ModelBuilder.cs) after training the model in Model Builder:

![image.png](https://images.zenhubusercontent.com/59810b60f8b79f8376e19948/c2dd18bc-4079-48de-969d-e5d382ad8eb5)

If you run this code in the console app, then you can re-train the model. Is that what you're looking for?

**Comment by JakeRadMSFT** [comment]
@ddobrc hopefully Bri answered your questions. Please re-open issue if not!
