### ISSUE TITLE
ML.NET Model Builder Price Prediction 'Start Training' gives error 'Trainer RSquared Absolute-loss Squared-loss RMS-loss Duration #Iteration'

### ISSUE THREAD

**Issue by danielcamps** [dotnet/machinelearning-modelbuilder#459]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have a .NET Core CLI application with "hello world", and I used the ML.NET Model Builder Extention:

Steps to reproduce: I clicked clicked "add machine learning"

Step 1. "Price Prediction".
Step 2. For the data I use a local MSSQL server (test connection succeeded), and then I configured the data. I want to predict the Value (decimal(16,6)) based on 10 input columns/features (7 integer columns, 2 datetime columns, 1 bit column)
Step 3. Train --> it wants to train for 1800 seconds. However, it quickly gives the error "Failed. See more in Output Pane", but the output pane only mentions "'| Trainer RSquared Absolute-loss Squared-loss RMS-loss Duration #Iteration |".
If have also tried setting the duration to 60 seconds, but then it says that 60 seconds is not enough for 127MB, and that I should train for longer. If I click 'try anyway', the same error occurs.

Why does it give this error and how can I fix this?

**Comment by LittleLittleCloud** [comment]
Thanks for your feedback
It sounds like an error in dataset, Could we have the tsv file under your %temp% folder? That's where sql data download to

**Comment by perkst** [comment]
I am also getting an error, I have a tabel with (Type, Date, Price, PredictedPrice), I ignore type and use the date and price to production the predicted. Only 346 rows when ran with only the predicted set as NULL.

I get "RSquared Absolute-loss Squared-loss RMS-loss  Duration #Iteration" regeardless how long i let run.

**Comment by LittleLittleCloud** [comment]
@perkst Sorry for the late reply. Could you upgrade to the latest modelbuilder and run the same experiment again, this time it should give you some error information (if there's any)

And what's your dataset's PredictedPrice looks like, is it all NULL value, or part of it is NULL while the other is number?

**Comment by beccamc** [comment]
@danielcamps or @perkst Any additional info regarding Xiaoyun's questions above? Does this still repro for you with the latest version?

**Comment by beccamc** [comment]
We don't have enough information to investigate this issue further. If you're still seeing a problem please...

1. Update to the latest Model Builder
2. Send us any updated error message.
3. Send the .tsv file in the %temp% folder produced from the downloaded sql.

Ping me and we'll re-open the issue. Thanks!
