### ISSUE TITLE
Azure Dialog - disable create in edit mode

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#462]
Disable create button on edit until something is changed.

1. Open the azure attach dialog. Choose values. Click create
2. Reopen the dialog. The "Create" button is enabled even though clicking it is the same as clicking close
Expected behavior: "Create" is disabled until a value has been updated.

**Comment by beccamc** [comment]
DONE
- Misaligned icons 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/1826e2c5-6f61-4485-a156-a8cb9cb8d898)

**Comment by zewditu** [comment]
![val.PNG](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/474ca5b0-8df1-424d-8d9e-8295a04daf39)

![val.PNG](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/e92232e4-c43b-45cf-a2c3-9c8d9866b48f)

**Comment by beccamc** [comment]
Fixed the screen to be disabled on reload. For the issue Zewditu found above, we don't fire an update until the textbox loses focus. This the wpf textbox behavior. If you were to clicked the create button with no name, it would pop and error message. We can fix this later if customers complain.

**Comment by zewditu** [comment]
validated
