### ISSUE TITLE
Filter Azure computes

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#463]
Filter computes in the Azure Attach Dialog. 

The following SKUs will **fail** for our current image models (or are close).
 
Small GPU SKUs:
* Standard_NC6 12GB RAM
* Standard_NV6 8GB RAM
* Standard_NV12s_v3 8GB RAM
* Standard_NV4as_v4 2GB RAM
* Standard_NV8as_v4 4GB RAM
* Standard_NV16as_v4 8GB RAM

[Yesterday 2:08 PM] Justin Ormont
    If you have access to details of each compute target, you can filter dynamically by removing (vm.gpuMemory <= 14GB)

**Comment by JakeRadMSFT** [comment]
STANDARD_NV6 is still showing up in the list.

**Comment by JakeRadMSFT** [comment]
User program failed with RuntimeError: CUDA out of memory. Tried to allocate 124.00 MiB (GPU 0; 7.94 GiB total capacity; 7.38 GiB already allocated; 61.00 MiB free; 54.97 MiB cached)
