### ISSUE TITLE
Configuring remote images run: unexpected red borders when picking workspace and compute

### ISSUE THREAD

**Issue by Dmitry-A** [dotnet/machinelearning-modelbuilder#466]
I am guessing this happens while the lower dialog entry is waiting for data to be loaded after a change is made for the "parent" input field.  Say I'm typing into a subscription name, and I type an existing subscription "AutoML".  Workspace input now gets a list of workspaces in that subscription.  I now keep typing to get to "AutoML Demo" and this makes the workspaces window red.

![image](https://user-images.githubusercontent.com/45412678/73317968-cd428f00-41ec-11ea-9e0c-8cf61e6040cd.png)

**Comment by beccamc** [comment]
@briacht and @JakeRadMSFT Are you figuring out the priority of this?

**Comment by beccamc** [comment]
This has been opened for 10 months and no customer has complained. This has been sitting to get a new priority for a month and no one has touched it. I'm closing this.
