### ISSUE TITLE
Azure Training- Add local creation for Workspace

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#467]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.2001.2801
 - Visual Studio Version: 16.4.3

**Describe the bug**

When creating a new Compute, clicking on *New* takes you to the Azure Portal Create VM resource page. https://ms.portal.azure.com/#create/Microsoft.VirtualMachine-ARM

Instead, it should send the user to https://ml.azure.com/compute/list.

**To Reproduce**
1. In the **Train** step, select **Edit Experiment**
2. Click on the **New** link next to the **Compute Name** dropdown.

**Screenshots**

![image](https://user-images.githubusercontent.com/46974588/73317983-fd4a5c00-4205-11ea-855b-69ee86dbbae6.png)

**Comment by beccamc** [comment]
To fix this, we're going to add a simple add experience locally. See original [figma ](https://www.figma.com/file/Ldml2fLl1ctocPyyfaCAbDll/ML.NET-Model-Builder%3A-Azure-Attach?node-id=221%3A864&viewport=-2599%2C860%2C0.5191625952720642) for more details

**Comment by beccamc** [comment]
Create compute done!
