### ISSUE TITLE
Exception when starting experiment

### ISSUE THREAD

**Issue by natke** [dotnet/machinelearning-modelbuilder#469]
**Model Builder Version**: 16.0.2001.2801
**Visual Studion Version**:16.4.3

**Bug description**
See attached exception. This occurred at the start of training. 
![Capture.PNG](https://images.zenhubusercontent.com/5ce48d4d5eba81334339009f/57e149ee-2998-41d3-a44b-2831ca33992d)

**Comment by beccamc** [comment]
Watch for another repro of this. Specifically if Natalie see this again with a different build.
