### ISSUE TITLE
Re-opening folder picker and closing out without changing folder should not stop training

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#471]
1. Select Image Classification scenario
2. Select dataset from folder
3. Start training (either local or Azure)
4. Go back to Data step, click folder picker to open File Explorer, exit out without changing folder / filepath
5. Training stops

This only happens for image classification, not text scenarios

**Comment by beccamc** [comment]
Two things here..

1. This should be fixed by adding a warning dialog when you re-open the folder picker
2. Nothing should happen when you cancel. it should be a no-op
