### ISSUE TITLE
Evaluate screen bugs

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#472]
![image](https://user-images.githubusercontent.com/10437687/73488770-62b16080-435e-11ea-99cb-48c2fde7777b.png)

1. "ML Task" -> "ML **t**ask"
2. Let's get rid of "Output to predict (Label)" row
3. Best model accuracy wrong (should be 75% -- there's another bug filed for this)
4. "Algorithm" -> "Algorithm:" (adding : )
5. Training Time is wrong -- I did not train for 24 days
6. "Training Time" -> "Training **t**ime"
7. In the table, Duration says "0"

**Comment by beccamc** [comment]
Fix everything above and both local and remote image should share the same info (I believe there is a "Top level folder" label we show for local image. )

**Comment by beccamc** [comment]
I'm seeing an empty Output to predict on local as well. This is a screenshot of Local Image Classification
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/71e2bc32-a400-43f1-b19a-2da744ff1140)
