### ISSUE TITLE
Unhandled exception in model consumption

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#473]
Get this error:
**Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ML.OnnxTransformer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.**

when trying to consume model (with this code):
![image](https://user-images.githubusercontent.com/10437687/73497107-d9eef080-436e-11ea-9925-8d806346cd4e.png)

**Comment by LittleLittleCloud** [comment]
What project do you create? Net 472 or net core app?
And could you check the version of Microsoft.ml installed in your project?

**Comment by briacht** [comment]
It is .NET Core 3.1 and Microsoft.ML 1.4.0 preview 3.

**Comment by codemzs** [comment]
What all nugets did you include?

**Comment by briacht** [comment]
I didn't add any after code gen. We should add whatever nugets they need. Which ones are required?
