### ISSUE TITLE
Reset warning locations

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#474]
This will be initially for **images only**

After a user hits "Start training" (whether training is in progress or already completed), they will receive a warning dialog (that they will lose their progress and will have to start over) if they try the following actions:
- If user selects a new scenario
- If user opens folder / file picker
- If user hits "Cancel training"
- If a user tries to close out of Model Builder
- If user selects "Edit experiment" or "Create experiment"

**Comment by LittleLittleCloud** [comment]
Currently we dont reset experiment when user create/edit Azure experiment, so it's safe for user to update their experiment information as long as they don't click on start training/cancel training.
