### ISSUE TITLE
 Unable to  select and deselect feature columns - only select all or clear

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#476]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1.  select any text scenario except Recommendation
2.  choose file 
3. select label column
4. try to deselect a feature column

**Expected Experience**
1. a drop-down that contain list of  feature columns 

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/9913153b-7395-453f-9649-a4f021ddaa3d)_

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by luisquintanilla** [comment]
I found the same issue using VS2017

**Comment by beccamc** [comment]
Validated in VS 2017
