### ISSUE TITLE
Show more info when uploading data to Azure

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#480]
It costs like 20-30 minutes to upload weatherdata folder in my apartment, and cifar 10 even more.

In that case, we need to show some progress to let the user know we are uploading data, so as to improve their using experience.

@briacht  any thoughts?

**Comment by briacht** [comment]
Yes we should definitely show any progress info that is meaningful to the user. What info is available? We can include it in the Progress section of Train screen, but might need to consult Kaitlin on exactly how to show it.

**Comment by LittleLittleCloud** [comment]
here is the message struct from AZCopy
```
        public override string MessageType => "Progress";

        public string ErrorMsg { get; }

        public string JobStatus { get; }

        public int TotalTransfers { get; }

        public int TransfersCompleted { get; }

        public int TransfersFailed { get; }

        public int TransfersSkipped { get; }
       
        // includes bytes sent in retries (i.e. has double counting, if there are retries) and in failed transfers
        public double BytesOverWire { get; }

        public double TotalBytesTransferred { get; }

        public double TotalBytesEnumerated { get; }

        public double TotalBytesExpected { get; }

        public float PercentComplete { get; }

        public List<FailedTransfer> FailedTransfers { get; }

        public List<FailedTransfer> SkippedTransfers { get; }
    }
```

**Comment by briacht** [comment]
In Progress section, under Status
- If user has not uploaded dataset before:
   Uploading data to Azure (33.33%...)
- If user re-trains with same dataset (without making changes) or if they delete images from dataset:
   Data already uploaded. Skipping data upload.
- If user re-trains with same dataset after adding more images to local dataset:
   Uploading new images to dataset in Azure (33.33%...)

**Comment by LittleLittleCloud** [comment]
@briacht I just find out (Thanks @JakeRadMSFT ) that we can get the # of skip file while uploading). Do we want to show the skip file either?

I'd prefer do that since it might still take a  long time even we do skip, and before that progress won't be updated, which will be always zero
