### ISSUE TITLE
Image Classification - Data selection doesnt show Train button upon selecting photos directory. 

### ISSUE THREAD

**Issue by Harshil13** [dotnet/machinelearning-modelbuilder#483]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment]
@Harshil13, Can you provide more details about the issue you are hitting? Can you share the dataset?
