### ISSUE TITLE
Select existing Azure Experiment

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#486]
Current experience: 

Experiment name is text box. If you use the same string as an exisiting experiment name, it will be selcted instead of created. 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/2ae8ca61-c67f-40c9-98e0-da12d16d7d71)

Ideal experience: 
1. Experiment name becomes a drop down with exisiting names
2. Add "new..." to launch a new dialog to input a new name. Similar to this (but only with name)
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/086a9271-5754-407a-9f60-5d9dc1e62268)

**Comment by JakeRadMSFT** [comment]
Won't fix for now.
