### ISSUE TITLE
Indicate in VS that user should create Enterprise workspace

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#488]
If we are sending a user off to the web to create a new workspace, we should have somewhere in Model Builder (before they go to web) that they need to select an Enterprise workspace

**Comment by JakeRadMSFT** [comment]
I think we should consider showing non-enterprise workspaces but disable them in the dropdown.

**Comment by beccamc** [comment]
Closing as this is no longer relevant. We allow in UI creation of workspaces with this PR - https://github.com/dotnet/machinelearning-tools/pull/510
