### ISSUE TITLE
Machine Learning Output window does not open

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#490]
If my Output window is open on another output and I hit "Start training", the Output window does not open to Machine Learning to show progress

Expect that when user hits "Start training" Output window opens to ML

**Comment by JakeRadMSFT** [comment]
We should also clean up output for Azure Training.

**Comment by briacht** [comment]
Ok so I realized that I just have to wait a bit for it to show up!

It doesn't open for "uploading data" step.. but once "reading data" status comes up then Output window opens to Machine Learning
