### ISSUE TITLE
Dialog and Browser opening not get focused /Foreground for link clicks  

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#491]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
1. Select Image scenario
2. load your Image data set
3. got to Train.
4. Select Azure
5. Create experiment 
6. click on new link

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
The browser get focused.
**Actual Experience**
The browser blink..blink at task bar .. and get normal 

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by JakeRadMSFT** [comment]
We should see if we can solve this for Dialogs too.

Let's reach out vsxdisc to ask for recommendations.

**Comment by beccamc** [comment]
I've updated our links to all open with the same utility. It uses the VS browser default "Open with..."  To change it you need to right click on a web file in VS and select "Open with.." (if anyone knows an easier way to change, let me know!)

Browser links are now opening in my preferred web browser (new chromium edge) and popping to the front of the screen.

**Comment by beccamc** [comment]
This PR https://github.com/dotnet/machinelearning-tools/pull/581

**Comment by zewditu** [comment]
when links clicked browsers get focused
