### ISSUE TITLE
ModelBuilder still go the next step(downloading model) after Azure training shows error

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#494]
![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/acaf118c-9128-4b74-ad27-fbf19e35954d)

**Comment by zewditu** [comment]
I also get the same

**Comment by LittleLittleCloud** [comment]
azure training should throw an exception (training error) if train process failed, so as to keep the behavior same with other experiments

**Comment by zewditu** [comment]
@LittleLittleCloud   how do you make your  remote training  failed?
