### ISSUE TITLE
Error with Azure training

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#497]
Not sure what this one is about:
![image](https://user-images.githubusercontent.com/10437687/73987275-a7a43c80-48f4-11ea-8ef6-a9454e45c330.png)

I went through like normal and was able to select workspace, compute, etc. like normal.

Also -- would it be possible when a user select "report issue" to send them to an already filled out template of a bug with their version of VS, Model Builder, and also the error message?

**Comment by JakeRadMSFT** [comment]
Not sure about the root cause but we should add retry logic. This seems like an intermittent error.

**Comment by beccamc** [comment]
@JakeRadMSFT Xiaoyun added retry logic right? Can this be closed?

**Comment by beccamc** [comment]
Retries have been implemented. Closing this.
