### ISSUE TITLE
Try it out has extra "Label" class

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#498]
In Try it out on Evaluate screen, there is an extra class called "Label" (should just be rainy, cloudy, and sunny based on dataset):

![image](https://user-images.githubusercontent.com/10437687/73988396-6feac400-48f7-11ea-8006-bc288d7141ca.png)

**Comment by JakeRadMSFT** [comment]
Azure training

**Comment by LittleLittleCloud** [comment]
They are from downloaded onnx label map, not from ModelBuilder
Does Azure Image changes anything?

**Comment by LittleLittleCloud** [comment]
Remove "ImageSource Label" in remote file and problem will be solved
