### ISSUE TITLE
Need a public changelog  - e.g. Add releases tab in the new issues repo.

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#50]
https://github.com/dotnet/machinelearning-modelbuilder

**Comment by greazer** [comment]
https://github.com/dotnet/machinelearning-modelbuilder/releases. Currently, each "release" is:
* The date of release 
* The associated version of the extension
* A pointer to the blog post describing it.

It's also necessary to create a tag for the source, which for this repo happens to be simply public documentation.

**Comment by rustd** [comment]
@greazer can you please add the VSIX as well to the release artifacts?
