### ISSUE TITLE
dotnet framework error

### ISSUE THREAD

**Issue by KoWunnaKo** [dotnet/machinelearning-modelbuilder#501]
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: linux

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment]
We're using #256 ... to track multi-targeting 2.x and 3.x.

For now, please install .NET Core 2.1 to use MLNET CLI.

**Comment by JakeRadMSFT** [comment]
Please re-open if installing 2.1 doesn't resolve the issue.

Thanks for reporting!
