### ISSUE TITLE
Image Classification Pipeline crashes

### ISSUE THREAD

**Issue by michalkubis** [dotnet/machinelearning-modelbuilder#502]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1911.11.3 (Preview)
 - Visual Studio 2019 Community 16.4.4

**Describe the bug**
Training fails during image classification. I have 10 folders, digits from 0-9, each contains 500 images. Training works fine on other machines, but not on machine with older CPU Core2 Duo T8300.

Output pane content - [output.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4177021/output.txt)

**Comment by JakeRadMSFT** [comment]
Hmm, can you provide more information about the machine? How much memory/ram does it have?

**Comment by michalkubis** [comment]
4GB, details attached, if the hardware is too old, you can ignore this issue.

[hwinfo.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4182758/hwinfo.zip)

**Comment by JakeRadMSFT** [comment]
I believe it is because the machine's specs are powerful enough. I'll followup with the ML.NET team though.

**Comment by beccamc** [comment]
@michalkubis Unfortunately this machine isn't powerful enough. We do now offer training on Azure if you need more power... although it sounds like you were able to complete this on another machine. Let us know if you run into any other issues. Thanks for reporting!
