### ISSUE TITLE
Unable to use the Extension

### ISSUE THREAD

**Issue by Ravi-TStark** [dotnet/machinelearning-modelbuilder#506]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

I installed the extension but it does not show up in the menu. I am running Visual Studio 2019 v16.4 and My app uses .Net Core 2.1

**Comment by JakeRadMSFT** [comment]
Can you share a screenshot of your installed extensions? Is it showing up as installed but disabled?

**Comment by Ravi-TStark** [comment]
Thank you for your response.
I got the problem sorted out. Apparently restarting Visual Studio and
reinstalling the extension worked out.
Thanks Again!

**Comment by JakeRadMSFT** [comment]
Of course! Thanks for reporting and I'm glad you found a way to resolve it!
