### ISSUE TITLE
Object detection in Model Builder

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#508]
- "When I use Model Builder, I want to train an object detection model, so can model builder support object detection training? I feel like I don't support it at the moment. For example, I want to make a palm recognition model, not picture classification."
  https://marketplace.visualstudio.com/items?itemName=MLNET.07&ssr=false#qna

- Another ask from Model Builder user study (anonymous)

- Ask from ML.NET Survey (anonymous)

**Comment by JakeRadMSFT** [comment]
Tracked using other issues.

**Comment by beccamc** [comment]
Looks like there was another customer request in the marketplace ![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/a8e62e71-e5c1-4af4-adb8-4d5c43395871)
