### ISSUE TITLE
RMSE should be greater than zero

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#509]
In recommendation scenario, the evaluation metrix showing in ModelBuilder is RMSE, but it's actually R-square. We need to change it back.

**Comment by justinormont** [comment]
You may want the ability for users to choose their optimization metrics. Then you'll just have to ensure the right one is displayed.

**Comment by LittleLittleCloud** [comment]
thanks Justin, though it's not gonna happened in this release
