### ISSUE TITLE
Installation Issue with Model Builder, have VS 2019 latest version

### ISSUE THREAD

**Issue by santoshdwive** [dotnet/machinelearning-modelbuilder#51]
![image](https://user-images.githubusercontent.com/39820111/57998703-403d2700-7af0-11e9-95ff-e6c964d8762f.png)

**Comment by JakeRadMSFT** [comment]
Did VS2019 install correctly/fully? You can check by opening up "Visual Studio Installer" and see if there are any warnings.

**Comment by rustd** [comment]
@santoshdwive can you please check if VS2019 installed correctly/fully?

**Comment by greazer** [comment]
@santoshdwive Please reactivate or enter a new issue if you have not been able to resolve this problem.
