### ISSUE TITLE
Cant donwload the mail or mac

### ISSUE THREAD

**Issue by tobyungwe** [dotnet/machinelearning-modelbuilder#510]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment]
Can you provide more information about what steps you've taken and what issue you are hitting?

**Comment by JakeRadMSFT** [comment]
Resolving due to lack of activity. If you still hit this issue .. please re-open!

Thanks for reporting!
