### ISSUE TITLE
Image Classification  Scenario click sends unhandled Exception

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#511]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. on Scenario page click Image classification
2. _Thanks for reporting!_

**Expected Experience**
Move to data page 
**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/3f086991-06f2-4d4a-91c9-9b6870e4e3e0)
**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by LittleLittleCloud** [comment]
It's just mismatch in namespace in generated project, upgrade to master branch and you should be fine
