### ISSUE TITLE
Weird bug - wrong labels

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#517]
I was using a text dataset for flight delays, with ARR_DEL15 as the Label column to predict (values of 0 or 1), and when I went to evaluate and try the model, the prediction I get is "98% cloudy, 2% Label.

1. Choose issue classification
2. Choose FlightData.csv file
3. Choose feature columns and Label column
4. Train
5. Evaluate try it out -- get weird labels that are not in dataset at all

![image](https://user-images.githubusercontent.com/10437687/74865873-aa485e00-5306-11ea-897a-3102f628ac49.png)

**Comment by edoardottt** [comment]
Without code is difficult....

**Comment by LittleLittleCloud** [comment]
Did you just finish an Azure image train and then run this training?
