### ISSUE TITLE
Display name of `Column to Predict (Label)` options inconsistent with `Data Preview` headers

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#52]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1905.641
 - Visual Studio Version: 2017, 2019

**Describe the bug**
In the *Data* step of building a model, the values in the `Column to Predict (Label)` are inconsistent with those in `Data Preview`. In the screenshot, the actual column name in the file is `fare_amount`. The `Data Preview` removes the underscores. `trip_time_in_secs` does have underscores both in `Column to Predict (Label)` and `Data Preview`, although still inconsistent.

**Expected behavior**
The names in `Column to Predict (Label)` should match those in the header of `Data Preview`. 

**Screenshots**

![image](https://user-images.githubusercontent.com/46974588/58043011-29a3c980-7b0a-11e9-87ec-59473ce3331f.png)

The file / data used comes from this [file](https://raw.githubusercontent.com/dotnet/machinelearning-samples/master/datasets/taxi-fare-train.csv).

**Comment by JakeRadMSFT** [comment]
@tbombach, Thoughts?

**Comment by tbombach** [comment]
Thanks for filing! I think this comes from the WPF datagrid control. I believe it automatically removes underscores in the header unless you double them: https://stackoverflow.com/questions/9403782/first-underscore-in-a-datagridcolumnheader-gets-removed
