### ISSUE TITLE
Link for "What is an Azure ML experiment?" goes to wrong place

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#520]
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/44970be6-51c9-4b04-a05f-fc2f071d0b3f)

^ Above link goes to - https://docs.microsoft.com/en-us/azure/machine-learning/how-to-manage-workspace.  It seems it should go to an explanation page instead of instructions on creating a new workspace? 

The forward link is http://aka.ms/vsmbazureml

**Comment by briacht** [comment]
Changed to https://docs.microsoft.com/en-us/azure/machine-learning/concept-workspace
