### ISSUE TITLE
No status reported for local workspace creation

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#523]
When creating a workspace locally, there should be a bit more status than just the spinner:

![image](https://user-images.githubusercontent.com/10437687/74868780-a9fe9180-530b-11ea-967f-3069598612d6.png)

Maybe we can do something like "Creating an Enterprise workspace in Azure. This may take a few minutes..."

@kawilkin ?

**Comment by beccamc** [comment]
Jake thinks this can wait til next release

**Comment by beccamc** [comment]
Added text suggested by Bri above
