### ISSUE TITLE
Cannot have spaces or special characters in compute or workspace names

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#529]
It turns our you cannot have spaces or special characters in the names of our computes and workspaces. If you have a space in your name we get an ugly error returned from the server. 

Yes, ideally we would do a check as users are typing and show a red border with a pop up. This would probably take a day of dev work. I propose doing a faster fix, and come back to the nice fix later if it's important. 

Two much faster fixes... 
1. We automatically strip any spaces or special characters from the name
2. When the user hits create we check their names and pop a more friendly error message saying what is wrong with the name.

**Comment by JakeRadMSFT** [comment]
I feel like there should just be a regex somewhere we could steal

**Comment by JakeRadMSFT** [comment]
3. If we show a good enough error message when it fails ... ship it as-is.

**Comment by briacht** [comment]
I don't think we should change the name they create; let's do #2

"Your compute [workspace] name cannot contain spaces or special characters. Please pick a different name."

**Comment by LittleLittleCloud** [comment]
adding an underline score will cause a 400 bad request, maybe we just add underline as illegal char as well?
