### ISSUE TITLE
Change from error to warning dialog

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#53]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1905.641
 - Visual Studio Version: 2017, 2019

**Describe the bug**
After training is successful, and the generated projects have been added to the current solution, when trying to close the ML.NET Model Builder screen, an error prompt asks whether the user wants to cancel training. 

**Expected behavior**

If training is successful and projects have been added to current solution, no error prompt should appear when closing ML.NET Model Builder screen.

**Screenshots**

![image](https://user-images.githubusercontent.com/46974588/58048335-88703f80-7b18-11e9-949e-b7bda27dfeb5.png)

**Comment by tbombach** [comment]
Thanks for filing this @luisquintanilla! Definitely a bug and something we want to fix. Thank you!

**Comment by rustd** [comment]
Change dialog from "Error - Warning". 
Update error message - "Model Builder"

**Comment by tbombach** [comment]
## Engineering work:
- We currently have code that determines if the window should close (https://github.com/dotnet/machinelearning-tools/blob/master/MLNET%20Model%20Builder/ToolWindows/TrainModelToolWindowControl.xaml.cs#L64). It currently checks if the user has made changes and prompt if the user has. We should skip prompting if the user has completed the "Code" tab.

**Comment by rustd** [comment]
Change the title of dialog box to say Warning. That is the only change required.
