### ISSUE TITLE
Build Errors Following Tutorial

### ISSUE THREAD

**Issue by ScottinTexasUS** [dotnet/machinelearning-modelbuilder#533]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/generate-code
Operating System: windows

When I tried to run the MyMLApp.ConsoleApp there were 7 build errors. CS0579.
These were in MyMLAppML.Model.AssemblyInfo.cs file.

[assembly: System.Reflection.AssemblyCompanyAttribute("MyMLAppML.Model")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("MyMLAppML.Model")]
[assembly: System.Reflection.AssemblyTitleAttribute("MyMLAppML.Model")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

This is the output from the Build.

1>MyMLAppML.Model\obj\Debug\netstandard2.0\MyMLAppML.Model.AssemblyInfo.cs(14,12,14,54): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
1>MyMLAppML.Model\obj\Debug\netstandard2.0\MyMLAppML.Model.AssemblyInfo.cs(15,12,15,60): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
1>MyMLAppML.Model\obj\Debug\netstandard2.0\MyMLAppML.Model.AssemblyInfo.cs(16,12,16,58): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
1>MyMLAppML.Model\obj\Debug\netstandard2.0\MyMLAppML.Model.AssemblyInfo.cs(17,12,17,67): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
1>MyMLAppML.Model\obj\Debug\netstandard2.0\MyMLAppML.Model.AssemblyInfo.cs(18,12,18,54): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
1>MyMLAppML.Model\obj\Debug\netstandard2.0\MyMLAppML.Model.AssemblyInfo.cs(19,12,19,52): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
1>MyMLAppML.Model\obj\Debug\netstandard2.0\MyMLAppML.Model.AssemblyInfo.cs(20,12,20,54): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute

Thanks,

Scott

**Comment by JakeRadMSFT** [comment]
This is resolved in the lastest version of Model Builder - released last Thursday. Can you upgrade and try again?

**Comment by JakeRadMSFT** [comment]
Resolving due to lack of activity. I believe this issue has been resolved in the latest version. If you still hit this issue .. please re-open! 

Thanks for reporting!
