### ISSUE TITLE
AutoMLService training fails when there's error in one of trainers

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#538]
Steps to reproduce

Dataset:
dataset-sqlserver.database.windows.net taxi-fare/Biance

select HighPrice as label, de-select ID and pick regression, click training

**Comment by FlixMa** [comment]
Having the same problem with own dataset:

    Poisson regression must regress to a non-negative label, but label -0.2607227 encountered

Then whole process failes and I am not able to generate the code.
Workaround: Use a training time where it doesnt reach that specific algorithm and retrain after code gen.
