### ISSUE TITLE
More proper way to handle headless csv file

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#54]
Currently when handling headless data, we simply just put the first line as header, which is inappropriate for the following reasons:

- Users might be confused about strange labels ( because if there's no header, the first row of data will be the label, which is kind of confusing)
- some values might be duplicated, which will cause a duplicate error in DataTable

In the older version Model-Builder, they use the following method to solve the problems

- provide a panel so that user can customize behave of the parser
![image](https://user-images.githubusercontent.com/16876986/58060399-2ae2ef80-7b26-11e9-8512-57c09095c73e.png)

- use ML.pipline sdk to make some assumption for user in csv file

We may consider older ML-builder's solution as for the new one, or make some change based on that

**Comment by JakeRadMSFT** [comment]
#32

**Comment by JakeRadMSFT** [comment]
closing #32..  although this one is kind of a dupe... it has more info. Thanks @LittleLittleCloud !

**Comment by rustd** [comment]
We don't want the UI options. We should be able to use the logic to parse the file(s)

**Comment by rustd** [comment]
#73
