### ISSUE TITLE
Training time is zero when it's image training

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#542]
Steps to reproduce

pick image training. loaded image folder and go to train step

move backward to data page, reload image folder and click on training tab immediately

start training

![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/d4a46b89-1924-49b5-84f0-860dcd51252c)

**Comment by beccamc** [comment]
Verified. I can't get to the train tab until the image data preview is loaded.
