### ISSUE TITLE
In the training phase it doesn't executed properly it shows failed message.

### ISSUE THREAD

**Issue by Nivedha6698** [dotnet/machinelearning-modelbuilder#545]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment]
Can you provide more information about what steps you've taken and what issue you are hitting?

**Comment by JakeRadMSFT** [comment]
Resolving due to lack of activity. If you still hit this issue .. please re-open!

Thanks for reporting!
