### ISSUE TITLE
Error when compute cluster doesn't exist 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#547]
Open azure dialog 

1. Choose ModelBuilder workspace 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/725d1fcc-b66a-4389-9d46-beab835ebbec)

The problem is one of the computes is in a bad state 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/15d7934e-d5e6-4770-89de-dcff89ee7e4a)

It's VM size is null 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/bb628119-4b76-4cd1-acd4-674c187dd8ee)

**Comment by LittleLittleCloud** [comment]
- [x] VS2019 Preview2
