### ISSUE TITLE
No result for custom prediction

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#548]
1. Do a custom scenario
2. Train, and then go to evaluate
3. Click Predict. We show the loading spinner but the prediction isn't there 

![NoResultForCustomPrediction.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c4a099ed-7964-4c8a-b222-250e8898db5f)

**Comment by beccamc** [comment]
This will probably get cut if we remove custom this release.

**Comment by JakeRadMSFT** [comment]
We're removing custom in the up coming release.
