### ISSUE TITLE
Ml.net execution

### ISSUE THREAD

**Issue by rajeshchoudhary2312** [dotnet/machinelearning-modelbuilder#552]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rajeshchoudhary2312** [comment]
Plz help me out

**Comment by JakeRadMSFT** [comment]
Can you please provide more details of what is happening?

**Comment by JakeRadMSFT** [comment]
Resolving due to not enough details. Sorry you're hitting an issue! If you add more details, please re-open bug.
