### ISSUE TITLE
mlnet not recognized

### ISSUE THREAD

**Issue by gigabyte-sha** [dotnet/machinelearning-modelbuilder#554]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment]
Can you please provide more information about what steps you've tried and what errors you're hitting?

**Comment by JakeRadMSFT** [comment]
Resolving due to not enough details. Sorry you're hitting an issue! If you add more details, please re-open bug.
