### ISSUE TITLE
Visual Studio 2017 Minimum Version Required

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#56]
Not exactly a bug. More of clarification. In the machine learning samples [document describing Model Builder](https://github.com/dotnet/machinelearning-samples/tree/master/modelbuilder), the *prerequisites* mention Visual Studio 2017 15.6+. At the bottom of the document in the *limitations* section, it says Visual Studio 2017 15.9.12. When I tried to install it on version 15.4 I got the message shown in the screenshot, which makes sense since it's < 15.6. Just looking for clarification on which version is the minimum, 15.6 or 15.9.

![image](https://user-images.githubusercontent.com/46974588/58202236-f8133580-7ca4-11e9-91c5-f461d913f2e9.png)

**Comment by rustd** [comment]
Min version 15.9.12 which is the new release going out soon.

**Comment by luisquintanilla** [comment]
Great. Thanks
