### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by infoneto-shmuel** [dotnet/machinelearning-modelbuilder#561]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows

I can't install it. and the log doesn't tell me what I am missing.
here is the log:

03/03/2020 16:03:22 - 	SignedBy           : Microsoft Corporation
03/03/2020 16:03:22 - 	Certificate Info   : 
03/03/2020 16:03:22 - 		-------------------------------------------------------
03/03/2020 16:03:22 - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
03/03/2020 16:03:22 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
03/03/2020 16:03:22 - 		[Serial Number] : 3300000304101C68D65CB4BF29000000000304
03/03/2020 16:03:22 - 		[Not Before]    : 05/06/2019 20:36:58
03/03/2020 16:03:22 - 		[Not After]     : 03/06/2020 20:36:58
03/03/2020 16:03:22 - 		[Thumbprint]    : A28267BD2BB3838A16666C63F4BB21D37CE0619B
03/03/2020 16:03:22 - 
03/03/2020 16:03:22 - 	Supported Products : 
03/03/2020 16:03:22 - 		Microsoft.VisualStudio.Community
03/03/2020 16:03:22 - 			Version : [15.0.28307.665,17.0)
03/03/2020 16:03:22 - 		Microsoft.VisualStudio.Enterprise
03/03/2020 16:03:22 - 			Version : [15.0.28307.665,17.0)
03/03/2020 16:03:22 - 		Microsoft.VisualStudio.Pro
03/03/2020 16:03:22 - 			Version : [15.0.28307.665,17.0)
03/03/2020 16:03:22 - 
03/03/2020 16:03:22 - 	References         : 
03/03/2020 16:03:22 - 	Prerequisites      : 
03/03/2020 16:03:22 - 		-------------------------------------------------------
03/03/2020 16:03:22 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
03/03/2020 16:03:22 - 		Name         : Visual Studio core editor
03/03/2020 16:03:22 - 		Version      : [15.0,17.0)
03/03/2020 16:03:22 - 
03/03/2020 16:03:22 - 		-------------------------------------------------------
03/03/2020 16:03:22 - 		Identifier   : Microsoft.VisualStudio.Workload.NetCoreTools
03/03/2020 16:03:22 - 		Name         : .NET Core cross-platform development
03/03/2020 16:03:22 - 		Version      : [15.0,17.0)
03/03/2020 16:03:22 - 
03/03/2020 16:03:22 - 		-------------------------------------------------------
03/03/2020 16:03:22 - 		Identifier   : Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1
03/03/2020 16:03:22 - 		Name         : .NET Core 2.1 development tools
03/03/2020 16:03:22 - 		Version      : [15.0,17.0)
03/03/2020 16:03:22 - 
03/03/2020 16:03:22 - Signature Details...
03/03/2020 16:03:22 - 	Extension is signed with a valid signature.
03/03/2020 16:03:22 - 
03/03/2020 16:03:22 - Searching for applicable products...
03/03/2020 16:03:22 - Found installed product - Global Location
03/03/2020 16:03:22 - Found installed product - Visual Studio Community 2017
03/03/2020 16:03:22 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by JakeRadMSFT** [comment]
What version of VS2017 do you have? Can you try updating to the latest version of 2017 or install the latest version of 2019?

Cheers,
Jake

**Comment by infoneto-shmuel** [comment]
Thx
 I already did it and it works.
Maybe you can add it to the log, so people can understand what's the problem
