### ISSUE TITLE
Cannot select a field from a field set bigger than 7

### ISSUE THREAD

**Issue by pkidd** [dotnet/machinelearning-modelbuilder#566]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/scenario
Operating System: windows 10 Enterprise, 64 bit
VS 2019 16.3.8 

Just following the scenario - adding data
Have selected a sql table 
Trying to select the Input Columns but can only 7  are accessible the drop down is not scrolling :(

![image](https://user-images.githubusercontent.com/6814097/76087472-1e912b80-5fae-11ea-9e31-eaab8648ab8d.png)

Thanks for the ability to feedback
Paul

**Comment by beccamc** [comment]
Thanks for reporting @pkidd. We fixed this issue in our latest build. Can you update to 16.0.2003.302 and see if that fixes it?  If you're already on the latest build then there is another issue going on and we'll need to dig in further.

**Comment by zewditu** [comment]
Validated
