### ISSUE TITLE
Evaluate tab enabled before training status does not say " Training complete".

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#567]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**

**Steps to Reproduce**
1. select image scenario in scenario page 
2. Choose Azure in Environment tab ==> set all azure dialog details 
3.  Go  to Data tab select you image data 
4. go to train tab  click start training button 

**Expected Experience**
if train status does not say "Training complete" disable  evaluate tab
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/5f7efdc8-dd84-41f5-9269-a95f6ffb4a32)
**Actual Experience**
## first 
![Capture.PNG](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/6d33b19c-972d-4715-97f0-ae606d422406)

## and then
 ![Capture2.PNG](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/37979933-007a-4536-bae5-8c02d86547de)
**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
I can't get a repro @zewditu 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/5ec9606c-9295-408b-be8d-bbbd6e325787)

Was this maybe you're second time training? The button was there and wasn't reset when the training restarted?

**Comment by zewditu** [comment]
@beccamc, may be because of that , me too I am not able to reproduce it. or it might be fixed after that  with latest merges, whatever,  it is gone now .
 Thanks for your effort to look into it .

**Comment by beccamc** [comment]
@zewditu I think it was maybe from before you removed the azure code from the train tab? Either way, let me know if you see it again!
