### ISSUE TITLE
Error creating ML using Microsoft learning

### ISSUE THREAD

**Issue by lebasemog** [dotnet/machinelearning-modelbuilder#568]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

[error.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4313911/error.txt)

**Comment by JakeRadMSFT** [comment]
@lebasemog, did you click the "Add Projects to Solution" button and add a project dependency to the generated *.Model project?

If you can share your code or a screenshot of your dependencies, using, and the code throwing those errors ... we can definitely help!

Cheers,
Jake

**Comment by JakeRadMSFT** [comment]
Resolving due to lack of activity. If you still hit this issue .. please re-open!

Thanks for reporting!
