### ISSUE TITLE
Inaccurate messaging for models explored from CLI and Model Builder UI

### ISSUE THREAD

**Issue by greazer** [dotnet/machinelearning-modelbuilder#57]
Currently both the CLI and Model Builder UI use the following algorithm when showing the users the explored models.

if explored >=5
=> "Top 5 models explored"
else
=> "Top 4|3|2 models explored" || "Top 1 model explored"

This messaging is technically and grammatically incorrect.

It should be:
if explored > 5
=> "Top 5 models explored"
else
=> "5|4|3|2 models explored" || "1 model explored"

If there are 5 or less models explored, then by definition they are the top. If there's only one model explored, it's both the top and bottom. It sounds silly to say "Top 1 model explored"

**Comment by beccamc** [comment]
+1 This issue came up again during Image Classification demo 9/13
