### ISSUE TITLE
Retry connection dialog should change options

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#570]
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/de65af8e-0d72-4e70-8913-8646cda36c8a)

This should change to "Retry" and "Cancel".  String should also change to - _please select "**Cancel**" and report this issue._

**Comment by beccamc** [comment]
To update the buttons to say custom actions like "Retry" and "Cancel" we'd need to build a custom control. This seemed out of scope for this fix. I just changed the text to make the Yes/No action more clear by adding a "Would you like to retry?" at the end of the message.

**Comment by zewditu** [comment]
@beccamc  just I disconnect my connection to  validate this,  but I am not sure is this right way to do it? if yes , it does not display  retry connection dialog instead model builder error  as shown in the following screenshot
 ![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/234284ca-9869-4ac1-a17b-1d0165ec220b)

**Comment by zewditu** [comment]
when the polling dialog come  it still says yes,/No
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/a8e4668b-df34-4755-92cd-49552839e193)

**Comment by zewditu** [comment]
when we  click No it display ![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/1469ed96-74c7-4155-9995-2ad023d32d44)
?
or just cancel  training ?

**Comment by beccamc** [comment]
To respond to the three questions/comments you posted... 
1. The polling is supposed to show up during training/polling. Ideally we would show a better message for disconnecting during setup but that would be a different item
2. We would have to write a custom control to have it say Retry so I fixed it in a different way. Per my other comment 
![image](https://user-images.githubusercontent.com/9122518/78413242-5ef2c200-75cb-11ea-96c6-ea747b9723b0.png)
3. This is by design. If you don't retry we throw the exception. We could improve this experience or we could also wait to see if any customers have issues...

**Comment by zewditu** [comment]
@beccamc  thanks for your explanation . I think we need create new Item to display ideal message when connection lost during setup.

**Comment by zewditu** [comment]
validated
