### ISSUE TITLE
Update all info icons

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#574]
Info icons should be sized and shaded appropriately. Right now the sizing is all over the place. It should size like this...
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/21718c2f-0c85-4233-9e0f-cb5287dcbb63)

And use the icon that's an outline: [StatusInformationOutline](http://glyphlist.azurewebsites.net/img/images/StatusInformationOutline.png)

**Comment by beccamc** [comment]
Fix in this PR - https://github.com/dotnet/machinelearning-tools/pull/611

**Comment by LittleLittleCloud** [comment]
Looks good!

![image](https://user-images.githubusercontent.com/16876986/80522899-1a481580-8942-11ea-98f7-745518923d49.png)
![image](https://user-images.githubusercontent.com/16876986/80522948-32b83000-8942-11ea-9514-5ec5614b7bd7.png)
