### ISSUE TITLE
DotNet Arcade Clean Up Issues

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#576]
Follow up tasks from this pr: 
https://github.com/dotnet/machinelearning-tools/pull/538

- [x] Validate that the vsix output has no binary Changes
- [x] fix the yaml file to call cibuild.cmd
- [x] setup automated infrastructure update PRs

- [x] Missing image
![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/5cde1c65e3106e39e8ae08f2/4e501080-c5cd-4a03-a7f1-5290d5fe237a)

- [x] Filter out VS DLLs we shouldn't be shipping. (See Comment Below)

- [ ] Build VS Insert VSIX and Gallery VSIX w/ each release build

**Comment by JakeRadMSFT** [comment]
VS DLLs we shouldn't be shipping:

envdte.dll
EnvDTE100.dll
EnvDTE80.dll
EnvDTE90.dll
EnvDTE90a.dll
Microsoft.Build.dll
Microsoft.Build.Framework.dll
Microsoft.Build.Tasks.Core.dll
Microsoft.Build.Utilities.Core.dll
Microsoft.CodeAnalysis.CSharp.dll
Microsoft.CodeAnalysis.CSharp.Workspaces.dll
Microsoft.CodeAnalysis.dll
Microsoft.CodeAnalysis.Workspaces.Desktop.dll
Microsoft.CodeAnalysis.Workspaces.dll
Microsoft.CSharp.dll
Microsoft.Data.ConnectionUI.dll
Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll
Microsoft.VisualBasic.dll
Microsoft.VisualStudio.CommandBars.dll
Microsoft.VisualStudio.ComponentModelHost.dll
Microsoft.VisualStudio.Composition.dll
Microsoft.VisualStudio.Composition.NetFxAttributes.dll
Microsoft.VisualStudio.CoreUtility.dll
Microsoft.VisualStudio.Data.Core.dll
Microsoft.VisualStudio.Data.dll
Microsoft.VisualStudio.Debugger.Engine.dll
Microsoft.VisualStudio.Debugger.Interop.10.0.dll
Microsoft.VisualStudio.Debugger.Interop.11.0.dll
Microsoft.VisualStudio.Debugger.Interop.12.0.dll
Microsoft.VisualStudio.Debugger.Interop.14.0.dll
Microsoft.VisualStudio.Debugger.Interop.15.0.dll
Microsoft.VisualStudio.Debugger.Interop.dll
Microsoft.VisualStudio.Debugger.InteropA.dll
Microsoft.VisualStudio.Designer.Interfaces.dll
Microsoft.VisualStudio.Editor.dll
Microsoft.VisualStudio.ImageCatalog.dll
Microsoft.VisualStudio.Imaging.dll
Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime.dll
Microsoft.VisualStudio.Language.dll
Microsoft.VisualStudio.Language.Intellisense.dll
Microsoft.VisualStudio.Language.NavigateTo.Interfaces.dll
Microsoft.VisualStudio.Language.StandardClassification.dll
Microsoft.VisualStudio.LanguageServer.Client.dll
Microsoft.VisualStudio.LanguageServer.Protocol.dll
Microsoft.VisualStudio.OLE.Interop.dll
Microsoft.VisualStudio.Package.LanguageService.15.0.dll
Microsoft.VisualStudio.ProjectAggregator.dll
Microsoft.VisualStudio.ProjectSystem.dll
Microsoft.VisualStudio.ProjectSystem.Interop.dll
Microsoft.VisualStudio.ProjectSystem.VS.dll
Microsoft.VisualStudio.Setup.Configuration.Interop.dll
Microsoft.VisualStudio.Shell.15.0.dll
Microsoft.VisualStudio.Shell.Design.dll
Microsoft.VisualStudio.Shell.Embeddable.dll
Microsoft.VisualStudio.Shell.Framework.dll
Microsoft.VisualStudio.Shell.Interop.10.0.dll
Microsoft.VisualStudio.Shell.Interop.11.0.dll
Microsoft.VisualStudio.Shell.Interop.12.0.dll
Microsoft.VisualStudio.Shell.Interop.14.0.DesignTime.dll
Microsoft.VisualStudio.Shell.Interop.15.0.DesignTime.dll
Microsoft.VisualStudio.Shell.Interop.15.1.DesignTime.dll
Microsoft.VisualStudio.Shell.Interop.15.3.DesignTime.dll
Microsoft.VisualStudio.Shell.Interop.15.5.DesignTime.dll
Microsoft.VisualStudio.Shell.Interop.15.6.DesignTime.dll
Microsoft.VisualStudio.Shell.Interop.15.7.DesignTime.dll
Microsoft.VisualStudio.Shell.Interop.15.8.DesignTime.dll
Microsoft.VisualStudio.Shell.Interop.8.0.dll
Microsoft.VisualStudio.Shell.Interop.9.0.dll
Microsoft.VisualStudio.Shell.Interop.dll
Microsoft.VisualStudio.TaskRunnerExplorer.14.0.dll
Microsoft.VisualStudio.Telemetry.dll
Microsoft.VisualStudio.TemplateWizardInterface.dll
Microsoft.VisualStudio.Text.Data.dll
Microsoft.VisualStudio.Text.Logic.dll
Microsoft.VisualStudio.Text.UI.dll
Microsoft.VisualStudio.Text.UI.Wpf.dll
Microsoft.VisualStudio.TextManager.Interop.12.1.DesignTime.dll
Microsoft.VisualStudio.TextManager.Interop.8.0.dll
Microsoft.VisualStudio.TextManager.Interop.dll
Microsoft.VisualStudio.TextTemplating.15.0.dll
Microsoft.VisualStudio.TextTemplating.Interfaces.10.0.dll
Microsoft.VisualStudio.TextTemplating.Interfaces.11.0.dll
Microsoft.VisualStudio.TextTemplating.Interfaces.15.0.dll
Microsoft.VisualStudio.TextTemplating.VSHost.15.0.dll
Microsoft.VisualStudio.Threading.dll
Microsoft.VisualStudio.Utilities.dll
Microsoft.VisualStudio.Validation.dll
Microsoft.VisualStudio.Web.BrowserLink.12.0.dll
Microsoft.VisualStudio.Workspace.VSIntegration.Contracts.dll
Microsoft.Win32.Primitives.dll
mscorlib.dll
netstandard.dll
Newtonsoft.Json.dll
PresentationCore.dll
PresentationFramework.dll
stdole.dll
StreamJsonRpc.dll
System.AppContext.dll
System.Collections.Concurrent.dll
System.Collections.dll
System.Collections.Immutable.dll
System.Collections.NonGeneric.dll
System.Collections.Specialized.dll
System.ComponentModel.Annotations.dll
System.ComponentModel.Composition.dll
System.ComponentModel.dll
System.ComponentModel.EventBasedAsync.dll
System.ComponentModel.Primitives.dll
System.ComponentModel.TypeConverter.dll
System.Composition.AttributedModel.dll
System.Composition.Convention.dll
System.Composition.Hosting.dll
System.Composition.Runtime.dll
System.Composition.TypedParts.dll
System.Console.dll
System.Core.dll
System.Data.Common.dll
System.Data.DataSetExtensions.dll
System.Data.dll
System.Design.dll
System.Diagnostics.Contracts.dll
System.Diagnostics.Debug.dll
System.Diagnostics.FileVersionInfo.dll
System.Diagnostics.Process.dll
System.Diagnostics.StackTrace.dll
System.Diagnostics.TextWriterTraceListener.dll
System.Diagnostics.Tools.dll
System.Diagnostics.TraceSource.dll
System.dll
System.Drawing.dll
System.Drawing.Primitives.dll
System.Dynamic.Runtime.dll
System.Globalization.Calendars.dll
System.Globalization.dll
System.Globalization.Extensions.dll
System.IO.Compression.dll
System.IO.Compression.FileSystem.dll
System.IO.Compression.ZipFile.dll
System.IO.dll
System.IO.FileSystem.dll
System.IO.FileSystem.DriveInfo.dll
System.IO.FileSystem.Primitives.dll
System.IO.FileSystem.Watcher.dll
System.IO.IsolatedStorage.dll
System.IO.MemoryMappedFiles.dll
System.IO.Pipes.dll
System.IO.UnmanagedMemoryStream.dll
System.Linq.dll
System.Linq.Expressions.dll
System.Linq.Parallel.dll
System.Linq.Queryable.dll
System.Management.dll
System.Net.Http.dll
System.Net.Http.Rtc.dll
System.Net.NameResolution.dll
System.Net.NetworkInformation.dll
System.Net.Ping.dll
System.Net.Primitives.dll
System.Net.Requests.dll
System.Net.Security.dll
System.Net.Sockets.dll
System.Net.WebHeaderCollection.dll
System.Net.WebSockets.Client.dll
System.Net.WebSockets.dll
System.Numerics.dll
System.ObjectModel.dll
System.Reflection.dll
System.Reflection.Emit.dll
System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.Lightweight.dll
System.Reflection.Extensions.dll
System.Reflection.Metadata.dll
System.Reflection.Primitives.dll
System.Resources.Reader.dll
System.Resources.ResourceManager.dll
System.Resources.Writer.dll
System.Runtime.CompilerServices.VisualC.dll
System.Runtime.dll
System.Runtime.Extensions.dll
System.Runtime.Handles.dll
System.Runtime.InteropServices.dll
System.Runtime.InteropServices.RuntimeInformation.dll
System.Runtime.InteropServices.WindowsRuntime.dll
System.Runtime.Numerics.dll
System.Runtime.Serialization.dll
System.Runtime.Serialization.Formatters.dll
System.Runtime.Serialization.Json.dll
System.Runtime.Serialization.Primitives.dll
System.Runtime.Serialization.Xml.dll
System.Security.Claims.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Csp.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.X509Certificates.dll
System.Security.Principal.dll
System.Security.SecureString.dll
System.ServiceModel.Duplex.dll
System.ServiceModel.Http.dll
System.ServiceModel.NetTcp.dll
System.ServiceModel.Primitives.dll
System.ServiceModel.Security.dll
System.Text.Encoding.dll
System.Text.Encoding.Extensions.dll
System.Text.RegularExpressions.dll
System.Threading.dll
System.Threading.Overlapped.dll
System.Threading.Tasks.Dataflow.dll
System.Threading.Tasks.dll
System.Threading.Tasks.Parallel.dll
System.Threading.Thread.dll
System.Threading.ThreadPool.dll
System.Threading.Timer.dll
System.ValueTuple.dll
System.Windows.Controls.Ribbon.dll
System.Windows.Forms.dll
System.Xaml.dll
System.Xml.dll
System.Xml.Linq.dll
System.Xml.ReaderWriter.dll
System.Xml.XDocument.dll
System.Xml.XmlDocument.dll
System.Xml.XmlSerializer.dll
System.Xml.XPath.dll
System.Xml.XPath.XDocument.dll
UIAutomationClient.dll
UIAutomationClientsideProviders.dll
UIAutomationProvider.dll
UIAutomationTypes.dll
VSLangProj.dll
VSLangProj100.dll
VSLangProj110.dll
VSLangProj140.dll
VSLangProj150.dll
VSLangProj157.dll
VSLangProj158.dll
VSLangProj2.dll
VSLangProj80.dll
VSLangProj90.dll
WindowsBase.dll

**Comment by LittleLittleCloud** [comment]
The `AZCopyService.Tests` and `AutoMLService.Tests` uses different sdk to build project, and they target to different platform as well(AzcopyService.Tests to net472 and AutoMLService.Tests for netcore3.0). Is there a reason to do that?

**Comment by jmarolf** [comment]
@LittleLittleCloud looks like these should both target `netcoreapp2.0`

**Comment by JakeRadMSFT** [comment]
or both target Net472 ... the services actually run as Net472 when used by Model Builder.

**Comment by jmarolf** [comment]
> uses different sdk to build project

Both of those projects needed Winforms references so I had them target the `Microsoft.NET.Sdk.WindowsDeskto` sdk which includes these assemblies automatically.
