### ISSUE TITLE
Missing SDK Version

### ISSUE THREAD

**Issue by jlmoya** [dotnet/machinelearning-modelbuilder#578]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.2 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=opensuse-leap.15.1-x64

**Comment by JakeRadMSFT** [comment]
Hello,
It should be available here: https://dotnet.microsoft.com/download/dotnet-core/2.1. Please report back if this doesn't resolve the issue.

Cheers,
Jake

**Comment by JakeRadMSFT** [comment]
Resolving due to lack of activity. If you still hit this issue .. please re-open!

Thanks for reporting!
