### ISSUE TITLE
Csv file not correctly parsed

### ISSUE THREAD

**Issue by Azkarell** [dotnet/machinelearning-modelbuilder#579]
**Model Builder Version**: 16.0.20003.302
**Visual Studion Version**: 2019

**Bug description**
csv files with escaped string that includes and semicolon fails to be parsed

**Steps to Reproduce**
1. create a csv file with following input 
Type;Example
c#;"hi i am not working;
"" i dont see why """
(produced by microsoft excel)
2. use it as an input inside file selection

**Expected Experience**
Parser should ignore semicolons inside an escaped csv string and parse the file correct

**Actual Experience**
Error message pops up with following message:
Unrecognized data format. Please check the input file to make sure it is a valid comma or tab separated file.
   bei Microsoft.ML.ModelBuilder.DataSources.FileDataSource.GetCorrectDelimiter(String selectedFileName)

stacktrace is abbreviated.

export this file as csv within excel and it wont work.

[failexample.xlsx](https://github.com/dotnet/machinelearning-modelbuilder/files/4331677/failexample.xlsx)

**Comment by rati-dzidziguri** [comment]
![image](https://user-images.githubusercontent.com/52178984/76712285-ac98af00-6730-11ea-80e9-83ea5cf23bc0.png)

**Comment by boblooney2** [comment]
Similar issue, different test case.  If your CSV contains a string field that is correctly escaped and contains a comma, it will error.  If you remove the comma, it is fine.

0,"Hello, this is a test"  <-- error
0,"Hello this is a test"  <-- works

**Comment by beccamc** [comment]
@boblooney2, @rati-dzidziguri and @Azkarell Thank you all for providing information and examples! 

It looks like there are 4 issues here that should work...
1. Comma inside quotes
2. Semi-colon inside quotes
3. Two quotes inside quotes 😊  

We've just started using a new data parsing library that supports comma, semi-colons, and quotes (provided they're two double quotes e.g. John ""Jim"" Johnson) . This fix will be shipped in our next release. You can access it now by moving to our in VS experience, available in VS 16.6 Preview 2.

![image](https://user-images.githubusercontent.com/9122518/79621633-f3c7e600-80c8-11ea-9a1a-041e7f02cb63.png)

4. Newline inside quotes

There is a bug in ML.NET around newline characters that we're working with partner teams to fix. This experience is currently **blocked**. 

Thanks for reporting!

**Comment by beccamc** [comment]
We're tracking the newline issue in #356. Please follow the problem there

**Comment by beccamc** [comment]
@boblooney2, @rati-dzidziguri and @Azkarell If anyone has a problem dataset they would be willing to share, please post it here. I'm compiling a list of test datasets to ensure our loader works for a variety of data. Thanks!

**Comment by beccamc** [comment]
Closing this issue. Please track the fix in #356
