### ISSUE TITLE
Spinner doesn't show immediately on file selection

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#583]
On file open, it takes a few seconds before the spinner show up. We should start showing the spinner immediately. 

![longPause2.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/511199ff-6e7f-4887-923b-5fb691854004)

**Comment by JakeRadMSFT** [comment]
Please investigate

**Comment by beccamc** [comment]
Something blocking the UI thread? Could be investigated with large datasets.

**Comment by beccamc** [comment]
This needs to be fixed for the October release. Now that we're predicting the column types on the data page it can take a long time. We need to show a spinner.

**Comment by LittleLittleCloud** [comment]
LGTM
