### ISSUE TITLE
Model consumption error - file not found

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#585]
I created a .NET Core console app, did text classification for sentiment analysis (yelp-labelled.txt dataset), and everything worked fine until I tried to copy + paste next steps code and run the app with model consumption:

![image](https://user-images.githubusercontent.com/10437687/76890843-4fdae880-6845-11ea-8136-601026a95bc9.png)

**Comment by beccamc** [comment]
+1 also saw this in a .Net Core console app.

**Comment by LittleLittleCloud** [comment]
Did you add reference to .Model project before running?

**Comment by LittleLittleCloud** [comment]
This bug only appears on test VS Build, and will disappear if using release VS Version to open generated project and run.

Perhaps it's something wrong with test VS Build?

**Comment by LittleLittleCloud** [comment]
test on  vs master branch and not appear

**Comment by beccamc** [comment]
Fixed on latest build.
