### ISSUE TITLE
zsh command not found

### ISSUE THREAD

**Issue by mailtruck** [dotnet/machinelearning-modelbuilder#588]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I get command not found when i try to execute `mlnet` from the command line.

I use zsh. I see the instruction about needing to give executable permission, but I'm not sure how to do that.

If I go into bash it looks like it's running from a location somehow, but if I do which to try to add that to my path in zsh profile I get nothing.

**Comment by LittleLittleCloud** [comment]
did you add dotnet-tool path to the Path environment?
```
export PATH="$PATH:~/.dotnet/tools"
```

**Comment by LittleLittleCloud** [comment]
Going to close this issue since no one responses for over 7 days, feel free to re-open it though
