### ISSUE TITLE
Not working when the project name has spaces

### ISSUE THREAD

**Issue by yatiac** [dotnet/machinelearning-modelbuilder#59]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1905.641
 - Visual Studio Version: 2019 16.0.2

**Describe the bug**
I tried to use the Model Builder but created a project with the name of:
"ML Auto ML Sample" and tried to make it work but it never did, I then changed the name of the project to "myMLApp" and started working as a charm

**To Reproduce**
1. Create new .Net Core Console App with the name "ML Auto ML Sample"
2. Right click on the project > Add > Machine Learning
3. Select Sales prediction
4. Fill the required fields (File, Label, etc)
5. Click Next (Train)
6. Put any number of second (e.g. 180) and click Start Training
7. Nothing happens

**Expected behavior**
ML Builder start training on the given dataset

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! We have a change ready for the next release.
