### ISSUE TITLE
About the relationship between gesture recognition and picture classification

### ISSUE THREAD

**Issue by GreenShadeZhang** [dotnet/machinelearning-modelbuilder#591]
I want to do a gesture recognition function, but this model creation does not support object detection, so I am not sure if i need to do hand object detection before training picture classification when doing gesture recognition. Or do I directly take pictures of many different groups of gestures without any processing, such as not doing hand labels, and then the number of pictures is enough, finish the picture classification can complete the function of gesture recognition?

**Comment by LittleLittleCloud** [comment]
We are working on object detection and you should be able to see it in the next month or two. 
if you just want to do gesture recognition ( like finding out whether your hand gesture is 6 or 1) and don't need the location information, you may just need to get enough training data ( and make sure in the training pictures, the target object is obviously enough) and training using image classification. 

@briacht Could you provide more information as you just finishing your American sign language demo

**Comment by GreenShadeZhang** [comment]
Thank you for your reply I'll try image classification first, look forward to your new features.

**Comment by LittleLittleCloud** [comment]
Close this for clean up board, feel free to re-open it should you have any questions
