### ISSUE TITLE
Unauthorized azure training bug

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#594]
![image](https://user-images.githubusercontent.com/10437687/77120465-27deb700-69f6-11ea-8d40-b4a97955f124.png)

-hit unauthorized, why didn't refresh token or try getting new token?

**Comment by beccamc** [comment]
@briacht  I know we talked about this yesterday, but did this pop up after you hit "yes" on the retry dialog? Or was the retry dialog never shown?

**Comment by beccamc** [comment]
This is very difficult to verify because it is the absence of a flakey error message. I'm going to close this. @briacht please let me know if you see this again!
