### ISSUE TITLE
Azure Telemetry fixes

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#595]
- [x] Fix image bugs
 ![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/71e97f6c-fd7b-4132-b113-43d973c8d3ec)

- [x] Open create experiment (main) dialog click
- [x] Edit experiment click
- [x] Cancel click (all dialogs)
- [x]  Time it takes to create workspace/compute
- [x] Created new workspace/compute included in create experiment event
- [x]  Learn more hyperlinks clicked in workspace and compute dialogs

- [x] (not telemetry) Change Ok -> OK on create resource group

**Comment by zewditu** [comment]
@beccamc , I use Vs telemetry monitor to validate this fix and I walked  Image classification-> Azure environment  -> create  new experiment -> edit experiment  > select image folder but i could not see any of the above events. is there any other way to validate it ?

![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/9f2f9d6a-302c-4778-9fd0-6b5cd0871c07)

**Comment by beccamc** [comment]
The logging of open create experiment was happening after closing the dialog. I've fixed that in this PR. I went through and doubled checked everything else was fixed. See screenshots below. 

Fix image bugs... 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/4604fbfd-543f-4a21-b90e-88e0afbaa123)

Open Create experiment 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/cf11ddcf-325e-44ea-aee9-a4d4b4e31607)

Edit experiment click...
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/abb5d1f9-b0fa-45be-8898-1262f27dab6a)

Cancel all dialogs click...
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/042083a0-6466-4a8c-b638-5a8ab3bfbb1c)
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/5c6b2933-2beb-43b8-b8b7-fc40ee391a96)
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/893d0f2f-6802-4e59-b268-7e5fed846690)

Time to create compute...
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c505b5e0-418c-41c2-b4e7-735244f9642d)

Create new workspace/compute included in create experiment event....
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/7bb34881-70fa-46c2-9907-045947641c74) 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/ba49e9a9-8b1d-48f6-a9f5-cb9e433c5ecb)

Hyperlinks..
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/7ef37566-cd40-4609-bf47-1ce32c6a5cd5)
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/e99c294d-ae47-41f5-a475-43783f44a2a3)

OK...
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c3d6b773-1174-4646-a528-f82cd089becb)

**Comment by zewditu** [comment]
validated

**Comment by beccamc** [comment]
I'm closing this because I provided screenshots of all the fixes above.
