### ISSUE TITLE
remove AutoMLServceLogger debug info

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#598]
Step to validate:
check the output pannel and make sure we don't have output start with "AutoMLServiceLogger"

**Comment by beccamc** [comment]
@LittleLittleCloud Can you add more information or a link to the PR here? I'm not sure what I need to validate :)

**Comment by beccamc** [comment]
Confirmed we have no output with AutoMLServiceLogger.
