### ISSUE TITLE
No error shown for bad predict input

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#599]
In evaluate (text) the try it out experience isn't showing an error when a field is empty 

![noErrorShown.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/84bba919-fe27-46e5-8fbe-9f8fa95ee0f6)

**Comment by LittleLittleCloud** [comment]
It's not necessarily to be an error to have an empty field in data. (And why you have three labels in titanic dataset...)

**Comment by JakeRadMSFT** [comment]
We should allow them to predict with missing fields ... but we should come up with a strategy for what to replace them with. This might be related to advanced features and what we do with missing values there.

**Comment by JakeRadMSFT** [comment]
Moving to validate ... do we allow them to do predictions with missing values and not error?

**Comment by LittleLittleCloud** [comment]
We do, should we close it or move it to ready to ship?

**Comment by beccamc** [comment]
Closing this as it wasn't customer supported.
