### ISSUE TITLE
Option to specify a test dataset

### ISSUE THREAD

**Issue by yatiac** [dotnet/machinelearning-modelbuilder#60]
**Describe the solution you'd like**
I would like to have an option to specify a test dataset to evaluate the model against

**Comment by beccamc** [comment]
Note: There has also been a request for training, validation AND holdout datasets.

**Comment by luisquintanilla** [comment]
Let's look into whether we have designs for this. Potential places:

- Optional dropdown in data source selection
- Advanced Data Options

**Comment by beccamc** [comment]
I found the PM [spec ](https://microsoft.sharepoint.com/:w:/r/teams/ML.NETModelBuilder/_layouts/15/Doc.aspx?sourcedoc=%7BC6FA529F-47DB-4D85-88A5-ED81575DC95C%7D&file=MB%20Spec%20-%20Advanced%20Options.docx&action=default&mobileredirect=true&share=IQGfUvrG20eFTYil7YFXXclcAQrT-C5s6i3UeOd_5VmVSbY)

**Comment by luisquintanilla** [comment]
@zewditu to look into it this month.

**Comment by luisquintanilla** [comment]
Waiting on #2191 before finishin implementation of this feature.

**Comment by luisquintanilla** [comment]
Closing this issue since #2191 has addressed this request. As we hear more feedback about the Try It Out experience we can evaluate the option to provide a test dataset there.
