### ISSUE TITLE
.NET Core 3.1 is not supported by ML.NET cli.

### ISSUE THREAD

**Issue by biztudio** [dotnet/machinelearning-modelbuilder#602]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: macos

.NET Core 3.1 is not supported by ML.NET cli. I run the cmd from the MS tutorial but get error.
shenyang@myMacBook-Pro myMLApp001 % mlnet auto-train --task binary-classification --dataset "wikipedia-detox-250-line-data.tsv" --label-column-name "Sentiment" --max-exploration-time 10
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.1 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.10.15-x64

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! @LittleLittleCloud can you check that the upcoming release works with just 3.1.1 on the machine?

**Comment by JakeRadMSFT** [comment]
@biztudio you can download the needed run time from here:

https://dotnet.microsoft.com/download/dotnet-core/2.1

**Comment by LittleLittleCloud** [comment]
Dup of #256
