### ISSUE TITLE
[Blocked] Forecasting (Local + Azure)

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#609]
Add Forcecasting scenario to Model Builder.

**Comment by beccamc** [comment]
#423 and #660 both requesting this feature. 

Customer comment (@SH2015) - 
Any plan to include time-series forecasts in Model Builder? there are too many applications in business for time-series analysis

@briacht For visibility

**Comment by beccamc** [comment]
Vote for forecasting in our marketplace page. 
![image](https://user-images.githubusercontent.com/9122518/85052536-b5998200-b15e-11ea-8f43-e42ba7d9a223.png)
