### ISSUE TITLE
tool tip does not word wrap and goes off the screen

### ISSUE THREAD

**Issue by salmanmkc** [dotnet/machinelearning-modelbuilder#61]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1905.641
 - Visual Studio Version: 2019 16.1.1

**Describe the bug**
tool tip on 3. Train section, Machine learning task does not word wrap, it goes off the screen on 1800x1200 150% scaling, on 100% it fits but does not word wrap.

**To Reproduce**
1. Set display resolution to 1800x1200 and scaling to 150%, or something similar, such as a low resolution
2. Click on the Train tab in the ML.net model builder
3. Locate Machine learning task under input
4. Hover over the question mark to bring up the tool tip, it does not fit fully

**Expected behavior**
The tool tip goes off the screen

**Screenshots**
![image](https://user-images.githubusercontent.com/32169182/58446063-29519280-80f7-11e9-8d49-c87fb0474598.png)

**Comment by rustd** [comment]
Try to shorten the message

**Comment by LittleLittleCloud** [comment]
what about just remove e.g? it seems a bit surplus to me

**Comment by rustd** [comment]
We could use this as the tool-tip message 
"Use binary classification to classify data into 2 categories, multi-class classification to classify data into 3+ categories or regression to predict a numerical value."
