### ISSUE TITLE
Update Train, Evaluate, and Next Steps

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#613]

**Comment by zewditu** [comment]
https://www.figma.com/file/jZ6RROEeT5GxcS6Q5zHugU/Updated-Test%2C-Evaluate%2C-%26-Next-Step-Pages---Kaitlin?node-id=60%3A3666

**Comment by kawilkin** [comment]
[Next Step Illustrations](https://app.zenhub.com/files/186917455/b1bb42c4-aeda-46bc-b10d-3ab82cfd3bd9/download)
