### ISSUE TITLE
Getting Error while adding Machine learning reference in solution

### ISSUE THREAD

**Issue by devopriyo85** [dotnet/machinelearning-modelbuilder#619]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows 8

While adding Machine leaning Item to the solution.I am getting below error 

exception has been thrown by the target of an invocation.

**Comment by zewditu** [comment]
@devopriyo85  thanks for reporting . What version Visual Studio you used?

**Comment by beccamc** [comment]
@devopriyo85 Friendly ping.  Can you share your version of visual studio? Thanks!

**Comment by beccamc** [comment]
I don't currently have enough information to investigate this issue. If you're still seeing a problem, please reopen this issue and provide your VS version number. Thank you!
