### ISSUE TITLE
The suggested code to consume the model does not reference the datamodel

### ISSUE THREAD

**Issue by salmanmkc** [dotnet/machinelearning-modelbuilder#62]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1905.641
 - Visual Studio Version: 2019 16.1.1

**Describe the bug**
After running through the ML.net Model builder, the final step, consume, the code that is suggested does not tell the user to import their data model. This may be to make it more general and can be seen as an error which can be fixed by the user, however it would be more user friendly to have it in the code straight away.

**To Reproduce**
1. Go to the final stage of the ML.net Model Builder
2. Scroll down to 'Consume'
3. Find the consume code and at the top it doesn't have the using statement for the data model which is needed for the code to work.

**Expected behavior**
When using the code in the application it will have a compile error since the data model needs to be imported. I know this may be self explanatory, however not all users may get it, and would be easier for those who don't know. Also, I think the reference is already made based of a previous issue that was resolved, but the NuGet package has to be manually installed, not sure how possible it is to have it be done automatically within the model builder, or maybe at least tell the user that they need to do it within the instructions. I know it's in the documentation but in the builder it would be useful as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/32169182/58446646-5e5ee480-80f9-11e9-83a6-63c6106063fd.png)

**Additional context**
Just to make it more user friendly for new starters

**Comment by rustd** [comment]
#76

**Comment by LittleLittleCloud** [comment]
We remove the `DataModel` namespace now, so this bug shouldn't exist anymore

**Comment by salmanmkc** [comment]
Awesome
