### ISSUE TITLE
Not all links are operational 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#620]
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/592a238b-5fe1-486b-bdaf-6fc2f5c11d60)
These don't work.. 

https://aka.ms/mlnet-cli-docs
https://aka.ms/mlnet-cli-telemetry

**Comment by briacht** [comment]
I've updated the aka links so they should work now

**Comment by zewditu** [comment]
validated
