### ISSUE TITLE
Miss warning msg when there's contradiction in inferring header

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#621]
mlnet-cli should show warning message if --has-header flag is contradicted with auto-detected result.

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud can you add more details?

**Comment by beccamc** [comment]
@LittleLittleCloud I'm assuming this is a dataset with a weird header. Can you share the dataset?

**Comment by LittleLittleCloud** [comment]
> @LittleLittleCloud I'm assuming this is a dataset with a weird header. Can you share the dataset?

It's not a dataset problem, going to move it from `Dataset Failure` epic

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud, @briacht Can we update this message to be more clear? This is the error message we currently get when has-header was set to "false" but we detect a header:

"Detect result for input file is True while your input is False. Please double check to confirm."

**Comment by briacht** [comment]
Does the user have to input something here if it's just a warning message? Or what are the actions there are supposed to take?

"A header has been detected in your dataset, but you have specified --has-header false. Are you sure that your dataset does not have a header? (Input y/n)."

**Comment by LittleLittleCloud** [comment]
No it's just a warning msg and they can't do any thing. So maybe just
`A header has been detected in your dataset, but you have specified --has-header false.` when has header
and 
`There's no header been detected in your dataset, but you have specified --has-header true.`?

**Comment by briacht** [comment]
Does this look like too much text in the CLI:

Warning: A header has been detected in your dataset, but you have specified --has-header false. If results are not as expected, please check --has-header option and try training again.

Warning: No header has been detected in your dataset, but you have specified --has-header true. If results are not as expected, please check --has-header option and try training again.

**Comment by LittleLittleCloud** [comment]
It's OK, text message is never too much in cli program
