### ISSUE TITLE
Auto-detect headers

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#623]
**System Information (please complete the following information):**
 - Model Builder Version: CLI 16.1.0

Training on a file without header because has-header flag default is true takes the first row as the column names. It would be good to have it default to false and autodetect/generate headers unless users explicitly say it had header.

Dataset:
```text
Wow... Loved this place.	1
Crust is not good.	0
Not tasty and the texture was just nasty.	0
```

Command:

```bash
mlnet classification --name classification --dataset yelp_labelled.txt --label-col 1
```

ModelInput:
```csharp
// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Classification.Model
{
    public class ModelInput
    {
        [ColumnName("Wow... Loved this place."), LoadColumn(0)]
        public string Wow____Loved_this_place_ { get; set; }


        [ColumnName("1"), LoadColumn(1)]
        public string _1 { get; set; }


    }
}
```

**Comment by JakeRadMSFT** [comment]
@justinormont @beccamc do we have anything that is good at guessing if there is a header?

**Comment by LittleLittleCloud** [comment]
Add a third option for `has-header` flag should be able to solve this
