### ISSUE TITLE
Some ideas in making ModelBuilder more reliable in machine learning

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#626]
ModelBuilder only picks the best model and dispose of the left ones right now. But there's chances that model performs best in train dataset doesn't necessarily perform well in the dataset that it doesn't see (Known as generalization ability). Using CV allows us to pick the model that has the best generalization ability on training dataset, but that's not always the case when it comes to unseen datasets. There's still the possibility that models with a lower rank can perform better. So it's a bit arbitrary to just keep the winner for the next step in model builder. 

A way to solve this situation is we can keep the best model of each trainer ( trainers, not models, along with the parameters for those models, which can be got from pipeline.) to try-it-out page and allow users to pass validate dataset to test those models. Let user to pick the winner. AutoML.Net doesn't need to be changed a lot as it keeps experiment during training. And this feature should be able to achieved by only changing ModelBuilder.

**Comment by JakeRadMSFT** [comment]
Closing - this seems outdated :)
