### ISSUE TITLE
Add .Net Framework version of generated code

### ISSUE THREAD

**Issue by bmanners** [dotnet/machinelearning-modelbuilder#63]
**Is your feature request related to a problem? Please describe.**
I want to test out the model builder on a system that targets .Net Framework but the generated code targets .Net Core.

**Describe the solution you'd like**
At the step where the code is generated it would be good to have a drop down to select the version of .Net to target.

**Describe alternatives you've considered**
as an alternative i guess i can copy paste the code into new projects and setup the references again...

**Comment by rustd** [comment]
#76 as a reference

**Comment by beccamc** [comment]
Validated this is working.
