### ISSUE TITLE
Azure AutoML Object Detection

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#630]
training Object Detection using Jasmie service, downloading artifact and wrapping it as ML.Net model

repo for Jasmie: 
https://msdata.visualstudio.com/Vienna/_git/vienna?path=%2Fsrc%2Fazureml-api%2Fsrc%2FJasmine

**Comment by beccamc** [comment]
PR isn't in for this. IMO we should just close this item because 1. We're not shipping it and 2. This will be verified in an Object detection bug bash. 

We could reopen but I think this was more for Tevin's tracking.
