### ISSUE TITLE
Model Builder Error.

### ISSUE THREAD

**Issue by ZionLloyd05** [dotnet/machinelearning-modelbuilder#632]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

Error Encountered : 
Model Builder Error.
![error](https://user-images.githubusercontent.com/40478221/77684128-c7252080-6f99-11ea-8b49-ec9e3200a830.jpg)

Stack Trace:
 at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext()

**Comment by JakeRadMSFT** [comment]
Hello,
Sorry you're hitting this error.

- How big is your dataset?
- How long did you train for?
- What scenario type did you choose?

**Comment by ZionLloyd05** [comment]
Hey, thanks for choosing to help out.

I was trying to follow the sentiment analyzer tutorial on the ml.net docs online, that was where I hit the error. But I think I had a way through it recently, I simply tried the whole thing again, new project i mean, and it worked.
Although if such repeats itself again, I might not be able to solve it, that's the fear

**Comment by beccamc** [comment]
@ZionLloyd05 Thanks for reporting! It sounds like you fixed the problem. If this repeats itself, please let us know by commenting here or opening a new issue. Thanks!
