### ISSUE TITLE
CodeGen update for Object Detection

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#633]
Should be able to share one CodeGen project for both ML.Net and Azure AutoML Object Detection

How to show object frame in console app

**Comment by beccamc** [comment]
PR isn't in for this. IMO we should just close this item because 1. We're not shipping it and 2. This will be verified in an Object detection bug bash. 

We could reopen but I think this was more for Tevin's tracking.
