### ISSUE TITLE
Byte array input for Image classification prediction

### ISSUE THREAD

**Issue by GreenShadeZhang** [dotnet/machinelearning-modelbuilder#635]
When I used the tool for image classification training and then generated the console program, I had a question about the model input parameters in the sample code as follows
```
 // Create single instance of sample data from first line of dataset for model input
  ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);
  // Make a single prediction on the sample data and print results
  var predictionResult = ConsumeModel.Predict(sampleData);

```
 ModelInput is as follows
```
[ColumnName("Label"), LoadColumn(0)]
 public string Label { get; set; }
[ColumnName("ImageSource"), LoadColumn(1)]
public string ImageSource { get; set; }
```

My question is if I want to read the image directly from the camera and convert it to byte for classification, but the parameters in the example seem to be just the path of the image, this tool is only training to support the path or do I need to do something to make the parameters do not use the path of the image but to adopt an array of bytes.

I hope you all answer my doubts

**Comment by beccamc** [comment]
Thanks for the feedback @GreenShadeZhang.  We don't support this currently but it is a good suggestion. We will look at the possibility of this change.

**Comment by GreenShadeZhang** [comment]
Okay, look forward to your new features, so that developers can also combine cameras to develop some creative apps.

**Comment by rapidengineering** [comment]
Are there any updates on this possible enhancement. I am working with the Azure Kinect kit in combination with C#. I am able to classify images succesfully each frame, but in order to do that I need to save the image to disk first. In my situation it would also be helpful if I could input an array of Bytes.

**Comment by ChengYen-Tang** [comment]
I also need this feature.

**Comment by sandervandevelde** [comment]
I need this in-memory option too (Just one year later :-) ). 

It would be nice if it is possible to pass an image as a byte array (png) of an eg. C# bitmap or image to my Image Classification Model? Why? I get the image from this industry-grade camera as a byte array so storing it on disk first is not efficient (speed and stability and waste of effort on filesystem transactions). Passing the image on in memory is the way to go for industrial usage...

**Comment by JakeRadMSFT** [comment]
I'll be sharing code in #851 and resolving this issue (please come continue the conversation there)

**Comment by JakeRadMSFT** [comment]
Please see - https://github.com/dotnet/machinelearning-modelbuilder/issues/851#issuecomment-833967834
