### ISSUE TITLE
Unable to run the commend provided

### ISSUE THREAD

**Issue by Tamilmaniaraja** [dotnet/machinelearning-modelbuilder#639]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/evaluate
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I'm getting the following error.

"**It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.3 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.10.15-x64**"

When I go to the link to download 2.1.0, the link is re-directed to 3.1 which I already have. This instruction needs to update or fixes the issue from mlnet.

**Comment by beccamc** [comment]
Sorry you ran into this issue and thanks for reporting @Tamilmaniaraja! We've fixed this problem and it'll be available in our next release of the ML.NET CLI. 

Until then, you can get unblocked by installing 2.1.0 from here - https://dotnet.microsoft.com/download/dotnet-core/2.1.  Sorry this link wasn't more accessible!
