### ISSUE TITLE
Be able to visualise the data set with the prediction line

### ISSUE THREAD

**Issue by salmanmkc** [dotnet/machinelearning-modelbuilder#64]
**Is your feature request related to a problem? Please describe.**
Well, in order to see a prediction, I have to supply all the inputs and then run the whole program and then wait for the output. If I want to see what another input would give, I would have to change those values and  then run the whole program again. I would keep doing this over and over again, whilst plotting the data in an Excel spreadsheet.

**Describe the solution you'd like**
I would like to be able to see a plotted line of what the model would predict, just to see how it fits. This image could be used for giving a general idea to the developer or could be showcased in the actual applicaition. For example, the image below from https://statisticsbyjim.com/regression/predictions-regression/ 
![image](https://user-images.githubusercontent.com/32169182/58505429-d2929a00-8184-11e9-990c-c8bb5f78d1d2.png)

**Describe alternatives you've considered**
As mentioned in the problem, I have tried to record all the data, bit by bit and then see any trends, etc. but it would be nice to have a visual representation generated.

**Additional context**
Some images I found on bing that demonstrate what would be useful, the first one below has a lot of useful information.
![image](https://user-images.githubusercontent.com/32169182/58505495-fce45780-8184-11e9-913c-c66e5066029c.png)

![image](https://user-images.githubusercontent.com/32169182/58505590-3321d700-8185-11e9-9a9b-d95e4abd8bce.png)

**Comment by beccamc** [comment]
@JakeRadMSFT Is this included in Notebook work? Is there an issue we can link this to?

**Comment by salmanmkc** [comment]
wow I remember when I wanted this like 3 years ago, nice pleasant surprise to see it again :)

**Comment by beccamc** [comment]
You can accomplish something similar to this with Notebooks! We have example notebooks on [Github](https://github.com/dotnet/csharp-notebooks#machine-learning), including a Notebook on basic visualizations. 

From [latest Model Builder](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022) you can generate a starting Notebook file that includes code to retrain your pipeline and make predications. Just install the [VS Notebook Editor extension](https://marketplace.visualstudio.com/items?itemName=MLNET.notebook) and you can get going.

**Comment by beccamc** [comment]
Let me know your thoughts on the Notebooks! We're actively working on our docs and Notebooks so feedback is appreciated! Thansk!
