### ISSUE TITLE
mlnet not compatible with dotnet core 3.1

### ISSUE THREAD

**Issue by Abh1sh3kSaxena** [dotnet/machinelearning-modelbuilder#640]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: Ubuntu 18.04.3

Initially path variable did not udpate after installation of mlnet after running mlnet using absolute path got below error. Please confirm if mlnet is not supported in later versions of dotnetcore 
_

> ~/.dotnet/tools/mlnet
> It was not possible to find any compatible framework version
> The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
>   - The following frameworks were found:
>       3.1.3 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> 
> You can resolve the problem by installing the specified framework and/or SDK.
> 
> The specified framework can be found at:
>   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=ubuntu.18.04-x64

_

**Comment by LittleLittleCloud** [comment]
Right now mlnet only works on dotnet core 2.1, but we are working on making it compatible with dotnet3.1 and it will come out pretty soon

#256

**Comment by LittleLittleCloud** [comment]
Upgrade to 3.1 in this [PR](https://github.com/dotnet/machinelearning-tools/pull/598)

**Comment by JacksonKearl** [comment]
@LittleLittleCloud the PR is 404ing, what is status of upgrade?
