### ISSUE TITLE
Feb Usabilla Feedback: ML.NET Tutorial 

### ISSUE THREAD

**Issue by v-mepa** [dotnet/machinelearning-modelbuilder#641]
**User Comment 1:** Doesn't work. Error with latest ml version.
**URL:** https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
**Screenshot:**  https://u4w-screenshots-production.s3.amazonaws.com/5e580b57e7703e50475b50cc/screenshot

**User Comment 2:** Doesn't see Machine Learning option, why? I have installed ,Net Core 2.1 SDK, restarted PC, removed ML.Builder, restared PC again anthen reinstalled ML builder but can't still see MAchine Builder to choose when click "Add".
**URL:** https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
**Screenshot:** https://u4w-screenshots-production.s3.amazonaws.com/5e566d04d274630a766e4c5f/screenshot

**User Comment 3:** how can you put a tutorial out there that requires an earlier version   of your own framework??? mlnet auto-train --task binary-classification   --dataset "wikipedia-detox-250-line-data.tsv" --label-column-name   "Sentiment" --max-exploration-time 10 It was not possible to find   any compatible framework version The framework 'Microsoft.NETCore.App',   version '2.1.0' was not found.   - The following frameworks were   found:       3.1.1 at  [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]  You can resolve   the problem by installing the specified framework and/or SDK.  The   specified framework can be found at:   - https://aka.ms/dotnet-core-applaunch?fra 
**URL**:https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
**Screenshot:** https://u4w-screenshots-production.s3.amazonaws.com/5e52f95bce07435278450f03/screenshot

**User Comment 4:** MyMLAppML was underlined by red. I think I have no such library
**URL :** https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
**Screenshot:** https://u4w-screenshots-production.s3.amazonaws.com/5e4d5ad267230857f64f3247/screenshot

**User Comment 5:** Following through with the steps, the trained model appears to give me true for everything that is put in that is beyond a one word value.  I feel that some example cases for positives, negatives, false positives, and false negatives should be added in to help showcase what you may experience when consuming the model.
**URL:** https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
**Screenshot:** https://u4w-screenshots-production.s3.amazonaws.com/5e4431c48e28731937613b8f/screenshot

**Comment by v-mepa** [comment]
@briacht I tried assigning this to you but it wont let me.

**Comment by briacht** [comment]
Hey @v-mepa , none of these links for the screenshots work

**Comment by briacht** [comment]
I believe the only actionable feedback (without further info) is:
**User Comment 3** - release CLI for .NET Core 3.1 (which will be our next release)
**User Comment 5** - use the yelp dataset for the getting started tutorial once Model Builder accepts files with no headers

**Comment by v-mepa** [comment]
The screenshots are only available for a month from the day feedback was logged, we have streamlined the process and trying to share feedback on a bi-weekly basis. These feedback were from Feb 2020. I will start adding the dates to issues so that you don't miss out on screenshots.
