### ISSUE TITLE
VS2019 crashes with the CreditCardFraud dataset from Kaggle

### ISSUE THREAD

**Issue by marcselis** [dotnet/machinelearning-modelbuilder#648]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

When training a new model from the CreditCardFraud dataset from Kaggle
(https://www.kaggle.com/mlg-ulb/creditcardfraud), Visual Studio 2019 16.5.2 crashes after starting the training, activating another window and reactivating Visual Studio.

**Comment by LittleLittleCloud** [comment]
Hey @marcselis . I can't reproduce the error on my computer, could you provide more details on it. Thanks

**Comment by marcselis** [comment]
I am following the tutorial in the link above, but I'm using the 155Mb input file from kaggle instead of the input file that is proposed in the tutorial.  When I come to the stage to start training the model it proposes to spend 1800 seconds on training.
After I click "start training", the trainign process starts and the progress keeps updating like expected.

But when I use my computer to do something else and switch back to Visual Studio 2019 16.5.2 to check on the progress, Visual Studio hangs.  The progress is not updated anymore and it is not responding to any clicks on menu items or whatever.  After some time a dialog appears saying that Visual Studio is not responding and needs to be restarted.

**Comment by LittleLittleCloud** [comment]
Can you reproduce the crash
@JakeRadMSFT Do you know where can we check VS's crash logs

**Comment by marcselis** [comment]
Yes I can reproduce the problem.
Steps:
1. start visual studio
2. create a new .NET Core 3.1 console project
3. click add, "Machine Learning"
4. Choose Sentiment Analysis
5. Choose File input and select the creditcard.csv file
6. Set "Column to predict label" to "class"
7. Click the "Train" button
8. Click the "Start Training" button.  The training time counter starts decreasing.
9. Activate another Window on your computer, "Edge Chromium" for example
10. Reactivate visual studio.
11. You'll notice that Visual Studio is not responding.  The training time counter is frozen.
12. Click somewhere in the Visual Studio window.
13. After a few seconds the "Microsoft Visual Studio 2019 has stopped working" dialog appears.
![dwm_kZ5UMuJjDS](https://user-images.githubusercontent.com/3587795/78639546-71604a80-78ae-11ea-9205-7e1b16ab377e.png)
[VSLog.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4442469/VSLog.zip)

**Comment by marcselis** [comment]
There is even an easier way to make Visual Studio crash I found out while documenting the steps above: if you activate another window after step 5 above and then reactivate Visual Studio again, the "Visual Studio 2019 stopped working" dialog appears quasi immediately.
[VSLog2.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4442537/VSLog2.zip)

**Comment by LittleLittleCloud** [comment]
Hey @marcselis, we might need your dump file for further diagnosis.  Could you follow this [link](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#record-a-repro) and report the issue that you find, thanks

**Comment by marcselis** [comment]
Hi @LittleLittleCloud, problem report can be found here: https://developercommunity.visualstudio.com/content/problem/984205/vs2019-1953-crash-while-using-microsoftml-modelbui.html

**Comment by LittleLittleCloud** [comment]
Thanks
