### ISSUE TITLE
Mar (1-31st) Usabilla Feedback: ML.NET tutorial

### ISSUE THREAD

**Issue by v-mepa** [dotnet/machinelearning-modelbuilder#649]
**User Comment 1:** I have Visual Studio 2019 and can't seem to find Machine Learning.
**URL:** https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
**Screenshot:** https://u4w-screenshots-production.s3.amazonaws.com/5e681a67d6b09b0f832e07d5/screenshot

**User Comment 2:** Can this be done for VC++?
**URL:** https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
**Screenshot:** https://u4w-screenshots-production.s3.amazonaws.com/5e67f6f2a1f64a5e78536ef1/screenshot

**User Comment 3:** Microsoft.ML.Data is not showing up
**URL:** https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/generate-code
**Screenshot:** https://u4w-screenshots-production.s3.amazonaws.com/5e79d473d274636c7d5362dc/screenshot

**User Comment 4:** Instructions say "Run myMLApp" but the app doesn't compile to an .exe and it doesn't say how to run a DLL app. Need directions to launch a DLL app from a console window.
**URL:** https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
**Screenshot:** https://u4w-screenshots-production.s3.amazonaws.com/5e714fe544952f444c2acdfe/screenshot

Adding table incase you want to know more details for each feedback :)
Status | Button name | Rating | Comment | Date | URL | Feedback Type | Language | OS | Browser | Device | Image
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Bri | Desktop | 2 | I have Visual Studio 2019   and can't seem to find Machine Learning. | 3/10/2020 22:53 | https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create | Specific | en-US | Win10 | Chrome 81.0.4044.43 | Desktop | https://u4w-screenshots-production.s3.amazonaws.com/5e681a67d6b09b0f832e07d5/screenshot
Bri | Desktop | 2 | Can this be done for VC++? | 3/10/2020 20:22 | https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create | Specific | en-US | Win10 | Chrome 80.0.3987.132 | Desktop | https://u4w-screenshots-production.s3.amazonaws.com/5e67f6f2a1f64a5e78536ef1/screenshot

Bri | Desktop | 3 | Microsoft.ML.Data is   not showing up | new | 3/24/2020 9:35 | https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/generate-code | Specific | en-US | Win10 | Chrome 80.0.3987.149 | Desktop | unknown | https://u4w-screenshots-production.s3.amazonaws.com/5e79d473d274636c7d5362dc/screenshot
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Bri | Desktop | 3 | Instructions   say "Run myMLApp" but the app doesn't compile to an .exe and it   doesn't say how to run a DLL app. Need directions to launch a DLL app from a   console window. | new | 3/17/2020 22:32 | https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume | Specific | en-US | Win10 | Chrome 80.0.3987.132 | Desktop | unknown | https://u4w-screenshots-production.s3.amazonaws.com/5e714fe544952f444c2acdfe/screenshot

****

**Comment by JakeRadMSFT** [comment]
Closing for now since we can't reach out to the customers and the information we have isn't actionable.
