### ISSUE TITLE
'mlnet' not found 

### ISSUE THREAD

**Issue by RashiqueR** [dotnet/machinelearning-modelbuilder#650]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by LittleLittleCloud** [comment]
Could you check if you add dotnet tool's path to `PATH` variable
`export PATH="$PATH:/root/.dotnet/tools"`

**Comment by beccamc** [comment]
@RashiqueR Did Xiaoyun's suggestion above help?

**Comment by beccamc** [comment]
Please try adding dotnet tool's path to `PATH `variable. If you're still seeing a problem please comment and reopen this issue. Thanks for reporting!
