### ISSUE TITLE
Model builder hangs on large datasets

### ISSUE THREAD

**Issue by Lynx1820** [dotnet/machinelearning-modelbuilder#652]
**System Information:**
 - Model Builder Version: 16.0.2003.302
 - Visual Studio Version: 2019 Preview

**Describe the bug**
When trying to load a large file in the Data step, VS hangs ("Not responding").

**To Reproduce**
Load a dataset of size 1TB w/ 4.4B rows.

![image](https://user-images.githubusercontent.com/10573634/78310194-0c999e80-7502-11ea-8fa2-ebe3e1b24cd2.png)
**Additional context**

**Comment by JakeRadMSFT** [comment]
@beccamc can we add this to our datasets issue.

**Comment by beccamc** [comment]
I took a look at our telemetry for number of columns (query in one note -> Shield team -> Kusto Queries). Below are the buckets of datasets and columns. 8,675 datasets have 1-100 columns. 2,744 datasets have 101-200 columns, etc. 47% of our datasets have over 100 columns (our current cut off for rendering in the UI).  5% have over 1000 columns.  

NumColumns | count_ |  percentage of total
100 | 8675 | 53%
200 | 2744 | 17%
300 | 1830 | 11%
400 | 909 | 6%
500 | 304 | 2%
600 | 952 | 6%
700 | 107 | 1%
800 | 18 | 0%
900 | 26 | 0%
> 1000 | 127 | 5%

**Comment by JakeRadMSFT** [comment]
@Lynx1820, Can you share the dataset? How many columns/rows does it have?

**Comment by Lynx1820** [comment]
I'm sorry, I just saw this. The data can be found at \\ct01\data\Criteo\Spark\day_0-23_withHeader.tsv

**Comment by JakeRadMSFT** [comment]
Closing out for Epic to track this work.
