### ISSUE TITLE
System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.ML.Data, Version=1.0.0.0,

### ISSUE THREAD

**Issue by ttstanley** [dotnet/machinelearning-modelbuilder#653]
**System Information (please complete the following information):**
 - Model Builder Version: N/A
 - Visual Studio Version Version 16.5.2

**Describe the bug**
When trying to use ConsumeModel.predict(); in my WPF app, I get a System.IO.FileNotFoundException: 

**To Reproduce**
1. Run my project
2. Click the 'Next' box on application
3. choose a random image from "browse" button and select "Chihuahua" from Breed Guess
4. Click Classify
5. Error pops up

**Expected behavior**
No error at all

**Comment by LittleLittleCloud** [comment]
Right now ML.Net doesn't work well with default netstandard project sdk, can you use [.net core project sdk(Microsoft.NET.Sdk.WindowsDesktop)](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview) to build your package instead?

**Comment by beccamc** [comment]
Tevin resolved this. Closing

**Comment by rapidengineering** [comment]
How was this resolved? I am having the same error with WPF.
