### ISSUE TITLE
Add project capabilities

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#655]
if generated by ModelBuilder, will add
`<ProjectCapability Include="ModelBuilderGenerated" />`
else
`<ProjectCapability Include="MLNETCLIGenerated" />`
to .Model and .Console project

**Comment by beccamc** [comment]
Yes! I see this in telemetry 

ML.Model project - 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/7780d76d-4f2c-4069-9946-a7008f8f62cf)

ConsoleApp project - 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/d270eb05-5e1f-4dc7-86bd-5285b24fcb12)
