### ISSUE TITLE
If connection lost  during Azure set up  for training  the right message not displayed 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#657]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
if intent connection is lost while the user is setting up for azure  taring we have to tell explicitly for the user as they have connection issue  

**Steps to Reproduce**
1. _Select Image classification scenario
2. _ select Azure environment 
3. click `set up workspace` button
4. Disconnect your internet connection
4. Select or create new  subscription 

**Expected Experience**
it should display dialog box  that tell there is connection problem  like [retry connection dialog](https://app.zenhub.com/workspaces/mlnet-tools-5cde1c97e3106e39e8ae08fc/issues/dotnet/machinelearning-modelbuilder/570)
**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/88d98e38-3e42-438e-8c4a-afaf7970e463)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
Training retry experience is working.
