### ISSUE TITLE
dataset error

### ISSUE THREAD

**Issue by SandhyaKourla** [dotnet/machinelearning-modelbuilder#658]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
@SandhyaKourla Sorry you've run into problems using Model Builder. Could you provide more details on the error you experienced? If possible, please attach the dataset that has problems. Thanks!

**Comment by beccamc** [comment]
@SandhyaKourla Friendly ping, any more details you can provide on this error?

**Comment by beccamc** [comment]
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/6e2b3fc2-27e1-4f66-91b3-b64d25ce9bec)
