### ISSUE TITLE
Sentiment Analysis Model  - Error on Training 

### ISSUE THREAD

**Issue by marwanatefgaber** [dotnet/machinelearning-modelbuilder#659]
Problem encountered on Visual Studio 2017 - Sentiment Analysis Model 
Operating System: windows

After Training Visual Studio Gives me this error  >

Error Details :  at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Microsoft.ML.CodeGenerator.Utilities.Utils.CreateSolutionFile(String solutionFile, String outputPath)
   at Microsoft.ML.CodeGenerator.CSharp.CodeGenerator.GenerateOutput()
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext()

**Comment by LittleLittleCloud** [comment]
Hi, thanks for your report, It seems that ModelBuilder can't access the location of the solutionFile, maybe it's used by some other process? And BTW could you provide your error message?

**Comment by beccamc** [comment]
@marwanatefgaber Thanks for reporting! Can you provide more details for the questions asked above?

**Comment by beccamc** [comment]
Unfortunately we don't have enough information to investigate this issue. If you're still seeing a problem, please provide answers to the above question and reopen. Thanks!
