### ISSUE TITLE
Train should not be enabled unless user selects the column to predict

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#66]
**System Information (please complete the following information):**
 - Model Builder Version: 
16.0.1905.2402
 - Visual Studio Version
VS 2019 RTM

**Describe the bug**
Train should not be enabled unless a user selects the data (file/ sql) and selects a column to predict.

**To Reproduce**
1. Add ML
2. Choose Sentiment Analysis
3. Upload a csv file
4. Click Train

**Expected behavior**
Train should not be enabled unless you select the column to predict.

**Screenshots**
![image](https://user-images.githubusercontent.com/1132652/58581664-f7c6ed00-8204-11e9-831b-087df11514b8.png)

**Additional context**

**Comment by tbombach** [comment]
Merged a fix for this and we'll ship this in the upcoming release
