### ISSUE TITLE
Text Classification : Failed see more in Output Pane

### ISSUE THREAD

**Issue by NVentimiglia** [dotnet/machinelearning-modelbuilder#662]
### System information

- Windows 10
- 3.1.1

### Issue

- **What did you do?**
I am using the ML.NET Model builder tool for visual studio to add machine learning to an existing dot net core web application. Using the tool, I attempted to train a text classification data set. When training, the progress stops saying 

> Status Failed. See more in Output Pane. 

The text in the output pane is 

> |     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |

My data set can be found here : https://data.world/crowdflower/sentiment-analysis-in-text

- **What did you expect?**

Either for the training to succeed or for a actionable error message.

### Source code / logs

No source code included, I am using the visual studio editor tool.

**Comment by LittleLittleCloud** [comment]
> So what?! Where is my Model and Code?
> 
> ![image](https://user-images.githubusercontent.com/6097882/78536168-14a15900-77f6-11ea-97f1-2e41ff6c41d6.png)

Can you go to the `code` page and there's a button names `Add to projects`. Simply click that to add model to your project

**Comment by beccamc** [comment]
@NVentimiglia You're absolutely right, thank you for reporting. I've made a few fixes that should help. 
1. I added the logging to the output pane
2. An error dialog should have been shown. It might have popped up behind the VS instance. I've fixed it so it should pop up in front. 

I've tested with the dataset you provided and I get a result that should put you on the right track: 
![image](https://user-images.githubusercontent.com/9122518/79160681-0bccfc00-7d8f-11ea-922c-3bb1024999bf.png)
 
We should also give you a better starting training time. Tracking that here [672](https://github.com/dotnet/machinelearning-modelbuilder/issues/672).

**Comment by beccamc** [comment]
@SkyQuant Can you see an "Add projects" button in the "Code" tab (bottom of left hand navigation) ?

**Comment by LittleLittleCloud** [comment]
My output window looks like this
![image](https://user-images.githubusercontent.com/16876986/79504226-652f6800-7fe7-11ea-9bd0-3648ef4e9688.png)

**Comment by SkyQuant** [comment]
> @SkyQuant Can you see an "Add projects" button in the "Code" tab (bottom of left hand navigation) ?

> Can you go to the `code` page and there's a button names `Add to projects`. Simply click that to add model to your project

Each possible buttons are pressed. And "Add projects" obviously first of all. Please, pay attention on 1) how it behave with dataset with delimiter (semicolon) at the row end  2) double to float conversion.
