### ISSUE TITLE
No Machine Learning in the Add menu

### ISSUE THREAD

**Issue by RodrickRK** [dotnet/machinelearning-modelbuilder#67]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1905.641
 - Visual Studio Version: 15.9.12

**Describe the bug**
There is no option to enable Machine Learning 

**To Reproduce**
1. Go to Solution Explorer 
2. Right Click on Project
3. Scroll down Add
4. No Machine Learning Present

**Expected behavior**
There should be an option to add Machine Learning in the Add menu

**Comment by rustd** [comment]
What project type are you using?

**Comment by rustd** [comment]
Please re-open and add more details if this issue still happens.
