### ISSUE TITLE
Better predict training times

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#672]
Our [current guidelines](https://aka.ms/vsmbtrain) for training time doesn't work with some datasets. 

Building an ML model to predict how long training should take.

**Comment by beccamc** [comment]
This is related to #120

**Comment by LittleLittleCloud** [comment]
Questions

For AutoML experiments, since the training time is set by users, `TrainResult.ExpeimentTime` will always be close to that training time. In that case how can we use this info to build a model and recommend appropriate training time.

**Comment by beccamc** [comment]
Great question! You are correct. At first only the successful runs have data that is useful, and ignoring failed runs will leave us with a bad model. To start, I think we can only have a model that predicts if you're training time is long enough to succeed. I think it's still useful because we can guess if the time is long enough, and add more if not. Hopefully, after a while of doing this, we'll have enough successful data to make actually value predictions. 

For Azure training we can create a model that predicts how long we think it'll take, just to give the user an estimated completion time (they still won't have the ability to change it... just an estimate to inform them) 

Thoughts?

**Comment by beccamc** [comment]
Haven't had any customer asks for this in a while. Closing as not high priority.
