### ISSUE TITLE
Azure Training Image Classification - Model Deployment Improvements

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#679]
While working on a sample to demo Azure training, there were a few challenges. The ideal sample would deploy the model trained in Azure to a .NET Core WinForms / WPF application. Instead, the current sample hosts the model in an ASP.NET Core Web API as a service and consumes the API from a UWP application.

https://docs.microsoft.com/en-us/samples/dotnet/machinelearning-samples/mlnet-image-classification-azure-model-builder/

Challenges listed below:

1. "Training" takes a long time (the first time). When start training is clicked, working with 2,000 images takes at least 30 minutes. Most of that time is spent provisioning resources the first time.
1. MapControl in WPF does not support Aerial View windows-toolkit/MIcrosoft.Toolkit.Win32#205
1. Can't deploy app to UWP directly because UWP does not support `System.Drawing`. While `System.Drawing` is not used directly by the UWP app, the pipeline created in `ModelBuilder` class of `Model` project uses it via the `LoadImages` transform. 
1. Can't use `PredictionEnginePool` because it doesn't expose `MLContext` for registering `CustomTransform` assemblies. dotnet/machinelearning#4965 #618
1. Can't reuse `ConsumeModel.Predict` method in `Model` autogenerated project because the current implementation returns a prediction instead of a `PredictionEngine`.

**Comment by JakeRadMSFT** [comment]
For #3 is there a different way to load images in UWP? I think we should be able to work around this ... we just might need a custom mapping and change the pipeline a bit.

**Comment by JakeRadMSFT** [comment]
# 5 we just need to publish an update extension. We'll have to update all of our install instructions to use the new extension.

**Comment by JakeRadMSFT** [comment]
Num 4 is in-progress

**Comment by luisquintanilla** [comment]
Maybe. Re: # 3 the challenge is the `NormalizeMapping` transform which takes the pixel values and normalizes them. The ONNX model expects a `float[]` or `Vector<Single>`. Therefore, `LoadRawImageBytes` wouldn't work. Unless you tweak `NormalizeMapping` transform to also convert the `byte[]` to `float[]`. The local image classification version works just fine by the way because it uses `LoadRawImageBytes` transform so not many workarounds, or hosting in ASP.NET Core Web API required then.

**Comment by JakeRadMSFT** [comment]
Yeah we could do that conversion ... @LittleLittleCloud can you look into this a bit?

**Comment by beccamc** [comment]
Luis, this should be fixed in the November ML.NET release. Can you validate it then?

**Comment by luisquintanilla** [comment]
Closing this issue since there have been several changes made that would make this scenario possible. Codegen is also being improved as part of #1638
