### ISSUE TITLE
Generated Code Projects Stored in Two Places

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#68]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1905.641
 - Visual Studio Version: 15.9.12

**Describe the bug**
After the model is trained and evaluated. In the Code step, after clicking `Added Projects`, as expected they are added to the current solution. However, they also persist in the default save location therefore storing the generated code contents in two places.

**Expected behavior**
After projects are added to the current solution, the generated code stored in `C:\Users\%USERNAME%\AppData\Local\Temp\MLVSTools` should be cleaned up / deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/46974588/58726010-9b073600-83ae-11e9-9ea0-71778442977f.png)

**Comment by rustd** [comment]
#76

**Comment by JakeRadMSFT** [comment]
It's not uncommon to leave stuff in Temp and windows has settings to Auto Clean ... but it should be easy to do.
