### ISSUE TITLE
Video Backlog

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#680]
## Quick getting started
 - [x] Intro to Machine Learning **Initial Video Series**
 - [x] Intro to Model Builder/CLI patterns (Scenario -> Environment -> Data -> Train -> Evaluate -> Code) **Initial Video Series**
 - [ ] Train a Machine Learning model in 60 seconds!
   - Sentiment analysis 

## General/Help:
 - [ ] Scenario Breakdown
 - [ ] Local vs Azure
 - [x] What is AutoML? **Initial Video Series**
 - [x] What is AutoML.NET? **Initial Video Series**
 - [ ] What is Azure ML (Workspace, Compute, Experiment)?
 - [ ] What is Azure AutoML?
 - [ ] How to pick an Azure Compute?
 - [ ] How much will training in Azure cost?
 - [ ] What is ML.NET?

## Data Prep:
 - [ ] Prepare your data for Classification
 - [ ] Prepare your data for Regression
 - [ ] Prepare your data for Recommendation
 - [ ] Prepare your data for Image Classification
 - [ ] Prepare your data for Object Detection

## Train:
 - [ ] Classification
 - [ ] Regression
 - [ ] Recommendation
 - [ ] Image Classification
 - [ ] Image Classification W/ GPU
 - [ ] Image Classification W/ Azure
 - [ ] Object Detection

## Leverage Model:
 - [ ] Using a Model in ASP.NET Applications
 - [ ] Using a Model in Blazor Application
 - [ ] Using a Model in WPF Application
 - [ ] Using a Model in WinForms Application

**Comment by JakeRadMSFT** [comment]
Where to post:

- [ ] Youtube Channel
- [ ] Tweet
- [ ] Linked In
- [ ] Hacker News
- [ ] Reddit

**Comment by JakeRadMSFT** [comment]
Video 1 Outline - The Essentials/Surface Level

- Intro to Machine Learning Essentials
  - What is Machine Learning (Very high level)?
    - What is a Model?
      - Training a Model
        - Example Data
      - Predictions with a Model
- Intro to Machine Learning with .NET
  - ML.NET - Framework to train Models with .NET/C# 
    -  Deeper dive in future videos.
  - Model Builder
    -  Train models from within VS
      - Scenario -> Environment -> Data -> Train -> Evaluate -> Code
  - MLNET CLI
    -  Train models from command line on MacOS and Linux using the same paradigm as Model Builder.

**Comment by JakeRadMSFT** [comment]
Consider adding how to consume other models in .NET as a videos

- TensorFlow
- PyTorch
- ONNX
- etc ...

**Comment by jwood803** [comment]
>Using a Model in ASP.NET Applications
 Using a Model in Blazor Application
 Using a Model in WPF Application
 Using a Model in WinForms Application

If it helps any, I have videos/examples of all of these except WinForms, which I can definitely do. 😄
