### ISSUE TITLE
Update example dataset/experiment for classification

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#681]
The current dataset is Wikipedia, which is an NLP sentiment analysis task and isn't perform very well when training using AutoML.Net. We might want to use another dataset as example (like iris or titanic).

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud is there a better featurizer that we could use?

**Comment by briacht** [comment]
We now use the Yelp dataset for the Getting Started tutorial which works well.
