### ISSUE TITLE
myMLApp does not run

### ISSUE THREAD

**Issue by jsaneill** [dotnet/machinelearning-modelbuilder#683]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Used ML tutorial for getting started.  myMLApp could not run.  Multiple errors listed such as unable to find NETStandard .lirary, Microsoft.NETcore .app, etc.  I checked references but not able to see a solution.

**Comment by LittleLittleCloud** [comment]
Thanks for reporting, which step do you fail at? Training model or consuming generated project? Could you provide more details? Such as error logs or screenshot.

**Comment by LittleLittleCloud** [comment]
Unfortunately, we don't have enough information to investigate this issue, If you're still seeing a problem, please re-open and provide additional information, thanks for reporting!
