### ISSUE TITLE
Consider making model builder's code generation 'ala carte'

### ISSUE THREAD

**Issue by nicolehaugen** [dotnet/machinelearning-modelbuilder#686]
ML .NET 1.2.0

Model Builder’s code generation functionality is useful for generating large data structures that contain many columns\properties; however, this functionality is currently tied to only a few trainers that are currently supported by Model Builder.

You can still use the code generation portion with other models, which is what I did for the recent Ranking sample. 

We should surface the code generation functionality so that it can be used selectively with other trainers.  Today, it's not clear that you can use the code generation piece with other trainers like this.

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! Can you share how you used it with Ranking?

**Comment by JakeRadMSFT** [comment]
@nicolehaugen Closing for now! We're adding ranking support ... hopefully that will resolve this issue.

Happy to discuss it more if you can provide insight into how ala carte would help beyond Model Builder adding more scenarios. Feel free to open with more details.

Thanks for reporting!

Cheers,
Jake
