### ISSUE TITLE
A CLI-script does not produce the same results as the generated C# code.

### ISSUE THREAD

**Issue by CBrauer** [dotnet/machinelearning-modelbuilder#687]
Hey Guys,

I have found that the C# source code that is generated by the CLI script does not agree with the script output.

I have modified the solution that is generated by a cli-script to see it they agree.  The cli-script shows metric values that I cannot duplicate with the code that was generated by the script.

I believe that the MLModel.zip file is not for the optimal solution found by the script.
I have zipped everything into a file called “cli-script.zip” and I have put this Zip file on my GitHub account: https://github.com/CBrauer/Test-of-ML.NET.

The file “test.zip” contains the folder: “cli-script”.  This folder contains:
1.	Model2.  This is the modified project solution that was created by the cli-script.
2.	“run-cli-script-model2.bat”.  This runs script.
3.	screen.png.  This is a screen capture of the results of the script.
4.	verify.txt.  The output of the Model2 project.  This should give the same results as “screen.png”.
The script output does not produce the same results as the C# solution that was created by the script.

I, therefore, assume that “MLModel.zip” is not the correct model file.

Charles

**Comment by LittleLittleCloud** [comment]
Hey @CBrauer, the link to your project is 404, can you update your project link?

**Comment by CBrauer** [comment]
Sorry about that.  It's back up at https://github.com/CBrauer/test.zip

**Comment by LittleLittleCloud** [comment]
Tested it on latest mlnet.cli. After setting test dataset with `validation-dataset`, evaluate metrics from cli and console app are match.

console: MaroAccuracy ~ 0.86637
![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/b29b9240-b803-44d8-b880-3a6fe3db55c7)

cli: 
![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/41c3f72f-ad86-4989-86dd-0d3f32e1a217)

Another thing, having both`--validation-dataset` and '--test-dataset' is rather confusing. I would prefer only keep `--test-dataset` and use it both as validate dataset when training and test dataset when generating code.

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you have any quesitons.
