### ISSUE TITLE
Feature: A dropdown list to choose what OptimizingMetric to use in AutoML GUI

### ISSUE THREAD

**Issue by ebizupnorth** [dotnet/machinelearning-modelbuilder#695]
It would be better if there is an option to choose what OptimizingMetric to use when using the AutoML GUI during training.

Thanks for this amazing AutoML.

**Comment by JakeRadMSFT** [comment]
@ebizupnorth Can you describe your scenario more? What metrics would you like to be able to optimize for?

**Comment by JakeRadMSFT** [comment]
@ebizupnorth closing for now but please re-open with more details on your use case! 

Cheers,
Jake
