### ISSUE TITLE
CLI codegen fails with spaces in project name

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-modelbuilder#696]
The AutoML CodeGen can't handle spaces in the project name, or it produces a corrupt .cs file.

Repro:
`mlnet auto-train --dataset analcatdata_germangss.csv  --ml-task multiclass-classification --label-column-name "Political_system" --max-exploration-time 60 --name "Analyzing Categorical Data" --output-path /tmp/blah/`

Note the spaces in the project name: 
`--name "Analyzing Categorical Data" `

Dataset: 
https://www.openml.org/data/get_csv/53559/analcatdata_germangss.arff

This produces corrupted .cs files with replicas of the project name.

For example, `Program.cs`:
```c#
using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Analyzing Categorical Data.Model.DataModels;

namespace Analyzing Categorical Data.ConsoleApp
{
    class Program
{
```

You'll note `Analyzing Categorical Data` is replicated into `Program.cs` with the spaces intact. We need to sanitize the project name to fit namespace/variable name requirements.

Currently we use a simple sanitization on the column names:
https://github.com/dotnet/machinelearning/blob/fac974daaec029b732802c1d0802818a27ab37be/src/mlnet/Utilities/Utils.cs#L47-L50

We may be able to reuse that sanitizer.

**Comment by LittleLittleCloud** [comment]
Fixed on latest cli

**Comment by justinormont** [comment]
Thanks @LittleLittleCloud
