### ISSUE TITLE
[Model Builder] Canceling training should not discard current results

### ISSUE THREAD

**Issue by Doggie52** [dotnet/machinelearning-modelbuilder#697]
### System information

- **OS version/distro**: Windows 10.0.18362 x64
- **.NET Version (eg., dotnet --info)**:  2.1.507
- **ML.NET Model Builder version**: 16.0.1905.641
- **Visual Studio 2017 version**: 15.9.12

### Issue

- **What did you do?** Ran Model Builder and started Training. After noticing that accuracy was not improving, I decided to cancel the training.
- **What happened?** Progress was canceled and I was unable to proceed to the Evaluate stage.
- **What did you expect?** I wanted to continue to the Evaluate stage to take the so far best performing model forward.

Possibly related to dotnet/machinelearning#844 although that issue I believe is for training one particular model, whereas this is for training multiple models.

### Source code / logs

![image](https://user-images.githubusercontent.com/4928988/57863894-cb69a480-77f2-11e9-8644-b10ce7c2337a.png)

As you can see, no link to Evaluate was present beneath the results.

**Comment by JakeRadMSFT** [comment]
Related #233

**Comment by LittleLittleCloud** [comment]
#233

**Comment by vzhuqin** [comment]
This issue can't be repro on：
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch:
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

Steps：
1. Create new C# console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Click "Stop training" after noticed the training results;
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/f37acc86-eea7-4fe8-afe3-23197323aaf9)
4. The message changed to "Cancelling">"x seconds remaining...">"Finalizing model...">"Training complete"
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/c2e709ce-83b2-4125-874e-05cce2e69df8)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/fda111e9-2089-4255-92d1-ec6d19fd1d6d)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/f4f6cf04-2c98-4065-9faf-b9bd8c04fd24)
