### ISSUE TITLE
Referenced sample does not have file header

### ISSUE THREAD

**Issue by natke** [dotnet/machinelearning-modelbuilder#70]
This example data set does not have a header, and Model Builder requires data files to have a header: https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip

Without extra information, this would cause confusion if a user tried Model Builder with this dataset.

Reference from this file: https://github.com/dotnet/machinelearning-samples/tree/master/modelbuilder

**Comment by rustd** [comment]
Duplicate of  #74
