### ISSUE TITLE
Model Builder Error after training

### ISSUE THREAD

**Issue by NebuDa** [dotnet/machinelearning-modelbuilder#704]
Hello,

Windows 10
Visual Studio 19

After creating a new C# WPF Framework Project just right clicking -> Add -> Machine Learning:
- Scenario Sentiment Analysis
- File .csv Label: Ausfall der Motoreinheit | Input Columns 2 of 2 selected
- Train for 10 seconds. 
- Error Popup: 
Model Builder Error
--------------------------
Das System kann die angegebene Datei nicht finden

bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei Microsoft.ML.CodeGenerator.Utilities.Utils.CreateSolutionFile(String solutionFile, String outputPath)
   bei Microsoft.ML.CodeGenerator.CSharp.CodeGenerator.GenerateOutput()
   bei Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:Zeile 155.

Previusly it tests something, I will post the Output below:

|     Trainer                              Accuracy      AUC    AUPRC  F1-score  Duration #Iteration             |
|1    AveragedPerceptronBinary               0,9412   0,8571   0,9635    0,9655       0,2          1             |
|2    SdcaLogisticRegressionBinary           0,9412   0,8571   0,9635    0,9655       0,8          2             |
|3    LightGbmBinary                         0,9583   1,0000   1,0000    0,9778       0,3          3             |
|4    SymbolicSgdLogisticRegressionBinary    0,8235   0,8571   0,9635    0,9032       0,3          4             |
|5    LinearSvmBinary                        0,9412   0,8571   0,9635    0,9655       0,2          5             |
|6    FastTreeBinary                         1,0000   1,0000   1,0000    1,0000       0,8          6             |
|7    LbfgsLogisticRegressionBinary          0,9412   0,8333   0,9213    0,9655       0,3          7             |
|8    FastForestBinary                       0,9231   1,0000   1,0000    0,9583       0,9          8             |
|9    SgdCalibratedBinary                    0,8824   0,5333   0,9292    0,9375       0,3          9             |
|10   LightGbmBinary                         0,9583   1,0000   1,0000    0,9778       0,4         10             |
|11   FastTreeBinary                         1,0000   1,0000   1,0000    1,0000       0,8         11             |
|12   LbfgsLogisticRegressionBinary          0,9412   0,8333   0,9213    0,9655       0,3         12             |
|13   LightGbmBinary                         0,9583   1,0000   1,0000    0,9778       0,3         13             |
|14   FastTreeBinary                         0,9583   0,9783   0,9981    0,9778       1,5         14             |
|15   LbfgsLogisticRegressionBinary          0,9412   0,8571   0,9635    0,9655       0,3         15             |
|16   LightGbmBinary                         0,8750   0,9348   0,9962    0,9302       0,3         16             |
|17   FastTreeBinary                         0,9412   1,0000   1,0000    0,9655       0,9         17             |
|18   LbfgsLogisticRegressionBinary          0,9412   0,8333   0,9213    0,9655       0,3         18             |
|19   LightGbmBinary                         0,9583   1,0000   1,0000    0,9778       0,5         19             |

===============================================Experiment Results=================================================
------------------------------------------------------------------------------------------------------------------
|                                                     Summary                                                    |
------------------------------------------------------------------------------------------------------------------
|ML Task: binary-classification                                                                                  |
|Dataset: C:\Users\[...]\Testdaten2Variablen200MLdotNET.CSV|
|Label : Ausfall der Motoreinheit                                                                                |
|Total experiment time : 9,7913704 Secs                                                                          |
|Total number of models explored: 19                                                                             |
------------------------------------------------------------------------------------------------------------------

|                                              Top 5 models explored                                             |
------------------------------------------------------------------------------------------------------------------
|     Trainer                              Accuracy      AUC    AUPRC  F1-score  Duration #Iteration             |
|1    FastTreeBinary                         1,0000   1,0000   1,0000    1,0000       0,8          1             |
|2    FastTreeBinary                         1,0000   1,0000   1,0000    1,0000       0,8          2             |
|3    LightGbmBinary                         0,9583   1,0000   1,0000    0,9778       0,3          3             |
|4    LightGbmBinary                         0,9583   1,0000   1,0000    0,9778       0,4          4             |
|5    LightGbmBinary                         0,9583   1,0000   1,0000    0,9778       0,3          5             |
------------------------------------------------------------------------------------------------------------------

[Testdaten2Variablen200MLdotNET.CSV.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4521133/Testdaten2Variablen200MLdotNET.CSV.txt)

**Comment by LittleLittleCloud** [comment]
Hey @NebuDa. It seems that your training is success, and it might be bug in Code Generator.
Could you provide your system language info? And could you also go to %Temp%\MLVSTools to check if there's a folder names $(Your_solution_name)ML?

**Comment by NebuDa** [comment]
Hi @LittleLittleCloud 
My System Language is German Germany and there is a folder named like my solution "motorausfallKIFloML" but without $

Thanks for responding.

**Comment by NebuDa** [comment]
I have fixed the problem @LittleLittleCloud 
I had to reinstall AND repair Visual Studio. There was a problem with the .NET Core SDK. I've found the problem, because it was not possible to load .NET Core projects.

Thank you very much.
