### ISSUE TITLE
doesnt install for VS 2019 community

### ISSUE THREAD

**Issue by LukePogaPersonal** [dotnet/machinelearning-modelbuilder#706]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by LittleLittleCloud** [comment]
Is modelbuilder extension can't download? or it can't find available VS version after starting install?

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you have any quesitons.
