### ISSUE TITLE
server not found when downloading

### ISSUE THREAD

**Issue by Hesham-Abdalbary** [dotnet/machinelearning-modelbuilder#708]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows

I have run into a server not found issue when I tried downloading the ML.Net package.

**Comment by LittleLittleCloud** [comment]
I just tried again, this time it works. Could you give it another try?

**Comment by Hesham-Abdalbary** [comment]
It works now, thanks A lot
