### ISSUE TITLE
Missing property naming of optionsbase

### ISSUE THREAD

**Issue by allschu** [dotnet/machinelearning-modelbuilder#71]
**System Information (please complete the following information):**
 - Model Builder Version: 
PackageReference Include="Microsoft.ML" Version="1.0.0"
 - Visual Studio Version: 
Microsoft Visual Studio Community 2019
Version 16.0.3
VisualStudio.16.Release/16.0.3+28803.352

**Describe the bug**
When to code is done generating its creates code, in the console app, which is missing an property naming of optionbase. See class ModelBuilder.cs line 59
The bold property is without naming and 

`mlContext.BinaryClassification.Trainers.SgdCalibrated(new SgdCalibratedTrainer.Options() { L2Regularization = 1E-06f, ConvergenceTolerance = 0, **001f**, NumberOfIterations = 10, Shuffle = true, LabelColumnName = "Sentiment", FeatureColumnName = "Features" });`

**To Reproduce**
1. Add Machine Learning to the project
2. Select sentiment analysis
3. Select file and select Use wikipedia-detox-250-line-data.tsv 
4. Select column to predict : Set to sentiment
5. Train the model for 10 sec
6. Click Evaluate
7. Click on Code
8. Build and you will get the error

**Expected behavior**
No error codes while building and all attributes are named.

**Screenshots**

**Additional context**

**Comment by rustd** [comment]
Can you please add the code for the entire file and highlight the code which is incorrect?

**Comment by rustd** [comment]
Can you please add the contents of the whole file and the contents of the error message?

**Comment by greazer** [comment]
@allschu, please re-open this issue if you were not able to resolve it. Thanks!
