### ISSUE TITLE
Log Data Context status in file

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#710]
- [ ] CodeTabDataContext
- [ ] DataTabDataContext
- [ ] EnvironmentTabDataContext
- [ ] EvaluateTabDataContext
- [ ] ModelBuilderDataContext 
- [ ] ScenarioTabDataContext

**Comment by LittleLittleCloud** [comment]
It would be of great help for us to locate error and collect information for debug usage by recording the current model builder state in log file and have user upload it.

**Comment by beccamc** [comment]
We've had this for a while, including customer uploading! I think we can close.
