### ISSUE TITLE
From Label to User and Item column. What should I put in Item column?

### ISSUE THREAD

**Issue by jannavarro** [dotnet/machinelearning-modelbuilder#712]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

So the steps is to download the wikipedia-detox data that has 2 columns: Sentiment and SentimentText. In the tutorial there is a Feature and a Label column however the latest GUI requests data for three columns:

![image](https://user-images.githubusercontent.com/4499051/80440958-685a1a80-893c-11ea-9e0d-eaa876260c60.png)

1. What is the user and item column for?
2. To help your team as well and lessen issues that are just questions I would like to ask if you have a release notes or if it doesn't exist yet I suggest that it should be added.

Thanks,
Jan

**Comment by JakeRadMSFT** [comment]
Hello! It looks like you're using recommendation when trying to train on a sentiment analysis or text classification dataset. Please try training using Text Classification.

For recommendation- an example would be movie recommendations. So the column to predict would be the rating a user would give the movie. The user column would be an ID or name. The Item Column would be the movie id or name column.

Hope that helps!

**Comment by JakeRadMSFT** [comment]
Thanks for the recommendation on release notes. We'll make sure they're added to our github for the release.

Cheers,
Jake

**Comment by JakeRadMSFT** [comment]
Resolving this issue due to lack of activity. Please re-open if you're still hitting this issue and the workaround provided didn't fix it.
