### ISSUE TITLE
Unable to read file from Kaggle in proper CSV format

### ISSUE THREAD

**Issue by aslotte** [dotnet/machinelearning-modelbuilder#713]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
Attempted to use a csv file from Kaggle https://www.kaggle.com/clmentbisaillon/fake-and-real-news-dataset but got a message saying that the format was incorrect although applications such as Excel can read it okay. 

![image](https://user-images.githubusercontent.com/30201569/80519728-6ef58b80-8956-11ea-8b90-3c25b93afe80.png)

**To Reproduce**

**Expected behavior**
I would like to be able to use the CSV file :) 

**Screenshots**

**Additional context**

**Comment by JakeRadMSFT** [comment]
Thanks for reporting this issue! We're working to support more datasets. The common cause is use of newlines or escaped quotes within value.

We've made some improvements but know we have more to go. What version of Model Builder are you using?

**Comment by aslotte** [comment]
Thanks @JakeRadMSFT! I'm not at that specific computer right now, but I'll let you know shortly.

**Comment by aslotte** [comment]
Here's some additional version info: 
![image](https://user-images.githubusercontent.com/30201569/81118986-e5b2fb80-8ef7-11ea-8608-8c2a61fa90dc.png)

**Comment by beccamc** [comment]
@aslotte I tested this dataset on our newest data processing code and it works! You'll have to combine the true and false datasets together and add a true/false column, but the news titles etc. should be readable on version 16.1.0.2027905. 

Let me know how it goes!

**Comment by aslotte** [comment]
Thanks @beccamc, I'll have a look!

**Comment by JakeRadMSFT** [comment]
@aslotte - resolving this issue. If you have any issues with Becca's suggestions feel free to re-open!

Cheers,
Jake
