### ISSUE TITLE
ML.NET 

### ISSUE THREAD

**Issue by EvoGame25** [dotnet/machinelearning-modelbuilder#715]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JakeRadMSFT** [comment]
Thanks for reporting an issue! Unfortunately, there isn't any information for us to investigate. I'll be closing the issue but if you add more details ... please re-open.
