### ISSUE TITLE
model builder generated should be MLNETCLI generated

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#716]
![image](https://user-images.githubusercontent.com/10437687/80536497-520d8800-8957-11ea-8a45-7242a1d56e9c.png)

@JakeRadMSFT MLNETCLI was the name we decided on right?

**Comment by beccamc** [comment]
Yes! Both projects say CLI 
 ![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/fd713f19-3b66-4ed1-9f8e-faee25563e6d)
