### ISSUE TITLE
Batch uploading using azcopy.

### ISSUE THREAD

**Issue by ttstanley** [dotnet/machinelearning-modelbuilder#717]
**Model Builder Version**: 16.1.0.2022701
*Visual Studion Version**: 16.5.4

**Bug description**
When uploading images from different paths for OD takes long time since I have to do them individually. For OD we are given a list of random file paths to upload, so folder uploading wont work. Instead we use single file upload which is also inefficent. Instead we would like to upload a list of files to be more efficient.

**Expected Experience**
Uploading to azure should be short

**Actual Experience**
takes a long time

**Comment by JakeRadMSFT** [comment]
@ttstanley @LittleLittleCloud does azcopy allow for a list of paths?

**Comment by ttstanley** [comment]
> @ttstanley @LittleLittleCloud does azcopy allow for a list of paths?

I don't believe so. From what I have seen it can take a directory or a single file.

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud  what would this take?

**Comment by JakeRadMSFT** [comment]
> Ok. So I'd recommend you use --list-of-files. That flag is not really documented though/it'd probably be good for the AzCopy team to know that y'all are going to be using it. Send an email to azcopyvteam, describe your situation, and say after talking to me I recommended that flag. Ask if they have a different recommendation, and if not, then you can use it.
