### ISSUE TITLE
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.

### ISSUE THREAD

**Issue by Mouldi** [dotnet/machinelearning-modelbuilder#718]
**System Information (please complete the following information):**
 - Model Builder Version: .NetCore 3.1.201 
 - Visual Studio Version :NA
- System : 

                  Distributor ID: Ubuntu
                   Description:    Ubuntu 18.04.4 LTS
                      Release:        18.04
                            Codename:       bionic

**Describe the bug**
When you try to train your model, you get the following error :
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.3 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=ubuntu.18.04-x64

**To Reproduce**
1. try to make the getting started tutorial
2. See error

**Expected behavior**
Train the model

**Screenshots**
![image](https://user-images.githubusercontent.com/8251910/80556428-64ec8080-8988-11ea-9075-5f33e7cdfe71.png)

**Additional context**
If anyone can take a look at this it would be awesome, I'm looking into AI options and ML.net seems like a good option if I can move past this initial hurdles.

Thank you!

**Comment by JakeRadMSFT** [comment]
Hello! 
For now you could get unblocked by installing a 2.1 runtime. We're planning to release a new version of the CLI soon that supports 3.1 and newer runtimes.

**Comment by JakeRadMSFT** [comment]
Resolving this issue. If my workaround didn't unblock you then please re-open this issue! 

We'll be shipping a new CLI this week that will work with 3.*.

Cheers,
Jake
