### ISSUE TITLE
Arabic Support Issue

### ISSUE THREAD

**Issue by Hesham-Abdalbary** [dotnet/machinelearning-modelbuilder#720]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

I ran into a problem while trying to upload a file that contains Arabic text: it told me that the format is incorrect though I have made sure that it is in the correct tab separated format, so, does ML.Net support Arabic language? meaning Can I give it Arabic text and make predictions accordingly ?

**Comment by JakeRadMSFT** [comment]
Do you have a dataset you could share with us?

**Comment by JakeRadMSFT** [comment]
Closing for now due to lack of response.

If you could share a dataset we'd be happy to try it out. The controls we're using should support Arabic and the data parsing should too.
