### ISSUE TITLE
Error in ML.NET Model Builder

### ISSUE THREAD

**Issue by Pn-prog91** [dotnet/machinelearning-modelbuilder#721]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

Hi, I don't know what's happening here. I've uploaded a csv file for my job and wanted to do a price predict of one of the labels. I runned the test for 30 minutes (1800 seconds), and I've achieved at this error:

Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext() em E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\Experiments\AutoMLExperiment.cs:line 108
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() em E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:line 134

Anyone who can help, I'm very gratefull. Thanks.

**Comment by beccamc** [comment]
@Pn-prog91 I'm very sorry for the delay in response! Do you still need help with this issue? If you do, would you be able to share your dataset with me? Thank you!

**Comment by beccamc** [comment]
Sorry again about the delay with this item! At this time I don't have enough info to investigate. If you still need help please ping me and we can reopen the issue. Thanks!
