### ISSUE TITLE
Old Model Builder is displayed instead of new if extension not uninstalled

### ISSUE THREAD

**Issue by jernejk** [dotnet/machinelearning-modelbuilder#722]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
When I installed Visual Studio 2019 16.6 Preview 2 I was very hyped for the new version of ML .NET Model Builder! 😁

Except I got only the old UI... So I ended up using a stable version of Model Builder in VS 16.5 because in the preview version the images were missing.

![image](https://user-images.githubusercontent.com/5943653/80658748-53ab8d00-8aca-11ea-9c09-b602aff45df6.png)
**Figure: The issue persistent to newer preview builds.**

Removing the Model Builder extension fixed the problem!

**To Reproduce**
1. Have Model Builder extension installed prior 16.6 Preview 2
2. Upgrade to 16.6 Preview 2

**Expected behavior**
The new and nice looking UI. 😀

**Screenshots**
![image](https://user-images.githubusercontent.com/5943653/80658852-a1c09080-8aca-11ea-9561-2cb993ce2dbd.png)

**Additional context**
I got it working now and it would be great if anyone else has the same problem, that this could be resolved somehow. Maybe updating the extension and adding a warning on the old version that they should remove the extension because now it's built-in?

**Comment by JakeRadMSFT** [comment]
Thanks for the feedback! We're looking into a smooth upgrade path from the old extension to the new built-in VS version.
