### ISSUE TITLE
Make Model Builder Open Source

### ISSUE THREAD

**Issue by dcostea** [dotnet/machinelearning-modelbuilder#724]
Could you please let me know where is the source code for Machine Learning Model Builder? Or is that private?

I see only this: 

![Untitled](https://user-images.githubusercontent.com/15055082/80817690-38c44000-8bd2-11ea-8ad1-1baa60fc9cc3.png)

**Comment by JakeRadMSFT** [comment]
It's private at the moment. We're looking into the option of making it open source.

Why do you ask? Would you be interested in contributing? Are there certain features you'd like to see added?

**Comment by dcostea** [comment]
> It's private at the moment. We're looking into the option of making it open source.
> 
> Why do you ask? Would you be interested in contributing? Are there certain features you'd like to see added?

I would like to contribute if I can. (I hope it's C#).
In my opinion, the Model Builder has a big impact on adopting ML.NET by developers who don't have Data Science background.
I would like to see more options in preparing the data (this was the point I decided to ask about the repository).
Thank you for your answer.

**Comment by JakeRadMSFT** [comment]
Thanks! We'll look into Open Sourcing.

**Comment by shaggygi** [comment]
Yes, I'm also interested in knowing the plans to open-source Model Builder.  I doubt I would be much help in contributing.  Mainly curious on how the extension works when adding the mbconfig and related files to project.  Thx

**Comment by beccamc** [comment]
Closing this in favor of the linked epic.
