### ISSUE TITLE
Model Builder Error

### ISSUE THREAD

**Issue by Darkne77** [dotnet/machinelearning-modelbuilder#726]
**Model Builder Version**: 16.0.2003.302
**Visual Studion Version**: 2019

Error:

Tensorflow exception triggered while loading model.

   в Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext() в E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\Experiments\AutoMLExperiment.cs:строка 108
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() в E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:строка 134

**Comment by JakeRadMSFT** [comment]
Hello,
Thanks for reporting! Sorry you're hitting this issue. Can you share more details?

What are the specifications of your machine? How much memory/ram do you have?

Cheers,
Jake

**Comment by Darkne77** [comment]
SSD 500 Gb, 16 Gb RAM

**Comment by JakeRadMSFT** [comment]
Could you try uninstalling and re-installing the ModelBuilder extension. I've only seen this happen when an ML.NET dependency is missing. That shouldn't be possible since we package it with the Model Builder extension but perhaps it had issues installing.

**Comment by JakeRadMSFT** [comment]
If you can update to VS 2019 16.6 Preview 3 or newer - 

https://devblogs.microsoft.com/visualstudio/new-in-visual-studio-2019-v16-6-preview-3/

We have a newer version of Model Builder available.

**Comment by Darkne77** [comment]
I tried in


   в
Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext()
в
/_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:строка
106
--- Конец трассировка стека из предыдущего расположения, где возникло
исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   в
Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext()
в
/_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:строка
147

вт, 5 мая 2020 г. в 20:32, Jake <notifications@github.com>:

**Comment by JakeRadMSFT** [comment]
Might be related to this issue:

https://github.com/dotnet/machinelearning/issues/5052

**Comment by Darkne77** [comment]
I find decision. Visual Studio Installer -> VS community 2019 -> additionally(Дополнительно) -> recover(Восстановить).

**Comment by lbdalmendray** [comment]
Microsoft Visual Studio Community 2019
Version 16.6.0
Adding ML.Net Builder to a Blazor Server Project .
Model Builder Error
Value cannot be null.
Parameter name: source

at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\Experiments\AutoMLExperiment.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:line 134

**Comment by JakeRadMSFT** [comment]
@Darkne77 did you find a solution?

@lbdalmendray how large is your dataset?

**Comment by lbdalmendray** [comment]
Two images for each label folder ( label A => 2 images , label B => 2 images ). Total was 4 images. Sorry , I did not find a solution.  The images are jpg files .

**Comment by JakeRadMSFT** [comment]
I believe this can happen when the datset is too small. Can you try 10-20 images for each?

**Comment by lbdalmendray** [comment]
@JakeRadMSFT Thanks a lot ! I did it . I used 20 images for each label folder and It works. Solved !

**Comment by JakeRadMSFT** [comment]
Resolving issue! Please re-open if you run into any other issues.

Cheers,
Jake
