### ISSUE TITLE
Cannot parse target values from big dataset (classification 3+)

### ISSUE THREAD

**Issue by PasaOpasen** [dotnet/machinelearning-modelbuilder#727]
**System Information:**
 - Model Builder Version: 16.0.2003.302.
 - Visual Studio Version: Community 16.5.4

**Describe the bug**

It cannot parse target values from big dataset (classification 3+ from 0 to 10, almost 600 000 samples) after than over 30% of samples in normally parsed (by Convert.ToDouble) dataset.

This error begins only after click at "start training" at 3th block.

Training failed with the exception: System.FormatException: Parsing failed with an exception: Could not parse value 3 in line 186170, column open_channels ---> System.InvalidOperationException: Could not parse value 3 in line 186170, column open_channels
   в Microsoft.ML.Data.TextLoader.Parser.ProcessOne(FieldSet vs, ColInfo info, ColumnPipe v, Int32 irow, Int64 line)
   в Microsoft.ML.Data.TextLoader.Parser.ProcessItems(RowSet rows, Int32 irow, Boolean[] active, FieldSet fields, Int32 srcLim, Int64 line)
   в Microsoft.ML.Data.TextLoader.Parser.ParseRow(RowSet rows, Int32 irow, Helper helper, Boolean[] active, String path, Int64 line, String text)
   в Microsoft.ML.Data.TextLoader.Cursor.ParallelState.Parse(Int32 tid)
   в Microsoft.ML.Data.TextLoader.Cursor.ParallelState.ThreadProc(Object obj)

|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |
Could not find input column 'Features'
Имя параметра: inputSchema
Could not find input column 'Features'
Имя параметра: inputSchema
Parsing failed with an exception: Could not parse value 2 in line 186178, column open_channels

**To Reproduce**
Try to make classificator for open_channels column in [this dataset](https://github.com/PasaOpasen/Competitions/blob/master/Ion%20Switching/train%20for%20MLnet.7z)

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! We'll look into what might be causing this issue.

**Comment by luisquintanilla** [comment]
I got the same issue.

I used the following dataset: https://www.kaggle.com/austinreese/craigslist-carstrucks-data

It's sparse and is 1.4 GB. Here is the error and stack trace:

```text
Unrecognized data format. Please check the input file to make sure it is a valid comma or tab separated file.

   at Microsoft.ML.ModelBuilder.DataSources.FileDataSource.GetCorrectDelimiter(String selectedFileName)
   at Microsoft.ML.ModelBuilder.DataSources.FileDataSource.GetListOfColumns(String selectedFileName)
   at Microsoft.ML.ModelBuilder.ToolWindows.DataTabDataContext.GetDataLoadDimensions()
   at Microsoft.ML.ModelBuilder.ToolWindows.TextDataControl.SelectFileButton_Click(Object sender, RoutedEventArgs e)
```

**Comment by beccamc** [comment]
@PasaOpasen Can you please download our new build and try this again? I think this is fixed! https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by beccamc** [comment]
I've tested, and this works on our new build: 16.6.0.  Please download and try it out - https://marketplace.visualstudio.com/items?itemName=MLNET.07. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/f67adc3b-f111-4509-83bb-821fd6a5cc26)

I'm closing this issue. Thank you for reporting!
