### ISSUE TITLE
[loc][Query][mlnet-tools] Localizability of strings

### ISSUE THREAD

**Issue by PDostalek** [dotnet/machinelearning-modelbuilder#728]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Thanks in advance for the reply

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description | Answer Needed By
-- | -- | -- | -- | -- | --
49,204 | mlnet\xlf\Strings.xlf | 0; "GenerateProject" | Generating a console project for   the best pipeline at location | does "the best pipeline at   location " mean the best pipeline deployed or the best pipeline at some   location? |  
49,209 | Microsoft.ML.ModelBuilder\Resources\Strings\xlf\CodeTabResources.xlf | 0;   "AddingProjects" | Adding   Projects | What   does 'adding' mean in this context?     The previous segment is 'Added Projects'.          Does it mean 'to add' or 'is going to add'? |  
49,217 | Microsoft.ML.ModelBuilder\Resources\Strings\xlf\DataTabResources.xlf | 0; "FeaturesLabel" | Features | Is "Feature" in the   below sense?          An attribute of an entity that is used as an input to a machine learning   algorithm.          0; "FeaturesLabel"     0; "ValuePredictionDescription" |  
49,223 | mlnet\xlf\Strings.xlf | 0;   "FurtherLearning" | For   further learning check | This   sentence seems to be incomplete. Please, confirm whether there is something   after "check" |  
49,228 | mlnet\xlf\Strings.xlf | 0;   "VerbosityHelperText" | Output verbosity choices:   q[uiet], m[inimal] (default) and diag[nostic]. | Is any part of these entries   translatable apart from "and"? |  
49,327 | Microsoft.ML.ModelBuilder\Resources\Strings\xlf\NextStepTabResources.xlf | 0;   "Objectexample" | detects   objects (such as boats, people, and sofas) in images and draws bounding boxes   around them. | Does   anything precede this string? We assumed that not for now and translated as   stand-alone string, please advise.                    Similar strings:          detects spikes in shampoo sales.          divides a set of iris flowers into different groups based on the flower's   characteristics.          0; "Objectexample"          0; "Objectexample"          0; "AnomalyExample"          0; "AnomalyExample"          0; "ClusteringExample"          0; "ClusteringExample" |  
49,328 | Microsoft.ML.ModelBuilder\Resources\Strings\xlf\NextStepTabResources.xlf | 0; "ModelCanNotChange" | Since this is just an example,   you can't change any of the details in Model Builder, but you can: | What follows after this string?   Please provide an example/screenshot. |  
49,329 | Microsoft.ML.ModelBuilder\Resources\Strings\xlf\NextStepTabResources.xlf | 0;   "TutorialText" | The   following link will open a tutorial and the complete sample code for | What   follows after this string? Please explain/provide a screenshot. |  
49,343 | Microsoft.ML.ModelBuilder\Resources\Strings\xlf\NextStepTabResources.xlf | 0; "TutorialText" | The following link will open a   tutorial and the complete sample code for | please specify what content   after this sentence. |  
49,344 | Microsoft.ML.ModelBuilder.AutoMLService\xlf\AutoMLServiceResources.xlf | 0;   "BestRunDescription" | Best   {0} metric value is {1} using algorithm {2} and preprocessor {3} | Can   you please explain what will go into the placeholder before   "metric"? We assumed a metric name for now, please advise. |  
49,345 | Microsoft.ML.ModelBuilder.AutoMLService\xlf\AutoMLServiceResources.xlf | 0; "RunIsLabel" | Run is | What follows after "Run   is"? Please provide a screenshot/an example. |

**Comment by beccamc** [comment]
49,204 @LittleLittleCloud

49,209 It is in the process of adding projects. The user clicked "Add projects" and this shows while we do the work of adding the projects. 

49,217 Yes, a feature is an attribute of an entity that is used as an input to a machine learning. 

49,223 Isn't being used and will remove. No translation needed. 

49,228 I believe "Output verbosity choices:" and "and" should be translated. "q[uiet], m[inimal] (default)" "diag[nostic]" should not be translated. @LittleLittleCloud to confirm

49,327 Isn't being used and will remove. No translation needed. 

49,328 Screenshot for context 

![image](https://user-images.githubusercontent.com/9122518/84329330-507bd600-ab39-11ea-817c-be3f91300748.png)

49,329 / 49,343 This is the scenario name (type of ML training that will be done). 

![image](https://user-images.githubusercontent.com/9122518/84329405-7903d000-ab39-11ea-9cbd-df7e0f485772.png)

49,344 Isn't being used and will remove. No translation needed. 

49,345 Run is {status}. E.g. "Run is failed", "Run is completed", etc.

**Comment by PDostalek** [comment]
Thank you @beccamc . Waiting for @LittleLittleCloud

**Comment by LittleLittleCloud** [comment]
49,204 It means the best pipeline at some location, a full path specifically.
49,223 this item is removed. So please just neglect it
49,228 Nope


Thanks @PDostalek

**Comment by PDostalek** [comment]
Thank you
