### ISSUE TITLE
Try parsing files with .txt extension as CSV or TSV

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#73]

**Comment by rustd** [comment]
- Add support for spaces as well "https://github.com/dotnet/machinelearning-samples/issues/417"

**Comment by tbombach** [comment]
The old model builder text parsing code cannot be used for our new Model Builder. The text parsing comes from an old preview version of the Microsoft.ML package (version 0.3.0-preview-26606-1) and is incompatible with the current Microsoft.ML nuget (v1.1). The text parsing/column detection functionality has been removed from Microsoft.ML.Data and moved to the AutoML library.

There is an `InferColumns` method in AutoML. This does what we want - it parses the file, determines if there's a header, what the separator is and what the column names are. However, it has a hard requirement that the label column be provided. This is how it recognizes if there's a header or not and what the separator is (by searching the first line for the label and using that info to determine the separator and if there's a header)

**Comment by tbombach** [comment]
I reached out to sefilipi about this

**Comment by LittleLittleCloud** [comment]
There're so many corner cases if we decided to do inference for users, and the reward and price seem not to match here. do we really HAVE to do that, any suggestion?@ @JakeRadMSFT @rustd @greazer

**Comment by LittleLittleCloud** [comment]
#74

**Comment by greazer** [comment]
@LittleLittleCloud Let's chat about this.

**Comment by LittleLittleCloud** [comment]
@greazer totally

**Comment by greazer** [comment]
The work to try and determine whether a header exists is being tracked by #74.
