### ISSUE TITLE
Scenario page alignment off

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#730]
**System Information (please complete the following information):**
 - Visual Studio Version: VS 16.6 preview 5

**Describe the bug**
Alignment of scenario groups is off:
![image](https://user-images.githubusercontent.com/10437687/81125353-c662a100-8eec-11ea-8b97-43e499bd13ca.png)

**Comment by LittleLittleCloud** [comment]
Validated
