### ISSUE TITLE
Modified 200 column datagrid causes problems for columns not shown

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#737]
Showing only 200 columns is causing problems with column selection and the try it out row

1. Select a column outside of the 200 range and an error is thrown (I thought this list was restricted down to 200 also.) Could solve this by restricting the select list or by modifying the grid.  In TextDataControl.xaml.cs

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/421ebd9a-872c-4318-8717-c227c15a6a70)
2. Error when selecting the Try It Out row. We could fix this by saving a copy of the first 10 rows, but not displaying them in the data grid. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/d6ec85df-fe9a-414e-9a85-bea1705f87aa)

Repro using the data found here - https://github.com/dotnet/machinelearning-modelbuilder/issues/627

**Comment by LittleLittleCloud** [comment]
Validate on EURUSD_60_prepared.zip dataset
https://drive.google.com/uc?id=1e_bP5Pvq3SNpLR4VvynG9x6FFLjAgWrc&export=download
