### ISSUE TITLE
Try to detect CSV/TSV without headers

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#74]

**Comment by JakeRadMSFT** [comment]
#54

**Comment by rustd** [comment]
Parse file with the following data e.g. (This is the same logic as in Model Builder)
	- File types - any text based file e.g. txt, csv, tsv, excel formats
	- Separators
		Supported Options: tab (default), space, comma, new line, colon, semi-colon
	- Quote
		Whether the input may include quoted values, which can contain separator characters, colons, and distinguish empty values from missing values. When true, consecutive separators denote a missing value and an empty value is denoted by "". When false, consecutive separators denote an empty value.
	- Parse files with no headers
		In this case, the col names become "Column0" .. "Column2" .. "ColumnN-1"
		These are the column names a user can select as one of the columns in the "Columns to Predict" dropdown
In the train step, instead of passing in column names to the CLI, you will pass the column index (0,1,…or N-1)

**Comment by tbombach** [comment]
The old model builder text parsing code cannot be used for our new Model Builder. The text parsing comes from an old preview version of the Microsoft.ML package (version 0.3.0-preview-26606-1) and is incompatible with the current Microsoft.ML nuget (v1.1). The text parsing/column detection functionality has been removed from Microsoft.ML.Data and moved to the AutoML library.

There is an `InferColumns` method in AutoML. This does what we want - it parses the file, determines if there's a header, what the separator is and what the column names are. However, it has a hard requirement that the label column be provided. This is how it recognizes if there's a header or not and what the separator is (by searching the first line for the label and using that info to determine the separator and if there's a header)

However,

**Comment by rustd** [comment]
Please reach out to sefilipi who wrote the code for Old Model Builder to get more data as well.

**Comment by LittleLittleCloud** [comment]
Currently, we just consider the situation that all files have header

**Comment by rustd** [comment]
Reopening. We need to support this scenario.

**Comment by greazer** [comment]
@LittleLittleCloud , @rustd is correct. We should try to support this scenario. Just not at the same time as the #73.

**Comment by LittleLittleCloud** [comment]
if (first line doesn't have repetitive column name) => set first line as header
else => using default header

Does that make sense?
@rustd

**Comment by rustd** [comment]
Add options for headers and separators. We will default to something and the user can change it.

**Comment by LittleLittleCloud** [comment]
We may still need some UI to allow users to set the option for parser

**Comment by unescrews** [comment]
I think this is a must for image classification scenarios where features are hundreds or thousands of pixels. Although I generated and added the headers with a line of WinPS code, I see no reason why this wouldn't be supported in future versions. I agree with @LittleLittleCloud .
