### ISSUE TITLE
Image training shows "How long should I train for?"

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#741]
When doing image training "How long should I train for?" is shown. User has no control over how long image data train so this should be removed (or the docs link should talk about image training )

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/55a9e25b-8c96-4c23-a701-aebafa5bf90d)

**Comment by JakeRadMSFT** [comment]
Look into changing text and adding to documentation for Image Training.

**Comment by beccamc** [comment]
This has been open for over 6 months with no action. Closing as low-priority. We can reopen if this comes back up.
