### ISSUE TITLE
Remove check for acceptable file extensions

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-modelbuilder#749]
The CLI & Model Builder have a check for acceptable file extensions:
```
private readonly string[] supportExtensions = new string[] { ".csv", ".tsv", ".txt" };
```

We should remove the check in favor of improving the existing error message. See: https://github.com/dotnet/machinelearning-modelbuilder/issues/748
 
There is no reason for this check and it reduces the functionality of the product.
 
Why it's not needed:
AutoML already sniffs the file to figure out its format, and from that determines if it's readable. And presents an error message if not.
 
Why it reduces functionality:
Many datasets don't have these extensions. For instance datasets named as `dataset.train` & `dataset.test`. Or simply have no extension. When I'm running datasets from a remote fileshare, I generally do not have the ability to rename them to conform to this rule.

**Comment by vzhuqin** [comment]
Validate this issue on:
- dotnet tool list -g
mlnet 16.5.22

- dotnet --version
5.0.202

**Data Set:**
https://testpass.blob.core.windows.net/test-pass-data/taxi-fare.csv

Steps:
If not indicate the file extension in cmd commend, will have error: File does not exist
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/58e502d4-8e9c-4ecf-9571-fe73233af483)

Please help to confirm if the above steps is correct?

**Comment by beccamc** [comment]
@JakeRadMSFT This hasn't been fixed. Should we close and see if any customers ask for this?

**Comment by LittleLittleCloud** [comment]
Isn't the check for file extension deliberately added, even it's not necessary?

And @vzhuqin The test fails because the file does not exist on disk, which is expected. What @justinormont means is that mlnet shouldn't throw an exception when the file extension is not `.csv`, `.tsv` or `.txt`, which mlnet.cli no longer check any more.
