### ISSUE TITLE
Data page - Alignment and restructuring

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#754]
**System Information (please complete the following information):**
 -  Model Builder Version: 16.1.0.2026303
 - Visual Studio Version: 16.7.0 Preview 2 [30107.82.master]

**Describe the bug**
The form for accepting input has a alignment issue, input type dropdown is too long, there's a lot of space between "Select a file" label and the text field, inconsistent input field sizing, and needs restructuring for a better experience.

<img width="1092" alt="Data - Form redesign" src="https://user-images.githubusercontent.com/48927690/82306692-3acd2380-9974-11ea-8ed1-8d0f0e65c84c.png">

**To Reproduce**
1. Go to Model Builder UI
2. Click on Recommendation scenario
3. Go to the Data screen

**Expected behavior**
Needs updated form design that follows UI guidelines and makes the overall experience better. Work with Rohan for new comps.

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
This needs a new spec.

**Comment by romalpani** [comment]
@beccamc I've added this to sprint 172 and we will prioritize it in sprint planning with @JakeRadMSFT and @briacht

**Comment by beccamc** [comment]
Just some feedback on this. I would love if the `Select a file:` box were longer. The amount showing is not useful for me, and I don't think I'm working with unusually long file paths

![image](https://user-images.githubusercontent.com/9122518/84193453-534ecc00-aa50-11ea-8ae5-89eff67e8429.png)
