### ISSUE TITLE
[loc][Query][mlnet-tools] Localizability of strings

### ISSUE THREAD

**Issue by PDostalek** [dotnet/machinelearning-modelbuilder#755]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Thanks in advance for the reply

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description | Answer Needed By
-- | -- | -- | -- | -- | --
49,758 | Microsoft.ML.ModelBuilder\Resources\Strings\xlf\EvaluateTabResources.xlf | 0; "SampleDataHeader" | Sample data | Is sample a noun or a verb? |  
49,987 | mlnet\xlf\Strings.xlf | 0;   "CacheHelperText" | Specify   [On\|Off\|Auto] for cache to be turned on, off, or auto-determined (default). | Is   [On\|Off\|Auto] translatable? Please, confirm. Left as is by now. |  
50,069 | Microsoft.ML.ModelBuilder\Resources\Strings\xlf\CodeTabResources.xlf | 0;   "TrainInAzureCardText" | and get the most out of the   cloud. | What will precede this string?   Is this a continuation of the header, "Train in Azure"? If so, is   it legitimate to make this a independent sentence? A screen would be helpful,   thank you. |  
50,072 | Microsoft.ML.ModelBuilder\Resources\Strings\xlf\CodeTabResources.xlf | 0;   "ImproveModelCardText1" | Check   out | It   assumes that this segment "Check out" (ResID   "ImproveModelCardText1") is followed by "to learn more about   how to use the model in your app." (ResID   "ImproveModelCardText2").                    But in Japanese, the translation of "Check out" should be located   in the last of the sentence.          So should it be "blank"? |  
50,076 | Microsoft.ML.ModelBuilder\Resources\Strings\xlf\CodeTabResources.xlf | 0;   "ImproveModelCardText2" | to learn more about how to use   the model in your app. | It seems that this segment   "to learn more about how to use the model in your app." (ResID   "ImproveModelCardText2") follows "Check out" (ResID   "ImproveModelCardText1").                    In Japanese, verb should be located in the last of sentence.                    So can we add the tranlslation of "Check out" into this segment? |

**Comment by beccamc** [comment]
- 49,758 "Sample" is a noun in "Sample data"
- For 50,069 50,072 and 50,076 we are making a change and I will checkin the strings in their complete form. Can we not translate these for right now? I will checkin the new strings on Thursday or Friday.
- @LittleLittleCloud to comment on 49,987 `Specify [On|Off|Auto] for cache to be turned on, off, or auto-determined (default).`  Is [On|Off|Auto] translatable? Or are those always in English?
 
@PDostalek Please let me know if I should answer these in the grid or another form. Thanks!

**Comment by PDostalek** [comment]
@beccamc  Thanks for your replies. Strings are continuously being translated, please let me know with changes. Thx

**Comment by beccamc** [comment]
@PDostalek  50,069 50,072 and 50,076 are checked in. 

@LittleLittleCloud for 49,987

**Comment by LittleLittleCloud** [comment]
For 49987, it's not, please keep the origin string, thanks

**Comment by PDostalek** [comment]
@beccamc Could you please provide us the whole concatenation of your strings?

**Comment by beccamc** [comment]
50,069 "Train your model in Azure and get the most out of the cloud"
50,072 "Check out our docs to learn how to to improve your model's performance"
50,076 Removed

**Comment by PDostalek** [comment]
THank you
