### ISSUE TITLE
Specified label column 'Sentiment' was not found.

### ISSUE THREAD

**Issue by espahbadi** [dotnet/machinelearning-modelbuilder#756]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment]
Hello,
Sorry you're hitting this issue! Can you please provide more details?

- What version of Visual Studio are you using?
- What version of Model Builder are you using?
- What dataset are you using?
- What scenario did you choose in Model Builder?

**Comment by JakeRadMSFT** [comment]
Closing due to lack of response. Please re-open if you're still hitting this issue!
