### ISSUE TITLE
Model Builder does not start after update on VS2019 16.6.0

### ISSUE THREAD

**Issue by dcostea** [dotnet/machinelearning-modelbuilder#757]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.2003.302
 - Visual Studio Version: 16.6.0

**Describe the bug**
Model Builder does not start after update to the latest version on VS2019 16.6.0.

**To Reproduce**
1. Create a new 'Console App (.NET Core)' application
2. Right Click on the project
3. Click Add->Machine Learning
4. Go to yellow bar below the main menu and click "Enable"
5. Tick the "Use previews of the .NET Core SDK (requires restart)"

**Expected behavior**
After restarting the VS2019 I expect to be able to open the Machine Learning wizard interface, but the yellow bar keeps showing.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/15055082/82393425-9cf65900-9a46-11ea-93a4-a2a418761043.png)
![Untitled2](https://user-images.githubusercontent.com/15055082/82393434-a253a380-9a46-11ea-9524-0f931dc1d5e0.png)

**Additional context**
I have tried to uninstall/install the Model Builder extension but no success. I tried to start VS2019 as admin but no success either. Now I cannot use Model Builder no matter what I do.
**_Later edit:_** I tried to uninstall/install using individual components, but still no success.

**Comment by aslotte** [comment]
I'm having the same issue and re-starting the computer doesn't help neither

**Comment by LittleLittleCloud** [comment]
@aslotte  @dcostea Can I have the catalog.json and extension.vsixmanifest file under ModelBuilder folder? Those files should locate under `Your\VS\InstallPath\{Enterprise or Comunity}\Common7\IDE\CommonExtensions\Microsoft\ModelBuilder`.

**Comment by rogreen** [comment]
@LittleLittleCloud I don't even get that far. I checked Use Previews of the .NET Core SDK, but when I right-click Add I don't see a Machine Learning option. I do not have a ModelBuilder folder in CommondExtensions\Microsoft. Other than 16.6, what are the prereqs for this?

**Comment by aslotte** [comment]
@LittleLittleCloud I hope this helps
[Issue_757.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4658180/Issue_757.zip)

**Comment by LittleLittleCloud** [comment]
> @LittleLittleCloud I don't even get that far. I checked Use Previews of the .NET Core SDK, but when I right-click Add I don't see a Machine Learning option. I do not have a ModelBuilder folder in CommondExtensions\Microsoft. Other than 16.6, what are the prereqs for this?

Did you select the Install ModelBuilder checkbox in VS installer when upgrading?
![image](https://user-images.githubusercontent.com/16876986/82479655-87edea00-9a87-11ea-9810-a7b0c0f92e7e.png)

**Comment by LittleLittleCloud** [comment]
> @LittleLittleCloud I hope this helps
> [Issue_757.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4658180/Issue_757.zip)

Thanks! We are looking into this.

**Comment by rogreen** [comment]
@LittleLittleCloud So now I get the same behavior decostea reported. Here are my 2 files in case that helps beyond the ones you already got. 
[rogreen_issue757.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4658555/rogreen_issue757.zip)

**Comment by beccamc** [comment]
@rogreen @aslotte @dcostea We're working on getting this fixed. In the meantime I've tested a workaround that should fix the problem. 

1. You need to install this Feature Flag management [extension](https://marketplace.visualstudio.com/items?itemName=PaulHarrington.FeatureFlagsExtension). 

2. Then go to Tools -> Options -> Environment -> Feature Flags and enable `ModelBuilder.Enable`
![image](https://user-images.githubusercontent.com/9122518/82486461-bbce0d00-9a91-11ea-935c-4a5cfa443a9d.png)


Sorry for the inconvenience! This isn't ideal but hopefully it can unblock you while we work on getting a fix in.

**Comment by aslotte** [comment]
@LittleLittleCloud I didn't do it in conjunction with the upgrade:
- I first upgraded
- I then went into Visual Studio Updated -> Individual Components and installed the preview of the Model Builder

**Comment by aslotte** [comment]
@beccamc thank you! I can confirm that the workaround worked perfectly 🥇

**Comment by dcostea** [comment]
I confirm, too!
So good to see the model builder is back ;)

**Comment by dcostea** [comment]
> @LittleLittleCloud I didn't do it in conjunction with the upgrade:
> 
> * I first upgraded
> * I then went into Visual Studio Updated -> Individual Components and installed the preview of the Model Builder

On the other side, I have removed the Model Builder extension and then I have added back before the issue occurred. I didn't have the chance to try installing via individual components.

**Comment by ashalogic** [comment]
> @rogreen @aslotte @dcostea We're working on getting this fixed. In the meantime I've tested a workaround that should fix the problem.
> 
> 1. You need to install this Feature Flag management [extension](https://marketplace.visualstudio.com/items?itemName=PaulHarrington.FeatureFlagsExtension).
> 2. Then go to Tools -> Options -> Environment -> Feature Flags and enable `ModelBuilder.Enable`
>    ![image](https://user-images.githubusercontent.com/9122518/82486461-bbce0d00-9a91-11ea-935c-4a5cfa443a9d.png)
> 
> Sorry for the inconvenience! This isn't ideal but hopefully it can unblock you while we work on getting a fix in.

Thanks 😊👍

**Comment by rogreen** [comment]
Works for me too. Thanks @ashalogic and @beccamc

**Comment by beccamc** [comment]
Using **VS version 16.7 Preview 1** will also work. It's only broken in the 16.6 version.

**Comment by thackman7** [comment]
I'm having the same issue with v16.6.  
When i dig into the logs on disk (C:\Users\{username}\AppData\Local\Temp\servicehub\logs)  
I'm getting this error msg:

05/20/2020 18:02:50 Eastern Standard Time : Error : Error creating Microsoft.ML.ModelBuilder.AutoMLService.AutoMLService instance of CLR service module 'MicrosoftMLModelBuilderAutoML': 
System.IO.FileLoadException: Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401) HResult='-2146233343' 
   at Microsoft.ML.Runtime.ComponentCatalog..ctor()

I'm also seeing an error in the event log.
Application: ServiceHub.Host.CLR.x64.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.ML.ModelBuilder.AutoMLEngine.Dispose()
   at Microsoft.ML.ModelBuilder.AutoMLEngine.Finalize()

**Comment by JakeRadMSFT** [comment]
@thackman7 I think that's a different bug. It was supposed to be a very rare bug (super edge case in the .NET Framework) - https://github.com/dotnet/machinelearning-modelbuilder/issues/267

If you hit it consistently, I can reach out the .NET Team again for a deeper investigation.

**Comment by kitron** [comment]
Works for me too. Thanks!

**Comment by dcostea** [comment]
Maybe this should stay open until the issue is fixed in VS.
