### ISSUE TITLE
   em Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext()

### ISSUE THREAD

**Issue by OlimiroLuiz** [dotnet/machinelearning-modelbuilder#758]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by JakeRadMSFT** [comment]
Hello,
Thanks for reporting this issue. In order to help, I need more information.

Can you share the following details:

Visual Studio Version
Model Builder Version
What scenario type did you run?
Can you share the dataset or information about it?

Cheers,
Jake

**Comment by beccamc** [comment]
@OlimiroLuiz Sorry you've run into an error! Can you provide answers to the questions above?

**Comment by beccamc** [comment]
Unfortunately we don't have enough information to investigate this issue. If you're still seeing a problem, please re-open and provide additional information. Thanks for reporting!
