### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#759]
![image](https://user-images.githubusercontent.com/10437687/82467221-49036880-9a76-11ea-8d48-bfe735325a49.png)

https://twitter.com/ShahidDev/status/1263055963604598784?s=20

**Comment by beccamc** [comment]
Fixed! ![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/144c3276-340f-46c2-b08b-5a1f03e6c5b7)
