### ISSUE TITLE
[Functional Spec] Improve Code Generation

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#76]
The generated code should be easily consumable from an existing .NET app for Console, Web, Desktop, WPF etc and should work for .NET Core (p0) and .NET FX (p1).

Here is a rough description.
When a user selects Add Projects, several things happen:
1.	[no change] The button to Add Projects is disabled, and the text changes to “Added Projects”
2.	A .NET Core class library project ([projectName]ML.Model) is added to the solution, which contains the following files:
o	[New] ConsumeModel.cs (model consumption code) with 4 methods for each apptype
o	DataModels folder, with ModelInput.cs and ModelOutput.cs
o	MLModel.zip (serialized model)
3.	[removed] The Microsoft.ML NuGet package is added to the user’s project.
4.	[removed]A reference to the generated library project is added to the user’s project.
5.	[New]The MLModel.zip Copy to Output Directory Property is set to “Always”
7.	[Update existing logic] The “Next Steps” section appears, which has the following text (customized for each apptype):
o	 1. To consume the trained model in your project, 
o	e.g. Call ConsumeModel.ConsumeForWeb() if launched from WebApp or Call ConsumeModel.ConsumeForDesktop() if launched from Desktop app
8. [New ]p1 - Don't generate ([projectName]ConsoleApp) and move ModelBuilder.cs (model training code) to class library

Error Cases
o	If the user’s project already has the most updated ML.NET package, then do not try and add package.
o	If the user’s project already has an older version of ML.NET package, then prompt user that they should update; if they say yes to update, then update to newest version. If say no, do nothing.  
o	Prompt: “You are using an old version of ML.NET (v0.9.0). Would you like to update to the newest version of ML.NET (v1.0.0)?”

**Comment by briacht** [comment]
Spec: https://microsoft-my.sharepoint.com/:w:/p/brachtma/EVOoEe-O5xFOt-HZg8T_nbMB-Z9Bgigk_c_VWIC2KF5oDg?e=VOAilU

**Comment by LittleLittleCloud** [comment]
I can take a look at 3 and 4 (automatically add Microsoft.ML and reference to generated project)

**Comment by LittleLittleCloud** [comment]
Finally start working on this!!!!!

- [ ] add *consuming* method
