### ISSUE TITLE
bug in try it out with classification dataset

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#760]
Version from most recent bug bash

Using this mushroom dataset: https://www.kaggle.com/uciml/mushroom-classification

When I try out the model, I get this error for the bruises column:

![image](https://user-images.githubusercontent.com/10437687/82613411-12167b00-9b7a-11ea-8ae4-b6c1838ca804.png)

If I change t to f, it works, but then I get error for another cap_shape column (I'm guessing it has to do with the dash vs. underscore?):

![image](https://user-images.githubusercontent.com/10437687/82613557-691c5000-9b7a-11ea-8e94-602b9f04c4db.png)

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud Can you help investigate this?

**Comment by LittleLittleCloud** [comment]
bruise is infered as boolean value, therefore it only accept "true/false" will fix that

**Comment by LittleLittleCloud** [comment]
Just test it and it seems that advanced option has already fixed this bug, cheers

**Comment by JakeRadMSFT** [comment]
Throws an exception for me now.
