### ISSUE TITLE
bug in train - incorrect models explored

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#761]
![image](https://user-images.githubusercontent.com/10437687/82613815-29a23380-9b7b-11ea-9de5-4b6ddd53e8cc.png)

**Comment by beccamc** [comment]
This is fixed! ![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/2846a980-2486-448d-8ba5-5ab005362e9e)
