### ISSUE TITLE
unable to consume trained modelset

### ISSUE THREAD

**Issue by ssriram30** [dotnet/machinelearning-modelbuilder#762]
please help to solve
![Screenshot_22](https://user-images.githubusercontent.com/13566196/82643375-046dfd80-9c2d-11ea-9546-d0172efe5b26.png)
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows
Visual studio 2017

**Comment by JakeRadMSFT** [comment]
What type of project are you trying to consume the model from? Is it full framework or .NET Core/.NET Standard?

**Comment by ssriram30** [comment]
I try to consume from .net framework 4.6.1 (Console application) @JakeRadMSFT

**Comment by ssriram30** [comment]
The issue not happened in .net core . it happens only on .net standard.

Refer : https://github.com/dotnet/machinelearning-modelbuilder/issues/422.

So now i close this issue.
