### ISSUE TITLE
Model Builder Errror 

### ISSUE THREAD

**Issue by bipindra** [dotnet/machinelearning-modelbuilder#763]
**System Information (please complete the following information):**
 - Model Builder Version:  The latest one available to download on 5/21/2020
 - Visual Studio Version : 2019 Professional

**Describe the bug**
On step 3 when i click start training, it throws error saying Specified label column e.g 'Sentiment' was not found. I tried with other sample csv, tsv and scenarios all of them threw same error. 

**To Reproduce**
1. Go to Model Builder from right click console app project , add Machine Learning 
2. Click on Scenario, then click on select a file, select wikipedia sentiment analysis sample file "wikipedia-detox-250-line-data.tsv"
3. Select column to predict "Sentiment"
4. Click on Train
3. It goes to step 3. Click on Start Train. 

**Expected behavior**
Not see any error.

**Screenshots** 
![image](https://user-images.githubusercontent.com/1760954/82672740-bea23c80-9c0e-11ea-8ceb-1ac477308dca.png)

**Additional context**
Above issue is with all sample files and database connection. I could not get this to work at all.

**Comment by JakeRadMSFT** [comment]
Hello, 
Thanks for reporting this issue. We have a new version that will be release this week but I'll investigate why you might be hitting it for the last release. 

Would you be open to seeing if this reproduces with a Beta build?

Cheers,
Jake

**Comment by bipindra** [comment]
Yes sure I will try beta build. Thank you.
 Where can I find it?

**Comment by JakeRadMSFT** [comment]
@bipindra sorry I missed your message! We've since released the build ... can you try the latest?

**Comment by JakeRadMSFT** [comment]
@bipindra resolving this issue due to lack of activity. 

If you're still hitting this issue - please re-open! I'm unable to reproduce with the wikipedia dataset.

Cheers,
Jake

**Comment by bipindra** [comment]
![Senti](https://user-images.githubusercontent.com/1760954/85877205-c96b6680-b7a4-11ea-90a3-b7bb601a9b1e.gif)

**Comment by Vectorfield4** [comment]
Still reproduced.
![image](https://user-images.githubusercontent.com/47894313/97510706-fc5d7b00-198d-11eb-83d2-154623f73187.png)
VS Community 2019 v16.6.7
