### ISSUE TITLE
Enable ML.NET Model Builder is not in Preview Features (VS16.6)

### ISSUE THREAD

**Issue by paradisehuman** [dotnet/machinelearning-modelbuilder#764]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.0.2026302
 - Visual Studio Version: 16.6

**Describe the bug**
Hi, I have upgraded my vs to 16.6. There isn’t any “Enable ML.NET Model Builder” in Preview Features for enabling it.

**To Reproduce**
1. Go to Tools
2. Click on Options
3. Click on Preview Features

**Expected behavior**
Seeing "Enable ML.NET Model Builder"

**Screenshots**
![image](https://user-images.githubusercontent.com/5645699/82687170-32266700-9c6c-11ea-8df9-c019b34aaed5.png)

**Comment by devenchawlayyc** [comment]
I have the same issue. Please fix this.

**Comment by ababilone** [comment]
Hi, Same over here.
Visual Studio 16.6 as well.

**Comment by attrib75** [comment]
Same here VS 16.6.0

**Comment by AndrewPetz** [comment]
I was able to fix this issue by uninstalling the "ML.NET Model Builder (Preview)" extension and installing it again.

**Comment by paradisehuman** [comment]
> I was able to fix this issue by uninstalling the "ML.NET Model Builder (Preview)" extension and installing it again. After re-installing, I did not get the popup to enable the preview feature when I tried to add Machine Learning to my project.

It's not worked for me.

**Comment by elamey** [comment]
Ditto... doesn't show and un-install/re-install doesn't work

**Comment by attrib75** [comment]
Not sure how to uninstall the "ML.NET Model Builder (Preview)"

**Comment by paradisehuman** [comment]
> Not sure how to uninstall the "ML.NET Model Builder (Preview)"

Run VS installer and select modify then Individual components. But it doesn't work.

**Comment by jernejk** [comment]
Hi, I had a similar problem before with Visual Studio 2019 16.6 Preivew 4 but this is a different issue.
You don't have to uninstall (unless you had it installed previously) but you might not have (unknowingly) installed it.

If it doesn't work at all, I have tried several things and it didn't work, including the below.

There are 2 workarounds:
1. Use Visual Studio 2019 16.7 Preview 1, it works perfectly
2. Uninstall (instructions below) and install the old extension https://marketplace.visualstudio.com/items?itemName=MLNET.07 

Obviously, if you want to have the latest features and you can't get it working with VS 2019 16.6, 16.7 Preview 1 is the second-best thing.

1. Run Visual Studio Installer
2. Modify 
3. Individual Components
4. Enter "Model Builder" in Search components
5. Check "ML.NET Model Builder (Preview)"
6. Modify (-275MB)

And to install it back, repeat the same thing:
1. Run Visual Studio Installer (already running if you followed previous steps)
2. Modify 
3. Individual Components
4. Enter "Model Builder" in Search components
5. Check "ML.NET Model Builder (Preview)"
6. Modify (360MB)

![image](https://user-images.githubusercontent.com/5943653/82814168-eda00300-9ed9-11ea-803f-30950e23a4a1.png)
**Figure: Modify Visual Studio 2019 16.6**

![image](https://user-images.githubusercontent.com/5943653/82813311-2343ec80-9ed8-11ea-8dac-fea56fe0b80f.png)
**Figure: Model Builder**

![image](https://user-images.githubusercontent.com/5943653/82814430-86368300-9eda-11ea-9c3d-ad1a947d251c.png)
**Figure: No matter what I do, it's not there.**

![image](https://user-images.githubusercontent.com/5943653/82814852-4d4ade00-9edb-11ea-88ec-92603b66fcd9.png)
**Figure: You can install the old extension if the built-in one doesn't work, just uninstall Model Builder in Visual Studio Installer.**

**Comment by danieldamianov** [comment]
Same VS 2019 16.6

**Comment by monarqueje01** [comment]
Same VS 2019 16.6
try All above and nothing work..

**Comment by jernejk** [comment]
@monarqueje01, as mentioned above, this is the old version of Model Builder.
Use it if you really want to use Model Builder and you don't mind using the old version.

There are 2 major features you won't be able to access (aside from nicer look):
- Significantly improved image classification
- Recommendations

This will probably be fixed by 16.6.1 or if you want to test these features try these workarounds (they didn't work for me):
* https://twitter.com/alexslotte/status/1263187069125431297
* https://github.com/dotnet/machinelearning-modelbuilder/issues/757

**Comment by JakeRadMSFT** [comment]
Apologies for this issue. We had a bug that only showed up in the release versions of VS. You can try out 16.7 Preview 1 or any of the 16.6 previews and it'll work. 

This will be fixed in 16.6.1 which should go out this week.

**Comment by JakeRadMSFT** [comment]
Also thanks @jernejk for helping people out! <3 the community involvement!

**Comment by aslotte** [comment]
Thanks all!

**Comment by JakeRadMSFT** [comment]
Fix will go out with 16.6.1 which is now targeting Monday.

**Comment by JakeRadMSFT** [comment]
Thanks for your patience! We've fixed this issue in VS 16.6.1 and that went out today. Please update and you should see that this issue has been resolved. If you're stilling having any issues, don't hesitate to reach out again!

Thanks for using Model Builder!

Cheers,
Jake

**Comment by jernejk** [comment]
Just want to confirm that it seems to be working :)
