### ISSUE TITLE
Training time finished without any models trained.

### ISSUE THREAD

**Issue by IlyaSelivanov** [dotnet/machinelearning-modelbuilder#765]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.2003.302
 - Visual Studio Version: Microsoft Visual Studio Community 2019, Version 16.5.5

**Describe the bug**
Training time finished without any models trained.

 at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\Experiments\AutoMLExperiment.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:line 134

**Preconditions**
1. Obtain train data from https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification

**To Reproduce**
1. Go to project right-click context menu;
2. Click on 'Add -> Machine Learning';
3. Select 'Issue Classification' scenario;
4. Set all necessary options;
5. Train model;

**Expected behavior**
Model trained, code generated

**Screenshots**
![image](https://user-images.githubusercontent.com/4151459/82736623-e0491400-9d33-11ea-90e9-d59a85818e1e.png)

**Comment by justinormont** [comment]
@IlyaSelivanov: You'll want a longer runtime. 

## Internal work
I'd recommend:
* Making the error message actionable by expand the error message to: "Training time finished without any models trained. Try increasing the runtime." 
* Increase the default runtime from 10 sec to at least 60 seconds. The current 10 seconds is too low for almost any dataset. Users should be aiming at 120-150 models created.
* Add checkbox for "create at least one model", and don't expire the run until the 1st model is created.
* Notify users if runtime is too low (after running): if they train <80 models, extrapolate how long it would take to run 150 models and recommend the user uses the estimated time for the next run.

**Comment by IlyaSelivanov** [comment]
@justinormont : Train time increasing solved this issue. Thank you.
