### ISSUE TITLE
Model Builder Error: unable to infer column types of the file provided

### ISSUE THREAD

**Issue by BMaj7** [dotnet/machinelearning-modelbuilder#767]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.2003.302
 - Visual Studio Version 2019 16.5.5

**Describe the bug**
ML.NET model builder crashes when trying to perform image training.

**To Reproduce**
1. Go to 'Project' in Solution Explorer
2. Right-Click on it
3. Click 'Add' and select  "Machine Learning"
4. Select Secnario "Image Classification"
5. Select a folder structure as described and click "Train"
6. Select "Local" and click "Start training"

**Expected behavior**
Image Training starting

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/65890356/82791045-59985200-9e6d-11ea-8e1c-3a59d32104e9.png)

**Additional context**
Images are structured in labeled subfolders in jpg format (5472 x 3648 pixel) as requested.

**Comment by BMaj7** [comment]
This issue may be related to spaces or brackets in file names used for training. After removing these, the issue is gone.

I recommend to implement name checkig and throwing a verbose exception that explains it better.

**Comment by justinormont** [comment]
@BMaj7 : Do you have an example of a filename which fails?

**Comment by BMaj7** [comment]
The filename structure was
img00 (xx).jpg

In case this helps as well: there have been also bitmaps (*.bmp) inside the folder with the same name.
