### ISSUE TITLE
Add Machine Learning option is not available in Visual Studio Community Preview 16.7.0 Preview 1

### ISSUE THREAD

**Issue by subhankars** [dotnet/machinelearning-modelbuilder#769]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

Microsoft Visual Studio Community 2019 Preview
Version 16.7.0 Preview 1.0
VisualStudio.16.Preview/16.7.0-pre.1.0+30114.128
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA332
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.7.157.11481
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2022804+66630a71f38744d343d39dca467706a5992dfb57
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.157.11481
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.157.11481
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.7.157.11481
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.6000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.7.0-1.20257.3+4b5650e58ee947f283ec098c133c9ffd86b18744
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.6000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.6000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.6000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30415.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62005.01040
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20430.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-1.20257.3+4b5650e58ee947f283ec098c133c9ffd86b18744
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20220.1+42cfdac02bb6d5e18d03aa986f9339d716dd62f3
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

**Describe the bug**
Unable to add Machine Learning Model Builder in .NET project. Add Machine Learning option is not available in Visual Studio Community Preview 16.7.0 Preview 1

**To Reproduce**
1. From Option >> Preview feature >> Enabled ML Model builder option
2. Right Click on the .NET project 
3. Add
4. Machine Learning Option is not available 

**Expected behavior**
Add Machine Learning option should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/17920161/82820988-dd2f5e80-9ec0-11ea-9857-7eef93ff5460.png)

**Comment by jernejk** [comment]
It seems to be a similar problem as #764 but at least for me, it worked on 16.7 Preview 1 but not in 16.6. Do you have 16.6 and if yes, does it work there?

**Comment by subhankars** [comment]
I know now why it was not working. We have to manually install the model builder from VS Installer
![image](https://user-images.githubusercontent.com/17920161/82861929-dd207480-9f3b-11ea-8402-c4b62175b804.png)
Now I can see it. Closing the issue.

**Comment by JakeRadMSFT** [comment]
Thanks for your patience! We've fixed this issue in VS 16.6.1 and that went out today. Please update and you should see that this issue has been resolved. If you're stilling having any issues, don't hesitate to reach out again!

Thanks for using Model Builder!

Cheers,
Jake
