### ISSUE TITLE
[Functional Spec] Add Recommendation Scenario

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#77]
A user wants to add recommended products to user's to based on popular items in their eCommerce store.

Here are the steps a user can take

Launch MB
Scenario
--- Choose Recommendation template
Data
--- Connect to Files/ SQL for accessing data (Single file and single table for now)
--- Choose Label
--- Choose features (e.g. user id/ product id). Show error's if user's select more than 3 which is not allowed for recommendation
--- Preview data in MB
Train
--- by specifying training time. Same datasize heuristics apply as before
--- Training code will be the ML.NET pipeline code
--- The progress window can just show training time, best algorithm, last algo
--- [Existing behavior] If training time finishes and no model found, then no model returned to user.
Evaluate 
--- model my seeing results summary (same as before in Output section) and details on model performance (Top 1 model explored - table of summary of metrics as we have today.)
Code
--- generate model training/ consumption code.

**Model Training and Consumption code**
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MatrixFactorization_MovieRecommendation

# Code changes
- This would involve copying the C# code from the CLI that generates code for the user and including it in model builder

**Comment by tbombach** [comment]
FYI, this is the sample repo: https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MatrixFactorization_MovieRecommendation
