### ISSUE TITLE
Model Builder 'Try your model' yields no results

### ISSUE THREAD

**Issue by EchoNBounce** [dotnet/machinelearning-modelbuilder#771]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.2003.302
 - Visual Studio Version: 16.5.4

**Describe the bug**
After successfully training a regression model, clicking the Predict button under 'Try your model' on the Evaluate tab has no effect. A spinner is briefly shown in the Results pane but nothing appears. For me, this happened whether I used the pre-populated row 1 sample data or any other data I entered. It occurred over multiple independent runs of Model Builder. In all cases, however, the generated model worked fine (e.g. I could use the codegen console app to generate predictions.)

**To Reproduce**
1. Go to Model Builder and choose a Custom Scenario.
2. Add data by selecting a CSV-based file source with an integer-valued label and multiple categorical/numeric features.
3. Train a regression machine learning task.
4. Go to evaluate the model and click the Predict button.

**Expected behavior**
Click the 'Predict' button in the 'Try your model' feature displays the model output for the configured parameters.

**Comment by beccamc** [comment]
Thanks for reporting @EchoNBounce! Are you in VS dark theme?

**Comment by EchoNBounce** [comment]
I am yes. Thanks for following up.

**Comment by beccamc** [comment]
Did this resolve the issue for you @EchoNBounce?

**Comment by beccamc** [comment]
This should be a bug relating to dark theme in an older Model builder version. Try changing themes or updating to resolve. Feel free to reopen if you need additional help!
