### ISSUE TITLE
Problem adding Machine Learning VS 2019 Enterprise

### ISSUE THREAD

**Issue by adebie** [dotnet/machinelearning-modelbuilder#778]
Hello,
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
When I try to add Machine Learning, I always receive a message "Would you like to enable the ML.NET Model Builder preview feature so you can add Machine Learning to your .NET projects? Enable".
![image](https://user-images.githubusercontent.com/42832630/83196166-b29d0a00-a13b-11ea-88ea-10abbaf6f41f.png)

When I the click on Enable, I receive the Options menu 
![image](https://user-images.githubusercontent.com/42832630/83196279-e8da8980-a13b-11ea-873d-9690d45a6264.png)

Clicking either on OK or Cancel does not show the ML scenario chooser.

Maybe I missed something...
Thanks for you help,

Alain.

Here are the technical installation details :
Microsoft Visual Studio Enterprise 2019
Version 16.6.0
VisualStudio.16.Release/16.6.0+30114.105
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

AnkhSVN2019   1.00.0.0009
AnkhSVN2019 - Subversion Support for Visual Studio

ASP.NET and Web Tools 2019   16.6.936.3669
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   16.6.936.3669
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.6.936.3669
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.936.3669
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.6.936.3669
Azure Functions and Web Jobs Tools

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.11.96.24460
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62004.28040
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by JakeRadMSFT** [comment]
Sorry you're hitting this issue:
Please see #764

**Comment by JakeRadMSFT** [comment]
Thanks for your patience! We've fixed this issue in VS 16.6.1 that went out today. Please update and you should see that this issue has been resolved. If you're stilling having any issues, don't hesitate to reach out again!

Thanks for using Model Builder!

Cheers,
Jake

**Comment by adebie** [comment]
Sorry for my late answer... I was away from my computer for a few days.
Thanks for your feedback. I updated my installation of VS to release 16.6.1 and it's working.
Alain.
