### ISSUE TITLE
ml module prediction returns 1 instead of true

### ISSUE THREAD

**Issue by OrShazam** [dotnet/machinelearning-modelbuilder#779]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment]
@OrShazam we've updated our documentation to match the behavior.

We made a change to return values of the same type as the training data. We used to convert 0/1 to false/true but it was confusing in some circumstances.

Please re-open if this explanation doesn't resolve the issue!

Cheers,
Jake
