### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train Operating System: windows

### ISSUE THREAD

**Issue by sgajendra237** [dotnet/machinelearning-modelbuilder#782]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Note: I am using vs2019 and OS win 10 32 bit

Please provide solution.

![err](https://user-images.githubusercontent.com/66199503/83350859-e7ec5800-a2f3-11ea-80b9-929b2edd7a9f.PNG)

**Comment by JakeRadMSFT** [comment]
Unfortunately 32bit isn’t supported. Some of the libraries we use require 64bit.

Do you have a 64bit machine you could try it on?

**Comment by sgajendra237** [comment]
Thanks Jake

**Comment by JakeRadMSFT** [comment]
Of course! Hopefully you have a 64 bit machine you can use!
