### ISSUE TITLE
Build errors when I try to run myMLapp

### ISSUE THREAD

**Issue by lanarosenthal** [dotnet/machinelearning-modelbuilder#783]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows
VS 16.7

1>------ Build started: Project: ConsoleApp2ML.Model, Configuration: Release Any CPU ------
1>C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file 'C:\Users\Lana Rosenthal\source\repos\ConsoleApp2\ConsoleApp2ML.Model\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>Done building project "ConsoleApp2ML.Model.csproj" -- FAILED.
2>------ Build started: Project: ConsoleApp2ML.ConsoleApp, Configuration: Release Any CPU ------
2>C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file 'C:\Users\Lana Rosenthal\source\repos\ConsoleApp2\ConsoleApp2ML.ConsoleApp\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
2>Done building project "ConsoleApp2ML.ConsoleApp.csproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by beccamc** [comment]
Sorry you've run into this problem @lanarosenthal and thanks for reporting! Can you try to restore packages following the instructions [here](https://docs.microsoft.com/en-us/nuget/Consume-Packages/Package-restore-troubleshooting#assets-file-projectassetsjson-not-found)?

**Comment by beccamc** [comment]
@lanarosenthal Any luck with the above?

**Comment by beccamc** [comment]
Unfortunately we don't have enough information to investigate this issue. If you're still seeing a problem, please re-open and provide additional information. Thanks for reporting!
