### ISSUE TITLE
Newtonsoft doesn't work for VS 2017

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#784]
We need to reference Newtonsoft from the Model Builder project. To safely do this for 2017, we need to remove indirect references to newtonsoft. Currently that is 

- Prose library 
- WindowsAzure.Storage

Both of these need to move to Service Hub.

**Comment by beccamc** [comment]
Also look at adding a gold bar to warn 2017 support will be discontinud soon

**Comment by JakeRadMSFT** [comment]
Related: #592
