### ISSUE TITLE
[Implementation] Add Image Classification Scenario

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#79]
This enables users to do add Image classification to their e-commerce site. A user can upload an image and classify the category of image e.g. cat vs dog or jeep vs land-rover. This does transfer learning on Inceptionv3

Here are the steps a user can take
- Launch MB
- Choose Image classification template
- Upload folders (image files) from disk/ (User has already labelled images into folders)
--- Upload fails if (min # of images/ per label is < 20)
- Preview images in MB
- Train model by specifying training time
--- Training code will be the ML.NET pipeline code and use transfer learning to train last layer
--- The progress window can just show training time, best algorithm
- Evaluate model my seeing results summary (same as before in Output section) and details on model performance (Top 1 model explored - table of summary of metrics as we have today.)
--- This will have only one model since we will use Inception and do transfer learning on last layer.
- Code - generate model training/ consumption code.

Future
--- SQL (image data or path)
--- Select tags to classify images into (future)
--- Test screen to live test the model (future)

**Model Training and Consumption code**
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator

**Comment by beccamc** [comment]
Open UI issues: 
- Image icon
- Warning for 0 files in folder
- Spinner for loading images
- Image should be fixed width (not stretch on small screen)

**Comment by beccamc** [comment]
Moved all info to the associated Epic. Closing this issue
