### ISSUE TITLE
Make Pipeline Serializable

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#792]
The pipeline class in AutoML is not serializable, because its Properties is of type `Dictionary<string, object>`, which means it can be serialized to json, but when deserializing, some information might be lost because it doesn't save any type info.

The missing ability of serialization blocks the implementation of re-entrancy for "add to project" experience. The "add to project" is implemented using Microsoft.ML.CodeGenerator, which uses pipeline and column inference result as input, and a C# project as output. To generate the code to recreate pipeline, Microsoft.ML.CodeGenerator has to use pipeline.Properties to get the hyperparameter of estimators. And because some hyperparameter is not primitive type, so its type information will be lost when serialized to json, and unable to restore back when deserializing.

One solution to this is by adding a `SerializedProperties` property to pipeline, with type `Dictionary<string, string>`. The key of `SerializedProperties` will be the properties' name, and its value will be **the code on how to create it**, which is of string type and can be directly used by Microsoft.ML.CodeGenerator. Through this there's no longer necessary to record the type information of properties, and all the information required by Microsoft.ML.CodeGenerator will be able to persist.

**Comment by justinormont** [comment]
Side note: This path can also lead to resumable AutoML runs. 

In the future, if we in-turn make the [pipeline runner](https://github.com/dotnet/machinelearning/tree/f87a3bbd8adb12934dae0a0060813ce9b7500664/src/Microsoft.ML.AutoML/Experiment/Runners) external to the main process, it can provide robustness to crashes, safer memory management, local parallelism, and further in the future distributed pipeline runs on clusters.
