### ISSUE TITLE
Error case handling - Bad state file

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#793]
- [x] Invalid Json - completely incorrect json (e.g. someone replaces with text file)
- [ ] Incomplete or incorrect objects - missing fields from objects, or extra unnecessary fields

**Comment by beccamc** [comment]
Doing the bare minimum for this. Won't crash VS process and hopefully we'll show something helpful to the customer for fixing it.

**Comment by vzhuqin** [comment]
@LittleLittleCloud  could you help to provide more details to validate this issue? on which Scenario? Environment? Data? or repro steps?

**Comment by JakeRadMSFT** [comment]
Closing issue this was just used for tracking. Design team is looking into long term fix.
