### ISSUE TITLE
has-header inference incorrect in new version of cli

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#798]
CLI 16.6.1 -- not detecting the correct has-header

Used the yelp_labelled dataset from: https://archive.ics.uci.edu/ml/datasets/Sentiment+Labelled+Sentences 

![image](https://user-images.githubusercontent.com/10437687/83672968-fc4a8200-a58b-11ea-8489-98439167d857.png)

And got this warning even though it does not have a header -- shouldn't be getting this warning:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/10437687/83673024-12f0d900-a58c-11ea-8179-a35157f2709d.png)

**Comment by briacht** [comment]
@beccamc

**Comment by beccamc** [comment]
This is working, no longer showing "no-header" message

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/794125e5-cf2e-4ab8-a113-c00e20194173)
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/53b62c79-5028-40b2-b613-bb93ef676d84)
