### ISSUE TITLE
[CLI] Add Image Classification Scenario

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#80]
This enables users to do add Image classification to their e-commerce site. A user can upload an image and classify the category of image e.g. cat vs dog or jeep vs land-rover.

Here are the steps a user can take

Launch CLI
Choose Image classification task with the following options
File path to  disk (User has labelled images into folders)
--- Upload fails if (min # of images/ per label is < 20)
--- Select tags to classify images into (future)
Train model by specifying training time
--- Training code will be the ML.NET pipeline code and use transfer learning to train last layer
--- The progress window can just show training time, best algorithm
Evaluate model my seeing results summary (same as before and details on model performance (Top 1 model explored - table of summary of metrics as we have today.)
--- This will have only one model since we will use Inception and do transfer learning on last layer.
Code - generate model training/ consumption code.

Model Training and Consumption code
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator

**Comment by LittleLittleCloud** [comment]
@briacht 
Can you help update document please

**Comment by beccamc** [comment]
This is shipped and bashed. Closing.
