### ISSUE TITLE
mlnet auto-train not available 

### ISSUE THREAD

**Issue by vermapraveen** [dotnet/machinelearning-modelbuilder#800]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

```
mlnet auto-train
Required command was not provided.
Unrecognized command or argument 'auto-train'
```
```
$ dotnet --version
3.1.300
```
```
mlnet auto-train --task binary-classification --dataset "wikipedia-detox-250-line-data.tsv" --label-column-name "Sentiment" --max-exploration-time 10

Required command was not provided.
Unrecognized command or argument 'auto-train'
Unrecognized command or argument '--task'
Unrecognized command or argument 'binary-classification'
Unrecognized command or argument '--dataset'
Unrecognized command or argument 'wikipedia-detox-250-line-data.tsv'
Unrecognized command or argument '--label-column-name'
Unrecognized command or argument 'Sentiment'
Unrecognized command or argument '--max-exploration-time'
Unrecognized command or argument '10'
```
```
 mlnet  --version
16.1.1+acd4a98c2ef0dd6575de234c00ddc4f48d1d4f75
```
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

**Comment by LittleLittleCloud** [comment]
We recently update mlnet cli, but the document is still under preview and not publish yet. mlnet v16.1.1 should still in unlist status and shouldn't be able to download yet (but somehow it doesn't).

You can fix this by two solution, one is to uninstall mlnet cli v16.1.1 and reinstall mlnet v0.15.1 back, the command is 
`dotnet tool install --global mlnet --version 0.15.1`

Or you can play with v16.1.1! some changes have been made to command interface to make it more easy to use, tell us if you like it or not!

**Comment by vermapraveen** [comment]
I tried uninstalling and realized I was on 16.1.1
```
dotnet tool uninstall --global mlnet
Tool 'mlnet' (version '16.1.1') was successfully uninstalled.
```

0.15.1 giving error:
```
 mlnet auto-train --task binary-classification --dataset "wikipedia-detox-250-line-data.tsv" --label-column-name "Sentiment" --max-exploration-time 10
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
```
Though I was able to proceed with below command, not sure if it does same as in tutorial, but I was able to train and generate artifacts to use in project
```
 mlnet classification  --dataset "wikipedia-detox-250-line-data.tsv" --label-col  "Sentiment" --train-time 100
```

**Comment by beccamc** [comment]
Yep! The command you used is the correct syntax for the new release. 

`mlnet classification  --dataset "wikipedia-detox-250-line-data.tsv" --label-col  "Sentiment" --train-time 100`

Sorry the docs were not correct!
