### ISSUE TITLE
Specified label column 'Sentiment' was not found.

### ISSUE THREAD

**Issue by maxsklad** [dotnet/machinelearning-modelbuilder#805]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

![image](https://user-images.githubusercontent.com/54217316/83946995-80417b80-a7d1-11ea-8350-493a14bd34fe.png)

**Comment by JakeRadMSFT** [comment]
Hello,
Thanks for reporting this issue. In order to help, I need more information.

Can you share the following details:

Visual Studio Version
Model Builder Version
What scenario type did you run?
Can you share the dataset or information about it?

Cheers,
Jake

**Comment by JakeRadMSFT** [comment]
Closing due to lack of response. Please re-open if you're still hitting this issue!
