### ISSUE TITLE
Epochs for Azure Connected Mode

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-modelbuilder#807]
Currently Model Builder requests `2` epochs from Azure AutoML. 

We should be letting AutoML choose the number of epochs. This lets the intelligence lie within AutoML to train a good model and lets the AutoML team hone the model training overtime.

I expect we can simply not send a value, which will let the defaults of Azure AutoML define the number of epochs. If we need to send a value, `15` is the right answer.

_(I pinged folks earlier on internal chat on the same topic)_

**Comment by raduk** [comment]
We do not need to send this parameter, it would default to 15 with early stopping if needed
