### ISSUE TITLE
Visual Studio 2019 Model Builder Extension Error

### ISSUE THREAD

**Issue by OmerSaleemCC** [dotnet/machinelearning-modelbuilder#808]
The following star happening when i tried adding Machine Learning to an existing Machine Learning project in visual Studio 2019. And now it throws same error every time 

Unable to split the file provided into multiple, consistent columns.

   at Microsoft.ML.AutoML.ColumnInferenceApi.InferSplit(MLContext context, TextFileSample sample, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:line 101

**Comment by JakeRadMSFT** [comment]
@OmerSaleemCC can you share the dataset (or a portion of it)?

**Comment by OmerSaleemCC** [comment]
Hi jake.I have just found out that the error I'd taking place due to column in table of datatype "bit". i.e; true or false. Ignoring the column or converting ther column information fix the problem. Thanks anyways. Omer.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jake <notifications@github.com> Date: 08/06/2020  3:55 am  (GMT+05:00) To: dotnet/machinelearning-modelbuilder <machinelearning-modelbuilder@noreply.github.com> Cc: OmerSaleemCC <cctvxperts@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [dotnet/machinelearning-modelbuilder] Visual Studio 2019 Model Builder Extension Error (#808) 
@OmerSaleemCC can you share the dataset (or a portion of it)?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dotnet/machinelearning-modelbuilder/issues/808#issuecomment-640292236",
"url": "https://github.com/dotnet/machinelearning-modelbuilder/issues/808#issuecomment-640292236",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by beccamc** [comment]
Great! Let us know if you run into another problem!

**Comment by beccamc** [comment]
Closing this as the problem has been fixed. @OmerSaleemCC if you run into another problem - or need to use the excluded "bit" column - let us know and we can debug with the data.
