### ISSUE TITLE
Sentiment Analysis absent

### ISSUE THREAD

**Issue by zzfima** [dotnet/machinelearning-modelbuilder#809]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/scenario
Operating System: windows
Visual Studio Professional 2019, 2017

There is no "Sentiment Analysis", ML.NET version 16.1.0.2027905
![3333](https://user-images.githubusercontent.com/7007970/83999978-7d2ec280-a96c-11ea-8c64-b7f5fb010987.PNG)

**Comment by beccamc** [comment]
@zzfima Thanks for reporting! Sorry about the mix up, our docs need to be updated. Please select "Text classification"

@briacht Can you update the docs for this?

**Comment by beccamc** [comment]
This has been fixed. Thanks again for reporting @zzfima!
