### ISSUE TITLE
Specific feedback mechanism to learn about customer data

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#812]
We need a better sense of what data our users want to use. We loose 1,000 people on the Data tab.  

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/9e5c8d3d-7a7b-4da0-99b4-22688d188bec)

Some may just be looking at the product, but presumably many fail at this step. Do all of these users have .csv/.tsv files? Or are some coming with .json formats, or as Justin has suggested .data and .train formats? Or do they have production data in Azure they're trying to use?

**My proposal** is to add an explicit feedback mechanism on the Data page. I know we'll be adding "Report a bug" and "Suggest a feature" but if I were a user I would think .csv is a limitation of the product and would not report that I want to use Json, etc. 

This is my dev art mock up 😁

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/1e9cac08-c744-4000-bc77-44f782565285)

Thoughts @briact?

**Comment by romalpani** [comment]
That's great observation @beccamc !
I will track this in the design backlog and we will prioritize it in sprint planning.

**Comment by beccamc** [comment]
We could also add a new issue type in our repro if we felt this was important enough. Not sure if that would be clearer or cause more confusion.

**Comment by beccamc** [comment]
This issue is 2 years old. I'm closing it 😊
