### ISSUE TITLE
Error in Eval Screen for Azure Connected Mode image models

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-modelbuilder#813]
**System Information (please complete the following information):**
 - Model Builder Version: Nightly build from 2020-06-07
 - Visual Studio Version: Microsoft Visual Studio Enterprise 2019 Preview Version 16.7.0 Preview 2.0

**Describe the bug**
On the multiclass image classification evaluation screen, one image was evaluated correctly, a second one threw the below error. Every other image works correctly.

Error:
```
Object reference not set to an instance of an object.

   at Microsoft.ML.ModelBuilder.ToolWindows.BaseViewModel.Set[T](T newValue, String caller)
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateTabDataContext.set_PredictedValue(ObservableCollection`1 value)
   at Microsoft.ML.ModelBuilder.ToolWindows.EvaluateTabControl.<BrowseImage_Click>d__6.MoveNext()
```

Nicely, I can close the error modal, and continue using Model Builder, including additional images on the eval page.

**To Reproduce**
Seems deterministic. Train a multiclass image model using the Azure Connected mode. On the eval screen, every other image causes the error.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4080826/84114027-7c377880-a9e0-11ea-8684-b9c8d8ea9859.png)

**Comment by LittleLittleCloud** [comment]
Looks like a bug in BaseViewModel. I'll take a look

**Comment by LittleLittleCloud** [comment]
Tested on the latest master and problem gone.

**Comment by justinormont** [comment]
> @LittleLittleCloud commented 2020-07-20T20:53:36Z
> Tested on the latest master and problem gone.

Great. Thanks for validating that it no longer occurs on master.
