### ISSUE TITLE
Not able to install modelbuilder

### ISSUE THREAD

**Issue by mangala1981** [dotnet/machinelearning-modelbuilder#814]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by LittleLittleCloud** [comment]
Hi, can you provide more information? like which version of Visual Studio do you have, and what error do you get

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you still have question though
