### ISSUE TITLE
Dup dataset header on BitCoin dataset

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#816]
**Model Builder Version**: 16.1.0.2027905
**Visual Studion Version**: v16.6.1

Pick BitCoin Dataset, the preview data table has two dup header
![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/a3dd6985-0b3f-403a-b065-93d9873d6ed6)

[BitCoin ](https://app.zenhub.com/files/186917455/48ca20cb-6ef6-459e-a179-ae61757a9b5a/download)

**Comment by beccamc** [comment]
The problem here is that the data has an extra line above the header. 

```
Created on 02-18-2020,https://www.CryptoDataDownload.com
Date,Symbol,Open,High,Low,Close,Volume BTC,Volume USDT
2020-02-18,BTCUSDT,9706,9715,9624.7,9709.99,2131.76,20619941.59
```

I assume we want to support this? Should we filter out any garbage that comes before the file header?

**Comment by beccamc** [comment]
[9/11 1:59 PM] Becca McHenry
I'm curious about the priority of this, and if we want to fix it #816 
​[9/11 2:27 PM] Bri Achtman
    Would the fix be ignoring anything before the header?
​[9/11 2:27 PM] Bri Achtman
    Could we do something like, if dataset has a header, and if second row is identical to header, do something
​[9/11 2:40 PM] Becca McHenry
    Yes, we can probably do something like, if dataset has header, look for first row that matches header, start reading data there
​[9/11 2:40 PM] Bri Achtman
    ok, do we know how common this is?
​[9/11 2:41 PM] Becca McHenry
    No I have no idea. I don't think this causes an error
    Our data preview page just looks weird
​[9/11 2:42 PM] Bri Achtman
    I'd say it's a P1.5 - it has happened to me once before, but I feel like we haven't had any cusotmer complaints about it
​[9/11 2:42 PM] Bri Achtman
    Maybe P2
​[9/11 2:42 PM] Bri Achtman
    And also it's easy enough for people to delete any stuff before their data I think?
(1 liked)​[9/11 2:42 PM] Bri Achtman
    Before putting it in MB
​[9/11 2:43 PM] Becca McHenry
    Yes I agree
​[9/11 2:43 PM] Becca McHenry
    Okay, maybe we can bucket this with the support ML.Net format files work?
​[9/11 2:44 PM] Bri Achtman
    Yeah!

**Comment by beccamc** [comment]
Bucketing with ML.NET format work https://github.com/dotnet/machinelearning-modelbuilder/issues/946

**Comment by JakeRadMSFT** [comment]
Closing for now -  we have an expectation in Model Builder that data is ready/clean for training.
