### ISSUE TITLE
A few issues with new CLI on Mac

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#817]
ML.NET CLI 16.6.1
1. It's really difficult to read / understand
![image](https://user-images.githubusercontent.com/10437687/84214435-2f9f7c00-aa78-11ea-8b1a-1a8bff8a760d.png)
![image](https://user-images.githubusercontent.com/10437687/84214452-3c23d480-aa78-11ea-8ddf-410b4f20208d.png)

2. Also I got this message:
"Unable to load shared library 'lib_lightgbm' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblib_lightgbm, 1): image not found
The type initializer for 'Native' threw an exception."

3. It only shows 1 model when training, then it says it explored 4 models, and then it only shows the top 2 models (see screenshot above)

**Comment by beccamc** [comment]
Should be added to an improve CLI epic. @JakeRadMSFT

**Comment by beccamc** [comment]
@LittleLittleCloud Are the issues here resolved?

**Comment by LittleLittleCloud** [comment]
Mght be, I'll take a look

**Comment by luisquintanilla** [comment]
Since the new version of the CLI has been published, I'm closing this issue. We can revisit if any users report it.
