### ISSUE TITLE
During training ModelBuilder returns Program ServiceHub.Host.CLR.x64 stopped working.

### ISSUE THREAD

**Issue by pstopczyk** [dotnet/machinelearning-modelbuilder#818]
Hi,
Microsoft Visual Studio Professional 2019, ver. 16.6.1

During training model via Model Builder (Image Classification scenaroi) VS returns:
Program ServiceHub.Host.CLR.x64 stopped working.

**Comment by pstopczyk** [comment]
The same issue is still in ver. 16.6.2

**Comment by LittleLittleCloud** [comment]
Thanks for the log, this is super helpful
We are building a fix for this bug, after it's done, can you help us to try that to see if problem gone? It's a known bug in clr and is rare to see. Thanks

**Comment by pstopczyk** [comment]
Yes, I will be ready to retest. Give me only hint when to start.

Regards
Pawel

czw., 11 cze 2020, 19:22 użytkownik Xiaoyun Zhang <notifications@github.com>
napisał:

**Comment by LittleLittleCloud** [comment]
#834

**Comment by LittleLittleCloud** [comment]
Hi @pstopczyk , we have a fixed build for this, could you try it out to see if this solve your questions? thanks

You can get the download link from #834

**Comment by pstopczyk** [comment]
Hi, I have checked. Now works fine. Thx.
