### ISSUE TITLE
There is no Sentiment Analysis scenario in the scenarios

### ISSUE THREAD

**Issue by Gszekt** [dotnet/machinelearning-modelbuilder#821]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/scenario
Operating System: windows
Visual Studio: Visual Studio 2017 Community

![批注 2020-06-11 231428](https://user-images.githubusercontent.com/26792853/84404410-5a84fe00-ac39-11ea-8bbf-36dad3c31a91.jpg)

Should I select the first one?Thank you.

**Comment by LittleLittleCloud** [comment]
The first one is sentiment analysis, in Chinese...

**Comment by Gszekt** [comment]
> 
> 
> The first one is sentiment analysis, in Chinese...

OK，Thank you。There is a anothor issure.I got a error while importing data.
![批注 2020-06-12 083544](https://user-images.githubusercontent.com/26792853/84452232-db6ae680-ac87-11ea-847e-a3c4c32583ee.png)
and there is no Newtonsoft.Json, Version=10.0.0.0
![123](https://user-images.githubusercontent.com/26792853/84452332-1f5deb80-ac88-11ea-99df-da56879d9f33.png)
