### ISSUE TITLE
[Newtonsoft.V10] I got a error while importing data.

### ISSUE THREAD

**Issue by Gszekt** [dotnet/machinelearning-modelbuilder#827]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows
Visual Studio 2017.

![image](https://user-images.githubusercontent.com/26792853/84504457-9037ee80-acee-11ea-906c-44b6f627c29f.png)
But there is no Newtonsoft.Json, Version=10.0.0.0 on nuget.
![image](https://user-images.githubusercontent.com/26792853/84504526-a9d93600-acee-11ea-8c9c-ba1029f2cd91.png)

**Comment by LittleLittleCloud** [comment]
Can I have your model builder version?

It's a known bug in VS 2017, Prose requires newtonsoft > v10.0,  but the version shipped by VS 2017 is v9.

One solution is you can install VS 2019, which ships newtonsoft v12 with it, We are also working on a fix for that and should be released soon.

**Comment by Gszekt** [comment]
> Can I have your model builder version?
> 
> It's a known bug in VS 2017, Prose requires newtonsoft > v10.0, but the version shipped by VS 2017 is v9.
> 
> One solution is you can install VS 2019, which ships newtonsoft v12 with it, We are also working on a fix for that and should be released soon.

Thank you so much! I'll install VS 2019 and try again. 
![批注 2020-06-13 073628](https://user-images.githubusercontent.com/26792853/84554295-c787b900-ad49-11ea-9ef4-bcdfa0e6242d.jpg)
I don't known how to get the version of model builder.I can provide my log if needed

**Comment by LittleLittleCloud** [comment]
Sure, go to extension manager window and you can get version info on the right panel
![image](https://user-images.githubusercontent.com/16876986/84686109-3c94f300-aef0-11ea-9f38-e7d69c17536b.png)

**Comment by Gszekt** [comment]
> 
> 
> Sure, go to extension manager window and you can get version info on the right panel
> ![image](https://user-images.githubusercontent.com/16876986/84686109-3c94f300-aef0-11ea-9f38-e7d69c17536b.png)

ok .
![批注 2020-06-16 080546](https://user-images.githubusercontent.com/26792853/84717561-c30d0b80-afa8-11ea-8082-7dcf4e509d5a.png)

**Comment by mertonmeng** [comment]
> Can I have your model builder version?
> 
> It's a known bug in VS 2017, Prose requires newtonsoft > v10.0, but the version shipped by VS 2017 is v9.
> 
> One solution is you can install VS 2019, which ships newtonsoft v12 with it, We are also working on a fix for that and should be released soon.

Would you mind sharing a work-around other than install the VS2019? I am working on some urgent project now, get a VS2019 license or wait for new release is too long.

**Comment by LittleLittleCloud** [comment]
@mertonmeng 
You can try install an extension that contains newtownsoft.v10, Like cloud explorer (though I'm not recommended this way, it's not a stable fix, depending on which module will be loaded first, cloud explorer or model builder)

**Comment by LittleLittleCloud** [comment]
Hi @mertonmeng , Could you let me know if that solution solves your question?

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if problem is not fixed
