### ISSUE TITLE
request for forecasting scenario in model builder

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#828]
<img width="569" alt="forecasting-request-mb" src="https://user-images.githubusercontent.com/10437687/84526036-7a481080-ac91-11ea-8446-c72a7c22407e.png">

**Comment by beccamc** [comment]
Do you want to add this "vote" to the epic? https://github.com/dotnet/machinelearning-modelbuilder/issues/609

**Comment by JakeRadMSFT** [comment]
Referenced this bug in the epic.
