### ISSUE TITLE
Wrong command is shown in the instructions the arguments did not match current version. 

### ISSUE THREAD

**Issue by jtalborough** [dotnet/machinelearning-modelbuilder#830]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

This command is valid: 
"mlnet classification --dataset "wikipedia-detox-250-line-data.tsv" --label-col "Sentiment" --train-time 10 "

**Comment by LittleLittleCloud** [comment]
What's your mlnet version, is that v0.15.1?

we just update mlnet cli and document, this command should be valid for v16.1.*, but it doesn't for the older version.

**Comment by LittleLittleCloud** [comment]
@jtalborough , looks like your question has been resolved so I'm going to close this issue, feel free to reopen it though if it doesn't solve.
