### ISSUE TITLE
GPU Service not found. Falling back to CPU AutoML Service. Training cancelled

### ISSUE THREAD

**Issue by sansindia85** [dotnet/machinelearning-modelbuilder#831]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: Windows version 1709

Error message :
GPU Service not found. Falling back to CPU AutoML Service.
Training cancelled

**Comment by LittleLittleCloud** [comment]
Can I have your log for this run?
you can get it from %temp%/MLVSTools/logs

**Comment by sansindia85** [comment]
Thanks for the reply.
Can you please give the complete path?
My Visual Studio 2019 is installed in D: drive. Also I searched for "MLVSTools" in both C: and D: drive but could not find it.
Also, I checked at C:\Users\username\AppData\Local\Temp but could not find MLVSTools.

**Comment by LittleLittleCloud** [comment]
The complete path on my system is 
`C:\Users\%UserName%\AppData\Local\Temp\MLVSTools\logs`

Sorry for the late reply, hope this can help.

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you still have the problem
