### ISSUE TITLE
no cont

### ISSUE THREAD

**Issue by DevTech2008** [dotnet/machinelearning-modelbuilder#835]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by beccamc** [comment]
Thanks for reporting this issue. In order to help, I need more information.

Can you share the following details:
- Visual Studio Version
- Model Builder Version
- What scenario type did you run?
- Error message and stack trace 

Thanks!

**Comment by beccamc** [comment]
@DevTech2008 Ping on the questions above 😊

**Comment by beccamc** [comment]
Unfortunately we don't have enough information to investigate this issue. If you're still seeing a problem, please re-open and provide additional information. Thanks for reporting!
