### ISSUE TITLE
Problem building dotnet

### ISSUE THREAD

**Issue by davidthestatue1** [dotnet/machinelearning-modelbuilder#839]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Two Errors I am receiving while building ML.net dotnet:
First error is after extracting the tar, and running the command:
'./dotnet tool install -g mlnet'
mlnet installs successfully, but I cannot run the software with command 'mlnet'
I am first prompted to install mldonkey-server using 'apt install mldonkey-server'
then, to attempt using the binary to run software sample code 'consumeModel' from
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
I get the error 
root@david-Lenovo-Product:/home/david/Downloads# ./dotnet run --project /home/david/code/Program.cs
/home/david/code/Program.cs(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

The build failed. Fix the build errors and run again.

**Comment by LittleLittleCloud** [comment]
the parameter for --project should be csproj file, which ends in .csproj, instead of csharp source file

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you still have the problem
