### ISSUE TITLE
[Functional Spec] Add Base Telemetry

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#84]

**Comment by greazer** [comment]
@rustd, I'm closing this issue for now. Feel free to reopen it with specific telemetry data-point asks and then change the title to make it more descriptive. Going forward all specs for features need to have telemetry added as part of the spec.

**Comment by rustd** [comment]
Let's use this to capture the base telemetry that we need for Model Builder. All new features will have specific telemetry requirements.

This doc captures the initial set of metrics. (merged with the list we had for //build). Bri is working on updating the doc and will send out the update.
https://microsoft-my.sharepoint.com/:w:/p/brachtma/EZOael_LilpItFPzu1GrGaUB7lwc6qxMOS8ykZrlJO4w1A?e=wB7gCk
