### ISSUE TITLE
Train Your Model Issue

### ISSUE THREAD

**Issue by marmosetg** [dotnet/machinelearning-modelbuilder#840]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Message Recd:
GPU Service not found. Falling back to CPU AutoML Service.
Training cancelled

**Comment by LittleLittleCloud** [comment]
Seems to be a dup of #833

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you still have the problem
