### ISSUE TITLE
[Feature Request] Enable to run ModelBuilder from more than one projects within a solution

### ISSUE THREAD

**Issue by yutaraa** [dotnet/machinelearning-modelbuilder#846]
Currently the names of the projects that ModelBuilder generates start with its solution name, not the project name you ran ModelBuilder from.
Therefore after you have run ModelBuilder once, running it from another project occurs project name conflict.
I expect that generated projects should be related to the project, not to the solution.
In my opinion, it is also consistent with the context menu operation on Solution Explorer, because ModelBuilder opens from a project's context menu.

Regards

**Comment by LittleLittleCloud** [comment]
#878

**Comment by JakeRadMSFT** [comment]
Thanks for reporting! We're working on a feature to support this but it's going to take us a few months.

**Comment by JakeRadMSFT** [comment]
#685

**Comment by yutaraa** [comment]
Thank you for your reply, Jake.
I'm looking forward it.
Also, thank all others who gave comments.
