### ISSUE TITLE
[Functional Spec] New Project Experience 

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#85]
The user should be able to select Model Builder from File - New Project for VS 2017 and 2019. This will create an Empty Solution with Model Builder window. 

When the user clicks "Add Projects" in the code step. It will add a consoleapp and a class library (existing behavior). It will skip adding references to ML.NET NuGet package and a reference to class library to the starting project (which doesn't exist in the File-New case)

Add "Right click - Add Machine Learning" option to Solution explorer for all cases.

A user should be able to launch Model Builder from the Extensions menu as well #96 has details

![image](https://user-images.githubusercontent.com/1132652/59221894-289c1000-8b7d-11e9-8a37-c42ae1f1331f.png)

![image](https://user-images.githubusercontent.com/1132652/59221903-2c2f9700-8b7d-11e9-955f-8501290e80a9.png)
![image](https://user-images.githubusercontent.com/1132652/59221914-305bb480-8b7d-11e9-9b19-eb15dd4b66b4.png)

**Comment by rustd** [comment]
Do this as well https://github.com/dotnet/machinelearning-modelbuilder/issues/96
Closing #96

**Comment by briacht** [comment]
Spec: https://microsoft-my.sharepoint.com/:w:/p/brachtma/EV6RODPN57hLmyZxYWPhvf4BXe2t7VMw8PkzWVsaw8Uqxw?e=OZzD9M

**Comment by tbombach** [comment]
Links for dev:
[Tags in new project dialog templates](https://devblogs.microsoft.com/visualstudio/build-visual-studio-templates-with-tags-for-efficient-user-search-and-grouping/)
[Wizards with Project Templates](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates?view=vs-2019) (this is how we can have events in our extension when the New Project Dialog creates the project from our template)

**Comment by JakeRadMSFT** [comment]
Upgrading to XL to handle the case where Extension isn't installed in Spec.

**Comment by greazer** [comment]
Until we have a spec that is implementable, we need to keep the label. At the review, it was decided that Bri's initial spec needed more attention.

**Comment by briacht** [comment]
New spec: https://microsoft-my.sharepoint.com/:w:/p/brachtma/Ea-69cOSuvhMsuHod0iH1AYBWdH9jX4xfFXJUyGhKjTkPA?e=MnyMm9
