### ISSUE TITLE
Locations of bounding box predictions when using console app in codegen.

### ISSUE THREAD

**Issue by ttstanley** [dotnet/machinelearning-modelbuilder#850]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.1.2031801
VS 19

**Describe the bug**
The codegen currently predicts bounding boxes based off the 600 x 800 pipeline uses. Thus the predictions assume the image is scaled to 600 x 800. However not all images are of this resolution so they may come out inaccurate.

**To Reproduce**
1. click object detection scenario
2. once done trraining "add code" to solution
4. run the newly generated console app
5. when looking at the locations of predicted boxes you will see numbers that are not representative of image.

**Expected behavior**
The values should be either related to image or normalized to values between 0 and 1.

**Additional context**
Some ideas is whether to normalize the values or add additional code in the program.cs that is generated to scale their example for them.  Both might confuse a customer on how to use their data. An issues is that the pipeline doesn't know any information about the images size when creating prediction so predictions coming out of model can't be scaled during the process. Maybe adding a comment on how the user can user their model to scale to the correct x,y locations will be another alternative.

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud Is this fixed?

**Comment by LittleLittleCloud** [comment]
Yep
