### ISSUE TITLE
[bug] Generated code from ML.Net ModelBuilder doesn't work (throws OperationCanceledException)

### ISSUE THREAD

**Issue by Jonathan-CG** [dotnet/machinelearning-modelbuilder#852]
### System information

- **OS version/distro**: Microsoft Windows Server 2016 Datacenter 10.0.14393 Build 14393
- **.NET Version (eg., dotnet --info)**: 3.1.301

Using AWS Workspace.

### Issue

- **What did you do?** I used the ML.Net ModelBuilder (https://docs.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-model-builder). I chose a scenario, selected my features/label, trained the model and generated the code with the new model trained.
- **What did you expect?** I was able to load the model saved and create new predictions with it. However, when I tried to retrain the model, using the ConsoleApp project generated by ML.Net Builder, it throws OperationCanceledException in the process. More specifically, I call the method "CreateModel()" from the class ModelBuilder in the ConsoleApp project (that is generated automatically by ML.Net Model Builder when you want to generate the code), then it trains the model but there's always a OperationCanceledException that is thrown. It seems to happen in the method SaveModel, but the path used for the model is correct, so I don't think it's a path issue..

### Source code / logs

Logs when I use ML.Net ModelBuilder tool (which worked fine)
![image](https://user-images.githubusercontent.com/13685010/85098434-bc5cdf00-b1c8-11ea-918c-2586d7e17b1e.png)

Image of what happens when I try to run the console app project generated by ML.Net ModelBuilder tool
![image](https://user-images.githubusercontent.com/13685010/85098688-5fadf400-b1c9-11ea-9664-5eefc1ac24f9.png)

**Comment by Jonathan-CG** [comment]
> Hi @Jonathan-CG This bug appears to be about code generated from Model Builder. So I am transferring this to the model builder repo.

Yes you are right. As for the issue I'll have to create a blank new project with new data because the one we're using is confidential. But to reproduce the issue you just need to use the Model Builder, use the Generate Code button and try to run the code generated from ModelBuilder by doing ModelBuilder.CreateModel() and it should crash.

I'll try to make a blank new project by EOW.

**Comment by LittleLittleCloud** [comment]
@Jonathan-CG 

Sorry for the late reply, let me know when your blank project is ready. Thanks

**Comment by LittleLittleCloud** [comment]
Close this because we shouldn't have this bug any more since we move to the new code gen
