### ISSUE TITLE
Reference to Model project not added 

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#855]
Reference to Model project not added

**Comment by briacht** [comment]
Happened during the user study.

Sometimes the reference to Model class library project would add, sometimes it wouldn't.

1. Go through MB (in this case text classification with yelp dataset) and generate code
2. Remove the generated files from the solution and then delete them from File Explorer
3. Close Model Builder (but not VS)
4. Re-open VS and go through text classification training with yelp dataset and generate projects
5. See if reference to projectML.Model is generated

**Comment by LittleLittleCloud** [comment]
@briacht 
Did you also remove the reference to .Model project in projectML.csproj when you do step2?

**Comment by JakeRadMSFT** [comment]
![image.png](https://images.zenhubusercontent.com/5cde1c65e3106e39e8ae08f2/95646286-f18f-48ac-90fe-b11bd5238d35)

Looks like there is an exception getting thrown in a place where we ignore it.

**Comment by JakeRadMSFT** [comment]
Resolved in preview
