### ISSUE TITLE
Feedback from first time user

### ISSUE THREAD

**Issue by Symbai** [dotnet/machinelearning-modelbuilder#859]
I have a couple of ideas where I want to use ML. One it is to recommend items from a list based on what other items a user has picked before. So I grabbed the Model Builder and chosen "Recommendation" as scenario. Selected the environment, no issues so far.

On the next page "Data" i was getting frustrated:

1. Why does the builder wants THREE input columns? In my scenario I only have two (full list of strings and a list of picked strings) and I expected the machine to recommend similar strings from the full list, based on the picked strings.
2. I was looking for an answer by using the info icon / tooltip next to each input column in the hope of it explains to me why it needs that and what exactly is meant by that. I was shocked to see how terrible information they gave. For example the info on "User column" says: "Pick user column". Its the same on other information icons as well. At these level of information I don't need the icons at all and all my questions remain unanswered....

As a completely beginner I really appreciate this model builder. But I would like more explanations on each step so I can adopt this to MY personal scenario and currently the Model Builder feels more like a show case demo which works perfectly when using the default data as input.

**Comment by JakeRadMSFT** [comment]
@Symbai thanks for providing this feedback! Right now Recommendation scenario in Model Builder uses a model type that requires rating - like movie recommendations that require users to specify a star rating. We can look into expanding recommendation to support scenarios without ratings. Can you describe the scenario you want to use recommendation for?

**Comment by beccamc** [comment]
Sorry you ran into this problem! We've updated the tooltips to be more [descriptive](https://github.com/dotnet/machinelearning-modelbuilder/issues/1298). It sounds like you want to use "Text Classification" instead of recommendation. Let us know if you run into more problems!
