### ISSUE TITLE
MacOS-mlnet: Command not found.

### ISSUE THREAD

**Issue by Maxhirez** [dotnet/machinelearning-modelbuilder#861]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: macos 
Catalina 10.15.5 Mac mini 2018 3Ghz 6-core i5

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Running this step I encounter:
zsh: command not found: mlnet
I backed out a few steps and confirmed that the mlnet tool is installed.  Also tried sudo and dotnet mlnet... etc.

![Screen Shot 2020-06-30 at 11 26 24 AM](https://user-images.githubusercontent.com/4993536/86151591-8a9b2080-bac4-11ea-905f-d73b74498cb6.png)

**Comment by LittleLittleCloud** [comment]
you need to add dotnet tool path to your environment path variable. there should be hint message from dotnet global tool once after you install mlnet.

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you still have the problem
