### ISSUE TITLE
Environment name text cutoff 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#863]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**
1. Steps to reproduce the behavior:
1. Select  image scenario
2. Jump into environment page 

**Expected behavior**
All text for azure environment should be displayed 
**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/36615490/86162543-cda8c400-bac3-11ea-8fb8-9461170f3755.png)
.

**Additional context**

**Comment by LittleLittleCloud** [comment]
Hmmm it's not cut on my PC, can you share your display setting?

**Comment by beccamc** [comment]
The problem was the bolding of the subtext. Fixed by https://github.com/dotnet/machinelearning-modelbuilder/issues/875
