### ISSUE TITLE
Scenario page - smaller UI bugs

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#865]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.1.2033001
 - Visual Studio Version

**Describe the bug**
1. The list of cards in each section of the scenario page must be alphabetically sorted (screenshot 1)
2. The cards for which the text content isn't truncated (or not overflowing), no need to show tool-tip (screenshot 2) 

**To Reproduce**
1. Go to ModelBuilder Scenario page

**Expected behavior**
1. Alphabetical ordering for cards in individual sections
2. For scenario cards, don't show tool-tip in case there isn't a text-overflow.

**Screenshots**
<img width="1176" alt="Bug_Scenario_1" src="https://user-images.githubusercontent.com/48927690/86162964-76572380-bac4-11ea-9fb5-2a7143875bd0.png">

<img width="1177" alt="Bug_Scenario_2" src="https://user-images.githubusercontent.com/48927690/86162980-79eaaa80-bac4-11ea-8707-083b3588f6bc.png">

**Additional context**

**Comment by beccamc** [comment]
Per ordering of cards, Bri and Rohan will user test.
