### ISSUE TITLE
Code Page, font color is black in dark theme

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#866]
![image](https://user-images.githubusercontent.com/16876986/86163340-f41b2f00-bac4-11ea-992b-f0b9b41bc415.png)

**Comment by beccamc** [comment]
Fixed 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/09639327-8997-45e3-a987-fb3e17e80f69)
