### ISSUE TITLE
Operation cancelled even on a good dataset after training fail

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#870]
Step to reproduce:
- regression training on this dataset (select price)
- train fails because price can't be parse as single
- select a good dataset, like taxi-fare-amount
- train cancel, can only be solved if kill x64 process

**Comment by LittleLittleCloud** [comment]
[trickyfile.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4853907/trickyfile.txt)

**Comment by beccamc** [comment]
Yes I can confirm this is fixed! So happy!! 😄
