### ISSUE TITLE
Object Detection - Training page - UI issues

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#872]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.1.2033001
 - Visual Studio Version

**Describe the bug**
1. The uploading percentage keeps flipping back and forth between 0% and 100%. It should show the actual sequential progress.
2. Ther progress percentage shows 'ellipses' at the end - that ellipses is not required.
3. Once the training has started, the button reads 'cancel uploading'. It should read 'Cancel training' (like it does in case of other scenarios).

**To Reproduce**
1. Go to Model Builder
2. Click on Object Detection card on scenario page
3. Go through to Data page
4. Upload a data set
5. Go to Training page and start training...

**Expected behavior**
Described above.

**Screenshots**
<img width="1351" alt="Bug_Training_1" src="https://user-images.githubusercontent.com/48927690/86166082-10b96600-bac9-11ea-8bd6-3debe5bc9f34.png">

**Additional context**

**Comment by LittleLittleCloud** [comment]
- the behavior of `Cancel uploading` is expected because the current step is uploading dataset.
- the flipping percentage has been fixed in #717 
- I will fix the second bug (eclipse at the end of percentage)
