### ISSUE TITLE
While the training is ongoing evaluate and code pages are enabled 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#873]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

1. Select image Scenario
2. Select azure environment 
3. select data
4. Start training

**Expected behavior**
Evaluate and code tabs should be disabled 
**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/86166300-6988fe80-bac9-11ea-94cb-ba6975db687d.png)

**Additional context**

**Comment by LittleLittleCloud** [comment]
Hmm I can't reproduce that, can you provide more details?

**Comment by beccamc** [comment]
No repro
