### ISSUE TITLE
Usabilla Feedback: User is facing dependency issue

### ISSUE THREAD

**Issue by v-mepa** [dotnet/machinelearning-modelbuilder#874]
**User Comment:** There is a dependency problem with Microsoft.ML and Microsoft.ML.DataView needing System.Collections.Immutable 1.2.3.0. Not sure how System.Collections.Immutable 1.7 (newest version) got in the packages directory but I can't change it to the old version so can please update Microsoft.ML.DataView and Microsoft.ML to use any version higher than 1.2.3.0?
**URL:** https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet
**OS:** MacOSX
**Browser:** Safari 13.1
**Device:** Desktop

![image](https://user-images.githubusercontent.com/42360097/86171588-cbe5fd00-bad1-11ea-82ae-caddb4d5e322.png)

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud can you take a look at this?

**Comment by LittleLittleCloud** [comment]
The issue is solved in machinelearning repo.
