### ISSUE TITLE
Data page regressions

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#876]
Default states should be consistent for drop-downs:

When open Data step:
![image](https://user-images.githubusercontent.com/10437687/86179060-6ba98800-bade-11ea-89d6-0396bdf95da8.png)

When select a dataset:
![image](https://user-images.githubusercontent.com/10437687/86179112-85e36600-bade-11ea-9ae4-df11f5c0f4a2.png)

When select a Label should say 1 of 1 columns (or whatever it said before):
![image](https://user-images.githubusercontent.com/10437687/86179175-a6132500-bade-11ea-90c3-3c9ea88a9472.png)

**Comment by beccamc** [comment]
Fixed: 
With selected dataset
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/999f7d62-a741-4206-bbc4-b8786b67d17b)

With selected label
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/524a3f38-052d-4423-a6e4-64a7de200f47)

Not fixed?  I think we need to change the font color on "Select column(s)"
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/1754f35a-ec70-4d45-94fe-b4d9bdc76223)

**Comment by beccamc** [comment]
Font color on custom control probably doesn't matter.. this will be replaced in Advanced Features.

**Comment by beccamc** [comment]
This is being fixed for advanced features. Closing.
