### ISSUE TITLE
Training fails

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#877]
Training fails on yelp-labelled dataset

It trained successfully the first time, then I tried to re-train and it kept failing. I even closed out of Model Builder and the solution and restarted Model Builder, but still get this error when re-starting and trying to train with yelp-labelled dataset:

![image](https://user-images.githubusercontent.com/10437687/86179499-3b161e00-badf-11ea-8432-2608ec41e64a.png)

**Comment by LittleLittleCloud** [comment]
dup of #870
