### ISSUE TITLE
result.Prediction is showing as error

### ISSUE THREAD

**Issue by balu960** [dotnet/machinelearning-modelbuilder#879]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by LittleLittleCloud** [comment]
Can you provide more detail and paste error you have here, thanks

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if your question is not solved.
