### ISSUE TITLE
Method not found: Microsoft.ML.AutoML.BestResultUtil.GetTopNRunResults

### ISSUE THREAD

**Issue by chunky** [dotnet/machinelearning-modelbuilder#880]
**Model Builder Version**: 16.1.0.2027905
**Visual Studio Version**: VS2019 16.6.3

**Bug description**
With freshly-updated [as of today, 2020-07-04] VS2019 and model builder, I tried to use the new ML builder wizard "image classifier". It failed with an exception: Method not found: 'System.Collections.Generic.IEnumerable`1<System.ValueTuple`2<Microsoft.ML.AutoML.RunDetail`1<!!0>,Int32>> Microsoft.ML.AutoML.BestResultUtil.GetTopNRunResults

**Steps to Reproduce**
1. Installed latest VS 2019 and updated Model Builder to latest version
2. Create new project. Right click on project -> Add -> "Machine Learning"
3. Choose image classification, "Local ML", Next.
4. As input, choose an appropriate folder, observe "data preview" looks like I expected, with images being shown under various classifications
5. Train, Start Training.

**Expected Experience**
Pretty much what I'd expect from the tutorial, and of a wizard.

**Actual Experience**
Shortly after click "start training", I get this:
"GPU Service not found. Falling back to CPU AutoML Service."

Moments later, this exception:
Method not found: 'System.Collections.Generic.IEnumerable`1<System.ValueTuple`2<Microsoft.ML.AutoML.RunDetail`1<!!0>,Int32>> Microsoft.ML.AutoML.BestResultUtil.GetTopNRunResults(System.Collections.Generic.IEnumerable`1<Microsoft.ML.AutoML.RunDetail`1<!!0>>, Microsoft.ML.AutoML.IMetricsAgent`1<!!0>, Int32, Boolean)'.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.ExecuteAsync(IDataView trainData, IDataView validateData, ColumnInformation columnInformation, Nullable`1 userCancellationToken, Nullable`1 timeout)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 147

**Additional Context**
Clicking "Open Log File" brings up this file:
[bdcc7a7b-fad5-4a23-8f95-54b9d04e13f6.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4874405/bdcc7a7b-fad5-4a23-8f95-54b9d04e13f6.txt)
Screenshot:
![image](https://user-images.githubusercontent.com/249518/86525290-1650dc00-be3a-11ea-85b0-8937cc0acc55.png)

This is a MS Surface, not sure what marque. It has an intel core i7-7660U @ 2.50GHz, 16GB Memory, 64-bit OS.
Windows 10 Enterprise 1903, build 18362.900

**Comment by chunky** [comment]
[digits_small.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4880158/digits_small.zip)

Here's the dataset I was using

**Comment by chunky** [comment]
I just updated VS to the latest 16.6.5, but I'm still having the same problem.

**Comment by JakeRadMSFT** [comment]
Sorry this fell off my radar! I'll try it out today. Thanks for all the details

**Comment by chunky** [comment]
Thank you! Please let me know if there's anything else I can do to assist. At work I'm exploring a cavalcade of new AI and ML options right now, and if this was working for me, it adds a very appealing option to the table.

**Comment by chunky** [comment]
Unfortunately this is still happening in today's new release of ML Model Builder [16.1.1.2041102] with the latest VS [16.7.532.28833]

**Comment by chunky** [comment]
I just tried completely uninstalling and reinstalling VS, but am still having the same issue. Is a fix for this on the horizon?

**Comment by chunky** [comment]
As mentioned, I previously had tried uninstalling and reinstalling VS, no dice. I happened to get a new laptop at work, and tried installing just the latest VS and Model Builder from scratch on a fresh windows install, today. I had had the previous laptop for ~4 years, and during that time it had had pretty much every released dotnet core version installed on it. I'm guessing that latest 

This error has now gone away.

**Comment by R0Wi** [comment]
I have exactly the same behaviour: on my dev PC where previous versions of .NET Core SDK 3.1 have been installed the above error occures. I tried to uninstall all other .NET Core SDK versions except the newest one but this doesn't help. On a fresh windows install everything works like expected with VS19. So sounds indeed like a leftover of an old installation. Is there any chance to get this fixed?

**Comment by LiQIjie** [comment]
I have same problem, work on it for several days , cann't fixed yet.

**Comment by LiQIjie** [comment]
this solved my problem https://github.com/dotnet/machinelearning-modelbuilder/issues/1259#issuecomment-813568213

**Comment by R0Wi** [comment]
> this solved my problem [#1259 (comment)](https://github.com/dotnet/machinelearning-modelbuilder/issues/1259#issuecomment-813568213)

Would also be interested in testing this. @LiQIjie  could you quickly explain how to install the mentioned preview?

**Comment by LiQIjie** [comment]
> > this solved my problem [#1259 (comment)](https://github.com/dotnet/machinelearning-modelbuilder/issues/1259#issuecomment-813568213)
> 
> 
> 
> Would also be interested in testing this. @LiQIjie  could you quickly explain how to install the mentioned preview?

Take a look here
https://docs.microsoft.com/en-us/visualstudio/extensibility/private-galleries?view=vs-2019

**Comment by LiQIjie** [comment]
CPU model builder works well ,but GPU model builder not.

**Comment by beccamc** [comment]
Hi everyone, that version of Model Builder has been released publicly. Please take a look here https://marketplace.visualstudio.com/items?itemName=MLNET.07

**Comment by chunky** [comment]
I just tried to upgrade, but when I follow through the instructions linked, I still get 16.2.0:

```
$ dotnet --version
5.0.301
$ dotnet tool update -g mlnet
Tool 'mlnet' was reinstalled with the latest stable version (version '16.2.0').
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
$ 
```

**Comment by beccamc** [comment]
Sorry for the miscommunication. The update is only for VS version. We're still working on releasing the new CLI. Are you still using the VS UI, or only the CLI?

**Comment by chunky** [comment]
All the work I do that involved ML.NET is on Linux. As far as I know, that's only CLI for the forseeable future?

**Comment by beccamc** [comment]
Correct, Linux is CLI for the foreseeable future. I'll update the issue when the new CLI ships.

**Comment by LittleLittleCloud** [comment]
@chunky 
You can try cli preivew from this feed
> https://mlnetcli.blob.core.windows.net/mlnetcli/index.json

To install mlnet from that feed
> dotnet tool install -g mlnet --add-source https://mlnetcli.blob.core.windows.net/mlnetcli/index.json

**Comment by beccamc** [comment]
This issue should be resolved and released. If anyone is still experiencing a problem please open a new issue. Thanks!
