### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error	CS0246	The type or namespace name 'MyMLAppML' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by TheToxicChemist01** [dotnet/machinelearning-modelbuilder#882]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

It doesnt recognise it and I downloaded the MLDotNet Nuget package, I dont know what to do

**Comment by LittleLittleCloud** [comment]
Did you have dotnet sdk 3.1 installed?

**Comment by TheToxicChemist01** [comment]
Yes, I am

**Comment by LittleLittleCloud** [comment]
How do you compile the project, do you use visual studio or dotnet cli?

Can you also upload a screenshot of the error msg, thanks

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you still have any questions
