### ISSUE TITLE
No-Header files cannot find column for training

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#889]
Remove the header from your data file. It will show correctly in the data preview but is unable to train. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/a915a32a-6be7-4be9-81db-e4b4fda533a0)

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/ed1581cc-6418-46c3-8527-ef978795a193)

**Comment by JakeRadMSFT** [comment]
@beccamc is this a regression?

**Comment by beccamc** [comment]
@JakeRadMSFT  Yes this is a regression

**Comment by beccamc** [comment]
For the yelp dataset we now can't even display the preview 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/84a1b82d-1f9a-4d38-be6b-7c2b62160413)
