### ISSUE TITLE
Strange error about Probability

### ISSUE THREAD

**Issue by CBrauer** [dotnet/machinelearning-modelbuilder#892]
### System information

Microsoft Visual Studio Professional 2019 Version 16.6.3
Windows 10 Enterprise, Build 19041.329
ML.NET 1.5.0

### Issue

I generated a console app with mlnet  cli.
I then modified the source code to use Cross Validation.
I'm getting an error during execution.
A screen capture of my running application is:

![screen](https://user-images.githubusercontent.com/1317234/87200529-97342b80-c2b1-11ea-89a5-8d257b8d07a2.png)

I don't understand the error: "Probability column 'Probability' not found (Parameter 'schema')

### Source code 

I have put the complete solution on https://github.com/CBrauer/Test_CrossValidate.

Using Visual Studio, I searched for the word "Probability".  It did not exist.

My ModelInput.cs is:

```
using System;
using Microsoft.ML.Data;

namespace Version3.Model {
  public class ModelOutput {
    [ColumnName("PredictedLabel")]
    public string Prediction { get; set; }
    public float[] Score { get; set; }
  }
}
```

By the way, you guys changed **Score** to be a float array.  Please explain how we should interpret this array.

I put the complete solution at: https://github.com/CBrauer/Test_CrossValidate

Any help will be greatly appreciated.

Charles

**Comment by JakeRadMSFT** [comment]
@CBrauer the Score array is the probabilities of the different labels. This is definitely something that needs improvement but you can find some information here: https://github.com/dotnet/docs/issues/14265.

Unfortunately, there isn't a great way to get the list of labels from ML.NET. We have some code we use in model builder that we might be able to clean up and share.

**Comment by CBrauer** [comment]
Thank you for your reply.
