### ISSUE TITLE
Adding machine learning to a program in vs 2019

### ISSUE THREAD

**Issue by harkimmzy** [dotnet/machinelearning-modelbuilder#896]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
Hi @harkimmzy sorry you've run into an issue while using Model builder! 

In order to help, can you provide more information: 
-  Visual Studio Version
-  Model Builder Version
-  The error message and stack trace 

Thank you!

**Comment by beccamc** [comment]
Any updates on this issue?

**Comment by beccamc** [comment]
![image](https://user-images.githubusercontent.com/9122518/90439500-49be9180-e09b-11ea-82fb-a8341a4ee81d.png)
