### ISSUE TITLE
Preview label not aligned  in GPU UI

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#897]
![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/50dd60bc-ad81-473a-8049-f7f4e069cbf8)
Two  preview label not aligned with each other

**Comment by beccamc** [comment]
This looks correct in the most recent build
 ![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/32e259e7-77c8-48cd-89f3-b20bf4720a06)
