### ISSUE TITLE
Mini-spec on data cleaning for PROSE team

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#899]
PROSE would like a spec/doc for data cleaning. Should include: 
- Expected API contract 
- Types of errors we expect to be fixed (e.g. rows with bad data, rows with "No data" instead of a number, rows with unusual data, etc.)
- How we'd like things to be fixed (pull bad rows into another file, interaction in UI, etc.)

**Comment by luisquintanilla** [comment]
@beccamc I think this issue is something we might want to explore to make data prep easier for code-first approaches.
