### ISSUE TITLE
Visual Studio Closing automatically

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#90]
Customer reported issue: https://github.com/dotnet/machinelearning-samples/issues/471
VS is crashing in this case.

**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by greazer** [comment]
@AkhilSynmax, we moved your issue at https://github.com/dotnet/machinelearning-samples/issues/471 to this repo. Can you please fill out details around Model Builder version and repro steps for the crash you're experiencing? Thanks!

**Comment by greazer** [comment]
@akhilSynmax, I was not able to reproduce the issue you describe using the dataset file you provided with the latest (June) build of Model Builder. Please reactivate, if you are still experiencing the crash.

**Comment by greazer** [comment]
@AkhilSynmax, are you possibly running on Windows 7? That may be the root cause. Please see #40
