### ISSUE TITLE
Set RunType and RunSource

### ISSUE THREAD

**Issue by raduk** [dotnet/machinelearning-modelbuilder#901]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
In RunDefinition the RunType should be sent with "ModelBuilder" value, and in CreateParentDTo, the RunSource should be sent with "ModelBuilder"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment]
@raduk & @JakeRadMSFT  could you give me more context about the issue?

**Comment by zewditu** [comment]
Radu confirmed that  highlighted values  are replaced by "Model Builder"

![image](https://user-images.githubusercontent.com/36615490/130514052-c16e3b11-eabf-4c0d-9ed9-ed523766445e.png)

**Comment by raduk** [comment]
Yes, I confirmed that they should be replaced with "ModelBuilder"

**Comment by zewditu** [comment]
Thanks for your correction.

**Comment by vzhuqin** [comment]
@zewditu  any update about how to validate this issue?

**Comment by zewditu** [comment]
Steps to validate 
1. Choose Image classification for Azure  or Object detection scenarios
2.  Complete Environment and data pages 
3. Click start training
4. Monitor the remote run in the azure portal  either using the link  "Monitor current run in the Azure portal." or directly in Azure portal 
5. After the experiment is completed successfully in the portal  open the raw json to see the properties of the run 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/c21257cd-c466-43fb-befb-9ecdb10c3806)
6. In the Rawjson make sure that azure ml resource should be "ModelBuilder" as shown in the below screenshot 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/a7292cd5-625e-4eda-a5e2-8adfc6ad2069)

**Comment by vzhuqin** [comment]
not repro this issue on ML.Net Model Builder: 16.9.1.2156904 (Main)

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b455e6d9-bce5-4a2a-990e-93654330645d)
