### ISSUE TITLE
Data page small UI bugs

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#904]
**System Information (please complete the following information):**
- Model Builder Version: 16.1.1.2036504
 - Visual Studio Version

**Describe the bug**
UI: For SQL database selection, use elaborate button text instead of ellipses button (it refers to browse)
>> Use button text "Choose data source"

Text: Use a comma before the last item in the list
>> It should be .csv, .tsv, or .txt

UI: Make the height of text fields as per VS standards

**To Reproduce**
1. Go to Model Builder
2. Click on Text Classification
3. Click on Local, then Data to go to next page 
4. Select SQL in the dropdown

**Expected behavior**
(see above)

**Screenshots**
![image](https://user-images.githubusercontent.com/48927690/87810233-846da980-c811-11ea-80db-1628df15ca39.png)

**Additional context**

**Comment by beccamc** [comment]
Problem 1 & 2: 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/443bb388-e594-4e38-9f06-852f2901dd94)

Problem 3: 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/4e661a8c-0754-4102-bca5-95e69a68dfb2)
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/6cf48518-5b77-4640-97b9-81d5663820c8)
