### ISSUE TITLE
GPU environment spinners

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#907]
Move the GPU environment spinners to each individual item. It should look like this

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c0eb3df5-05a0-447b-b816-903c13f396e0)

Instead it currently shows only one spinner. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/fc2c6363-d06b-4e17-8ccb-9acc37bd1149)

**Comment by beccamc** [comment]
I am prioritizing this under my other commitments for this release

**Comment by JakeRadMSFT** [comment]
sounds good

**Comment by beccamc** [comment]
No one has commented on this, closing for now. We can reopen it if we want it later.
