### ISSUE TITLE
text scenario file explorer says "all supported image files"

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#908]
I selected text classification and then went to choose a local file and saw:

![image](https://user-images.githubusercontent.com/10437687/88087709-31ac2e80-cb3e-11ea-9153-50337ec5b692.png)

It should say "All supported files"

**Comment by beccamc** [comment]
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/3cb5b8f8-af53-47d0-8818-966d4dca43bc)
