### ISSUE TITLE
Switch order of data sources in description text on Data page

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#909]
In the description text, we have SQL Server then File, but in the drop-down we have File before SQL Server.

![image](https://user-images.githubusercontent.com/10437687/88087986-9798b600-cb3e-11ea-8ed7-2834f40b6df4.png)

Change the description text so it says "from either a File or SQL Server"

**Comment by beccamc** [comment]
This string is gone in the new design
 ![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/8c43b32d-9377-4c53-83cb-5b60c445a035)
