### ISSUE TITLE
Basic references are missing like System.Console, System.String

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#91]
Customer reported issue : https://github.com/dotnet/machinelearning-samples/issues/452

**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tbombach** [comment]
Duplicate of #65
