### ISSUE TITLE
GPU Service not found. Falling back to CPU AutoML Service. Training cancelled

### ISSUE THREAD

**Issue by huthido** [dotnet/machinelearning-modelbuilder#912]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

Output:
GPU Service not found. Falling back to CPU AutoML Service.
Training cancelled

**Comment by huthido** [comment]
GPU Service not found. Falling back to CPU AutoML Service.
Training cancelled

**Comment by longfinger65** [comment]
I have the same problem. Is there a solution now?

**Comment by LittleLittleCloud** [comment]
Sorry for the late reply
This error looks like a dup of #883, which will be fixed in the next release.  You can also fix this error by downloading the fix build from that thread.

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you still have question
