### ISSUE TITLE
"Train in Azure" on Next steps page should only show for image scenario

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#913]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by zewditu** [comment]
## Non-Image scenario
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/f7441d4d-cfb9-43b9-885b-6f2126d6dd38)
## No  Train in Azure
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/96713611-2748-4119-b3e9-b69f258ebaf3)

**Comment by vzhuqin** [comment]
Can repro this issue on Main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Text classification scenario:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/1e2e53f7-6fd7-4e09-bdfb-d3925cb20f10)
Value prediction scenario:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e86f5978-3397-488b-887a-21072fa5d1be)
Recommendation scenario:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/56205710-7f7e-4081-9328-50ca1bfdf4c6)

**Could you help to confirm whether should have "Train in Azure" for Object detection scenario?**
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/771aa252-124b-42c7-9ccf-b081b7bb5f66)

**Comment by vzhuqin** [comment]
This issue not repro on Main branch: 
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Now only Image Classification and Object detection scenarios have "Train in Azure" on Next steps page.

Object detection:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/591f667e-2549-40e1-bbdb-d07b9f742458)
Image classification Local (CPU):
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/452990a2-f859-40e7-ba43-54831275c73a)
Image classification Azure:
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/f51e5c6c-dec5-4b94-ab03-c9d852e6fed5)
Text classification Local (CPU):
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b508afd3-1b28-47bb-b6e3-1678d05f49b5)
Value prediction Local (CPU):
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b66f3ff6-9a79-45a1-8341-66f51aa4389f)
Recommendation Local (CPU):
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/33886cc7-0d5d-467b-b282-3f4f79866c35)
