### ISSUE TITLE
Error Adding Model Builder to a project (cannot load system.valuetuple'2' from mscorelib

### ISSUE THREAD

**Issue by ragsta** [dotnet/machinelearning-modelbuilder#914]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.0
 - Visual Studio Version 2017

**Describe the bug**
Visual studio fail when try to Add Artificial intelligence to a project

**To Reproduce**
I've created a new .net core 2.0 console application,
set the project destination platform to x64 
added the nuget package for ml.net framework v1.5.1
try to add "Artificial intelligence to the project".
At this point the operation fail with message:
Cannot load System.valuetuple'2'

**Screenshots**
![image](https://user-images.githubusercontent.com/12233725/88311897-c4e98d80-cd11-11ea-92bf-47e66000b5c1.png)

![image](https://user-images.githubusercontent.com/12233725/88311666-79cf7a80-cd11-11ea-81ed-f36be81b4c09.png)

**Comment by LittleLittleCloud** [comment]
Thanks for the feedback, this is the first time we see this issue, we will take a look.

In the meanwhile, could you try open modelbuilder on VS2019 as well to see if the problem still exists? Thanks

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you have more questions.
