### ISSUE TITLE
Tensorflow exception triggered while loading model.

### ISSUE THREAD

**Issue by uirty** [dotnet/machinelearning-modelbuilder#915]
ML.NET Model Builder (Preview) Version 16.1.0.2027905
Microsoft Visual Studio Community 2019 Version 16.6.5

When I use [ML.NET Model Builder] and [ML.NET Teaching Courses] to learn image classification...
The same error occurred.
https://docs.microsoft.com/zh-tw/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning
https://docs.microsoft.com/zh-tw/dotnet/machine-learning/tutorials/image-classification

Tensorflow exception triggered while loading model.

Select Create a new project from the Visual Studio 2019 start window.
Choose the C# Console App (.NET Core) project template.
Change the project name to TestImageClassification.
Make sure Place solution and project in the same directory is unchecked.
Create the project.
1.Right-click on the TestImageClassification in Solution Explorer and select Add > Machine Learning.
2.In the Model Builder Scenario screen, select the Image Classification scenario
3.Download and add data  [Images.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4970566/Images.zip)

4.
CPU: Intel(R) Core(TM)2 Duo CPU     E7200  @ 2.53GHz
Memory : 8 GBytes
Local training

Log file:[6fd732ca-a518-4c9e-bfc0-a48a67e444b1.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4970571/6fd732ca-a518-4c9e-bfc0-a48a67e444b1.txt)

**Comment by LittleLittleCloud** [comment]
Looks like the model is not loading correctly, could you go to %temp%/MLNET/ and delete `resnet_v2_50_299.meta` and run again? This step will remove the old model and download the new one from official website.

In the meanwhile, your CPU also looks pretty old, and it's likely that tensorflow is not support on your mode.

**Comment by uirty** [comment]
> Looks like the model is not loading correctly, could you go to %temp%/MLNET/ and delete `resnet_v2_50_299.meta` and run again? This step will remove the old model and download the new one from official website, please let me know if it works

Thanks for replying! The result is the same.
Log file:[e9c1ab87-a99d-4ca2-97c9-ebb0995629bc.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5021052/e9c1ab87-a99d-4ca2-97c9-ebb0995629bc.txt)

**Comment by uirty** [comment]
delete resnet_v2_50_299.meta
Thanks for replying! The result is the same.

 I can only try to get a new computer, but no money ...... ...... Hey Hey...

    在 2020年8月4日 星期二 上午01:38:48 [GMT+8]， Xiaoyun Zhang<notifications@github.com> 寫道：  
 
 


Looks like the model is not loading correctly, could you go to %temp%/MLNET/ and delete resnet_v2_50_299.meta and run again? This step will remove the old model and download the new one from official website.

In the meanwhile, your CPU also looks pretty old, and it's likely that tensorflow is not support on your mode.

**Comment by LittleLittleCloud** [comment]
Does your cpu supports avx instruction? If not the train will fail, because the version of tensorflow modelbuilder uses is prebuilt using avx instruction.

**Comment by uirty** [comment]
My cpu does not have avx instruction set, can I only buy a new computer to solve the problem?2020年8月5日 02:10，Xiaoyun Zhang <notifications@github.com>寫道：
Does your cpu supports avx instruction? If not the train will fail, because the version of tensorflow modelbuilder uses is prebuilt using avx instruction.

**Comment by LittleLittleCloud** [comment]
Yeah it seems that you have to get a new computer for image classification.
