### ISSUE TITLE
Input Value Type Incorrectly Interpreted 

### ISSUE THREAD

**Issue by bizbizzz** [dotnet/machinelearning-modelbuilder#919]
**System Information (please complete the following information):**
 - Model Builder Version: ml.net CLI
 - Visual Studio Version 8.6.7 for Mac

**Describe the bug**
Want the ability to override what ML.net guessed as the column type. 
Interpreted float value with very little variance as a string. 

**Expected behavior**
Want the ability to override what ML.net guessed as the column type.

**Comment by LittleLittleCloud** [comment]
This sounds like a bug in AutoML.Net, could we have your dataset if may? Or one of the example of mis-interpreted float value?

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it had you have any questions.
