### ISSUE TITLE
Model Builder Error

### ISSUE THREAD

**Issue by LeechFilcher** [dotnet/machinelearning-modelbuilder#920]
**System Information (please complete the following information):**
 - Model Builder Version: Visual Studio Model Builder
 - Visual Studio Version: Visual Studio Community 2019 16.6.5

**Describe the bug**
The Modelbuilder Fails on training an Image Model, with this error:
Tensorflow exception triggered while loading model.
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 147

**To Reproduce**
1. Select Image Classification
2. Select your Initial Dataset to train with
3. Click on Train
4. Error is produced and training fails.

**Expected behavior**
For the Training to finish.

**Additional context**
This works on my Work Computer but not the Server it is supposed to be trained on, could this be a hardware requirement problem? Are there any hardware requirements for the training to be possible?

**Comment by LittleLittleCloud** [comment]
looks like a dup of #915 
It's likely that if your server's CPU mode is too old, tensorflow might not support that. But that occasion is rare. The image training should work on most of hardware.

Could you try first remove the old resnet_v2_50_299.meta model and train again to see if error disappear? You can find instruction on how to do it from #915

**Comment by LeechFilcher** [comment]
The CPU is roughly 10 years old, these are the important specifications of the server:

2x Intel XEON X5650
136 GB of Memory
GTX 560

Local training and recognition both fail. Recognition fails with error:
"The program '[55144] Zuse.Api.exe' has exited with code -1073741795 (0xc000001d) 'Illegal Instruction'."
I'm guessing this is an issue with AVX instructions? Is there some kind of hardware requirements/recommendations 
I could follow for renting/buying a new machine?

**Comment by LittleLittleCloud** [comment]
It might be, ModelBuilder uses SciSharp.TensorFlow.Redist v1.14.0 for tensorflow training, which is a .net bind to tensorflow v1.14.0 and is prebuilt using AVX instructions. So if your CPU doesn't support avx, the training will fail.

any CPU which supports avx instruction (which means almost all CPUs launched after 2011) should work for image classification. If not, you might need to rent/buy a new cpu for image training, sorry about that.

**Comment by LeechFilcher** [comment]
All good. I will then rent out another server and develop an API to handle it there. Thanks for your support, I'll close this ticket since it's resolved from my side.
