### ISSUE TITLE
Environment change from GPU to CPU doesn't start a CPU train. Same thing for changing from CPU to GPU (doesn't start a GPU train)

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#926]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.1.2038102
 - Visual Studio Version

**Describe the bug**
After launching a GPU train, if re-select CPU train, the train will still be running on GPU.

**To Reproduce**
- Pick image classification
- select GPU training and run
- go back to the environment and select CPU and run
- The train is still running on GPU

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
Duplicate https://github.com/dotnet/machinelearning-modelbuilder/issues/900, which has been verified by Jake.
