### ISSUE TITLE
When I Right-click on the project in Solution Explorer, Add > **Machine Learning**. options is unavailable.

### ISSUE THREAD

**Issue by msnatarajan** [dotnet/machinelearning-modelbuilder#930]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

When I Right-click on the project in Solution Explorer, Add > **Machine Learning**. options is unavailable.

![image](https://user-images.githubusercontent.com/52795404/89134598-e7d32900-d4eb-11ea-9f59-1bc5fe3a6ed3.png)

I have followed all previous steps. VS version is Microsoft Visual Studio Professional 2019
Version 16.6.5

**Comment by LittleLittleCloud** [comment]
Hi, could you go to `manage extension` -> `installed` and check if model builder is installed there？
You should see something like this:
![image](https://user-images.githubusercontent.com/16876986/89211776-2235d800-d577-11ea-8904-fb0adc93f444.png)

**Comment by msnatarajan** [comment]
Thank you, Xiaoyun for your quick response. You're right. I installed the
extension and it looks good now.

[image: image.png]

Thanks,

*Meenakshi Sundaram Natarajan*

**Comment by LittleLittleCloud** [comment]
Thanks, I'm going to close the issue because it's solved
