### ISSUE TITLE
exception with Azure image training

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#931]
![image](https://user-images.githubusercontent.com/10437687/89211422-a50a6300-d576-11ea-8402-d57fae4bb5ba.png)

Workspace info:
![image](https://user-images.githubusercontent.com/10437687/89211871-53aea380-d577-11ea-94b5-bee619594b36.png)

1. Select image classification
2. Select Azure training env, set up workspace with existing subscription, compute and default experiment name
3. Select Weather dataset
4. Start training
5. Get the Exception above
6. It looks like the training process continued after I closed out of dialog, but hasn't finished yet so not sure

**Comment by LittleLittleCloud** [comment]
dup of #927

**Comment by beccamc** [comment]
Dup bug is closed.
