### ISSUE TITLE
dataset w/o header not being loaded correctly

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#933]
![image](https://user-images.githubusercontent.com/10437687/89213137-7a6dd980-d579-11ea-9856-2d2cce9efc9f.png)

I used the yelp_labelled dataset; preview:

![image](https://user-images.githubusercontent.com/10437687/89213195-95404e00-d579-11ea-8c3e-b81330542f94.png)

**Comment by beccamc** [comment]
This looks correct now ![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/e4e1696c-c7d3-4213-8a53-0d702d2b181f)
