### ISSUE TITLE
Text classification & other local scenarios should not have Train in Azure next step

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#934]
![image](https://user-images.githubusercontent.com/10437687/89213837-932abf00-d57a-11ea-9492-4e58e30d209d.png)

For every scenario that only has a local option, let's remove the "Train in Azure" card from the Next Steps page

**Comment by beccamc** [comment]
Duplicate https://github.com/dotnet/machinelearning-modelbuilder/issues/913
