### ISSUE TITLE
I can't find Machine Learning button on the menu

### ISSUE THREAD

**Issue by walidnagga** [dotnet/machinelearning-modelbuilder#935]
![Capture d’écran (8)](https://user-images.githubusercontent.com/37023534/89271988-cc783300-d63d-11ea-8f29-441ce0e3372e.png)

![Capture d’écran (7)](https://user-images.githubusercontent.com/37023534/89271864-989d0d80-d63d-11ea-8e30-dbd783528d5b.png)

Thanks for your help!

**Comment by LittleLittleCloud** [comment]
Can you go to "manage extension" -> installed to see if modelbuilder is installed, the window should look like this:
![image](https://user-images.githubusercontent.com/16876986/89332423-38f82f80-d648-11ea-867b-6fb5f87c9f43.png)

**Comment by walidnagga** [comment]
Merci bien, le problème est résolu.

**Comment by LittleLittleCloud** [comment]
De rien mon ami, Fermez le problème car le problème est résolu
