### ISSUE TITLE
Reference SampleClassification.Model in consumeModelApp project

### ISSUE THREAD

**Issue by patilkunal** [dotnet/machinelearning-modelbuilder#938]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

In second last step the code 
```
var input = new ModelInput();
```
will not work since it does not know how to reference `SampleClassification.Model` directory. Or something it missing from the steps.

**Comment by LittleLittleCloud** [comment]
If the reference to `SampleClassification.Model` project is not added, you can simply go to the .csproj file of your host project and add the following line:

` <ProjectReference Include="..\SampleClassification.Model.csproj" />`

This line will add reference to your SampleClassification.Model project

**Comment by levis501** [comment]
More specifically, the following must be added to the `<Project>` tag
`  <ItemGroup>`
` <ProjectReference Include="..\SampleClassification\SampleClassification.Model\SampleClassification.Model.csproj" />`
`</ItemGroup>`

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it had you have any questions.

**Comment by AldebaranNapoli** [comment]
FIRST my error was 

/Software/myMLApp/consumeModelApp$ dotnet run
Progam.cs(2,7): error CS0246: Il nome di tipo o di spazio dei nomi 'SampleClassification' non è stato trovato. Probabilmente manca una direttiva using o un riferimento all'assembly. [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]
Program.cs(2,7): error CS0246: Il nome di tipo o di spazio dei nomi 'SampleClassification' non è stato trovato. Probabilmente manca una direttiva using o un riferimento all'assembly. [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]
Program.cs(6,11): error CS0101: Lo spazio dei nomi 'consumeModelApp' contiene già una definizione per 'Program' [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]
Program.cs(8,21): error CS0111: Il tipo 'Program' definisce già un membro denominato 'Main' con gli stessi tipi di parametro [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]

I changed the consumeModelApp.csproj folowing your instructions 

like this

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SampleClassification\SampleClassification.Model\SampleClassification.Model.csproj" />
 </ItemGroup>
</Project>

and when i launch dotnet gives me now this errors only

/Software/myMLApp/consumeModelApp$ dotnet run
Program.cs(6,11): error CS0101: Lo spazio dei nomi 'consumeModelApp' contiene già una definizione per 'Program' [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]
Program.cs(8,21): error CS0111: Il tipo 'Program' definisce già un membro denominato 'Main' con gli stessi tipi di parametro [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]

La compilazione non è riuscita. Correggere gli errori di compilazione e ripetere l'esecuzione.
