### ISSUE TITLE
 Error performing the following exercise https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data

### ISSUE THREAD

**Issue by rsiles** [dotnet/machinelearning-modelbuilder#939]
en Microsoft.ML.AutoML.ColumnTypeInference.GetAndValidateLabelColumn(Arguments args, IntermediateColumn[] cols)
   en Microsoft.ML.AutoML.ColumnTypeInference.InferTextFileColumnTypesCore(MLContext context, IMultiStreamSource fileSource, Arguments args)
   en Microsoft.ML.AutoML.ColumnInferenceApi.InferColumnTypes(MLContext context, TextFileSample sample, ColumnSplitResult splitInference, Boolean hasHeader, Nullable`1 labelColumnIndex, String label)
   en Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   en Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParamater config, ColumnInformation columnInformation)
   en Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() en /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:línea 112

**Comment by beccamc** [comment]
@rsiles Sorry you ran into this problem! To confirm, you were using the Wikipedia detox dataset found in our docs? What language is your Visual Studio set to?

**Comment by rsiles** [comment]
Hello Becca, I am using C # in Spanish.

**I am using this data:** 
https://raw.githubusercontent.com/dotnet/machinelearning/master/test/data/wikipedia-detox-250-line-data.tsv

**I am attaching information from my visual studio:**

Microsoft Visual Studio Community 2019
Versión 16.7.0
VisualStudio.16.Release/16.7.0+30330.147
Microsoft .NET Framework
Versión 4.8.04084

Versión instalada: Community

Administrador de paquetes NuGet   5.7.0
Administrador de paquetes NuGet de Visual Studio. Para obtener más información acerca de NuGet, visite https://docs.nuget.org/

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
Para obtener más información, visite https://www.asp.net/

Azure Functions and Web Jobs Tools   16.7.532.28833
Azure Functions and Web Jobs Tools

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Extensión IntelliCode   1.0
Información detallada de la extensión Visual Studio IntelliCode

Extensiones de herramientas de contenedor de Visual Studio (versión preliminar)   1.0
Vea, administre y diagnostique contenedores en Visual Studio.

Herramientas comunes de Windows Azure   1.10
Ofrece servicios comunes para su uso con los servicios móviles de Microsoft Azure y Microsoft Azure Tools.

Herramientas de Azure App Service v3.0.0   16.7.532.28833
Herramientas de Azure App Service v3.0.0

Herramientas de C#   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
Los componentes de C# utilizados en el IDE. En función del tipo de proyecto y la configuración, se podría utilizar una versión diferente del compilador.

Herramientas de entrega continua de Microsoft para Visual Studio   0.4
Configuración simplificada de las canalizaciones de Azure DevOps desde el IDE de Visual Studio.

Herramientas de TypeScript   16.0.20702.2001
Herramientas de TypeScript para Microsoft Visual Studio

Herramientas de Visual Basic   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
Los componentes de Visual Basic utilizados en el IDE. En función del tipo de proyecto y la configuración, se podría utilizar una versión diferente del compilador.

Herramientas de Visual F# 10.10.0.0 para F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Herramientas de Microsoft Visual F# 10.10.0.0 para F# 4.7

Microsoft Azure Tools   2.9
Microsoft Azure Tools para Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools para contenedores   1.1
Desarrolle, ejecute y valide sus aplicaciones de ASP.NET Core en el entorno de destino. Presione F5 para ejecutar la aplicación directamente en un contenedor con opción de depuración, o bien presione CTRL + F5 para editar y actualizar la aplicación sin necesidad de recompilar el contenedor.

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

Paquete del host de adaptador de depuración de Visual Studio Code   1.0
Capa de interoperabilidad para el hospedaje de adaptadores de depuración de Visual Studio Code en Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62007.09200
Microsoft SQL Server Data Tools

Visual Studio Tools para contenedores   1.0
Visual Studio Tools para contenedores

VisualStudio.DeviceLog   1.0
Información sobre el paquete

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.440 (d16-7@358f3c6)
Extensión de Visual Studio para habilitar la implementación de Xamarin.iOS y Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Extensión de Visual Studio para habilitar las herramientas de Xamarin Designer en Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.0.3 (d16-7/aca845b)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f


Xamarin.iOS and Xamarin.Mac SDK   13.20.2.2 (817b6f72a)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by beccamc** [comment]
@rsiles Sorry for the delay. 

1. What version of Model Builder are you on? You can find this by checking the extension manager. 
2. Did you select "Sentiment" as the column to predict?

I've changed my VS to Spanish and am not getting a repro of this problem. My wikipedia dataset is able to train. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c638a759-60d7-4af7-bc13-9ce2f1f542c5)

**Comment by beccamc** [comment]
@rsiles Any update on the above questions?

**Comment by beccamc** [comment]
@rsiles We're re-written our data processing and removed the code you were getting an error from. I would update and try again. If the problem is still there ping me or re-open this issue.
