### ISSUE TITLE
Model Builder throws Data Error when using a dataset without header

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#940]
**Model Builder Version**: 053658f6dd7af3f7493e198f54d082b4f96b02f5
**Visual Studion Version**: VS2019

**Bug description**
Model Builder throws data error if the dataset doesn't have header

**Steps to Reproduce**
- select the example dataset
- model builder throws data error

![image.png](https://images.zenhubusercontent.com/5c1c0052c50615756d6b573e/f8316c46-6a5e-41ef-9877-da68facf3793)

PS:
there should be a space between data error and error msg too

[Salvinisentiment.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5053051/Salvinisentiment.txt)

**Comment by briacht** [comment]
I also noticed that even when my dataset was read in correctly in the data preview:

![image](https://user-images.githubusercontent.com/10437687/90423437-4e6e5000-e071-11ea-8332-c4d50646153c.png)

The generated ModelInput.cs is not correct:

![image](https://user-images.githubusercontent.com/10437687/90423482-6219b680-e071-11ea-899f-8178d0906d05.png)

**Comment by zewditu** [comment]
Validated
