### ISSUE TITLE
System.TypeInitializationException: 'The type initializer for 'ConsoleApp8ML.Model.ConsumeModel' threw an exception.'

### ISSUE THREAD

**Issue by SrisuwanPonson** [dotnet/machinelearning-modelbuilder#941]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
System.TypeInitializationException: 'The type initializer for 'ConsoleApp8ML.Model.ConsumeModel' threw an exception.'

FileNotFoundException: Could not load file or assembly 'Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

**Comment by beccamc** [comment]
Are your project using .NET Full Framework?

There is a bug in the .NET Full Framework non-SDK-style project format. We are pursing a permanent fix with the .NET team. 
 
To get unblocked, upgrade your .NET Framework project to use the [SDK-style](https://docs.microsoft.com/en-us/dotnet/standard/frameworks), or start a new project using .NET Core. Checkout this [blog ](https://www.hanselman.com/blog/UpgradingAnExistingNETProjectFilesToTheLeanNewCSPROJFormatFromNETCore.aspx) by Scott Hanselman for more help.
 
If you can't upgrade to the SDK-style, use the following to get unblocked with the non-SDK-style project format..

1. Set the target platform to x64
`<PlatformTarget>x64</PlatformTarget>`
 
2. Add a package reference to your project for [Microsoft.ML](https://www.nuget.org/packages/Microsoft.ML) (latest version) 
`<PackageReference Include="Microsoft.ML" Version="1.5.0-preview" />`

**Comment by SrisuwanPonson** [comment]
thank I just found I build console application for .NET frame work , not .NET CORE

**Comment by luronumen** [comment]
HI Guys,

Any news about this issue?
I am facing the same issue for using ML.NET in my .NET Framework project.

Best Regards,
Luciano

**Comment by beccamc** [comment]
@luronumen Did you try to upgrade your project to SDK Style project? [Here ](https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#runtime-error-in-code-systemiofilenotfoundexception-could-not-load-file-or-assembly-microsoftmldata)are a few more troubleshooting tips.

**Comment by luronumen** [comment]
Hi @beccamc 

Thank you very much for your prompt reply!

I tried to migrate the _packages.config_ file in my project to _Package Reference_ but after that the **Basler.Pylon** namespace  related with the **Basler.Pylon.NET.x64** NuGet package is not recognized.

Package reference before upgrade:

        <Reference Include="Basler.Pylon, Version=1.2.0.0, Culture=neutral, PublicKeyToken=e389355f398382ab, processorArchitecture=AMD64">
          <SpecificVersion>False</SpecificVersion>
          <HintPath>..\..\packages\Basler.Pylon.NET.x64.6.2.0.18677\lib\native\Basler.Pylon.dll</HintPath>
        </Reference>

Package reference after update

    <PackageReference Include="Basler.Pylon.NET.x64">
      <Version>6.2.0.18677</Version>
    </PackageReference>

do you know how to fix it?

Thanks in advance,
Luciano

**Comment by JakeRadMSFT** [comment]
@luronumen - I only have a guess. For this project - how are you building it Any CPU or x64 only? 

You might need to set it to specifically build x64 since the targets file in the NuGet has a conditional 

Copied from the NuGet:
``` 
<ItemGroup Condition="'$(Platform)' == 'x64'">
      <Reference Include="Basler.Pylon">
         <HintPath>$(MSBuildThisFileDirectory)..\lib\native\Basler.Pylon.dll</HintPath>
      </Reference>
  </ItemGroup>
```

**Comment by luronumen** [comment]
HI @beccamc and @JakeRadMSFT 

I got to upgrade my .NET Framework project to use the SDK-style but now I am facing these two issues:
1. When I build for the x64 platform the following warning is showed:
`ALINK : warning AL1073: Referenced assembly 'mscorlib.dll' targets a different processor`
2. My Pre Build Event stop to work with the following error:
`The command "..\PLUGINS\ADB\adb.exe kill-server 2>NUL" exited with code 3.`

For the first issue that I mentioned I used the following project instruction that it is no longer working for the SDK-style:
`<TargetFrameworkSDKToolsDirectory Condition=" '$(PlatformTarget)' == 'x64'">$(TargetFrameworkSDKToolsDirectory)\$(PlatformTarget)\</TargetFrameworkSDKToolsDirectory>`

My Pre Build Event instruction that stop to work is that:
`<PreBuildEvent>$(ProjectDir)..\PLUGINS\ADB\adb.exe kill-server 2&gt;NUL</PreBuildEvent>`

Do you know how to fixed these issues?

Thank you very much for your support!
Best Regards,
Luciano
