### ISSUE TITLE
How  do I set up my local GPU for training?  link does not work 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#942]
**Model Builder Version**: 	16.1.1.2041102
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
The link break 

**Steps to Reproduce**
1. _select  image classification scenario 
2. select Local(GPU) in environment tab
3. Click "How  do I set up my local GPU for training?" link 

**Expected Experience**
the right documentation should be displayed about how to set local GPU for training. 
**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/10198583-f6ac-418c-94f5-bfe4d32147bb)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
@briacht Did you update the forward link?

**Comment by briacht** [comment]
https//aka.ms/vsmbgpu
