### ISSUE TITLE
Toxic should be 1 right? why become true

### ISSUE THREAD

**Issue by SrisuwanPonson** [dotnet/machinelearning-modelbuilder#943]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by beccamc** [comment]
Thanks for reporting @SrisuwanPonson! What version on Model Builder are you on? On our newest version 16.1.1.2041102 it shows 1/0 results 

![image](https://user-images.githubusercontent.com/9122518/90441254-411b8a80-e09e-11ea-89ab-a3495bca1b2b.png)

**Comment by beccamc** [comment]
Did this solve the problem?

**Comment by SrisuwanPonson** [comment]
Yes
