### ISSUE TITLE
Wrong next step for  Auto ML  supported scenario.

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#944]
**Model Builder Version**: 	16.1.1.2041102
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**

**Steps to Reproduce**
1 Select  Text classification  from scenario page 
2.  Select data from a file 
3. Train
4. evaluate
5. Genera code
6. Click  next step button 

**Expected Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/f201aa74-e72d-4b78-b8b8-947e3eaf009d)

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/c882fab0-f6f8-44e2-aa05-f5ae4af77d21)_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
This is if you click the "Next step" button instead of using the left navigation

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/17f415f1-a9c1-4832-9900-57ff86432241)

**Comment by beccamc** [comment]
Per chat with Bri, will put together hot fix end of week or early next week. I'll look to see if there are other small bugs we want to fix. Bri will check how many people have upgraded the extension.
