### ISSUE TITLE
Image training error with small dataset

### ISSUE THREAD

**Issue by gocool67** [dotnet/machinelearning-modelbuilder#945]
Value cannot be null.
Parameter name: source

![image](https://user-images.githubusercontent.com/34451667/89977926-f529a980-dc89-11ea-8ab5-f8cef8ae7da8.png)

**Comment by beccamc** [comment]
@gocool67 Sorry you've run into this problem. Quick question, are you using only one image example per training class? Or training only one class? 

We've seen this before due to very small number of images per class.

**Comment by beccamc** [comment]
@gocool67 Any luck with adding additional images?

**Comment by gocool67** [comment]
Sorry to late reply,
May be you right but there is not one image but small scale of images, I mean 20+ images over there
I will try with more images soon

**Comment by gocool67** [comment]
I am try create solutions on lion image tracking
But I not able to find image of lion in large numbers

**Comment by beccamc** [comment]
Do you only have one class - meaning do you only have one folder of images? Is "Lion" the only class you're trying to identify?

**Comment by beccamc** [comment]
@gocool67 Any update here? Are you using more than one class (more than just Lion)?

**Comment by gocool67** [comment]
I am using lion and lioness, and apart from this my definition is indentify
lion, so there is on folder my be

Like unique lion from several images

You got my point ?

**Comment by beccamc** [comment]
@gocool67 Does your data look like this? ![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/e9b5edac-0d2c-4066-90c9-49fe68108bc4)

**Comment by gocool67** [comment]
No,

As human have finger print and facial difference to identify person to
person, I want to same on lion to help census of lion with out interfering
them life

Nice to make an interest on it, thanks

I approached to give name to lion like this
http://livingwithlions.org/mara/lions/akiki/

Thanks
Gokul

**Comment by beccamc** [comment]
@gocool67 Thanks for the additional info! I understand your scenario now. If you share you data or data source with me I can try it on my side.

**Comment by gocool67** [comment]
Sure,
I am requesting to some data providers but due to clearing it is in waiting
mode.

I ask few provides to give me data but still not positive response,I will
update on same and if they are not give then I am plan to download from my
own but it is not in as much.


Thanks
Gokul

**Comment by beccamc** [comment]
@gocool67 Sounds like a cool project! If you need help let me know.

**Comment by gocool67** [comment]
Sure, thanks
I sure need you in detail how I trained or modify module

Thanks
Gokul

**Comment by beccamc** [comment]
@gocool67 Can you share your data with me? If I have your images I can get a model.

**Comment by gocool67** [comment]
Sorry for the late reply,

But data providers are not responding

Thanks
GOKUL Hirani

**Comment by beccamc** [comment]
@gocool67 We've made a lot of changes since you filed this last August. A larger dataset should work. It if doesn't (or you need other help with this project) feel free to re-open this issue. Thanks!
