### ISSUE TITLE
The type or namespace name 'SampleClassification' could not be found

### ISSUE THREAD

**Issue by xysverma** [dotnet/machinelearning-modelbuilder#947]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Program.cs(2,7): error CS0246: The type or namespace name 'SampleClassification' could not be found (are you missing a using directive or an assembly reference?)

**Comment by LittleLittleCloud** [comment]
You need to add reference to your model project before running the code, here's an example
https://github.com/dotnet/machinelearning-modelbuilder/issues/938#issuecomment-673571607

**Comment by xysverma** [comment]
Adding tag as given in comment worked. Hopefully this will be added in Getting Started document so that people using mac can also use it seamlessly.  Thank a ton!

<ItemGroup>
<ProjectReference Include="..\SampleClassification\SampleClassification.Model\SampleClassification.Model.csproj" />
</ItemGroup>
