### ISSUE TITLE
Can't install ModelBuilder when having 2 versions of VS2017

### ISSUE THREAD

**Issue by alexulq** [dotnet/machinelearning-modelbuilder#95]
I have 2 versions of VS2017 installed. One SSDT and one Enterprise. I want to install Model Builder for the Enterprise one but it wants to install it also for SSDT which obviously doesn't work. 

`05/06/2019 10:38:54 - The extension with ID 'FE96D051-645F-4309-AE99-107A776B0DA2' is not installed to Visual Studio Enterprise 2017.
05/06/2019 10:38:55 - Extension cannot be installed to the following products due to missing prerequisites:
05/06/2019 10:38:55 - 	Microsoft SQL Server Data Tools for Visual Studio 2017 (SSDT)
05/06/2019 10:38:55 - 		-------------------------------------------------------
05/06/2019 10:38:55 - 		Identifier   : Microsoft.VisualStudio.Workload.NetCoreTools
05/06/2019 10:38:55 - 		Name         : .NET Core cross-platform development
05/06/2019 10:38:55 - 		Version      : [15.0,17.0)
05/06/2019 10:38:55 - 		Error        : The prerequisite specified does not exist
05/06/2019 10:38:55 - 
05/06/2019 10:38:55 - 		-------------------------------------------------------
05/06/2019 10:38:55 - 		Identifier   : Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1
05/06/2019 10:38:55 - 		Name         : .NET Core 2.1 development tools
05/06/2019 10:38:55 - 		Version      : [15.0,17.0)
05/06/2019 10:38:55 - 		Error        : The prerequisite specified does not exist`

**Comment by rustd** [comment]
@JakeRadMSFT can you please look into this or re-assign?

**Comment by JakeRadMSFT** [comment]
Looking into this. I have to follow up with VS Installer/Extension team.

**Comment by JakeRadMSFT** [comment]
History:
We used to require just the workload - "Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1".

- Fails when trying to install on Visual Studio that doesn't have workload.
- Fails when two versions are installed and only the one that has the workload is chosen for install.

Current State:
Now we require a specific build of VS2017

- Fails when trying to install on Visual Studio that isn't 15.9.12 or greater
- Fails when two versions are installed and only the one that is valid is chosen for install.

**Comment by JakeRadMSFT** [comment]
@alexulq, does this issue still reproduce for you? 

What versions of VS 2017 are you using? How did you install SSDT?

**Comment by JakeRadMSFT** [comment]
Resolving issue because of no response. If you're still running into this issue please re-open.

Thanks  for reporting!

Cheers,
Jake
