### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, culture=neutral publickeytoken=30ad4fe6b2a6aeed

### ISSUE THREAD

**Issue by fourfruit** [dotnet/machinelearning-modelbuilder#953]
I had a troubleshooting when I launched Model Builder.
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, culture=neutral publickeytoken=30ad4fe6b2a6aeed'. My Visual Studio Version was 2017 Community Version.

**Comment by fourfruit** [comment]
find issue

**Comment by beccamc** [comment]
@fourfruit Sorry you've run into this problem. We've identified the issue and are rolling out a fix in the next few days. We'll keep you posted as to when we release. 

Thank you for reporting!
