### ISSUE TITLE
StepTabs enum should be base 0

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#956]
StepTabs enum in ModelBuilderDataContext are base 1 (None = 0), while the actual tab controls are base 0. Is this discrepancy needed, and if it is can we make a generic conversion method so this is clearer?

**Comment by JakeRadMSFT** [comment]
@beccamc @LittleLittleCloud what should be done for this?

**Comment by beccamc** [comment]
Looking at this more I realized it's base 0 because we have a concept of **completed** tab. We need a base value before Scenario so we can indicate when Scenario tab is completed. We could maybe change to -1, but I'm not going to because if it ain't broke don't fix it.
