### ISSUE TITLE
Add "ML.NET Model Builder" to Extensions menu

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#96]
Currently the only way to access Model Builder is to create/open a .NET project, right-click the project, and select Add > Machine Learning.

It is possible to add options in the Extensions menu for downloaded extensions; as an example, see Telerik:
![image](https://user-images.githubusercontent.com/10437687/59126626-5df4f380-891a-11e9-9580-be3d98d9fcb2.png)

For another point of entry for Model Builder, add "ML.NET Model Builder" to the Extensions menu, which has the following options:
Add Machine Learning (Action: opens Model Builder in VS)
Model Builder Documentation (Action: opens aka.ms/modelbuilderdocs in browser)
Report an Issue (Action: opens aka.ms/modelbuilderissues in browser)
ML.NET Documentation (Action: opens aka.ms/mlnetdocs in browser)

**Comment by rustd** [comment]
This will be done as part of File-New work
