### ISSUE TITLE
Double "How do I format my Json"

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#963]
Nit: I find it weird that we say "How do I format my Json" twice. Should the second say More Information or something similar?

![image](https://user-images.githubusercontent.com/9122518/90700127-9eecd580-e24a-11ea-86fa-59364dabe28d.png)

**Comment by briacht** [comment]
Yeah that should say something like "Learn more about how to format your data for object detection." and then link to docs

**Comment by LittleLittleCloud** [comment]
@romalpani @briacht  The current footage note in the design doc for this format json window is like this
![image](https://user-images.githubusercontent.com/16876986/91074671-bf71b280-e5f1-11ea-8e6f-eb67a7520329.png)

Do we still want to stick with design doc on this case?

**Comment by romalpani** [comment]
I know that we were still not sure about the VoTT tool. But if I am not wrong, we are using the json that the VoTT tool generates. So, if that's still the case, then we can use the screenshot above. 

@briacht is there a different tool we want users to use (or recommend)?
