### ISSUE TITLE
Environment page - workspace error message

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#966]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.1.2041905
 - Visual Studio Version: 

**Describe the bug**
When I try to select an existing workspace + experiment or try to create a new workspace I get errors that basically dump the logs in the dialog. 

**To Reproduce**
1. Go to Model Builder
2. Click on Object Detection
3. Select Azure and set up an experiment

**Expected behavior**
If there's an error in creating / using existing workspace, we should warn the user in a more user-friendly manner in VS. Will need designs from design team.

**Screenshots**
![image](https://user-images.githubusercontent.com/48927690/90702072-26cce280-e23f-11ea-914a-8e2768927989.png)

![image](https://user-images.githubusercontent.com/48927690/90702083-30564a80-e23f-11ea-8a26-9e24abbed317.png)

**Additional context**

**Comment by LittleLittleCloud** [comment]
The root cause of it is user doesn't have enough permission to create a workspace, better error message should be thrown in model builder though

**Comment by romalpani** [comment]
Thank you for debugging this, @LittleLittleCloud .
I have created a design backlog ticket for this item.
