### ISSUE TITLE
Add "Machine Learning" menu item not present

### ISSUE THREAD

**Issue by easyt** [dotnet/machinelearning-modelbuilder#969]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows
Visual Studio Enterprise: 16.7.2

I enabled the "Enable ML.NET Model Builder" preview feature and restarted all instances of Visual Studio. I created a .NET Core console application (netcoreapp3.1). When I right-click the project and go to "Add", a child menu shows up without the "Machine Learning" menu item.

I found this issue https://github.com/dotnet/machinelearning-modelbuilder/issues/935, and installed the "ML.NET Model Builder (Preview)" extension manually. This fixed the issue, but I would have been stuck if I didn't search for someone else having the same issue.

**Comment by LittleLittleCloud** [comment]
Thanks for your feedback. Right now, Model Builder preview feature flag will still appear even if you don't install Model Builder. We will seek how to fix that in the future
