### ISSUE TITLE
automation in selecting best algorithm 

### ISSUE THREAD

**Issue by Jason2019June** [dotnet/machinelearning-modelbuilder#97]
**Describe the solution you'd like**

In project page it mentioned that " Model Builder leverages best in class automated machine learning (AutoML) to evaluate different models. ", could we make this AutoML available in lib or we can do this in code for automation?  

I have 20 different data files and different algorithms are recommended in code generated, but I have to do this for each manually on UI.  Although all 20 files have the same columns and label to predict, but the data are of different regions, single model doesn't work for all.  The AutoML is working great in recommending the best model, but how we can scale it?  

Thanks.

**Comment by greazer** [comment]
@Jason2019June, You can do the same operations using the mlnet CLI in a terminal script (i.e., batch or powerscript on Windows) https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/mlnet-cli?tabs=windows. I think this is what you're looking for.
