### ISSUE TITLE
not found Wikipedia detox dataset  

### ISSUE THREAD

**Issue by KiisMyGun** [dotnet/machinelearning-modelbuilder#972]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

https://raw.githubusercontent.com/dotnet/machinelearning/master/test/data/wikipedia-detox-250-line-data.tsv not found

**Comment by LittleLittleCloud** [comment]
Just tried the url you posted and it's valid. Can you try again.

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it had you have any quesitons
