### ISSUE TITLE
No workspaces experience isn't accessible 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#974]
I don't think this is accessible, as the user can't interact with that combo box. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/62e97dc4-dd0d-4500-b909-9ac2f1a60610)

**Comment by JakeRadMSFT** [comment]
Are we sure that the accessibility "cursor" can't get there? Maybe we can ask Dante?

**Comment by beccamc** [comment]
They'll find this in the Accessibility testing. Closing.
