### ISSUE TITLE
Can't find ML.NET "Machine Learning" in the ADD button on the project...

### ISSUE THREAD

**Issue by vrejohanian** [dotnet/machinelearning-modelbuilder#975]
after installing ML.NET in VS2019 (and enabling it in the options), tried to add to the project the scaffold of the machine learning, but can't find "Machine Learning" button inside the ADD to the project button.
![image](https://user-images.githubusercontent.com/44858268/91464038-1da0ce80-e85a-11ea-9edd-35580929ae3c.png)

**Comment by LittleLittleCloud** [comment]
Did you also select "install ML.Net ModelBuilder" when installing VS2019?

Seems to be a dup of #969

**Comment by vrejohanian** [comment]
Yes I installed ML.Net ModelBuilder (which is a preview).

**Comment by vrejohanian** [comment]
thank you @LittleLittleCloud , the problem was that I have to install the ML.NET ModelBuilder in a separate process from the VS2019 Extension Manager (beside the VS2019 Installer).
once i installed via the Extension Manager the problem was solved.

**Comment by LittleLittleCloud** [comment]
#954

**Comment by JakeRadMSFT** [comment]
#978
