### ISSUE TITLE
The last step of the guide for me is really hard to complete.

### ISSUE THREAD

**Issue by AldebaranNapoli** [dotnet/machinelearning-modelbuilder#977]
FROM HERE https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/generate-code

FIRST my error was

/Software/myMLApp/consumeModelApp$ dotnet run
Progam.cs(2,7): error CS0246: Il nome di tipo o di spazio dei nomi 'SampleClassification' non è stato trovato. Probabilmente manca una direttiva using o un riferimento all'assembly. [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]
Program.cs(2,7): error CS0246: Il nome di tipo o di spazio dei nomi 'SampleClassification' non è stato trovato. Probabilmente manca una direttiva using o un riferimento all'assembly. [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]
Program.cs(6,11): error CS0101: Lo spazio dei nomi 'consumeModelApp' contiene già una definizione per 'Program' [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]
Program.cs(8,21): error CS0111: Il tipo 'Program' definisce già un membro denominato 'Main' con gli stessi tipi di parametro [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]

I changed the consumeModelApp.csproj following your instructions and when i launch dotnet gives me now this errors only

/Software/myMLApp/consumeModelApp$ dotnet run
Program.cs(6,11): error CS0101: Lo spazio dei nomi 'consumeModelApp' contiene già una definizione per 'Program' [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]
Program.cs(8,21): error CS0111: Il tipo 'Program' definisce già un membro denominato 'Main' con gli stessi tipi di parametro [/home/dolphin/Software/myMLApp/consumeModelApp/consumeModelApp.csproj]

La compilazione non è riuscita. Correggere gli errori di compilazione e ripetere l'esecuzione.

Another question:
its normal that when i launch the Software/myMLApp/consumeModelApp$ dotnet add reference "../SampleClassification/SampleClassification.Model/SampleClassification.Model.csproj COMMAND i have always this sign (>) and the windows terminal open with the prompt?

(> and prompt)

and if i try to open the Program.cs file with an editor it gives me that's is busy with a process and i think is with dotnet add reference "../SampleClassification/SampleClassification.Model/SampleClassification.Model.csproj

**Comment by LittleLittleCloud** [comment]
Hi @AldebaranNapoli 
Could you share your directory tree view? It looks like for the second error, your solution has two Program.cs file with main function, and that confuses dotnet on which main to run.

**Comment by AldebaranNapoli** [comment]
├── consumeModelApp
│   ├── bin
│   │   └── Debug
│   │       └── netcoreapp3.1
│   ├── consumeModelApp.csproj
│   ├── obj
│   │   ├── consumeModelApp.csproj.nuget.dgspec.json
│   │   ├── consumeModelApp.csproj.nuget.g.props
│   │   ├── consumeModelApp.csproj.nuget.g.targets
│   │   ├── Debug
│   │   │   └── netcoreapp3.1
│   │   │       ├── consumeModelApp.AssemblyInfo.cs
│   │   │       ├── consumeModelApp.AssemblyInfoInputs.cache
│   │   │       ├── consumeModelApp.assets.cache
│   │   │       ├── consumeModelApp.csprojAssemblyReference.cache
│   │   │       ├── consumeModelApp.csproj.CoreCompileInputs.cache
│   │   │       └── consumeModelApp.csproj.FileListAbsolute.txt
│   │   ├── project.assets.json
│   │   └── project.nuget.cache
│   ├── Progam.cs
│   └── Program.cs
├── Salvinisentiment2.tsv
├── Salvinisentiment.csv
├── Salvinisentiment.tsv
└── SampleClassification
    ├── SampleClassification.ConsoleApp
    │   ├── ModelBuilder.cs
    │   ├── Program.cs
    │   └── SampleClassification.ConsoleApp.csproj
    ├── SampleClassification.Model
    │   ├── bin
    │   │   └── Debug
    │   │       └── netstandard2.0
    │   │           ├── MLModel.zip
    │   │           ├── SampleClassification.Model.deps.json
    │   │           ├── SampleClassification.Model.dll
    │   │           └── SampleClassification.Model.pdb
    │   ├── ConsumeModel.cs
    │   ├── MLModel.zip
    │   ├── ModelInput.cs
    │   ├── ModelOutput.cs
    │   ├── obj
    │   │   ├── Debug
    │   │   │   └── netstandard2.0
    │   │   │       ├── SampleClassification.Model.AssemblyInfo.cs
    │   │   │       ├── SampleClassification.Model.AssemblyInfoInputs.cache
    │   │   │       ├── SampleClassification.Model.assets.cache
    │   │   │       ├── SampleClassification.Model.csprojAssemblyReference.cache
    │   │   │       ├── SampleClassification.Model.csproj.CoreCompileInputs.cache
    │   │   │       ├── SampleClassification.Model.csproj.FileListAbsolute.txt
    │   │   │       ├── SampleClassification.Model.dll
    │   │   │       └── SampleClassification.Model.pdb
    │   │   ├── project.assets.json
    │   │   ├── project.nuget.cache
    │   │   ├── SampleClassification.Model.csproj.nuget.dgspec.json
    │   │   ├── SampleClassification.Model.csproj.nuget.g.props
    │   │   └── SampleClassification.Model.csproj.nuget.g.targets
    │   └── SampleClassification.Model.csproj
    └── SampleClassification.sln

**Comment by LittleLittleCloud** [comment]
Your consumeModelApp has two Program.cs (therefore two main functions) which confuses dotnet, could you delete one of them and try again?

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you have any questions
