### ISSUE TITLE
Machine Learning Option in VS 2019

### ISSUE THREAD

**Issue by Manoj-Prabu** [dotnet/machinelearning-modelbuilder#978]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

I couldn't able to find Machine Learning option under Add option in console application. Am I missing anything.

**Comment by JakeRadMSFT** [comment]
What version of VS 2019 do you have installed. Can you share a screenshot of the VS About screen under help?

Can you also start the "Visual Studio Installer" and share which workloads and components are installed?

**Comment by beccamc** [comment]
@Manoj-Prabu were you able to resolve this issue?

**Comment by beccamc** [comment]
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/c7b34b67-7a5e-4a84-afee-455408dd4ccb)
