### ISSUE TITLE
Can't run Model Builder properly because Cuda can't detect Visual Studio

### ISSUE THREAD

**Issue by Cariaga** [dotnet/machinelearning-modelbuilder#979]
![aditional Error](https://user-images.githubusercontent.com/9010504/91635718-51801d80-ea2d-11ea-8c52-a022388932ea.png)

Using

- Visual Studio 2019
- Model Builder 16.1.1.2041102

additional error
gpu training failed please check that your gpu is configured properly

**Comment by JakeRadMSFT** [comment]
You can continue without the cuda extension in VS. It's unrelated to Model Builder's GPU driver needs.

**Comment by Cariaga** [comment]
apparently it doesn't work without the proper cuda 
or there is an issue with my nvidia because i'm unable to access the control panel

other issue that i encountered
https://github.com/dotnet/machinelearning-modelbuilder/issues/906

Thanks to this info its **solved now**
https://github.com/dotnet/machinelearning-modelbuilder/issues/887

i had to install ML.Net Model Builder GPU Support along with ML.Net Model Builder.

to verify if its using the GPU is to look if gpu is 100% Memory usage
