### ISSUE TITLE
Data ErrorInput array is longer than the number of columns in this table

### ISSUE THREAD

**Issue by GaryMalk** [dotnet/machinelearning-modelbuilder#980]
I cannot import data from a csv file into ML.NET Builder.  The data has 11 rows.  Here is the CSV file:
[race.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/5146190/race.zip)

1. Launch VS 2019
2. Create new Console App C# .NET Core
3. Add Machine Learning
4. Select Value Prediction template
5. Environment = local CPU
6. Data: Select CSV file
7. Click drop down box to select Column to Predict

RESULT: Error message Data ErrorInput array is longer than the number of columns in this table
EXPECTED: To select a column

I actually have several CSV files and need to join them together to create a machine learning model to predict outcomes based on many inputs.  So the fact that this breaks on just a single file is troubling.

**Comment by JakeRadMSFT** [comment]
Sorry you're hitting this issue and thanks for reporting and sharing the file. I've never seen that error - I'll dig into it.

**Comment by scotthadley1968** [comment]
I have the same issue manifested itself today

**Comment by beccamc** [comment]
@GaryMalk Thanks for included your dataset! We've made a lot of improvements in this space. I just tested the provided file and it works. Please download the latest version and try again. 

@scotthadley1968 Can you upgrade to the latest version released 11/11/20 - 16.3.0.2056001? It may fix your problem.

**Comment by beccamc** [comment]
Any updates with the latest builds?

**Comment by beccamc** [comment]
This area has been completely re-written since August of last year. Please check your data again. Reopen and @ mention me if it still doesn't work. Thanks!
