### ISSUE TITLE
Advanced data options..

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#981]
- [ ] Replace data sources  type selector combo into radio buttons for text based scenarios 
- [ ]  Provide advanced options to enable the user 
                  -  column setting  (to enable users to choose purpose to each columns like category , ignore ... )
                   - data formating ( select  column separator and decimal separator 

Based on specifications : 
https://microsoft-my.sharepoint.com/:w:/p/brachtma/EflGo8r9PmtHo_FRuCho6IIBDFqHa17Pzbc3Ft0tzkDhSw?e=pIBQ11
https://www.figma.com/file/qFoQ4iC27jpNZb7CCuo7Hj/Model-Builder---RM?node-id=684%3A1746

**Comment by beccamc** [comment]
This has been validated in bashes.
