### ISSUE TITLE
ML.Net Model Build Error

### ISSUE THREAD

**Issue by jasonkriel26** [dotnet/machinelearning-modelbuilder#984]
Hi.
I am doing this tutorial:
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/scenario

Connected to a sql database and then selected a Table Name.
When selecting a table name i get this error:
![image](https://user-images.githubusercontent.com/70566244/91813049-5cf06600-ec32-11ea-9fab-594a32c81bb2.png)

**Comment by beccamc** [comment]
@jasonkriel26 Sorry you've run into this problem. We're got a fix for this ready and are hoping to ship this week. You can track the fix in this item - https://github.com/dotnet/machinelearning-modelbuilder/issues/970

As a work around, you can revert to the previous version of Model Builder (should be available from the Extensions menu).
