### ISSUE TITLE
Could not find feature column 'Features' Parameter name: inputSchema

### ISSUE THREAD

**Issue by zhudavh** [dotnet/machinelearning-modelbuilder#987]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version 16.7.2

**Describe the bug**
When I tried to perform a binary text classification for sentimental analysis with attached TSV file, I got this error

Training failed with the exception: System.ArgumentOutOfRangeException: Could not find feature column 'Features'
Parameter name: inputSchema
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.CheckInputSchema(SchemaShape inputSchema)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.GetOutputSchema(SchemaShape inputSchema)

By examing the attached TSV (txt) file, I could not see any issue with the TSV file

I have to rename the file to .TXT file since your web site only accept TXT file. 

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/25772247/92144994-27d44700-eddd-11ea-9e44-b782a9363af3.png)

[11290-memo.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5170114/11290-memo.txt)

**Additional context**

**Comment by LittleLittleCloud** [comment]
Looks like a bug in column inference.

It seems that Desc column has a lot of repetitive value, which makes column inference api in AutoML gives the wrong guess. I'll take a look.

**Comment by zhudavh** [comment]
Thanks for looking into this

David

**Comment by beccamc** [comment]
@LittleLittleCloud Yes, just tested this with the PROSE and it works! This fix will be going out with out October release.

**Comment by zhudavh** [comment]
Thanks a lot !

David

**Comment by beccamc** [comment]
@zhudavh This should be fixed in our latest release. Check it out when you get a chance and let me know if this is resolved. Thanks!

**Comment by zhudavh** [comment]
Yes  I just tested it and it is working now

Thanks

David
