### ISSUE TITLE
No way to generate projects again without re-training

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#992]
1. Train a model with Model Builder
2. Add projects to solution in Code step
3. Delete projects from solution
4. No way to re-add the projects:
![image](https://user-images.githubusercontent.com/10437687/92665120-97a17080-f2ba-11ea-9d04-6dc6fdd5b925.png)

@romalpani We will probably need to come up with something for this

**Comment by romalpani** [comment]
I've created a design backlog ticket for this issue.

**Comment by JakeRadMSFT** [comment]
Do we care about this after reentrancy?

**Comment by JakeRadMSFT** [comment]
We should make it save new code each time you save the designer.
