### ISSUE TITLE
ML.NET assembly error on ARM64 [Jetson Nano]

### ISSUE THREAD

**Issue by chunky** [dotnet/machinelearning-modelbuilder#994]
Specific error:
**Could not load file or assembly 'Microsoft.ML.ModelBuilder.AutoMLService, Version=16.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.**

System: NVIDIA Jetson Nano running latest everything from NVIDIA. Ubuntu 18.04.5 LTS , latest JetPack and fully updated.

chunky@ckjetson:/mnt/sup2rtam/digits_mlnet$ dotnet --version
3.1.402
chunky@ckjetson:/mnt/sup2rtam/digits_mlnet$ mlnet --version
16.2.0+511cc1082bef7a4bbb2f83ad88c1c425c932079c
chunky@ckjetson:/mnt/sup2rtam/digits_mlnet$ time mlnet image-classification --dataset digits_350001_400000 --name MillionDigitsClassification
Save Label File to /mnt/sup2rtam/digits_mlnet/digits_350001_400000/ImageLabel.tsv
Could not load file or assembly 'Microsoft.ML.ModelBuilder.AutoMLService, Version=16.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.

Dotnet installed per directions here: https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.402-linux-arm64-binaries [manually extract to home dir, and point PATH].  ML.NET installed per instructions here: https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install

Data file is likely irrelevant to issue, but it's the same data attached to this bug report: https://github.com/dotnet/machinelearning-modelbuilder/issues/880

Exact same data and workflow is working fine on my Intel desktop with Ubuntu 20.04

**Comment by LittleLittleCloud** [comment]
Thanks for the feedback, mlnet uses tensorflow.net to run image training, which currently doesn't have an arm version. 
To run it on arm, you will need to build your own arm binary. And replace that binary with the one carried by mlnet. This is a bit hacky, Since I didn't try it before and I don't have arm device at hand, I can't guarantee it will 100 % work though.

**Comment by chunky** [comment]
I found the same advice on some forum where someone had been asking after the same thing but for raspberry pi. 

I tried compiling it myself on my Jetson [using this guidance: https://github.com/dotnet/machinelearning/blob/master/docs/building/unix-instructions.md ], but got an error that the compiler didn't recognise the flag to enable SSE [because of course it didn't, because my compiler doesn't have SSE, because my chip doesn't]. That's where I gave up and went back to my intel desktop.

This was mostly an experiment to see if I could get my Jetson doing anything useful, since my original main reason to purchase it also fell down [the CPU is pretty lethargic, so my nontrivial model for reinforcement learning can't pump fast enough to feed the GPU everything it needs for effective RL].

While explicit ARM64 support in ML.NET would be great for me, my use case also works fine with desktops, so... _shrug_

**Comment by LittleLittleCloud** [comment]
update: after mlnet 1.9.0, arm64 should be supported for most trainers. However there's still a few trainers which are not support on arm64 platform, like LGBM and image classification

I'm going to close this issue as for now there's no roadmap or estimation on when to support arm64 for those trainers, nor is it under mlnet community's control on having them support arm64 or not.

So unfortunately if you want to train image classification on arm64 platform,, it won't work. But for other scenarios it should.
