### ISSUE TITLE
mlnet image-classification ignores --name parameter

### ISSUE THREAD

**Issue by chunky** [dotnet/machinelearning-modelbuilder#999]
**System Information (please complete the following information):**
$ mlnet --version
16.2.0+511cc1082bef7a4bbb2f83ad88c1c425c932079c
$ dotnet --version
3.1.402
$  lsb_release -d
Description:	Ubuntu 19.10

**Describe the bug**
Using mlnet, I would expect --name to do what it says: "Name for output project or solution to create. Default is SampleImageClassification.".

The parameter appears to be ignored and always create "SampleImageClassification"

**To Reproduce**
1. Run command: "mlnet image-classification --dataset ./digits_1_500 --name DigitsClassification"
2. Observe output:
...............
Generated C# code for model consumption: /home/chunky/src/mlnet_image_classification/SampleImageClassification/SampleImageClassification.ConsoleApp
Check out log file for more information: /home/chunky/.mlnet/log.txt
Exiting ...
...............

Also note that it created a project folder "SampleImageClassification", with similarly named stuff inside: SampleImageClassification.ConsoleApp  SampleImageClassification.Model  SampleImageClassification.sln

~/.mlnet/log.txt does not, anywhere, include the text "DigitsClassification"

**Expected behavior**
I would expect, in the example above, "DigitsClassification" to be the name of alll the things, instead of SampleImageClassification.

**Comment by LittleLittleCloud** [comment]
Thanks for your feedback, we will fix that soon

**Comment by LittleLittleCloud** [comment]
The code generator in mlnet cli is in a broken state because the old code gen only support AutoML.Net while we are randomly pick both AutoML to launch trial.

**Comment by vzhuqin** [comment]
Validate this issue on:

- dotnet tool list -g

mlnet 16.5.22

- dotnet --version

5.0.202

Data Set:
https://testpass.blob.core.windows.net/test-pass-data/weather.zip

**Steps:**
1. Download the dataset and copy the image folder: weather-small to folder: C:\999Validation\ 
2. Run commend: 
cd C:\999Validation
mlnet image-classification --dataset C:\999Validation\weather-small --name WeatherPrediction
3. Find the folder name "WeatherPrediction" is generated with some error, @LittleLittleCloud could you help to take a look?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/68965095-37e5-4b27-b169-b155334c3115)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/bac71fc6-fb2c-4ce6-a183-343a6805f1c9)

**Log:**
[https://app.zenhub.com/files/186917455/db31a326-4f4a-4629-8c37-103ab7af6f44/download](https://app.zenhub.com/files/186917455/db31a326-4f4a-4629-8c37-103ab7af6f44/download)

**Comment by LittleLittleCloud** [comment]
@vzhuqin 
Sure, that looks like a different issue, I'll open a new bug and close this one
